### ISSUE TITLE
la instrucción ApplyRegex no está funcionando

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#10]
la instrucción ApplyRegex no está funcionando correctamente, cuando antes funcionaba bien.

Esta es la instruccion del script:

ApplyRegex "^(?i)(NoHayRegistros)$" to the string "<<<Result>>>" and save as "ResRegex"

 

El log de la ejecucion me muestra:

16/04/2019 04:35:52 p. m. - Powershell IfRule.txt: Running

16/04/2019 04:35:52 p. m. - Powershell IfRule.txt : Result : NoHayRegistros

16/04/2019 04:35:52 p. m. - Powershell IfRule.txt : Success

16/04/2019 04:35:52 p. m. - ApplyRegex "^(?i)(NoHayRegistros)$" to the string "<<<Result>>>" and save as "ResRegex": Running

16/04/2019 04:35:52 p. m. - error: ApplyRegex "^(?i)(NoHayRegistros)$" to the string "<<<Result>>>" and save as "ResRegex" : Regex generate a null result creating an Error

16/04/2019 04:35:52 p. m. - ApplyRegex "^(?i)(NoHayRegistros)$" to the string "<<<Result>>>" and save as "ResRegex" : Error

 

"Regex generate a null result creating an Error" cuando no deberia ser asi.

Esto hace que, al estar la instrucción adentro de un Try / Catch, salga por el Catch cuando no deberia ser así. Hace un tiempo vimos este tema con Andres De La Cruz Rojas y había quedado solucionado, ¿Podrián revisarlo? 

Se cambio la Expresión Regular a la pedida por Andres (El detalle en Soporte del Teams) pero sigue dando error.

**Comment by FaustinoLechuga** [comment]
Te esta dando error por que estas aplicandole el regex a este string "<<>>" y pues no hay coinidencias, me podrias explicar que es lo que debe estar dentro del string? o que variable estas utilizando?

**Comment by MartinMedinaSTK** [comment]
Se ve que cuando pegue el código borro la variable.  Asi esta en el script: 
to the string "<<Result>>"

Lo que contiene la variable Result es lo que se ve en el log "NoHayRegistros".

**Comment by MartinMedinaSTK** [comment]
Lo vuelve a borrar... el string donde se aplica la regex es la variable Result.

**Comment by FaustinoLechuga** [comment]
Al parecer el error que tienes es que la variable Result no existe, o no se esta creando. Debido a esto en el log aun tienes el nombre de la variable y no el valor.

**Comment by MartinMedinaSTK** [comment]
16/04/2019 04:35:52 p. m. - Powershell IfRule.txt : Result : NoHayRegistros 

el valor de la variable es "NoHayRegistros"

**Comment by FaustinoLechuga** [comment]
Eso es lo que te regresa el powershell pero si en el script principal no existe la variable no hay manera que el powershell se la mande al script principal.
Solo hay que agregar esta intruccion antes de correr el powershell
DefineVariable type "string" as "Result"

**Comment by pabloreitanosofttek** [comment]
Hola! el issue tiene 11 días de apertura... ¿Cuándo es la fecha de fin?
¡gracias!
Saludos,
PR

**Comment by gantonioid** [comment]
Tiene “pending input” desde los mismos 11 días Pablo y no hubo respuesta ni se reportaron resultados de pruebas después de que se propuso definir una variable “Result” hace cuatro días... cierro por falta de actividad

**Comment by MartinMedinaSTK** [comment]
Tardaron mucho en responder (6 días) desde que cargue el issue hasta que me dijeron que el problema estaba en que faltaba definir la variable "Result", con lo cual en ese tiempo reemplace en el código todas las instrucciones applyRegex por IF, ya que cuando se desarrollo este bot el IF no existía y el applyRegex se usaba para "simular" un IF. Por este motivo es que, al cambiar el código, no puedo probar que definiendo la variable "Result" se soluciona el problema.

**Comment by pabloreitanosofttek** [comment]
Está OK que quede cerrado el issue, pero tengamos en cuenta a partir de ahora de poner para cuando lo necesitan... sin eso el equipo de Soporte no puede priorizar temas. 
¡gracias!
