### ISSUE TITLE
[EXCELLIA] Error al dar click en un botón (anteriomente funcionando) WEB2

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#100]
En la página https://www.telecreditobcp.com/tlcnp/ al llegar al momento de hacer click en el botón Exportar:
![imagen](https://user-images.githubusercontent.com/50331739/57809519-fe049600-773b-11e9-88ad-96c161bad774.png)
Me tirar error pero anteriormente funcionaba correctamente, probe cambiando a dynamic, poniendo el selector completo. Pero no me funciona.Adjunto el log, en caso de que necesiten los datos de ingreso a la web, se los paso por email.
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3184437/log.txt)
Muchas gracias!
Urgencia: Alta 16.05

**Comment by carlosortiz632** [comment]
Hola, te contacté por Teams para revisarlo a fondo.

viendo el log, veo que tienes un context antes de hacer click en Exportar, pero no encuentro razón de esta instrucción. Tal vez poniendo un `EndContext` antes de dar el click en exportar pueda solucionar todo.

De todos modos, quedo al pendiente.

**Comment by RickProductivity** [comment]
Gracias Charly

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarianelaDuarte** [comment]
Buen día, no me llegó nada por Teams, la idea es que este dentro del context porque esta acción se realiza si se encuentra cierta palabra en el context, yo  en el codigo lo estoy forzando para que si o si pase por allí, anteriormente corria perfectamente. 
Probé fuera del context y funciona la instrucción, pero yo necesito que descargue solo si encuentra una palabra en el context, luego de esas pruebas concluyo que el problema viene del context.

**Comment by carlosortiz632** [comment]
¿Qué elemento es el que estás buscando? Igual existe la función de ElementExists que puede funcionar mejor para este caso.

**Comment by MarianelaDuarte** [comment]
Necesito, descargar el archivo solo si en la grilla(imagen de referencia)  en la columna "descripción de operación" contiene Efectivo VA o Efectivo VL. Es por eso que había elegido context.
![imagen](https://user-images.githubusercontent.com/50331739/57855308-bc69fe80-77c0-11e9-9920-0e3defdc723c.png)
Yo lo force a que si en el context habia una e para que siempre pase por ese camino.

**Comment by carlosortiz632** [comment]
El `dynamic` es CASE SENSITIVE, por lo que poniendo solo `efectivo` no arrojaría ningún resultado. Estoy haciendo pruebas y el `Context` no es la mejor de las opciones para este problema. Recomendaría mucho usar la función `ElementExists` en conjunto con un If. Es más lógico verlo de esa manera y más entendible al momento de leer el código.
`Web2 ElementExists in dynamic="EFECTIVO" save as "variable"`.


En cuanto a por qué no funciona al poner una `e` en dynamic. Lo que pasa es que, seguramente, se está encontrando un elemento inválido para el context. Esto no marca error, pero ya estoy encargándome de que esto no suceda. Mientras, recomendaría la opción de arriba que es el caso de uso correcto.

Saludos.

**Comment by MarianelaDuarte** [comment]
Cambie Context por ElementExists y ya puedo hacer que el flujo del proceso funcione correctamente, igualmente algo anda mal en Context.. 
Cierro el Issue de todas formas, muchas gracias Carlos.
Saludos
