### ISSUE TITLE
WEB2 y procesos programadas

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#101]
Los procesos programados ( e incluso normales) suelen fallar la primera vez que ejecutan algo de web2, esto hace que las tareas programadas con web2 fallen sin opcion a completarse y obliga a programar dos tareas seguidas para preveer la falla.

No tengo capturas de pantalla ni nada, pero durante la primer ejecucion del dia de una instruccion web2, simplemente da error y en la siguiente funciona normal.

**Comment by carlosortiz632** [comment]
Cuando puedas, podrás proporcionar el mensaje de error que aparece en el log.txt y el error.txt? Este problema viene desde Turing, pero no hemos podido replicarlo para poder solucionarlo. En cuanto te vuelva a pasar podrías compartirmelo?

Gracias!

**Comment by gantonioid** [comment]
Se envió versión 20190516T0457 para esperar al motor de browpet para asegurar que esté activo antes de empezar la ejecución de instrucciones Web2.

**Comment by NehuenV** [comment]
la actualizacion funciona bien y ya no falla la primer ejecucion.

**Comment by gantonioid** [comment]
Perfecto, cierro issue
