### ISSUE TITLE
Consulta: Necesito seleccionar los valores de un rango de celdas de un excel y pegarlos en una grilla de SAP

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#102]
Existe alguna función de Excelium que nos permita seleccionar valores de un rango de celdas?
Los pasos que debo hacer son: 

- Filtro el excel por una columna (columna R = OK)
- Selecciono los valores del resultado del filtro anterior (columna Q) y los copio en el portapapeles (Ctrl+C)
- Ingreso en una transacción de SAP y en los filtros pego los datos obtenidos del excel.
![image](https://user-images.githubusercontent.com/49758327/57861458-0822a500-77cd-11e9-8f3b-9964e3e3d3c5.png)

Gracias

**Comment by gantonioid** [comment]
Puedes filtrar lo que quieres con ApplyFilter, usando la sintaxis que termina con 

> and copy their value on "<SaveVariable>"

Pero la segunda parte de copiar en portapapeles y pegar en SAP no la tenemos tal cual... podrías intentar:

1. ApplyFilter que retorna `List<List<string>> `[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter](url)
2. Luego, iterar e ir construyendo una lista con [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/AddToList](url)
3. Pasar esa lista al portapapeles con [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/LoadVarToClipboard](url)
4. Luego pegar con ctrl+v Titanium Type ^(v) o si hay una específica de SAP Reader no lo sé @eradgg

**Comment by MartinMedinaSTK** [comment]
Toño, cuando decis iterar e ir construyendo una lista, estas hablado de recorrer la hoja filtrada con un foreach?

**Comment by gantonioid** [comment]
Sí, en ApplyFilter se hace el filtro y ya se lee guardando en una variable.
Esa variable es la que iteras con foreach para ir construyendo una lista que vas a cargar al portapapeles y luego usarla en SAP.

Aclaración... esto es una suposición, desconozco si esta lista se pueda pegar después en SAP @eradgg

**Comment by eradgg** [comment]
@MartinMedinaSTK el SAP por lo general tiene un botón para pegar del porta papeles. sería dar click en ese botón y ya pegaría la lista generada.  si no existe sería buscar una alternativa, podría ser lo que comenta @gantonioid ^(v) sería usar la instrucción SAP ElementFocus para posicionar el cursos en ese elemento y se envía el ctrl + v

**Comment by MartinMedinaSTK** [comment]
Claro, el usuario se para en la grilla y hace control + V y pega todo lo selecionado en el excel, yo creo que con eso no voy a tener problema. Para mi el punto es tener los datos del excel en el portapapeles, pero voy a seguir los pasos que me paso Toño. Gracias a ambos!
@gantonioid podemos dejar el issue abierto hasta mañana por si tengo alguna duda mientras hago lo hablamos ?

**Comment by gantonioid** [comment]
Sí, tú prueba. Sólo no olvides pasarnos los comentarios.

**Comment by MartinMedinaSTK** [comment]
ok gracias.

**Comment by gantonioid** [comment]
qué tal @MartinMedinaSTK ? probaste ayer?

**Comment by MartinMedinaSTK** [comment]
@gantonioid ayer hice el cambio que hablamos, aplicando un filtro al excel y guardando el resultado en una variable tipo lista. El resultado 

5/17/2019 10:41:34 AM - DefineVariable type "List" as "lstFacturas" : Success
5/17/2019 10:41:34 AM - Excel ApplyFilter to the worksheet WSRetencionesHoja to the column with the index {18} with the criteria "=OK" and copy their value on "lstFacturas": Running
5/17/2019 10:41:34 AM - Se actualizo la variable : 
Var Name : lstFacturas
Value : System.Collections.Generic.List`1[System.Array]
5/17/2019 10:41:34 AM - Excel ApplyFilter to the worksheet WSRetencionesHoja to the column with the index {18} with the criteria "=OK" and copy their value on "lstFacturas" : Success
5/17/2019 10:41:34 AM - Excel Save WBRetenciones: Running
5/17/2019 10:41:34 AM - Excel Save WBRetenciones : Success
5/17/2019 10:41:34 AM - #-- aca recorrer con un for lo que devuelve el applyFilter: Running
5/17/2019 10:41:34 AM - aca recorrer con un for lo que devuelve el applyFilter : Success
5/17/2019 10:41:34 AM - Web Navigate to https://www.google.com/: Running
5/17/2019 10:41:34 AM - Execution started
5/17/2019 10:41:36 AM - Execution ended
5/17/2019 10:41:36 AM - Web Navigate to https://www.google.com/ : Success
5/17/2019 10:41:36 AM - Web Type FACT RETEN: <<<regFac[16]>>>: Running
5/17/2019 10:41:36 AM - Execution started
5/17/2019 10:41:37 AM - Execution ended
5/17/2019 10:41:37 AM - Web Type FACT RETEN: <<<regFac[16]>>> : Success
5/17/2019 10:41:37 AM - Titanium Sleep 3000 : Running
5/17/2019 10:41:40 AM - Titanium Sleep 3000  : Success


como se puede ver en el log no da error pero, no estoy seguro de que el value de la variable (System.Collections.Generic.List`1[System.Array]) sea lo que esta haciendo que se vea mal el valor de la variable mas abajo en el foreach. a continuacion el codigo:

DefineVariable type "List" as "lstFacturas"
Excel ApplyFilter to the worksheet WSRetencionesHoja to the column with the index {18} with the criteria "=OK"  and copy their value on "lstFacturas"
Excel Save WBRetenciones
#-- aca recorrer con un for lo que devuelve el applyFilter
foreach regFac in lstFacturas {
Web Navigate to https://www.google.com/
Web Type FACT RETEN: <<<regFac[16]>>>
Titanium Sleep 3000 
} 

¿podes chequear que este bien el código? no estoy seguro si es así como se recorre una variable de tipo lista y si es así como se recupera el valor.

Gracias!

**Comment by gantonioid** [comment]
Te mandé un update porque arreglamos que ApplyFilter antes te traía List[System.Array]
Ahora te trae List[List] y así ya puedes recorrerla

**Comment by MartinMedinaSTK** [comment]
Actualice Turing y cambió el error: 

5/17/2019 1:56:30 PM - Excel Save WBRetenciones: Running
5/17/2019 1:56:31 PM - Excel Save WBRetenciones : Success
5/17/2019 1:56:31 PM - DefineVariable type "List" as "lstFacturas": Running
5/17/2019 1:56:31 PM - MixReader : Se agrego una nueva variable : 
Var Name : lstFacturas
Value : 
5/17/2019 1:56:31 PM - DefineVariable type "List" as "lstFacturas" : Success
5/17/2019 1:56:31 PM - Excel ApplyFilter to the worksheet WSRetencionesHoja to the column with the index {18} with the criteria "=OK" and copy their value on "lstFacturas": Running
5/17/2019 1:56:31 PM - Object reference not set to an instance of an object.
5/17/2019 1:56:31 PM - Error applying filterObject reference not set to an instance of an object.
5/17/2019 1:56:31 PM - Excel ApplyFilter to the worksheet WSRetencionesHoja to the column with the index {18} with the criteria "=OK" and copy their value on "lstFacturas" : Error
5/17/2019 1:56:32 PM - Execution ended

este es el código:

# -- Guardo el excel para luego filtralo y traer las datos que necesito en la transaccion 
Excel Save WBRetenciones
DefineVariable type "List" as "lstFacturas"
Excel ApplyFilter to the worksheet WSRetencionesHoja to the column with the index {18} with the criteria "=OK"  and copy their value on "lstFacturas"
Excel Save WBRetenciones
#-- aca recorrer con un for lo que devuelve el applyFilter
foreach regFac in lstFacturas {
Web Navigate to https://www.google.com/
Web Type FACT RETEN: <<<regFac[16]>>>
Titanium Sleep 3000 
}

**Comment by gantonioid** [comment]
Tienes celdas vacías? en tu excel? Parece similar a uno que atendió @JuanISalazarM lo revisas por favor?

**Comment by JuanISalazarM** [comment]
Seguro, yo lo reviso. Me comunicaré por Teams por si tengo dudas.

**Comment by MartinMedinaSTK** [comment]
La instrucción addToList me esta guardando el siguiente valor:

5/20/2019 4:01:40 PM - AddToList "lstFacturas" value "015-002-000000002": Running
5/20/2019 4:01:40 PM - Se actualizo la variable : 
Var Name : lstFacturas
Value : System.Collections.Generic.List`1[System.String]
5/20/2019 4:01:40 PM - AddToList "lstFacturas" value "015-002-000000002" : Success

se correcto? o debería ver la lista de los datos que fui almacenando?

**Comment by JuanISalazarM** [comment]
Esto es que se agregó el valor a la lista IstFacturas.
También solicito de favor ingrese el Script para revisar los errores por parte de Excel más rápido. Porfavor.
Le solicito igual de favor ingrese el archivo para saber si no existen campos vacíos o cualquier otra razón por la cual no funciona el método.

**Comment by gantonioid** [comment]
@MartinMedinaSTK algún update?

**Comment by MartinMedinaSTK** [comment]
@gantonioid me falta probar copiar la lista a la grilla de SAP como para cerrar el proceso y listo.

**Comment by gantonioid** [comment]
podrás probar hoy? 

Recuerda... esa lista que ya tienes hay que cargarla primero al portapapeles y luego pegarla en SAP. Las instrucciones están más arriba en este ticket.

**Comment by MartinMedinaSTK** [comment]
Si eso hice... ya la tengo en el portapapeles, y ya llegué a la grilla donde tengo que pegarla... hoy tengo que terminar este proceso así que mas tarde te confirmo como quedo.
Gracias

**Comment by gantonioid** [comment]
Cerraré el ticket, si hay problemas con las instrucciones mencionadas nos dices

**Comment by MartinMedinaSTK** [comment]
Ok @gantonioid, disculpame que no pude seguir con este proceso para comentarte si funcionó o no. Estoy con la salida a producción de dos procesos y no le puede dedicar tiempo.

Cuando lo pruebe te aviso, gracias.

**Comment by MartinMedinaSTK** [comment]
@gantonioid te quería comentar que pegar directamente la lista en la grilla de SAP no funciona, lo que hace es pegar el código de la lista, pero lo pude resolver recorriendo la lista con un foreach y pegando elemento por elemento en la grilla.
saludos

**Comment by gantonioid** [comment]
a qué te refieres con el código de la lista? Igual ya pudiste pero para saberlo.
