### ISSUE TITLE
Tareas programadas y analytics

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#103]
¿Las tareas programadas son visibles desde las analytics del proceso? Hoy a las 9:10 am se ejecuto una tarea programada pero no puedo ver los detalles en la pagina de turing

**Comment by andresCruzF** [comment]
Hola @NehuenV , gracias por ayudarnos detectando este bug , acabo de liberarte un update que soluciona este problema (version = 20190516T1140) te pido lo valides y quedo al pendiente en caso de que tengas algun otro problema. 

Saludos.
