### ISSUE TITLE
[TITAN] - Problema con if y -ge (mayor o igual)

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#104]
Tengo el siguiente sencillo código:

```
DefineVariable type "string" as "MAYOR" with the value "524"
DefineVariable type "string" as "menor" with the value "81"
if ("<<<menor>>>" -ge "<<<MAYOR>>>")
SystemNotify Type "Notification" with message "Todo mal."
else
SystemNotify Type "Notification" with message "Todo bien."
end
```
Lo que pasa es que el fujo está yendo por el If en lugar del Else. Lo más extraño es que si inicializo las variables "MAYOR" y "menor" con 100 y 1 respectivamente, funciona correctamente

Adjunto el log con el error correspondiente:
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3187905/log.txt)

Adjunto el log cuando inicializo con 1 y 100:
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3187930/log.txt)

Esto es una pequeña parte de mi código la cual simplifiqué para que se pueda apreciar el problema sin la intervención de otros factores. 

Necesito una solución para este lunes.

Gracias.

**Comment by FaustinoLechuga** [comment]
Ok, ya lo estoy atendiendo

**Comment by FaustinoLechuga** [comment]
Intenta el if quitandole las comillas a las variables.

if (<<<menor>>> -ge <<<MAYOR>>>)

Me comentas si te funciono, si no para ver que otra cosa puede ser.

**Comment by CesarEmanuelLencina** [comment]
Muchas gracias @FaustinoLechuga era eso. Problema resuelto.
