### ISSUE TITLE
Error applying filterReferencia a objeto no establecida

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#105]
Buenas tardes,

en ticket 97 se aclaro la funcionalidad de la ApplyFilter  con el copy, se integro ejemplo del funcionamiento. adaptado a la automatización que se esta realizando. pero al usarlo en el excel del cliente. sale el siguiente error

Error applying filterReferencia a objeto no establecida como instancia de un objeto.
se agrega el código y el excel

[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3188820/codigo.txt)

[cuadratura caja y depósitos 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3188810/cuadratura.caja.y.depositos.27-03.xlsx)

agradezco por la atención prestada

**Comment by JuanISalazarM** [comment]
Enterado, revisaré el problema. Solicito mencione la fecha límite porfavor.

**Comment by rrrios** [comment]
le agradezco que fuera lo mas pronto posible, por que tenemos entrega el día lunes 20 de mayo y falta integrar mas cosas.

**Comment by JuanISalazarM** [comment]
Entendido. Cualquier cambio o inconveniente le notificaremos. Gracias por su atención.

**Comment by gantonioid** [comment]
@rrrios tu variable del foreach no existe, leíste y guardaste en Personas pero quieres iterar sobre ExcelVariable... nunca se declaró ExcelVariable

**Comment by gantonioid** [comment]
De seguro copiaste ejemplos de varias partes pero no hiciste los ajustes para integrarlos bien

**Comment by rrrios** [comment]
Buenos Dias 
Por favor  no cerrar @gantonioid  el ticket, por lo siguiente 
1. sí de acuerdo ala observación que usted encontró sentencia de foreach si es un error de sintaxis, pero ese no era el problema por que ApplyFilter  era la sentencia que estaba presentando el problema.

2. este issue le estaba haciendo soporte @JuanISalazarM, el cual me estaba atendiendo y encontró que el excel que yo estaba utilizando estaba con datos vacíos y nulos y esto estaba generando el error de Error applying filterReferencia a objeto no establecida como instancia de un objeto.

El ajuste se realizo el día de ayer 16 de mayo de 2019 tipo 4:30 de la tarde hora Colombia, por parte de el, se me notifico para que se actualizara Frida, para realizar pruebas y asi cerrar el issue.

pero me toco atender el requerimiento de otro proyecto y por eso no se pudo verificar. 

por lo anterior mencionado solicito reabrir este issue, ya que la respuesta dada en este seguimiento no cumple con la solución solicitada.

agradezco por la atención prestada.

**Comment by JuanISalazarM** [comment]
Se ha resuelto Issue
