### ISSUE TITLE
[TITAN] Problemas al usar la instruccion "GetUnique"

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#106]
Buenas, preciso tomar los valores unicos de una columna en excel, para luego gurdarlos en una lista y recorrer esa lista con un foreach, al ejecutarlo me salta el siguiente error: 
<img width="530" alt="2019-05-17 10_34_32-Cartolas del 03 ABR 2019 - Excel" src="https://user-images.githubusercontent.com/49756974/57932713-e17a7200-7891-11e9-8e27-b11bd981d6b5.png">

Les adjunto el script para su analisis.
[GetUnique.txt](https://github.com/FridaSupport/TuringSuport/files/3191743/GetUnique.txt)

**Comment by gantonioid** [comment]
@JuanIgnacioBurgos en qué instrucción es el error? puedes pasar tu log también por favor?

veo raro que el filtro lo pones `with the criteria "<<<Fecha>>>"`, según la documentación necesita algún tipo de comparador =, <, >, >=, <>, etc... pero no sé en qué línea está el problema.

Espero tu log

**Comment by JuanIgnacioBurgos** [comment]
Me resulta raro que revisando el log no marca error en ningun lado, se los adjunto:
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3191958/log.txt)

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid en cuanto al comparador, ya he utilizado la instruccion sin ningun coparador en otras ocasiones y funciono sin problemas

**Comment by gantonioid** [comment]
Disculpa pero el log no parece coincidir con el script que adjuntaste

**Comment by JuanIgnacioBurgos** [comment]
insisto en que ocurre algo raro con este error, al correr el scipt por primera vez arroja el "Objet reference..." sin embargo el proceso parece quedar suspendido y no finaliza de forma correcta, al Volver a ejecutar el mismo script el log arroja lo siguiente:

<img width="960" alt="2019-05-17 11_53_36-Microsoft Edge" src="https://user-images.githubusercontent.com/49756974/57936482-75503c00-789a-11e9-90a7-86fa04dbf939.png">


[log.txt](https://github.com/FridaSupport/TuringSuport/files/3191981/log.txt)

**Comment by gantonioid** [comment]
ESTOY viendo el log... de este último que adjuntas saco que haces estos pasos:

1. Cargas el libro WBmacro
2. Usas GetUnique apuntando a la hoja "WSasiento"  (que no has cargado)
3. Luego quieres volver a cargar el libro WBmacro ???
![image](https://user-images.githubusercontent.com/9600868/57937197-0d462980-788b-11e9-96ea-9a993411c66b.png)

Hay dos opciones... (1) editaste el log antes de mandármelo o (2) no es el código que enviaste al momento de publicar el issue.

Antes de llegar a conclusiones sobre el script necesitamos entender el caso. Nuestras herramientas para ello son el log completo que coincida con el script que estás usando.

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid te parece que lo veamos en una call? asi es mas facil poder entendernos :)

**Comment by pabloreitanosofttek** [comment]
Porfa que no pase del Lunes @JuanIgnacioBurgos  @gantonioid .

¡Gracias! 
Slds,

**Comment by JuanIgnacioBurgos** [comment]
Hola buen dia, por favor necesitaria ver este tema, es bastante particular, ya que arroja dos log distntos en una misma ejecucion.

**Comment by gantonioid** [comment]
@JuanISalazarM se comunicará contigo

**Comment by JuanISalazarM** [comment]
Cualquier duda me comunicaré por Teams. Buen día.

**Comment by JuanIgnacioBurgos** [comment]
Genial, quedo atento!

**Comment by FaustinoLechuga** [comment]
Intenta con esta instruccion, solo cambie esto "colindex" por esto "col_index", la documentacion tenia un error, ya se esta corrigiendo.
Excel GetUnique values from "WSasiento" col_index "1" start_at 2 as Fechas

Espero confirmación sobre el funcionamiento de la instucción.

**Comment by JuanIgnacioBurgos** [comment]
Hola, ya la probe, ahora funciona, gracias!

**Comment by gantonioid** [comment]
Se cierra. Usuario reporta que fue solucionado.
