### ISSUE TITLE
[TITAN]problemas al usar ApplyFilter  and copy their value

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#107]
Buenas Tardes
este problema se había reportado con anterioridad pero con otro excel, se esta utilizando la sentecia ApplyFilter  and copy their value.y se genera el

Error applying filterReferencia a objeto no establecida como instancia de un objeto.

me permito adjuntar el excel y codigo
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3192413/codigo.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3192414/log.txt)
[OBIEE X CTA. 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3192415/OBIEE.X.CTA.27-03.xlsx)

Agradezco por la atención prestada.

**Comment by JuanISalazarM** [comment]
Se le prestará atención. Cualquier inconveniente o cambio será notificado.

**Comment by andresCruzF** [comment]
Hola @rrrios  gracias por ayudarnos a encontrando un bug en esta funcion , te comento el error se presenta ya que las columanas K y L tienen definido un formato por lo que al momento de leer sus valores con la funcion ApplyFilter and copy el programa detecta que estas cuentan con un valor nulo, ya que forman parte del rango de celdas utilizadas (debido al formato que tienen dichas celdas) pero no tiene  un valor asiganado, es por esto que te envio un update con el cual ya no deberias tener problemas (ID =20190517T0552 ).

De igual forma te comento que el resultado es una lista de listas , donde se tendria que aplicar un foreach dentro de otro foreach para poder ir sacando su valor siendo la primera lista las Filas y la segunda las Filas  

[ [0,1,2,3] , [0 ,1,2,3,4] , ...] por poner un ejemplo  

Saludos

**Comment by andresCruzF** [comment]
Quedo en espera a que me confirmes que el error ya fue resulto para cerrar este  issue

**Comment by rrrios** [comment]
Buenas tardes

atendiendo su solicitud se actualizo la aplicación, y el error no esta apareciendo. pero necesito de su colaboración de como aplicar el foreach de forma correcta, ya que lo implemente como se sugirió y no eh podido solo traer una columna especifica.

ejemplo filtro la columna A pero guardo los valores en la columna C.
se esta implementando el foreach de la siguiente forma,  

foreach value in LocalObbie{
Message "value = <<<value>>>"
foreach li in value{
Message "li = <<<li>>>"
}
}
para que por favor me digas que me hace falta
gracias.

**Comment by rrrios** [comment]
agrego en un adjunto el código correcto, ya que en el comentario anterior no se esta mostrando como es.

[codigo for.txt](https://github.com/FridaSupport/TuringSuport/files/3192832/codigo.for.txt)
gracias

**Comment by rrrios** [comment]
se realizo la prueba  y el funcionamiento es el correcto. se puede cerrar el issue
