### ISSUE TITLE
[TITAN] Error al Usar CreatePivotTable 

### ISSUE THREAD

**Issue by dsalgadoi2012** [FridaSupport/TuringSuport#108]
Buenas tardes, 

al usar la instruccion CreatePivotTable 
"Excel CreatePivotTable CachePT1 in Hoja2 cell M1 withname "Tabla Dinamica" as PivotTable"
me genera el error, en la documentacion el whitname esta asi "whit_name" pero en el ejemplo esta whitname , sin embargo uso las dos formas y no me funciona, adjunto imagen del error.

la instrucción completa es la siguiente 

Excel CachePivotTable WBComparacion in Hoja2 from UsedRange as CachePT1
Excel CreatePivotTable CachePT1 in Hoja2 cell M1 withname "Tabla Dinamica" as PivotTable 

Cordialmente,
Daniel Alejandro Salgado.

![image](https://user-images.githubusercontent.com/34099274/57953231-2237b280-78b5-11e9-8b0b-cf58449a9630.png)

**Comment by pabloreitanosofttek** [comment]
Porfa poné el script o mínimamente el numero de proceso así pueden ayudarte más rápido.
¿Para que fecha se necesita? ¿Que criticidad? 

Grax!
Slds,

**Comment by dsalgadoi2012** [comment]
#
Excel NewWs in WBComparacion as Hoja3 
Excel CachePivotTable WBComparacion in Hoja2 from UsedRange as CachePT1
Excel CreatePivotTable CachePT1 in Hoja2 cell M1 withname "Tabla Dinamica" as PivotTable 
#
este es el script 
requiero poder cargar los valores del Pivot y continuar el proceso del Video 5

**Comment by FaustinoLechuga** [comment]
Ya lo estoy revisando

**Comment by FaustinoLechuga** [comment]
Intenta con esta instruccion. Solo cambie "withname" por "with_name", la documentacion tiene un error, en un momento mas la corrijo.
Excel CreatePivotTable CachePT1 in Hoja2 cell M1 with_name "Tabla Dinamica" as PivotTable

**Comment by FaustinoLechuga** [comment]
Quedo al pendiente para la confirmación sobre el funcionamiento de la instrucción.

**Comment by dsalgadoi2012** [comment]
ya no me arroja error sin embargo no me la crea, voy a validar todo el proceso pero considero que ya se puede cerrar este hilo 
muchas Gracias.
