### ISSUE TITLE
[TITAN] Generacion de turing off para el cliente.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#109]
Buenas tardes,

Necesitamos una version de turing offline con un usuario asociado al cliente TITAN con los siguientes procesos a copiar:

Responsable: Julian Arturo Bustos Gomez 
Nombre proceso: CARGALOCALES
ID: 1508212038

Responsable: César Emanuel Lencina
Nombre proceso: TITAN ADI
ID: 1138631086

Responsable: Juan Ignacio Burgos
Nombre proceso: ETV. 1-Carga y ejecución de Macro
ID: 528541555

Responsable: Karen Andrea Rueda Manjarres
Nombre proceso: carga_excel
ID: 1006593420

Responsable: Karen Andrea Rueda Manjarres
Nombre proceso: MixreaderProc
ID: 784948359

Necesidad: Urgente, (antes del miercoles 22 de mayo)

**Comment by andresCruzF** [comment]
Hola @ClaudioRodolfoGarcete me gustaria saber si hay algun canal de Teams para poder publicar esta version de Turing y asi poder mantener un control de las mismas , quedo en espera de tu respuesta para poder subir esta version , saludos.

**Comment by ClaudioRodolfoGarcete** [comment]
Si, el teams es "Proyecto FRIDA - TITÁN" en cualquier momento te dan acceso.

**Comment by andresCruzF** [comment]
Hola @ClaudioRodolfoGarcete no cuento con acceso al grupo de Teams , por lo que me tome la libertad de subirlo a otro repositorio para poder cumplir con la fecha de entrega , te hago llegar el link de descarga del mismo para que lo puedas descargar.

https://onesofttek.sharepoint.com/:u:/s/SofttekLabs/EZZwHG6TgXZHt53KRrWCSCEB1-HofaRlmSe7km8HUeM7RA?email=claudio.garcete%40softtek.com&e=26xl1i

Saludos

**Comment by ClaudioRodolfoGarcete** [comment]
@andresCruzF  podras subirlo a otro lugar ? ya que turing no esta completamente subido.

Some files weren't downloaded. The limit of file downloads has been reached. The total number of file downloads cannot be greater than 200

**Comment by andresCruzF** [comment]
@ClaudioRodolfoGarcete , Listo te acabo de compartir el link a tu correo te pido de favor lo valides , Saludos.

**Comment by ClaudioRodolfoGarcete** [comment]
Listo Andres, podes cerrar este issue.

**Comment by andresCruzF** [comment]
Gracias @ClaudioRodolfoGarcete , continuo al pendiente
