### ISSUE TITLE
Error en la instrucción WriteFormula

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#11]
Buenos dias,

Estoy tratando de hacer un cruce entre dos archivos excel, para eso necesito utilizar la formula "BUSCARV" la cual toma un valor del archivo 1 y lo compara en el archivo 2, para luego traer determinada informacion al archivo1.

La instruccion que me esta fallando es la siguiente:
Excel WriteFormula Hoja1 in F2:LastRow formula =BUSCARV(A2;'[OFICINA DE RECUENTOS SANTIAGO Y REGIONES.xlsx]Prosegur ex ChileValores (2)'!$A$2:$C$610;3;0)

Les dejo screen del error y una copia del log adjuntos, cualquier informacion adicional que presicen, por favor haganmelo saber.

Saludos.

<img width="956" alt="2019-04-23 10_08_56-Microsoft Edge" src="https://user-images.githubusercontent.com/49756974/56583655-73070480-65b0-11e9-9d25-bbcc9b988709.png">
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3107680/log.txt)

**Comment by JuanIgnacioBurgos** [comment]
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3107691/log.txt)

**Comment by JuanIgnacioBurgos** [comment]
Solucionado:

<img width="565" alt="respuesta" src="https://user-images.githubusercontent.com/49756974/56595202-9a67cc80-65c4-11e9-810f-ed84ed88d451.png">

**Comment by charlie632** [comment]
Cierro Issue
