### ISSUE TITLE
[TITAN]error en ReadValueThatMatch y WriteValueThatMatch

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#110]
el presente es informar que estas 2 sentencias, tal ves por temas de versiona miento. se perdieron los cambios. ya que estas 2 sentencias ya se habían reportado los errores y se habían hecho las respectivas correcciones y se cerraron los issues . 

agradezco por la atención prestada.

**Comment by FaustinoLechuga** [comment]
Pero que error tienes?

**Comment by rrrios** [comment]
se agraga el log
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3193073/log.txt)

**Comment by pabloreitanosofttek** [comment]
Podrias agregar el script? ¿Que urgencia tiene? ¿que fecha de necesidad?
Grax!

Slds,

**Comment by rrrios** [comment]
Buenos días 

me permito agregar el script y excel con el que se esta utilizando. y la necesidad es de urgente ya que esto ya se había reportado y se había corregido.




agradezco por la atención prestada

**Comment by JuanISalazarM** [comment]
Revisaré el problema. Se espera que esté resuelto para el miércoles antes de las 4pm. Si tengo dudas me comunicaré por medio de Teams.

**Comment by rrrios** [comment]
le agradezco por la atención prestada.

pero si requiero este ajuste lo mas pronto posible, ya que estamos en entrega al cliente el día de mañana 21 de mayo de 2019 y con esa fecha estas dando afectaría el compromiso que tenemos con el.

**Comment by JuanISalazarM** [comment]
Seguro, trataré que quede lo más pronto posible.
Veo que utiliza tres archivos en total para un fragmento del código.
Solicito de favor enviar los dos archivos faltantes, así como las variables que es para cada uno para replicar el error.
Espero su respuesta, muchas gracias.

**Comment by rrrios** [comment]
de acuerdo con lo solicitado adjunto los items que se están usando
[cuadratura caja y depósitos 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3199733/cuadratura.caja.y.depositos.27-03.xlsx)
[Copia de Consolidado pendientes MARZO.xlsx](https://github.com/FridaSupport/TuringSuport/files/3199734/Copia.de.Consolidado.pendientes.MARZO.xlsx)
[OBIEE X CTA. 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3199735/OBIEE.X.CTA.27-03.xlsx)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3199737/codigo.txt)
[LogTransacciones.xlsx](https://github.com/FridaSupport/TuringSuport/files/3199741/LogTransacciones.xlsx)

**Comment by JuanISalazarM** [comment]
El usuario confirma que se ha solucionado el Issue, procedo a cerrar el Ticket
