### ISSUE TITLE
[TITAN] Error al intentar click en imagen usando Titanium

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#111]
Buenos Días, se requiere hacer clic en una imagen especifica usando Titanium, el control de errores se implantó con el try/catch, ya que la misma imagen puede presentar dos estados, una vez ejecutada la primera fase del script al intentar hacer clic en otra imagen diferente Titanium indica que no es posible encontrar la imagen requerida, pero esta imagen no es la que se esta intentado ejecutar, adjunto fragmento del log y el archivo de log, numero de línea (212 del archivo log)

Fragmento Log:
20/05/2019 11:37:53 - Titanium ClickImage aplicar_Analytics.png Timeout= 500 NumberClicks= 1: Running
20/05/2019 11:37:55 - Error: ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2
20/05/2019 11:37:55 - Titanium ClickImage aplicar_Analytics.png Timeout= 500 NumberClicks= 1 : Error
20/05/2019 11:37:55 - Titanium ClickImage aplicar_Analytics2.png Timeout= 500 NumberClicks= 1: Running
20/05/2019 11:37:56 - Error: ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2

Archivo Log
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3198691/log.txt)

**Comment by FaustinoLechuga** [comment]
Ese error ocurre por que no esta encontrando la imagen, para manejar este tipo de errores se recomienda usar un try/catch en caso de que no encuentre la imagen.

**Comment by JulianBustos** [comment]
El try catch esta implementado, adjunto el script en ejecución.

la fase de ejecución comprende desde la línea 25 hasta la 162.

[Script_V1_SAE.txt](https://github.com/FridaSupport/TuringSuport/files/3198864/Script_V1_SAE.txt)

**Comment by FaustinoLechuga** [comment]
Al parecer solo se quedo guardado el mensaje de error de esta instruccion " ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2" pero el bot esta buscando la imagen que le indicas aqui "Titanium ClickImage aplicar_Analytics.png Timeout= 500 NumberClicks= 1"

Te voy a liberar una version con unas modificaciones en el log que especifica un poco mas que tipo de error es. 

¿Podras correr el proceso y despues mandarme el log que se cree con esta nueva version?

**Comment by JulianBustos** [comment]
Si señor, no hay problema

**Comment by FaustinoLechuga** [comment]
Si se resolvio?

**Comment by JulianBustos** [comment]
No señor, se sigue presentando, adjunto el archivo de Log generado.

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3203275/log.txt)

**Comment by FaustinoLechuga** [comment]
Podrias ser mas especifico? tiene varios error el log y no entiendo que es lo que no te esta funcionando.

**Comment by JulianBustos** [comment]
En la línea 124 genera un error al intentar abrir una de las imágenes (PPL_PROD.png) de ahí en adelante cada imagen que va a abrir genera el mismo error con la misma imagen (Error: ClickImage PPL_PROD.png Timeout= 500 NumberClicks= 1 Sim= 0.9)

El código de script que este ejecuta es el siguiente:

## Carga la información de PPL "" *******************************************************
	try
		Titanium Sleep = 300
		Titanium ClickImage Search.png Timeout= 300 NumberClicks= 1
		Titanium Sleep = 300
		Titanium Type "<<arcAccess>>" {ENTER}
		Titanium Sleep = 3000
		try
			if (Titanium ImageAppears cerrar_Off_Err.png Timeout= 1000 -eq "true" )
				Titanium ClickImage cerrar_Off_Err.png Timeout= 300 NumberClicks= 1
			end
			Titanium Sleep = 1000
		catch
		end
		try
			if (Titanium ImageAppears col_OPPL.png Timeout= 3000 -eq "true" )
				Titanium ClickImage col_OPPL.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			else
				Titanium ClickImage col_OPPL2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			end
		catch
		end
		Titanium Type ^{HOME}
		Titanium Sleep = 100
		Titanium Type {DOWN}
		Titanium Sleep = 100
		Titanium Type ^+({END})
		Titanium Sleep = 100
		Titanium Type +({UP})
		Titanium Sleep = 100
		Titanium Type ^c
		## Abre la DD de Access Carga_Locales ***************************************************
		try
			Titanium Sleep = 4000
			Titanium ClickImage Search.png Timeout= 400 NumberClicks= 1 Sim= 0.9
			Titanium Sleep = 300
			Titanium Type "<<<rutaDBsAccess>>>carga locales.accdb" {ENTER}
			Titanium Sleep = 5000
			try
				Titanium ClickImage PPL_PROD.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			catch
				Titanium ClickImage PPL_PROD2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			end
			Titanium Sleep = 7000
			Titanium ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2 Sim= 0.9
			Titanium Sleep = 300
			# Borra los registros que encuentre si existen *******
			try 
				Titanium Type {DEL}
				Titanium Sleep = 7000
				If (ImageAppears Si_Access.png Timeout= 5000 - eq "true")
					Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
					Titanium Sleep = 70000
				end
				try
					Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
				catch
				end
			catch
			end
			Titanium ClickImage PPL_FOCUS.png Timeout= 400 NumberClicks= 1 Sim= 0.9
			Titanium Sleep = 200
			#Titanium ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2 Sim= 0.9
			#Titanium Sleep = 600
			Titanium Type ^v
			Titanium Sleep = 2000
			Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			Titanium Sleep = 90000
			try
				Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			catch
				Titanium ClickImage aceptar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			end
			try
				Titanium Sleep = 90000
				Titanium ClickImage PPL_CARGA.png Timeout= 400 NumberClicks= 2 Sim= 0.9
				Titanium Sleep = 7000
				Titanium Type "27-03-2019"
				Titanium Sleep = 40000
				Titanium ClickImage aceptar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
				Titanium Sleep = 700
				Titanium ClickImage SelTable_Access.png Timeout= 500 NumberClicks= 2 Sim= 0.9
			catch
			end
		catch
		end
	catch
	end
	try
		Titanium Sleep = 60000
		Titanium ClickImage xls_Icon.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 600
		Titanium ClickImage excel_Off.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 600
		Titanium ClickImage No_Excel.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 7000
		try
			Titanium ClickImage access_On.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage access_On2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		Titanium Sleep = 6000
		try
			Titanium ClickImage access_Off.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage access_Off2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
	catch
	end
## Apertura aplicacion Web Analytic descargar CTA XXX .xls*******************************
Titanium Sleep = 6000
	try
		Web2 GoTo http://10.193.24.166:12001/analytics/
		Web2 Sleep 3000
		Titanium ClickImage max_Chrome.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Web2 Sleep 3000
		Web2 InsertValue "SOFRPA01" in name="NQUser"
		Web2 InsertValue "Abril2019" in name="NQPassword"
		Web2 Key "Enter"
		#Web2 Sleep 4000
		#Web2 Click in id="Catálogo"
		Web2 Sleep 4000
		Web2 Click in dynamic="CSC-IF - Cuadratura Locales Interfase Histórica - POR_CTA_LOCALES"
		Web2 Sleep 4000
		Web2 Type "V" in name="_paramsEstado"
		Web2 Sleep 200
		Web2 Type "01-01-2019" in name="_paramsFecha_Desde"
		Web2 Sleep 200
		Web2 Type "30-05-2019" in name="_paramsFecha_Hasta"
		Web2 Sleep 2000
		Titanium ClickImage cbo_Open.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Web2 Sleep 1000
		Titanium ClickImage sel_CruzVerde.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Web2 Sleep 3000
		try
			Titanium ClickImage aplicar_Analytics.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage aplicar_Analytics2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		Titanium Sleep 50000
		try
			Titanium ClickImage Orac_OpenExport.png Timeout= 500 NumberClicks= 1 Sim= 0.9 
			Titanium Sleep 100
			Titanium ClickImage Orac_Export.png Timeout= 500 NumberClicks= 1 Sim= 0.9 
			Titanium Sleep 100
			Titanium ClickImage Orac_ExportExcel.png Timeout= 500 NumberClicks= 1 Sim= 0.9 
			Titanium Sleep 100
			Titanium ClickImage Orac_ExportOpenExcel.png Timeout= 500 NumberClicks= 2 Sim= 0.9 
			Titanium Sleep 9000
		catch
		end
	catch
	end

**Comment by FaustinoLechuga** [comment]
El log que me pasaste es el de este ultimo proceso verdad?

**Comment by JulianBustos** [comment]
si señor

**Comment by FaustinoLechuga** [comment]
Una disculpa por la demora, lo que veo en el log y el script que estas utilizando es que pones los image appears dentro de un if pero esta estructura no funciona de esta manera (al menos no hasta ahora). 

Tambien el error que me reportas puede que sea debido a que la imagen no existe en la pantalla o que con la similitud de 0.9 no la encuentra. Puedes jugar con diferentes imagenes o con diferentes similitudes para que la encuentres.

Los timeouts que veo que pones tambien son muy cortos, recuerda que ese es el tiempo limite que le das a la intruccion para que encuentre la imagen y como titanium lo que hace es analizar las imagenes que se encuentran en la pantalla si la imagen no se a cargado o no existe en esa pantalla lo marcara como si no lo hubiera encintrado.

Yo en lo personal siempre uso similitudes de 0.8 a menos que haya otra imagen muy parecida, y en el timeout casi siempre uso 5000, esto no significa que se vaya a tardar siempre 5 segundos sino que la va a esperar 5 segundos maximo pero si la encuentra antes sigue con las demas instrucciones.

**Comment by JulianBustos** [comment]
Buenas Tardes, en efecto ya he probado con otros valores en la similitudes, llegando a 0.7, sin embargo voy a verificar lo que me comentas del tiempo de espera en el análisis de las imágenes para ver si esto soluciona el inconveniente, me preocupa lo que me comentas del if ya que al ser de las estructuras básicas no pueda soportar este tipo de comparación y al no contar con un While o Until es más tedioso realizar operaciones que requieran un tiempo indeterminado diferente al que usa el sleep, ya que en varias ejecuciones, este al finalizar continua procesando el script solapando todos los procesos e impidiendo su correcta ejecución.

**Comment by gantonioid** [comment]
Hay actualización del tema? qué pasó en la prueba @JulianBustos ?

Apoyando lo que mencionó Faustino, incluso en la misma máquina donde se tomó el recorte, no es recomendable usar similitudes de 1.0. Además tiempos de espera indeterminados nunca son recomendables, por lo tanto no lo permitimos en FRIDA. Lo que puedes hacer es poner un timeout más grande.

Un timeout no es un sleep, es decir: un Sleep de 5 segundos siempre tardará 5 segundos, pero el timeout se auto-cancela si la imagen buscada aparece en pantalla antes de esos 5 segundos.

**Comment by JulianBustos** [comment]
Buenos Días,

se realiza la aplicación de la recomendación de la siguiente forma:

Titanium ClickImage cbo_Open.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
Web2 Sleep 1000
Titanium ClickImage sel_CruzVerde.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
Web2 Sleep 3000
try
Titanium ClickImage aplicar_Analytics.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
catch
Titanium ClickImage aplicar_Analytics2.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
end
Titanium Sleep 30000
try
Titanium ClickImage Orac_OpenExport.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
Titanium Sleep 100
Titanium ClickImage Orac_Export.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
Titanium Sleep 100
Titanium ClickImage Orac_ExportExcel.png Timeout= 5000 NumberClicks= 1 Sim= 0.8
Titanium Sleep 100
Titanium ClickImage Orac_ExportOpenExcel.png Timeout= 5000 NumberClicks= 2 Sim= 0.8 
Titanium Sleep 9000
catch
end

Se intenta utilizar la instrucción (Titanium ImageAppears max_Chrome.png Timeout= 5000 Sim= 0.8)
la cual tambien continua gerenando una ecxepción

Adjunto el Log generado:

29/05/2019 10:47:35 - Titanium ClickImage max_Chrome.png Timeout= 5000 NumberClicks= 1 Sim= 0.8: Running
29/05/2019 10:47:38 - Titanium ClickImage max_Chrome.png Timeout= 5000 NumberClicks= 1 Sim= 0.8 : Success
### **29/05/2019 10:47:38 - Titanium ImageAppears max_Chrome.png Timeout= 5000 Sim= 0.8: Running
29/05/2019 10:47:44 - Error: ImageAppears max_Chrome.png Timeout= 5000 Sim= 0.8
29/05/2019 10:47:44 - Titanium ImageAppears max_Chrome.png Timeout= 5000 Sim= 0.8 : Error**
29/05/2019 10:47:45 - Execution ended

**Comment by JulianBustos** [comment]
Se utilizara el ImageAppears en try catch para manejar las posibles acciones a ejecutar, este ya funciona correctamente.
