### ISSUE TITLE
[TITAN][Excel] Mejora Instruccion ReadColumn

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#112]
Hola, estaria necesitando tomar los valores que me quedan en una columna de excel luego de aplicar un filtro, lo que sucede es que al utilizar la instruccion "Excel ReadColumn from the worksheet WSasiento with the column index {3} and save its value as {Deberes}" me gurda en la lista "Deberes" la totalidad de valores que hay en la columna, y yo unicamente estaria necesitando que se guarden aquellos que han quedado visibles luego de aplicar el filtro.

Será possible poder realizarle este ajuste a la instruccion?

Gracias.
Slds.

**Comment by JuanISalazarM** [comment]
Buenos días.
Le anexo los siguientes métodos. Donde la instrucción ApplyFilter almacena los valores filtrados en una variable, según el criterio que necesite.
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter

`ApplyFilter to the worksheet <wsKey> to the column with the index {<ColumnIndex>} with the criteria "<Criteria>" and copy their value on "<SaveVariable>"`

Si lo que desea es mantener el filtro puesto, puede utilizar la siguiente instrucción, después de haber utilizado la función anterior.
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/Filter

Espero resuelva su necesidad. Tenga excelente día.

**Comment by JuanIgnacioBurgos** [comment]
Buen dia, @JuanISalazarM lo que ocurre es que yo el filtro lo hago en la Columna A y debo guardar los valores que figuran en la Columna B, ¿como puedo lograr esto?

**Comment by gantonioid** [comment]
Hola
Te comparto referencia: #89 
Puedes consultar esto que explica las funciones de filtrado
[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Excelium.one%7Cbb884e0c-70ef-47e0-a7df-3de160ae6059%2FFiltrado%7Cf7028af7-17b9-475c-aa3b-5b7cf66667dd%2F%29&wdorigin=703](url)

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid esta correcto el link? no me estaria mostrando nada

**Comment by gantonioid** [comment]
Sí, es correcto el link. y si lo pones directo en el navegador?

**Comment by JuanISalazarM** [comment]
Lo que esta página muestra, es el funcionamiento de la función ApplyFilter.
Al aplicar el filtro en la columna A, ya guarda los valores de todas las columnas.
Es decir, si usted desea los valores de la columna C, puede tomar los valores por medio de un forEach.
Dado que los valores de la columna C, ya se encuentran en la variable que usted haya definido.
Si desea los valores de la columna C. Sería de la siguiente manera:
foreach v in variable{
Message <<<v[2]>>>
}

[0] = A
[1] = B
[2] = C
...

Y así sucesivamente.
Espero sirva la información. Le invito cordialmente revisar la documentación porfavor. Tenga un excelente día.

**Comment by JuanIgnacioBurgos** [comment]
okey, lo voy a probar de esta manera, cualquier cosa les comento, gracias.

**Comment by JuanIgnacioBurgos** [comment]
Estoy utilizando la instruccion indicada y el log me arroja el siguiente error "Object reference not set to an instance of an object"
¿Que puede estar sucediendo?

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3208947/log.txt)

**Comment by JuanIgnacioBurgos** [comment]
Tambien les adjunto el script para facilitar su analisis :

[Valuethatmatch.txt](https://github.com/FridaSupport/TuringSuport/files/3208978/Valuethatmatch.txt)

**Comment by Johhnn117** [comment]
Puedes revisar que tengas las versión 20190523T0315 y volver a intentarlo?

**Comment by JuanIgnacioBurgos** [comment]
Hola, tengo la version mensionada, y  el error persiste!!

**Comment by JuanISalazarM** [comment]
Buenas. Quisiera pedirle de favor si podría proporcionarnos el archivo que está utilizando para este proceso. Muchas gracias.

**Comment by JuanIgnacioBurgos** [comment]
Aqui se los comparto

[Cuadratura Macro FCV ETV 2-Abr-2019; Prosegur_.zip](https://github.com/FridaSupport/TuringSuport/files/3213178/Cuadratura.Macro.FCV.ETV.2-Abr-2019.Prosegur_.zip)

**Comment by JuanISalazarM** [comment]
Se le ha liberado una nueva versión de Frida, y se ha enviado algunas observaciones a través de Teams.

**Comment by JuanISalazarM** [comment]
Se ha solucionado el Issue.

**Comment by JuanIgnacioBurgos** [comment]
Le acabo de dar una Vuelta de tuerca mas al script la cual agrega cierta complejidad y la instruccion "Excel ReadValueThatMatch" me vuelva a dar el error "Object reference not set to an instance of an object" no se bien como sortearlo ni tampco a que se debe, si precisan que les comparta nuevamente el script, con gusto se los comparto!

PD: comentarme si se precisa crear un nuevo issue.

**Comment by pabloreitanosofttek** [comment]
Buenas, entiendo que aun no se resolvió dado que @JuanIgnacioBurgos lo probó y no funcionó... sugiero que hablen vía teams y se pongan de acuerdo en como seguir con el apoyo de @PabloMx y/o @Yorlay para que estén tanto desde lo funcional como desde lo técnico. ¡Gracias!

**Comment by JuanIgnacioBurgos** [comment]
Buenos dias @pabloreitanosofttek  se termino solucionando con la implementacion de dos instrucciones nuevas, el tema lo seguimos via Teams con @JuanISalazarM 

Gracias!
