### ISSUE TITLE
[Titan] ejemplo de if mayor o menor igual

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#113]
Buenos días

el presente es para solicitar de favor un ejemplo de if cuando se va hacer con valores de mayor que, menor que, diferente que, ya que actualmente solo tenemos conocimiento del siguiente

`if ("<<<local3[4]>>>" -eq "<<<DespObiee>>>" )`

agradezco por la atención prestada y pronta respuesta.

**Comment by andresCruzF** [comment]
Hola @rrrios te comparto la documentaciíon del IF para que la tengas presente , esta se encuentra en el grupo de Teams "Desarrollo FRIDA" en el channel Wiki en "Lógica de Scripts" 

[IF.docx](https://github.com/FridaSupport/TuringSuport/files/3203514/IF.docx)
