### ISSUE TITLE
Consulta: Necesito insertar valores guardados en una variable en SAP

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#114]
Estoy guardando un dato en excel en una variable, y lo que necesito es usar esa variable e insertarla en SAP, como muestra la imagen 1, esta es la forma que la estoy guardando:

Excel ReadCell from the worksheet WSName from the cell {6,3} and save its value as {OficinaDeVentas}

Luego quiero usar esa misma variable en SAP "Oficina de Ventas"
Gracias

![1](https://user-images.githubusercontent.com/49756748/58106870-cde34a00-7bb6-11e9-91b6-2cc80d8634cd.jpg)

**Comment by victorgamboa** [comment]
Gracias
Seria algo asi:
sap Write id txtbx[1] "<<<OficinasDeVentas>>>" 

pero el ID txtbx[1] como lo obtengo?

**Comment by victorgamboa** [comment]
@Johhnn117 

Esto pude sacar de SAP:
session.findById("wnd[0]/usr/ctxtVBAK-VKBUR").text = "1"

**Comment by Johhnn117** [comment]
Write <Type> <Identifyer> <Text> 
prueba con esta linea
Write id wnd[0]/usr/ctxtVBAK-VKBUR "tu texto"

**Comment by victorgamboa** [comment]
Gracias, ya lo pude realizar
