### ISSUE TITLE
[TITAN] [Exelium] No puedo escribir en un excel.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#115]
Ejecuto el siguiente código:

```
Excel LoadWBook "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Planilla ADI.xlsm" as LibroPlanilla
Excel LoadWSheet LibroPlanilla sheet_index 1 as hojaPlanilla
Excel Write "Hola mundo" in hojaPlanilla row 18 and column 3
Titanium Sleep 5000
Excel Save LibroPlanilla
```
El problema es que si bien la ejecución dice terminar correctamente, en realidad no se escribe nada en el archivo. Ni siquiera se ve que lo escriba durante el tiempo de ejecución (para eso el sleep)

Adjunto el log y el archivo en cuestión.
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3203304/log.txt)
[Planilla ADI.zip](https://github.com/FridaSupport/TuringSuport/files/3203310/Planilla.ADI.zip)

Si no puedo copiar un simple string menos podré pegar columnas enteras y fórmulas, que es lo que en realidad tengo que hacer. 

Necesito una solución para mañana (22-05-2019).

**Comment by FaustinoLechuga** [comment]
Ya lo estoy atendiendo pero no puedo replicar el error, seguiré intentando para ver por que no esta funcionando la instrucción.

**Comment by CesarEmanuelLencina** [comment]
¿Qué versión de office usan ustedes, de 32 o 64 bits?

**Comment by FaustinoLechuga** [comment]
No es la version, al parecer es el libro.

**Comment by CesarEmanuelLencina** [comment]
Noté que al abrir otro excel mientras tengo abierto el de Planilla ADI aparece el cartel que se puede ver en la siguiente captura:

![Screenshot (20)](https://user-images.githubusercontent.com/50213758/58129751-deb0b180-7bf0-11e9-99f1-413e9f64ecca.png)

Cuando busco dicha macro no la encuentro, (View>Macros)

Además al posarme en una celda de forma manual me intenta conectar a Oracle. Anteriormente podía pegar datos con Turing en este tipo de documentos pero ahora no me deja. Sí puedo pegarlos manualmente.

Además de lo comentado no he encontrado nada más.

**Comment by CesarEmanuelLencina** [comment]
Actualizo: El proceso fue corrido hoy en otra PC y ocurre exactamente el mismo problema. Finaliza correctamente pero en realidad no escribe en la celda.

El archivo fue generado desde Oracle en una PC con office de 32 bits y yo tengo la versión de 64 bits ¿puede ser ese el problema?

**Comment by FaustinoLechuga** [comment]
Si esta escribiendo valores pero el documento de Planilla ADI no lo esta mostrando y no se que pueda ser, si puede ser que influya lo del office 32 bits y el 64 pero no creo que el problema vaya por ahi. No nos habiamos topado con este tipo de problematicas anteriormente.

**Comment by CesarEmanuelLencina** [comment]
Recién, recién me terminaron de instalar office 32 bits en mi pc, así que voy a estar probando esto nuevamente ahora y te informo.

**Comment by CesarEmanuelLencina** [comment]
Actualizo: el error persiste, no tiene que ver con la versión.

**Comment by pablorlmx** [comment]
@FaustinoLechuga por favor nos das un update del avance, se nos está empezando a agotar el tiempo, tenemos que salir a UAT a más tardar el martes de la próxima semana, ya llevamos 1 semana de retraso.

+@RickProductivity 
Gracias.

**Comment by FaustinoLechuga** [comment]
Hola buen dia, hasta el momento no hemos podido resolver el problema ya que del lado del codigo nos indica que si esta escribiendo en el excel y que no hay ningun problema. Lo que se cree es que la macro no es compatible con el bot y por eso esto no esta funcionando.

**Comment by pabloreitanosofttek** [comment]
De ser como dice @FaustinoLechuga … ¿Que hacemos? ¡Gracias!

**Comment by FaustinoLechuga** [comment]
Lo que hemos visto es que lo mas seguro es que sea un problema con la macro, y estoy viendo si hay otra manera de solucionarlo.

**Comment by CesarEmanuelLencina** [comment]
Lo que estoy necesitando para solucionar este problema es una función que funcione como CopyRange (la cual por cierto no funciona en mi versión de turing) pero que me guarde los elementos copiados en el portapapeles. De esta forma con Titanium podría hacer un Ctrl+V y pegarlo "manualmente" por así decirlo.

**Comment by pabloreitanosofttek** [comment]
¿Como venimos? @FaustinoLechuga  

¡Gracias!

**Comment by CesarEmanuelLencina** [comment]
La nueva versión que me liberaron no corrigió el problema. Por favor necesito extraer los datos de un excel y desde el portapaeles pegarlo con Ctrl+V en otro (la planilla ADI). 

"CopyRangeToClipboard from <WSheetKey> star_at {18,3} to {LastRow, 15}"  o algo así.

**Comment by pabloreitanosofttek** [comment]
Buen día, seguimos con problemas con este ticket... Necesitamos una fecha cierta de resolución... ¿Cuándo puede ser? Gracias! @FridaSupport

**Comment by gantonioid** [comment]
@CesarEmanuelLencina te mandé la versión 20190530T0319, contiene la función CopyPaste que solicitaste
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/CopyPaste](url)

**Comment by CesarEmanuelLencina** [comment]
De las cuatro instrucciones que me dieron no funciona ninguna en la Planilla ADI. El problema radica en que estas funciones trabajan de manera similar a como lo hace Write, CopyColumn, WriteFormula, y el resto de las que tampoco funcionan.

Lo único que necesito es que se copie un rango como {18,3} to {LastRow, 15} al portapapeles. Eso es todo. Después yo con titanium hago el paste.

**Comment by pabloreitanosofttek** [comment]
Entonces lo que necesitas es que te dejen poner info en el "CONTROL + C"... de no ser esto, les pido a @CesarEmanuelLencina  y a @gantonioid  que charlen.

¡Gracias!  @pablorlmx

**Comment by gantonioid** [comment]
No me queda claro si probaste lo que te mandé [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/CopyPaste](url)

Esto es un Copy + Paste, por eso la insistencia

**Comment by CesarEmanuelLencina** [comment]
> 
> 
> No me queda claro si probaste lo que te mandé [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/CopyPaste](url)
> 
> Esto es un Copy + Paste, por eso la insistencia

Probé las cuatro formas y el proceso finaliza correctamente pero al abrir la Planilla ADI no escribió nada (sí, estoy dandole Save antes de terminar).



> 
> 
> Existen estas funciones de portapapeles (podrías hacer ctrl+v)
> Las has probado? en dado caso, por qué no te funcionan?
> 
>     * [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ReadColumn](url)
> 
>     * [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/LoadVarToClipboard](url)
> 
>     * [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/PasteVar](url)

Con ReadColumn + PasteVar funciona pero necesito poder limitar el rango. No necesito todas las filas de la columna. Necesito poder elegir el rango. Algo parecido como el CopyRange pero que copie a una variable en lugar de a una celda.

**Comment by gantonioid** [comment]
Suena a que se puede hacer con una combinación de funciones existentes.
Ejemplo:

1. ReadColumn para leer y tener una variable con los valores
2. Iteración y construcción de una lista con la función `AddToList` usando if (valor me interesa) -> agregar a lista
3. `LoadVarToClipBoard`
4. Titanium Type ^(g) para usar el comando "Ir a..."
5. Titanium Type B4 <--- para posicionarnos en la celda B4 o la celda que quieras
6. Titanium ^(v) para pegar

También podrías usar ApplyFilter o ReadValueThatMatch como el paso 1

**Comment by CesarEmanuelLencina** [comment]
Lo que ocurre es que la hoja de excel tiene el siguiente formato:

![imagen](https://user-images.githubusercontent.com/50213758/58651968-eeaf4c00-82e8-11e9-91f2-f12ba2f6d72a.png)

Cuando levanto la columna traigo todos los encabezados y demás de arriba. No creo que el filtrado ayude porque no siempre voy a saber con que me voy a encontrar en las celdas.

**Comment by CesarEmanuelLencina** [comment]
> 
> 
> Suena a que se puede hacer con una combinación de funciones existentes.
> Ejemplo:
> 
>     1. ReadColumn para leer y tener una variable con los valores
> 
>     2. Iteración y construcción de una lista con la función `AddToList` usando if (valor me interesa) -> agregar a lista
> 
>     3. `LoadVarToClipBoard`
> 
>     4. Titanium Type ^(g) para usar el comando "Ir a..."
> 
>     5. Titanium Type B4 <--- para posicionarnos en la celda B4 o la celda que quieras
> 
>     6. Titanium ^(v) para pegar
> 
> 
> También podrías usar ApplyFilter o ReadValueThatMatch como el paso 1



Ahí lo pruebo.

**Comment by CesarEmanuelLencina** [comment]
Ya probé lo que me pasate pero estoy teniendo problemas con el pasteVar. Además de que es muy lento e inviable.

Si querés lo vemos en un call ahora.

**Comment by gantonioid** [comment]
El problema de copiado quedó solucionado. Se observó que el usuario rechazaba la descarga de actualizaciones. Una vez aplicados los updates, funcionaron los ejemplos brindados.

**Comment by pabloreitanosofttek** [comment]
En general, es más fácil si hablamos… busquen un hueco durante el día y pónganse de acuerdo.

Gracias!

Slds,

PR

**Comment by pablorlmx** [comment]
Estimados,

pueden por favor armar una call y revisar el tema? Creo que la iteración por la herramienta no está siendo fructífera.


________________________________

**Comment by pabloreitanosofttek** [comment]
Propongo CALL…. Júntense 10’ luego de la daily Cesar.



Slds,

PR

**Comment by gantonioid** [comment]
@pabloreitanosofttek @pablolmx Ya está resuelto y cerrado
