### ISSUE TITLE
[Excellia] - Teclado virtual BOLIVARIANO-ECUADOR

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#116]
Se requiere poder ingresar una contraseña por medio del teclado virtual en el banco:

https://www3.bolivariano.com/bancav/

![veinti4online, Banca en internet del Banco Bolivariano - Google Chrome](https://user-images.githubusercontent.com/25591982/58119644-d00ad000-7bd9-11e9-84f8-d69dc571bc97.jpg)

La solución se necesita para el 23/05

**Comment by carlosortiz632** [comment]
Utilizando este selector puedes darle click a cualquier tecla del teclado. `input[value='u']`

Ejemplo:

`Web2 Click in selector="input[value='u']"`

_Nótese el uso de comillas simples ( ' ) dentro del selector._

Saludos!

**Comment by SoledadNunez** [comment]
Muchas gracias, lo pruebo y te confirmo.

**Comment by SoledadNunez** [comment]
Buenas tardes cierro el issue, funciona la instrucción.
Muchas gracias
