### ISSUE TITLE
Turing se cierra de manera aleatoria

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#117]
Estaba mostrando un proceso y Turing se cerró de manera aleatoria. Como comentario en el Teams les dejo un video con el caso.

**Comment by pabloreitanosofttek** [comment]
¿Podrías poner el link acá @jaristimuno ? 
¡gracias!

**Comment by jaristimuno** [comment]
https://teams.microsoft.com/l/message/19:cd9528b2e6604acf8bf35c51657d8525@thread.skype/1558471337811?tenantId=864ee999-c538-44a0-bddd-0449de62df6d&groupId=0d5132ed-7582-417f-8a6c-63e895ec18b2&parentMessageId=1558471337811&teamName=Desarrollo%20FRIDA&channelName=Soporte&createdTime=1558471337811

**Comment by andresCruzF** [comment]
Hola @jaristimuno te acabo de liberar un update (ID = 20190521T0942) el cual contiene una herramienta interna de monitoreo de errores en el codigo que nos permite analizar este tipo de eventos con mayor detalle te pido vuelvas a correr el proceso para que podamos conocer mayor detalle del mismo 

Saludos, quedo al pendiente.

**Comment by pabloreitanosofttek** [comment]
Hace más pesado a Frida? Xq sino tal vez deberíamos
Pensar en que sea para todos xq les pasa a varios, solo que Jesus tiene un video del momento justo.
Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: andresCruzF <notifications@github.com>
Enviado: martes, mayo 21, 2019 6:43 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Comment
Asunto: Re: [FridaSupport/TuringSuport] Turing se cierra de manera aleatoria (#117)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hola @jaristimuno<https://github.com/jaristimuno> te acabo de liberar un update (ID = 20190521T0942) el cual contiene una herramienta interna de monitoreo de errores en el codigo que nos permite analizar este tipo de eventos con mayor detalle te pido vuelvas a correr el proceso para que podamos conocer mayor detalle del mismo

Saludos, quedo al pendiente.

**Comment by andresCruzF** [comment]
Hola @pabloreitanosofttek lo hace muy poco pesado (de 16.6 MB a 17.1 MB) la intención es que así sea que todos reciban este update pero por el momento estamos limitando el uso de updates globales para evitar impactar los ambientes productivos y los usuarios que no presentan problema en sus procesos , así mismo desde la semana pasada todos los updates liberados ya vienen con esta funcionalidad lo que nos ha permitido ir encontrado errores en el código de manera más eficiente.

Saludos.

**Comment by pabloreitanosofttek** [comment]
Ok, gracias por la info!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: andresCruzF <notifications@github.com>
Enviado: martes, mayo 21, 2019 7:53 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] Turing se cierra de manera aleatoria (#117)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hola @pabloreitanosofttek<https://github.com/pabloreitanosofttek> lo hace muy poco pesado (de 16.6 MB a 17.1 MB) la intención es que así sea que todos reciban este update pero por el momento estamos limitando el uso de updates globales para evitar impactar los ambientes productivos y los usuarios que no presentan problema en sus procesos , así mismo desde la semana pasada todos los updates liberados ya vienen con esta funcionalidad lo que nos ha permitido ir encontrado errores en el código de manera más eficiente.

Saludos.

**Comment by RickProductivity** [comment]
@pabloreitanosofttek esto es parte de las acciónese de monitoreo que estamos tomando y habíamos conversado. Solo que nos les hemos hecho mucha publicidad.

**Comment by pabloreitanosofttek** [comment]
Genial! Hay q hacer algo de marketing!
Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: RickProductivity <notifications@github.com>
Enviado: miércoles, mayo 22, 2019 2:06 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] Turing se cierra de manera aleatoria (#117)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


@pabloreitanosofttek<https://github.com/pabloreitanosofttek> esto es parte de las acciónese de monitoreo que estamos tomando y habíamos conversado. Solo que nos les hemos hecho mucha publicidad.

**Comment by jaristimuno** [comment]
Hola @andresCruzF La herramienta de monitoreo es solamente interna? Ya que no me quedó muy claro como sabrian ustedes cuando sucederia el error. Podrias explicarme un poco mas?

**Comment by FaustinoLechuga** [comment]
Si es una herramienta interna que nos hará saber de forma mas especifica por que se están presentando estos inconvenientes.

**Comment by jaristimuno** [comment]
Es decir que estan siempre al pendiente de los distintos errores o fallas que pueda presentar cada usuario y a cada log correspondiente?

**Comment by andresCruzF** [comment]
@jaristimuno  Hola si es correcto estamos al pendiente de cualquier error que succeda con la herramienta con cada usuario y en cada computadora , pero esta herramienta solo nos reporta los errores no controlados en el codigo por lo que un error de syntaxis se mantiene local al igual que la bitacora de log.txt para no estar mandando datos confidenciales.

Saludos, quedo al pendiente en caso de que el error persista .
