### ISSUE TITLE
[TITAN] Error al ejecutar script de RPA

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#119]
Buenas Tardes, se esta presentando un error al intentar el script, se genera el siguiente mensaje:

![image](https://user-images.githubusercontent.com/50154520/58131466-5b895e80-7be4-11e9-9e35-3c340834fac2.png)

**pero el log no registra el inconveniente:**

21/05/2019 17:16:55 - Titanium Type "C:\CargaLocales\Archivos\carga locales.accdb" {ENTER}: Running
21/05/2019 17:16:58 - Titanium Type "C:\CargaLocales\Archivos\carga locales.accdb" {ENTER} : Success
21/05/2019 17:16:58 - Titanium Sleep = 5000: Running
21/05/2019 17:17:03 - Titanium Sleep = 5000 : Success
21/05/2019 17:17:03 - Titanium ClickImage PPL_PROD.png Timeout= 500 NumberClicks= 2 Sim= 0.9: Running
21/05/2019 17:17:05 - Titanium ClickImage PPL_PROD.png Timeout= 500 NumberClicks= 2 Sim= 0.9 : Success
21/05/2019 17:17:05 - Titanium Sleep = 7000: Running
21/05/2019 17:17:12 - Titanium Sleep = 7000 : Success
21/05/2019 17:17:12 - Titanium ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2 Sim= 0.9: Running
21/05/2019 17:17:15 - Titanium ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2 Sim= 0.9 : Success
21/05/2019 17:17:15 - Titanium Sleep = 300: Running
21/05/2019 17:17:16 - Titanium Sleep = 300 : Success
21/05/2019 17:17:16 - # Borra los registros que encuentre si existen *******: Running
21/05/2019 17:17:16 - Borra los registros que encuentre si existen ******* : Success
21/05/2019 17:17:16 - Titanium Type {DEL}: Running
21/05/2019 17:17:17 - Titanium Type {DEL} : Success
21/05/2019 17:17:17 - Titanium Sleep = 9000: Running
21/05/2019 17:17:26 - Titanium Sleep = 9000 : Success

**Archivo log:**

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3204593/log.txt)

**Parte del script que se esta ejecutando es el siguiente, el cual concuerda con la traza ejecutada en el Log:**

## Abre la DD de Access Carga_Locales ***************************************************
try
Titanium Sleep = 4000
Titanium ClickImage Search.png Timeout= 400 NumberClicks= 1
Titanium Sleep = 300
Titanium Type "<<<rutaDBsAccess>>>carga locales.accdb" {ENTER}
Titanium Sleep = 5000
try
Titanium ClickImage PPL_PROD.png Timeout= 500 NumberClicks= 2 Sim= 0.9
catch
Titanium ClickImage PPL_PROD2.png Timeout= 500 NumberClicks= 2 Sim= 0.9
end
Titanium Sleep = 7000
Titanium ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2 Sim= 0.9
Titanium Sleep = 300
# Borra los registros que encuentre si existen *******
Titanium Type {DEL}
Titanium Sleep = 9000
try
try 
Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
catch
Titanium ClickImage SiBorrar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
end
Titanium Sleep = 90000
try
Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
catch
Titanium ClickImage SiBorrar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
end
catch
catch 
end
Titanium Sleep = 80000
Titanium ClickImage PPL_FOCUS.png Timeout= 400 NumberClicks= 1 Sim= 0.9
Titanium Sleep = 200
Titanium Type ^v
Titanium Sleep = 9000

**Comment by andresCruzF** [comment]
Hola @JulianBustos te acabo de liberar un update (ID = 20190521T0938 ) el cual contine un monitor interno que nos permite identificar errores en el codigo , podrias volver a correr el proceso para que podamos analizar con mayor detalle este error.

Saludos, quedo al pendiente

**Comment by JulianBustos** [comment]
Buenas Tardes, se realiza ejecución solicitada.

**Comment by andresCruzF** [comment]
Hola @JulianBustos , ya hemos identificado la causa de tu error en un momento lo solucionamos y te mandamos el update con la solucion.

**Comment by andresCruzF** [comment]
Hola @JulianBustos podrias validar que el error ya no se encuentre presente quedo al pendiente (ID = 20190521T1159)

**Comment by JulianBustos** [comment]
Buenos Días,
Actualizo el Turing a la versión referida, pero al ejecutar continua desplegando el mismo mensaje:

![image](https://user-images.githubusercontent.com/50154520/58178794-743d5700-7c6c-11e9-8596-b3ce9768c178.png)

**Adjunto el archivo de Log Generado:**
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3207599/log.txt)

**El script ejecutado es el siguiente: Se indenta para facilitar la lectura**
######################################################### [Carga Locales] #########################################################
# CargasLocales|Cargar Archivo Excel
# Proceso: Paso Proceso Archivos | Abri archivo FCV de Cuadratura - "CuadraturaLocales X.xls"
# 29-04-2019|Julian Bustos
# Variables de entrada:
# Fecha Inicio: Date, Valor: ToDay
# ExcelFile: Text, Valor: CuadraturaLocales XX-XX.xls (XX-XX = DD-MM)
# ExcelFile: Text, Valor: Cuadratura GEO XX-XX.xls (XX-XX = DD-MM)
# DirectDescarg: Text, valor: C:\Users\xxxxxx\Descargas\
# Entorno: QA.
########################################################  CuadraturaLocales ########################################################
## Variables a utilizar *******************************
DefineVariable type "string" as "rutaDBsAccess" with the value "<<urlAccessFile>>"
DefineVariable type "string" as "diaProceso"
DefineVariable type "string" as "mesProceso"
DefineVariable type "string" as "fechaHoy"
DefineVariable type "string" as "indexLogRow" with the value "0"
DefineVariable type "string" as "messageError" with the value "Err: "
GetCurrentDate Date{dd es} and save as diaProceso
GetCurrentDate Date{MM es} and save as mesProceso
GetCurrentDate Date{MM/dd/yy es} and save as fechaHoy
GetCurrentDate Date{dd/MM/yyyy es} and save as fechaHoyReal
GetCurrentDate Date{dd-MM-yyyy es} and save as fechaHoyAccess
## Carga la información de PPL "" *******************************************************
	try
		Titanium Sleep = 300
		Titanium ClickImage Search.png Timeout= 300 NumberClicks= 1
		Titanium Sleep = 300
		Titanium Type "<<arcAccess>>" {ENTER}
		Titanium Sleep = 3000
		try
			Titanium ClickImage cerrar_Off_Err.png Timeout= 300 NumberClicks= 1
			Titanium Sleep = 1000
		catch
		end
		try
			Titanium ClickImage col_OPPL.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage col_OPPL2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		Titanium Type ^{HOME}
		Titanium Sleep = 100
		Titanium Type {DOWN}
		Titanium Sleep = 100
		Titanium Type ^+({END})
		Titanium Sleep = 100
		Titanium Type +({UP})
		Titanium Sleep = 100
		Titanium Type ^c
		## Abre la DD de Access Carga_Locales ***************************************************
		Titanium Sleep = 4000
		Titanium ClickImage Search.png Timeout= 400 NumberClicks= 1
		Titanium Sleep = 300
		Titanium Type "<<<rutaDBsAccess>>>carga locales.accdb" {ENTER}
		Titanium Sleep = 5000
		try
			Titanium ClickImage PPL_PROD.png Timeout= 500 NumberClicks= 2 Sim= 0.9
		catch
			Titanium ClickImage PPL_PROD2.png Timeout= 500 NumberClicks= 2 Sim= 0.9
		end
			Titanium Sleep = 7000
		try
			Titanium ClickImage SelTable_Access.png Timeout= 400 NumberClicks= 2 Sim= 0.9
		catch
		end			
		Titanium Sleep = 300
		# Borra los registros que encuentre si existen *******
		Titanium Type {DEL}
		Titanium Sleep = 9000
		try 
			Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage SiBorrar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		Titanium Sleep = 90000
		try
			Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage SiBorrar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		catch
		Titanium Sleep = 80000
		Titanium ClickImage PPL_FOCUS.png Timeout= 400 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 200
		Titanium Type ^v
		Titanium Sleep = 9000
		try
			Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage SiBorrar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		Titanium Sleep = 90000
		try
			Titanium ClickImage Si_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage SiBorrar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		try
			Titanium Sleep = 90000
			Titanium ClickImage PPL_CARGA.png Timeout= 400 NumberClicks= 2 Sim= 0.9
			Titanium Sleep = 7000
			Titanium Type "27-03-2019"
			Titanium Sleep = 40000
			Titanium ClickImage aceptar_Access.png Timeout= 500 NumberClicks= 1 Sim= 0.9
			Titanium Sleep = 700
			Titanium ClickImage SelTable_Access.png Timeout= 500 NumberClicks= 2 Sim= 0.9
		catch
		end
		Titanium Sleep = 60000
		Titanium ClickImage xls_Icon.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 600
		Titanium ClickImage excel_Off.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 600
		Titanium ClickImage No_Excel.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		Titanium Sleep = 7000
		try
			Titanium ClickImage access_On.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage access_On2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
		Titanium Sleep = 6000
		try
			Titanium ClickImage access_Off.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		catch
			Titanium ClickImage access_Off2.png Timeout= 500 NumberClicks= 1 Sim= 0.9
		end
	catch
		SystemNotify Type "Notification" with message "Error ejecutando Bloque Carga la información de PPL."
	end

**Comment by RickProductivity** [comment]
Oye podrias confirmarnos el id de la version ?

Gracias
________________________________

**Comment by JulianBustos** [comment]
Adjunto la versión actual

![image](https://user-images.githubusercontent.com/50154520/58180673-1c085400-7c70-11e9-9390-164fd2ddce55.png)

**Comment by andresCruzF** [comment]
Hola @JulianBustos , acabo de generar un update para tu usuario con la correcion a este error el cual se presenta en la estructura de tu script , se trabajo en reportar este tipo de error de manera mas clara por lo que te pido valides que ya se encuentra solucionado 

id= 20190522T0633

Saludos

**Comment by JulianBustos** [comment]
Buenas tardes, en efecto, ya no se presenta el error de secuencia no contiene elementos, mil gracias.
