### ISSUE TITLE
append Instruction was't found - **Excelium**

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#12]
Tengo problemas con una instrucción, lo que quiero hacer es insertar una nueva fila al de los datos en un archivo Excel utilizando el reader de **Excelium**, no se si estoy usando la instrucción adecuada, según la descripción entiendo que si, pero me sale el error:

La instrucción usada es:

**Excel append from WSName at [1 ="text",2 ="text2"]**

También la use con Append usando la A en mayúscula y sale el mismo error.

fragmento del Log:

4/23/2019 11:07:58 AM - Excel append from WSName at [1 ="text",2 ="text2"]: Running
4/23/2019 11:07:58 AM - Error: append from WSName at [1 ="text",2 ="text2"]
4/23/2019 11:07:58 AM - Error in append Instruction was't found
4/23/2019 11:07:58 AM - Error in append Instruction was't found
4/23/2019 11:07:58 AM - Excel append from WSName at [1 ="text",2 ="text2"] : Error
4/23/2019 11:08:00 AM - Execution ended

Agradezco la ayuda.

**Comment by gantonioid** [comment]
@FaustinoLechuga agregar append al switch/case de Excelium

**Comment by FaustinoLechuga** [comment]
Listo, ya se agrego la instrucción solo habría que hacer un update de Frida que es cerrando y volviendo a abrir la applicacion

**Comment by gantonioid** [comment]
Gracias Tino, @carlosgiraldo nos confirmas para cerrar el issue?

**Comment by carlosgiraldo** [comment]
Hola, gracias, ya funciona.
