### ISSUE TITLE
[FRIDA] Versiones distintas y "log" de cambios

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#122]
Buenas, ¿Como están?

Les consulto algo... estoy viendo que están haciendo versiones puntuales para resolver los temas puntuales que surgen y me pregunto 2 cosas:

- Si hacen _updates_ a algunos chicos por temas puntuales, cuando necesitemos la versión final de PRD ¿Como sabemos que es la versión de todos los que desarrollaron y no tengamos ideas y vuelta?

- Sería bueno que cuando apruebo un cambio de "actualizar a una nueva versión" sería bueno saber que cambios incluye, porque sino estamos ciegos a la hora de saber que cambio... Podria traer un log (o algo) para que podamos saber.

Prioridad: BAJA
Fecha: 31/05

¡Gracias!
Slds,
PR

**Comment by andresCruzF** [comment]
Hola @pabloreitanosofttek ,

Contamos con un dashboard de versiones que nos permite conocer la version que tiene activa cada usuario como cada Area.

### Si hacen updates a algunos chicos por temas puntuales, cuando necesitemos la versión final de PRD ¿Como sabemos que es la versión de todos los que desarrollaron y no tengamos ideas y vuelta?

La version que se libera a PRD cuenta siempre con los cambios  mas actuales en la palataforma de tal manera que no haya problemas entre los cambios que tiene cada version , asi mismo una vez liberada se valide que esta sea 100%funcional para que no haya necesidad de hacer alguna modificación una vez liberados los procesos 

### Sería bueno que cuando apruebo un cambio de "actualizar a una nueva versión" sería bueno saber que cambios incluye, porque sino estamos ciegos a la hora de saber que cambio... Podria traer un log (o algo) para que podamos saber.

Nos encontramos trabajando una nueva metodologia como area que nos permita llevar este control por el momento no hemos encontrado la manera de poder hacer publico este log pero estamos en la busqueda de una forma de hacer este proceso automatico .

![image](https://user-images.githubusercontent.com/49708627/58491290-57a19300-8134-11e9-88a3-0407847ba545.png)

**Comment by pabloreitanosofttek** [comment]
OK, confiaré entonces en el proceso de control de por allá.

¡Gracias!
