### ISSUE TITLE
Turing en Modo TURN ON EVENT LISTENER y SCHEDULE 

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#123]
Buenos días, es posible tener el Turing ejecutándose en modo TURN ON EVENT LISTENER para que se ejecuten unos procesos y otros estén en modo SCHEDULE para que todos los días a cierta hora se ejecuten otros sin problema en la misma maquina virtual? debería tener alguna consideración para que esto suceda?

quedo atento a sus respuestas.

**Comment by gantonioid** [comment]
Hola Carlos
Posible sí es. Lo que hay que tener en cuenta es que las ejecuciones no se sobrepongan, ya que estarían utilizando las mismas dependencias (librerías de código) y provocar errores. 
Ve la respuesta de #52 y me dices si resuelve tu duda.

**Comment by carlosgiraldo** [comment]
Entonces si se podría tener 3 procesos que están esperando llamado desde el API de FRIDA para ejecutarse de forma remota y otros 3 programados para ejecutarse en cierto momento del día.

Lo que si me preocupa es el tema de las librerías compartidas porque todos estos procesos van a ejecutar los readers de SAP, que pasa si yo tengo dos Turing en la misma maquina Virtual uno en modo TURN ON EVENT LISTENER y el otro Turing solo ejecutando los SCHEDULER?

**Comment by gantonioid** [comment]
El EVENT LISTENER no hay problema porque se hace una cola de ejecución. Pero como comenté, si llega el horario de una tarea scheduleada cuando una ejecución de EVENT LISTENER está en progreso ahí es donde hay problema.
Por lo tanto la recomendación es tener las máquinas necesarias para que no haya múltiples ejecuciones simultáneas en la misma máquina.
