### ISSUE TITLE
[Excellia] - Instrucción CheckIfFileExist no funciona

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#124]
No logró que la instrucción "CheckIfFileExist" funcioné, siempre retorna que no existe.
adjunto el código probado, la sintaxis en la documentación
![CheckIfFileExist_Cap1](https://user-images.githubusercontent.com/49729569/58184323-431e5000-7c87-11e9-858a-8466f20b3d7c.png)
![CheckIfFileExist_Cap2](https://user-images.githubusercontent.com/49729569/58184324-431e5000-7c87-11e9-8185-d4af0286419c.png)
[CheckIfFileExist_Prueba1.txt](https://github.com/FridaSupport/TuringSuport/files/3207911/CheckIfFileExist_Prueba1.txt)
[CheckIfFileExist_Prueba2.txt](https://github.com/FridaSupport/TuringSuport/files/3207912/CheckIfFileExist_Prueba2.txt)
[CheckIfFileExist_Prueba3.txt](https://github.com/FridaSupport/TuringSuport/files/3207913/CheckIfFileExist_Prueba3.txt)

**Comment by Johhnn117** [comment]
Hola Ignacio, puedes revisar que tengas la versión nueva? es 20190522T0440

**Comment by ignacionovio** [comment]
Se acaba de actualizar la version y ya funciona. gracias!
