### ISSUE TITLE
Consulta. Excelium fechas formato excel

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#125]
Al leer las fechas de un libro de excel, al ser formato fecha, excel internamente las guarda como un valor numerico y no una fecha. Al momento de FRIDA leer la celda lee el valor de manera numerica e.j "35314" es igual a 6/9/1996. Hay alguna instrucción que permita leerlo en formato fecha? He probado aplicandole manualmente el cambio de formato, he utilizado los applyformat de la documentación y si bien el cambio se toma de manera visual, en el log sigue llegando "35314"

**Comment by JuanISalazarM** [comment]
Enterado. Revisaré el problema. Solicito de favor ingresar el log, código utilizado, y el archivo a analizar, porfavor. Cualquier duda me comunicaré a través de Teams.

**Comment by jaristimuno** [comment]
[log2.txt](https://github.com/FridaSupport/TuringSuport/files/3208445/log2.txt)
[archivofinal.xlsx](https://github.com/FridaSupport/TuringSuport/files/3208446/archivofinal.xlsx)
[archivoescritura.xlsx](https://github.com/FridaSupport/TuringSuport/files/3208447/archivoescritura.xlsx)
[escritura.txt](https://github.com/FridaSupport/TuringSuport/files/3208460/escritura.txt)

Adjunto dejo los archivos excel a analizar, el codigo (escritura) y el log

**Comment by JuanISalazarM** [comment]
Enterado muchas gracias. Cualquier duda me comunico con usted por medio de Teams.

**Comment by raulpoltiSTK** [comment]
@JuanISalazarM Necesitamos poder avanzar con este tema de forma urgente, tenemos demo en el día de hoy para presentar el BOT al negocio. Darle prioridad, Gracias.

**Comment by JuanISalazarM** [comment]
Realicé una corrección en la linea implementada a través de Teams @jaristimuno 
Solicitaría de favor implementarla y realizar pruebas. Esperemos solucione el Issue. Espero su respuesta.

**Comment by JuanISalazarM** [comment]
Se le ha liberado una nueva versión.
Una observación. En la linea: 
`Excel Write <<<ValueDolarar>>> in HojaF row 15 and column 18`
Ocurre un error por no encontrar la variable `<<<ValueDolarar>>>`
Favor de probar la nueva versión porfavor. Tenga un excelente día.

**Comment by JuanISalazarM** [comment]
Se ha resuelto el Issue.
