### ISSUE TITLE
[Excellia] Foreach falla con grupos de registros Cuenta[2]

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#126]
Se requiere recorrer un string caracter a caracter, pero dicho string esta contenido en un una columna de un grupo de registros. Para esto se genera la siguiente instrucción:

```
................................
Excel ReadRows from WSconf start_at 2 as RegCuentas
.................................
foreach Cuenta in RegCuentas{
..................
foreach caracter in  Cuenta[2]{
Web2 Click in selector="input[value='<<<caracter>>>']"
Web2 Sleep 1000
}
...............................
```
Al ser ejecutado Frida cierra el navegador y el código sale por el catch.
En el log no se visualiza el error ya que la instrucción foreach es transparente para este, por eso no se adjunta detalle de log.
Se requiere respuesta para el el 23/05

**Comment by JuanISalazarM** [comment]
Enterado. Revisaré el problema. Solicito de favor ingresar el log, código utilizado, y el archivo a analizar, porfavor. Cualquier duda me comunicaré a través de Teams.

**Comment by SoledadNunez** [comment]
Te armo el paquete y lo envió vía teams ya que tiene credenciales. Lo que voy a solicitar es mucho cuidado con el uso de las credenciales ya que son ambientes productivos y es complicado desbloquear las contraseñas.
Como opción también esta realizar una call y te muestro cual es a falla que esta teniendo.

**Comment by gantonioid** [comment]
Sugeriría que pruebes en el foreach poner una variable directa no apuntando al índice 2 de una lista. Es decir (en el script de tu post):
```
................................
Excel ReadRows from WSconf start_at 2 as RegCuentas
.................................
foreach Cuenta in RegCuentas{
DefineVariable type "string" as "otraVar" with the value "<<<Cuenta[2]>>>"
foreach caracter in  otraVar{
Web2 Click in selector="input[value='<<<caracter>>>']"
Web2 Sleep 1000
}
...............................
```

Este es un ejemplo funcionando (Lee una tabla de usuarios y teclea en Notepad todos los IS de cada usuario - letra por letra)

```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\Usuarios-admin.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
Excel ReadRows from hoja start_at 2 as filas
Titanium Type {WIN}
Titanium Sleep 3000
Titanium Type Notepad
Titanium Sleep 3000
Titanium Type {ENTER}
Titanium Sleep 3000
foreach f in filas {
DefineVariable type "string" as "IS" with the value "<<<f[0]>>>"
foreach caracter in IS {
Titanium Type <<<caracter>>>
}
Titanium Type {ENTER}
Titanium Sleep 1000
}
```

Aguardo tus comentarios sobre la prueba

**Comment by gantonioid** [comment]
@SoledadNunez pudiste probar?

**Comment by SoledadNunez** [comment]
Buenas estaba probando otros temas que también se destrabaron, ya estoy con este en 5 ya te confirmo.
Muchas gracias

**Comment by SoledadNunez** [comment]
Se puede cerrar el tk, las pruebas con esa modificación fueron correctas. Muchas gracias de nuevo.

**Comment by SoledadNunez** [comment]
Buenas tardes, Se replico el error en otro de los procesos, puedo saltear el error, pero la estructura es bastante mas sencilla que la de BCP.
Paso el código y log por si es de ayuda en la resolución
[Banco BBVA Continental.txt](https://github.com/FridaSupport/TuringSuport/files/3214055/Banco.BBVA.Continental.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3214056/log.txt)

 del tk

**Comment by gantonioid** [comment]
Esto es un tema diferente, pero te recuerdo que cuando en el log aparece algo similar a lo que te está saliendo `"<<<Mail%1°>>>"` Significa que... no se encuentra el índice deseado de la variable Mail, ya sea porque no es una lista o porque el índice que le pides está fuera de rango (IndexOutOfBounds)

**Comment by SoledadNunez** [comment]
Si, perdón lo pegue en el TK equivocado, ya borre el comentario y lo coloque en el 33.
