### ISSUE TITLE
[Excellia] - Problemas en la versión de Turing generada para el ambiente productivo

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#127]
Les paso 3 problemas que detectamos en la versión de Turing que tenemos en la maquina del cliente Excellia:
-	Monitoreo de Detracciones – primera corrida: el proceso recorre un Excel con sociedades y por cada sociedad debe ejecutar todo el proceso del bot completo, que incluye ingresar a la web de SUNAT y bajar un archivo Excel que luego se sube a SAP.  Para la primer sociedad (primera vuelta del foreach) termina ok, cuando corre para la segunda da error en la siguiente instrucción:
22/05/2019 09:57:27 a. m. - Web2 Click in id="btnAceptar": Running
22/05/2019 09:57:28 a. m. - Web2 Click in id="btnAceptar" : Success
22/05/2019 09:57:28 a. m. - Web2 Sleep 3000: Running
22/05/2019 09:57:31 a. m. - Web2 Sleep 3000 : Success
22/05/2019 09:57:31 a. m. - Web2 Navigation: Running
22/05/2019 09:57:32 - {"error":"Navigation Timeout Exceeded: 90000ms exceeded"}
22/05/2019 09:57:32 a. m. - Web2 Navigation : Error
22/05/2019 09:57:32 a. m. - SendMail with subject "Monitoreo de Detracciones - Error al descargar el archivo de SUNAT" to "martin.medina@softtek.com" with body "Ocurrió un error en la descarga del archivo de detracciones de SUNAT, el proceso no se ha finalizado y deberá ser revisado manualmente. Desde la Sociedad OTRA (164) inclusive y en adelante no se han procesado.": Running
22/05/2019 09:57:33 a. m. - SendMail with subject "Monitoreo de Detracciones - Error al descargar el archivo de SUNAT" to "martin.medina@softtek.com" with body "Ocurrió un error en la descarga del archivo de detracciones de SUNAT, el proceso no se ha finalizado y deberá ser revisado manualmente. Desde la Sociedad OTRA (164) inclusive y en adelante no se han procesado." : Success

-	Pago Central – primera corrida: se detectó un error que se había corregido en la versión anterior de Turing que teníamos en esta máquina, editanto el script directamente en el Turing de la maquina del cliente y por otro lado también lo habíamos modificado en el script del Turing del desarrollador.  Cuando se generó una nueva versión de Turing para resolver un issue (cuando se corre un proceso se cierra Turing) se perdieron esos cambios que habíamos hecho en el script de la máquina.  Entiendo que al ser una versión offline de Turing es correcto que se pierda, por eso también lo hicimos en el proceso del desarrollador para no perder los cambios y que las siguientes versiones de Turing lo incorporen. No tenemos claro como se generar las versiones de Turing a partir de los procesos desarrollados por nosotros, creíamos que en cada nueva versión se tomaban los procesos de cada Turing del desarrollador que lo creó, ¿es correcto esto?

-	 Pago Central – segunda corrida: Luego de solucionar el problema anterior, en la segunda ejecución del proceso da error nuevamente en la instrucción que hace el envío de un mail con adjunto:
22/05/2019 9:18:05 - GetLastFileInTheFolder "D:\Users\servcomp\Downloads\" with the name "captura.jpg" and save as FileName: Running
22/05/2019 9:18:05 - Se agrego una nueva variable : 
Var Name : FileName
Value : D:\Users\servcomp\Downloads\captura.jpg
22/05/2019 9:18:05 - GetLastFileInTheFolder "D:\Users\servcomp\Downloads\" with the name "captura.jpg" and save as FileName : Success
22/05/2019 9:18:05 - ##Envio el mail con la captura tomada: Running
22/05/2019 9:18:05 - Envio el mail con la captura tomada : Success
22/05/2019 9:18:05 - SendMail with subject "Solicitud de fondos para el pago de: Identificador: TRA01 Sociedad: 301" to "pruebaMM@gmail.com" with body "Envio los importes por los programas de la Sociedad: 301 - N/A - de la fecha: 23.05.2019" and a file attachment "D:\Users\servcomp\Downloads\captura.jpg": Running
22/05/2019 9:18:07 - error: SendMail with subject "Solicitud de fondos para el pago de: Identificador: TRA01 Sociedad: 301" to "pruebaMM@gmail.com" with body "Envio los importes por los programas de la Sociedad: 301 - N/A - de la fecha: 23.05.2019" and a file attachment "D:\Users\servcomp\Downloads\captura.jpg" : Email Not Send 
22/05/2019 9:18:07 - SendMail with subject "Solicitud de fondos para el pago de: Identificador: TRA01 Sociedad: 301" to "pruebaMM@gmail.com" with body "Envio los importes por los programas de la Sociedad: 301 - N/A - de la fecha: 23.05.2019" and a file attachment "D:\Users\servcomp\Downloads\captura.jpg" : Error

No es la primera vez que nos sucede este error en este ambiente, ¿podrán verificar la instrucción sendmail? ¿Necesitaremos una nueva versión de Turing para para solucionar este tema?

Adjunto los 3 archivos de log de cada corrida.
[log_monitoreo de detracciones_corrida1.txt](https://github.com/FridaSupport/TuringSuport/files/3208702/log_monitoreo.de.detracciones_corrida1.txt)
[log_pago_central_corrida1.txt](https://github.com/FridaSupport/TuringSuport/files/3208703/log_pago_central_corrida1.txt)
[log_pago_central_corrrida2.txt](https://github.com/FridaSupport/TuringSuport/files/3208704/log_pago_central_corrrida2.txt)

Estos errores son en ambiente productivo y dejan so poder ejecutarse nuevamente el bot sin la interversión humana debido a que deja sesiones de SAP y Web abiertas.

Necesitamos que le den prioridad y una solución.

**Comment by raulpoltiSTK** [comment]
Estimados dar prioridad a este tema! gracias!

**Comment by andresCruzF** [comment]
Hola @MartinMedinaSTK ,

### Pago Central – primera corrida:  "No tenemos claro como se generar las versiones de Turing a partir de los procesos desarrollados por nosotros, creíamos que en cada nueva versión se tomaban los procesos de cada Turing del desarrollador que lo creó, ¿es correcto esto?"

La versión de Turing Offline que se han estado generado cuentan con la versión más actual de los proceso , siendo construida a partir de la versión que se encuentra en la base de datos,  así mismo te comento que en algunos casos no es necesario reconstruir toda la estructura de archivos del programa (esto únicamente es necesaria cuando se agrega o retira algún nuevo proceso) es por esto que se sugiere que únicamente se remplace el archivo con el nombre  TuringExpo.exe como lo hace PUMBA manteniendo los cambios que se haya realizado de manera offline en los procesos.

### No es la primera vez que nos sucede este error en este ambiente, ¿podrán verificar la instrucción sendmail? ¿Necesitaremos una nueva versión de Turing para para solucionar este tema?

Revisaremos este error a mayor profundida unicamente me gustaria saber si este tambien se presenta en la maquina fisica de excelia o unicamente en la maquina virtual ?

**Comment by carlosortiz632** [comment]
Hola @MartinMedinaSTK. Para el primer error, la página carga completamente? De ser así, prueba quitando la instrucción Navigation y poniendo un sleep un poco más grande antes. Si esto funciona, puedo generarte una versión que solucione completamente este error. De no cargar la página completamente, tendríamos que buscar alguna otra solución.

Saludos.

**Comment by MartinMedinaSTK** [comment]
hola @andresCruzF todos los errores reportados son de la maquina física de excellia (en las dos maquinas tenemos la misma versión de turing). 

Para el primer punto no sabíamos que funcionaba así, entiendo que esto pasa solo porque es una version offline?

volvimos a correr el proceso y sigue dando error en sendmail:

22/05/2019 14:31:17 - SendMail with subject "Error en ejecución de proceso de Pago Central" to "pruebaMM@gmail.com" with body "Ocurrió un error en el proceso de ejecución de Pago Central" and a file attachment "D:\Users\servcomp\Documents\RPA_STK\versionesTuring\TuringExpo (Offline)v10\TuringExpo (Offline) - Excellia\App\log.txt": Running
22/05/2019 14:31:18 - error: SendMail with subject "Error en ejecución de proceso de Pago Central" to "pruebaMM@gmail.com" with body "Ocurrió un error en el proceso de ejecución de Pago Central" and a file attachment "D:\Users\servcomp\Documents\RPA_STK\versionesTuring\TuringExpo (Offline)v10\TuringExpo (Offline) - Excellia\App\log.txt" : Email Not Send 
22/05/2019 14:31:18 - SendMail with subject "Error en ejecución de proceso de Pago Central" to "pruebaMM@gmail.com" with body "Ocurrió un error en el proceso de ejecución de Pago Central" and a file attachment "D:\Users\servcomp\Documents\RPA_STK\versionesTuring\TuringExpo (Offline)v10\TuringExpo (Offline) - Excellia\App\log.txt" : Error

Algo no esta funcionando evidentemente, cuando hicimos la primer prueba de este proceso hace una semana aproximadamente la primera vez dio error en SendMail y la segunda corrido lo hizo bien. Pero ahora no sucede lo mismo. Hay que revisarlo.

**Comment by pabloreitanosofttek** [comment]
¡Porfa necesitamos tener los bots en vivo! 

¡Gracias!

**Comment by RickProductivity** [comment]
Oigna, pero algo me ocnfunde, es decir entiendo que con la maquina virtual no hay problema
 ( desde siemrpe se visualizo usar una maquina virtual), por que no prueban en la maquina virtual con accesos de Dev ?


________________________________

**Comment by andresCruzF** [comment]
Hola @MartinMedinaSTK 

### Algo no esta funcionando evidentemente, cuando hicimos la primer prueba de este proceso hace una semana aproximadamente la primera vez dio error en SendMail y la segunda corrido lo hizo bien. Pero ahora no sucede lo mismo. Hay que revisarlo.

Ya se mando una nueva version de Turing con una ampliación de tiempo de respuesta del API al igual que se coloco una aclaración de los posible erorers en la bitacora de log para un futuro analisis en caso de volver a presentarse un error en la funcion de sendMail

La version de Turing se encuentra en el Teams de Grupo Romero en general en la carpeta de FRIDA Installer con el nombre de TuringExpo.exe unicamente hace falta remplazar el archivo para no afectar a los atrchivos de la maquina. Yo he remplazado la version de la maquina fisica de excelia por lo que te pido lo valides en la virtual.

Saludos , quedo al pendiente
