### ISSUE TITLE
[TITAN] Copiar proceso al ambiente del cliente

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#128]
Hola Andres, como estas?

Necesitamos que nos copies este proceso al turing offline del cliente TITAN.

Responsable: Juan Ignacio Burgos
ID: 225623540
nombre: ETV1

Necesidad: Urgente, fecha limite: 22 de mayo 2019

**Comment by JuanIgnacioBurgos** [comment]
@andresCruzF Por favor necesitamos pasar este proceso al Turing del cliente para realizar pruebas el dia de hoy

**Comment by raulpoltiSTK** [comment]
Alguna novedad sobre este tema? Necesitamos sacarlo urgente! Gracias

**Comment by andresCruzF** [comment]
Hola @ClaudioRodolfoGarcete  y @JuanIgnacioBurgos  ya se encuentra en el Teams de ARS Chile la nueva version del Turing que solicitan , se encuentra en el canal de Proyecto FRIDA - TITAN en la carpeta de TuringExpo Installers con el no,bre de Turing(Offline) - TITAN v2

Quedo al pendiente
