### ISSUE TITLE
[Excellia] Pantallas que tienen arrays como IDs. Instruccion: SAP GetArrayRowNumber

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#129]
Hola,

No es posible obtener la cantidad de filas de una pantalla con arrays como IDs.

Se adjunta los siguientes archivos:

[Elements.txt](https://github.com/FridaSupport/TuringSuport/files/3209144/Elements.txt)

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3209147/log.txt)

![tablaRara](https://user-images.githubusercontent.com/33100638/58205579-3add0980-7cb5-11e9-8700-02100c68e817.png)

Nombre proceso: Pago Confirming Excellia
ID: 415861891

Visto con @eradgg , Necesidad: Urgente, proceso en ambiente productivo.

**Comment by eradgg** [comment]
Se está revisando. La instrucción no funciona para este caso ya que no está definido el Array, se hará una extensión de la intrucción para que acepte el inicio del grid

**Comment by eradgg** [comment]
Sigo trabajando en este issue, como te había comentado @ClaudioRodolfoGarcete es algo complicado, espero tener una solución mañana.

**Comment by eradgg** [comment]
Ya quedó solucionado. Ya te subí una versión y dejé el script con los cambios para que funcione.
Cualquier problema lo revisamos.

saludos.

**Comment by ClaudioRodolfoGarcete** [comment]
GetArrayRowNumber me
