### ISSUE TITLE
Utilizar browpet en ventana emergente.

### ISSUE THREAD

**Issue by charlie632** [FridaSupport/TuringSuport#13]
Consulta en nombre de: @camilitwo .

Texto original:

> Hola tengo la siguiente duda.
> 
> estoy generando una app web2, al momento de hacer click sobre un boton, me levanta una ventana emergente. es aqui mi duda, como le indico en el codigo que ventana tomar...
> 
>  
> 
> Si alguien tiene alguna documentacion, seria de gran ayuda

![image](https://user-images.githubusercontent.com/8704336/56600618-bb2d2380-65be-11e9-9300-24d93925b9e3.png)
![image](https://user-images.githubusercontent.com/8704336/56600640-c8e2a900-65be-11e9-8d1a-a700b1a1a706.png)

![image](https://user-images.githubusercontent.com/8704336/56600674-db5ce280-65be-11e9-87ff-d6cde7bfb677.png)

**Comment by charlie632** [comment]
La función `SwitchPage Last` te ayuda a cambiar el contexto de la ventana en la que se encuentra Browpet. Las instrucciones siguientes a esta instrucción se ejecutarán sobre la ventana emergente. Para regresar a la ventana principal es ncesario utilizar la instrucción de `SwitchPage Main`.

**Comment by camilitwo** [comment]
Hola!

tendrias por ahi algun example, de como utilizar dicha funcion??

**Comment by charlie632** [comment]
@camilitwo  
Con este script fue con el que probamos la función al momento de crearla. Me dices si funciona. 

saludos.
```
Web2 GoTo https://www.quackit.com/javascript/javascript_alert_box.cfm
Web2 Sleep 2000
Web2 Click in selector="body > div.main > article > p:nth-child(20) > a" 
Web2 Sleep 3000
Web2 SwitchPage Last
Web2 Click in selector="body > div > p > a"
Web2 SwitchPage Main
Web2 Click in selector="body > div.main > article > p:nth-child(20) > a"
```

**Comment by camilitwo** [comment]
Funciono correctamente!

Gracias!

**Comment by charlie632** [comment]
Perfecto, cierro el issue
