### ISSUE TITLE
Ingresar Contraseña en teclado virtual para Telebanking ScotiaBank.

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#130]
Buenos días, necesito ingresar sesión en un sitio con teclado virtual:
La url es la siguiente:
https://telebanking.scotiabank.com.pe/TeleBanking/FrontEnd
El teclado es el siguiente:
![imagen](https://user-images.githubusercontent.com/50331739/58261027-f18cc880-7d4d-11e9-80dd-f3b979d0607c.png)

Intenté acceder yo sola, pero por xpath o selector, no se me ocurre una solución universal ya que son varios los valores variables por cada elemento.
Ejemplo con letra S:
S
Xpath: /html/body/div[2]/div[4]/button[2]
Selector: body > div.darkKeypad.keypad-popup > div:nth-child(4) > button:nth-child(2)
Necesito poder resolver este asunto para esta semana.
Desde ya muchas gracias.
A quién se le asigne este ticket, le pido que se comunique conmigo para pasarle los datos de acceso.

**Comment by carlosortiz632** [comment]
Hola, @MarianelaDuarte. Podrías probar con el siguiente xPath?

`"//button[contains(text(), 'u')]"`

Ej. 

`Web2 Click in xpath="//button[contains(text(), 'u')]"`

Saludos.

**Comment by MarianelaDuarte** [comment]
Hola Carlos! Buenos días,
Probado y ha funcionado correctamente.
Muchas gracias por la velocidad en respuesta.
Saludos
