### ISSUE TITLE
Consulta SAP Reader insertar datos en una grilla de SAP

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#131]
Estoy guardando unos datos en una variable de un Excel y los necesito insertar en los campos Material y Cantidad de pedido, existe alguna instrucción aparte de Write, si pudiéramos hacer una call para explicar mejor

![image](https://user-images.githubusercontent.com/49756748/58265824-6eb83d80-7d4e-11e9-8063-7d2220a71781.png)

**Comment by eradgg** [comment]
Si claro, podemos hacer una call.

**Comment by victorgamboa** [comment]
recuerda detallarme todo lo que necesitamos para ver la solución y si necesitamos pedirle algo al cliente, ya que estamos sobre la fecha de entrega, gracias Eder!

**Comment by eradgg** [comment]
Tenemos que hacer una prueba con VS ya que no puedo saber qué esta pasando en SAO corriendo sólo con FRIDA, este elemento no se ha podido identificar @RickProductivity  @gantonioid ¿Con quien podemos escalarlo para ver si el cliente nos puede proporcionar VPN para poder hacer la prueba desde mi local?

**Comment by gantonioid** [comment]
Veo en la imagen que tienen el foco en el campo, pueden escribir con Titanium aunque sea temporalmente en lo que avanzamos con el flujo?

@pabloreitanosofttek nos ayudas con lo que se menciona de la VPN?

**Comment by pabloreitanosofttek** [comment]
@José Pablo Romero López<mailto:jose.romero@softtek.com> @Yorlay Fermin Mayora<mailto:yorlay.fermin@softtek.com> porfa revisar el detalle de la VPN… Entiendo que es Finning.

¡Gracias!

Saludos,
Pablo Reitano | Innovation Delivery Manager
Softtek Sudamérica Hispana | Maipú 942, Piso 19 | Ciudad Autónoma de Buenos Aires | Buenos Aires, Argentina, 1006
Tel: 54 (11) 5252 8100 Ext: 7948 | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:7E90847B-DA1E-40B3-A63C-83A1C2A95A6F] twitter.com/Softtek<http://twitter.com/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:B3D991EB-5DF8-4C9B-BD73-644B5DC600C0]  linkedin.com/company/Softtek<http://www.linkedin.com/company/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:036C97D2-03EA-4434-9B10-ACB42E701186]  facebook.com/Softtek<http://www.facebook.com/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:4ACE75F1-2EE0-42F0-A771-FDD7221B80FC]  feeds.feedburner.com/SofttekBlog<http://feeds.feedburner.com/SofttekBlog> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:ECF27B1D-E254-4E08-A9C9-8064C08528AB]  youtube.com/SofttekTV<http://www.youtube.com/SofttekTV>

De: gantonioid <notifications@github.com>
Enviado el: jueves, 23 de mayo de 2019 18:15
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
CC: Pablo Sebastián Reitano <pablo.reitano@softtek.com>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] Consulta SAP Reader insertar datos en una grilla de SAP (#131)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Veo en la imagen que tienen el foco en el campo, pueden escribir con Titanium aunque sea temporalmente en lo que avanzamos con el flujo?

@pabloreitanosofttek<https://github.com/pabloreitanosofttek> nos ayudas con lo que se menciona de la VPN?

**Comment by pabloreitanosofttek** [comment]
OK., gracias!

Saludos,
Pablo Reitano | Innovation Delivery Manager
Softtek Sudamérica Hispana | Maipú 942, Piso 19 | Ciudad Autónoma de Buenos Aires | Buenos Aires, Argentina, 1006
Tel: 54 (11) 5252 8100 Ext: 7948 | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:7E90847B-DA1E-40B3-A63C-83A1C2A95A6F] twitter.com/Softtek<http://twitter.com/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:B3D991EB-5DF8-4C9B-BD73-644B5DC600C0]  linkedin.com/company/Softtek<http://www.linkedin.com/company/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:036C97D2-03EA-4434-9B10-ACB42E701186]  facebook.com/Softtek<http://www.facebook.com/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:4ACE75F1-2EE0-42F0-A771-FDD7221B80FC]  feeds.feedburner.com/SofttekBlog<http://feeds.feedburner.com/SofttekBlog> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:ECF27B1D-E254-4E08-A9C9-8064C08528AB]  youtube.com/SofttekTV<http://www.youtube.com/SofttekTV>

De: Yorlay Fermin Mayora
Enviado el: viernes, 24 de mayo de 2019 14:13
Para: Pablo Sebastián Reitano <pablo.reitano@softtek.com>
CC: José Pablo Romero López <jose.romero@softtek.com>; Víctor Gamboa <victor.gamboa@softtek.com>; Eder Raul Alberto David Garcia Guardado <ederr.garcia@softtek.com>
Asunto: RE: [FridaSupport/TuringSuport] Consulta SAP Reader insertar datos en una grilla de SAP (#131)

Gracias Pablo,

Ya no es necesaria la vpn para Eder. Victor y el tienen otra forma de solventarlo.  Te avisamos cualquier duda.

Saludos Cordiales.

Yorlay Fermin | Consultor de Tecnología
Softtek Chile | Av. Cerro el Plomo 5420, Of 505 | Las Condes| Santiago de Chile.
Tel: (56-2) 2 374 3998 | www.softtek.com<http://www.softtek.com/?utm_campaign=emailsignature&utm_source=email&utm_medium=email>
twitter.com/Softtek<http://twitter.com/Softtek> | linkedin.com/company/Softtek<http://www.linkedin.com/company/Softtek> | facebook.com/Softtek<http://www.facebook.com/Softtek> | feeds.feedburner.com/SofttekBlog<http://feeds.feedburner.com/SofttekBlog> | youtube.com/SofttekTV<http://www.youtube.com/SofttekTV>

De: Pablo Sebastián Reitano
Enviado el: viernes, 24 de mayo de 2019 8:28
Para: FridaSupport/TuringSuport <reply@reply.github.com<mailto:reply@reply.github.com>>; FridaSupport/TuringSuport <TuringSuport@noreply.github.com<mailto:TuringSuport@noreply.github.com>>; José Pablo Romero López <jose.romero@softtek.com<mailto:jose.romero@softtek.com>>; Yorlay Fermin Mayora <yorlay.fermin@softtek.com<mailto:yorlay.fermin@softtek.com>>
CC: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Asunto: RE: [FridaSupport/TuringSuport] Consulta SAP Reader insertar datos en una grilla de SAP (#131)

@José Pablo Romero López<mailto:jose.romero@softtek.com> @Yorlay Fermin Mayora<mailto:yorlay.fermin@softtek.com> porfa revisar el detalle de la VPN… Entiendo que es Finning.

¡Gracias!

Saludos,
Pablo Reitano | Innovation Delivery Manager
Softtek Sudamérica Hispana | Maipú 942, Piso 19 | Ciudad Autónoma de Buenos Aires | Buenos Aires, Argentina, 1006
Tel: 54 (11) 5252 8100 Ext: 7948 | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:7E90847B-DA1E-40B3-A63C-83A1C2A95A6F] twitter.com/Softtek<http://twitter.com/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:B3D991EB-5DF8-4C9B-BD73-644B5DC600C0]  linkedin.com/company/Softtek<http://www.linkedin.com/company/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:036C97D2-03EA-4434-9B10-ACB42E701186]  facebook.com/Softtek<http://www.facebook.com/Softtek> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:4ACE75F1-2EE0-42F0-A771-FDD7221B80FC]  feeds.feedburner.com/SofttekBlog<http://feeds.feedburner.com/SofttekBlog> | [Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Descripción: Description: Description: cid:ECF27B1D-E254-4E08-A9C9-8064C08528AB]  youtube.com/SofttekTV<http://www.youtube.com/SofttekTV>

De: gantonioid <notifications@github.com<mailto:notifications@github.com>>
Enviado el: jueves, 23 de mayo de 2019 18:15
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com<mailto:TuringSuport@noreply.github.com>>
CC: Pablo Sebastián Reitano <pablo.reitano@softtek.com<mailto:pablo.reitano@softtek.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Asunto: Re: [FridaSupport/TuringSuport] Consulta SAP Reader insertar datos en una grilla de SAP (#131)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Veo en la imagen que tienen el foco en el campo, pueden escribir con Titanium aunque sea temporalmente en lo que avanzamos con el flujo?

@pabloreitanosofttek<https://github.com/pabloreitanosofttek> nos ayudas con lo que se menciona de la VPN?

**Comment by eradgg** [comment]
Solucionado.
