### ISSUE TITLE
[TITAN] [URGENTE] Apertura de Excel falla

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#132]
Hola, el cliente me paso un set de pruebas para la demo de hoy, estoy teniendo algunos inconvenientes con los archivos excel. No estoy pudiendo abrirlos con FRIDA, ya intente renombrarlos, cambiarlos de formato, etc pero no hubo caso.

Les dejo el excel para ver si me pueden ayudar a dar con el problema.
[Depósitos  13-05-2019.xlsx](https://github.com/FridaSupport/TuringSuport/files/3213044/Depositos.13-05-2019.xlsx)

**Comment by JuanIgnacioBurgos** [comment]
Solucionado al parecer el nombre del archive llevaba dos espacios eso hace que el FRIDA falle


Cierro issue

**Comment by gantonioid** [comment]
Script funcionando:

```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\Depositos.13-05-2019.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
Excel Write "Hola" in hoja cell A1
SystemNotify Type "alert" with message "Breakpoint"
```

![image](https://user-images.githubusercontent.com/9600868/58268789-b8ebef80-7d4b-11e9-82db-591e3a9e1e66.png)

**Comment by gantonioid** [comment]
Súper que ya lo resolviste!
