### ISSUE TITLE
[EXCELLIA] - Error instruccion SelectRb de SAP

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#133]
Buenas tardes estoy queriendo seleccionar una opcion de un RadioButton y no puedo.
Adjunto el log del proceso y la linea que utilizo. Utilicé el SAP Recorder para obtener el ID y tambien grabar y reproducir script de SAP para verificar que no me equivoqué de ID.
No sé si la instrucción es la que esta fallando o qué sucede.
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3213623/log.txt)
La instrucción es:
SAP SelectRb id wnd[0]/usr/radRB_CRE
Quizas estoy escribiendo mal la instrucción, pero es como la vi en la documentación de la web.
El Process ID es : 1979440310.

**Comment by eradgg** [comment]
Hola Marianela.

Intenta buscando el Id del radio button en el ShowElemets y pon ese Id, debería ser algo como:  
/app/con[0]/ses[0]/wnd[0]/usr/radRB_CRE.
Si no funciona, podemos tener una llamada para checarlo.
Saludos.

**Comment by MarianelaDuarte** [comment]
Busque el id con ShowElements y ahora hace click pero sucede que después de hacer el click vuelve al paso anterior (primer opción seleccionada por defecto). ¿Cómo se debe hacer para que quede seleccionado ese?

**Comment by MarianelaDuarte** [comment]
Buen día, luego de varias pruebas y ver el comportamiento, vi que se cambiaba la opcion porque se seleccionaba antes de que se actualizaran las opciones, ya pude solucionarlo refrescando previamente a la selección.Doy por cerrado el ticket.
