### ISSUE TITLE
[FRIDA] No accede a SAP

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#134]
Al momento de ingresar los datos para ingresar en SAP, FRIDA no esta escribiendo los valores correspondientes para ingresar.

Esto funcionaba hasta hace unas horas. No fue editado el codigo, no fue cambiada la configuración del ambiente SAP. 

Tampoco se me ha actualizado la versión de TURING

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3217941/log.txt)
[prueba.txt](https://github.com/FridaSupport/TuringSuport/files/3217944/prueba.txt)

Prioridad: ALTA
Fecha: 27/05

¡Gracias!

**Comment by gantonioid** [comment]
Si no cambió el script y no recibiste actualización de Turing, entonces puede ser el ambiente. A veces sucede que en un reboot del servidor de SAP, se desactiva el scripting.

**Comment by eradgg** [comment]
si podría ser el SAPscript como menciona Antonio, ahora lo reviso en llamada.

**Comment by jaristimuno** [comment]
Mmm ok. Pero en caso de que se haya desactivado el scripting de SAP. No deberia de mostrar SAP un mensaje indicando que se esta iniciando desde un script? Porque el problema esta en que no muestra dicho mensaje y tampoco escribe.

**Comment by jaristimuno** [comment]
Efectivamente por mas que no muestra el mensaje de que se esta intentando acceder a traves de un script, el valor estaba en false. Fue modificado y funcionó
