### ISSUE TITLE
[TITAN] Necesito pasar contenido del portapapeles a una variable.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#135]
Entiendo que contamos en el MixedReader con _LoadVarToClipboard_ que copia el contenido de una variable al portapapeles. Lo que necesito es una instrucción que haga exactamente lo contrario; pasar del portapapeles a una variable.

Lo necesito a más tardar para el martes 28/05 .

**Comment by gantonioid** [comment]
Qué tipo de dato tienes en el portapapeles?

**Comment by pabloreitanosofttek** [comment]
@CesarEmanuelLencina  además de responderle a @gantonioid  te pido que subas el script así tal vez el soporte puede ser más rápido.

¡gracias!

**Comment by CesarEmanuelLencina** [comment]
Lo que intento hacer es levantar un **string** que se encuentra en una celda de una aplicación de java. Vengo utilizando Titanium para moverme en dicha aplicación por lo que mi código para esa parte es el siguiente:

```
Titanium ClickImage Xb-Impuesto.PNG Timeout= 10000 NumberClicks= 1 ClickPosition= CENTER_RIGHT
Titanium ClickImage 13b-Copiar.PNG Timeout= 10000 NumberClicks= 1
#Acá iría el codigo para pasar el dato copiado a una variable.
```

En la siguiente imagen se pueden ver los pasos:
![tempsnip](https://user-images.githubusercontent.com/50213758/58419742-c95cdc80-8061-11e9-853b-78254a94a59d.jpg)

**Comment by CesarEmanuelLencina** [comment]
+ @pablorlmx

**Comment by gantonioid** [comment]
Te liberé un update que contiene la función `GetTextFromClipboard` la documentación está pendiente de subir, pero se usa así:
`GetTextFromClipboard and save as "username"`
A partir de ahí, sirve como cualquier otra variable.
Es importante mencionar que detonará error si el portapapeles tiene algo que no sea texto.

**Comment by gantonioid** [comment]
Documentación disponible.
[http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/GetTextFromClipboard](url)

Por favor comenta los resultados de tu prueba con la instrucción.

**Comment by CesarEmanuelLencina** [comment]
Lo acabo de probar y funciona perfectamente. Se puede cerrar el issue.

Muchas gracias.
