### ISSUE TITLE
[TITAN] Copiar rangos entre hojas

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#136]
La instruccion falla, el log no da mucho detalle, unicamente marca " error", adjunto script y log para su analisis.
[CopyRangePRF.txt](https://github.com/FridaSupport/TuringSuport/files/3218412/CopyRangePRF.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3218415/log.txt)

Quedo atento.
Slds.

**Comment by FaustinoLechuga** [comment]
Esta función es especifica de un proceso, pero tal vez esta función te sirva. [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/CopyRange](url)

Eliminare la función de la documentación para evitar confusiones.

**Comment by JuanIgnacioBurgos** [comment]
@FaustinoLechuga Hola, la funcion que me sugeris no me permite copiar un rango de celdas a otra hoja, que es justamente lo que estoy precisando, lo que hace la instruccion "CopyRange" es mover dentro de una misma hoja un rango de celdas, reitero esto no me sirve.

@gantonioid Entiendo que se habia acordado el NO cerrar tickets sin la aprobacion del usuario, por lo que por favor pido que se vuelva a abrir dado que el problema no fue solucionado.

**Comment by JuanIgnacioBurgos** [comment]
Y por favor hacer el esfuerzo de mantener la documentacion lo mas actualizada posible, ya que nosotros nos basamos en ella para realizar el desarrollo de los bots.

**Comment by gantonioid** [comment]
Juan, recién describiste la necesidad hace una hora. Antes el ticket no era válido. Ayúdanos a ayudarte.

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid entiendo lo que decis, de igual manera les habia adjuntado el script desde un principio, voy a explicarme un poco mejor para la proxima.

Gracias, slds.

**Comment by gantonioid** [comment]
@JuanIgnacioBurgos por favor prueba la función Copy, la cual tiene poco clara la documentación pero aquí te pongo un ejemplo funcional:

Cargar libro1 y copiar (toda la hoja) a otra hoja que puede ser de otro libro.
Especial atención en que **copiada** (nombre de la hoja de destino) se crea automáticamente si no existe dentro del libro2.
Además, **copiada** es el nombre de la hoja dentro del archivo de Excel, que no es necesariamente el nombre que le diste si es que ya la cargaste con LoadWSheet
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\unLibro.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\libro2.xlsx" as libro2
Excel Copy values from hoja to libro2 sheet_name copiada start_at F5 transpose false
SystemNotify Type "notification" with message "breakpoint"
```
Dime si te sirve. Hoy es feriado para algunos de nosotros en México, puede haber demora en las respuestas.

**Comment by JuanIgnacioBurgos** [comment]
Perfecto, lo voy a probar, luego te comento si tuve algún inconveniente.

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid Acabo de  probarlo, quizas este cometiendo algun error yo, pero la instruccion me da Error, comparto script y log:

[Copy.txt](https://github.com/FridaSupport/TuringSuport/files/3224321/Copy.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3224324/log.txt)

**Comment by gantonioid** [comment]
Checa que el start_at es la celda superior izquierda de donde quieres empezar a pegar, y le estás dando un rango.

**Comment by JuanIgnacioBurgos** [comment]
Ya quedo, al perecer estaba cometiendo el error de poner un rango luego de start_at, la instruccion correcta seria:
Excel Copy values from WSasiento to WBmacro sheet_name Sheet2 start_at A1 transpose false
