### ISSUE TITLE
[TITAN]CopyRange  copea datos nulos vacios

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#137]
Buenos Dias

Se esta utilizando CopyRange varias veces en un mismo excel y en la misma pestaña.  la sentencia  se ejecuta con normalidad. pero parece que también copea las celdas vacías. y al momento de volver a usar CopyRange  lo hace en una celda mucho mas abajo.

se adjunta los insumos
[OBIEE X CTA. 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3224127/OBIEE.X.CTA.27-03.xlsx)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3224129/codigo.txt)
[LogTransacciones.xlsx](https://github.com/FridaSupport/TuringSuport/files/3224130/LogTransacciones.xlsx)

**Comment by JuanISalazarM** [comment]
Seguro veré cual es el problema.

**Comment by pabloreitanosofttek** [comment]
@JuanISalazarM  ¿Que avance hay?
¡gracias! 

@rrrios  ¿Para que fecha lo necesitas? ¡Gracias!

**Comment by rrrios** [comment]
@pabloreitanosofttek  lo mas pronto posible, ya que la otra semana se requiere, para entrega al cliente.

**Comment by JuanISalazarM** [comment]
@pabloreitanosofttek Buenas tardes. Se ha optado implementar una nueva función. Dado que se ha encontrado otra solución utilizando ApplyFilter, sin embargo, los valores son almacenados en una variable. Por tanto, la nueva función desplegará los valores almacenados en la variable.
Agradezco su comprensión. Excelente fin de semana.

**Comment by pablorlmx** [comment]
Estimado @FridaSupport, pueden dar prioridad a esto por favor! esta semana debemos poder resolver el tema y hoy es un stopper. incluyo a @RickProductivity

**Comment by JuanISalazarM** [comment]
Seguro, se han estado realizando pruebas con dos nuevas funciones. Se estaría liberando versión para su testing antes de terminar el día de hoy.
Gracias por su atención.

**Comment by gantonioid** [comment]
@pablorlmx este ticket requirió de **dos** funciones nuevas. Se están terminando de probar para hacer el release.

**Comment by JuanISalazarM** [comment]
Se ha actualizado el Turing de @rrrios 
Además, a través de TEAMS se han señalado observaciones acerca del nuevo Script.
Tengan un excelente día.

**Comment by pablorlmx** [comment]
Gracias!

________________________________

**Comment by gantonioid** [comment]
Necesitamos que nos reporten el resultado de la prueba

**Comment by rrrios** [comment]
Buenos días 

se realizo la prueba con el código sugerido por el teams y salió un error
se adjunta el código y el log generado

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3257774/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3257776/codigo.txt)

**Comment by JuanISalazarM** [comment]
Buenos días. Se ha revisado el error. Posiblemente Turing no se actualizó de manera correcta.
Se ha realizado un nuevo Update. Favor de volver a correr la automatización porfavor. Espero su respuesta.

**Comment by rrrios** [comment]
de acuerdo con lo conversado en el teams y a las pruebas unitarias con la implementación de los campos nulos y vacíos se da el caso como exitoso
