### ISSUE TITLE
Consulta: Metodo para enviar un archivo PDF por mail

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#138]
Existe alguna instrucción que adjunte un archivo .pdf y lo envíe a un destinatario de correo

**Comment by eradgg** [comment]
Hola Victor, en la documentación de Mixed reader en Automation platform puedes revisar la función SendMail:
Aquí te pongo el ejemplo, pero eso está en la documentación.

SendMail with subject "Test Send Mail" to "a.b@softtek.com" with body "Test mail" and a file attachment "C:File"

**Comment by victorgamboa** [comment]
Gracias Eder, pero al enviar el mail, el remitente del correo es turing@softtek.com
Necesito enviarlo de otro remitente por ejemplo soporte.clientes@finning.com

**Comment by gantonioid** [comment]
Victor, por ética y seguridad no podemos suplantar la identidad de nadie. Por eso el remitente es Turing Platform <turing@softtek.com>

**Comment by victorgamboa** [comment]
Entonces que puedo hacer? el cliente necesita usar su correo para el envió de cotizaciones

**Comment by gantonioid** [comment]
@eradgg @andresCruzF

**Comment by gantonioid** [comment]
Hay una instrucción que permite enviar correos utilizando el Outlook configurado en la máquina del usuario que está corriendo Turing.
@eradgg puede dar más referencia.

**Comment by eradgg** [comment]
Resuelto. Se probó con la función SendEmailAttachements BoClientesMail To "ederr.garcia@softtek.com" Subject "Prueba datos" Attachements "Test.htm" Path "C:\Users\EDERR.GARcia\Documents\Proyectos\Finning\SOFIA", resulve la necesidad.
