### ISSUE TITLE
Instruccion SortColumns, para multiples criterios de ordenamiento?

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#14]
Buenas tardes,
estaria necesitando realizar un sort en una planilla excel, (igual al de la imagen adjunta), en el cual se tienen en cuenta varios criterios de ordenamiento en simultaneo. Segun veo en la documentacion de la instrucción se indica que esta funcionalidad "aún se encuentra en desarrollo"

Queria consultarles en que estado se encuentra y si es posible utilizarla, ya que me seria muy util.
<img width="394" alt="2019-04-23 15_56_54-DocDef - ETV prosegur - Excel" src="https://user-images.githubusercontent.com/49756974/56608456-30115500-65e1-11e9-97a7-4373fabe9339.png">

La linea de codigo que tendria que utilizar para realizar este orden entiendo que seria la siguiente:
Excel SortColumns in Hoja4 in UsedRange by columns {6/ascending,2/ascending,3/ascending} header Yes
Aunque por el momento me da error.

**Comment by FaustinoLechuga** [comment]
Aun no esta terminada, pero por el momento se puede utilizar la instrucción que hace el sort individual por cada columna.

**Comment by JuanIgnacioBurgos** [comment]
Hola Faustino, existe la posibilidad de realizar un Sort en un rango especifico y no en toda una columna?

**Comment by FaustinoLechuga** [comment]
Por el momento no pero estaremos trabajando en ello

**Comment by RickProductivity** [comment]
Pero viendo la imagen , si te sirve el sort por columna no?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JuanIgnacioBurgos** [comment]
Si, aunque en el mismo proceso más adelante se me presenta una situacion en la que no, es por eso que aprovechaba para consultar...

**Comment by pabloreitanosofttek** [comment]
Hola, ¿Cuál es la fecha de necesidad? ¡gracias!

**Comment by gantonioid** [comment]
Ayudaría también ver el archivo de log.
Gracias

**Comment by JuanIgnacioBurgos** [comment]
Hola, no es algo crucial, pude resolverlo aplicando filtros individuales en cada columna, aunqe entiendo que no es lo mas optimo, ya que estaria escribiendo 5 lineas de codigo pudiendo resolverse en una unica linea.

Aunque no vendria mal en un futuro cercano tener una instruccion para realizar ordenamientos con varios criterios y Tambien poder especificar en que rango se quiere aplicar, ya que no siempre se busca ordenar toda una columna, sino que solo una parte.

Gracias, Saludos.

**Comment by gantonioid** [comment]
Gracias @JuanIgnacioBurgos !

**Comment by gantonioid** [comment]
Ya está hecha la función de SortColumns por hasta tres columnas (asc y desc). Pendiente de release.
