### ISSUE TITLE
Mal funcionamiento en Excelium ApplyFilter

### ISSUE THREAD

**Issue by CristianCelano** [FridaSupport/TuringSuport#140]
Necesito filtrar un excel para quedarme con unos elementos deteminados y no me funciona la instruccion ApplyFilter.

Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1
Excel LoadWSheet book1 sheet "abril" as hoja1
Excel ApplyFilter to the worksheet hoja1 to the column with the index {13} with the criteria "TBKCREDITO"
#Excel Filter in hoja1 in column 13 with criteria TBK CREDITO
Titanium Sleep 4000
Excel Save book1 and close
CopyColumn 9 from hoja1 start_at 1 to the sheet hoja2 in column 9 start_at 1

![2019-05-27 16_28_41-RunWindow](https://user-images.githubusercontent.com/49986799/58436766-730d8f00-809d-11e9-8434-c5cd950ead70.png)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3224827/log.txt)
[ERROR.txt](https://github.com/FridaSupport/TuringSuport/files/3224828/ERROR.txt)

**Comment by andresCruzF** [comment]
Hola @CristianCelano 

He realizado pruebas y no me presenta error el programa , me tome la libertad de mandarte un update para estar seguros que estamos corriendo la version (ID 20190529T0106) mas actual del programa , de igual forma adjunto un script de prueba similar al tuyo y un archivo con el cual lo podras valdiar. 

Saludo quedo al pendiente si se te sigue presentando el problema 

_GetHome
Excel LoadWBook "<<File>>" as book1
Excel LoadWSheet book1 sheet_index 1 as hoja1
#Excel LoadWSheet book1 sheet "abril" as hoja1
Excel ApplyFilter to the worksheet hoja1 to the column with the index {2} with the criteria "TBKCREDITO"
Titanium Sleep 4000
Excel Save book1 and close_

[Book1.xlsx](https://github.com/FridaSupport/TuringSuport/files/3230224/Book1.xlsx)

**Comment by CristianCelano** [comment]
Hola @andresCruzF 

Se me actualizo el turing a la version 20190429T0519, pero no es la vercion que vos mencionas en el mensaje anterior.
Probe de nuevo con el codigo que paste y tampoco funciona.
Podriamos probar con actualizar el turing a la version que antes mencionaste? (ID 20190529T0106)
Desde ya muchas gracias.

Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1
Excel LoadWSheet book1 sheet_index 1 as hoja1
Titanium Sleep 4000
#Excel LoadWSheet book1 sheet "abril" as hoja1
Excel ApplyFilter to the worksheet hoja1 to the column with the index {13} with the criteria "TBKCREDITO"
Titanium Sleep 4000
Excel Save book1 and close

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3232596/log.txt)

**Comment by andresCruzF** [comment]
Hola @CristianCelano 

Me podrias compartir el archivo de Excel por Teams , he realizado pruebas con ambas versiones y funciona sin mayor problema por lo que me gustaria analizar el archivo, unicamente te pido lo coloques en teams para evitar que se encuentre en este git publico.

Saludos.

**Comment by andresCruzF** [comment]
Hola @CristianCelano 

Ya quedo resulto el problema por lo que te comparto el ID  20190529T0413 de la nueva version para que lo puedas validar , saludos.

**Comment by CristianCelano** [comment]
Funciona! Muchisimas gracias!
