### ISSUE TITLE
[Exellia] Se requiere dar clic en un teclado virtual

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#141]
Buenas tardes, se requiere ingresar una contraseña por medio del teclado virtual de la pagina https://interbank.pe/
Pasos para llegar al teclado
hacer clic en Vanca por internet --> Empresas
![image](https://user-images.githubusercontent.com/25591982/58436999-5e7dc680-809e-11e9-8df3-bf55caba3911.png)

Dar clic en ingrese su clave Web
![image](https://user-images.githubusercontent.com/25591982/58437140-f976a080-809e-11e9-8d23-96db307568db.png)

![image](https://user-images.githubusercontent.com/25591982/58437127-ea8fee00-809e-11e9-9f28-710312d06291.png)

Se requiere la finalización del TK para el 28/05

**Comment by carlosortiz632** [comment]
Hola @SoledadNunez. Puedes probar con el siguiente xPath?

`//button[contains(text(),'5')]`

Ejemplo:
```
Web2 Click in xpath="//button[contains(text(),'5')]"
Web2 Click in xpath="//button[contains(text(),'3')]"
```

Saludos!

**Comment by SoledadNunez** [comment]
Funciono sin problemas, muchas gracias.

**Comment by gantonioid** [comment]
#130
