### ISSUE TITLE
Web2 Extract from selector No encuentra el objeto

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#142]
Devuelve el error "{"error":"Element not found"}"

**Comment by gantonioid** [comment]
Hace falta la url donde esto sucede, qué elemento estás buscando, instrucción específica y algún screenshot. El ticket tal cual está publicado no es válido.

**Comment by carlosortiz632** [comment]
@gantonioid Este ticket fue subido nuevamente ya que el primero lo eliminamos nosotros. Tengo toda la info necesaria para trabajar en él.

**Comment by gantonioid** [comment]
Entendido, gracias.
