### ISSUE TITLE
[TITAN] Criterio de filtrado "≠variable"

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#143]
Me encuentro con que necesito aplicar un filtro con el criterio "distinto a" una variable, entiendo que la syntaxis es la siguiente: 
Excel ApplyFilter to the worksheet WSpegado to the column with the index {1} with the criteria "<><<<value>>>" and delete the rows

pero no obtengo los resultados deseados, es decir, no se eliminan aquellos valores que son distintos al valor de mi variable.
¿cual seria la sytaxis correcta?

<img width="695" alt="-EditInstructionsWindow" src="https://user-images.githubusercontent.com/49756974/58437532-c3d2b700-80a0-11e9-8f14-9e6d0dcab0c9.png">

Gracias.
Slds.

**Comment by JuanIgnacioBurgos** [comment]
PD: si en lugar de una variable "hardcodeo" directamente el valor, el filtro funciona bien, el problema se da a la hora de querer hacerlo con una variable de por medio.

Excel ApplyFilter to the worksheet WSpegado to the column with the index {1} with the criteria "<>Valor" and delete the rows

Esto funciona, filtra y luego elimina todas las celdas que sean distinas a "Valor"

**Comment by JuanIgnacioBurgos** [comment]
hola, alguna novedad?

**Comment by gantonioid** [comment]
Hola
Con mi versión (20190529T0106) puedo filtrar valores diferente a una variable.

Mi script:
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\b1.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
DefineVariable type "string" as "var" with the value "a"
SystemNotify Type "notification" with message "Breakpoint"
Excel ApplyFilter to the worksheet hoja to the column with the index {1} with the criteria "<><<<var>>>" and delete the rows
SystemNotify Type "notification" with message "Breakpoint"
```
el libro que uso:
[b1.xlsx](https://github.com/FridaSupport/TuringSuport/files/3233172/b1.xlsx)

**Comment by gantonioid** [comment]
Veo que tú tienes esa misma versión 20190529T0106

**Comment by gantonioid** [comment]
En otra prueba, este script con el archivo del usuario funciona correctamente
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\jib.xlsm" as libro
Excel LoadWSheet libro sheet_index 9 as hoja
Excel GetUnique values from "hoja" col_index "1" start_at 2 as Fechas
foreach value in Fechas {
if ("02.04.19" -eq "<<<value>>>")
SystemNotify Type "alert" with message "Breakpoint"
Excel ApplyFilter to the worksheet hoja to the column with the index {1} with the criteria "<><<<value>>>" and delete the rows
SystemNotify Type "alert" with message "Breakpoint"
end
}
```
Se solicitó una sesión online para verlo a detalle

**Comment by JuanIgnacioBurgos** [comment]
Solucionado, se tenia una version de Turing desactualizada.

Sentencia correcta:
Excel ApplyFilter to the worksheet WSpegado to the column with the index {1} with the criteria "<><<<value>>>" and delete the rows
