### ISSUE TITLE
[URGENTE] Error loading files.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#144]
Estamos teniendo el siguiente error al intentar editar instrucciones con Turing.

![Captura](https://user-images.githubusercontent.com/50213758/58480452-c2e96600-8130-11e9-9097-394a9c4bda6d.PNG)

Por favor solucionarlo lo antes posible. La producción está parada.

**Comment by carlosgiraldo** [comment]
Buenos días, yo también estoy teniendo el mismo problema.

![Error_archivos](https://user-images.githubusercontent.com/14879161/58481352-d8a35f00-8121-11e9-9985-38194a659003.png)

Agradezco la ayuda.

**Comment by gantonioid** [comment]
Ver de nuevo por favor, debe de estar solucionado.

**Comment by CesarEmanuelLencina** [comment]
Efectivamente ya nos está funcionando correctamente, muchas gracias por su pronta respuesta.

**Comment by carlosgiraldo** [comment]
Gracias, a mi ya me funciona.
