### ISSUE TITLE
Urgente: Error al abrir Edit Instruccions

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#145]
Hasta el día de ayer la solapa "Edit Instruccions" funciona asin problemas, hoy me da el siguiente error,

![image](https://user-images.githubusercontent.com/49756748/58480744-f7592400-8128-11e9-9cf4-62769fe9d74d.png)

**Comment by gantonioid** [comment]
Ver de nuevo por favor, debe de estar solucionado.

**Comment by victorgamboa** [comment]
Muchas gracias!
