### ISSUE TITLE
[FRIDA] Consulta ejecución multiples Bots

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#146]
Buenas,
¿Como están?

Tenemos una duda respecto a la ejecución de bots paralelos dentro de una misma máquina virtual... supongamos el siguiente escenario:

1) 3 bots dentro de la misma maquina (B1-B2-B3) scheduleados a las 9-10-11hs (respectivamente)
2) Sólo tenemos un usuario válido para la ejecución (por ejemplo: un único usuario SAP)

Que pasa si:

B1 corre a las 9hs y tarda más de 1 hora (por la razón que fuese) y debe empezar el B2? ¿Lanza error? ¿Se auto-corre luego B2? ¿Avisa de lo que hizo? Pensamos en 2 sesiones... ¿Anda realmente FRIDA así? ¿Está probado? ¿Hay ejemplos? ¿El log como queda? ¿En caso de que falle una de las 2 sesiones... avisa cual de las 2? ¿Son 2 turings distintos?

y luego que pasa con B3? se ejecuta normal o hay que tener algún tipo de intervención humana?

¡Gracias! 

Prioridad: Media
Fecha esperada: 03/06.

¡Gracias!
Slds,

**Comment by gantonioid** [comment]
Hola Pablo, lo contesté en el tk #52 pero pides mayor nivel de detalle, para esto sumo a @andresCruzF

**Comment by pabloreitanosofttek** [comment]
Gracias! @gantonioid  es algo más puntual porque me surgieron dudas nuevas. 
Espero la respuesta de @andresCruzF 

Slds,

**Comment by andresCruzF** [comment]
Hola @pabloreitanosofttek 

Existen varias maneras de atacar este tipo de problemas, de manera inicial dependería de la tecnología que se vea involucrada. En el caso específico de SAP y Web si se corren dos procesos en simultaneo el segundo proceso marca error ya que el primer proceso tiene ocupados los recursos de chromedriver.exe , browpet-engine y Interop.SAPFEWSELib.dll ya que por cada Turing únicamente existe uno , en caso de querer correr varios se podría optar por tener varias copias de Turing para que cada una de estas corra un proceso en específico sin tener este conflicto de recursos.

Por otro lado, no hay problemas de correr varios procesos de Frida en simultaneo ya que se genera una instancia de TuringExpo cada que se arranca el programa por lo que los procesos de procesamiento o de Excel funcionan sin mayor problemas en paralelo.

Así mismo si se están ejecutando de manera remota la plataforma de FRIDA se encarga del balanceo de cargas colocando los procesos en fila de tal manera que no se ejecuta el segundo hasta no haber terminado la ejecución del primero, manteniendo una fila que se puede evitar conectando varias computadoras y dejando que la plataforma realice la acción de balancear las cargas usando siempre alguna de las computadoras libres.

**Comment by pabloreitanosofttek** [comment]
Joya! Tendrán algún ejemplo o en algún cliente haciendo esto?  Cambia la forma en que programamos?

¡gracias!
De: andresCruzF <notifications@github.com>
Enviado el: martes, 28 de mayo de 2019 18:02
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
CC: Pablo Sebastián Reitano <pablo.reitano@softtek.com>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] [FRIDA] Consulta ejecución multiples Bots (#146)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hola @pabloreitanosofttek<https://github.com/pabloreitanosofttek>

Existen varias maneras de atacar este tipo de problemas, de manera inicial dependería de la tecnología que se vea involucrada. En el caso específico de SAP y Web si se corren dos procesos en simultaneo el segundo proceso marca error ya que el primer proceso tiene ocupados los recursos de chromedriver.exe , browpet-engine y Interop.SAPFEWSELib.dll ya que por cada Turing únicamente existe uno , en caso de querer correr varios se podría optar por tener varias copias de Turing para que cada una de estas corra un proceso en específico sin tener este conflicto de recursos.

Por otro lado, no hay problemas de correr varios procesos de Frida en simultaneo ya que se genera una instancia de TuringExpo cada que se arranca el programa por lo que los procesos de procesamiento o de Excel funcionan sin mayor problemas en paralelo.

Así mismo si se están ejecutando de manera remota la plataforma de FRIDA se encarga del balanceo de cargas colocando los procesos en fila de tal manera que no se ejecuta el segundo hasta no haber terminado la ejecución del primero, manteniendo una fila que se puede evitar conectando varias computadoras y dejando que la plataforma realice la acción de balancear las cargas usando siempre alguna de las computadoras libres.

**Comment by gantonioid** [comment]
**No olvidar que Titanium requiere elementos visibles en pantalla, si una ventana creada por un segundo proceso bloquea lo que Titanium está buscando, fallará**

Dicho lo anterior... Lo que cambia es la configuración del equipo, es decir... si como mencionaste en el post original tienes B1, B2, B3 con scheduling a las 9, 10 y 11 respectivamente, lo que se puede hacer es lo siguiente:
![image](https://user-images.githubusercontent.com/9600868/58588237-da098000-8224-11e9-965d-32d6a8743996.png)

Luego, usar el Turing dentro de la carpeta B1 para configurar el scheduling del B1 a las 9:00 como lo desean; el Turing de la carpeta B2 para schedulear B2 a las 10:00, y así sucesivamente.

De esa manera, cada Turing usará su propia copia de las librerías que requiere sin los problemas derivados de concurrencia en ese aspecto.

No cambia nada en la manera de programar los RPA

**Comment by pabloreitanosofttek** [comment]
Entonces algún tipo de control y gestión hay que hacer... sobretodo para los deploys (no en si para la cuestión de la creación).
¡gracias!
