### ISSUE TITLE
[TITAN]Error en CreatePivotTable

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#147]
Buenos Dias

Se esta implementando una automatización para una tabla dinámica, se están utilizando las sentencias que esta en la documentación del Desarrollo Frida wiki.

al momento de ejecutar la sentencia CreatePivotTable, genera error.

se adjuntas los insumos.

[LogTransacciones.xlsx](https://github.com/FridaSupport/TuringSuport/files/3228475/LogTransacciones.xlsx)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3228476/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3228478/codigo.txt)

**Comment by FaustinoLechuga** [comment]
Lo estare revisando

**Comment by FaustinoLechuga** [comment]
Este error se debe a que las Hojas se estan seleccionando de manera incorrecta, siempre que se cargen las hojas por medio del index hay que recordar que se cuentan de izquierda a derecha las hojas existentes en el libro.

Se cambiaron estas instrucciones del script:
Excel LoadWSheet bookLog sheet_index 2 as SheetBookLog
Excel LoadWSheet bookLog sheet_index 1 as Hoja2

Aparte de estas modificaciones elimine la primera fila del excel donde viene la infomacion de la tabla, de lo contrario no podra leer nada.

**Comment by rrrios** [comment]
Buenas tardes  @FaustinoLechuga 

atendiendo su sugerencia se implemento los cambios y funciono correctamente y se puede cerrar el ticket.

pero la sentencia Excel NewWs esta creando la pestaña al lado derecho del excel, hay alguna forma de crearlo a la izquierda

agradezco por la atención prestada y la solución brindada

**Comment by FaustinoLechuga** [comment]
Excel automaticamente abre la ventana de ese lado, solo hay que tener presente este tipo de detalles con los indices. Pero al crear un nuevo worksheet se le asigna ya un key asi que no deberia de haber ningun problema. Otra forma que se puede utilizar para evitar las confusiones es cargar las hojas por nombres.
