### ISSUE TITLE
[Consulta] Foreach dinamico

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#148]
Necesito ayuda con un Foreach dinámico, que se ejecute en SAP.
Lee los registros de un excel que se guardan en una variable y los inserta en una grilla en SAP. se debe aumentar automáticamente la grilla, para que inserte el segundo registro.

**Comment by eradgg** [comment]
Se habla  con Victor para ver este caso.

**Comment by eradgg** [comment]
Se explica el funcionamiento del for eache y como funciona el nogrid (arreglo de labels que simulan un grid) al agregar un nuevo elemento.
