### ISSUE TITLE
RunCustomLocal - problema con argumentos.

### ISSUE THREAD

**Issue by cgarcete** [FridaSupport/TuringSuport#15]
Problema con RunCustomLocal.

Debido a la coma (,) en el segundo argumento, no es posible ejecutar la siguiente instruccion:

RunCustomLocal ChangeDateFormatTipoDeCambio "BCP","Martes,#11#marzo#2019"

log:

4/23/2019 4:14:41 PM - Execution started
4/23/2019 4:14:41 PM - RunCustomLocal ChangeDateFormatTipoDeCambio "BCP","Martes,#11#marzo#2019": Running
4/23/2019 4:14:41 PM - Will run custom C:\Users\claudio.garcete\Documents\1259173227\App\/Local/922159886/0/CustomLocal/ChangeDateFormatTipoDeCambio\Release\ChangeDateFormatTipoDeCambio.jar
4/23/2019 4:14:41 PM - Running - File :  java
4/23/2019 4:14:41 PM - Running - Arguments : -jar C:\Users\claudio.garcete\Documents\1259173227\App\/Local/922159886/0/CustomLocal/ChangeDateFormatTipoDeCambio\Release\ChangeDateFormatTipoDeCambio.jar "BCP" "Martes" "#11#marzo#2019"
4/23/2019 4:14:41 PM - The CustomLocal finished running
4/23/2019 4:14:41 PM - RunCustomLocal ChangeDateFormatTipoDeCambio "BCP","Martes,#11#marzo#2019" : Success
4/23/2019 4:14:41 PM - : Running
4/23/2019 4:14:41 PM - Error: 
4/23/2019 4:14:41 PM - Error in  Instruction was't found
4/23/2019 4:14:41 PM -  : Error
4/23/2019 4:14:41 PM - Execution ended

Se adjunta el custom:

https://onesofttek-my.sharepoint.com/:u:/g/personal/claudio_garcete_softtek_com/EfOwgTXsOf9MvCh3YnwzPa4BLha_BzB6egTDv4h_s7WJJA?e=jFIPJT

Ejecutar por shell:

java -jar ChangeDateFormatTipoDeCambio.jar "Banrep" "Lunes#9#abril#de##2019"
java -jar ChangeDateFormatTipoDeCambio.jar "BCP" "Lunes,#9#abril#2019

**Comment by gantonioid** [comment]
Puedes prescindir de la coma? o usar otro símbolo en la instrucción RunCustomLocal, luego si la necesitas reemplázala en tu jar

La coma es nuestro separador de argumentos, así que si podemos resolverlo de alguna otra manera estaría mejor

**Comment by jaristimuno** [comment]
No se puede prescindir de la coma ya que es un valor que viene por deafult en una pagina y se toma todo el string como variable

**Comment by cgarcete** [comment]
> Puedes prescindir de la coma? o usar otro símbolo en la instrucción RunCustomLocal, luego si la necesitas reemplázala en tu jar
> 
> La coma es nuestro separador de argumentos, así que si podemos resolverlo de alguna otra manera estaría mejor

Si te referis a la coma que esta fuera de los argumentoss (""), coincido con vos. Pero en este caso la coma viene dentro, o sea, en el interior del segundo argumento (ver negrita)

RunCustomLocal ChangeDateFormatTipoDeCambio "BCP","Martes**,**#11#marzo#2019"

**Comment by gantonioid** [comment]
Sí Claudio. Me di cuenta que la coma que mencionas está dentro del parámetro.
Yo lo que digo es que no soportamos comas, debido a que son nuestro separador... Tu aportación es válida y entra como mejora.

Lo que dije es que en el script puedes cambiar el caracter ',' -> '*'
y dentro de tu CustomLocal, regresarlo '*' -> ','

De la siguiente manera (suponiendo que ya tienes la variable fecha = "Martes,#11#marzo#2019" )
```
ReplaceComma.txt (Powershell)
$s = "<<<fecha>>>"
$s = $s.replace(",", "*")
$res = "fecha2 : " + $s
Write-Output $res 
```

y en tu script principal tendrías
```
##Define variable fecha = "Martes,#11#marzo#2019"
PowerShell ReplaceComma.txt
##Aquí tienes fecha2 = "Martes*#11#marzo#2019"
RunCustomLocal ChangeDateFormatTipoDeCambio "BCP","<<<fecha2>>>"
```

Dentro de tu Custom vuelve a hacer el replace de ( * ) a ( , )
