### ISSUE TITLE
[Consulta] Instrucción para capturar un campo e insertar una variable

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#150]
Probé con dos instrucciones para capturar ese campo pero me da error.

![image](https://user-images.githubusercontent.com/49756748/58509600-e75f3580-8164-11e9-8e3f-58132ad46137.png)

**Comment by gantonioid** [comment]
Qué instrucciones? tienes el log? por favor agregar más detalles para el soporte

**Comment by victorgamboa** [comment]
Error: Error in SAP SelectTab id wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\07/ssubSUBSCREEN_BODY:SAPMV45A:4352/subSUBSCREEN_PARTNER_OVERVIEW:SAPLV09C:1000/tblSAPLV09CGV_TC_PARTNER_OVERVIEW/ctxtGVS_TC_DATA-REC-PARTNER[1,3] "3482798"

Log:  5/28/2019 5:05:23 PM - SAP ClickButton id wnd[0]/usr/subSUBSCREEN_HEADER:SAPMV45A:4021/btnBT_HEAD: Running
5/28/2019 5:05:26 PM - SAP ClickButton id wnd[0]/usr/subSUBSCREEN_HEADER:SAPMV45A:4021/btnBT_HEAD : Success
5/28/2019 5:05:26 PM - SAP SelectTab id wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\07: Running
5/28/2019 5:05:27 PM - SAP SelectTab id wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\07 : Success
5/28/2019 5:05:27 PM - SAP SelectTab id wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\07/ssubSUBSCREEN_BODY:SAPMV45A:4352/subSUBSCREEN_PARTNER_OVERVIEW:SAPLV09C:1000/tblSAPLV09CGV_TC_PARTNER_OVERVIEW/ctxtGVS_TC_DATA-REC-PARTNER[1,3] "3482798": Running
5/28/2019 5:05:27 PM - error: SelectTab id wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\07/ssubSUBSCREEN_BODY:SAPMV45A:4352/subSUBSCREEN_PARTNER_OVERVIEW:SAPLV09C:1000/tblSAPLV09CGV_TC_PARTNER_OVERVIEW/ctxtGVS_TC_DATA-REC-PARTNER[1,3] "3482798" : System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'SAPFEWSELib.GuiTab'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{43D61F6A-338A-4613-BC3C-C795C573266E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at SapScriptReader.SapScriptExecute.SelectTabById(String TabId) in C:\Users\EDERR.GARcia\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 1184
   at SapScriptReader.SapScriptExecute.SelectTab(String action) in C:\Users\EDERR.GARcia\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 1166
5/28/2019 5:05:27 PM - SAP SelectTab id wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\07/ssubSUBSCREEN_BODY:SAPMV45A:4352/subSUBSCREEN_PARTNER_OVERVIEW:SAPLV09C:1000/tblSAPLV09CGV_TC_PARTNER_OVERVIEW/ctxtGVS_TC_DATA-REC-PARTNER[1,3] "3482798" : Error
5/28/2019 5:05:27 PM - error: selectm id "wnd[0]/mbar/menu[4]/menu[12]" : System.Runtime.InteropServices.COMException (0x0000026F): The menu item is disabled.
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.IGuiMenuTarget.Select()
   at SapScriptReader.SapScriptExecute.SelectMenuById(String MenuId) in C:\Users\EDERR.GARcia\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 1685
   at SapScriptReader.SapScriptExecute.SelectMenu(String action) in C:\Users\EDERR.GARcia\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 1663
5/28/2019 5:05:27 PM - Execution ended

**Comment by eradgg** [comment]
¿Me puedes mandar el script? veo que usas la instrucción SelectTabId pero el id es de una label.

**Comment by victorgamboa** [comment]
@eradgg, ya lo pude resolver gracias.

Pero tengo otro problema, que instrucción debería utilizar para escribir un texto en el siguiente campo?
Tengo que insertar una variable en ese campo:

Nombre del Campo en Scripting:
session.findById("wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\08/ssubSUBSCREEN_BODY:SAPMV45A:4152/subSUBSCREEN_TEXT:SAPLV70T:2100/cntlSPLITTER_CONTAINER/shellcont/shellcont/shell/shellcont[1]/shell").text = "Cotizaciòn" + vbCr + "" + vbCr + ""

session.findById("wnd[0]/usr/tabsTAXI_TABSTRIP_HEAD/tabpT\08/ssubSUBSCREEN_BODY:SAPMV45A:4152/subSUBSCREEN_TEXT:SAPLV70T:2100/cntlSPLITTER_CONTAINER/shellcont/shellcont/shell/shellcont[1]/shell").setSelectionIndexes 11,11

Luego presionar botón Guardar
session.findById("wnd[0]/tbar[0]/btn[11]").press


![image](https://user-images.githubusercontent.com/49756748/58569105-77ec5300-8203-11e9-86e0-744c6ff0fa0b.png)

**Comment by victorgamboa** [comment]
aparte de Eder quien mas me puede ayudar? lo necesito urgente...

**Comment by eradgg** [comment]
Ya lo revisé, se tiene que agregar el control a Sapscript, hay que hacer un cambio, lo tendré listo para hoy tarde o mañata temprano para probar

**Comment by eradgg** [comment]
Ya terminé el cambio Victor. Puedes usar la misma instrucción Write con el id de tu elemento.

**Comment by gantonioid** [comment]
Se cierra por “suspendido”
