### ISSUE TITLE
[EXCELLIA] - SAP aceptar ventana de guardar archivo al ser exportado.

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#151]
Buenas tardes, Al dar la opción de exportar (generar  archivo excel), llego hasta la instancia que muestro en la siguiente imagen:
![imagen](https://user-images.githubusercontent.com/50331739/58512930-aec75800-8174-11e9-9448-e9ae5dcaf37c.png)
Intente con presionar Enter tanto con SAP como Titanium y no logro que el bot lo realice, porque manualmente con enter ya lo guarda.
Grabe con el Sap Recorder y tampoco supero esa instancia, igual que con el grabador de SAP.
¿Hay alguna instrucción? o ¿como hago para que presione en guardar?.
Desde ya muchas gracias!

**Comment by eradgg** [comment]
Hola Marianela.
Esta es una ventana de windows, el export debería de manejarlo pero a veces varía. ¿Me puedes indicar qué proceso es? para hacer la prueba ver sio necesita algún cambio.

**Comment by MarianelaDuarte** [comment]
Hola Eder!,el Process ID es: 1979440310, claro ya es ventana de windows, por eso pensé que con darle enter con Titanium iba  a funcionar pero llevo horas tratando de solucionar jaja.
Gracias!, si necesitas algun dato de ingreso hablame asi te lo envío por privado.
Saludos

**Comment by eradgg** [comment]
Lo que pasa es que SAP se queda esperando para que se cierre esta ventana y ya no ejecuta ninguna otra instrucción. Tengo algo que soluciona esto, pero no había probado con el de Save As. Lo pruebo y te mando la solución.

**Comment by MarianelaDuarte** [comment]
Lo que necesito es exportar, no importa si es save as, o no hice lo que tuve al alcance y lo que vi que hacia el usuario, si ves que haciendo save solo, no hay problema, voy por ese camino. ;)

**Comment by eradgg** [comment]
Ya casi termino el cambio, estoy haciendo pruebas, una vez terminado te subo una versión, si tuve que modificar el código.

**Comment by MarianelaDuarte** [comment]
Genial! Muchas Gracias Eder, aguardo tu actualización.
Saludos.

**Comment by eradgg** [comment]
Hola Marianela.

Ya está terminado. te envié una actualización para probarlo.
Modifiqué la función ManageWinCtl para poder manejar las ventanas.
Tu script ya lo modifiqué, debe de funcionar así como está.

Si tienes algún problema o duda estoy a tus órdenes.

**Comment by MarianelaDuarte** [comment]
Hola Eder, lo corrí al script tal cual esta y funciona igual que antes, se queda en la ventana para guardar.
¿Debería modificarle algo más?

**Comment by pabloreitanosofttek** [comment]
@eradgg, @MarianelaDuarte  ¿pudieron verlo? 

¡Gracias!

**Comment by MarianelaDuarte** [comment]
Buenas tardes @pabloreitanosofttek: 
No, hoy lo tenemos que ver, estoy a la espera que Eder este disponible para verlo.

**Comment by MarianelaDuarte** [comment]
Esta caído SAP del cliente asi que no vamos a poder verlo hasta que vuelva el servicio. Ya nos comunicamos con Eder pero no puedo ejecutar el proceso.

**Comment by pabloreitanosofttek** [comment]
@MarianelaDuarte  pudieron probar? ¡Gracias!

**Comment by MarianelaDuarte** [comment]
Hola @pabloreitanosofttek nos reunimos hoy, efectivamente no funcionaba asi que Eder lo esta revisando nuevamente. Por ende, sigue el ticket abierto.
En cuanto funcione ok lo cierro.
Saludos

**Comment by MarianelaDuarte** [comment]
Luego de varios intentos con Eder, pudo solucionar el problema correctamente asi que doy por cerrado el ticket.
