### ISSUE TITLE
[TITAN] Instruccion MultiFilter, agregar criterio "distinto a" y "and delete rows"

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#152]
Buenas, en determinada columna de un excel preciso quedarme unicamente con dos valores e eliminar el resto de valores, habia pensado hacerlo de la siguiente manera:

Excel ApplyFilter to the worksheet WSpegado to the column with the index {2} with the criteria "<>111010264" and delete the rows
Excel ApplyFilter to the worksheet WSpegado to the column with the index {2} with the criteria "<>111010265" and delete the rows

Lo que ocurre es que al hacer esto, cuando se aplica la primer instruccion Tambien me borra aquellas filas con el dato de la segunda instruccion (algo logico)

Por eso es que pense en utilizar la instruccion Multifilter, pero me encuentro con que la misma no tiene la opcion de filtrar aquellos valores "distintos a" ni tampoco la opcion de eliminar estas filas con el "and delete rows"
La sentencia que busco seria algo asi:

**Excel MultiFilter from WSpegado in_column_index 2 with_criteria <>[111010264, 111010265] and delete the rows**

¿es viable implementar estas mejoras a la instruccion? es un paso clave en el proceso que estoy desarrollando.

Quedo atento.
slds.

**Comment by gantonioid** [comment]
Hola
La versión (20190529T0542) ahora contiene expansión para la función KeepRows, servirá para lo que quieres hacer:
```
KeepRows from wsheetA where 1 in ["Monday", "Tuesday", "Friday", "Sunday"]
KeepRows from wsheetA where 3 not ["Pizza", "Salad", "Soup"]
```

La sintaxis que dice "in", borrará todas las filas excepto las que en la col 1 tengan "Monday", "Tuesday"...
La sintaxis que dice "not" borrará todas las filas que en la col 3 tengan "Pizza", "Soup", "Salad"

**Comment by JuanIgnacioBurgos** [comment]
Perfecto, voy a estar probandolo! en breve les confirmo su funcionamiento

**Comment by JuanIgnacioBurgos** [comment]
Estuve realizando algunas pruebas, la instruccion funciona bien, pero me trae problemas para los pasos siguientes: luego de esta instruccion leo una columna y realizo una sumatoria de todos valores que hay en las celdas, lo que ocurre es que en lugar de tomar el valor de la celda por ej: 1004, me toma el valor individual de cada digito que hay en la celda y los suma, es decir, 1+0+0+4

Me resulta bastante curioso, ya que si comento la linea que agregue, la sumatoria se realiza de manera correcta, tomando 1004 y sumandole el siguiente valor

adjunto log y script....cualquiercosa por favor contactarme por Teams y lo vemos en una call, ya que quizas por aqui no queda muy claro.


[Copy.txt](https://github.com/FridaSupport/TuringSuport/files/3234075/Copy.txt)

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3234076/log.txt)

**Comment by gantonioid** [comment]
Se propuso como alternativa la función WriteFormula, se usará para continuar
