### ISSUE TITLE
[TITAN]WriteValueThatMatch  Error con valor no existente

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#153]
Buenos Dias

se esta implementando la sentencia WriteValueThatMatch, y en el maching the value se le envía un valor que no esta en esa columna. y genera error. por que FRIDA no encuentra el valor para filtrar. (lo cual seria algo lógico, por que no se encontró el dato para validar y no debería escribir).

les solicito de su amable colaboración para conocer una validación de que si el dato no existe no ejecute, se pensó en un ApplyFilter que guarda una lista. pero no eh visto ninguna sentencia que me indique el tamaño del list como una sentencia de (Count, lenght) o si es un list vacio. esto para validar antes de ejecutar el  WriteValueThatMatch y no generar error.

Agradezco por la atención prestada y estaré atento a cualquier comentario.

**Comment by JuanISalazarM** [comment]
Seguro lo atenderemos.

**Comment by FaustinoLechuga** [comment]
Nos podras comprartir porfavor el log y el script que estas usando, si se puede el excel tambien. Esto para poder tener un ejemplo y replicar el error que te sucedió y de esta manera poder hacer la mejora que solicitas.

**Comment by rrrios** [comment]
se adjuntan los insumos según lo requerido
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3234584/codigo.txt)
[reproceso.xlsx](https://github.com/FridaSupport/TuringSuport/files/3234585/reproceso.xlsx)
[LogTransacciones.xlsx](https://github.com/FridaSupport/TuringSuport/files/3234586/LogTransacciones.xlsx)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3234587/log.txt)

**Comment by FaustinoLechuga** [comment]
Te mande un update con un cambio en la instruccion de WriteValueThatMatch que te permite escribir un valor vacio como el ejemplo que venia en el log.

WriteValueThatMatch in the worksheet ShRepEx at the column {2} maching the value "130" and writing in the column {8} the value {}

**Comment by rrrios** [comment]
Buenas tardes @FaustinoLechuga 

atendiendo a tu sugerencia se actualizo Frida y se realizo la prueba con el código anteriormente adjuntado, con un resultado de que no genera error el código ejecutado.  basado en esto se podría cerrar el git.

pero si seria bueno saber cual seria el alcance de esta implementación para conocimiento tecnico.
 y lo otro si dentro de Frida hay algún comando como Count, lenght para saber el tamaño de los objetos que se están utilizando.

agradezco por la atención prestada y por la solución brindada.

**Comment by FaustinoLechuga** [comment]
¿A que te refieres con alcance? 
Lo unico que se cambio es que antes no aceptaba valores vacios en parametro que escribia en otra columna y ahora si. La instrucción sigue funcionando igual espero que esto resuelva tu duda.

Y de lo otro no estoy enterado que exista algún comando reciente que devuelva el tamaño del arreglo pero lo voy a consultar con el equipo.

**Comment by gantonioid** [comment]
No hay función que retorne el tamaño de un arreglo, está considerado para un futuro. No hay fecha definida.
