### ISSUE TITLE
[TITAN] Ejemplos de uso instrucción ClickCoordinates de Titanium

### ISSUE THREAD

**Issue by karenandrearueda** [FridaSupport/TuringSuport#155]
Solicito su colaboración con un ejemplo más especifico de como debo usar esta instrucción, en un caso especifico como por ejemplo realizar una selección de items con checkbox y que herramientas recomiendan para identificar las cordenadas en la pantalla.

Agradezco su pronta colaboración.

**Comment by gantonioid** [comment]
ClickCoordinates es para el caso muy específico en que no encuentres otra solución. También tiene sus desventajas.

Lo que tienes que hacer es tomar a mano un screenshot de tu pantalla y abrirla en Paint, esto te permitirá conocer las coordenadas _x_ y _y_ de donde quieres dar click
![coord](https://user-images.githubusercontent.com/9600868/58580519-ebe22780-8212-11e9-899a-fe260b6dc3d9.png)

Ya sabiendo las coordenadas, puedes usar la Instrucción, que en este caso por ejemplo el logotipo Softtek está en las coordenadas (681, 671)
`ClickCoord -x 681 -y 671 -clicks 1`

**Desventajas**
Puedes probar y estar segura que funciona en tu computadora, pero no tenemos la certeza de que en la máquina del cliente el logotipo esté en las mismas coordenadas.
Por lo mismo, es mejor ClickImage, pero la decisión es tuya.
