### ISSUE TITLE
[Consulta-SAP] Seleccionar una fila completa

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#156]
Instrucción para seleccionar esa fila y luego presionar botón Imprimir (Ctrl + P)

![image](https://user-images.githubusercontent.com/49756748/58639539-1d1b3000-82c5-11e9-9263-987e42026675.png)

Elements:
[Elements.txt](https://github.com/FridaSupport/TuringSuport/files/3237401/Elements.txt)

Scripting:
session.findById("wnd[0]").maximize
session.findById("wnd[0]/mbar/menu[0]/menu[5]").select
session.findById("wnd[1]/usr/tblSAPLVMSGTABCONTROL").getAbsoluteRow(0).selected = true

**Comment by gantonioid** [comment]
Qué has intentado?

Seleccionar la fila
[http://automationplatform.azurewebsites.net/Readers/Tools/SAP/SelectGridRow](url)

Click
[http://automationplatform.azurewebsites.net/Readers/Tools/SAP/ClickButton](url)

Se cierra la consulta.

**Comment by victorgamboa** [comment]
Si intente las dos, pero hay algo que no reconoce el campo, lo mismo que me paso en el Issues 150

**Comment by eradgg** [comment]
Hola Victor, mándame el show Elements por favor, como en el otro Issue para ver si se trata de otro tipo de elemento.

**Comment by victorgamboa** [comment]
te lo adjunte 
[Elements.txt](https://github.com/FridaSupport/TuringSuport/files/3238014/Elements.txt)

**Comment by eradgg** [comment]
Si es otro tipo de control. Necesito hacer también cambios para este. te aviso cuando lo termine.

**Comment by eradgg** [comment]
Ya quedó el cambio, subí una nueva versión para que preubes junto con el otro. 
Así es como tienes que usarla:
SAP SelectTableRow TableId wnd[1]/usr/tblSAPLVMSGTABCONTROL RowN 0
si tienes algún problema, seguimos en contacto.

**Comment by victorgamboa** [comment]
Muchas gracias Eder, lo pruebo y te comento

**Comment by gantonioid** [comment]
Se cierra por “suspendido”
