### ISSUE TITLE
Documentacion SAP Reader

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#157]
La funcion VerticalScroll tiene exactamente la misma sintaxis que la funcion GridCellDoubleClick.
![image](https://user-images.githubusercontent.com/49946883/58643585-f0bbdf80-82d5-11e9-8545-7bfcda219221.png)

![image](https://user-images.githubusercontent.com/49946883/58643265-4e9bf780-82d5-11e9-9ae4-89a9b6b3500f.png)

Prioridad: Media

**Comment by FaustinoLechuga** [comment]
Revisare a que se debe este error, muchas gracias por hacernos la observación.

**Comment by FaustinoLechuga** [comment]
Ya se corrigió esto.
