### ISSUE TITLE
[Titan] Instruccion que me permita escribir unicamente en las celdas visibles

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#158]
Buenas, preciso escribir unicamente en aquellas celdas de una colmuna que han quedado visibles luego de aplicar un filtro.

Puedo lograr esto con alguna de las intrucciones ya existentes?

Quedo atento.
Slds.

**Comment by gantonioid** [comment]
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteValueThatMatch](url)

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid si habia pensado en esa instruccion, el problema es que no en las demas columnas los valores se repiten por lo que si aplico el WriteValueThatMatch, me escribiria en todas las celdas que el valor coincide, esten visibles las celdas luego del filtro o no :(

**Comment by gantonioid** [comment]
Cómo haces el filtro? qué función, parámetros, etc

**Comment by JuanIgnacioBurgos** [comment]
Primero aplico los siguientes filtros, en tres columnas distintas

Excel ApplyFilter to the worksheet WScartola1sur to the column with the index {3} with the criteria "<>ABONO POR ERROR EN DEPOSITO"
Excel ApplyFilter to the worksheet WScartola1sur to the column with the index {2} with the criteria "ARICA"
Excel ApplyFilter to the worksheet WScartola1sur to the column with the index {6} with the criteria <>""

Una vez aplicados estos filtros necesito escribir en la columna 6 (solo en aquellas celdas que han qedado visibles)....(la escritura tambien depende de una validacion previa...pero esto ya lo tengo resuelto)

**Comment by gantonioid** [comment]
Se le tiene que escribir lo mismo a todas las celdas visibles? podríamos generar una variación de 
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteAll](url)

Algo así:
WriteAll "Tiendas" in Sheet4 start_at B4 **-visible**
Para escribir "Tiendas" en todas las filas abajo de B4 que estén visibles

Te parece?

**Comment by JuanIgnacioBurgos** [comment]
Me parece perfecto!!

**Comment by gantonioid** [comment]
@JuanISalazarM

**Comment by JuanISalazarM** [comment]
Seguro veré como puedo hacer la variación. Cualquier duda se la hago llegar por chat de Teams. Buenos días.

**Comment by gantonioid** [comment]
La versión 20190530T0608 ya tiene esta variación. Está documentada, pero es como lo expliqué arriba.
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteAll](url)

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid @JuanISalazarM Hola, con la nueva actualizacion me ocurre que no puedo realizar varios filtros en simultaaneo como tenia hasta hace unos momentos

Excel ApplyFilter to the worksheet WScartola1sur to the column with the index {3} with the criteria "<>ABONO POR ERROR EN DEPOSITO"
Excel ApplyFilter to the worksheet WScartola1sur to the column with the index {2} with the criteria "ARICA"
Excel ApplyFilter to the worksheet WScartola1sur to the column with the index {6} with the criteria =""

unicamente la planilla queda filtrada por el ultimo ApplyFilter, desfiltrando los dos primeros

**Comment by gantonioid** [comment]
Puedes probar MultiFilter y/o Filter? Para filtrar con varios criterios en una instrucción

**Comment by JuanIgnacioBurgos** [comment]
Con la instruccion filter, qedan los filtros en simultaneo, pero estoy teniendo problemas con el que tiene criterio <>, no lo estaria tomando como "distinto a" sino como parte del filtrado

Excel Filter in WScartola1sur in column 3 with criteria "<>ABONO POR ERROR EN DEPOSITO"

es correcta la syntaxis?

Por otro lado la instruccion multifilter dio error a la hora de querer filtrar con el criterio <>

Excel MultiFilter from WScartola1sur in_column_index 3 with_criteria [<>ABONO POR ERROR EN DEPOSITO] : Error

**Comment by gantonioid** [comment]
OK, mira este script
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\b1.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
Excel Filter in hoja in column 1 with criteria a
SystemNotify Type "Notification" with message "Breakpoint"
Excel Filter in hoja in column 2 with criteria d1
SystemNotify Type "Notification" with message "Breakpoint"
Excel Filter in hoja in column 3 with criteria <>g1
SystemNotify Type "Notification" with message "Breakpoint"
Excel WriteAll "El Producto" in hoja start_at D2 -visible
SystemNotify Type "Notification" with message "Breakpoint"
```

Estoy usando este archivo
[b1.xlsx](https://github.com/FridaSupport/TuringSuport/files/3238629/b1.xlsx)

El resultado (Quité el filtro manualmente para que se vea que escribe solo en las visibles)
![image](https://user-images.githubusercontent.com/9600868/58662072-f40f9500-82ee-11e9-9488-b95aa0fb3890.png)

**Comment by gantonioid** [comment]
> Con la instruccion filter, qedan los filtros en simultaneo, pero estoy teniendo problemas con el que tiene criterio <>, no lo estaria tomando como "distinto a" sino como parte del filtrado
> 
> Excel Filter in WScartola1sur in column 3 with criteria "<>ABONO POR ERROR EN DEPOSITO"
> 
> es correcta la syntaxis?

No, mira en mi ejemplo que no lleva comillas el criterio

**Comment by JuanIgnacioBurgos** [comment]
Puede ser que lo que necesito filtrar "ABONO POR ERROR EN DEPOSITO" lleve espacios, por eso no se filtra correctamente, recien probe con la siguiente instruccion:
Excel Filter in WScartola1sur in column 3 with criteria <>ABONO POR ERROR EN DEPOSITO

**Comment by gantonioid** [comment]
Sí, te estoy liberando la versión 20190530T0914. Ya funciona con espacios, **no necesita comillas**

**Comment by JuanIgnacioBurgos** [comment]
okey, voy a probarlo

**Comment by JuanIgnacioBurgos** [comment]
Quedo funcionando, les agradezco la pronta atencion, cierro el issue, saludos!
