### ISSUE TITLE
[Excellia] - Error en ApplyRegex

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#159]
El siguiente código me devuelve error:
DefineVariable type "string" as "valor1" with the value "12,361.00"
`ApplyRegex "/(?!,)([0-9]+)/g" to the string "<<<valor1>>>" and save as "valor1"`
El error devuelto es: "Regex generate a null result creating an Error"

**Comment by gantonioid** [comment]
puedes describir en palabras qué es lo que esperas obtener del regex? tal vez `"/(?!,)([0-9]+)/g"` no es correcto

**Comment by ignacionovio** [comment]
Necesito quitar la coma y el punto de ese string, para revisar la expresión regular lo hice en "https://regexr.com/" y funcionó

**Comment by gantonioid** [comment]
Un regex no manipula strings para quitar comas... tendrías que pasarle el string a un script de powershell que haga un string.replace de , por (string vacío)

**Comment by gantonioid** [comment]
Con la descripción dada, la solución es manejo de strings con PowerShell, no error de Regex. Cierro el tema. Referencia de uso de PowerShells con FRIDA en la wiki. [https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Powershell%20y%20Customs.one%7Cbd8098e4-0de8-43cb-9d8e-c59985399811%2FPowerShell%7C787ed60b-66ef-408f-9f3c-8621521b704f%2F%29&wdorigin=703](url)
