### ISSUE TITLE
Tengo un consulta, ¿es posible convertir un .csv a .xlsx?

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#16]
Tengo un consulta, ¿es posible convertir un .csv a .xlsx?

**Comment by gantonioid** [comment]
Hay una función de load csv
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/LoadWSContent](url)

Después puedes manejarla como una hoja normal, copiar de ahí y guardar

**Comment by MartinMedinaSTK** [comment]
No esta muy claro en la documentación como se usa, a que corresponde cada parámetro, por ejemplo "text" es un texto fijo? tendrás un ejemplo para pasarme?
Gracias

**Comment by gantonioid** [comment]
Perdóname es 
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/LoadCsv](url)

Le dices el path del archivo y qué caracter es el separador... esto porque también podría ser un tsv o venir separado por agún otro símbolo

**Comment by MartinMedinaSTK** [comment]
Cargando el CSV con esta función puedo aplicar filtros y borrar filas? una vez cargado puedo aplicar las mismas funciones que tenemos para un excel?

**Comment by gantonioid** [comment]
así es Martín, esa función agrega a tus libros cargados, similar al LoadWBook... tienes después que cargar la hoja con LoadWSheet tomando la primera hoja del libro... a partir de ahí ya la usas como si siempre hubiera sido de Excel.

**Comment by MartinMedinaSTK** [comment]
Hola probé con esta instrucción (LoadCSV) y no funciona, no da error pero las siguientes instrucciones que se ejecutan no hacen nada, por ejemplo:

Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 9
Excel ApplyFormat from WSNameSunat in_column_index 4 format 0
Excel ApplyFormat from WSNameSunat in_column_index 7 format 0
Excel RemoveRows from WSNameSunat where 7 equals 20508528656 start_at 2  

¿Podemos abrir este issue que todavía no fue resuelto? 

Por otro lado si quiero convertir en archivo a excel con la función ConvertTo2007 lo único que hace es agregar una "x" a la extensión del archivo (.csvx) generando un archivo erróneo.

**Comment by MartinMedinaSTK** [comment]
Adjunto los archivos.
Acciones.txt (el script de turing)
log.txt (el log de la ejecucion del proceso)
detracciones.csv (el archivo que quiero procesar)
[acciones.txt](https://github.com/FridaSupport/TuringSuport/files/3114254/acciones.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3114255/log.txt)

[detracciones.zip](https://github.com/FridaSupport/TuringSuport/files/3114259/detracciones.zip)

**Comment by gantonioid** [comment]
@MartinMedinaSTK 
Usé las siguientes líneas en mi prueba, y funciona como te dije
```
##Carga del archivo CSV
Excel LoadCSV "C:\Users\gilberto.isida\Downloads\detracciones.csv" separated_by , as WBNameSunat
Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat
##Se escribe sobre el CSV, como si fuera una hoja de Excel normal
Excel Write "CSV" in WSNameSunat cell A18
##Se filtra sobre el CSV, como si fuera una hoja de Excel normal
Excel ApplyFilter to the worksheet WSNameSunat to the column with the index {1} with the criteria "CSV"
Titanium Sleep 5000
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\otro.xlsx" as otrolibro
##Se copia toda la hoja (datos visibles del CSV) a otro libro
Excel CopySheet WSNameSunat to otrolibro as copiada
Titanium Sleep 5000
Excel Save otrolibro
```

Usando tu CSV de detracciones, aplico un filtro y copio la hoja (filtrada) a otro libro tal como si fuera un Excel.

Adjunto libro resultante
[otro.xlsx](https://github.com/FridaSupport/TuringSuport/files/3114609/otro.xlsx)



**Puede servir la función para transformar CSV directo a un XLSX sin hacerle más, pero SÍ existen alternativas y no se considera urgente**

**Comment by gantonioid** [comment]
Dado que el ejemplo dado funciona, cierro el issue. Si hay problemas favor de crear otro para revisar versiones u otros detalles.
