### ISSUE TITLE
Nuevamente no se ejecuto llamados API runprocess FRIDA

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#160]
Buenas Tardes @gantonioid , de nuevo se realizo llamado a Turing por medio del API de FRIDA para correr procesos pero no se ejecuto el bot, pueden ayudarme a validar si existen procesos pendientes por correr en FRIDA y podrían decirme porque no se dio la ejecución? después de que realicen la validación y si existen procesos pendientes por ejecución, por favor cancelarlos debido a que el cliente ya los realizo de forma manual.

Una ejecución debió darse a las 4.30 a.m de Colombia, otra a alas 9:01 a.m del día de ayer 29/05/2019.

ID de Procesos: cadenasbw1772122536 y  monitoreo301570862

No se si ocurrió lo mismo que se reporto para el caso: 

https://github.com/FridaSupport/TuringSuport/issues/93

El fin de semana me reportaron dos caídas mas de las cadenas pero de esas no tengo reportes de ejecución desde el flow, si ven algo en la herramienta agradecería me lo reportaran.

gracias.

quedo atento a su colaboración.

**Comment by gantonioid** [comment]
Habían pendientes tres ejecuciones de procesos de cadenas, pero con fecha del 22 de mayo, no coincide con el reporte.

Como información adicional, existen estas APIs relacionadas con ejecuciones remotas. Tal vez ayuden a darte respuesta. No tengo otros registros para compartirte ni información para saber la respuesta a la consulta :(
[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Remoto%20y%20Scheduling.one%7C21c7d51f-bc2f-4d07-9e52-ba06e3cee982%2FAPIs%20de%20FRIDA%20ejecuci%C3%B3n%20remota%7Cbf4b6ca9-a4a1-4726-94e0-22941d7d032f%2F%29&wdorigin=703](url)

**Comment by RickProductivity** [comment]
Oye @carlosgiraldo Que es lo que excatmante tenemos en prod ? quien aprobo la propuesta ? o es para mejora interna?

**Comment by carlosgiraldo** [comment]
Buenos días @gantonioid 

Ya pude revisar con la persona que tiene acceso a la Maquina Virtual y estaba presente el siguiente mensaje:


![error_01](https://user-images.githubusercontent.com/14879161/58714270-01c62880-838a-11e9-8166-9b62e5f99523.jpg)


En el visor de eventos encontramos lo siguiente, espero les sirva para saber por que motivo se esta deteniendo la ejecución de Turing:

Application: TuringExpo.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
   at System.Net.WebClient.DownloadString(System.Uri)
   at System.Net.WebClient.DownloadString(System.String)
   at AutomationOfThings.AOT+<t_Elapsed>d__81.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


![error_02 jpg](https://user-images.githubusercontent.com/14879161/58714313-14d8f880-838a-11e9-8eb7-3e169c80a728.png)



Faulting application name: TuringExpo.exe, version: 1.0.0.0, time stamp: 0x5ca2ae2c
Faulting module name: KERNELBASE.dll, version: 10.0.14393.2791, time stamp: 0x5c5a43dc
Exception code: 0xe0434352
Fault offset: 0x000db152
Faulting process id: 0x1fc4
Faulting application start time: 0x01d511b4b0be030a
Faulting application path: C:\FRIDA\TuringValorem\App\TuringExpo.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: b208dd99-0715-4aca-b339-5e89186731fa
Faulting package full name: 
Faulting package-relative application ID:


![error_03 jpg](https://user-images.githubusercontent.com/14879161/58714317-19051600-838a-11e9-888d-0c9377ff2e65.png)

**Comment by gantonioid** [comment]
Gracias por el log. Parece cuestión de red, lo indica el mensaje de la excepción. @andresCruzF 

> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Net.WebException
> at System.Net.WebClient.DownloadDataInternal(System.Uri, System.Net.WebRequest ByRef)
> at System.Net.WebClient.DownloadString(System.Uri)
> at System.Net.WebClient.DownloadString(System.String)
> at AutomationOfThings.AOT+<t_Elapsed>d__81.MoveNext()

**Comment by pabloreitanosofttek** [comment]
¿que sea de red quiere decir que es algo que FRIDA no maneja bien?  o quiere decir que la VM hizo alguna cosa que nos rompió?


¡Gracias!

**Comment by gantonioid** [comment]
En este caso me refiero a que es muy probable que ya no se tenga el acceso de internet requerido. El mensaje que compartió Carlos indica que el problema es en `System.Net.WebClient.DownloadString(System.String)`
Eso quiere decir que falló al hacer la petición de lectura en una URL... por lo tanto sugiero revisar permisos de red en la VM

**Comment by carlosgiraldo** [comment]
Pero si Turing no tienen acceso a las URL no inicia? o si? Lo pregunto porque esta mañana después de todas las validaciones deje a Turing ejecutándose en modo TURN ON EVENT LISTENER 

Que otra cosa puedo hacer para evitar este problema? es mejor ejecutar Turing en modo offline o igual tendría el problema? Si lo dejo en modo offline se ejecutan los llamados desde el API de FRIDA?

**Comment by gantonioid** [comment]
Un Turing offline no tiene Event Listener. 
Lo encendiste hoy y funciona? porque el error que reportaste como dije fue un error en una conexión a la url.

**Comment by carlosgiraldo** [comment]
Si, hoy después de extraer el Log que adjunte que encontramos en la maquina Virtual lo volví a ejecutar (el Turing) y lo deje en modo escucha-

**Comment by gantonioid** [comment]
Veamos qué pasa en estos días... @andresCruzF tenemos el rastreador de errores en VALOREM?

**Comment by pabloreitanosofttek** [comment]
@gantonioid  @andresCruzF  ¿lo tenemos? ¡gracias!

**Comment by carlosgiraldo** [comment]
Buenos días, hace una hora se ejecuto un bot pero no he podido validar si se ejecuto en la maquina virtual porque la persona que me da acceso no tiene tiempo en este momento, se que lo que se ejecuto es lo siguiente:

TaskID: "cadenasbw1772122536", 
ProcessID: "1901772471" 

Ejecute la API para saber el estado del proceso pero creo que aun no se usarlos bien porque me dice o no se si es que no tengo bien la URL:
{
    "message": "No HTTP resource was found that matches the request URI 'http://automationplatform.azurewebsites.net/api/ExecutionStatus'.",
    "messageDetail": "No type was found that matches the controller named 'ExecutionStatus'."
}


quedo atento  a validaciones y seguimiento del log que mencionan si se tiene, en una hora mas o menos se deberá ejecutar un segundo bot que valida la ejecución del bot anterior.

**Comment by gantonioid** [comment]
Carlos, primero el TaskID tiene que ser numérico (sigue el ejemplo de la wiki) y ese valor te lo da la llamada al API de RunProcess.

Luego tengo yo una pregunta para entender el caso... es scheduling o llamado remoto? porque mencionas que "en una hora se deberá ejecutar" cómo sabes? tiene horario? por qué no usas scheduling en vez de remoto?

**Comment by carlosgiraldo** [comment]
Buenos días @gantonioid , el llamado es remoto porque su ejecución se da cuando llega un correo electrónico notificando que un cadena BW se daño y que debe ser reparada, esta detección del correo lo realice por medio de Microsoft Flow y desde ahí hago el llamado al proceso vía API de FRIDA. ¿Por que digo que en una hora mas o menos deberá ejecutarse? lo que pasa es que proceso de reparación de cadenas BW lo partí en dos bots: uno repara y el otro pasado cierto tiempo revisa si la cadena pudo ser reparada, es decir, la cadena se repara por medio de un bot y el segundo bot revisa si la cadena quedo reparada, si no se reparo la cadena se envía un correo a un consultor BW para que el revise que pasa con la cadena y por que no pudo ser reparada. Como yo identifique que cadena fue la que fallo y tengo una tabla que me indica los tiempos promedios de ejecución por cadena pude estimar un aproximado en que se iba a lanzar el siguiente bot que realiza el monitoreo.

**Comment by gantonioid** [comment]
@carlosgiraldo quisiera mandarte un update al turing de Valorem para intentar que el LISTENER se conecte por sí mismo. Tú me dices cuándo podemos hacerlo.

**Comment by carlosgiraldo** [comment]
Buenos días @gantonioid , que debo hacer? solo reiniciar el Turing en Valorem? o como seria la actividad? es para yo poder coordinar con la persona que administrar el servidor y ver que requerimos de el en tiempo. Mas adelante espero no estar dependiendo de contactar a una persona ya que estoy gestionando que me puedan dar acceso a la maquina para poder estar mas pendiente del Bot.

**Comment by gantonioid** [comment]
Solo sería cerrar y volver a abrir Turing, la actualización llega en automático. Pero dime cuándo tienes acceso y probamos porque necesitaríamos probar que los procesos que tienes funcionan correctamente después del update.

**Comment by pabloreitanosofttek** [comment]
Estoy atento al resultado... porfa comentar cuando se sepa algo @gantonioid  @carlosgiraldo

**Comment by gantonioid** [comment]
Quedamos en verlo el lunes @pabloreitanosofttek, envié el MR para las 9am MEX. pendiente de confirmación @carlosgiraldo

**Comment by pabloreitanosofttek** [comment]
Este ticket sigue vivo o murió @carlosgiraldo ?

**Comment by gantonioid** [comment]
Iba de la mano con #213
