### ISSUE TITLE
[SOFIA] Generar usuario y version de turing offline.

### ISSUE THREAD

**Issue by cgarcete** [FridaSupport/TuringSuport#162]
Buen dia,

Necesitamos la generacion de un usuario y una version de turing offline para el cliente SOFIA.

Responsable: Victor Gamboa
Nombre proceso: Sofia
ID: 1105317075

Necesidad: Urgente.

**Comment by gantonioid** [comment]
@pabloreitanosofttek
Creo que la urgencia con estos temas se puede evitar... asumo que las fechas de deploy son conocidas.

**Comment by pabloreitanosofttek** [comment]
Si, podemos evitarlo y concuerdo con @gantonioid 

@FridaSupport  porfa tengamos presente cuando se acerca la fecha de fin de proyecto.

**Comment by yorlay** [comment]
@gantonioid necesitamos tenerlo listo para el jueves 6 de junio

**Comment by andresCruzF** [comment]
Hola @yorlay y @cgarcete  

Te compoarti esta version de turing por correo , quedo al pendiente.

Saludos.
