### ISSUE TITLE
[TITAN] Image not found.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#165]
Titanium se comporta de manera inestable. La primera vez hace click en una imagen correctamente, pero la segunda vez no la encuentra en el directorio de imágenes. Quiero dejar claro que no me refiero a que no la encuentra en la pantalla (imagen not found in the screen). Hasta ayer funcionaba correctamente.

Adjunto el log correspondiente. La imagen es E-Seleccionar.PNG.

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3242818/log.txt)

Necesito una solución para este lunes 3.

**Comment by CesarEmanuelLencina** [comment]
+@pablorlmx

**Comment by pabloreitanosofttek** [comment]
@CesarEmanuelLencina  podrás poner el script? Así @Johhnn117  y @FaustinoLechuga  tienen todas las herramientas. 
¡gracias!

**Comment by CesarEmanuelLencina** [comment]
@pabloreitanosofttek ya hice hace una hora una call con Jonathan Camacho y le proporcioné el código con las imágenes. Hasta donde sé están trabajando en la solución. De todas formas lo adjunto acá para que quede:

```
Excel LoadWBook "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Planilla ADI.xlsm" as LibroPlanilla
Titanium ClickImage E-Mayor.PNG Timeout= 15000 NumberClicks= 2 ClickPosition= CENTER_RIGHT
Titanium Sleep 5000
Titanium Type [DATOS BORRADOS]
Titanium Type {TAB}
Titanium Type [DATOS BORRADOS]
Titanium Type {ENTER}
Titanium Sleep 2000
Titanium Type {m}
for 6 times{
Titanium ClickImage E-Bajar.PNG Timeout= 5000 NumberClicks= 1 sim= 0.8
}
Titanium ClickImage E-MailAnalista.PNG Timeout= 10000 NumberClicks= 1
Titanium ClickImage E-Seleccionar.PNG Timeout= 10000 NumberClicks= 1
Titanium ClickImage E-Maicao.PNG Timeout= 10000 NumberClicks= 1 ClickPosition= CENTER_LEFT
Titanium ClickImage E-Seleccionar.PNG Timeout= 10000 NumberClicks= 1
```

**Comment by pabloreitanosofttek** [comment]
OK, la próxima porfa actualicemos el status porque sino para mi no pasó nada.

¡gracias!

Slds,

PR

**Comment by andresCruzF** [comment]
Hola @CesarEmanuelLencina 

Te comparto una versión de Turing con la corrección de este error, el cual se presentaba al intentar abrir un archivo que se encontraba ocupado en memoria (por la velocidad a la que se accede a la imagen esta no se alcanzaba a liberaba el recurso a tiempo).

Turing Version ID  : 20190603T0710

Saludos , quedo al pendiente

**Comment by CesarEmanuelLencina** [comment]
Hola @andresCruzF, por desgracia me está dando el mismo error que vimos en la call con Jonathan. Adjunto el log correspondiente y un captura donde se ve la versión: 

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3249158/log.txt)

![imagen](https://user-images.githubusercontent.com/50213758/58829389-13bff980-861e-11e9-8372-9a00dde778ab.png)
