### ISSUE TITLE
[TITAN] - Error al actualizar Turing

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#166]
Buenas Tardes,

se abre la aplicación Turing, al abrirla en horas de la tarde esta indica que tiene una actualización pendiente, se procede a obtener la ultima versión y al iniciar esta, muestra la siguiente información:

![image](https://user-images.githubusercontent.com/50154520/58754265-0249e680-8492-11e9-8e25-f5281035c884.png)

![image](https://user-images.githubusercontent.com/50154520/58754262-efcfad00-8491-11e9-9978-7accf20cd416.png)

**Comment by FaustinoLechuga** [comment]
Hola buenas tardes, 
Ya estoy revisando el tema, al parecer fue un error descargando la actualización que deja a la plataforma a inutilizable.

**Comment by FaustinoLechuga** [comment]
El error se soluciona volviendo a descargar turing desde la pagina.

[http://automationplatform.azurewebsites.net/Home/ConfigurationDownload](url)

Intenta haciendo esto, quedo al pendiente para cualquier problema.

**Comment by gantonioid** [comment]
Julián reporta por correo que descargó de nuevo y ya no tiene el problema
