### ISSUE TITLE
[Excellia] - Función para obtener cantidad de lineas en una tabla html

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#167]
Necesitaría saber cuantas lineas tiene una tabla HTML para poder recorrerla haciendo procesos parciales cada 8 lineas.

**Comment by carlosortiz632** [comment]
No hay función para obtener esa información. Lo mejor sería revisar en la tabla si hay alguna especie de contador y aplicar la función Extract ahí.

**Comment by gantonioid** [comment]
Tema sin actividad
