### ISSUE TITLE
[TITAN] Error enviando varios parametros a Custom

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#168]
Buenas Tardes, requiero pasar varios parámetros a un desarrollo custom para un RPA, al momento de pasar un parámetro de esta forma, el app no genera ningún problema, pero cuando intento pasar varios el log me genera la siguiente información:

**Log de Error:** 

03/06/2019 14:33:25 - RunPowerShell CustomLocal2.txt : Running
03/06/2019 14:33:26 - RunPowerShell CustomLocal2.txt  : error : en línea: 1 carácter: 14
+ $fileexe = ''c:\dev\titan\proyecto\2.2 carga de locales\archivos\prgb ...
+              ~~~~~~~~~~~~~~~~~~~~~~~~~
token 'c:\dev\titan\proyecto\2.2' inesperado en la expresión o la instrucción.

en línea: 1 carácter: 94
+ ... les_docs.exe" 03/06/2019 c:\dev\titan\proyecto\2.2 carga de locales\a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
falta la cadena en el terminador: ".
03/06/2019 14:33:26 - RunPowerShell CustomLocal2.txt  : Error

**El código del Shell es el siguiente:**

$fileExe = ''<<<rutaDBsAccess>>>PrgBot\CargaLocales_Docs.exe" <<<fechaHoyReal>>> <<<rutaDBsAccess>>> <<<consolidateCsvFile>>> <<<geoXlsFile>>> 
& $fileExe

El ejecutable es un .exe de consola en c#, el cual recibe los siguientes argumentos:

 static void Main(string[] args)
        {
            string strFecha = args[0];
            string strRuta = args[1];
            string strCsv = args[2];
            string strXls = args[3];

Cuando realizo la prueba con un solo argumento este funciona, pero al enviar los demás se genera el inconveniente, que puedo estar haciendo mal?.

**Comment by JulianBustos** [comment]
Adjunto en comillas dobles los parámetros, ya que veo una vez se publica en Git y van entre Mayor/Menor, quedan ocultos:

$fileExe = '''rutaDBsAccess'PrgBot\CargaLocales_Docs.exe" 'fechaHoyReal' 'rutaDBsAccess' 'consolidateCsvFile' 'geoXlsFile'

**Comment by gantonioid** [comment]
@JulianBustos Esto no es tema de soporte.

Lo que estás intentando es correr un exe con un script de PowerShell, no como se acostumbran los CustomLocal con FRIDA.

Dicho eso... noto que en tu línea
`$fileExe = ''<<<rutaDBsAccess>>>PrgBot\CargaLocales_Docs.exe" <<<fechaHoyReal>>> <<<rutaDBsAccess>>> <<<consolidateCsvFile>>> <<<geoXlsFile>>> 
& $fileExe`

- usas doble comilla simple en vez de comilla normal justo después de `$fileExe =`
- Revisa esta referencia en StackOverflow [https://stackoverflow.com/questions/1673967/how-to-run-an-exe-file-in-powershell-with-parameters-with-spaces-and-quotes](url)
- Las variables que contengan espacios deben de ir entre comillas

Siempre considera que si tu script PowerShell no corre por su cuenta, no va a servir en FRIDA.
![image](https://user-images.githubusercontent.com/9600868/58835574-f427d180-861b-11e9-9361-ff205c3aa934.png)
