### ISSUE TITLE
[TITÁN] Actualización de Turing offline para el cliente.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#169]
Necesito que el Turing offline del cliente Titán se encuentre actualizado con la versión que poseo para que así corran las instrucciones que hicieron para la _Planilla ADI_.

Si necesitan algún tipo de información por favor háganmelo saber.

Necesito esto para este mismo día de ser posible.
+@pablorlmx

**Comment by JuanIgnacioBurgos** [comment]
@FridaSupport Por favor tartar esto con caracter de Urgencia, temenos demo con el cliente el dia de hoy...Muchas gracias!

**Comment by andresCruzF** [comment]
Hola @CesarEmanuelLencina  

Me podrías proporcionar los IDs de los procesos que se requieren vengan en esta versión de Turing de igual forma te comento que en caso de no necesitar agregar o migrar algún script únicamente es necesario copiar el archivo "TuringExpo.exe" de tu versión actual a la carpeta de Turing Offline que se te proporciono del cliente (Todos los archivos de configuración permanecerán sin cambio alguno )

![image](https://user-images.githubusercontent.com/49708627/58889161-1a964d00-86ae-11e9-8cc2-2b3e9110fc2a.png)

**Comment by CesarEmanuelLencina** [comment]
ID: cargaexcel
Process ID: 1006593420

ID: CARGALOCALES
Process ID: 1508212038

ID: ETV. 1-Carga y ejecucion de Macro
Process ID: 528541555

ID: ETV1
Process ID: 225623540

ID: MixreaderProc
Process ID: 784948359

ID: TITAN ADI
Process ID: 1138631086

ID: ETV4
Process ID: (este sería un nuevo proceso)

**Comment by gantonioid** [comment]
Están haciendo el ETV4 o ya lo tienen? podemos esperar a que tengan ese Process ID?

**Comment by CesarEmanuelLencina** [comment]
El ETV4 sería:

ID: prueba script (si se puede en la offline renombrar a ETV4 mejor, si no, no importa)
ID Process: 396341192

**Comment by gantonioid** [comment]
Ya está el cambio de nombre

**Comment by CesarEmanuelLencina** [comment]
¿Ya está disponible la actualización?

**Comment by pablorlmx** [comment]
Estimado @FridaSupport, pueden dar prioridad a esto por favor! En 30 minutos tenemos prueba en vivo con el cliente y no podremos ejecutar desde el servidor por esto! incluyo a @RickProductivity

**Comment by pablorlmx** [comment]
Estimados alguna novedad?

**Comment by andresCruzF** [comment]
Buenos Dias @CesarEmanuelLencina 

Se trabaja en un API para mejorar los tiempo de respuesta para este tipo de requerimiento de igual forma te comento que ya fue generada la nueva version de TuringOfline con los procesos que nos solicitaste y se encuentra en el Teams de ARS - Chile en el Canal de Proyecto FIRDA - TITÁN en la carpeta de TuringExpo Installers con el nombre de Turing (Offline) - TITAN v3. Así mismo te comento que el proceso con ID 1006593420 fue eliminado de la plataforma por lo que agrege una copia de la version anterior que les proporcione espero les funcione.

Saludos , quedo al pendiente

**Comment by JuanIgnacioBurgos** [comment]
Gracias, Andres vamos a estar corriendo los procesos en la VM, cualquier inconveniente nos volvemos a contactar.

Saludos
