### ISSUE TITLE
Error in Mixed-reader con web2 

### ISSUE THREAD

**Issue by camilitwo** [FridaSupport/TuringSuport#17]
Al momento de levantar una ventana emergente no esta reconociendo un boton.

menciono que esta es la segunda ventana emergente que abre dentro del ciclo, y en la primera no tuve problemas.

el siguiente codigo:
```
Web2 GoTo "<<url>>"
Web2 Navigation
Web2 Type "<<user>>" in name ="login"
Web2 sleep 1000
Web2 Type "<<pass>>" in name ="password"
Web2 sleep 1000
Web2 Click in selector="body > table > tbody > tr:nth-child(2) > td.top > form > table > tbody > tr > td.login > table > tbody > tr:nth-child(3) > td > input"
Web2 Navigation
Web2 GoTo "http://192.168.1.22/Instalaciones2"
Web2 Navigation
Web2 Click in id="IngresoFiil"
Web2 sleep 100
Web2 Click in id="Instalacion"
Web2 sleep 100
Web2 Click in name = "botonBuscarCliente"
Web2 SwitchPage Last
Web2 Navigation
#Web2 Type "<<<rutCliente>>>" in name="rut"
Web2 Type "13471316-K" in name="rut"
Web2 sleep 100
Web2 Key "Enter"
Web2 sleep 100
Web2 Click in name="indiceConsultarCliente"
Web2 sleep 3000
Web2 Click in id="Seleccionar"
Web2 sleep 100
Web2 SwitchPage Main
Web2 Navigation
Web2 Click in id="botonAgregarServicio"
Web2 SwitchPage Last
Web2 sleep 1000
Web2 Click in selector="body > form > table:nth-child(65) > tbody > tr > td > table > tbody > tr > td > input:nth-child(1)"
Web2 sleep 100
```

Fecha necesidad: 25/04/2019

![image](https://user-images.githubusercontent.com/22084703/56660576-c4c19480-666d-11e9-8167-5020cd356aeb.png)

**Comment by charlie632** [comment]
Se cerró correctamente la primera ventana emergente?

**Comment by camilitwo** [comment]
Si, no hay problema en la primera

**Comment by charlie632** [comment]
o cómo es que se está cerrando?

**Comment by camilitwo** [comment]
al darle a un boton se cierra automaticamente, asi esta programado, despues vuelve a la pantalla principal y levanta la segunda ventana y es en esta donde no reconoce el boton

**Comment by charlie632** [comment]
Ok, Lo checo.

**Comment by charlie632** [comment]
Podrías intentar darle click al botón usando la siguiente instrucción?

`Web2 Click in dynamic="Agregar Producto"`

**Comment by camilitwo** [comment]
Ya lo había probado.
![image](https://user-images.githubusercontent.com/22084703/56661647-34388380-6670-11e9-8368-9e4215342fc3.png)

**Comment by charlie632** [comment]
Hay manera en que pueda entrar a esa página para poder revisarla?

**Comment by camilitwo** [comment]
Necesitas vpn del cliente, si quieres me llamas por teams o skype y compartimos pantalla...

**Comment by pabloreitanosofttek** [comment]
Hola, ¿Cuál es la fecha de necesidad? ¡gracias!

**Comment by camilitwo** [comment]
> Hola, ¿Cuál es la fecha de necesidad? ¡gracias!

**Comment by camilitwo** [comment]
Hola, lo solicite para el día 25/04.

Saludos,

**Comment by gantonioid** [comment]
Tuvieron la sesión para verlo? Porque se solicitó acceso a la web que están utilizando y así atender el caso. Queda difícil debuggear por skype.

**Comment by carlosortiz632** [comment]
Sí, tuvimos una sesión en hice unas mejoras, pero no funcionaron. Como dices, al no tener acceso a la página web es muy difícil debuggearlo. Hoy mandaré una actualización para tratar de debuggear remotamente.

**Comment by gantonioid** [comment]
Gracias @carlosortiz632 !!

@pabloreitanosofttek @camilitwo Esto se está atendiendo, pero por los problemas de acceso mencionados requiere más esfuerzo => tiempo... así que consideren avanzar con otra cosa.

> Sí, tuvimos una sesión en hice unas mejoras, pero no funcionaron. Como dices, al no tener acceso a la página web es muy difícil debuggearlo. Hoy mandaré una actualización para tratar de debuggear remotamente.

**Comment by pabloreitanosofttek** [comment]
Y ¿Cuál es la fecha prevista? Porque todos estos temas son temas que nos preocupan porque la mitad tienen que ver con entrega a distintos clientes.

**Comment by camilitwo** [comment]
Aun estoy esperando una retroalimentacion, podria esperar hasta el viernes 10/05

**Comment by carlosortiz632** [comment]
@camilitwo  Podríamos tener una sesión el día de hoy para revisarlo?

**Comment by camilitwo** [comment]
Hola, hoy y mañana estoy complicado, tendría que ser el jueves.

**Comment by gantonioid** [comment]
@pabloreitanosofttek sin su colaboración las fechas de compromiso no valen

**Comment by carlosortiz632** [comment]
Se solucionó probema. Quedo pendiente de más feedback.
