### ISSUE TITLE
[TITAN] Problema al ejecutar custom en turing.

### ISSUE THREAD

**Issue by cgarcete** [FridaSupport/TuringSuport#170]
Estimados,

no es posible ejecutar un custom que tiene dentro un archivo con extension .jar. La funcionalidad del mismo es migrar los datos de un archivo excel a una DB access.

Instruccion FRIDA:
RunCustomLocal accessAndXlsData "C:\\Users\\claudio.garcete\\Downloads\\titanJulian\\testerTitan\\PPL 27-03.xlsx", "jdbc:ucanaccess://C:/Users/claudio.garcete/Downloads/titanJulian/testerTitan/cargalocales.accdb"

Instruccion CMD: (Aclaro que por CMD no tengo problemas al realizar la ejecucion)
java - jar "C:\\Users\\claudio.garcete\\Downloads\\titanJulian\\testerTitan\\PPL 27-03.xlsx" "jdbc:ucanaccess://C:/Users/claudio.garcete/Downloads/titanJulian/testerTitan/cargalocales.accdb"

![ejecucion custom](https://user-images.githubusercontent.com/20261007/58884744-5f72b180-86b7-11e9-9adc-1d60702ece71.png)

Log:

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3252704/log.txt)

Se adjunta el .jar, el excel y la bd para poder reproducir el inconveniente.

https://onesofttek-my.sharepoint.com/:f:/r/personal/claudio_garcete_softtek_com/Documents/customTITAN?csf=1&e=qKU33F

Necesidad: Urgente.

**Comment by gantonioid** [comment]
@cgarcete el link a OneDrive que compartes no funciona
![image](https://user-images.githubusercontent.com/9600868/58887531-698eb300-86ab-11e9-8463-db9a739e2a93.png)

**Comment by gantonioid** [comment]
El log que adjuntas indica error en la última línea (espacio en blanco). **No en el RunCustomLocal**
![image](https://user-images.githubusercontent.com/9600868/58888321-d8b8d700-86ac-11e9-9c21-6eac2aa97a39.png)

Necesito más información (el link correcto a OneDrive para intentar reproducir el error que se reporta)

**Comment by ClaudioRodolfoGarcete** [comment]
Deje el  espacio en blanco a proposito, el tema es que el custom no se ejecuta ( no se el motivo y el log no me da la sufiente info para determinar la causa), ya te di acceso a onedrive (confirmame)

**Comment by pablorlmx** [comment]
Estimado @FridaSupport, pueden dar prioridad a esto por favor! esta semana debemos poder resolver el tema y hoy es un stopper. incluyo a @RickProductivity

**Comment by gantonioid** [comment]
@ClaudioRodolfoGarcete Confirmado, gracias. Ya estoy viéndolo.

@pablorlmx es un ticket de reciente. Se está atendiendo, paciencia. Por aquí se reportará estatus.

**Comment by gantonioid** [comment]
@ClaudioRodolfoGarcete te pasé la versión 20190604T1006 por favor prueba y me dices. No tienes que hacer cambios en tu script.

**Comment by pablorlmx** [comment]
Gracias por la repuesta.

________________________________

**Comment by gantonioid** [comment]
Estoy a la espera del resultado de la prueba con la versión enviada.

**Comment by ClaudioRodolfoGarcete** [comment]
muchas gracias @gantonioid 

Esto fue solucionado.
