### ISSUE TITLE
[TITAN]Problemas SendMail con correos Microsoft 

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#171]
Buenos Dias

la sentencia SendMail  al utilizarla para correos Microsoft no funciona, al momento de ejecutarla no genera error y el log muestra que si ejecuto la tarea, pero el correo de notificación no esta llegando. por favor validar si para este tipo de correos hay alguna restricción o algo para tener en cuenta, ya que se realizo la misma prueba con correo Gmail y funciono.

**Comment by Johhnn117** [comment]
Puedes subir el código y el log?

**Comment by rrrios** [comment]
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3253460/codigo.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3253462/log.txt)

**Comment by eradgg** [comment]
Hola. 
efectivamente Softtek tiene una restricción para el correo de FRIDA y lo está bloqueando, esto ya se escaló, pero aún no tenemos una solución. Por ahora hay que usar ese workaround de enviar correos a una dirección de gmail. Por favor checar: #68
Saludos.

**Comment by gantonioid** [comment]
@rrrios corrección que es softtek quien bloquea los mails, no que FRIDA no los envíe.
