### ISSUE TITLE
[TITÁN] [Exelium] Error de sintaxis con Write.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#172]
Al intentar escribir en una celda de Excel Turing arroja un error de sintaxis que indica que quise cargar nuevamente un archivo ya utilizado.

Esto ocurrió en el código completo de mi proceso por lo que copiarlo entero sería muy extenso. La parte en conflicto es la siguiente:

```
Excel LoadWBook "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Log.xlsx" as Log
Excel LoadWSheet Log sheet_index 1 as hojaLog
Excel Write "<<<Hour>>> hs <<<CurrentDate>>>" in hojaLog row 1 and column 7
Excel WriteInRange from the worksheet hojaLog the value "-" from the cell {2,3} up to the cell {20,3}
if (<<<Paso>>> -eq 19)
Excel WriteInRange from the worksheet hojaLog the value "Finalizado" from the cell {2,3} up to the cell {20,3}
else
Excel WriteInRange from the worksheet hojaLog the value "Finalizado" from the cell {2,3} up to the cell {<<<Paso>>>,3}
MathOperation <<<Paso>>> + 1 and save as Paso
Excel Write "ERROR" in hojaLog row <<<Paso>>> and column 3
end
Excel ConditionalFormat in hojaLog range C2:C20 format "textcolor:Green" where cell_value equals value Finalizado
Excel ConditionalFormat in hojaLog range C2:C20 format "textcolor:Red" where cell_value equals value ERROR
Excel Save Log
```
Adjunto el log correspondiente.
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3253912/log.txt)

Agrego: la línea que se muestra como error es similar a la de un archivo que guardé usando la instrucción SaveAs.

Ante cualquier duda estoy disponible para una call y así ver el problema en mayor detalle.

Necesitaría una solución para mañana en lo posible.

**Comment by CesarEmanuelLencina** [comment]
Encontré una solución: aparenemente tengo abiertos demasiados archivos Excel; solo tuve que guardar y cerrar uno de ellos y el resto del código se ejecutó correctamente.

**Comment by gantonioid** [comment]
El usuario encontró solución

**Comment by RickProductivity** [comment]
Gracias

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
