### ISSUE TITLE
[TITÁN] [Exelium] Ponerle Color a una celda.

### ISSUE THREAD

**Issue by dsalgadoi2012** [FridaSupport/TuringSuport#173]
Buenas Tardes, para el proyecto requiero marcas unas celdas de Color amarillo, estas vienen de un Filtro y debe marcase en unos casos toda la fila y en otros toda la columna

**Comment by gantonioid** [comment]
Necesitamos por favor todos los detalles posibles. De aquí entiendo:

- Se filtra por X columna o por múltiples (Puede ser usando las funciones de Filtro existente)
- Quieres especificar el color de celda de una celda específica (B3 por ejemplo) el UsedRange, o las filas visibles o la columna con index = 5

Por favor confirma o amplía la descripción si lo entendido es equivocado

**Comment by gantonioid** [comment]
gracias @FaustinoLechuga

**Comment by dsalgadoi2012** [comment]
te confirmo es tal cual lo comentas, tanto para el resultado de los filtros como para una columna especifica.

**Comment by FaustinoLechuga** [comment]
Okay, solo para confirmar se desea que la funcion:
- Cambie color de una celda en especifico
- Cambie el color de una fila completa o multiples
- Cambie el color de una columna completa o multiples
- Cambie color de un rango
- Cambie el color de una fila completa o multiples solo celdas visibles (Estas son las que se ven despues de filtrar)
- Cambie el color de una columna completa o multiples solo celdas visibles (Estas son las que se ven despues de filtrar)
-  Cambie color de un rango solo las celdas visibles (Estas son las que se ven despues de filtrar)

Comenzare haciendo eso a menos que se me indique lo contrario

**Comment by gantonioid** [comment]
@FaustinoLechuga Cómo vamos?

**Comment by FaustinoLechuga** [comment]
Ya casi sale.

**Comment by FaustinoLechuga** [comment]
Ya esta lista la función, te libere una nueva versión con este cambio que es la 20190606T0529.
La función se llama BackgroundColor y puedes revisar su funcionamiento en [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/BackgroundColor](url)

Quedo al pendiente para la confirmación y para cualquier duda o aclaración.

**Comment by FridaSupport** [comment]
Se cierra el issue a falta de una respuesta.
