### ISSUE TITLE
[EXCELLIA] [URGENTE] Falta de documentacion del proceso Pago Central

### ISSUE THREAD

**Issue by raulpoltiSTK** [FridaSupport/TuringSuport#174]
Hola @andresCruzF @FridaSupport , ¿Como estas?

Nos encontramos presentando el proceso de Pago Central con el cual tenemos que salir a Producción, y el cliente nos comenta que no contempla todo lo que Relevaste en su momento en Perú, que es solo una forma en la que se realiza, y nos reclama las otras 3 formas de realizarlo.
De lo que nos enviaste documentado para realizar el proceso no se encontraba completo, faltando . 
Tienes la documentación del resto de formas que componen el proceso? 
En los videos que subiste a Pago a Proveedores encontramos videos que puede ser los que componen al proceso de Pago Central, pero no se logran entender o no sirven para documentarlos.

Los videos que encontramos son los siguientes:
-	VIDEO: “Pago a Probedores - Pago central.mp4”(SIC), Con Marilin Yovana Huaman Corrales, se muestra el uso de la transacción "ZF110A" para la sociedad 253,264,291 (Grupo Ransa) que según Liana no se usa aquí.
Se menciona que la diferencia entre la transacción ZF110 y la ZF110A es que esta última permite copiar masivamente proveedores, la otra solo unos cinco.
la captura de imagen que se envía es de totales, no la que indico Liana hoy (apertura por banco)
Si hay diferencia entre Cbc y Tpbc los corrige uno a uno, eso se había desarrollado pero Liana indico que no se haga.
Indica que algunas sociedades se usan en distintos servidores de SAP, la 251 se usa en el "P3" y con la transacción ZF110
Hace un bloqueo de pago "z" y se hace la captura por "relación Bancaria" y una serie de acciones posteriores que no están en el relevamiento.
Sin especificar porque pasa a pago de detracciones, entra en SUNAT, emite un archivo, lo carga en SAP y se termina el video en medio del proceso..

-	VIDEO: "Documentacion Pago a Probedores - Friday, October 26, 2018 1.17.57 PM.mp4", trata de “Cheques Manuales”

-	VIDEO: "Documentacion Pago a Probedores - Friday, October 26, 2018 12.17.41 PM.mp4", Se usa la transacción ZF110 (Relacionada con Pago central)

-	VIDEO: "Documentacion Pago a Probedores - Friday, October 26, 2018 3.22.29 PM.mp4" No tiene video, es solo audio, no se entiende que hacen.

-	VIDEO: "Documentacion Pago a Probedores - Friday, October 26, 2018 1.08.56 PM.mp4", Trata de “Aprobación de anticipos” (es lo que intuyo por el subject del mail que envía)

-	VIDEO: "Documentacion Pago a Probedores - Friday, October 26, 2018 4.44.15 PM.mp4", No tiene video, es solo audio, no se entiende que hacen.

Una particularidad de todos los videos anteriores es que no tienen una introducción al proceso que están relevando, todos comienzan con un proceso en curso, por lo que es muy difícil saber qué están haciendo.

Nos puedes ayudar con esto, ya que el Liana y Walter quieren que les mostremos el proceso completo, y están esperando una respuesta, debido a que esto se relevó el 30 de Octubre y ya debería estar diseñado. Ya que este proceso lo estamos queriendo implementar en productivo y el cliente no esta conforme porque no cumple con sus expectativas en cuanto a lo que relevaste.

Necesitamos que nos puedas entregar la documentación de lo faltante para revisarlo con el cliente y encontrar la forma de incluirlo.

Aguardo tus comentarios.

FECHA DE NECESIDAD: 05/06/2019

**Comment by raulpoltiSTK** [comment]
@andresCruzF @FridaSupport tenemos alguna novedad al respecto? El cliente esta a la espera de una respuesta. Gracias

**Comment by gantonioid** [comment]
@raulpoltiSTK se entregó todo el material que teníamos, no existe más.

Derivado de una conversación entre Rick y Pablo se generó un correo (en el que estás copiado) con una sugerencia de relevar lo que haga falta. Si gustas revisarlo y tratar el tema por ahí.
