### ISSUE TITLE
[SAP - Consulta] Guardar número de cotización

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#175]
Al crear una cotización en SAP, necesito guardar el numero de cotización que se crea en una variable, para después asignárselo al archivo PDF que guardo, existe alguna instrucción para guardar aquello?

Con Scripting no pude tomar ese sector de SAP

![Numero Cotizacion](https://user-images.githubusercontent.com/49756748/58959009-221f2a00-8772-11e9-8e29-e2c4c2504694.PNG)

**Comment by gantonioid** [comment]
Me parece que hay algo para obtener lo que sale en la barra de estado
Revisa esto:
[http://automationplatform.azurewebsites.net/Readers/Tools/SAP/ReadStatus](url)

**Comment by eradgg** [comment]
Hola Victor, efectivamente, puedes usar esa instrucción y si necesitas sólo el número existe la siguiente: 
http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/Delete
para poder quitarle las partes que no son el número.

Saludos.

**Comment by victorgamboa** [comment]
Gracias a ambos, lo revisare, si tengo alguna duda Eder, te puedo hablar por Skype?

**Comment by eradgg** [comment]
Adelante, estamos en contacto en skype.

**Comment by eradgg** [comment]
Ya hice el cambio en la función, puededs probarlo?

**Comment by gantonioid** [comment]
@victorgamboa ?

**Comment by victorgamboa** [comment]
Falta la función Doble Click, Eder quedo de hacerla

**Comment by gantonioid** [comment]
Es de lo mismo de obtener el status?

**Comment by eradgg** [comment]
Se solucionó con Titanium sólo quedó pendiente esa función, quizá podría ser otro ticket, pero de igual forma ya te subí una nueva versión Victor, con la función Doucle click.

Favor de probarla, la sintaxis es la siguiente:
DoubleClick ElementId wnd[0]/sbar

**Comment by eradgg** [comment]
@victorgamboa pudiste hacer la prueba?

**Comment by gantonioid** [comment]
@victorgamboa @pablorlmx ya probaron?

**Comment by eradgg** [comment]
YA quedó resuelto, se cirra el ticket, Victor confirmó que ya funciona correctamente.
