### ISSUE TITLE
Solicitud Turing para produccion para proyecto de RPA interno

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#176]
Se requiere un Turing offline para el proceso interno Tipo de cambio. 

Este esta en mi perfil con el ID 972285755

Para el 07/06/19

**Comment by gantonioid** [comment]
Si es interno, entonces cuál es la solicitud? Agregarlo a algún área para que otros usuarios ejecuten ese proceso? Área de cliente? cuál?

**Comment by gantonioid** [comment]
No hay información para atender la solicitud... Favor de comentar para reabrir
