### ISSUE TITLE
[Excellia] - Error en función DateFormat3 de Excellium - Necesidad: URGENTE

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#177]
Buenos días, estoy teniendo problemas con la función indicada en el título. 
Agrego el código que tengo en el bot:
## --- Carga archivo CSV --- 
Excel LoadCSV "<<<EnviormentDownloadsPath>>>detracciones.csv" separated_by , as WBNameSunat
Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat
Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 10
##Aplicar formato de fecha (DD.MM.YYYY) 
Excel Dateformat3 in WSNameSunat in column 10

El problema es que está cruzando en mes y el día para la fecha, por ejemplo:
La fecha 04/06/2019 la convierte en 06.04.2019 como se ve en la siguiente imagen que contiene los dos archivos, el original (detracciones.csv) descargado de la web de SUNAT y el modificado por Turing (DETRAC TRAMARSA 05.06.2019 20196570.csv) luego de aplicar la función Dateformat3:

![image](https://user-images.githubusercontent.com/49758327/58962107-db84fc00-8780-11e9-92a8-d58161d31f61.png)

El problema no termina acá, cuando en el mismo archivo tengo fechas con días posteriores al 12 (entiendo que es porque es el último mes del calendario) el formato dd/mm/yyyy lo aplica correctamente, como se muestra en la siguiente imagen, a su vez también se ve que en el mismo archivo hay fechas con error (06.03.2019 cuando debería ser 03.06.2019) y hay fechas correctas (31.05.2019):

![image](https://user-images.githubusercontent.com/49758327/58962427-84335b80-8781-11e9-965a-ca4017700313.png)

Por favor necesito que le den prioridad a este tema ya que es un bot que se encuentra en productivo generando este error.

**Comment by JuanISalazarM** [comment]
Le pido de favor proporcione archivo Excel, log, y script(código) porfavor.
Lo atenderemos en la brevedad.

**Comment by MartinMedinaSTK** [comment]
Te envío un zip con los 3 archivos adentro.
[error dataformat3.zip](https://github.com/FridaSupport/TuringSuport/files/3258251/error.dataformat3.zip)

**Comment by JuanISalazarM** [comment]
Muchísimas gracias. Esto nos ayuda bastante, se lo agradecemos.

**Comment by MartinMedinaSTK** [comment]
Perdón te adjunto el csv original que es el que toma el proceso para su ejecución. El que está en el otro zip es el queda como resultado del proceso.

[detracciones.zip](https://github.com/FridaSupport/TuringSuport/files/3258308/detracciones.zip)
.

**Comment by JuanISalazarM** [comment]
Enterado, gracias.

**Comment by MartinMedinaSTK** [comment]
@JuanISalazarM, alguna novedad?

**Comment by JuanISalazarM** [comment]
Si. Estoy realizando pruebas con la función DateFormat:
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/DateFormat

Y me arroja el siguiente resultado:

![image](https://user-images.githubusercontent.com/50111840/58981073-404b5100-8797-11e9-95b0-057a4cdb57fb.png)

Cabe mencionar que esto es en el primer archivo que envió, lo intenté con el segundo (entiendo que es el base), y los resultados no fueron los deseados.

Quisiera solicitar de favor si podría intentar la función DateFormat, después de haber llamado a la función DateFormat3.

La manera en la que tengo el DateFormat en mi script es la siguiente:
DateFormat <wsKey> column_index <columnIndex> source \"MM.dd.yyyy\" string(\"dd.MM.yy\")

Porfavor, considere que <wsKey> se sustituye por el Worksheet donde desea que se realice la acción.
También el <columnIndex> el número de columna donde desea que se aplique la instrucción.

Quisiera solicitar de favor si podría intentar la función DateFormat, después de haber llamado a la función DateFormat3.

**Comment by MartinMedinaSTK** [comment]
pasame la instrucción tal cual la tenes funcionando en tu script

**Comment by MartinMedinaSTK** [comment]
Da error. Te paso el script:

## --- Carga archivo CSV --- 
Excel LoadCSV "<<<EnviormentDownloadsPath>>>detracciones.csv" separated_by , as WBNameSunat
Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat
Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 10
##Aplicar formato de fecha (DD.MM.YYYY) 
Excel Dateformat3 in WSNameSunat in column 10
Excel DateFormat 10 WSNameSunat "MM.dd.yyyy" string("dd.MM.yy")

Log:

6/5/2019 4:21:20 PM - Carga archivo CSV ---  : Success
6/5/2019 4:21:20 PM - Excel LoadCSV "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat: Running
6/5/2019 4:21:21 PM - Excel LoadCSV "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat : Success
6/5/2019 4:21:21 PM - Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat: Running
6/5/2019 4:21:21 PM - Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat : Success
6/5/2019 4:21:21 PM - Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 10: Running
6/5/2019 4:21:21 PM - Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 10 : Success
6/5/2019 4:21:21 PM - ##Aplicar formato de fecha (DD.MM.YYYY) : Running
6/5/2019 4:21:21 PM - Aplicar formato de fecha (DD.MM.YYYY)  : Success
6/5/2019 4:21:21 PM - Excel Dateformat3 in WSNameSunat in column 10: Running
05/06/2019 04:21:21 p. m. - Excel Dateformat3 in WSNameSunat in column 10 : Success
05/06/2019 04:21:21 p. m. - Excel DateFormat 10 WSNameSunat "MM.dd.yyyy" string("dd.MM.yy"): Running
05/06/2019 04:21:21 p. m. - Error, there was no syntax that matched the instruction
05/06/2019 04:21:21 p. m. - Error, there was no syntax that matched the instruction
05/06/2019 04:21:21 p. m. - Excel DateFormat 10 WSNameSunat "MM.dd.yyyy" string("dd.MM.yy") : Error

**Comment by JuanISalazarM** [comment]
Lo que pasa es que hubo error de sintaxis, una disculpa.
`DateFormat <wsKey> column_index <columnIndex> source \"MM.dd.yyyy\" string(\"dd.MM.yy\")`

Esta es la sintaxis a utilizar, en su caso sería:
`DateFormat WSNameSunat column_index 10 source \"MM.dd.yyyy\" string(\"dd.MM.yy\")`

Solicito de favor realizar el cambio en el Script, y realizar la prueba necesaria. Gracias por su atención, esperamos su respuesta.

**Comment by MartinMedinaSTK** [comment]
Error:

6/5/2019 4:45:31 PM - Excel Dateformat3 in WSNameSunat in column 10: Running
05/06/2019 04:45:31 p. m. - Excel Dateformat3 in WSNameSunat in column 10 : Success
05/06/2019 04:45:31 p. m. - Excel DateFormat WSNameSunat column_index 10 source \"MM.dd.yyyy\" string(\"dd.MM.yy\"): Running
05/06/2019 04:45:31 p. m. - Error, there was no syntax that matched the instruction
05/06/2019 04:45:31 p. m. - Error, there was no syntax that matched the instruction
05/06/2019 04:45:31 p. m. - Excel DateFormat WSNameSunat column_index 10 source \"MM.dd.yyyy\" string(\"dd.MM.yy\") : Error

 Script:

## --- Carga archivo CSV --- 
Excel LoadCSV "<<<EnviormentDownloadsPath>>>detracciones.csv" separated_by , as WBNameSunat
Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat
Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 10
##Aplicar formato de fecha (DD.MM.YYYY) 
Excel Dateformat3 in WSNameSunat in column 10
Excel DateFormat WSNameSunat column_index 10 source \"MM.dd.yyyy\" string(\"dd.MM.yy\")

**Comment by MartinMedinaSTK** [comment]
@JuanISalazarM alguna novedad?

**Comment by JuanISalazarM** [comment]
Estoy revisando el código, lo ingresé a mi Turing, y no marca el error que muestra el Log.
Desconozco que está pasando porque la sintaxis parece correcta.
Probablemente sea la versión.
¿Que versión tiene actualmente?

**Comment by JuanISalazarM** [comment]
Intente mandar llamar la instrucción sin el Backslash.

`Excel DateFormat WSNameSunat column_index 10 source "MM.dd.yyyy" string("dd.MM.yy")`

De esta manera.

**Comment by JuanISalazarM** [comment]
Buenos días @MartinMedinaSTK  .
¿Se ha realizado la prueba?
Estaré atento a su respuesta.

**Comment by MartinMedinaSTK** [comment]
sigue mal, ojo porque con esta función esta cortando el año da dos dígitos:
![image](https://user-images.githubusercontent.com/49758327/59045653-dd20f380-8856-11e9-9c6f-fcd953897c6e.png)

**Comment by MartinMedinaSTK** [comment]
la versión de Turing que tengo yo es:
![image](https://user-images.githubusercontent.com/49758327/59045755-0ccffb80-8857-11e9-88ee-04982a415528.png)

La versión de Turing que tengo en la MV del cliente es:

![image](https://user-images.githubusercontent.com/49758327/59045891-44d73e80-8857-11e9-9e13-8d75210595b8.png)

**Comment by MartinMedinaSTK** [comment]
@JuanISalazarM @gantonioid @RickProductivity gente por favor, necesito que este problema se  solucione en el día de hoy, es un bug que tenemos en un bot que está en productivo y estamos desde ayer sin poder resolverlo.  

Por las evidencias esta claro que es un error en la función Dateformat3. Vuelvo a copiar el script original que estoy usando en el bot:

## --- Carga archivo CSV --- 
Excel LoadCSV "<<<EnviormentDownloadsPath>>>detracciones.csv" separated_by , as WBNameSunat
Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat
Excel ReplaceCharacter "/" from the worksheet WSNameSunat with "." in the row with the index 10
##Aplicar formato de fecha (DD.MM.YYYY) 
Excel Dateformat3 in WSNameSunat in column 10
Excel ApplyFormat from WSNameSunat in_column_index 5 format 0
Excel ApplyFormat from WSNameSunat in_column_index 8 format 0
Excel RemoveRows from WSNameSunat where 8 equals <<<xlsRUC>>> start_at 2
Titanium Sleep 5000  

Necesito que se solucione el problema cuanto antes, revisen la función si ya pudo @JuanISalazarM generar el error.

**Comment by JuanISalazarM** [comment]
¿Tendrá de casualidad el archivo "detracciones.csv", antes de realizar el LoadCSV?
Para realizar pruebas del cambio de fecha antes de utilizar el DateFormat3.
Si es así, solicito que comparta el archivo por este medio para evitar tener que buscarlo en TEAMS. Gracias.

**Comment by MartinMedinaSTK** [comment]
@JuanISalazarM lo que me estas pidiendo ya me lo pediste ayer (exactamente hace 22 hs) fijate en este mismo chat, mas arriba vas a encontrar un archivo con nombre detracciones.zip ese es el archivo tal cual se baja de la pagina web antes de que lo procese Excellium. 
Si te fijas en los comentarios del día de ayer dijiste que con este archivo no habías podido hacer que funcione la instrucción que me enviaste. 

Por favor, no dejemos los temas colgados y más cuando son bugs productivos.

**Comment by Johhnn117** [comment]
Estamos buscando una solución, te avisamos lo más pronto posible

**Comment by JuanISalazarM** [comment]
Buenas tardes señor.
Se ha actualizado el Turing con una nueva función para este problema. Solicito de favor realizar la prueba con las siguientes instrucciones para cargar el archivo CSV.
Instrucciones:
`Excel LoadCSVFixed "<<<EnviormentDownloadsPath>>>detracciones.csv" separated_by , as WBNameSunat`
`Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat`
`Excel DateFormat WSNameSunat column_index 10 source "dd/MM/yyyy" string("dd.MM.yyyy")`

**Comment by MartinMedinaSTK** [comment]
Hola @JuanISalazarM hice una prueba y parecería funcionar bien. Te hago una consulta, al cambiar la función de carga de CSV (LoadCSVFixed), antes lo hacia con LoadCSV, el resto de las funciones que yo aplico sobre el csv siguen funcionando?

Por ejemplo: 
Excel ApplyFormat from WSNameSunat in_column_index 5 format 0
Excel ApplyFormat from WSNameSunat in_column_index 8 format 0
Excel RemoveRows from WSNameSunat where 8 equals <<<xlsRUC>>> start_at 2

Por otro lado, necesitaría que generen la version de Turing offline para Excellia con este cambio incluido, agrego a @andresCruzF que él fue quien se encargo de generar las anteriores.

Gracias

**Comment by gantonioid** [comment]
Hola Martín

Deben de seguir funcionando de la misma manera todas las otras funciones, lo que se hizo fue "evitar" que Excel cambiara los valores "12/05/2019" a un tipo Fecha... porque siendo Fechas no se pueden filtrar después comparando con un string (lo que haces en RemoveRows).

Todo esto porque Fecha no se puede comparar con String.

Ahora, en cuanto a la versión que quieres actualizar... puedes copiar el TuringExpo.exe que tienes ya corregido y probado (derecha), dentro de la carpeta de Turing offline que quieres actualizar(izquierda).
![image](https://user-images.githubusercontent.com/9600868/59112315-66dcc980-8908-11e9-85a7-a17c3cd1c96f.png)

Nos avisas si necesitas ayuda o cerramos el ticket

**Comment by gantonioid** [comment]
Era un tema urgente y en todo el día no se recibió insistencia del problema. Cierro el issue

**Comment by MartinMedinaSTK** [comment]
@gantonioid no respondí el viernes porque no tenemos acceso a la MV del cliente cuando estamos fuera de la red de Softtek. De todas maneras el viernes hice una prueba en mi máquina y funcionó (lo informe por este mismo medio mas arriba), pero quiero probarlo en la MV del cliente para cerrar el tema, que lo haré en el día de hoy.  

Por otro lado, cuando hablamos de procesos que están en producción, y definimos niveles de necesidad, tenemos alguna especie de tiempo de compromiso para la resolución según su criticidad?

**Comment by gantonioid** [comment]
Sí vi que respondiste que funciona en tu máquina, es por eso que cerré el ticket. Cuando hagas las pruebas en la MV del cliente, nos avisas si tienes problemas.

Los niveles de criticidad nos ayudan para priorizar, y la intención es resolverlo pronto. No te voy a dar un tiempo de compromiso general para todos los casos _urgentes_, _prioridad alta_ etc. porque cada problema es diferente, independientemente de su nivel de urgencia.

Lo que yo quiero saber es **por qué el problema de este ticket en particular se descubrió hasta que entramos en productivo**?? **No se había probado antes en esa MV o ambiente??**
No entiendo ese procedimiento de parte de ustedes y deben de tener claro que es riesgoso hacer cambios de último minuto, ya sea del script o la máquina ejecutora.

**Comment by MartinMedinaSTK** [comment]
@gantonioid solo lo ultimo, acá termino y porque me estas preguntado. Como se ve en la imagen que está a continuación, la función Dateformat3 funcionaba bien para fechas donde el día era mayor a 12 ( no me preguntes porque... esa respuesta se la dejo a ustedes): 

![image](https://user-images.githubusercontent.com/49758327/59203544-2fbf2000-8b75-11e9-9b5d-366a81b2368d.png)

Las pruebas se hicieron en la MV con el cliente a fines de mayo (semana del 26/5) y todo estaba ok, cuando se puso en productivo el proceso el 4 de junio comenzamos a visualizar el error.

"No entiendo ese procedimiento de parte de ustedes y deben de tener claro que es riesgoso hacer cambios de último minuto, ya sea del script o la máquina ejecutora."

No te preocupes que tenemos bien claro lo riesgoso que es pedir un cambio en Turing ya que, por experiencias ya vividas, cada update de turing tenemos que volver a revisar todos los procesos por si alguno dejo de funcionar, con todo el re trabajo que eso nos implica, es más, te confirmo que somos los que más deseamos que Turing funcione perfectamente, pero bueno... eso ya está fuera de nuestro alcance.

Te mando un saludo y gracias por el soporte de siempre.

**Comment by MartinMedinaSTK** [comment]
@gantonioid encontré una diferencia entre el archivo original y el modificado por Turing. 

Archivo original ( _detracciones.csv ): 
![image](https://user-images.githubusercontent.com/49758327/59206506-70219c80-8b7b-11e9-820e-b2cefe75e065.png)


Archivo modificado por turing ( detracciones.csv ): La segunda fecha no tiene formato de fecha. Justo es el ultimo registro del archivo.
![image](https://user-images.githubusercontent.com/49758327/59206541-8891b700-8b7b-11e9-87e5-3749b3443a81.png)

[Downloads.zip](https://github.com/FridaSupport/TuringSuport/files/3272728/Downloads.zip)

Me avisas?

Por favor abrir el issue nuevamente.

**Comment by MartinMedinaSTK** [comment]
@gantonioid puede ser que en la versión que se actualizó en el día de hoy no tenga la nueva instrucción para cargar el csv?

Me esta dando error en:
6/10/2019 2:22:56 PM - Excel LoadCSVFixed "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat: Running
6/10/2019 2:22:58 PM - Error LoadCSVFixed "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat
6/10/2019 2:22:58 PM - Excel LoadCSVFixed "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat : Error

**Comment by gantonioid** [comment]
@MartinMedinaSTK Se actualizó tu usuario? el error es en tu máquina o en la MV?

**Comment by gantonioid** [comment]
@JuanISalazarM Puedes investigar qué sucedió?

**Comment by JuanISalazarM** [comment]
Seguro, estoy en eso.

**Comment by MartinMedinaSTK** [comment]
@gantonioid es todo con mi usuario en mi maquina, todavía no lo pase a la MV.

**Comment by MartinMedinaSTK** [comment]
Versión de Turing: 20190607T0731

**Comment by JuanISalazarM** [comment]
Realicé un cambio en la función LoadCSVFixed, con los archivos que amablemente proporcionó.
Anexo una imagen del resultado obtenido luego de haber realizado las instrucciones:
-LoadCSVFixed
-LoadWSheet
-DateFormat

![image](https://user-images.githubusercontent.com/50111840/59216435-394e8500-8b81-11e9-9cd2-428ea5ba98e0.png)

Con esto dicho, quisiera notificarle que su versión de Turing ha sido actualizado. Solicito de favor volver a realizar la prueba y notificar cualquier inconveniente.
Agradecemos su tiempo. Esperamos su respuesta.

**Comment by MartinMedinaSTK** [comment]
ok ya lo pruebo.

**Comment by MartinMedinaSTK** [comment]
@JuanISalazarM @gantonioid les paso las novedades sobre este tema. hice pruebas en la MV del cliente con datos de producción y ahora tenemos otro problema, si bien el problema de la fecha parece estar resuelto, al momento de subir el archivo csv a SAP los datos del archivo se suben todos en una sola columna, como se muestra a continuación: 

![image](https://user-images.githubusercontent.com/49758327/59277571-d28ba300-8c36-11e9-89c3-1746d15df842.png)

Cuando deberían quedar de esta manera: 

![image](https://user-images.githubusercontent.com/49758327/59279372-2e0b6000-8c3a-11e9-95e3-96907147a964.png)

Les adjunto los siguientes archivos: 

- detracciones_Original.csv --> archivo original descargado de la web de SUNAT.
- DETRAC_procesado por Turing.csv --> archivo procesado por la ultima versión de Turing para subir a SAP 
- DETRAC_procesado por Turing versión Anterior.csv --> archivo procesado por la versión anterior de Turing que solo tenia el problema de las fechas.

El problema para mi en este caso es que el formato del archivo que genera Turing se rompió, con la nueva versión de turing se solucionó el tema de la fecha pero se rompió el formato del archivo completo, por eso es que SAP no puede separar los datos en las columnas correspondientes.

Con este cambio de Turing, directamente el bot no puede procesar nada de la información y termina dando un error que le llega al cliente, y deben realizar toda la operación manualmente.

Les pido que por favor verifiquen perfectamente que los cambios que realizan sobre Turing no rompan nada de lo que ya esta funcionando, para evitar que estos problemas vuelvan a pasar, y mas teniendo en cuenta que estamos trabajando sobre un bot que tiene un bug y que ya esta productivo.

@RickProductivity @pablo.reitano.softtek
[detracciones.zip](https://github.com/FridaSupport/TuringSuport/files/3277095/detracciones.zip)

**Comment by gantonioid** [comment]
@MartinMedinaSTK te estoy escribiendo en teams, estás?

**Comment by gantonioid** [comment]
necesito saber qué instrucciones usas para pasar la info de Excel a SAP

**Comment by MartinMedinaSTK** [comment]
Estaba en una call.

La transacción (zarp146) tiene un upload del archivo:
![image](https://user-images.githubusercontent.com/49758327/59284961-8bf07580-8c43-11e9-9883-311a1dfcaf02.png)

**Comment by gantonioid** [comment]
Encontramos solución, en un momento te mandamos la actualización.

**Comment by JuanISalazarM** [comment]
@MartinMedinaSTK 
Su versión de Turing ha sido actualizado. Solicito de favor volver a realizar la prueba y notificar cualquier inconveniente.
Agradecemos su tiempo. Esperamos su respuesta.

**Comment by gantonioid** [comment]
@MartinMedinaSTK cómo salió la prueba?

**Comment by MartinMedinaSTK** [comment]
@gantonioid recién termine de correr la prueba en la MV de cliente, justo se dio que había problemas con la web de SUNAT que consultamos, por lo cual no podíamos correr el proceso completo y terminaba con error.  De todas maneras ya corrió correctamente en producción con resultado exitoso. 
Gracias por el soporte.
Saludos.

**Comment by MartinMedinaSTK** [comment]
cierro el issue
