### ISSUE TITLE
[Excellia] Urgente. SAP FindText no permite rescribir la variable en la nueva versión de turing

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#178]
Buenos días,
El día de hoy acepte la actualización de Turing, y comencé a tener inconvenientes sobre escribiendo las variables de SAP FindText, En la primer vuelta se ejecuta sin problema pero en la segunda indica el siguiente error.

05/06/2019 10:42:29 - SAP FindText "No existen registros a adicionar VERIFICAR log" as IdVerificaLog: Running
05/06/2019 10:42:30 - System.ArgumentException: Ya se agregó un elemento con la misma clave.
   en System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   en System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   en System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   en SapScriptReader.SapScriptExecute.FindText(String action) en C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:línea 2018
   en SapScriptReader.SapScriptExecute.SelectAction(String action) en C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:línea 518
   en SapScriptReader.SapScriptExecute.RunLine(String paso, Dictionary`2 variables) en C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:línea 157
05/06/2019 10:42:30 - SAP FindText "No existen registros a adicionar VERIFICAR log" as IdVerificaLog : Error

**Comment by raulpoltiSTK** [comment]
@FridaSupport buenas, necesitamos darle curso a este tema. Nos dan una mano. Gracias

**Comment by eradgg** [comment]
Hola Soledad, te subí una versión nueva.

¿Podrías revisarla? si tienes algún otro problema con esa versión avísame por favor, para ayudarte si se perdió otra cosa.

Saludos.

**Comment by SoledadNunez** [comment]
Buenas tardes, actualice la versión que me mencionas pero ahora no puedo ejecutar los procesos porque se cierra frida:

![image](https://user-images.githubusercontent.com/25591982/58986518-f4f36b80-87b3-11e9-8835-3cc36d46b43f.png)

**Comment by SoledadNunez** [comment]
Buenos días, hay alguna novedad de este tema?

**Comment by eradgg** [comment]
Ya te subí una nueva versión Victor, con la función Doucle click.

Favor de probarls, la sintaxis es la siguiente:
DoubleClick ElementId wnd[0]/sbar

**Comment by eradgg** [comment]
Hice el cambio pero Soledad no ha podido descargar ni volver a correr Turing, ya estuvimos en llamada pero el problema es que Turing no le descarga, podrían ayudarnos @andresCruzF, @gantonioid?

**Comment by eradgg** [comment]
@SoledadNunez Funcionó?

**Comment by SoledadNunez** [comment]
No, ejecuta algunas acciones pero luego da error.

**Comment by SoledadNunez** [comment]
La versión descargada ayer no funciono, siguió dando error al ejecutar procesos.

Elimine la versión y no eh logrado volver a descargarla.

![image](https://user-images.githubusercontent.com/25591982/59104512-254c1e80-8908-11e9-9ae9-08da2c5bfb99.png)

![image](https://user-images.githubusercontent.com/25591982/59104534-339a3a80-8908-11e9-93f7-a9852166d6b5.png)

No aparece la opción para guardar el archivo en la computadora, se deja varios minutos pero no aparece.

**Comment by gantonioid** [comment]
Tienes que aceptar esa alerta "Process Saved", después de aceptarla es que se empieza a procesar tu pedido y toma un par de minutos la descarga.

**Comment by SoledadNunez** [comment]
si, si, la acepte y lo deje mas de 15 minutos a ver si aparecía.. Pero nunca me da la opción de guardar ni lo descarga automáticamente.

**Comment by SoledadNunez** [comment]
Buenas tardes, ya pude probar la función sin problemas, Cierro el issue, muchas gracias.
