### ISSUE TITLE
[Turn on event Listener] Urgente. Se cierra la ventana de Listener Windows

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#179]
Al utilizar la función, Turn on event Listener, y ejecutar el proceso de Microsoft Flow, se cierra automáticamente y no ejecuta el bots, hace un par de días funcionaba correctamente

![Listen](https://user-images.githubusercontent.com/49756748/58964073-46800400-877c-11e9-8fd2-d224c6bd892a.PNG)

**Comment by gantonioid** [comment]
@victorgamboa parece que no seguiste la documentacion. Necesitas enviar los valores que van a tomar las variables de tu script, tengo tres registros de ejecuciones del proceso sofia1072851774 iniciados el día de hoy por tu usuario, pero no enviaste los JsonParams

Aquí la referencia del API remoto
[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Remoto%20y%20Scheduling.one%7C21c7d51f-bc2f-4d07-9e52-ba06e3cee982%2FAPI%20llamado%20RPA%20remoto%7C3a59e25c-cf89-4cb7-8b25-617d9110062a%2F%29&wdorigin=703](url)

Si dices que funcionaba previamente, entonces puede ser error tuyo en la extracción de parámetros desde FLOW, porque el request no nos está llegando con los JsonParams que te comento.

**Comment by gantonioid** [comment]
Al tener el script unas variables configuradas, el Turing las "espera", al llegar nulas puede ser eso lo que provoca que se cierre.

**Comment by victorgamboa** [comment]
Esa configuración tengo en Flow, nunca mas la modifique y funcionaba correctamente,
Hoy probé el flujo y aparece el error que les comento, lo podríamos revisar en una call?

![Flow](https://user-images.githubusercontent.com/49756748/58966925-2d2d8680-8781-11e9-8df1-7ede9dcceca7.PNG)

**Comment by victorgamboa** [comment]
El problema que tenia, era es que yo ingrese una variable tipo Password, la cambie por variable texto y funciono correctamente.

![Password](https://user-images.githubusercontent.com/49756748/58986596-bce82a80-87ab-11e9-8635-000e2fe9e77d.PNG)

![Flow](https://user-images.githubusercontent.com/49756748/58986839-3e3fbd00-87ac-11e9-97ad-37dd99e100e8.PNG)


ahora ese parámetro no lo puedo guardar en Flow, como lo puedo rescatar o volver a obtener desde un archivo de configuración en tiempo de ejecución?

**Comment by gantonioid** [comment]
Habías adjuntado antes un screenshot diferente, lo cual demuestra que sí cambiaste los JsonParams que te dije al principio.

La respuesta sobre lectura de archivos locales (los que quieres usar como "configuración")
Existen estas funciones para leer archivos txt con instrucciones del script en FRIDA
- [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/GetAllLines](url)
- [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/GetAllText](url)

Pero al ser contraseñas, no lo recomiendo ya que los archivos no están encriptados. A menos que tengas un CustomLocal que encripte y desencripte esos txt, pero la solución quedaría de tu lado.

**Comment by gantonioid** [comment]
Se está desviando el tema original, y las preguntas fueron contestadas. Si se tiene un reporte de error, favor de abrir un ticket nuevo.
