### ISSUE TITLE
No escribe valores de un excel a otro

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#18]
Guardo "23-Apr-19 12:00:00 AM" como valor dinamico tomado de un excel. Prosigo a abrir otro excel y escribir dicha variable y da error. El log no muestra nada... 
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3113702/log.txt)

Agradeceria su pronta respuesta

**Comment by gantonioid** [comment]
Revisa la sintaxis, no le estás indicando en qué hoja quieres escribir
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/Write](url)
