### ISSUE TITLE
[TITAN] Instruccion ReadColumn sin parametro "with nulls" trae nulls.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#180]
Estimados,

La instruccion ReadColumn, me trae elementos vacios, se adjunta log:

Excel ReadColumn from the worksheet miHoja with the column index {1} and save its value as {cuentaLista}

6/5/2019 4:59:41 PM - Excel ReadColumn from the worksheet miHoja with the column index {1} and save its value as {cuentaLista}: Running
6/5/2019 4:59:41 PM - Se agrego una nueva variable : 
Var Name : cuentaLista
Value : CSC-IF - Cuadratura Locales Interfase Histórica - CTA_CPT ;  ; Empresa: ; CRUZ VERDE ; Cuenta ; 111040034 ; 111040310 ; 111040312 ; 111040314 ; 111040324 ; 111040325 ; 111040331 ; 111040334 ; 211040028 ; 211040076 ; 211040319 ; 211060311

![aaaaa](https://user-images.githubusercontent.com/33100638/58986661-4b60aa00-87b4-11e9-84f1-ce12344067c7.png)

Necesidad: Urgente.

**Comment by pablorlmx** [comment]
@FridaSupport, @RickProductivity  nos apoyan por favor! 
+@pabloreitanosofttek

**Comment by gantonioid** [comment]
Pueden pasar el archivo Excel?

**Comment by ClaudioRodolfoGarcete** [comment]
Se adjunta el excel en teams.

**Comment by Johhnn117** [comment]
Puedes compartir el log y el script?

**Comment by ClaudioRodolfoGarcete** [comment]
Compartido en teams.

**Comment by Johhnn117** [comment]
puedes revisar que tengas la versión 20190606T0408?

**Comment by ClaudioRodolfoGarcete** [comment]
Solucionado con la version: 20190606T0408

6/6/2019 2:10:06 PM - Excel ReadColumn from the worksheet miHoja with the column index {1} and save its value as {cuentaLista}: Running
6/6/2019 2:10:07 PM - Se agrego una nueva variable : 
Var Name : cuentaLista
Value : **CSC-IF - Cuadratura Locales Interfase Histórica - CTA_CPT ; Empresa: ; CRUZ VERDE ; Cuenta ; 111040034 ; 111040310 ; 111040312 ; 111040314 ; 111040324 ; 111040325 ; 111040331 ; 111040334 ; 211040028 ; 211040076 ; 211040319 ; 211060311**
6/6/2019 2:10:07 PM - Excel ReadColumn from the worksheet miHoja with the column index {1} and save its value as {cuentaLista} : Success
6/6/2019 2:10:07 PM - DefineVariable type "number" as "numFilaColA" with the value "1": Running
