### ISSUE TITLE
Log if

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#181]
Ayudaria bastante en la identificación de errores que en el log, en vez de mostrar if block: true, diga exactamente que se esta comparando, bien sea con el valor de la variable o con el nombre de dichas variables

Prioridad: Media

**Comment by gantonioid** [comment]
Para saber qué es lo que se compara puedes escribir lo que está dentro de la condición una línea antes del if así:

```
Message voy a comparar "a" con "b"
if ("a" -eq "b")
```

De esta manera hasta te aparecería en la ventana de Turing

**Comment by andresCruzF** [comment]
Hola @jaristimuno 

En conjunto con el update del ticket #186 realizare este cambio,

Saludos.
