### ISSUE TITLE
[TITAN]Error en sentencia CreatePivotTable cuando se utiliza el WriteVariableValue

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#182]
Buenas tardes

en issue #137 se desarrollo una nueva funcionalidad para que cuando se realizara una escritura en el excel no se copiara las celdas vacias  el cual para lo que se requerida para ese caso es exitoso.

pero cuando se ejecuta el siguiente paso de la automatización que en este caso es crear una tabla dinámica  con la sentencia CreatePivotTable sale error,

cabe resaltar que esto por el momento pasa con la nueva implementación
se adjunta el fuente y log

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3258893/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3258898/codigo.txt)

**Comment by JuanISalazarM** [comment]
Podría proporcionar los archivos Excel, luego de haber realizado la copia, porfavor?
Para evitar tener que hacer el paso de copiar e ir directamente a la instrucción que está trayendo problemas.
Gracias, esperamos su respuesta.

**Comment by rrrios** [comment]
solo se adjunta un excel, ya que el otro es un excel vacio
[OBIEE X CTA. 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3258952/OBIEE.X.CTA.27-03.xlsx)

**Comment by JuanISalazarM** [comment]
Como se le había comentado en el chat de TEAMS. Se agrega una columna extra. Esta está haciendo que truene al querer crear el PivotTable.

![image](https://user-images.githubusercontent.com/50111840/58995128-92e93500-87b8-11e9-8fe6-a99cc385bd64.png)

Porfavor utilice la instrucción RemoveCols para eliminar la columna dentro del código. Le anexo la documentación de la función:
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/RemoveCols

**Comment by JuanISalazarM** [comment]
Buenos días @rrrios .
¿Se ha realizado la prueba?
Estaré atento a su respuesta.
