### ISSUE TITLE
Log no muestra algo mas que "error"

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#183]
Al momento de escribir en un excel, me da el siguiente error.
![image](https://user-images.githubusercontent.com/49946883/59003693-5edc3700-87ed-11e9-97c9-fb51f5b159b2.png)

Adjunto dejo el log, copia del script y el archivo donde esta intentando escribir

[copia.txt](https://github.com/FridaSupport/TuringSuport/files/3259822/copia.txt)
[archivofinal.xlsx](https://github.com/FridaSupport/TuringSuport/files/3259823/archivofinal.xlsx)
[archivoescritura.xlsx](https://github.com/FridaSupport/TuringSuport/files/3259824/archivoescritura.xlsx)

Prioridad: Alta

**Comment by gantonioid** [comment]
@jaristimuno Usas esa instrucción correctamente muchas veces antes de la línea 5590 de tu script, ahí empieza el primer error con la sintaxis de Write, el valor que quieres escribir debe de ir entre comillas y no las tienes
Tu instrucción:
`Excel Write <<<ValueDolarar2>>> in HojaF row <<<rowPosition>>> and column 3`
Debe ser
`Excel Write "<<<ValueDolarar2>>>" in HojaF row <<<rowPosition>>> and column 3`

Si aún así no funciona coméntalo y reabrimos
