### ISSUE TITLE
[TITÁN] [Excelium] SaveAs es incompatible con RemoveSheets

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#185]
Tengo el siguiente código, con el objetivo de recrear el error de mi verdadero proceso, en donde voy a traer y abrir un archivo, copiar datos a una nueva hoja, luego borrar dicha hoja y guardar el archivo con otro nombre:

```
CopyFile "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\RESET\Traspaso ADI.xls" to "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Traspaso ADI.xls" and save as "NewFileName"
Excel LoadWBook "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Traspaso ADI.xls" as TraspasoADI
Excel LoadWSheet TraspasoADI sheet_index 2 as hojaAsiento1
Excel Copy values from hojaAsiento1 to TraspasoADI sheet_name auxiliar start_at A1 transpose false
Excel RemoveSheets from TraspasoADI sheet auxiliar
Excel SaveAs TraspasoADI as ArchivoNuevo.xls in C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo
```
El proceso termina en error y este es el log correspondiente: [log (con RemoveSheets).txt](https://github.com/FridaSupport/TuringSuport/files/3261715/log.con.RemoveSheets.txt)

Ahora bien, si quito la línea _Excel RemoveSheets from TraspasoADI sheet auxiliar_  el proceso se ejecuta correctamente. Log: [log (sin RemoveSheets).txt](https://github.com/FridaSupport/TuringSuport/files/3261716/log.sin.RemoveSheets.txt)

Por desgracia en mi proceso real necesito borrar una hoja por lo que no me alcanza con deshacerme de tal línea.

---------------------------------------------------------------------------

Como alternativa opté por crear la hoja sin eliminarla (para así ver la diferencia entre archivos), luego guardar el archivo con un simple Save y por último hacer un CopyFile con el nombre nuevo. El código es el siguiente:

```
CopyFile "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\RESET\Traspaso ADI.xls" to "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Traspaso ADI.xls" and save as "NewFileName"
Excel LoadWBook "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\Traspaso ADI.xls" as TraspasoADI
Excel LoadWSheet TraspasoADI sheet_index 2 as hojaAsiento1
Excel Copy values from hojaAsiento1 to TraspasoADI sheet_name auxiliar start_at A1 transpose false
Excel Save TraspasoADI
CopyFile "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\RESET\Traspaso ADI.xls" to "C:\Users\cesar.lencina\Documents\-Sofía- Documentación y archivos\Ensayo\<<<nombre>>>.xls" and save as "NewFileName2"
```
Pero el archivo copiado no es el que guardé al final (con una hoja nueva) sino el que se abrió al principio sin modificaciones. Log correspondiente: [log (haciendo un copy).txt](https://github.com/FridaSupport/TuringSuport/files/3261895/log.haciendo.un.copy.txt)

---------------------------------------------

Adjunto el archivo que estoy utilizando: [Traspaso ADI.zip](https://github.com/FridaSupport/TuringSuport/files/3261924/Traspaso.ADI.zip)

---------------------------------------------

Necesito una solución para mañana lo más temprano posible para cualquiera de las dos situaciones, preferentemente la primera.

Gracias.

**Comment by FaustinoLechuga** [comment]
Lo estare revisando

**Comment by CesarEmanuelLencina** [comment]
En la segunda opción que comenté, cometí un error respecto al lugar de donde tomo el archivo. La segunda opción se ejecuta bien, sin embargo más adelante en mi código cuando intento cerrar un archivo (Excel Close LibroPlanilla) me tira error.

Adjunto el log correspondiente.
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3262725/log.txt)

**Comment by FaustinoLechuga** [comment]
Listo ya te libere una version 20190606T0637 que soluciona este error. Que es el que comentabas al principio, puebala y si funciona esperamos tu confirmacion.

**Comment by CesarEmanuelLencina** [comment]
Sí funciona perfectamente. Ya se puede cerrar el ticket.

¡Muchas gracias!
