### ISSUE TITLE
[Softtek-RPA interno] Comparación entre variables string y valor obtenido

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#186]
En el archivo req.txt esta la necesidad original ya que github me borra los nombres de las variables

Se tiene la variable Compa1 declarada como string con el valor `"'<<<fecha>>>'"` notese que esta entre comilla simple para que tome exactamente ese valor como una cadena de caracteres.

y se tiene la variable `<<<fecha>>>` que va a tomar el valor de una fecha durante la ejecucion.

Al momento de comparar la variable fecha contra Compa1, Compa1 tambien ha tomado el valor de la fecha y no se ha mantenido como string

![image](https://user-images.githubusercontent.com/49946883/59038700-d8097780-8849-11e9-9377-78b3f32eb2e6.png)

SystemNotify "Notification" with message "comparacion entre `"<<<fechararg2>>>"` y `"'<<<Comparacion1>>>'""`

`if ("<<<fechararg2>>>" -eq "'<<<Comparacion1>>>'")`

Se requiere que la variable Compa1 mantenga el valor string `<<<fecha>>>` ya que al momento de la ejecucion, si por error no encuentra el valor deseado, esta variable queda asi, no queda null ni "" o con valor alguno, queda con su nombre y ese caso necesito comparar si obtuvo el valor o se quedó con el nombre 

Adjunto les dejo el log y el script
[req.txt](https://github.com/FridaSupport/TuringSuport/files/3261943/req.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3261904/log.txt)
[copia.txt](https://github.com/FridaSupport/TuringSuport/files/3261909/copia.txt)

Prioridad: Alta
Necesidad: 06/06

**Comment by andresCruzF** [comment]
Hola @jaristimuno 

Me podrias explicar un pcoo mejor el requerimiento , por lo que entiendo se busca que durante la ejecucion del script la variable <<<Compa1 >>> mantrenga un valor de "<<<Fecha>>>" como string , mando un script de ejemplo ejecutado en la version vigente de FRIDA donde se cumple esta condición

![image](https://user-images.githubusercontent.com/49708627/59046343-747e4a80-8847-11e9-8d83-fcd2886b83ff.png)

![image](https://user-images.githubusercontent.com/49708627/59046387-87911a80-8847-11e9-90ed-801d00cfc08e.png)

**Comment by jaristimuno** [comment]
En el script que adjuntas el valor de Date es una fecha. Lo que yo comento seria que Date tuviese el valor de <<<nombre>>>,  es decir, que no se traduzca de <> al valor, sino que mantenga el <>

**Comment by andresCruzF** [comment]
Gracias por la acalaracion , ya comprendo el requerimiento lo trabajo a la brevedad y te libero un update

**Comment by andresCruzF** [comment]
![image](https://user-images.githubusercontent.com/49708627/59057488-1ad64a00-8860-11e9-864f-2be6711f05b8.png)

ID = 20190606T0638

**Comment by jaristimuno** [comment]
Necesitas algun input de mi parte?

**Comment by andresCruzF** [comment]
Hola @jaristimuno 

Este cambio esta impactando lña sintaxis de browpet por lo que sera retirado , te pido porfavor cambies la manera de armar el if para evitar el uso de esta tipo de logica 

Ejemplo 

if ("06/06/2019" -Match "Date")

Saludos , favor de confirmar para poder volver a cerrar este ticket

**Comment by jaristimuno** [comment]
Ok. No sabia que se podia usar la misma sintaxis de powershell. Gracias
