### ISSUE TITLE
[Excellia] - Error al recorrer una variable list con un foreach

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#187]
Fecha necesidad: Urgente
En lugar de recorrer una a una las posiciones del list, recorre uno a uno los caracteres de cada posición, y luego pasa a la siguiente posición, etc..
Adjunto: Código sin pass, log y video en Teams
[Error_Foreach.txt](https://github.com/FridaSupport/TuringSuport/files/3263177/Error_Foreach.txt)
[Error_Foreach_log.txt](https://github.com/FridaSupport/TuringSuport/files/3263179/Error_Foreach_log.txt)

**Comment by gantonioid** [comment]
El foreach puede recorrer sobre variables de tipo lista, string y diccionarios... Por lo que veo, iteras sobre la variable **SAPImportes**, y ésta la generas con la instrucción:
`SAP CopyGridCells GridId wnd[0]/usr/cntlGRID1/shellcont/shell/shellcont[1]/shell Rows "0-<<<CantLineas>>>" Column WRSHB as SAPImportes`

@eradgg qué tipo de variable es SAPImportes ??  Si es un string, entonces recorrer caracter por caracter **ES** el funcionamiento esperado del foreach en este caso

**Comment by eradgg** [comment]
Hola Ignacio, se necesitará crear una nueva función ya que esa genera un string, y necesitamos una lista.
¿Cuál es el proceso?

**Comment by gantonioid** [comment]
Eder toma la mejora para la instrucción de SAP.

No es bug de foreach

**Comment by eradgg** [comment]
Hola Ignacio, ya está hecha la función, sólo necesito probarla antes de subirla. Podrías pasarme el nombre o ID del proceso para hacer la prueba?
saludos.

**Comment by ignacionovio** [comment]
Buenisimo! el ID del proceso es 2049404524

**Comment by eradgg** [comment]
Ya tengo el proceso, necesita archivos para correr, me los podrías proporcionar por favor?
saludos.

**Comment by ignacionovio** [comment]
[Accesos.xlsx](https://github.com/FridaSupport/TuringSuport/files/3267265/Accesos.xlsx)

**Comment by eradgg** [comment]
Te subí una nueva versión. en vez de usa la fiunción CopyGridCells tienes que utilizar la siguiente: CopyGridCellsToList 
Se usa la función con la misma sintaxis de la otra, la única diferencia es que esta guardará una lista en vez de un string.

SAP CopyGridCellsToList GridId wnd[0]/usr/cntlGRID1/shellcont/shell/shellcont[1]/shell Rows "0-<<<CantLineas>>>" Column WRSHB as SAPImportes

**Comment by gantonioid** [comment]
Pendiente la prueba de la nueva función creada

**Comment by ignacionovio** [comment]
Funciona perfecto. Gracias!
