### ISSUE TITLE
Error Loading Files Turing en VM

### ISSUE THREAD

**Issue by DarioPalacios** [FridaSupport/TuringSuport#188]
El turing en la VirtualMachine me da Error Loading Files, tanto la version que uso en mi maquina como la version offline para vm

![errorLoading](https://user-images.githubusercontent.com/51096253/59110878-5af80400-8916-11e9-87f2-f407394aafcf.PNG)

Por ende desde la vm no puedo modificar scripts y solo corre procesos que no tengan adjuntos como imagenes o poweshell porque no los encuentra

![errorImagen](https://user-images.githubusercontent.com/51096253/59111258-0d2fcb80-8917-11e9-9776-1b17ae6793c5.PNG)

Es una VM con Windows 7 de 64bits
Fecha de necesidad : 11/7/19

**Comment by andresCruzF** [comment]
Hola @DarioPalacios  lo reviso y a  la brevedad me pongo en contacto contigo

**Comment by andresCruzF** [comment]
Favor de rivisar tu correo , en el te he compartido un archivo con la finalidad de solucionar este problema o en su defecto poder analizarlo a mayor detalle.

Saludos

**Comment by DarioPalacios** [comment]
Hola alguna novedad con esto ? Respondi el mail que me enviaron adjuntando el STKA.autocomplete.json y probe con el STKA.autocmoplete.json que me enviaron pero sigue sin andar.
Saludos

**Comment by raulpoltiSTK** [comment]
Buenas, necesitamos resolver este tema. El dia viernes salimos a Produccion con el cliente y aun no hemos tenido novedades. @andresCruzF @RickProductivity @FridaSupport

**Comment by andresCruzF** [comment]
Hola @DarioPalacios 

Nos encontramos buscando solución al problema de Edit Instructions , asi mismo te comparto una nueva versión de Turing para poder validar que ya no se tenga problema tratando de encontrar la imágenes requeridas por Titanium. Quedo al pendiente en caso de que el error persista. 

ID = 20190612T0744

Saludos , continuaremos revisando el error que se presenta en el proceso de editar el script en esta computadora.

**Comment by DarioPalacios** [comment]
Hola, el error persiste. Sigo sin poder modificar ni correr procesos con imagenes de titanium
o powershells desde el turing de la maquina virtual

![errorImagenes](https://user-images.githubusercontent.com/51096253/59382359-e8cb5900-8d33-11e9-9cda-11d98b9be634.PNG)

**Comment by DarioPalacios** [comment]
@andresCruzF podriamos ver este problema por skype ? @FridaSupport

**Comment by andresCruzF** [comment]
Hola @DarioPalacios 

Podrias borrar las carpetas de "/App/screenshots" y la de "/App/121083690/0/screenshots" y compartirme capturas de pantalla del contenidio de las carpetas al termino de la ejecucion del proceso esto para poder invetigar mas del error. De igual forma me gustaria ver si puedes tener una sesion mañana a las 9:30 am (Horario Mexico)?

Saludos

**Comment by DarioPalacios** [comment]
Hola @andresCruzF 
Si por favor espero la sesion de las 9:30. Gracias
Saludos

**Comment by DarioPalacios** [comment]
Hola @andresCruzF @FridaSupport , todavia estoy esperando la sesion para ver este tema. Por favor cuanto antes mejor.
Saludos

**Comment by raulpoltiSTK** [comment]
@FridaSupport @andresCruzF Necesitamos poder resolver este tema! Mañana tenemos Demo con el cliente y seguimos sin poder resolverlo. Gracias

**Comment by pabloreitanosofttek** [comment]
¿Cual es el status? @FridaSupport

**Comment by DarioPalacios** [comment]
Hola @FridaSupport @andresCruzF 
Te acerco 3 logs donde fallan los procesos en la virtual. Los mismo desde mi maquina corren bien.
De todas formas me gustaria poder ver este tema por skype. 
Saludos
[logIf.txt](https://github.com/FridaSupport/TuringSuport/files/3290944/logIf.txt)
[logImagenres.txt](https://github.com/FridaSupport/TuringSuport/files/3290945/logImagenres.txt)
[logPowershell.txt](https://github.com/FridaSupport/TuringSuport/files/3290947/logPowershell.txt)

**Comment by pabloreitanosofttek** [comment]
Sigo sin entender … ¿Cuál es el status? @DarioPalacios @andresCruzF  @gantonioid  @FridaSupport

**Comment by andresCruzF** [comment]
Hola @DarioPalacios 

Una disculpa por no haber podido tener la sesión , hemos estado impartiendo cursos y nos fue imposible , así mismo el equipo ha estado intentando resolver este problema logrando realizar varias pruebas con éxito en windows 7 , únicamente no hemos podido correr scripts de powershell por lo que la función de if y de scheduling siguen sin estar habilitadas para windows 7. Así mismo te pido me compartas captura de pantalla de la carpeta "App" y de la prueba solicitada anteriormente que coloco a continuación para validar porque Titanium marca error. Así mismo te mando un update para que las pruebas se realicen con los últimos cambios que hemos estado realizando.

_Podrias borrar las carpetas de "/App/screenshots" y la de "/App/121083690/0/screenshots" y compartirme capturas de pantalla del contenidio de las carpetas al termino de la ejecucion del proceso esto para poder invetigar mas del error._ 

Por ultimo me gustaria tener una sesion el dia de mañana a las 10 am (Hora Mexico) de ser posible o en su defecto el dia de hoy de ser posible.

Saludos.

**Comment by pabloreitanosofttek** [comment]
Un solo comentario, en ARG el Lunes (hoy) y el Jueves son festivos… Por otro lado, revisemos el detalle si funciona o no con Win7… Recuerden que lo pregunté expresamente y me dijeron que si funcionaba y que lo podíamos dejar en las propuestas.

Sds
PR

**Comment by DarioPalacios** [comment]
Hola @andresCruzF @FridaSupport 
Si borro ambas carpetas en el frida offline me da un error de image not found comun:

![errorOffline](https://user-images.githubusercontent.com/51096253/59689925-e98e4000-91b6-11e9-9c3b-b53bf50ca547.PNG)

Si las borro en el frida online me crea la carpeta screenshots 
y me da el mismo error anterior

[logImagenesSinCarpetas.txt](https://github.com/FridaSupport/TuringSuport/files/3301790/logImagenesSinCarpetas.txt)

**Comment by DarioPalacios** [comment]
@andresCruzF @FridaSupport 

Hola, Andres te comparto el ultimo log de la virual que me pediste
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3302516/log.txt)

**Comment by DianaSTK** [comment]
Buenas tardes, @andresCruzF :
                                  Hay algún avance con lo hablado al medio día? Podrías indicarnos cuándo estiman tener una solución al problema? En función a ello veremos cómo proceder con el cliente que espera hace varios días la implementación del proceso. 
Muchas gracias!
Cualquier consulta o sugerencia, a tu disposición!

**Comment by DianaSTK** [comment]
Buenos días, @andresCruzF :
Hay algún avance con lo hablado ayer? Podrías al menos indicarnos cuándo estiman tener una solución al problema? En función a ello veremos cómo proceder con el cliente que espera hace varios días la implementación del proceso. 
Aguardo tu respuesta.
Cualquier consulta o sugerencia, a tu disposición!

**Comment by DianaSTK** [comment]
Buenas tardes, @RickProductivity @FridaSupport @andresCruzF : 
Les consulto, podremos tener el día de hoy una respuesta sobre el avance de la solución solicitada? Mañana es festivo en Argentina y el viernes por la mañana tenemos una reunión con el cliente para ver este tema. Necesitamos al menos contar con alguna fecha tentativa de cierre. 
Cualquier consulta, a su disposición.
Diana Martínez.-

**Comment by DarioPalacios** [comment]
Buenas tardes, @RickProductivity @FridaSupport @andresCruzF :
Les consulto, podremos tener el día de hoy una respuesta sobre el avance de la solución solicitada? Mañana es festivo en Argentina y el viernes por la mañana tenemos una reunión con el cliente para ver este tema. Necesitamos al menos contar con alguna fecha tentativa de cierre.
Cualquier consulta, a su disposición.

**Comment by pabloreitanosofttek** [comment]
@FridaSupport  este ticket es el más prioritario de toda la lista.... porfa necesito apoyo para su resolución.

¡Gracias! 
Slds,

**Comment by pabloreitanosofttek** [comment]
@andresCruzF @gantonioid  Este es el ticket más prioritario de toda la lista... en ARG hoy es festivo por lo que tal vez no tengas respuesta de @DarioPalacios o de @DianaSTK … les pido que puedan avanzar todo lo posible sin el apoyo dado que ya tiene unos días. 
¡Gracias!

**Comment by pabloreitanosofttek** [comment]
¿cual es el último status válido?

**Comment by DianaSTK** [comment]
Buen día, @pabloreitanosofttek,@RickProductivity @FridaSupport:
                                                    Desde el martes no hay novedades aunque intentamos contactarnos también vía skype con @andresCruzF .
El error persiste, lo último que comentó Andrés es que creía saber dónde se  originaba. Quedamos en revisarlo al final de ese día.
En unas horas tenemos revisión con el cliente y lamentablemente no tenemos forma de dar un pronóstico sobre este tema.
Cualquier consulta o sugerencia, me encuentro a disposición.

**Comment by DianaSTK** [comment]
Buenas tardes, @RickProductivity @FridaSupport @andresCruzF :
Les consulto, podremos tener el día de hoy una respuesta sobre el avance de la solución solicitada? Necesitamos al menos contar con alguna fecha tentativa de cierre.
Cualquier consulta, a su disposición.
Diana Martínez.-

**Comment by DianaSTK** [comment]
Buenas tardes, @RickProductivity @FridaSupport @andresCruzF :
Les consulto, podremos tener el día de hoy una respuesta sobre el avance de la solución solicitada? Necesitamos al menos contar con alguna fecha tentativa de cierre.
Cualquier consulta, a su disposición.
@pabloreitanosofttek , cómo podemos avanzar este tema? Hace dos semanas que mostramos el mismo estado al cliente.
Diana Martínez.-

**Comment by DarioPalacios** [comment]
Status del Dia:     @DianaSTK @andresCruzF @FridaSupport 
Se consulto por parte de Aldo Manuel Vega Quiroz del equipo de Innovation de México si este ticket tiene restriccion de ambiente lo cual es afirmativo, debe ejecutarse en esta maquina virtual. Y la posibilidad de que se pueda generar una máquina virtual igual a la utilizada pero con sistema operativo Windows 10 en vez de Windows 7, la respuesta fue negativa dado que el cliente utiliza Windows 7

**Comment by pabloreitanosofttek** [comment]
Y sumo que pregunté expresamente por WIN7 en otro ticket y fue afirmativa la respuesta... por lo que ahora, no puedo cambiarle al cliente la versión.

**Comment by pabloreitanosofttek** [comment]
Se pidió al cliente pasar a Win10 @DianaSTK  @andresCruzF … Si no se puede, tendremos que volver sobre le tema... ponerlo en "ON HOLD" ¡gracias!

**Comment by pabloreitanosofttek** [comment]
Hoy nos dieron la máquina nueva... atenti @DianaSTK  @DarioPalacios  @andresCruzF  @gantonioid  

¡gracias!

**Comment by DarioPalacios** [comment]
Buenas @FridaSupport @andresCruzF @DianaSTK @pabloreitanosofttek 
Estoy probando el Turing en la nueva virtual con Win10 y se arreglaron todos los errores **A excepcion del Titanium**.
Edit Instruccion    -       Funciona
If                            -     Funciona
Powershell              -    Funciona
**Titanium ClickImage   -     No Funciona**
Estoy usando el Turing Offline, exactamente este:
https://onesofttek.sharepoint.com/sites/SofttekLabs/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FSofttekLabs%2FShared%20Documents%2FTuringExpo%2FCooperaci%C3%B3n%20Seguros%2FTuring%20%2DCooperaci%C3%B3n%20Seguro%2Ezip&parent=%2Fsites%2FSofttekLabs%2FShared%20Documents%2FTuringExpo%2FCooperaci%C3%B3n%20Seguros&p=true&cid=1ebfba36-437f-4eb1-b9ca-e8c65baad13b volvi a descargarlo y solo agregue las sentencias para probar.
Adjunto el Log
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3336150/log.txt)

**Comment by DianaSTK** [comment]
Buendos días: @FridaSupport @andresCruzF @DarioPalacios  @pabloreitanosofttek
Debimos gestionar con el cliente el cambio a Win10. Ellos hicieron la modificación. Al verificar vemos que: Titanium ClickImage - No Funciona. Por favor, podrían ver este tema con prioridad? Dejamos más detalle arriba y por cualquier consulta técnica, @DarioPalacios se encuentra a disposición para responder.
Saludos.
Diana.-

**Comment by pabloreitanosofttek** [comment]
Este es el ticket más importante dado que debemos poner en prd este bot ya hecho y uno que está en camino... @Martin Gabriel Medina<mailto:martin.medina@softtek.com> puede apoyar

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: DianaSTK <notifications@github.com>
Enviado: viernes, junio 28, 2019 8:49 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] Error Loading Files Turing en VM (#188)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Buendos días: @FridaSupport<https://github.com/FridaSupport> @andresCruzF<https://github.com/andresCruzF> @DarioPalacios<https://github.com/DarioPalacios> @pabloreitanosofttek<https://github.com/pabloreitanosofttek>
Debimos gestionar con el cliente el cambio a Win10. Ellos hicieron la modificación. Al verificar vemos que: Titanium ClickImage - No Funciona. Por favor, podrían ver este tema con prioridad? Dejamos más detalle arriba y por cualquier consulta técnica, @DarioPalacios<https://github.com/DarioPalacios> se encuentra a disposición para responder.
Saludos.
Diana.-

**Comment by DianaSTK** [comment]
@FridaSupport @andresCruzF @DarioPalacios @pabloreitanosofttek:
Buenas tardes. Hay alguna novedad sobre esta  solicitud?

**Comment by DianaSTK** [comment]
@FridaSupport @andresCruzF @DarioPalacios @pabloreitanosofttek:
Buenas noches. Hay alguna novedad sobre esta solicitud?

**Comment by pabloreitanosofttek** [comment]
Hola! Este es el ticket más importante hace semanas... debe estar resuelto el lunes.... gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: DianaSTK <notifications@github.com>
Enviado: sábado, junio 29, 2019 8:20 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] Error Loading Files Turing en VM (#188)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


@FridaSupport<https://github.com/FridaSupport> @andresCruzF<https://github.com/andresCruzF> @DarioPalacios<https://github.com/DarioPalacios> @pabloreitanosofttek<https://github.com/pabloreitanosofttek>:
Buenas noches. Hay alguna novedad sobre esta solicitud?

**Comment by DianaSTK** [comment]
@FridaSupport @andresCruzF @DarioPalacios @pabloreitanosofttek:
Buenos días. Estamos a disposición por si requieren que validemos algo en los ambientes asignados. Aguardamos novedades.
Saludos,
Diana.-

**Comment by DianaSTK** [comment]
@FridaSupport @andresCruzF @DarioPalacios @pabloreitanosofttek:
Buenas tardes. Hay alguna novedad sobre esta solicitud? Podrían decirnos al menos si la están revisando? Tenemos que iniciar el desarrollo de otro BOT con el cliente y vamos a tener el mismo problema de no resolverse.
Quedo a la espera.
Saludos,
Diana.-

**Comment by pabloreitanosofttek** [comment]
@andresCruzF  @gantonioid  necesito apoyo para este ticket... es el más prioritario de toda la lista, hace ya unas semanas... Necesitamos una solución. 

¡gracias!

**Comment by DianaSTK** [comment]
@FridaSupport @andresCruzF @DarioPalacios @pabloreitanosofttek:
Buenos días. Estamos a disposición por si requieren que validemos algo en los ambientes asignados. Aguardamos novedades.
Saludos,
Diana.-

**Comment by DianaSTK** [comment]
@andresCruzF cómo estás? Pudieron encontrar el error?
Me gustaría tener al final del día un avance de la solución ya que mañana a la mañana debo hablar con el cliente por este tema.

Saludos.
@FridaSupport @DarioPalacios @pabloreitanosofttek:

**Comment by DianaSTK** [comment]
@andresCruzF cómo estás? Pudieron encontrar el error?
Hoy podrá estar listo? Por favor, me pueden responder?

Saludos.
@FridaSupport @DarioPalacios @pabloreitanosofttek:

**Comment by RickProductivity** [comment]
Hola Diana oye Andrés parece que ya lo resolvió pero necesita por lo menos todo el día de hoy para unas Pruebas y asegurarse que ahora si está resuelto. Gracias

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DianaSTK** [comment]
Muchas gracias, @RickProductivity !!
Si necesitan algo de nuestra parte, a disposición.
Saludos,
Diana.-

**Comment by andresCruzF** [comment]
Hola @DianaSTK  , @pabloreitanosofttek  , @raulpoltiSTK  , @DarioPalacios 

Ya se valido el funcionamiento de los diferntes modulos de FRIDA en la maquina virtual con windows 10 dejando instaladas dos versiones de Turing (Offline y Online) para su utilización. Favor de validar con el script que se estara ocupando en este ambiente.

Saludos , quedo al pendiente.

**Comment by DianaSTK** [comment]
Excelente noticia, @andresCruzF !!
Lo revisamos ni bien llegue @DarioPalacios  e informamos resultados.
Saludos!
Diana.-

**Comment by DianaSTK** [comment]
@FridaSupport @DarioPalacios @pabloreitanosofttek, @raulpoltiSTK, @RickProductivity : Buenos días! Les informamos que hemos verificado y el bug se encuentra resuelto. Procederemos ahora realizar las tareas de configuración para dejar el BOT corriendo. Muchas gracias por la colaboración! 
Saludos,
Diana.-
