### ISSUE TITLE
[Excellia] urgente - Foreach no recorre string

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#189]
Buenos días, en la ultima versión que me pasaron de turing dejo de funcionar el foreach con String, por lo que dejaron de funcionar varios procesos arrojando el siguiente error en pantalla,

![image](https://user-images.githubusercontent.com/25591982/59117103-67cf2480-8923-11e9-83a6-241006029166.png)

**Comment by Johhnn117** [comment]
puedes compartir el Script, log y el archivo del proceso?

**Comment by SoledadNunez** [comment]
@eradgg  esta mirando, dijo que va a generar una nueva versión de turing para probar esto si no llega a ser eso, te contacto para hacer una call y mostrar el funcionamiento, no es posible subir los archivos por los accesos que tienen, me eliminarían el TK.

**Comment by andresCruzF** [comment]
Hola @SoledadNunez 

He revisado el error y te he compartido un update por lo que te pido valides que se encuenyra funciuonando , asi mismo adjunto un log de evidencia de las pruebas realizadas con esta version.

![image](https://user-images.githubusercontent.com/49708627/59119612-da86d280-8918-11e9-8a9c-1ed442f4ddab.png)


Saludos.

**Comment by SoledadNunez** [comment]
Actualice y ya ingresa al foreach, pero me esta dando error un paso mas adelante, levanto otro git por este tema o lo continuamos en este? este código funcionaba 
Instruccion que falla
```
foreach caracter in Contrasena {
Web2 Click in selector="input[value='<<<caracter>>>']"
#Web2 Sleep 1000
}

```

Log
```
07/06/2019 14:46:03 - DefineVariable type "string" as "Contrasena" with the value "1509" : Success
07/06/2019 14:46:03 - Web2 Click in selector="input[value='<<<caracter>>>']": Running
7/6/2019 14:46:24 - {"error":"Element not found"}
07/06/2019 14:46:24 - Web2 Click in selector="input[value='<<<caracter>>>']" : Error
```

**Comment by andresCruzF** [comment]
Hola @SoledadNunez 

Te comparto una nueva version de Turing con este cambio resulto 

id = 20190607T0642

Saludos

**Comment by SoledadNunez** [comment]
Buenas tardes, ya logre ejecutar sin inconvenientes con esa nueva versión. 
Cierro el issue, muchas gracias
