### ISSUE TITLE
Problemas con un For

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#19]
Buenas tardes,
tengo el siguiente problema, tengo que recorrer un Excel y cuando venga una celda vacía debe enviar un mail. el tema es que aplique un for para que recorra todas las celdas que por ahora son 7 celdas, y al encontrar una celda vacía el mail se envía 7 veces, necesito alguna forma de que la instrucción no entre dentro del for y solo se envíe 1 mail...

**Comment by FaustinoLechuga** [comment]
Me podras comprartir tu script?

**Comment by victorgamboa** [comment]
DefineVariable type "number" as "incremento" with the value "14"
Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\SOFIA - Formulario de Solicitud de Cotización - v.1.0 - 11-04-2019.xlsx" as WBName
Excel LoadWSheet WBName sheet "Form Solicitud Cotización" as WSName
for 7 times {
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,2} and save its value as {valorCelda1}
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,3} and save its value as {valorCelda2}
#Message "<<<valorCelda1>>>"
#Titanium Sleep 1000
if ("<<<valorCelda1>>>" -eq "")
Message "Enviar_Mail"
SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos"
Titanium Sleep 1000
else
Message <<<valorCelda1>>>
Titanium Sleep 1000
end
#Message "<<<valorCelda2>>>"
#Titanium Sleep 1000
if ("<<<valorCelda2>>>" -eq "")
Message "Enviar_Mail"
Titanium Sleep 1000
else
Message <<<valorCelda2>>>
SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos"
Titanium Sleep 1000
end
MathOperation <<<incremento>>> + 1 and save as incremento
}

**Comment by victorgamboa** [comment]
25-04-2019 11:26:02 - Execution started
25-04-2019 11:26:02 - DefineVariable type "number" as "incremento" with the value "14": Running
25-04-2019 11:26:02 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 14
25-04-2019 11:26:02 - DefineVariable type "number" as "incremento" with the value "14" : Success
25-04-2019 11:26:02 - Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\SOFIA - Formulario de Solicitud de Cotización - v.1.0 - 11-04-2019.xlsx" as WBName: Running
25-04-2019 11:26:04 - Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\SOFIA - Formulario de Solicitud de Cotización - v.1.0 - 11-04-2019.xlsx" as WBName : Success
25-04-2019 11:26:04 - Excel LoadWSheet WBName sheet "Form Solicitud Cotización" as WSName: Running
25-04-2019 11:26:04 - Excel LoadWSheet WBName sheet "Form Solicitud Cotización" as WSName : Success
25-04-2019 11:26:04 - Excel ReadCell from the worksheet WSName from the cell {14,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:04 - Se agrego una nueva variable : 
Var Name : valorCelda1
Value : 1327167.000
25-04-2019 11:26:04 - Excel ReadCell from the worksheet WSName from the cell {14,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:04 - Excel ReadCell from the worksheet WSName from the cell {14,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:04 - Se agrego una nueva variable : 
Var Name : valorCelda2
Value : 8
25-04-2019 11:26:04 - Excel ReadCell from the worksheet WSName from the cell {14,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:04 - #Message "1327167.000": Running
25-04-2019 11:26:04 - Message "1327167.000" : Success
25-04-2019 11:26:04 - #Titanium Sleep 1000: Running
25-04-2019 11:26:04 - Titanium Sleep 1000 : Success
25-04-2019 11:26:04 - If Result : False
25-04-2019 11:26:04 - Else Block Running
25-04-2019 11:26:04 - Message 1327167.000: Running
25-04-2019 11:26:04 - Message 1327167.000 : Success
25-04-2019 11:26:04 - Titanium Sleep 1000: Running
25-04-2019 11:26:05 - Titanium Sleep 1000 : Success
25-04-2019 11:26:05 - #Message "8": Running
25-04-2019 11:26:05 - Message "8" : Success
25-04-2019 11:26:05 - #Titanium Sleep 1000: Running
25-04-2019 11:26:05 - Titanium Sleep 1000 : Success
25-04-2019 11:26:05 - If Result : False
25-04-2019 11:26:05 - Else Block Running
25-04-2019 11:26:05 - Message 8: Running
25-04-2019 11:26:05 - Message 8 : Success
25-04-2019 11:26:05 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:06 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:06 - Titanium Sleep 1000: Running
25-04-2019 11:26:07 - Titanium Sleep 1000 : Success
25-04-2019 11:26:07 - MathOperation 14 + 1 and save as incremento: Running
25-04-2019 11:26:07 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 15
25-04-2019 11:26:07 - MathOperation 14 + 1 and save as incremento : Success
25-04-2019 11:26:07 - Excel ReadCell from the worksheet WSName from the cell {15,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:07 - Se actualizo la variable : 
Var Name : valorCelda1
Value : 6I2510.000
25-04-2019 11:26:07 - Excel ReadCell from the worksheet WSName from the cell {15,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:07 - Excel ReadCell from the worksheet WSName from the cell {15,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:07 - Se actualizo la variable : 
Var Name : valorCelda2
Value : 4
25-04-2019 11:26:07 - Excel ReadCell from the worksheet WSName from the cell {15,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:07 - #Message "6I2510.000": Running
25-04-2019 11:26:07 - Message "6I2510.000" : Success
25-04-2019 11:26:07 - #Titanium Sleep 1000: Running
25-04-2019 11:26:07 - Titanium Sleep 1000 : Success
25-04-2019 11:26:07 - If Result : False
25-04-2019 11:26:07 - Else Block Running
25-04-2019 11:26:07 - Message 6I2510.000: Running
25-04-2019 11:26:07 - Message 6I2510.000 : Success
25-04-2019 11:26:07 - Titanium Sleep 1000: Running
25-04-2019 11:26:08 - Titanium Sleep 1000 : Success
25-04-2019 11:26:08 - #Message "4": Running
25-04-2019 11:26:08 - Message "4" : Success
25-04-2019 11:26:08 - #Titanium Sleep 1000: Running
25-04-2019 11:26:08 - Titanium Sleep 1000 : Success
25-04-2019 11:26:08 - If Result : False
25-04-2019 11:26:08 - Else Block Running
25-04-2019 11:26:08 - Message 4: Running
25-04-2019 11:26:08 - Message 4 : Success
25-04-2019 11:26:08 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:09 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:09 - Titanium Sleep 1000: Running
25-04-2019 11:26:10 - Titanium Sleep 1000 : Success
25-04-2019 11:26:10 - MathOperation 15 + 1 and save as incremento: Running
25-04-2019 11:26:10 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 16
25-04-2019 11:26:10 - MathOperation 15 + 1 and save as incremento : Success
25-04-2019 11:26:10 - Excel ReadCell from the worksheet WSName from the cell {16,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:10 - Se actualizo la variable : 
Var Name : valorCelda1
Value : 1R1808.000
25-04-2019 11:26:10 - Excel ReadCell from the worksheet WSName from the cell {16,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:10 - Excel ReadCell from the worksheet WSName from the cell {16,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:10 - Se actualizo la variable : 
Var Name : valorCelda2
Value : 8
25-04-2019 11:26:10 - Excel ReadCell from the worksheet WSName from the cell {16,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:10 - #Message "1R1808.000": Running
25-04-2019 11:26:10 - Message "1R1808.000" : Success
25-04-2019 11:26:10 - #Titanium Sleep 1000: Running
25-04-2019 11:26:10 - Titanium Sleep 1000 : Success
25-04-2019 11:26:10 - If Result : False
25-04-2019 11:26:10 - Else Block Running
25-04-2019 11:26:10 - Message 1R1808.000: Running
25-04-2019 11:26:10 - Message 1R1808.000 : Success
25-04-2019 11:26:10 - Titanium Sleep 1000: Running
25-04-2019 11:26:11 - Titanium Sleep 1000 : Success
25-04-2019 11:26:11 - #Message "8": Running
25-04-2019 11:26:11 - Message "8" : Success
25-04-2019 11:26:11 - #Titanium Sleep 1000: Running
25-04-2019 11:26:11 - Titanium Sleep 1000 : Success
25-04-2019 11:26:11 - If Result : False
25-04-2019 11:26:11 - Else Block Running
25-04-2019 11:26:11 - Message 8: Running
25-04-2019 11:26:11 - Message 8 : Success
25-04-2019 11:26:11 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:12 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:12 - Titanium Sleep 1000: Running
25-04-2019 11:26:13 - Titanium Sleep 1000 : Success
25-04-2019 11:26:13 - MathOperation 16 + 1 and save as incremento: Running
25-04-2019 11:26:13 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 17
25-04-2019 11:26:13 - MathOperation 16 + 1 and save as incremento : Success
25-04-2019 11:26:13 - Excel ReadCell from the worksheet WSName from the cell {17,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:13 - Se actualizo la variable : 
Var Name : valorCelda1
Value : 1R0719.000
25-04-2019 11:26:13 - Excel ReadCell from the worksheet WSName from the cell {17,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:13 - Excel ReadCell from the worksheet WSName from the cell {17,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:13 - Se actualizo la variable : 
Var Name : valorCelda2
Value : 4
25-04-2019 11:26:13 - Excel ReadCell from the worksheet WSName from the cell {17,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:13 - #Message "1R0719.000": Running
25-04-2019 11:26:13 - Message "1R0719.000" : Success
25-04-2019 11:26:13 - #Titanium Sleep 1000: Running
25-04-2019 11:26:13 - Titanium Sleep 1000 : Success
25-04-2019 11:26:13 - If Result : False
25-04-2019 11:26:13 - Else Block Running
25-04-2019 11:26:13 - Message 1R0719.000: Running
25-04-2019 11:26:13 - Message 1R0719.000 : Success
25-04-2019 11:26:13 - Titanium Sleep 1000: Running
25-04-2019 11:26:14 - Titanium Sleep 1000 : Success
25-04-2019 11:26:14 - #Message "4": Running
25-04-2019 11:26:14 - Message "4" : Success
25-04-2019 11:26:14 - #Titanium Sleep 1000: Running
25-04-2019 11:26:14 - Titanium Sleep 1000 : Success
25-04-2019 11:26:14 - If Result : False
25-04-2019 11:26:14 - Else Block Running
25-04-2019 11:26:14 - Message 4: Running
25-04-2019 11:26:14 - Message 4 : Success
25-04-2019 11:26:14 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:15 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:15 - Titanium Sleep 1000: Running
25-04-2019 11:26:16 - Titanium Sleep 1000 : Success
25-04-2019 11:26:16 - MathOperation 17 + 1 and save as incremento: Running
25-04-2019 11:26:16 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 18
25-04-2019 11:26:16 - MathOperation 17 + 1 and save as incremento : Success
25-04-2019 11:26:16 - Excel ReadCell from the worksheet WSName from the cell {18,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:16 - Se actualizo la variable : 
Var Name : valorCelda1
Value : 1G8878.000
25-04-2019 11:26:16 - Excel ReadCell from the worksheet WSName from the cell {18,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:16 - Excel ReadCell from the worksheet WSName from the cell {18,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:16 - Se actualizo la variable : 
Var Name : valorCelda2
Value : 4
25-04-2019 11:26:16 - Excel ReadCell from the worksheet WSName from the cell {18,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:16 - #Message "1G8878.000": Running
25-04-2019 11:26:16 - Message "1G8878.000" : Success
25-04-2019 11:26:16 - #Titanium Sleep 1000: Running
25-04-2019 11:26:16 - Titanium Sleep 1000 : Success
25-04-2019 11:26:16 - If Result : False
25-04-2019 11:26:16 - Else Block Running
25-04-2019 11:26:16 - Message 1G8878.000: Running
25-04-2019 11:26:16 - Message 1G8878.000 : Success
25-04-2019 11:26:16 - Titanium Sleep 1000: Running
25-04-2019 11:26:17 - Titanium Sleep 1000 : Success
25-04-2019 11:26:17 - #Message "4": Running
25-04-2019 11:26:17 - Message "4" : Success
25-04-2019 11:26:17 - #Titanium Sleep 1000: Running
25-04-2019 11:26:17 - Titanium Sleep 1000 : Success
25-04-2019 11:26:17 - If Result : False
25-04-2019 11:26:17 - Else Block Running
25-04-2019 11:26:17 - Message 4: Running
25-04-2019 11:26:17 - Message 4 : Success
25-04-2019 11:26:17 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:18 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:18 - Titanium Sleep 1000: Running
25-04-2019 11:26:19 - Titanium Sleep 1000 : Success
25-04-2019 11:26:19 - MathOperation 18 + 1 and save as incremento: Running
25-04-2019 11:26:19 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 19
25-04-2019 11:26:19 - MathOperation 18 + 1 and save as incremento : Success
25-04-2019 11:26:19 - Excel ReadCell from the worksheet WSName from the cell {19,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:19 - Se actualizo la variable : 
Var Name : valorCelda1
Value : 4S8598.000
25-04-2019 11:26:19 - Excel ReadCell from the worksheet WSName from the cell {19,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:19 - Excel ReadCell from the worksheet WSName from the cell {19,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:19 - Se actualizo la variable : 
Var Name : valorCelda2
Value : 2
25-04-2019 11:26:19 - Excel ReadCell from the worksheet WSName from the cell {19,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:19 - #Message "4S8598.000": Running
25-04-2019 11:26:19 - Message "4S8598.000" : Success
25-04-2019 11:26:19 - #Titanium Sleep 1000: Running
25-04-2019 11:26:19 - Titanium Sleep 1000 : Success
25-04-2019 11:26:19 - If Result : False
25-04-2019 11:26:19 - Else Block Running
25-04-2019 11:26:19 - Message 4S8598.000: Running
25-04-2019 11:26:19 - Message 4S8598.000 : Success
25-04-2019 11:26:19 - Titanium Sleep 1000: Running
25-04-2019 11:26:20 - Titanium Sleep 1000 : Success
25-04-2019 11:26:20 - #Message "2": Running
25-04-2019 11:26:20 - Message "2" : Success
25-04-2019 11:26:20 - #Titanium Sleep 1000: Running
25-04-2019 11:26:20 - Titanium Sleep 1000 : Success
25-04-2019 11:26:20 - If Result : False
25-04-2019 11:26:20 - Else Block Running
25-04-2019 11:26:20 - Message 2: Running
25-04-2019 11:26:20 - Message 2 : Success
25-04-2019 11:26:20 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:21 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:21 - Titanium Sleep 1000: Running
25-04-2019 11:26:22 - Titanium Sleep 1000 : Success
25-04-2019 11:26:22 - MathOperation 19 + 1 and save as incremento: Running
25-04-2019 11:26:22 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 20
25-04-2019 11:26:22 - MathOperation 19 + 1 and save as incremento : Success
25-04-2019 11:26:22 - Excel ReadCell from the worksheet WSName from the cell {20,2} and save its value as {valorCelda1}: Running
25-04-2019 11:26:22 - Se actualizo la variable : 
Var Name : valorCelda1
Value : 
25-04-2019 11:26:22 - Excel ReadCell from the worksheet WSName from the cell {20,2} and save its value as {valorCelda1} : Success
25-04-2019 11:26:22 - Excel ReadCell from the worksheet WSName from the cell {20,3} and save its value as {valorCelda2}: Running
25-04-2019 11:26:22 - Se actualizo la variable : 
Var Name : valorCelda2
Value : 9
25-04-2019 11:26:22 - Excel ReadCell from the worksheet WSName from the cell {20,3} and save its value as {valorCelda2} : Success
25-04-2019 11:26:22 - #Message "": Running
25-04-2019 11:26:22 - Message "" : Success
25-04-2019 11:26:22 - #Titanium Sleep 1000: Running
25-04-2019 11:26:22 - Titanium Sleep 1000 : Success
25-04-2019 11:26:22 - If Result : True
25-04-2019 11:26:22 - If Block Running
25-04-2019 11:26:22 - Message "Enviar_Mail": Running
25-04-2019 11:26:22 - Message "Enviar_Mail" : Success
25-04-2019 11:26:22 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:23 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:23 - Titanium Sleep 1000: Running
25-04-2019 11:26:24 - Titanium Sleep 1000 : Success
25-04-2019 11:26:24 - #Message "9": Running
25-04-2019 11:26:24 - Message "9" : Success
25-04-2019 11:26:24 - #Titanium Sleep 1000: Running
25-04-2019 11:26:24 - Titanium Sleep 1000 : Success
25-04-2019 11:26:24 - If Result : False
25-04-2019 11:26:24 - Else Block Running
25-04-2019 11:26:24 - Message 9: Running
25-04-2019 11:26:24 - Message 9 : Success
25-04-2019 11:26:25 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos": Running
25-04-2019 11:26:25 - SendMail with subject "Cotización Incompleta" to "victor.gamboa@hotmail.cl" with body "Cotización incompleta, favor llenar todos los campos" : Success
25-04-2019 11:26:25 - Titanium Sleep 1000: Running
25-04-2019 11:26:26 - Titanium Sleep 1000 : Success
25-04-2019 11:26:26 - MathOperation 20 + 1 and save as incremento: Running
25-04-2019 11:26:26 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 21
25-04-2019 11:26:26 - MathOperation 20 + 1 and save as incremento : Success
25-04-2019 11:26:27 - Execution ended
