### ISSUE TITLE
[TITAN][Exelium] Error al usar Write utilizando LastRow

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#190]
Buenas tardes

al usar la sentencia Write  en el row  se LastRow sale error.
Excel Write "<<<VarCount>>>" in shCopConRes row LastRow  and column 2
se elimino todos los rows para verificar si había algún dato vacio y se dejo solo el encabezado y aun así sale error.
pero al colocar numero del row funciona
Excel Write "<<<VarCount>>>" in shCopConRes row 2 and column 2.

se requiere que funcione con el LastRow ya que en el momento de hacer Write no se tiene el row exacto.

o si alguna forma de escribir una variable para este caso, por favor informar ya que se utilizo WriteVariableValue también sale error. no se si esto ocurre por que se había usado con anterioridad en una variable tipo List.

agradezco por la atención prestada y estaré atento a sus comentarios

**Comment by JuanISalazarM** [comment]
Seguro. Solicito de favor los archivos siguientes: El archivo Excel, script utilizado, y el log. Gracias, espero su respuesta.

**Comment by rrrios** [comment]
[Copia de Consolidado pendientes MARZO.xlsx](https://github.com/FridaSupport/TuringSuport/files/3267373/Copia.de.Consolidado.pendientes.MARZO.xlsx)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3267374/codigo.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3267376/log.txt)

**Comment by JuanISalazarM** [comment]
Muchas gracias. El error es el siguiente. La función Write, no soporta la opción de escribir en la última fila "LastRow".
Existe una función llamada GetSpecial, cuya función es obtener la última fila usada, y guarda ese valor en una variable que usted define. Le proporciono el enlace donde puede ver la documentación:

http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/GetSpecial

Acabo de realizar una prueba con el siguiente código:

`try`
`Excel LoadWBook "<<fileExcel>>" as BoExCopConPen`
`Excel LoadWSheet BoExCopConPen sheet_index 3 as shCopConRes`
`Excel Write "1" in shCopConRes row 2 and column 2`
`Excel GetSpecial lastRow from shCopConRes and save as LRow`
`Excel Write "1" in shCopConRes row <<<LRow>>> and column 2`
`Excel Save BoExCopConPen and close`
`catch`
`SystemNotify Type "Notification" with message "Error General clase"`
`end`

El valor que la función arroja es que la última fila usada es la 632. Esto se debe a que ya existían valores en la celda, y al momento de eliminarlos con la tecla (supr) se entiende que esa celda fue usada. Es necesario tomar precaución con esto.

![image](https://user-images.githubusercontent.com/50111840/59136192-9fe85e80-8947-11e9-93b5-95303017038c.png)

Si lo que desea es evitar que la ultima fila esté equivocada.
Recomendaría lo siguiente.
Seleccionar las filas:

![image](https://user-images.githubusercontent.com/50111840/59136509-1174dc80-8949-11e9-9653-7a7ec35b87e7.png)

Botón derecho y Delete, o eliminar la opción que aparezca en Excel. Espero resuelva el problema. Espero su respuesta.

**Comment by rrrios** [comment]
Buenos Dias

efectivamente como lo comentas este registrando en una celda x debido a las celdas vacías que tiene el excel. el inconveniente que se tiene es que el cliente tendría que realizar esta labor manualmente y se esta tratando de que el usuario realice las tareas manuales lo menos posible. ya además  hay Exceles que no se genera manualmente si no que los genera una herramienta de reporting y ante eso seria mas complicado controlar eso.

agradezco por la atención prestada y estaré atento a cualquier inquietud o sugerencia

**Comment by JuanISalazarM** [comment]
Buenos días. Existe una función llamada RemoveRows, que hace exactamente lo que se necesita. Eliminar las FILAS que no se necesiten. De esta forma podemos asegurar un LastRow correcto.
Le proporciono la documentación correspondiente:

http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/RemoveRows

Agradezco su atención. Espero su respuesta.

**Comment by gantonioid** [comment]
@rrrios esto no es un bug.

- El Excel de entrada para la automatización, lo genera un sistema o una persona?
- El UsedRange considera las celdas que tengan bordes, formato, etc. y **ese es el funcionamiento estándar de Excel.**
- Nosotros o FRIDA no podemos "adivinar" que ese UsedRange no es correcto para tu proceso específico, tendrías que hacer tú el script FRIDA (o uno custom) para limpiar el archivo previo a procesarlo.
- @JuanISalazarM te mencionó que puedes quitar esas líneas vacías con `RemoveRows`, pero existe igual `KeepRows `o `ApplyFilter and delete`

**Comment by rrrios** [comment]
@gantonioid 
nosotros lo que requerimos es simplemente que se habilite la opción de LastRow para esta sentencia, así como funciona para otras.

además atendiendo la sugerencia de @JuanISalazarM del RemoveRows, se esta probando y se esta mirando cual es la que mejor nos puede funcionar para este caso.

 por ultimo basado en la documentación en azure, en ningún lado esta especificado que no se puede realizar esta sentencia de esta forma o que no esta soportado..

**Comment by FaustinoLechuga** [comment]
Lo que se esta solicitando si se puede hacer pero eso queda como mejora y no como un issue debido a que no hay nada que este fallando.

Respondiendo a lo de la documentación, se especifica que funciones cuentan con esta característica en la sintaxis, si en la sintaxis o en los ejemplos no se presenta el caso que solicitas de LastRow o LastCol entonces esa función no tiene esa característica.

Se va a comenzar a realizar la mejora que solicitas.

**Comment by FaustinoLechuga** [comment]
Te acabo de liberar la versión 20190611T0808 que incluye el cambio que solicitaste, pido de favor que pruebes con este update.

Estos son algunos ejemplos que utilice:
```
Excel Write "Nombres" in Sheet1 row LastRow and column 5
Excel Write "Nombres" in Sheet1 row 6 and column LastCol
Excel Write "Nombres" in Sheet1 row LastRow and column LastCol
```

**Comment by rrrios** [comment]
Agradeciendo por el apoyo a la solicitud y las sugerencias dadas 

se obtuvo version y se probo y ya no se genera error.

**Comment by gantonioid** [comment]
Se aclara que no era error. El usuario intentaba usar la función con una sintaxis no soportada (LastRow)

Esto se atendió como mejora
