### ISSUE TITLE
[TITAN] Excelium - ReadCell

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#191]
La instruccion ReadCell no guarda la coma decimal.

![issueComaDecimal](https://user-images.githubusercontent.com/33100638/59121334-34de5e00-892e-11e9-8411-e71de2acf602.png)

Log:
6/7/2019 1:13:29 PM - Excel ReadCell from the worksheet miHoja from the cell {80,7} and save its value as {CUENTA6}: Running
6/7/2019 1:13:29 PM - Se agrego una nueva variable : 
Var Name : CUENTA6
Value : 12121

Necesidad: Urgente.

**Comment by JuanISalazarM** [comment]
Seguro, en cuanto tengamos la solución le comunicamos inmediatamente.

**Comment by JuanISalazarM** [comment]
Se le ha actualizado Turing.
Se ha creado una nueva función para resolver la problemática. Solicito de favor ingresar la siguiente línea para llevar a cabo una prueba:

`ReadCellText from the worksheet {miHoja} from the cell {80,7} and save its value as {CUENTA6}`

Gracias por su atención. Espero su respuesta.

**Comment by ClaudioRodolfoGarcete** [comment]
Se soluciono el problema del issue pero abriste otro que estaba cerrado.

ReadColumn trae nulls:

6/7/2019 4:06:44 PM - Excel ReadColumn from the worksheet excelLecturaMiHoja with the column index {1} and save its value as {cuentaLista}: Running
6/7/2019 4:06:44 PM - Se agrego una nueva variable : 
Var Name : cuentaLista
Value : CSC-IF - Cuadratura Locales Interfase Histórica - CTA_CPT ;  ; Empresa: ; CRUZ VERDE ; Cuenta ; 111040034 ; 111040310 ; 111040312 ; 111040314 ; 111040324 ; 111040325 ; 111040331 ; 111040334 ; 211040028 ; 211040076 ; 211040319 ; 211060311
6/7/2019 4:06:44 PM - Excel ReadColumn from the worksheet excelLecturaMiHoja with the column index {1} and save its value as {cuentaLista} : Success
6/7/2019 4:06:44 PM - Excel ReadColumn from the worksheet excelLecturaMiHoja with the column index {4} and save its value as {descripcionColumnaLista} with nulls: Running
6/7/2019 4:06:44 PM - Se agrego una nueva variable : 
Var Name : descripcionColumnaLista

**Comment by Johhnn117** [comment]
Si, en un momento actualizamos la versión que lo corrige

**Comment by Johhnn117** [comment]
puedes revisar que tengas la varsión 20190607T0743

**Comment by ClaudioRodolfoGarcete** [comment]
Perfecto, solucionado.
