### ISSUE TITLE
Consulta Excell ReadRows

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#192]
Al momento de obtener fechas de un archivo excel, estas vienen con formato 

03.01.2019
o
13Feb02

Que luego son transformadas con un powershell al formato deseado dd/MM/yyyy o dd.MM.yyyy. Pero al momento de compararlas mas adelante en el script, estas fechas llegan invertidas MM/dd/yyyy.

**¿Cuando se levantan las fechas del excel, toman el formato por defecto de la maquina en donde esta corriendo el proceso, la configuracion del usuario, la configuracion del excel o cual configuracion?** Ya que esto solo sucede con las fechas que son levantadas de excel descardados. Si es un excel armado por mi no presento este problema. Se probó guardando las fechas en un excel propio y levantandolas de este.

Adjunto les dejo los archivos necesarios

[archivos.zip](https://github.com/FridaSupport/TuringSuport/files/3267177/archivos.zip)

Necesidad: Urgente

**Comment by Johhnn117** [comment]
Tuve una llamada con Juan, estamos buscando una solución.

**Comment by jaristimuno** [comment]
Hola. Como va la solucion de esto?

**Comment by pabloreitanosofttek** [comment]
@Johhnn117  ¿Cuándo estará? @FridaSupport  ¡gracias!

**Comment by Johhnn117** [comment]
Sigo trabajando en el ticket, en cuanto encuentre la solución les informo

**Comment by pabloreitanosofttek** [comment]
@Johhnn117  necesitamos una fecha aproximada de resolución... @gantonioid porfa apoyo. 

¡Gracias!

**Comment by gantonioid** [comment]
en #197, están intentando la **buena idea** de usar WriteFormula para convertir fechas a texto.

**Comment by pabloreitanosofttek** [comment]
¿Y eso que quiere decir? ¿Que si se resuelve el #197  se resuelven los 2?

**Comment by Johhnn117** [comment]
Se esperan correciones por parte de @jaristimuno

**Comment by gantonioid** [comment]
Varios días sin comentarios del usuario, cierro el issue.
