### ISSUE TITLE
[Consulta]Urgente - Listener de Turing ejecuta un proceso mas de una vez

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#193]
Estoy trabajando en la creación de una cotización en SAP, el flujo es el siguiente:

1. Correo soporte.clientes@finning.com recibe un correo con un archivo adjunto (Excel). Esta lectura la estoy haciendo con MS Flow.

2. Flow deja el archivo adjunto en una carpeta y el bots se dispara

3. Crea la cotización en SAP y la envía de vuelta al cliente que solicito la cotización

Cuando turing esta en modo ListenerWindows, llega un mail, y se ejecuta el bots, pero se ejecuta mínimo 3 veces mas y se hace el envío de correo a otros destinatarios que anteriormente se hicieron pruebas, ahí esta el error, solo se debería ejecutar 1 vez por correo en la bandeja de entrada, agradeceria si podemos ver el problema con mayor profundidad, gracias.

**Comment by gantonioid** [comment]
Se ejecuta varias veces porque quedan pendientes en la cola. Probablemente alguna ejecución falló y se queda en cola, cuando vuelves a poner turing en modo listener llegan las que están pendientes.

**Comment by gantonioid** [comment]
Si me das el Action que estás usando con el API, reviso la cola.

**Comment by victorgamboa** [comment]
Buen día,
Action: "sofia1072851774",

**Comment by gantonioid** [comment]
### Ejecuciones múltiples
Había dos ejecuciones en cola, que fueron generadas el 6 de junio. Es por eso que al abrir Turing en modo Listener, se ejecutaban automáticamente.

Limpié la cola de pendientes para el proceso indicado. Por favor considera usar las otras APIs disponibles, si es que lo ves oportuno. Tú puedes revisar el estatus de ejecución de un llamado remoto y también podrías borrar los pendientes (lo que yo hice). Checa la documentación para aplicarlas.
[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Remoto%20y%20Scheduling.one%7C21c7d51f-bc2f-4d07-9e52-ba06e3cee982%2FAPIs%20de%20FRIDA%20ejecuci%C3%B3n%20remota%7Cbf4b6ca9-a4a1-4726-94e0-22941d7d032f%2F%29&wdorigin=703](url)

### Se hace el envío de correos a otros destinatarios
Tienes evidencias de lo que mencionas? no podría ser el mismo punto anterior (ejecuciones múltiples)? qué material me puedes dar para rastrear tu problema?

**Comment by victorgamboa** [comment]
Yo creo que el envío a otros destinatarios se debe al caso anterior, donde se ejecutan los procesos que quedaron pendientes, la única evidencia de eso, son los correos de la bandeja de enviados,

**Comment by gantonioid** [comment]
Entonces prueba ahora que borré las ejecuciones pendientes. Ve el API de _ClearExecutionQueue_ documentada en ese link que pasé en mi respuesta anterior. Ojalá te ayude. Mantendré el ticket en suspendido unos días mientras lo revisas y nos comentas.

**Comment by victorgamboa** [comment]
Dale muchas gracias

**Comment by pablorlmx** [comment]
Estimado @gantonioid hemos detectado que el flujo tarda varios minutos (2 minutos promedio) entre que se recibe un correo y se ejecuta el BOT de FRIDA. Esto se puede configurar?

Sin la intervención de FRIDA el flujo de flow es instantaneo

**Comment by gantonioid** [comment]
FLOW es independiente de FRIDA... y lo único que se hace es llamar a un API. No tenemos control de cuánto tarde el flow en ejecutar, la llamada al API es sencilla y rápida.

**Comment by pablorlmx** [comment]
Estimado @gantonioid gracias por la respuesta. FLOW se activa de inmediato, el problema radica entre que FLOW hace el llamado REST a FRIDA y se activa el BOT en el servidor cliente. Lo que necesitamos entender es si todo se dispara de inmediato o si al entrar en cola de ejecución hace que demore algunos minutos.

**Comment by gantonioid** [comment]
Entra a cola de ejecución, el llamado al API pone en cola de ejecución el proceso deseado. Es normal que demore, pero únicamente unos seg.

**Comment by pablorlmx** [comment]
Gracias @gantonioid. Ves posible juntarte con @victorgamboa y revisar su implementación. Yo lo estuve viendo con él y vimos que tardaba más de 2 minutos, probando aisladamente Flow tardaba un par de segundos.

**Comment by gantonioid** [comment]
@pablorlmx 
Ya lo vi con Víctor. Quedó claro en la llamada y con la explicación que el inconveniente se está presentando **EN FLOW** es decir... Microsoft no procesa inmediatamente los correos con el Flow que tiene Víctor. En cuanto Microsoft lo procesa, vimos que el llamado se hace inmediatamente en FRIDA.

En cuanto a eso, el tema queda cerrado.

Ahora, me dicen que propusiste de solución usar Softron. Esto es **UNA IDEA EQUIVOCADA**. Softron no es la respuesta porque se trata de un add-in de Office, y como tal, requiere a una persona utilizando el Outlook, monitoreando los correos electrónicos. Si se hace como propones (Softron), el tiempo de respuesta será mayor. Flow lo que hace es precisamente permitirnos generar los llamados a un proceso automatizado de manera autónoma, **desatendida**.

@pabloreitanosofttek, probablemente habrá que tomar medidas para mitigar esta equivocada decisión de venta

**Comment by victorgamboa** [comment]
@gantonioid 
Consulta, están bien esos parámetros? me da error 404
Podrías colaborarme,

![Postman](https://user-images.githubusercontent.com/49756748/59522447-ba1cc200-8e9c-11e9-8755-40fce197e4d3.PNG)
