### ISSUE TITLE
[TITAN] Excelium - ReadColumn

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#194]
Instruccion: ReadColumn

Problema: no lee los decimales numericos.

![ERRORTURINGREADCOLUM](https://user-images.githubusercontent.com/33100638/59134268-e8f0e080-8950-11e9-866d-8b15ba50aac6.png)

Log:

6/7/2019 6:17:14 PM -  : Success
6/7/2019 6:17:14 PM - Excel ReadColumn from the worksheet miHojaExcelGenerado with the column index {3} and save its value as {saldoExcelGenerado}: Running
6/7/2019 6:17:14 PM - Se agrego una nueva variable : 
Var Name : saldoExcelGenerado
**Value : Saldo ; 0 ; 0 ; 0 ; 0 ; 0 ; 12121 ; 0 ; 0 ; 0 ; 0 ; -10921 ; 0**

Necesidad: Urgente.

**Comment by gantonioid** [comment]
Qué te hace pensar eso? Tal parece que en ese screenshot no hay decimales. Puede estarse usando la coma para el separador de miles. Revisa por favor la configuración del Excel y comenta más detalles por favor.

Si el archivo no tiene info sensible por favor compártela por aquí o pon el link de Teams

**Comment by ClaudioRodolfoGarcete** [comment]
Tenes razon @gantonioid es una configuracion del excel, desestimar el issue.
