### ISSUE TITLE
[TITAN] [Pregunta] ejecucion de procesos anidados

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#195]
Queria consutarles si es posible que al finalizar un proceso llamese "A" este puede inidcarle a un proceso "B" que comience su ejecucion?
De esta forma cada vez que finalice el proceso A, el proceso B comenzaria a ejecutarse.

es viable algo asi?

**Comment by gantonioid** [comment]
es posible, pero no de manera offline.
Por qué lo harías así? el script de B puede estar como segunda parte de tu archivo del script A, no?

**Comment by JuanIgnacioBurgos** [comment]
Ocurre que temenos dos procesos que por separado se ejecutan de forma correcta, cuando intentamos ejecutarlos a ambos en un unico Script las ventanas emergentes de excel no se omitian y requerian de confirmacion manual para que el bot se siguiera ejecutando, ventanas como la siguiente:

![save](https://user-images.githubusercontent.com/49756974/59219340-9e61a500-8b98-11e9-93c3-8f7d2dbd13e2.jpg)

quizas esto se este dando porque uno de los procesos utiliza Titanium, aunque no estoy muy Seguro de que sea esto la causa.

De todas formas en la VM del cliente temenos una version de Turing offline, por lo que no serviria la alternativa pensada.

**Comment by gantonioid** [comment]
Y esa alerta por qué sale? Los cambios se guardan con SaveWB, la usas? o qué estás haciendo?

**Comment by JuanIgnacioBurgos** [comment]
Si, utilizo la instruccion de Excel Save WB, de hecho cuando corro ese script por separado no tengo problemas con estas ventanas, al juntarlo con el segundo script es cuando estas ventanas empiezan a dar problemas.

**Comment by gantonioid** [comment]
> Y esa alerta por qué sale? Los cambios se guardan con SaveWB, la usas? o qué estás haciendo?

Puedes dar más información sobre lo que necesitas en tu script? (Descripción del proceso a alto nivel)

Ese libro se llama Libro1? O es un libro que acabas de crear? Ya existe?

Hasta el momento no tengo lo suficiente para  ayudarte

**Comment by pablorlmx** [comment]
@gantonioid podrías tener una call con @JuanIgnacioBurgos y te muestren? creo que es mejor que iterar por acá solamente dado que el error es bastante raro.

**Comment by gantonioid** [comment]
@FaustinoLechuga nos ayudas a investigar porfa?

**Comment by FaustinoLechuga** [comment]
Si, estaré revisando

**Comment by CesarEmanuelLencina** [comment]
¿Hay alguna novedad con esto?

+@FridaSupport +@raulpoltiSTK

**Comment by pablorlmx** [comment]
Estimados, pudieron ver esto? Llevamos varios días sin respuesta.
+ @RickProductivity  y @pabloreitanosofttek

**Comment by pabloreitanosofttek** [comment]
Necesitamos conocer la fecha de resolución de este ticket... @gantonioid @FaustinoLechuga ¿Cuándo será? ¿Necesitan algo de @JuanIgnacioBurgos @CesarEmanuelLencina ? De ser así pídanlo... si no se entiende del todo el pedido, a las 12hs ARG es un buen momento de charla. 

¡Gracias! 
Slds,

**Comment by FaustinoLechuga** [comment]
El dia de ayer me puse en contacto con @JuanIgnacioBurgos para ver este tema, por el momento la única solución inmediata es utilizar titanium para darle click en ok cuando la ventana aparezca.

**Comment by JuanIgnacioBurgos** [comment]
Buenas, el dia de hoy tuvimos una call con Faustino, se visualizo la problematica, tambien se compartieron los scripts y los archivos para su analisis.

Quedamos atentos. Slds

**Comment by pabloreitanosofttek** [comment]
Gracias! Esperamos pronto la respuesta .


Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: JuanIgnacioBurgos <notifications@github.com>
Enviado: martes, junio 18, 2019 3:50 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [TITAN] [Pregunta] ejecucion de procesos anidados (#195)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Buenas, el dia de hoy tuvimos una call con Faustino, se visualizo la problematica, tambien se compartieron los scripts y los archivos para su analisis.

Quedamos atentos. Slds

**Comment by pabloreitanosofttek** [comment]
Buen día, porfa @FaustinoLechuga  comentar la estimación así podemos gestionar de cara a cliente. 
¡gracias!

**Comment by FaustinoLechuga** [comment]
Hola buen dia, se estan haciendo pruebas con diferentes metodo para solucionar esta problematica, por el momento estoy en espera de los resultados de una de estas pruebas por lo que no podría estimar la resolución de esto.

**Comment by CesarEmanuelLencina** [comment]
@FaustinoLechuga Hemos probado la solución que nos proporcionaste y si bien se resolvió el problema de las ventanas desplegables, ahora mi proceso falla al momento de ejecutar una macro dentro de un excel.

Dentro del siguiente zip encontrarás los archivos necesarios, el log que muestra el error y el código que se ejecutó en Turing: [Archivos ETV3.zip](https://github.com/FridaSupport/TuringSuport/files/3315798/Archivos.ETV3.zip)

Si necesitás algo más o si me olvidé de algún archivo no dudes en contactarme.

**Comment by JuanIgnacioBurgos** [comment]
identificamos que la parte del script que compartio Cesar es la que esta dando problemas, el resto del script esta corriendo de forma correcta, incluso se estan ejecutando otras macros sin problemas.

**Comment by FaustinoLechuga** [comment]
Estare revisando los archivos para ver por que les falla con esa macro

**Comment by FaustinoLechuga** [comment]
Error in : RunMacro "ADI" InBook LibroMacro
21-06-2019 15:14:35 - Exception : No se puede ejecutar la macro "ADI". Puede que la macro no esté disponible en este libro o que se hayan deshabilitado todas las macros.
21-06-2019 15:14:35 - Error in : RunMacro "ADI" InBook LibroMacro

Este es el error que marca el log y revisando la macro me percate que no hay ninguna macro en este documento. Podrian revisar el archivo de excel que debe contener la macro?

**Comment by CesarEmanuelLencina** [comment]
El archivo MacroParcial15.xlsm tiene dos botones que ejecutan las correspondientes macros siendo el que dice ADI el que me interesa.

![imagen](https://user-images.githubusercontent.com/50213758/60017653-ad982680-965f-11e9-8339-9201b86af8ac.png)

Supongo que este debe ser el código de la macro.

![imagen](https://user-images.githubusercontent.com/50213758/60018380-8e01fd80-9661-11e9-98b2-04b7a37cd858.png)

Siempre llamé a la macro de manera local con el comando `Excel RunMacro "ADI" InBook LibroMacro` y no he tenido problemas.

Cualquier cosa hacemos una call.

**Comment by gantonioid** [comment]
En #32 menciono algo similar... puedes ponerle public a esa macro y volver a intentar? Debería quedar así:

`public sub ADI()`

**Comment by CesarEmanuelLencina** [comment]
Lo acabo de probar y el error es exactamente el mismo.

**Comment by pabloreitanosofttek** [comment]
@FaustinoLechuga  @gantonioid  seguimos con el issue abierto... ¡porfa apoyo! 

¡gracias!

**Comment by FaustinoLechuga** [comment]
Estoy en contacto con Juan y con Cesar ya se resolvió la primer problemática pero han surgido otras que se están resolviendo,

**Comment by pabloreitanosofttek** [comment]
OK, gracias... porfa comentar como viene.

**Comment by FaustinoLechuga** [comment]
Se resolvió un problema al correr una macro. Falta que se implementes los procesos y verificar que todo funcione correctamente.

**Comment by CesarEmanuelLencina** [comment]
En el día de hoy juntamos los scripts y lamentablemente el problema de las ventanas emergentes continua. Se podría decir que estamos como al principio. @FaustinoLechuga cuando estés disponible lo vemos en conjunto con Juan en una call.

**Comment by JuanIgnacioBurgos** [comment]
Buenas tardes, realizamos otra call junto con Cesar y Faustino, se pudo destrabar el inconveniente mediante la siguiente instruccion `Excel TurnHeadlessTo true` al comenzar el segundo Script, con esta instruccion los excel corren en back y no aparecen las ventanas Emergenetes.

Gracias @FaustinoLechuga por la ayuda!!
Cualquier cosa les avisamos. Por ahora se cierra el issue.
Saludos.
