### ISSUE TITLE
[TITAN] No funciona CopyPaste

### ISSUE THREAD

**Issue by CristianCelano** [FridaSupport/TuringSuport#196]
Intento copiar un rango en una hoja de un libro para pegarlo en otra hoja de otro libro y no funciona la instruccion CopyPaste

Codigo:
```
Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1
Excel LoadWSheet book1 sheet "abril" as hoja1
Excel LoadWBook "C:\Users\cristian.celano\Desktop\FalsaCartola.xlsx" as BCartola
Excel LoadWSheet BCartola sheet_index 1 as HCartola
Excel WriteFormula HCartola in L2 formula =SUBTOTAL(3,C:C)
Excel GetCellValue from the worksheet HCartola in column {12} and row {2} and save as length
Excel WriteFormula hoja1 in O1 formula =SUBTOTAL(3,B:B)
Excel GetCellValue from the worksheet hoja1 in column {15} and row {1} and save as length2
Excel MultiFilter from HCartola in_column_index 3 with_criteria [PAGO RECIBIDO TBK TARJETA DE CREDITO, PAGO RECIBIDO TBK TARJETA DE DEBITO]
MathOperation <<<length2>>> + 1 and save as length3
Excel CopyPaste HCartola A2:H<<<length>>> to hoja1 B<<<length3>>>
Titanium Sleep 6000
Excel Save BCartola and close

```
LOG:
6/10/2019 3:17:51 PM - Proces ID :1053608489
6/10/2019 3:17:51 PM - Execution started
6/10/2019 3:17:51 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1: Running
6/10/2019 3:17:52 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1 : Success
6/10/2019 3:17:52 PM - Excel LoadWSheet book1 sheet "abril" as hoja1: Running
6/10/2019 3:17:52 PM - Excel LoadWSheet book1 sheet "abril" as hoja1 : Success
6/10/2019 3:17:52 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\FalsaCartola.xlsx" as BCartola: Running
6/10/2019 3:17:53 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\FalsaCartola.xlsx" as BCartola : Success
6/10/2019 3:17:53 PM - Excel LoadWSheet BCartola sheet_index 1 as HCartola: Running
6/10/2019 3:17:53 PM - Excel LoadWSheet BCartola sheet_index 1 as HCartola : Success
6/10/2019 3:17:53 PM - Excel WriteFormula HCartola in L2 formula =SUBTOTAL(3,C:C): Running
6/10/2019 3:17:53 PM - Excel WriteFormula HCartola in L2 formula =SUBTOTAL(3,C:C) : Success
6/10/2019 3:17:53 PM - Excel GetCellValue from the worksheet HCartola in column {12} and row {2} and save as length: Running
6/10/2019 3:17:53 PM - Excel GetCellValue from the worksheet HCartola in column {12} and row {2} and save as length : Success
6/10/2019 3:17:53 PM - Excel WriteFormula hoja1 in O1 formula =SUBTOTAL(3,B:B): Running
6/10/2019 3:17:53 PM - Excel WriteFormula hoja1 in O1 formula =SUBTOTAL(3,B:B) : Success
6/10/2019 3:17:53 PM - Excel GetCellValue from the worksheet hoja1 in column {15} and row {1} and save as length2: Running
6/10/2019 3:17:53 PM - Excel GetCellValue from the worksheet hoja1 in column {15} and row {1} and save as length2 : Success
6/10/2019 3:17:53 PM - Excel MultiFilter from HCartola in_column_index 3 with_criteria [PAGO RECIBIDO TBK TARJETA DE CREDITO, PAGO RECIBIDO TBK TARJETA DE DEBITO]: Running
6/10/2019 3:17:53 PM - Excel MultiFilter from HCartola in_column_index 3 with_criteria [PAGO RECIBIDO TBK TARJETA DE CREDITO, PAGO RECIBIDO TBK TARJETA DE DEBITO] : Success
6/10/2019 3:17:53 PM - MathOperation 13 + 1 and save as length3: Running
6/10/2019 3:17:53 PM - MixReader : Se agrego una nueva variable : 
Var Name : length3
Value : 14
6/10/2019 3:17:53 PM - MathOperation 13 + 1 and save as length3 : Success
6/10/2019 3:17:53 PM - Excel CopyPaste HCartola A2:H19 to hoja1 B14: Running
6/10/2019 3:17:53 PM - Error: CopyPaste HCartola A2:H19 to hoja1 B14
6/10/2019 3:17:53 PM - Error in copypaste Instruction was't found
6/10/2019 3:17:53 PM - Error in copypaste Instruction was't found
6/10/2019 3:17:53 PM - Excel CopyPaste HCartola A2:H19 to hoja1 B14 : Error
6/10/2019 3:17:54 PM - Execution ended

Muchas Gracias.

**Comment by FaustinoLechuga** [comment]
Al parecer la version que tienes actualmente no cuenta con ese cambio, te hice un update 20190610T0725 que ya cuenta con esta instruccion. Prueba si con esto se resuelve tu problematica.

Quedo al pendiente.

**Comment by CristianCelano** [comment]
Sigue fallando

log:
6/10/2019 4:40:45 PM - Proces ID :1053608489
6/10/2019 4:40:45 PM - Execution started
6/10/2019 4:40:45 PM - ### Registro de pago TBK: Running
6/10/2019 4:40:45 PM - Registro de pago TBK : Success
6/10/2019 4:40:45 PM - ### TRY general: Running
6/10/2019 4:40:45 PM - TRY general : Success
6/10/2019 4:40:45 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1: Running
6/10/2019 4:40:46 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\libro1.xlsx" as book1 : Success
6/10/2019 4:40:46 PM - Excel LoadWSheet book1 sheet "abril" as hoja1: Running
6/10/2019 4:40:47 PM - Excel LoadWSheet book1 sheet "abril" as hoja1 : Success
6/10/2019 4:40:47 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\FalsaCartola.xlsx" as BCartola: Running
6/10/2019 4:40:47 PM - Excel LoadWBook "C:\Users\cristian.celano\Desktop\FalsaCartola.xlsx" as BCartola : Success
6/10/2019 4:40:47 PM - Excel LoadWSheet BCartola sheet_index 1 as HCartola: Running
6/10/2019 4:40:47 PM - Excel LoadWSheet BCartola sheet_index 1 as HCartola : Success
6/10/2019 4:40:47 PM - Excel WriteFormula HCartola in L2 formula =SUBTOTAL(3,C:C): Running
6/10/2019 4:40:47 PM - Excel WriteFormula HCartola in L2 formula =SUBTOTAL(3,C:C) : Success
6/10/2019 4:40:47 PM - Excel GetCellValue from the worksheet HCartola in column {12} and row {2} and save as length: Running
6/10/2019 4:40:47 PM - Excel GetCellValue from the worksheet HCartola in column {12} and row {2} and save as length : Success
6/10/2019 4:40:47 PM - Excel WriteFormula hoja1 in O1 formula =SUBTOTAL(3,B:B): Running
6/10/2019 4:40:47 PM - Excel WriteFormula hoja1 in O1 formula =SUBTOTAL(3,B:B) : Success
6/10/2019 4:40:47 PM - Excel GetCellValue from the worksheet hoja1 in column {15} and row {1} and save as length2: Running
6/10/2019 4:40:47 PM - Excel GetCellValue from the worksheet hoja1 in column {15} and row {1} and save as length2 : Success
6/10/2019 4:40:47 PM - Excel MultiFilter from HCartola in_column_index 3 with_criteria [PAGO RECIBIDO TBK TARJETA DE CREDITO, PAGO RECIBIDO TBK TARJETA DE DEBITO]: Running
6/10/2019 4:40:47 PM - Excel MultiFilter from HCartola in_column_index 3 with_criteria [PAGO RECIBIDO TBK TARJETA DE CREDITO, PAGO RECIBIDO TBK TARJETA DE DEBITO] : Success
6/10/2019 4:40:47 PM - MathOperation 13 + 1 and save as length3: Running
6/10/2019 4:40:47 PM - MixReader : Se agrego una nueva variable : 
Var Name : length3
Value : 14
6/10/2019 4:40:47 PM - MathOperation 13 + 1 and save as length3 : Success
**6/10/2019 4:40:47 PM - Excel CopyPaste HCartola A2:H19 to hoja1 B14: Running
6/10/2019 4:40:47 PM - Error: CopyPaste HCartola A2:H19 to hoja1 B14
6/10/2019 4:40:47 PM - Error in copypaste Instruction was't found
6/10/2019 4:40:47 PM - Error in copypaste Instruction was't found
6/10/2019 4:40:47 PM - Excel CopyPaste HCartola A2:H19 to hoja1 B14 : Error**
6/10/2019 4:40:47 PM - Message Fallo Excel: Running
6/10/2019 4:40:47 PM - Message Fallo Excel : Success
6/10/2019 4:40:47 PM - ###Final de TRY general: Running
6/10/2019 4:40:47 PM - Final de TRY general : Success
6/10/2019 4:40:48 PM - Execution ended

**Comment by FaustinoLechuga** [comment]
Me podras compartir la version de frida con la que cuentas?
