### ISSUE TITLE
Consulta Excel WriteFormula

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#197]
Al momento de intentar escribir la siguiente instrucción: WriteFormula HojaF in B2:LastRow formula =TEXT(B:B; "dd/MM/yyyy")

Intenté colocando TEXTO en vez de TEXT, por si era un tema del lenguaje de excel, cuando se coloca TEXTO, este escribe directamente la formula en la celda, no la esta aplicando como tal y por ende pisa los valores que tenia anteriormente. Adjunto el log, el error, el script y el archivo 

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3276339/log.txt)
[ERROR.txt](https://github.com/FridaSupport/TuringSuport/files/3276341/ERROR.txt)
[archivofinal.xlsx](https://github.com/FridaSupport/TuringSuport/files/3276342/archivofinal.xlsx)
[scp.txt](https://github.com/FridaSupport/TuringSuport/files/3276348/scp.txt)

Prioridad: Alta
Necesidad: Urgente

**Comment by gantonioid** [comment]
@jaristimuno 

1. Las fórmulas se ponen en inglés y el separador de parámetros es una coma, no punto y coma
2. Tú mismo estás reemplazando los valores del libro, no es la fórmula, ni FRIDA... Esto porque escribes la fórmula en la columna B (ahí están tus datos, así que se sobre-escriben)
3. Lo que tendrías que hacer sería poner la instrucción : `Excel WriteFormula HojaF in C2:LastRow formula =TEXT(B:B, "dd/MM/yyyy")` para que la fórmula se escriba en la columna C y así no se pierda información (luego puedes copiar valores o lo que sea)
![image](https://user-images.githubusercontent.com/9600868/59275368-cf39ec80-8c21-11e9-9bdc-70371d6b507a.png)

**Comment by jaristimuno** [comment]
Consulta Frida, manejo de excel. ¿Que cultura, region e idioma usa FRIDA o el lector de los excel al momento de levantar uno? Ya que me indican que el separador de las formulas puede ser tanto la coma, el punto y coma, o cualquier otro

**Comment by gantonioid** [comment]
Todo hemos visto que es dependiendo de tu configuración local. A excepción de WriteFormula. Tienen que ser en inglés y usando las comas como separador de parámetros.

**Comment by pabloreitanosofttek** [comment]
Eso quiere decir que si está en ESPAÑOL ARGENTINA va a tomar lo mismo que la máquina de quien está desarrollando con esa configuración? ¡gracias!

**Comment by gantonioid** [comment]
Significa que Excel se comporta un poco diferente según el idioma y cultura configurados en la máquina que ejecuta el script.

**Comment by gantonioid** [comment]
@jaristimuno pudiste probar lo que te compartí? Lograste que funcione tu WriteFormula ??

**Comment by jaristimuno** [comment]
Probé lo que sugeriste, pero solo funcionaba a la primera corrida, en las corridas siguientes, escribia la formula como tal

**Comment by gantonioid** [comment]
Bien, funcionó... sólo entonces córrelo con un archivo nuevo cada vez, no sobre el mismo ya procesado.

**Comment by jaristimuno** [comment]
En este caso no se puede hacer eso que sugieres, ya que es un solo excel con el que se trabaja. Sigo buscando soluciones

**Comment by pabloreitanosofttek** [comment]
Que otra opción hay Toño? La
Regla de negocio es como dice JesusDavid.

Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: jaristimuno <notifications@github.com>
Enviado: martes, junio 11, 2019 6:15 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] Consulta Excel WriteFormula (#197)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


En este caso no se puede hacer eso que sugieres, ya que es un solo excel con el que se trabaja. Sigo buscando soluciones

**Comment by gantonioid** [comment]
Les comparto un script que usa WriteFormula combinado con TextFormat y CopyColumn. Lo ejecuté varias veces, en cada una agregando filas al Excel y se hace correctamente.
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\archivofinal.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as HojaF
Excel WriteFormula HojaF in C2:LastRow formula =TEXT(B:B, "dd/MM/yyyy")
SystemNotify Type "Notification" with message "Breakpoint"
Excel TextFormat in HojaF in column 2
Excel CopyColumn value 3 from HojaF start_at 2 to the sheet HojaF in column 2 start_at 2
SystemNotify Type "Notification" with message "Breakpoint"
Excel Save libro
```

**Comment by gantonioid** [comment]
Esto te funciona? puedes probar?

**Comment by pabloreitanosofttek** [comment]
Probarlo xfa Jesus ... es importante.
Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: gantonioid <notifications@github.com>
Enviado: miércoles, junio 12, 2019 11:33 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] Consulta Excel WriteFormula (#197)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Esto te funciona? puedes probar?

**Comment by gantonioid** [comment]
Varios días sin respuesta, cierro el issue

**Comment by pabloreitanosofttek** [comment]
Son 2 días e interactuaste conmigo... busquemos un acuerdo... 3 días con 3 strikes... si no hay respuesta, vale cerrarlo... te parece @gantonioid ? 

¡Gracias!

**Comment by gantonioid** [comment]
Que Jesús pruebe, nos comente y reabrimos sin problema.

**Comment by pabloreitanosofttek** [comment]
OK, está de baja médica y puede tardar unos dias…
