### ISSUE TITLE
No se envía el Body en un correo 

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#198]
No se envía el body configurado en un mail a un destinatario x
@eradgg lo esta revisando, si necesitas mas detalles me avisas, gracias

**Comment by eradgg** [comment]
Ya lo estoy revisando.

**Comment by gantonioid** [comment]
Qué instrucción están usando?

**Comment by eradgg** [comment]
Es la instrucción que creé para Impac. Hab[ia un problema con el HTML. lo simplifiqué.
Así debería de funcionar:
DefineVariable type "string" as "BoClientesMail" with the value "<body lang=ES-MX style='tab-interval:.5in'><div><p>Hola, estos son los archivos.</p><p>Gracias</p></div></body>"
SendEmailAttachements BoClientesMail To "<<<RemitenteMail>>>" Subject "Cotización <<<NumeroCotizacion>>>" Attachements "Cotización <<<NumeroCotizacion>>>.pdf" Path "C:\Users\soporte.clientes\Documents"

**Comment by victorgamboa** [comment]
Muchas gracias Eder, una vez mas...me funciono ok
