### ISSUE TITLE
[TITAN] Tablas dinamicas excel: CachePivotTable - CreatePivotTable.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#199]
Se necesita realizar una tabla dinamica pero hay un error en la instruccion CreatePivotTable que lo impide.

El rango de datos que se desea tomar es desde  A1 hasta I12.

Se desea llevarlo a la hoja "Hoja2"

![excel1](https://user-images.githubusercontent.com/33100638/59305616-f8359e00-8c70-11e9-8f2f-3e4e9e34a7dd.png)

![excel2](https://user-images.githubusercontent.com/33100638/59305709-2ca95a00-8c71-11e9-9ddb-ce89b9ad5c30.png)

Instruccion FRIDA:
DefineVariable type "string" as "excelOBIEExCTA" with the value "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03.xlsx"
Excel LoadWBook "<<<excelOBIEExCTA>>>" as miLibroOBIEE
Excel LoadWSheet miLibroOBIEE sheet "Sheet1" as miHojaOBIEE
Excel LoadWSheet miLibroOBIEE sheet "Hoja2" as miHojaOBIEE2
Excel CachePivotTable miLibroOBIEE in miHojaOBIEE from A1 to I12 as CachePT1
## ESTO FALLA
Excel CreatePivotTable CachePT1 in miHojaOBIEE2 cell A2 with_name "a" as PivotTable
Excel TableField Row from PivotTable fname "Local" as PivotFieldRow1
Excel TableField Value from PivotTable fname "Saldo" as PivotFieldValue1
Titanium Sleep = 3000
Excel Save miLibroOBIEE

Log:

6/11/2019 5:50:28 PM - Proces ID :1146059059
6/11/2019 5:50:28 PM - Execution started
6/11/2019 5:50:28 PM - DefineVariable type "string" as "excelOBIEExCTA" with the value "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03.xlsx": Running
6/11/2019 5:50:28 PM - MixReader : Se agrego una nueva variable : 
Var Name : excelOBIEExCTA
Value : C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03.xlsx
6/11/2019 5:50:28 PM - DefineVariable type "string" as "excelOBIEExCTA" with the value "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03.xlsx" : Success
6/11/2019 5:50:28 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03.xlsx" as miLibroOBIEE: Running
6/11/2019 5:50:30 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03.xlsx" as miLibroOBIEE : Success
6/11/2019 5:50:30 PM - Excel LoadWSheet miLibroOBIEE sheet "Sheet1" as miHojaOBIEE: Running
6/11/2019 5:50:30 PM - Excel LoadWSheet miLibroOBIEE sheet "Sheet1" as miHojaOBIEE : Success
6/11/2019 5:50:30 PM - Excel LoadWSheet miLibroOBIEE sheet "Hoja2" as miHojaOBIEE2: Running
6/11/2019 5:50:30 PM - Excel LoadWSheet miLibroOBIEE sheet "Hoja2" as miHojaOBIEE2 : Success
6/11/2019 5:50:30 PM - Excel CachePivotTable miLibroOBIEE in miHojaOBIEE from A1 to I12 as CachePT1: Running
6/11/2019 5:50:30 PM - Excel CachePivotTable miLibroOBIEE in miHojaOBIEE from A1 to I12 as CachePT1 : Success
6/11/2019 5:50:30 PM - ## ESTO FALLA: Running
6/11/2019 5:50:30 PM - ESTO FALLA : Success
6/11/2019 5:50:30 PM - Excel CreatePivotTable CachePT1 in miHojaOBIEE2 cell A2 with_name "a" as PivotTable: Running
6/11/2019 5:50:30 PM - Error in : CreatePivotTable CachePT1 in miHojaOBIEE2 cell A2 with_name "a" as PivotTable
6/11/2019 5:50:30 PM - Exception:System.Runtime.InteropServices.COMException (0x800A03EC): The PivotTable field name is not valid. To create a PivotTable report, you must use data that is organized as a list with labeled columns. If you are changing the name of a PivotTable field, you must type a new name for the field.
   at System.Dynamic.ComRuntimeHelpers.CheckThrowException(Int32 hresult, ExcepInfo& excepInfo, UInt32 argErr, String message)
   at CallSite.Target(Closure , CallSite , ComObject , PivotCache , Range , String )
   at CallSite.Target(Closure , CallSite , Object , PivotCache , Range , String )
   at ExcelReader.ExcelExecute.CreatePivotTable(String action) in C:\Users\jonathan.camacho\Source\Repos\AutomationPlatform\ExcelReader\ExcelExecute.cs:line 10350
6/11/2019 5:50:30 PM - Error in : CreatePivotTable CachePT1 in miHojaOBIEE2 cell A2 with_name "a" as PivotTable
6/11/2019 5:50:30 PM - Excel CreatePivotTable CachePT1 in miHojaOBIEE2 cell A2 with_name "a" as PivotTable : Error
6/11/2019 5:50:31 PM - Execution ended

Se adjunta el excel en teams.

**Comment by ClaudioRodolfoGarcete** [comment]
Necesidad: Urgente.

**Comment by JuanISalazarM** [comment]
Seguro lo atenderemos.

**Comment by JuanISalazarM** [comment]
Buenas tardes @ClaudioRodolfoGarcete .
Según la imagen el cuadro empieza a partir de la celda A5.
Este código muestra error dado que el A1 está combinado con otras celdas.
Por tanto recomiendo la siguiente línea para guardar la tabla pivote: 

`CachePivotTable miLibroOBIEE in miHojaOBIEE from A5 to I12 as CachePT1`

Espero resuelva la incógnita. Espero su respuesta.

**Comment by ClaudioRodolfoGarcete** [comment]
Muchas gracias @JuanISalazarM , solucionado.
