### ISSUE TITLE
La instruccion DeleteAll no funciona

### ISSUE THREAD

**Issue by CristianCelano** [FridaSupport/TuringSuport#20]
Tengo que eliminar el contenido de una hoja de excel y no me funciona la instruccion DeleteAll

Instruccion:
Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro
Titanium Sleep 2000
Excel LoadWSheet libro sheet_index 1 as hoja
Titanium Sleep 2000
Ecel DeleteAll from Ejercicio1
Titanium Sleep 2000
Excel Save libro

Log:
4/25/2019 10:41:15 AM - Execution started
4/25/2019 10:41:15 AM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro: Running
4/25/2019 10:41:15 AM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro : Success
4/25/2019 10:41:15 AM - Titanium Sleep 2000: Running
4/25/2019 10:41:17 AM - Titanium Sleep 2000 : Success
4/25/2019 10:41:17 AM - Excel LoadWSheet libro sheet_index 1 as hoja: Running
4/25/2019 10:41:17 AM - Excel LoadWSheet libro sheet_index 1 as hoja : Success
4/25/2019 10:41:17 AM - Titanium Sleep 2000: Running
4/25/2019 10:41:19 AM - Titanium Sleep 2000 : Success
4/25/2019 10:41:19 AM - Ecel DeleteAll from Ejercicio1: Running
4/25/2019 10:41:19 AM - Error: Ecel DeleteAll from Ejercicio1
4/25/2019 10:41:19 AM - Error in ecel Instruction was't found
4/25/2019 10:41:19 AM - Ecel DeleteAll from Ejercicio1 : Error
4/25/2019 10:41:20 AM - Execution ended

**Comment by FaustinoLechuga** [comment]
Ecel DeleteAll from Ejercicio1

intenta agregando una x a en el excel

Excel DeleteAll from Ejercicio1

**Comment by CristianCelano** [comment]
Ya lo probe y no funciona

Instruccion:
Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro
Titanium Sleep 2000
Excel LoadWSheet libro sheet_index 1 as hoja
Titanium Sleep 2000
Excel DeleteAll from Ejercicio1
Titanium Sleep 2000
Excel Save libro

Log:
4/25/2019 2:28:46 PM - Execution started
4/25/2019 2:28:46 PM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro: Running
4/25/2019 2:28:47 PM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro : Success
4/25/2019 2:28:47 PM - Titanium Sleep 2000: Running
4/25/2019 2:28:49 PM - Titanium Sleep 2000 : Success
4/25/2019 2:28:49 PM - Excel LoadWSheet libro sheet_index 1 as hoja: Running
4/25/2019 2:28:49 PM - Excel LoadWSheet libro sheet_index 1 as hoja : Success
4/25/2019 2:28:49 PM - Titanium Sleep 2000: Running
4/25/2019 2:28:51 PM - Titanium Sleep 2000 : Success
4/25/2019 2:28:51 PM - Excel DeleteAll from Ejercicio1: Running
4/25/2019 2:28:51 PM - Error DeleteAll from Ejercicio1
4/25/2019 2:28:51 PM - Excel DeleteAll from Ejercicio1 : Error
4/25/2019 2:28:51 PM - Execution ended

**Comment by FaustinoLechuga** [comment]
Intenta con esto, el wskey es el nombre de como guardaste al ws

Excel DeleteAll from hoja

**Comment by CristianCelano** [comment]
Tampoco funciona asi

Instruccion:
Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro
Titanium Sleep 2000
Excel LoadWSheet libro sheet_index 1 as hoja
Titanium Sleep 2000
Excel DeleteAll from hoja
Titanium Sleep 2000
Excel Save libro

Log:
4/25/2019 4:57:38 PM - Execution started
4/25/2019 4:57:38 PM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro: Running
4/25/2019 4:57:39 PM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro : Success
4/25/2019 4:57:39 PM - Titanium Sleep 2000: Running
4/25/2019 4:57:41 PM - Titanium Sleep 2000 : Success
4/25/2019 4:57:41 PM - Excel LoadWSheet libro sheet_index 1 as hoja: Running
4/25/2019 4:57:41 PM - Excel LoadWSheet libro sheet_index 1 as hoja : Success
4/25/2019 4:57:41 PM - Titanium Sleep 2000: Running
4/25/2019 4:57:43 PM - Titanium Sleep 2000 : Success
4/25/2019 4:57:43 PM - Excel DeleteAll from hoja: Running
4/25/2019 4:57:43 PM - Error DeleteAll from hoja
4/25/2019 4:57:43 PM - Excel DeleteAll from hoja : Error
4/25/2019 4:57:43 PM - Execution ended

**Comment by FaustinoLechuga** [comment]
ya lo estoy revisando

**Comment by FaustinoLechuga** [comment]
Te acabo de liberar una versión con unos cambios que hice, podrías probar la función de nuevo?

**Comment by CristianCelano** [comment]
Ahi lo probe y funciona perfecto
Muchas gracias.


instruccion:
Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro
Titanium Sleep 2000
Excel LoadWSheet libro sheet_index 1 as hoja
Titanium Sleep 2000
Excel DeleteAll from hoja
Titanium Sleep 2000
Excel Save libro

log:
4/29/2019 2:35:46 PM - Execution started
4/29/2019 2:35:46 PM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro: Running
4/29/2019 2:35:47 PM - Excel LoadWBook "C:\Users\cristian.celano\Downloads\Ejercicio1.XLS" as libro : Success
4/29/2019 2:35:47 PM - Titanium Sleep 2000: Running
4/29/2019 2:35:49 PM - Titanium Sleep 2000 : Success
4/29/2019 2:35:49 PM - Excel LoadWSheet libro sheet_index 1 as hoja: Running
4/29/2019 2:35:49 PM - Excel LoadWSheet libro sheet_index 1 as hoja : Success
4/29/2019 2:35:49 PM - Titanium Sleep 2000: Running
4/29/2019 2:35:51 PM - Titanium Sleep 2000 : Success
4/29/2019 2:35:51 PM - Excel DeleteAll from hoja: Running
4/29/2019 2:35:51 PM - Excel DeleteAll from hoja : Success
4/29/2019 2:35:51 PM - Titanium Sleep 2000: Running
4/29/2019 2:35:53 PM - Titanium Sleep 2000 : Success
4/29/2019 2:35:53 PM - Excel Save libro: Running
4/29/2019 2:35:54 PM - Excel Save libro : Success
4/29/2019 2:35:54 PM - Execution ended
