### ISSUE TITLE
[SAP] Al procesar un archivo Excel con 100 registros For Each se cae

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#200]
Al procesar un archivo Excel con 100 registros y guardandola en una variable para insertar en SAP el For Each se cae, adjunto los archivos de LOG, el For Each y el archivo Excel cual estoy procesando.

Error: Error in SAP Write id wnd[0]/usr/tabsTAXI_TABSTRIP_OVERVIEW/tabpT\01/ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL_U_ERF_AUFTRAG/ctxtRV45A-MABNR[1,10] "1900649.000"

[For Each.txt](https://github.com/FridaSupport/TuringSuport/files/3282686/For.Each.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3282687/log.txt)
[SOFIA -- Formulario de Solicitud de Cotización - ER 11-06 performance-testing.xlsx](https://github.com/FridaSupport/TuringSuport/files/3282688/SOFIA.--.Formulario.de.Solicitud.de.Cotizacion.-.ER.11-06.performance-testing.xlsx)

**Comment by eradgg** [comment]
Ya lo reviso.

**Comment by eradgg** [comment]
hola Victor, no pude encontrar diferencias con el ShowElements, podrías grabar lso scripts con 10 y mas de 10?

saludos.

**Comment by victorgamboa** [comment]
Dale, los hago y te los envío

**Comment by eradgg** [comment]
Sigo trabajando en este Issue, no se ha podido reconocer los elementos, estoy haciendo una aplicación que me ayude a saber qué pasa en esl servidor, ya que no podemos conectarnos directamente al servidor de SAP y hacer una prueba en modo debug.

Si se pudiera conseguir la manera de tener la conexión mediante SAP sería más fácil y menos tardado.

**Comment by victorgamboa** [comment]
Hola Eder, ya hable con el cliente, y esta complicado por el tema de la VPN, Compliance y de seguridad de Finning, otra alternativa es que instales Visual Studio en el servidor y hacer el debug ahí mismo, el cliente me pidió si puedes pasarme un correo solicitando estas dos alternativas para escalarlo con las áreas que corresponden, saludos.

**Comment by gantonioid** [comment]
Instalar visual en su servidor significaría poner el código fuente de FRIDA en esa máquina.
NO nos conviene hacer eso @eradgg @victorgamboa @pabloreitanosofttek

No se puede compartir la VPN de Victor con Eder? o conseguirle una diciendo que es parte del equipo de desarrollo del RPA?

**Comment by victorgamboa** [comment]
La VPN que uso yo es WEB "https://vpn.finning.cl/Softtek". Que solución podríamos solicitar?

**Comment by gantonioid** [comment]
Cómo te conectas tú? supongo que tienes credenciales para usar la VPN, se pueden compartir o pedir unas credenciales para Eder? Lo que digo es que consigamos unos accesos para facilitarle a Eder entrar a ver el problema y solucionarlo.

**Comment by victorgamboa** [comment]
Yo me conecto a través de ese link que adjunte, ya le pase las credenciales a Eder y pudo entrar, pero entiendo que Eder necesita instalar el acceso a SAP desde su maquina local para hacer el debug...Y el cliente ve complicado instalar el acceso a SAP en su maquina.

**Comment by pabloreitanosofttek** [comment]
¿Y entonces?

**Comment by gantonioid** [comment]
Pues no lo sé... seguro @eradgg está viendo opciones pero no la tenemos fácil. ¿Quién nos ayuda? @pabloreitanosofttek

**Comment by pablorlmx** [comment]
No pueden tomar la máquina de @victorgamboa de manera remota?

**Comment by gantonioid** [comment]
@pablorlmx se requiere un entorno de desarrollador, por eso la solicitud es que @eradgg tenga acceso desde su máquina.

**Comment by eradgg** [comment]
si tengo acceso remoto al servidor, pero eso no me sirve ya que necesito tener conexión de SAP para ver por qué me está dando error, así es muy difícil poder entender que pasa, estoy desarrollando una aplicación con el mismo código pero que me esté dando logs todo el timpo de qué es lo que pasa, pero me lleva mucho tiempo. Si se pudiera negociar que se tenga el acceso sería mucho más rápido, como lo es´con Argentina, 1, 2 días si es complicado, ahora ya llevo 5 y no tengo idea de qué es lo que pasa en su ambiente.

**Comment by eradgg** [comment]
Hay que recordar que en varios aspectos SAP al ser un ambiente que se peude desarrollar por cada cliente, varía en la programación de las interfases, por eso muchas veces hay que revisar qué es lo que sucede.

**Comment by pabloreitanosofttek** [comment]
¿Y entonces? @FridaSupport

**Comment by gantonioid** [comment]
> @pablorlmx se requiere un entorno de desarrollador, por eso la solicitud es que @eradgg tenga acceso desde su máquina.

Pues entiendo que esto se mantiene... entiendo que nos han ayudado a tener acceso

**Comment by pablorlmx** [comment]
Ya lo estamos revisando con el cliente. Ni bien nos den na respuesta les avisamos.

________________________________

**Comment by pabloreitanosofttek** [comment]
Ticket el hold hasta tener acceso... nos confirmará @pablorlmx 

¡gracias!

**Comment by pablorlmx** [comment]
No es posible acceder al SAP del cliente dado qu su software de VPN no lo permite.

Se puede usar un SAP interno dado que el error es replicable debido a que la transacción es estándar y el error no es de datos?


________________________________

**Comment by eradgg** [comment]
Favor de checarlo y validar. Se cambió el script.

**Comment by gantonioid** [comment]
5 días sin respuesta... lo damos por resuelto. Comentar con los resultados en caso de querer abrirlo de nuevo.
