### ISSUE TITLE
[Excellia] - Error al referenciar una posición de un list

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#201]
NECESIDAD URGENTE
Estando dentro de un foreach, al referenciar una posición determinada de un list usando un contador, el resultado queda fijo en la primer posición.
Adjunto código armado para probar el error.
[ERROR_LIST.txt](https://github.com/FridaSupport/TuringSuport/files/3282799/ERROR_LIST.txt)

**Comment by FaustinoLechuga** [comment]
¿Podras adjuntar el log correspondiete a las instrucciones que nos mandaste?

**Comment by ignacionovio** [comment]
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3282902/log.txt)

**Comment by FaustinoLechuga** [comment]
Ya vi que era, era un error de sintaxis al momento de usar la variable. A veces puede ser algo confuso pero solo hay que tomar en cuenta esos detalles. Notese que en la siguiente instrucción utilice `<<<cont>>>` en lugar de solo cont.
`SystemNotify Type "Validation" with message "<<<cont>>> <<<Reg>>> <<<lista2[<<<cont>>>]>>>"`
Espero esto resuelva el problema, quedo al pendiente para la confirmación.

**Comment by ignacionovio** [comment]
Funciona así, muchas gracias
