### ISSUE TITLE
[TITAN] ApplyFilter con referencia.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#202]
Hola,

Partiendo del siguiente excel, necesitamos realizar un filtro haciendo referencia a la fila 5.

![1](https://user-images.githubusercontent.com/33100638/59382774-da317180-8d34-11e9-9e7c-71b9a32ad185.png)

Al ejecutar el siguiente script:

DefineVariable type "string" as "excelOBIEExCTA" with the value "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03V2.xlsx"
Excel LoadWBook "<<<excelOBIEExCTA>>>" as miLibroOBIEE
Excel LoadWSheet miLibroOBIEE sheet "Sheet1" as miHojaOBIEE
#Excel RemoveRows from the worksheet miHojaExcelGenerado from the index 1 to 3
Excel ApplyFilter to the worksheet miHojaOBIEE to the column with the index {3} with the criteria "111040300"
Titanium Sleep = 4000
#Excel Save miLibroOBIEE

El comportamiento es el siguiente:

![2](https://user-images.githubusercontent.com/33100638/59383087-968b3780-8d35-11e9-8c89-106aba1d479b.png)

Como ven, realiza el filtro de las cuentas 111040300 correctamente, pero elimina las filas 2,3 y 4, lo cual, es un comportamiento que NO debe suceder.

Lo que necesitamos es una forma de que la instruccion ApplyFilter haga el filtro dada una referencia, en este caso es la fila 5, y NO borre las filas.

O quizas sea un tema de sintaxis y ya exista tal cosa, a la espera de feed.

Se adjunta el excel en teams.

Necesidad: Urgente.

**Comment by JuanISalazarM** [comment]
Seguro, lo atenderemos.

**Comment by JuanISalazarM** [comment]
Buenas tardes.
Se ha actualizado la versión de su Turing.
Solicitaría de favor colocar esta línea de código:

`ApplyFilterStartAt to the worksheet {miHojaOBIEE} start at row {5} to the column with the index {3} with the criteria "111040300"`

En lugar de ApplyFilter, porfavor. Gracias por su atención. Esperamos su respuesta.

**Comment by ClaudioRodolfoGarcete** [comment]
Resuelto @JuanISalazarM  muchas gracias.
