### ISSUE TITLE
[TITAN] RemoveSheets

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#204]
No es posible borrar hojas con la instruccion RemoveSheets.

Log:

6/13/2019 12:55:59 PM - Proces ID :1146059059
6/13/2019 12:55:59 PM - Execution started
6/13/2019 12:55:59 PM - DefineVariable type "string" as "excelOBIEExCTA" with the value "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03V2.xlsx": Running
6/13/2019 12:55:59 PM - MixReader : Se agrego una nueva variable : 
Var Name : excelOBIEExCTA
Value : C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03V2.xlsx
6/13/2019 12:55:59 PM - DefineVariable type "string" as "excelOBIEExCTA" with the value "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03V2.xlsx" : Success
6/13/2019 12:55:59 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03V2.xlsx" as miLibroOBIEE: Running
6/13/2019 12:56:01 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\OBIEE X CTA. 27-03V2.xlsx" as miLibroOBIEE : Success
6/13/2019 12:56:01 PM - Excel LoadWSheet miLibroOBIEE sheet "Hoja2" as miHojaOBIEE2: Running
6/13/2019 12:56:01 PM - Excel LoadWSheet miLibroOBIEE sheet "Hoja2" as miHojaOBIEE2 : Success
6/13/2019 12:56:01 PM - Excel RemoveSheets from miLibroOBIEE sheet miHojaOBIEE2: Running
6/13/2019 12:56:01 PM - Error in : RemoveSheets from miLibroOBIEE sheet miHojaOBIEE2
6/13/2019 12:56:01 PM - Exception : Invalid index. (Exception from HRESULT: 0x8002000B (DISP_E_BADINDEX))
6/13/2019 12:56:01 PM - Error in : RemoveSheets from miLibroOBIEE sheet miHojaOBIEE2
6/13/2019 12:56:01 PM - Excel RemoveSheets from miLibroOBIEE sheet miHojaOBIEE2 : Error
6/13/2019 12:56:02 PM - Execution ended

Necesidad: Urgente.

**Comment by Johhnn117** [comment]
En vez de escribir 
Excel RemoveSheets from miLibroOBIEE sheet miHojaOBIEE2

usa 
Excel RemoveSheets from miLibroOBIEE sheet Hoja2

**Comment by ClaudioRodolfoGarcete** [comment]
Perfecto, solucionado. Era un tema de sintaxis.

**Comment by Johhnn117** [comment]
Tema resuelto, error de sintaxis
