### ISSUE TITLE
[SAP] Se envía mail sin firma del cliente

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#205]
AL enviar un mail, este se envía sin la firma del cliente
@eradgg ya esta al tanto y lo esta revisando.

Gracias

**Comment by eradgg** [comment]
Hola Victor, ya está hecho el cambio, debería de funcionar.
¿Puedes probar?

Saludos.

**Comment by victorgamboa** [comment]
No tengo que hacer ningún cambio?
el cambio solo lo hiciste tu?

**Comment by eradgg** [comment]
Hola Victor. 

Creé una nueva versión, ya que el Windows del servidor está en inglés, pero el office está en español. en esta nueva función puedes poner directamente la ruta del archivo de la firma.
Esta es la manera de utilizarla:
SendEmailWithSignature BoClientesMail To "<<<RemitenteMail>>>" Subject "Cotización <<<NumeroCotizacion>>>" Attachments "Test.htm" Path "C:\Users\EDERR.GARcia\Documents\Proyectos\Finning\SOFIA\Issues\No mail" Signature "C:\Users\EDERR.GARcia\AppData\Roaming\Microsoft\Signatures\Softtek.htm"
saludos.

**Comment by victorgamboa** [comment]
Eder, me sigue dando un error:

6/14/2019 10:40:29 AM - DefineVariable type "string" as "BoClientesMail" with the value "<body lang=ES-MX style='tab-interval:.5in'><div><p>Estimado Le adjuntamos su Cotización Repuestos 25068397 de acuerdo a lo solicitado. Cualquier duda, por favor, comunicarse al Centro de Venta de Repuesto (CVR) al número 22 928 6000 Atentamente</p></div></body>" : Success
6/14/2019 10:40:29 AM - SendEmailWithSignature BoClientesMail To "<victor.gamboa@hotmail.cl>" Subject "Cotización Repuestos 25068397" Attachments "Cotización Repuestos 25068397.pdf" Path "C:\Users\soporte.clientes\Documents\" Signature "C:\Users\soporte.clientes\AppData\Roaming\Microsoft\Firmas\Softtek.htm": Running
6/14/2019 10:40:29 AM - Error: SendEmailWithSignature BoClientesMail To "<<<RemitenteMail>>>" Subject "Cotización <<<NumeroCotizacion>>>" Attachments "Cotización <<<NumeroCotizacion>>>.pdf" Path "C:\Users\soporte.clientes\Documents\" Signature "C:\Users\soporte.clientes\AppData\Roaming\Microsoft\Firmas\Softtek.htm"
6/14/2019 10:40:29 AM - Error in sendemailwithsignature Instruction was't found
6/14/2019 10:40:29 AM - SendEmailWithSignature BoClientesMail To "<victor.gamboa@hotmail.cl>" Subject "Cotización Repuestos 25068397" Attachments "Cotización Repuestos 25068397.pdf" Path "C:\Users\soporte.clientes\Documents\" Signature "C:\Users\soporte.clientes\AppData\Roaming\Microsoft\Firmas\Softtek.htm" : Error
6/14/2019 10:40:31 AM - Execution ended

**Comment by pabloreitanosofttek** [comment]
Si no está funcionando @eradgg  te pido que saques la etiqueta de resuelto. ¡gracias!

**Comment by pablorlmx** [comment]
@eradgg alguna novedad? Por favor necesitamos resolver esto lo antes posible. Gracias

**Comment by eradgg** [comment]
Hola Ya envié un status por correo.

Ahí comento por qué es que está atrasado este Issue, tengo varios que no puedo debuggear en la máquina de Finning, y esto atrasa los tiempos de solución.

**Comment by eradgg** [comment]
Se hace el cambio. Victor confirma que si env[ia el correo correctamente.
