### ISSUE TITLE
[Excellia] SAP ReadElement - No encuentra el elemento ID (urgente)

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#206]
Se ejecuta la instrucción ReadElement de SAP, para obtener el texto de la siguiente Imagen,

![image](https://user-images.githubusercontent.com/25591982/59463324-1d0a4c80-8dfc-11e9-81ac-bb8057f36504.png)

```
El Id de la ventana es:/app/con[0]/ses[0]/wnd[1]/usr/txtMESSTXT1
el ID del texto contenido en la ventana es: wnd[1]/usr/txtMESSTXT2
```

Se realizo pruebas con ambos Id siempre con el mismo Resultado:
Instrucciones usadas:

```
SAP ReadElement /app/con[0]/ses[0]/wnd[1]/usr/txtMESSTXT1 as StatusMessage
SAP ReadElement wnd[1]/usr/txtMESSTXT2 as StatusMessage
```

```
SAP FindText ">>> Cta." as IdVerificaLog
SAP ReadElement <<<IdVerificaLog>>> as StatusMessage
```

Log de error:

> 
> 13/06/2019 16:53:00 - SAP FindText ">>> Cta." as IdVerificaLog: Running
> 13/06/2019 16:53:01 - Se actualizo la variable : 
> Var Name : IdVerificaLog
> Value : /app/con[0]/ses[0]/wnd[1]/usr/txtMESSTXT1
> 13/06/2019 16:53:01 - SAP FindText ">>> Cta." as IdVerificaLog : Success
> 13/06/2019 16:53:01 - Please check the for syntax and that the value given is a number greater than 0
> 13/06/2019 16:53:01 - error: selectm id "wnd[0]/mbar/menu[4]/menu[12]" : System.Runtime.InteropServices.COMException (0x0000026B): The control could not be found by id.
>    en System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
>    en SAPFEWSELib.ISapSessionTarget.FindById(String Id, Object Raise)
>    en SapScriptReader.SapScriptExecute.SelectMenuById(String MenuId) en C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:línea 1738
>    en SapScriptReader.SapScriptExecute.SelectMenu(String action) en C:\Users\andres.cruz\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:línea 1716
> 13/06/2019 16:53:02 - Execution ended

**Comment by eradgg** [comment]
Hola Soledad.

Ahora reviso por qué no está funcionando, podrías usar el Show Elements para identificar el id dle elemento que trae el texto. o ¿Necesita ser dinámico?

**Comment by SoledadNunez** [comment]
tengo el id del elemento que trae el teto y es el 
ID del texto contenido en la ventana es: wnd[1]/usr/txtMESSTXT2

No es necesario que sea dinámico.

**Comment by eradgg** [comment]
Ya probaste así?

SAP ReadElement wnd[1]/usr/txtMESSTXT2 as StatusMessage
Cual es el proceso?

**Comment by SoledadNunez** [comment]
Buenos días Eder, fijate que en el detalle del TK indico que probé también con el id que me sugerís.

a que te referís con proceso? a la transacción SAP o al numero del proceso frida? contactame  por teams y lo hablamos bien.
Muchas gracias

**Comment by eradgg** [comment]
Me puedes confirmar que ya funciona?

saludos.

**Comment by SoledadNunez** [comment]
Buenos días Edder, ya funciona cierro el issue
