### ISSUE TITLE
[Excellia] - Error CopyPaste

### ISSUE THREAD

**Issue by Josecamats** [FridaSupport/TuringSuport#207]
Buenas tardes, no me funciona CopyPaste de Excellium.

Script:
```
Excel WriteFormula WS in P1 formula =SUBTOTAL(3,D:D)
Excel GetCellValue from the worksheet WS in column {16} and row {1} and save as Count1
Titanium Sleep 8000
Excel CopyPaste WS A1:M<<<Count1>>> to WSNC A1
```

Log:
6/14/2019 4:46:20 PM - Excel CopyPaste WS A1:M98 to WSNC A1: Running
6/14/2019 4:46:20 PM - Error: CopyPaste WS A1:M98 to WSNC A1
6/14/2019 4:46:20 PM - Error in copypaste Instruction was't found
6/14/2019 4:46:20 PM - Error in copypaste Instruction was't found
6/14/2019 4:46:20 PM - Excel CopyPaste WS A1:M98 to WSNC A1 : Error

**Comment by JuanISalazarM** [comment]
Seguro, lo atenderemos.
Solicitaría de favor que me comparta los archivos que utiliza para la ejecución del proceso, el log y el código que utiliza, porfavor.
También solicito conocer la versión de Turing que tiene actualmente.
Gracias por su atención. Esperamos su respuesta.

**Comment by JuanISalazarM** [comment]
Buenas. 
Solicitamos nuevamente que nos proporcione los archivos previamente mencionados, porfavor.
Esto es para llevar a cabo pruebas para ver que está fallando realmente.
Por su atención, gracias. Esperamos su respuesta.

**Comment by JuanISalazarM** [comment]
Nos encontramos en espera de los archivos.

**Comment by FaustinoLechuga** [comment]
Platicando con Juan y Antonio llegamos a la conclusión que tal vez un update resuelva esto con un update. Se te realizo un update (20190617T0444) para que Frida se actualice solo hay que cerrarlo y volverlo a abrir. 

Esperamos confirmación que Frida se actualizo exitosamente y que se soluciono el problema, de lo contrario favor de seguir al contacto por este medio.

**Comment by pabloreitanosofttek** [comment]
Estimados, @Josecamats  está enfermo hoy... no se si lo podrán seguir con alguien @MartinMedinaSTK

**Comment by gantonioid** [comment]
Tienen acceso al proceso en cuestión para hacer la prueba?
@JuanISalazarM puedes dar seguimiento con Martín? supongo que requerirá el mismo update que Josecamats

**Comment by JuanISalazarM** [comment]
Seguro, necesitaría que lo ingresen a este ticket para que nos reporte cualquier incidencia. Porfavor.
Procederé a actualizar el Turing de Martin. Pero necesito que esté en este Ticket para saber si se solucionó o no.

**Comment by gantonioid** [comment]
Claro, aquí está copiado @MartinMedinaSTK

**Comment by JuanISalazarM** [comment]
Estimado @MartinMedinaSTK la versión de su Turing ha sido actualizada. Solicito de favor realizar una prueba.
En caso de que no funcione. Pido de favor los archivos previamente mencionados, los cuales son: 
-Los archivos que utiliza para la ejecución del proceso
-El log
-El código que utiliza

Porfavor. Gracias. Nos encontramos al pendiente.

**Comment by gantonioid** [comment]
@MartinMedinaSTK tienes comentarios?

**Comment by pabloreitanosofttek** [comment]
Buen día quedamos a la espera de los comentarios de @Josecamats. (en ARG el 20 es festivo)

**Comment by Josecamats** [comment]
Hola como estan todos?
Disculpen la demora, me encontraba de baja médica.
Recién lo volví a probar con la actualización y funciona.
Muchas gracias!
