### ISSUE TITLE
[Consulta] Error 404 Not Found

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#208]
AL realizar el llamado a la api, da el siguiente Error.

![image](https://user-images.githubusercontent.com/49756748/59689383-906dde80-91ad-11e9-8606-28eb6ffe159e.png)

Estoy usando estos Parametros:

{
	"ProcessID":"sofia1072851774",
	"UserID":"ffa950b2-9903-470b-874b-85d21d805a09"
}

Quien me podria ayudar a resolver esto?
Necesito limpiar la cola de correos que se van a leer cuando el bots se active, gracias.

**Comment by gantonioid** [comment]
Puedes intentar de nuevo, ajusté el servidor para solucionarlo. Ya responde status 200 - OK
![image](https://user-images.githubusercontent.com/9600868/59700005-29a1f280-91b8-11e9-818b-10d7b3f08832.png)

**Comment by gantonioid** [comment]
@victorgamboa ya probaste?

**Comment by victorgamboa** [comment]
Si, Muchas gracias @gantonioid

**Comment by FridaSupport** [comment]
Se cierra el ticket. Ya se solucionó
