### ISSUE TITLE
[TITAN]Solicitud De ayuda para insertar varias columnas  

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#209]
Buenos Dias

Se solicita de su amable colaboración para insertar varias columnas, filtradas por una columna especifica,
actualmente se esta utilizando WriteValueThatMatch (Funcionamiento Correcto) pero al ejecutarlo para varias columnas no es muy útil ya que se demora mucho ejecutando la automatización. Ejemplo.

Excel WriteValueThatMatch in the worksheet ShExConsolidadoPend at the column {1} maching the value "<<<locRep[1]>>>" and writing in the column {6} the value {<<<locRep[2]>>>}
Excel WriteValueThatMatch in the worksheet ShExConsolidadoPend at the column {1} maching the value "<<<locRep[1]>>>" and writing in the column {7} the value {<<<locRep[3]>>>}

se pensó en el CopyRange, pero en tiempo de ejecución se desconoce el row que se requiere.

la solicitud es para saber si alguna forma de obtener una fila especifica enviando un filtro, o si alguna sentencia que tenga el mismo comportamiento de WriteValueThatMatch, pero para escribir en varias columnas. o si  hay alguna forma de implementar el  CopyRange para este caso, Adjunto los Exceles y el código con el que se esta trabajando.

[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3302194/codigo.txt)
[reproceso.xlsx](https://github.com/FridaSupport/TuringSuport/files/3302200/reproceso.xlsx)
[Copia de Consolidado pendientes MARZO.xlsx](https://github.com/FridaSupport/TuringSuport/files/3302201/Copia.de.Consolidado.pendientes.MARZO.xlsx)

Agradezco por la atención prestada y estaré atento a cualquier comentario.

**Comment by Johhnn117** [comment]
Buenos días,

revisaré la mejoras que nos comentas, te mantengo informado.

**Comment by Johhnn117** [comment]
Estoy tratando de correr el proceso con el script que subiste pero me marca un error de Syntaxis, puedes checarlo?

![image](https://user-images.githubusercontent.com/50710733/59700359-c8c6ea00-91b8-11e9-8be2-a6e307639173.png)

**Comment by rrrios** [comment]
saludos
descargue el txt que yo subi y me funciona, por lo que veo en la imagen que adjuntantés es un error de estructura en try catch, es como si no se estuviera cerrando el Catch. por favor valida si el catch que tienes tiene el end.  en la línea 24 debe tener 2 end, uno del if y el otro del catch.

**Comment by pablorlmx** [comment]
Estimado @Johhnn117, qué posibilidad tenemos de avanzar esto con prioridad? Si bien hoy no es bloqueante el BOT asociado debe estar listo pasado mañana.

sumo a @RickProductivity  y @pabloreitanosofttek para que estén al tanto

**Comment by Johhnn117** [comment]
Estoy revisando la solicitud, mañana doy un update del progreso

**Comment by pabloreitanosofttek** [comment]
Ok, porfa avísanos para tener acciones de cara a cliente.
Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: Jonathan Camacho Guel <notifications@github.com>
Enviado: martes, junio 18, 2019 4:39 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [TITAN]Solicitud De ayuda para insertar varias columnas (#209)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Estoy revisando la solicitud, mañana doy un update del progreso

**Comment by Johhnn117** [comment]
Estoy trabajando en un WriteValueThatMatch que permita insertar varias columnas filtradas por una columna especifica, hoy queda entonces comparto la solución en cuanto la termine.

**Comment by Johhnn117** [comment]
@rrrios puedes revisar que tengas la versión 20190619T1120

se añadió una función con la siguiente sintaxis: 
`WriteValueThatMatch in the worksheet <wsKey> at the column {<ColumnAIndex>} maching the value "<Criteria>" and writing in cells starting at {<ColumnBStartIndex2>} and ending at {<ColumnBEndIndex2>} the values {<value1>,<value2>....,<valuen>}`


en tu caso el código quedaría de la siguiente forma mostrada en el archivo adjunto.
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3308190/codigo.txt)

con el script que subiste tardaba un minuto en correr 102 lineas, con la nueva instrucción hace las mismas 102 lineas en 30s

**Comment by pabloreitanosofttek** [comment]
Gracias @Johhnn117  esperamos los comentarios de @rrrios .

**Comment by rrrios** [comment]
se obtuvo version, se hara las pruebas respectivas y durante el transcurso del día. se dará la respuesta para cerrar el issue.

**Comment by rrrios** [comment]
se realizo la prueba, y lo que sucedió fue los datos los escribió en una sola columna separados por comas
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50424090/59880057-bba12b00-9371-11e9-9da4-5edd96b39324.png">
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3312043/log.txt)

**Comment by Johhnn117** [comment]
no estás usando bien la instrucción, si quieres podemos tener una llamada para verla a detalle

**Comment by rrrios** [comment]
la instrucción se esta utilizando tal cual la pusiste en el adjunto. 
Excel WriteValueThatMatch in the worksheet ShExConsolidadoPend at the column {1} maching the value "<<<locRep[1]>>>" and writing in cells starting at {6} and ending at {11} the values {<<<locRep[2]>>>,<<<locRep[3]>>>,<<<locRep[4]>>>,<<<locRep[5]>>>,<<<locRep[6]>>>,<<<locRep[7]>>>}
estoy pendiente para realizar la llamada para ver en detalle el inconveniente,

**Comment by Johhnn117** [comment]
Tuvimos una llamada @rrrios y yo para revisar el script, se va a revisar la nueva instrucción con las modificaciones que se hicieron al script del proceso para encontrar la razón por la cual copió todos los datos en la misma columna

**Comment by Johhnn117** [comment]
puedes revisar que tengas la versión 20190621T0830 y volver a correr el proceso?

**Comment by rrrios** [comment]
saludos
se realizo la respectiva prueba, se abrió el excel en tiempo de ejecución y se puede observar que el sistema cambia los valores por un breve momento, pero por alguna razón deja los valores tal y como estaban inicialmente en el excel.

**Comment by pabloreitanosofttek** [comment]
@gantonioid @Johhnn117  @FridaSupport  ¿Me cuentan cual es el estado? Necesitamos tener certeza de la resolución del problema.

¡gracias!

**Comment by Johhnn117** [comment]
Se está trabajando en solucionar el porque no se están guardando los cambios, en el transcurso del día doy una actualización del asunto

**Comment by pabloreitanosofttek** [comment]
Ok, gracias... porfa sacar que está resuelto entonces, dado que según comentario de arriba no está. 

slds,

**Comment by pabloreitanosofttek** [comment]
@Johhnn117 al final está? no vi el update.

gracias!

**Comment by Johhnn117** [comment]
se tuvo una plática con @rrrios y me comentó que a pesar de que la instrucción funciona está copíando valores erroneos, revisando su script me di cuenta que en dos ocasiones está tomando una celda vacia para darle un valor a una variable, se le preguntó si eso es a propósito o si es un error, sigo en espera de su respuesta ya que esa podría ser la razón de que su proceso no funcione como se desea

**Comment by rrrios** [comment]
En primer lugar la línea que sugiere @Johhnn117 no esta presentando error, esto basado en log que genera el sistema.
En segundo lugar esa línea esta metida en un if lo cual no afecta la nueva funcionalidad, ya que esta separado y no va ejecutar la línea que puede presentar el error.
En tercero se comento la línea la cual se sospecha se este presentando el error y el resultado es el mismo, que no se esta insertando bien los valores y además hace falta valores.

se adjunta el log
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3350937/log.txt)

**Comment by Johhnn117** [comment]
Ok, voy a revisar el script original que hace bien el proceso pero tardaba mucho y compararlo con las nuevas instrucciones para ver cual es la razón y solucionarlo hoy, en el transcurso del día doy un update del ticket

**Comment by Johhnn117** [comment]
se compartió nueva versión con @rrrios, quedo en espera de sus comentarios

**Comment by rrrios** [comment]
se tuvo call con @Johhnn117 aclarando la solicitud. se descargo version y se realizaron las pruebas unitarias respectivas.  la cuales cumplen con lo que se estaba requiriendo.

agradezco por el apoyo a la solicitud.
