### ISSUE TITLE
Convertir CSV en XLSX (continuación del Issue #16) 

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#21]
@gantonioid Probé tu ejemplo tal cual lo dejaste en el issue #16 y solo funcionó la primera vez.
![image](https://user-images.githubusercontent.com/49758327/56740370-33beec00-6747-11e9-9e61-3c750637046a.png)

te adjunto el log.

4/25/2019 10:44:50 AM - Execution started
4/25/2019 10:44:50 AM - ##Carga del archivo CSV: Running
4/25/2019 10:44:50 AM - Carga del archivo CSV : Success
4/25/2019 10:44:50 AM - Excel LoadCSV "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat: Running
4/25/2019 10:44:52 AM - Excel LoadCSV "C:\Users\martin.medina\Downloads\detracciones.csv" separated_by , as WBNameSunat : Success
4/25/2019 10:44:52 AM - Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat: Running
4/25/2019 10:44:52 AM - Excel LoadWSheet WBNameSunat sheet_index 1 as WSNameSunat : Success
4/25/2019 10:44:52 AM - ##Se escribe sobre el CSV, como si fuera una hoja de Excel normal: Running
4/25/2019 10:44:52 AM - Se escribe sobre el CSV, como si fuera una hoja de Excel normal : Success
4/25/2019 10:44:52 AM - Excel Write "CSV" in WSNameSunat cell A18: Running
4/25/2019 10:44:52 AM - Excel Write "CSV" in WSNameSunat cell A18 : Success
4/25/2019 10:44:52 AM - ##Se filtra sobre el CSV, como si fuera una hoja de Excel normal: Running
4/25/2019 10:44:52 AM - Se filtra sobre el CSV, como si fuera una hoja de Excel normal : Success
4/25/2019 10:44:52 AM - Excel ApplyFilter to the worksheet WSNameSunat to the column with the index {1} with the criteria "CSV": Running
4/25/2019 10:44:52 AM - Excel ApplyFilter to the worksheet WSNameSunat to the column with the index {1} with the criteria "CSV" : Success
4/25/2019 10:44:52 AM - Titanium Sleep 5000: Running
4/25/2019 10:44:57 AM - Titanium Sleep 5000 : Success
4/25/2019 10:44:57 AM - Excel LoadWBook "C:\Users\martin.medina\Downloads\otro.xlsx" as otrolibro: Running
4/25/2019 10:44:57 AM - Excel LoadWBook "C:\Users\martin.medina\Downloads\otro.xlsx" as otrolibro : Success
4/25/2019 10:44:57 AM - ##Se copia toda la hoja (datos visibles del CSV) a otro libro: Running
4/25/2019 10:44:57 AM - Se copia toda la hoja (datos visibles del CSV) a otro libro : Success
4/25/2019 10:44:57 AM - Excel CopySheet WSNameSunat to otrolibro as copiada: Running
4/25/2019 10:44:57 AM - Error CopySheet WSNameSunat to otrolibro as copiada
4/25/2019 10:44:57 AM - Excel CopySheet WSNameSunat to otrolibro as copiada : Error
4/25/2019 10:44:58 AM - Execution ended

No sé si será un problema de versiones de Turing o alguna configuración de la maquina. Podras darme una mano?

**Comment by RickProductivity** [comment]
Por que no hacen un Skype?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gantonioid** [comment]
Los nombres de las hojas deben de ser únicos... Si lo corres dos veces seguidas, la segunda fallará porque (en este ejemplo) se está creando una hoja con el nombre "copiada", si ya existe una hoja con ese nombre, la ejecución fallará.

Ya lo vimos en vivo y se explicó la razón del error. Tema cerrado.
