### ISSUE TITLE
[Excellia] - Se puede resolver el control de acceso a una web cuando se deben reconocer imagenes? Necesidad: Urgente

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#210]
Hola, en el día de hoy la página del SUNAT ( https://e-menu.sunat.gob.pe/cl-ti-itmenu/MenuInternet.htm ) agregó un nuevo control de acceso, requiere que se marque una casilla de seguridad que dice "no soy un robot" y luego se seleccionen unas imagenes, tal como se muestra en la imagen a continuación:

![image](https://user-images.githubusercontent.com/49758327/59702431-10a43c00-91ce-11e9-95c6-41d2ca381fa9.png)

Este cambio hace que un proceso que tenemos en producción no pueda ejecutarse. Les pido que le den prioridad.

Gracias

**Comment by gantonioid** [comment]
Se está revisando, pero es una mejora **MAYOR** va a requerir tiempo de desarrollo. @pabloreitanosofttek

**Comment by pabloreitanosofttek** [comment]
Me queda claro... entiendo por el hilo de teams que no es necesario resolverlo ASAP dado que es un cambio, pero seguro nos pedirán fecha y tiempos de compromiso... Porfa ponerlo en el roadmap y priorizarlo... De primer punto entender el tipo de cambio, como afecta a todo lo que ya tenemos (porque seguro requerirá deploy en PRD de Excellia) y conocer los tiempos de entrega. ¡Gracias!

**Comment by gantonioid** [comment]
@carlosortiz632 habló con @MartinMedinaSTK sobre una solución, en espera de resultados.

**Comment by MartinMedinaSTK** [comment]
@carlosortiz632 @gantonioid El miércoles estuve haciendo pruebas en mi maquina, de 6 de cada 10 veces terminaron con éxito. Hoy voy a estar subiendo la solución a la maquina virtual para que corra en producción. Luego les comento.
Gracias, saludos.

**Comment by MartinMedinaSTK** [comment]
@carlosortiz632 @gantonioid ya subí los cambios a la máquina virtual, el proceso corrió en automático resolviendo el captcha para las dos sociedades para las cuales se ejecuta el proceso.
Gracias 
Saludos
