### ISSUE TITLE
[TITAN]Apoyo para Filtrar por varias columas en un excel

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#211]
Buenas tardes

Se Require de su amable apoyo para filtrar un excel con 2 columnas, ya que se necesita que se filtre un excel por 2 columnas ( ejemplo filtrar por fecha y por local),  se ha implementado filtrar por una columna por un dato (local) y realizar un ciclo foreach  y dentro del ciclo un if con otra validación (fecha),  por temas de tiempo de ejecución esta opción no es optima ya que la automatización se esta demorando mas de lo que se haría manual y que los datos que se procesan son de gran cantidad.

se han utilizados WriteValueThatMatch, ApplyFilter, ReadColumn y todas utilizan solo un parámetro.
 
Agradezco por la atención prestada y estaré atento a cualquier comentario o sugerencia.

**Comment by rrrios** [comment]
se implemento el Filter  como se sugirió y funciono

pero la sentencia  WriteAll se puede usar como un copy range?
ya que requiero utilizar write en 6 columnas diferentes y al hacer el writeAll uno a uno se demora en tiempo de ejecución.

**Comment by gantonioid** [comment]
No sé a qué te refieres: "_como un copy range_" pero tiene una terminación de **-visible** para escribir solo en las celdas visibles de una columna filtrada.

Has pensado en usar `WriteFormula`? ella acepta rangos, y la fórmula que escribas puede ser un 
`=IF(algo, then, else)`

No tengo claro tu nuevo requerimiento pero... el tema del filtrado (el asunto original del ticket) ya se resolvió. ¿Puedes comentar al respecto?

**Comment by pabloreitanosofttek** [comment]
De acuerdo con @gantonioid … porfa abrir un ticket nuevo (Atento @rrrios  dado que el problema vino de la mano de no conocer la plataforma de manera entera)

**Comment by rrrios** [comment]
@FaustinoLechuga 
De acuerdo a lo solicitado, se da por cerrado el issue, ya que sé atendió el  requerimiento original y se implemento y cumple con lo que se había solicitado.
