### ISSUE TITLE
[TITAN][Excel] Convertir numero almacenado como texto, en numero

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#212]
Buenas, tengo el siguiente excel en el que las columnas vienen "numeros almacenados como texto" (como se puede ver en la imagen de abajo) y para poder operar con ellos necesito poder convertirlos en numero:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/49756974/59770059-b82c7780-927d-11e9-9655-be157f4ab422.png">

Para convertirlos manualmente debo hacer lo siguiente:
<img width="585" alt="image" src="https://user-images.githubusercontent.com/49756974/59770140-deeaae00-927d-11e9-98e7-e76c47827dc9.png">

para que finalmente queden de la siguiente manera:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/49756974/59770210-004b9a00-927e-11e9-81f0-b053623783d2.png">

Puedo lograr esto a traves de alguna instruccion?, las funciones de applyformat no funcionan ya que primero se Deben hacer esto pasos previos.
Les adjunto el excel para su analisis.

[Informe 06-06-2019; Prosegur.zip](https://github.com/FridaSupport/TuringSuport/files/3306336/Informe.06-06-2019.Prosegur.zip)

se agradece pronta respuesta.
muchas gracias.

**Comment by gantonioid** [comment]
Por qué el comentario de que no funciona ApplyFormat? tienes log de error o alguna info adicional?

**Comment by JuanIgnacioBurgos** [comment]
Al estar la celda guardada como "numeros almacenados como texto"  hasta que no se cambie esta condicion no se pueden aplicar otros formatos a la celde, lo probe de forma manual y Tambien a traves de FRIDA.

**Comment by JuanIgnacioBurgos** [comment]
Buscando en internet encontre un foro en el que explicaban qe una forma de resolver el problema era mediante una formula sumarle 0 al valor, haciendo esto la celda queda con formato de numero, les comparto el link por si en un futur0 alguien se encuentra con el mismo inconveniente:

https://excelyvba.com/convertir-texto-a-numero-en-excel/

Para resolverlo lo que hice fue:
1. Aplicar la suma de +0 a cada una de las celdas en la columna siguiente,.
2. Copiar los datos de una columna a la otra.
3. Eliminar la columna en donde se habian escrito las formulas.


Script:
```
DefineVariable type "List" as "CELDAs8"
Excel ReadColumn from the worksheet Hoja11 with the column index {6} and save its value as {CELDAs8}
DefineVariable type "string" as "posicion8" with the value "0"
foreach CELDA8 in CELDAs8 {
MathOperation <<<posicion8>>> + 1 and save as posicion8
Excel WriteFormula Hoja11 in G<<<posicion8>>> formula =F<<<posicion8>>>+0
}
SystemNotify Type "notification" with message "se aplico formula en columna G"
Excel CopyRange from the worksheet Hoja11 from the cell {2,7} up to the cell {<<<posicion8>>>,7} to the cell {2,6}
SystemNotify Type "notification" with message "se copio de la columna G a la F"
Excel RemoveCols from Hoja11 at [7]
SystemNotify Type "notification" with message "se elimimno la columna con las formulas"
```
Cierro issue, quizas se pueda ver la forma de hacer esto con una sola instruccion, pero lo dejo a modo de mejora.
Saludos.

**Comment by FaustinoLechuga** [comment]
Hola @JuanIgnacioBurgos veo que estas usando el foreach para llenar las celdas del excel y esto esta bien pero si el archivo es muy largo va a tomar mucho tiempo llenar el excel por lo que te informo que la instrucción de WriteFormula acepta rangos y esto haria mas rapida la ejecución. Te dejo el link para que veas algunos ejemplos.

[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteFormula](url)

En caso que la formula no sea igual para cada celda se puede escribir la formula en una celda y luego autollenar la columna con la instrucción auto fill, aqui te dejo el link.

[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/AutoFill](url)

**Comment by gantonioid** [comment]
@JuanIgnacioBurgos @pabloreitanosofttek  ven esto como material de wiki?

**Comment by pabloreitanosofttek** [comment]
Urgente a la wiki @JuanIgnacioBurgos !

**Comment by JuanIgnacioBurgos** [comment]
Listo, ya se encuentra en la wiki.

**Comment by gantonioid** [comment]
Lo que pones asumo que es como lo resolviste finalmente en tu caso, pero recomiendo que se modifique para mejorar el performance con la sugerencias de Faustino.


> Hola @JuanIgnacioBurgos veo que estas usando el foreach para llenar las celdas del excel y esto esta bien pero si el archivo es muy largo va a tomar mucho tiempo llenar el excel por lo que te informo que la instrucción de WriteFormula acepta rangos y esto haria mas rapida la ejecución. Te dejo el link para que veas algunos ejemplos.
> 
> [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteFormula](url)
> 
> En caso que la formula no sea igual para cada celda se puede escribir la formula en una celda y luego autollenar la columna con la instrucción auto fill, aqui te dejo el link.
> 
> [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/AutoFill](url)

De cualquier manera, gracias por la contribución
