### ISSUE TITLE
Problemas nueva Version Turing Valorem - Ayuda Urgente

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#213]
Buenos días, su ayuda para que se solucione el problema que se presenta con Turing desde el día Lunes, se han tenido varios fallos del sistema BW de Cadenas y el cliente me esta preguntando por que el bot no esta probándose para que ejecute su cometido.

Cuando ejecuto turing me indica si quiero actualizar, como primera opción le indico que si:

![error_01](https://user-images.githubusercontent.com/14879161/59773865-fc1a7f00-9273-11e9-9b7e-dafa0a9f5a94.png)

reviso los procesos y no carga ninguno.

![error_04](https://user-images.githubusercontent.com/14879161/59773903-0b99c800-9274-11e9-8454-677510e12975.png)

entonces nuevamente ejecuto Turing y ahora le indico que no actualice nada y al parecer carga los procesos pero al dar click en cualquier Area Turing deja de funcionar.

![error_02](https://user-images.githubusercontent.com/14879161/59774005-46036500-9274-11e9-8482-4d058a23744b.png)

![error_03](https://user-images.githubusercontent.com/14879161/59774009-4865bf00-9274-11e9-8c78-f4499fb8a2b9.png)

Mientras se soluciona esto podrían bajarle la versión al Turing de Valorem? La que tenia antes no presentaba este problema.

Gracias

**Comment by andresCruzF** [comment]
Hola @carlosgiraldo 

Me podrías confirmar con que usuario se encuentra configurado este Turing , ya sea con el de "valorem.colombia@softtek.com" o con el de "carlos.giraldo@softtek.com". Así mismo me gustaría saber si este es un Turing offline o online. De maner similar empiezo a revisar el problema.

Saludos.

**Comment by gantonioid** [comment]
Es online a nombre de valorem.colombia. Tenía antes la versión 20190402T1258 y le envié update para que tenga la que tengo yo (20190611T0141)

Esto para que valorem incluya el monitor de errores y la reconexión automática del Turing Listener.

**Comment by carlosgiraldo** [comment]
Gracias @gantonioid , quedo atento a información que les pueda proporcionar.

**Comment by pabloreitanosofttek** [comment]
¿Que avances hay? @FridaSupport

**Comment by andresCruzF** [comment]
Hola @pabloreitanosofttek  y @carlosgiraldo 

Se acaba de enviar un update que soluciona este problema.

ID=20190619T0852 

Saludos , estamos al pendiente

**Comment by pabloreitanosofttek** [comment]
@carlosgiraldo porfa confirmar que funcionó o bien comentar con @andresCruzF a ver que solución podemos pensar... el cliente nos ha puesto una multa por este error. 

¡gracias!

**Comment by carlosgiraldo** [comment]
Buenas Tardes, Disculpen la demora en la prueba pero desde ayer estaba visitando clientes y no estaba en la oficina, ya realice la prueba pero de nuevo fallo la ejecución.

 @andresCruzF  si necesita que hagamos una llamada para revisarlo me dice y revisamos el tema.

![error_05](https://user-images.githubusercontent.com/14879161/59878791-cf975d80-936e-11e9-926c-481eb3b47807.png)


gracias por la ayuda.

**Comment by pabloreitanosofttek** [comment]
@gantonioid @andresCruzF  se está tornando clave resolverlo... ¡gracias!

**Comment by carlosgiraldo** [comment]
Buenas Tardes, por favor cerrar el caso, la solución fue borrar los archivos de la carpeta: App\RememberMeLog

Ya el Turing quedo operando correctamente.

![OK](https://user-images.githubusercontent.com/14879161/59953571-52d7b280-9446-11e9-8824-2eda2bc0a5b1.png)

Gracias.

**Comment by gantonioid** [comment]
Súper, muchas gracias
