### ISSUE TITLE
[TITAN]ApplyFormat  no aplica formato de fecha en tiempo de ejecucion 

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#215]
Buenos Dias

Se esta aplicando un formato de fecha a una columna antes de aplicarle un filtro y guardarla en una variable. pero al recorrer la variable en un foreach y buscar la columna con la fecha, esta trae el dato en formato de texto.

se adjunta los insumos
[Copia de Consolidado pendientes MARZO.xlsx](https://github.com/FridaSupport/TuringSuport/files/3306836/Copia.de.Consolidado.pendientes.MARZO.xlsx)
[reproceso.xlsx](https://github.com/FridaSupport/TuringSuport/files/3306837/reproceso.xlsx)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3306843/codigo.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3306845/log.txt)

Agradezco por la atención prestada

**Comment by FaustinoLechuga** [comment]
Esta problemática se resuelve utilizando la instrucción:
Excel DateFormat ShExReproceso column_index 1 source "dd/MM/yyyy" string("dd/MM/yy")

y quitando esta instrauccion:
Excel ApplyFormat from ShExReproceso in_column_index 1 format dd/MM/yyyy

FYI:
La instrucción DateFormat lo que hace es pasar el valor tipo date a un valor tipo texto lo que permite poder comparar valor sin inconveniente.

Quedo al pendiente.

**Comment by pabloreitanosofttek** [comment]
@FaustinoLechuga no me termina de quedar claro si fue una solución de código o de entendimiento de la plataforma.... ¿Me aclaras? 
¡gracias!

**Comment by rrrios** [comment]
saludos @FaustinoLechuga 

Se atendió la sugerencia y se realizo la prueba unitaria con el ejemplo que pusiste,  el caso es exitoso para lo que se requiere.

Agradezco por el apoyo brindado.

**Comment by FaustinoLechuga** [comment]
Perfecto, respondiendo a tu pregunta @pabloreitanosofttek fue un error de confusión ya que la instrucción que se sugirió ya había sido creada para resolver este tipo de problemáticas.
