### ISSUE TITLE
[TITÁN] [Excelium] - Hoja protegida.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#216]
El cliente me proporcionó un nuevo archivo excel el cual cuenta con una hoja protegida. El asunto es que cuando intento hacer un "Copy values" desde otra hoja el proceso rompe. 

Este es el log correspondiente: [log.txt](https://github.com/FridaSupport/TuringSuport/files/3306677/log.txt)
Este es el código que ejecuté: [Código.txt](https://github.com/FridaSupport/TuringSuport/files/3306792/Codigo.txt)
Este es el archivo: [Planilla ADI.zip](https://github.com/FridaSupport/TuringSuport/files/3306875/Planilla.ADI.zip)

Si ejecuto el mismo proceso con el excel desprotegido que usaba anteriormente no tengo dicho problema. Anterior excel: [Planilla ADI (buena).zip](https://github.com/FridaSupport/TuringSuport/files/3306910/Planilla.ADI.buena.zip)

Entiendo que es engorroso este proceso y como no puede simular el error por separado para mostrarles un código más sintético considero que lo más adecuado sería hacer un a call y mostrarles el problema en vivo.

Necesito una solución lo antes posible. Quedo a su disposición.

+@pablorlmx

**Comment by gantonioid** [comment]
Que yo recuerde no hemos trabajado con hojas protegidas... Tienes la contraseña para _desprotegerla_?

**Comment by CesarEmanuelLencina** [comment]
@gantonioid Como le comenté por teams a @JuanISalazarM esta ADI no usa contraseña.

Dicho al paso también actualizo: le he proporcionado a JuanISalazarM los otros archivos requeridos e imágenes para que pueda correr el proceso. En estos momentos se está revisando el problema.

**Comment by pabloreitanosofttek** [comment]
@gantonioid  te pido sacar el label de "pending input" porque fueron entregados. 
¡gracias!

**Comment by CesarEmanuelLencina** [comment]
Actualizo: Ya se me dió una posible solución, durante el día estaré corriendo pruebas e informaré los resultados.

**Comment by CesarEmanuelLencina** [comment]
Pese a no haber una instrucción en Excelium para desproteger una hoja, la solución de utilizar Titanum luego de abrir el archivo con Excelium para hacer click en el botón _Desproteger hoja_ ha funcionado correctamente. 

Gracias @JuanISalazarM. Se puede cerrar el problema.

**Comment by JuanISalazarM** [comment]
Para servir. Que tenga un excelente día.

**Comment by gantonioid** [comment]
Aún así ves posible hacer una función de Excelium? @JuanISalazarM
