### ISSUE TITLE
[TITAN] Tomar variables del cuerpo de mail

### ISSUE THREAD

**Issue by FacundoButron** [FridaSupport/TuringSuport#217]
Es posible capturar variables desde el cuerpo del mail ? 

El cliente nos pide que se ejecute un proceso, a partir de la llegada de un correo. En el correo en cuestión se envían ciertos datos, que deben ser capturados para ser luego llevados a otro sistema como input. 

Hay forma de hacer esto?

![image](https://user-images.githubusercontent.com/52009201/59788623-824dba00-92a2-11e9-9394-d59778834cdc.png)

Mil Gracias!

**Comment by gantonioid** [comment]
Es posible, pero hemos estado usando Microsoft Flow para eso, sobre todo si los correos vienen con ese formato bastante _legible_ con regex o tablas, etc. Ver la documentación en la wiki para llamar procesos remotos con Flow.

[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Remoto%20y%20Scheduling.one%7C21c7d51f-bc2f-4d07-9e52-ba06e3cee982%2FLlamando%20un%20proceso%20desde%20Flow%7Cb83c50b0-d334-45d4-b2f3-8b4314bf4053%2F%29&wdorigin=703](url)

**Comment by gantonioid** [comment]
Se dio respuesta y link a documentación.
