### ISSUE TITLE
[TITAN]COUNT para Frida

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#218]
Buenas tardes

El presente es para solicitar información o la implementación de una sentencia COUNT, ya que con anterioridad se había preguntado y en el momento no estaba desarrollada. Se requiere ya que para la implementación que se esta realizando, el sistema necesita saber cuantos registros ah procesado, para luego insertarlo en un excel como resumen.

Agradezco por la atención prestada y el pronto apoyo, por que el proyecto esta en etapa QA se tiene que entregar a mas tardar el día viernes 21 de junio a mas tardar

**Comment by Johhnn117** [comment]
Muy bien, te contacto por Teams

**Comment by gantonioid** [comment]
Código:
```
AddToList "lista" value "v1"
AddToList "lista" value "v2"
AddToList "lista" value "v3"
AddToList "lista" value "v4"
CountItems in lista and save_as elementos
Message <<<elementos>>>
Titanium Sleep 5000 
```
arroja count de 4
Codigo:
```
DefineVariable type "string" as "lista" with the value "dadada"
CountItems in lista and save_as elementos
Message <<<elementos>>>
Titanium Sleep 5000 
```
Arroja count de 6


Esta nueva función soporta listas, diccionarios y strings

**Comment by gantonioid** [comment]
para seguimiento @Johhnn117

**Comment by rrrios** [comment]
se obtuvo version y se implemento con lo sugerido en el git y quedo funcionando para lo que se requería

agradezco por la atención de la solicitud y la prontitud de la respuesta..
