### ISSUE TITLE
[Excellia] - Aparición de ventana emergente solo en ejecución de bot.

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#219]
Buenas tardes ¿ cómo estan? , me sucede que al ejecutar el bot de Registro de Cobranzas en un determinado momento aparece una ventana emergente de publicidad(es la adjunta en la línea de abajo). y el bot falla ya que deja de realizar las acciones que deberia hacer.
![imagen](https://user-images.githubusercontent.com/50331739/59941599-f10e4d00-9433-11e9-960f-2f398182a5f8.png)
¿cómo hago para cerrar esa ventana si aparece? porque no aparece siempre, es más de manera manual no me aparece. Solo al ejecutar el proceso sucede.

**Comment by carlosortiz632** [comment]
Hay un momento específico en el cual esta ventana aparece? Si sí, hay manera de poder cerrar esa ventana emergente. Solo hay que saber dónde poner la instrucción

**Comment by MarianelaDuarte** [comment]
Si, aparece cuando esta haciendo los pasos para entrar a descargar un archivo, no sé si s porque el bot demora más pero no llega a completar toda la secuencia que se abre esa ventana y en consecuencia tira error.

**Comment by pabloreitanosofttek** [comment]
@carlosortiz632 @MarianelaDuarte  ¿Cuál es status? ¡gracias!

**Comment by MarianelaDuarte** [comment]
sigue sucediendo el mismo problema, pero como estoy con varios bot a la vez. No lo estoy ejecutando a ese bot.

**Comment by pabloreitanosofttek** [comment]
OK, @carlosortiz632  porfa dale soporte en cuanto puedas. ¡gracias!

**Comment by carlosortiz632** [comment]
Hola @MarianelaDuarte, puedes cerrar la ventana con las siguientes instrucciones

```
Web2 SwitchPage Last
Web2 CloseTab
Web2 SwitchPage Main
```

Saludos.

**Comment by MarianelaDuarte** [comment]
Hola Carlos, voy a tratar de subir un video para que puedan ver el comportamiento, intente con la solución que mencionas, pero el problema es que no siempre aparece en el mismo momento, habria que poner como un condicional "si aparece la ventana cerrar", porque yo puse la intruccion y a veces coincide con la aparición pero otras no, y falla.

**Comment by pabloreitanosofttek** [comment]
@MarianelaDuarte  lo subiste? ¡gracias!

**Comment by MarianelaDuarte** [comment]
Subido al Teams! Saludos.

**Comment by MarianelaDuarte** [comment]
Disculpen este issue ahora tiene prioridad alta, @FridaSupport  alguien puede revisarlo?
Subi video en el Teams
https://teams.microsoft.com/l/message/19:cd9528b2e6604acf8bf35c51657d8525@thread.skype/1562004694200?tenantId=864ee999-c538-44a0-bddd-0449de62df6d&groupId=0d5132ed-7582-417f-8a6c-63e895ec18b2&parentMessageId=1562004694200&teamName=Desarrollo%20FRIDA&channelName=Soporte&createdTime=1562004694200

**Comment by MarianelaDuarte** [comment]
Buenas tardes Carlos, ayer probe la solución mencionada en Teams y no resuelve el problema, y BCP tiene la particularidad de que se expira la sesión en cuestión de segundos. Pero logro sacar el cartel varias veces, porque vi que varias veces se hace en cuando esta en determinado paso, pero igual no funcion ya que despues no encuentra el id siguiente, entonces realice que haga los pasos de nuevo y chan, vuelve a salir la ventana. Es un ciclo repetitivo.

**Comment by raulpoltiSTK** [comment]
@FridaSupport Necesitamos darle un cierre a este tema de forma urgente para poder entregar el Bot que el cliente nos viene reclamando. Favor de dar prioridad. Gracias.

**Comment by MarianelaDuarte** [comment]
Buenas tardes @FridaSupport  ¿alguna novedad de este issue? Necesito dar por cerrado el BOT y esa ventana emergente me lo impide.
Saludos

**Comment by pabloreitanosofttek** [comment]
@FridaSupport  @gantonioid  ¿Como venimos? ¡gracias!

**Comment by raulpoltiSTK** [comment]
@FridaSupport @gantonioid Buenas, tenemos alguna novedad? Necesitamos dar un cierre a este tema. Gracias.

**Comment by raulpoltiSTK** [comment]
@FridaSupport @pabloreitanosofttek @RickProductivity No estamos recibiendo respuesta! Alguien nos puede ayudar?

**Comment by carlosortiz632** [comment]
Existen las instrucciones para cerrar la ventana, las cuales ya fueron proporcionadas. No hay manera de detectar cuándo aparezca la ventana, por lo cual se deberá hacer una lógica extra para ejecutar estas instrucciones dentro de un `try/catch` donde se crea que puede aparecer la ventana.

**Comment by MarianelaDuarte** [comment]
Lo realice pero sigue apareciendo, por ende se vuelve un bucle sin fin. Porque la cierro, se hacen los pasos de nuevo, aparece de nuevo y asi sucesivamente.

**Comment by gantonioid** [comment]
- Si le das click al boton de cerrar en vez de cerrar la vetnana directamente, se comporta diferente?
- Ya intentaste ignorar la ventana y continuar con el proceso? solo asegúrate de que **el foco lo tengamos en la ventana principal**. Eso lo puedes hacer con `Web2 SwitchPage Main` en el momento en el que detectes que sale la nueva ventana.

A menos que FRIDA termine con error, no creo que haya mucho que hacer del lado de soporte, ve qué otras instrucciones puedes usar en combinación con estructuras lógicas y si hay error en el LOG, nos reportas para ayudarte.

@carlosortiz632 tienes algún otro comentario?

**Comment by gantonioid** [comment]
Cerrado por inactividad posterior a las alternativas presentadas.
