### ISSUE TITLE
Excel RangeDelete

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#22]
Buen día, estoy teniendo un inconveniente con la instrucción RangeDelete. 
En el LOG aparece:
25/4/2019 12:44:45 - Error: RangeDelete from hoja2 in B7:C22
25/4/2019 12:44:45 - Error in rangedelete Instruction was't found
25/4/2019 12:44:45 - Error in rangedelete Instruction was't found
25/4/2019 12:44:45 - Excel RangeDelete from hoja2 in B7:C22 : Error

En DOCUMENTATION el comando figura así:
![RangeDelete](https://user-images.githubusercontent.com/49987311/56750058-56f29700-6759-11e9-995d-661ed5766eb2.jpg)

La línea de código que uso en Turing es:
Excel LoadWBook "C:\Users\martin.olmedo\Desktop\Control Carga de Horas.xlsx" as libro2
Excel LoadWSheet libro2 sheet_index 1 as hoja2
Excel RangeDelete from hoja2 in B7:C22

Necesito usar esta instrucción porque quiero borrar los datos de una lista para poder actualizarlos. Probé con RemoveRows y no sirve para lo que necesito porque borra datos de la columna A (que esta oculta) que necesito. Lo mismo con RemoveCols.

Muchas gracias.

**Comment by FaustinoLechuga** [comment]
Ya se resolvio, podrias probar de nuevo esa intruccion? Solo hay que actualizar Frida que es cerrandolo y volviendolo a abrir.

**Comment by MartinJOlmedo** [comment]
Si, funciona perfecto. Muchas gracias!
