### ISSUE TITLE
Consulta. BrowPet. Comportamiento Extraño

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#220]
Al  momento de escribir valores tomados de un excel con la instruccion insertvalue en la pagina https://www1.oanda.com/lang/es/fx-for-business/historical-rates en el apartado del calendario, en los atributos datepicker-start-date y datepicker-end-date. Por mas que se escriban correctamente en la corrida, una vez hecho el click en el boton apply, la pagina cambia a la fecha actual el apartado de end-date, provocando datos incongruentes. Adjunto en teams dejo un video con el proceso corriendo donde se detalla mejor
[CalendarioC.xlsx](https://github.com/FridaSupport/TuringSuport/files/3315743/CalendarioC.xlsx)
[calendarioscp.txt](https://github.com/FridaSupport/TuringSuport/files/3315745/calendarioscp.txt)

Necesidad: Alta
Prioridad: Alta

**Comment by carlosortiz632** [comment]
Coloca esta instrucción justo después de que ingresas las dos fechas. Esto hará que el componente se refresque y te dé la fecha correcta.

`Web2 Click in id="datepicker-obj-container"`

**Comment by jaristimuno** [comment]
Perfecto. Gracias
