### ISSUE TITLE
[TITAN]hay alguna forma de saber el row exacto? 

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#221]
Buenas tardes

se requiere saber el row exacto de un excel el cual se le han aplicado unos filtros, pero buscando en las variables que retornan algunas sentencias, no se ha podido ver el row exacto que se esta utilizando,
 se requiere tener el row exacto para utilizar la sentencia de BackgroundColor. que solicita el row exacto para ejecutar la instrucción y en tiempo de ejecución se desconoce.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/50424090/59949160-ee155b80-9437-11e9-9d0a-2ef6776cdcb0.png">
y se esta utilizando el
Excel BackgroundColor from {ShExConPenAvantis} row {169} start_at {1} to {yellow} 

Agradezco por la atención prestada y estaré atento a cualquier sugerencia.

**Comment by gantonioid** [comment]
Cómo filtraste? ReadValueThatMatch regresa un diccionario de <fila, valor>
Piensas iterar fila por fila para aplicar el BackgroundColor?

Esta misma función sirve para colorear las celdas visibles después de filtrar.

@FaustinoLechuga

**Comment by rrrios** [comment]
se filtro con Excel Filter , ya que se requiere que se haga mas de un filtro, al realizar varios filtros solo va quedar una fila, por eso es la consulta de como se puede saber la fila para este caso, el ReadValueThatMatch es una buena opción, pero el no trabaja con multiple filtros. por eso no se utilizo. o que otra se puede usar, por que el filter no se si guarde en variables lo que ejecuto.

agradezco por la atención prestada.

**Comment by pabloreitanosofttek** [comment]
@rrrios  ¿Está para cerrar este ticket? ¡gracias!

**Comment by FaustinoLechuga** [comment]
Se mandaron lineas de código que deben de solucionar la problemática, en espera de confirmación sobre el funcionamiento.

**Comment by pabloreitanosofttek** [comment]
Ok, gracias... @rrrios ?

**Comment by rrrios** [comment]
saludos
se implemento lo sugerido por @FaustinoLechuga y funciono como lo  había sugerido, pero hay un problema con GetSpecial lastRow from wsheet and save as LRowproblema  ya que esta sentencia trae la ultima celda del excel así este oculta,  y lo que se requiere es que traiga la ultima celda visible en el excel,  Para este caso no se si haya otra sentencia que haga lo que se requiere o haya otra forma de implementar eso.

agradezco por la atención prestada y estaré atento a cualquier duda, inquietud, sugerencia.

**Comment by pabloreitanosofttek** [comment]
¿Viste este ticket @ClaudioRodolfoGarcete? Sería bueno que puedas aportar desde la experiencia.

¡gracias!

**Comment by rrrios** [comment]
se tuvo una call con @FaustinoLechuga  y se verifico remotamente en tiempo de ejecución, la sugerencia del código que se tenia que implementar. se realizaron pruebas unitarias con la automatización completa. y funciono. dado por cerrado el issue
