### ISSUE TITLE
[TITAN] Copiar proceso en turing del cliente.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#222]
Buen dia,

necesitamos copiar el siguiente proceso en el turing del cliente TITAN.

Nombre responsable: Cristian Fabio Celano
Nombre del proceso: RipleyPrueba
ID del proceso: 462026834

Necesidad: Urgente.

@andresCruzF

**Comment by Johhnn117** [comment]
@ClaudioRodolfoGarcete listo, ya se copió el proceso al Turing de TITAN

**Comment by gantonioid** [comment]
Aquí indican que el proceso se llama RipleyPrueba, están seguros que quieren agregarlo así (No parece adecuado) ?
Es Turing online/offline? Ya lo vieron con @Johhnn117 ?

**Comment by CristianCelano** [comment]
Ya cree un proceso con un nombre mas adecuado.
Nombre responsable: Cristian Fabio Celano
Nombre: Conciliacion Ripley
ID: 1946866900

Gracias.

**Comment by Johhnn117** [comment]
Se compartió Turing Offline con el proceso 1946866900 a @CristianCelano por Teams
