### ISSUE TITLE
Turing se cierra de manera aleatoria

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#223]
Buen día! 
Me emepezó a pasar hoy (24/06) lo siguiente: cuando quiero correr un script se cierra Turing sin dar error. Sucede con una frecuencia de 1 cada 4 o 5 veces que le doy Start (después de Run). La versión que tengo es 20190506T1048 y el script que quiero correr empieza así:

GetCurrentDate Month and save as Mes
GetCurrentDate Day and save as Dia
GetCurrentDate Year and save as Anio
SAP RunSapInstance ".........

Los datos de Log muestran lo siguiente: 
![TURING](https://user-images.githubusercontent.com/49987311/60028645-18545c80-9676-11e9-9996-6284d5c42eef.jpg)

Muchas gracias!

**Comment by andresCruzF** [comment]
Hola @MartinJOlmedo 

Este es un error con las librerias de SAP el cual podemos evitar agregando la palabra "graphic" en la sintaxis de RunSapInstance para evitar que succeda.

RunSapInstance "CC DEV" 010 <<SapUsr>> <<SAPPwd>> ES graphic

Saludos.

**Comment by MartinJOlmedo** [comment]
Si, puede ser. No estaba poniendo GRAPHIC al final. Lo voy a implementar hoy y si no vuelve el error, cierro el issue.
Muchas gracias!

**Comment by MartinJOlmedo** [comment]
Confirmo la solución del issue. Muchas gracias!
