### ISSUE TITLE
[EXCELLIA] "Problema" en SAP ClickGridToolBtn

### ISSUE THREAD

**Issue by Josecamats** [FridaSupport/TuringSuport#224]
@eradgg 
Buenos dias!
Tengo una consulta sobre un "problema" que estoy teniendo, quiero darle click al boton de exportar en una grilla de SAP y al hacerlo con turing me lo marca en azul pero no abre ninguna opcion.
--------------------------------------------------------------------------------------------------------
Con turing:
![Error](https://user-images.githubusercontent.com/50020196/60101734-ad1c9000-9732-11e9-817f-7d67aefae4c2.png)
-------------------------------------------------------------------------------------------------------
Manualmente: 
![Normalmente](https://user-images.githubusercontent.com/50020196/60102013-3df36b80-9733-11e9-8d67-e5f9ea1a4368.png)
-------------------------------------------------------------------------------------------------------
Log:
6/25/2019 10:11:54 AM - SAP ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&MB_EXPORT": Running
6/25/2019 10:11:55 AM - SAP ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&MB_EXPORT" : Success
--------------------------------------------------------------------------------------------------------
Script:
SAP ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&MB_EXPORT"
--------------------------------------------------------------------------------------------------------

Vi en la documentacion que hay una instruccion para exportar directamente, no tengo claro como funciona.

**Comment by eradgg** [comment]
Hola José.

Muchas veces cuando buscamos el context menu no activa el padre, trata usando el mismo ClickGridToolBtn pero directamente a "Hoja de cálculo" o la opción que quieras activar.
saludos.

**Comment by Josecamats** [comment]
Hola Eder!
Traté de esta forma y me dio error:
SAP ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&XXL"
-------------------------------------------------------------------------------------------------------------
Log:
6/26/2019 12:22:23 PM - SAP ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&XXL": Running
6/26/2019 12:22:23 PM - error: ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&XXL" : System.ArgumentException
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.ISapGridViewTarget.PressToolbarButton(String Id)
   at SapScriptReader.SapScriptExecute.ClickGridToolButton(String GridId, String ButtonId) in C:\Users\faustino.villarreal\source\repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 3153
   at SapScriptReader.SapScriptExecute.ClickGridToolBtn(String action) in C:\Users\faustino.villarreal\source\repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 2914
6/26/2019 12:22:23 PM - SAP ClickGridToolBtn GridId wnd[0]/usr/cntlCC_DATA/shellcont/shell ButtonId "&XXL" : Error

**Comment by eradgg** [comment]
Me puedes contactar por Skype para revisarlo_
gracias.

**Comment by eradgg** [comment]
ya vi cual es el error.
El primero si es un botón, pero para acceder a las opciones ahí ya son context menu. usa la instrucción:
SelectContextMenu 
de ls siguiente manera:
SAP SelectContextMenu id /app/con[0]/ses[0]/wnd[0]/usr/cntlCC_DATA/shellcont/shell &XXL
Aa hice el cambio en tu script.

**Comment by Josecamats** [comment]
Funciona bien así.
Muchas gracias Eder!
