### ISSUE TITLE
[Excellia] Context realiza clic fuera del contexto. Urgente.

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#225]
Se realiza el context para obtener el nombre de una columna y seleccionar la casilla para descarga de la otra.
El nombre lo obtiene correctamente pero la selección, siempre toma el primer elemento de la lista.

Se necesita solución para el día de hoy,

![image](https://user-images.githubusercontent.com/25591982/60103694-721c5b80-9736-11e9-84b0-ed0a78c3f945.png)

Archivo que descargó
![image](https://user-images.githubusercontent.com/25591982/60104092-23bb8c80-9737-11e9-81ae-afa6e85476cf.png)

![image](https://user-images.githubusercontent.com/25591982/60104144-3b931080-9737-11e9-893f-544896e35aae.png)

Log
```
25/06/2019 10:31:54 - Web2 In Context of dynamic=".SMM": Running
25/06/2019 10:31:55 - Web2 In Context of dynamic=".SMM" : Success
25/06/2019 10:31:55 - Web2 sleep 30000: Running
25/06/2019 10:32:25 - Web2 sleep 30000 : Success
25/06/2019 10:32:25 - Web2 Extract from selector="td:nth-child(3)" save as "NombreArchivoDescarga": Running
25/06/2019 10:32:26 - Se actualizo la variable : 
Var Name : NombreArchivoDescarga
Value : 010519_290519_300519_114510465.SMM
25/06/2019 10:32:26 - Web2 Extract from selector="td:nth-child(3)" save as "NombreArchivoDescarga" : Success
25/06/2019 10:32:26 - Web2 Click in selector="tr.nw > td > label > i": Running
25/06/2019 10:32:26 - Web2 Click in selector="tr.nw > td > label > i" : Success
25/06/2019 10:32:26 - Web2 EndContext: Running
25/06/2019 10:32:27 - Web2 EndContext : Success
```
>

**Comment by carlosortiz632** [comment]
Puedo yo acceder a la página? Será más fácil para que pueda debuggearlo.

**Comment by SoledadNunez** [comment]
La verdad que no, esta es la pagina que se bloqueo varias veces,  es la misma instrucción que vimos hace unos días atrás que seleccionaba el todos en vez del registro del contexto, por si eso ayuda.

Lo que podemos hacer es una reunión y te muestro como funciona.

**Comment by carlosortiz632** [comment]
Podrías utilizar esta instrucción para dar el click?

`Web2 Click in selector="td > label > i"`

De todos modos, ya te contacté por skype para tener una sesión remota

**Comment by SoledadNunez** [comment]
Selecciona todos los registros en vez de solo el del contexto

**Comment by pabloreitanosofttek** [comment]
¿Y entonces?

**Comment by SoledadNunez** [comment]
Estamos todavía probando distintas opciones y distintos desarrollos, en un momento vamos a hacer una call, porque ya no sabemos por donde solucionarlo.
No lo pueden debuggear, porque cada vez que lo hacen se bloquea el usuario.

**Comment by pabloreitanosofttek** [comment]
@carlosortiz632 @gantonioid  ¿Como venimos? ¿Que fecha tiene de cierre? 

¡Gracias!

**Comment by SoledadNunez** [comment]
ya esta funcionando, muchas gracias.
