### ISSUE TITLE
Logs ejecución Remota Turing Valorem

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#226]
Buenos días, pueden ayudarme con los logs de ejecución de las siguientes tareas:

ProcessID: cadenasbw1772122536
TaskID:1880155293

ProcessID: cadenasbw1772122536
TaskID:1117283237

Gracias.

**Comment by gantonioid** [comment]
Se pueden revisar los logs en la máquina ejecutora, @carlosgiraldo comentaste que ibas a hacer un script para archivarlos en otra ubicación y que no fueran reemplazados en cada ejecución.

No se atiende este ticket.
