### ISSUE TITLE
[TITAN] TuringExpo expuesto como Malware.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#227]
El cliente detecto con su antivirus a TuringExpo como Malware, necesitamos saber cuales podrian ser los motivos.

@gantonioid

**Comment by andresCruzF** [comment]
Hola @ClaudioRodolfoGarcete 

Me podrías confirmar el nombre del antivirus que presenta este problema al igual que el nombre del ejecutable que esta siendo detectado como malware, así mismo me podrías confirmar si se cuentan con mayor detalle del problema, con anterioridad se ha presentado este problema en PUMBA.exe, la razón por la cual se presentó este problema fue debido al uso de la librería Fody y Costura Fody que nos permite incorporar los dlls al compilado .exe de TuringExpo , lo que nos ayuda a retirar la dependencia que existe entre el código y sus subcomponentes.

![image](https://user-images.githubusercontent.com/49708627/60195856-88dbb480-9801-11e9-88e2-a64d21d5c67d.png)

**Comment by andresCruzF** [comment]
https://github.com/Fody/Fody
https://github.com/Fody/Costura

**Comment by ClaudioRodolfoGarcete** [comment]
Hola @andresCruzF 

Te paso la info que nos brindo el cliente:

Datos servidor COR4572V:

![image004](https://user-images.githubusercontent.com/33100638/60197593-0ad5d880-9816-11e9-8d4f-80cad6d7cd3a.png)

Informe de amenaza:

![image005](https://user-images.githubusercontent.com/33100638/60197209-5b006b00-9815-11e9-95ea-248aa6c8aded.png)

De acuerdo al informe de amenaza, el nombre del antivirus es SEP:

![aaaaaaaaaaa](https://user-images.githubusercontent.com/33100638/60197972-ea5a4e00-9816-11e9-8ee8-30343e029713.png)


Para mayor detalle deberiamos coordinar una reunion @pablorlmx

**Comment by pabloreitanosofttek** [comment]
@andresCruzF  @gantonioid ¿Les falta algo de información o con lo compartido está OK?
¡gracias!

**Comment by gantonioid** [comment]
Según yo Andrés contestó en su comentario. Resumen: Usamos una librería que ayuda a empaquetar la aplicación en tiempo de compilación para que se produzcan menos archivos dentro de la carpeta de App
![image](https://user-images.githubusercontent.com/9600868/60278276-c2292880-98c4-11e9-8a0e-665657aa1c7e.png)

En el pasado hemos identificado un par de situaciones en los que el antivirus bloquea la aplicación y llegamos a la conclusión de que es por esta librería.

**Comment by gantonioid** [comment]
@pabloreitanosofttek Se responde la pregunta/necesidad?

**Comment by pabloreitanosofttek** [comment]
@pablorlmx @ClaudioRodolfoGarcete  porfa validen la respuesta (o no y re-pregunten) y comuniquen al cliente. ¡gracias @gantonioid!

**Comment by pabloreitanosofttek** [comment]
Está OK, cerrar ticket. ¡gracias!
