### ISSUE TITLE
Consulta Browpet/Excel

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#228]
Disculpa, se envio antes de completar.

Deseo capturar la tabla completa de valores y escribirlas en un excel, 

![image](https://user-images.githubusercontent.com/49946883/60276260-a5dfb880-98d1-11e9-9f5e-9cf5741099ee.png)

Probé extrayendo el selector de dicha tabla y escribir el selector en excel pero da error. Hay manera de capturar todos los valores y despues escribirlos?

**Comment by gantonioid** [comment]
??

**Comment by gantonioid** [comment]
Dónde está el error? qué material nos puedes dar para ayudarte?
Error en la captura de los elementos de la tabla?
Error en la escritura del Excel?

**Comment by jaristimuno** [comment]
El error vendria siendo al momento de escribir la tabla en excel

[ERROR.txt](https://github.com/FridaSupport/TuringSuport/files/3335339/ERROR.txt)

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3335338/log.txt)

https://www.set.gov.py/portal/PARAGUAY-SET/detail?folder-id=repository:collaboration:/sites/PARAGUAY-SET/categories/SET/Informes%20Periodicos/cotizaciones-historicos/2019/f-mes-de-junio&content-id=/repository/collaboration/sites/PARAGUAY-SET/documents/informes-periodicos/cotizaciones/2019/F%20-%20Mes%20de%20Junio

**Comment by gantonioid** [comment]
El error se debe a que el `Extract` de la tabla trae en texto plano todo el contenido, incluyendo saltos de línea.

Cuando la ejecución llega a la instrucción de `Write` dentro del Excel, se hace el reemplazo de la variable **incluyendo los saltos de línea**... 
`Excel Write "<<<tabla>>>" in HojaF row 1 and column 21`

La solución por el momento sería manipular el string (texto plano) que resulta de la extracción del contenido de la tabla utilizando PowerShell, y regresarlo a FRIDA en forma de JSON (lista de listas) para que tengas una variable que contenga las celdas (tabla)

Posteriormente, usar la instrucción `WriteTableVariable `para escribirla en el Excel indicando la celda superior izquierda donde quieres colocar la tabla.

@carlosortiz632 o que comentamos del `Extract`

**Comment by pabloreitanosofttek** [comment]
que opinion tiene @ClaudioRodolfoGarcete ?

**Comment by ClaudioRodolfoGarcete** [comment]
si es como dice toño, en el log debe figurar toda la tabla en una variable, el paso siguiente seria aplicar un regex para luego insertarlo en el excel.

Otra cosa que se me ocurre es recorrer cada columna por separado con un for guardarlo en un list y hacer lo que comente arriba.

**Comment by pabloreitanosofttek** [comment]
@jaristimuno ¿Alcanza con esto? ¡gracias!

**Comment by jaristimuno** [comment]
Si, probé y funciona
