### ISSUE TITLE
[EXCELLIA] - No puedo acceder a una celda de una tabla para escribir sobre ella

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#229]
Necesidad: Urgente
Necesito escribir el dispositivo de salida y Directorio Salida y no puedo hacer foco en las celdas ni tampoco escribir.
![imagen](https://user-images.githubusercontent.com/50331739/60289393-a9346d80-98ec-11e9-9632-713e9885c3db.png)
Habira utilizado Titanium pero solo me sirve cuando tengo una sola fila en la tabla.

Asimismo voy a necesitar leer el valor de la columna Vía Pago para hacer una validación.
Los Id los estaba tomando tanto del SAP recorder y del mismo SAP y no pude resolverlo, me comunique con @eradgg  al respecto para consultarle al respecto, el ya esta viendo el tema.

saludos y gracias!

**Comment by eradgg** [comment]
Hola Marianela.
Cree la función SAP WriteGridCell GridId wnd[0]/usr/cntlCONTROL01/shellcont/shell Column "DSPRN" Row 0 Value "LOCL".
La puedes usar como está arriba. Eso debería de solucionar el problema.

Saludos.

**Comment by MarianelaDuarte** [comment]
Buenos días Eder ¿como estas? Muchas gracias! ya probé la solución y funciona OK :D.
Te agradezco la atención inmediata a mi problema.
Lo que si vamos a necesitar que este cambio este en la versión de la máquina virtual de Excellia.
¿Me avisan si debo cargar otro ticket para solicitar eso?
Aguardo los comentarios para luego cerrar el ticket.
Saludos

**Comment by eradgg** [comment]
Hola MArianela, lo consulto con @gantonioid y @andresCruzF  para ver cuando lo podemos agregar a esa versión.
Saludos.

**Comment by pabloreitanosofttek** [comment]
@eradgg  cuando será? ¡gracias!

**Comment by MartinMedinaSTK** [comment]
Buenos días @gantonioid @andresCruzF me pueden confirmar si este cambio esta incluido en la versión de Turing 20190618T0627 ? y si no es así, podrán liberar el cambio para todos? 
Lo necesitamos para 11:30 am de Perú.
Gracias.

**Comment by gantonioid** [comment]
@MartinMedinaSTK  qué versión requieren y para quién se necesita liberar?

**Comment by MartinMedinaSTK** [comment]
@gantonioid entiendo que para resolver este git se generó una versión de Turing para Marianela, ahora necesito saber si este cambio ya fue liberado para todos y si está incluido en la versión de Turing que deje mas arriba.

**Comment by gantonioid** [comment]
No sabemos si la versión general incluye o no este cambio. Por eso necesito que me digas es qué versión consideran correcta y a quién se la tenemos que liberar.

@MartinMedinaSTK Mi pregunta es para agilizar la respuesta además de atender tu solicitud con precisión. 

Marianela HOY tiene activa la versión 20190628T1242, esa es la que necesitas? a qué otro usuario se le tiene que liberar LA MISMA versión? no puedo volverla General, para no interferir o provocar problemas con los demás usuarios

**Comment by gantonioid** [comment]
Ayer se le asignó a Martín la V.20190628T1242. Espero resultados de sus pruebas y confirmación para cerrar el tk.

**Comment by MartinMedinaSTK** [comment]
@gantonioid OK resuelto. 
Saludos!
