### ISSUE TITLE
Actualizar Parametros de perfil 

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#23]
Al loguearme en SAP, el sistema solicita Parámetro, existe alguna forma de evitar eso? me pidieron que lo cargara como error, gracias.

**Comment by victorgamboa** [comment]
![Captura](https://user-images.githubusercontent.com/49756748/56812372-beb3eb00-6808-11e9-93d3-e1c515ab53d7.JPG)

**Comment by eradgg** [comment]
Hola Victor. ¿Podrías enviarme un vide donde para ver cuando te sucede este error? ¿es el mismo que subió Claudio al Teams? Como explica Rodrigo ahí parece ser más un problema de configuración.
Pero igual manda el ambiente, usuario, y datos para reproducir el error, para checar si es con Turing.

**Comment by eradgg** [comment]
Se soluciona el Issue. Hay que quitar la transacción default en Detalles/Set Start Transaction.
