### ISSUE TITLE
[TITÁN] [MixedReader] Se requiere un "DeleteFile".

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#230]
Mi proceso descarga un archivo para trabajar con él y al finalizar debería eliminarlo para que no se acumule con el pasar de las ejecuciones. He notado que existe RenameFile y CopyFile las cuales funcionan correctamente. ¿Es viable hacer un DeleteFile?

De poder hacerse entonces para implementarlo en la máquina virtual del cliente necesitaría que se trabaje sobre el último ejecutable (TuringExpo.exe) que nos proporcionó @FaustinoLechuga para así no perder las mejoras que él hizo.

Prioridad media, lo necesito antes de este viernes.

**Comment by FaustinoLechuga** [comment]
Ya estoy trabajando sobre ello, te aviso cuando este lista la función que también incluya los cambios que hicimos antes.

**Comment by gantonioid** [comment]
Siempre está la opción de una línea o dos de PowerShell

**Comment by CesarEmanuelLencina** [comment]
Gracias @FaustinoLechuga, funcionó a la perfección el nuevo ejecutable en la versión offline del cliente.

Se puede cerrar el issue.
