### ISSUE TITLE
[TITAN] MultiFilter 

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#231]
Buenas tardes,

consulta, cual es la forma de aplicar un filtro mediante dos criterios con la instruccion ApplyFilterStartAt?

Lo siguiente no lo estaria realizando:

Excel ApplyFilterStartAt to the worksheet {miHojaExcelGenerado} start at row {5} to the column with the index {2} with the criteria "="348";="600""

Documentacion: 

![aaaaa](https://user-images.githubusercontent.com/33100638/60459013-66d59e00-9c16-11e9-9168-22d8ea7bf97e.png)

Necesidad: Urgente.

**Comment by FaustinoLechuga** [comment]
Intenta hacerlo con la función de MultiFilter, creo que esa te ayudaría mas.
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/MultiFilter](url)

**Comment by ClaudioRodolfoGarcete** [comment]
Hola @FaustinoLechuga , el tema es que necesito aplicar un filtro a la fila numero 5, y al mismo, aplicarle 2 criterios.

**Comment by FaustinoLechuga** [comment]
Perfecto, ya entendí tu problemática empezare a implementar un start_at en la funcion de multifilter.

**Comment by FaustinoLechuga** [comment]
Te acabo de liberar una nueva versión con la modificación que solicitaste 20190702T0439. Seria utilizar la instrucción de MultiFilter como se muestra a continuación.
`MultiFilter from Sheet2 in_column_index 2 start_at 5 with_criteria[348, 600]`

De igual manera se puede revisar la documentación para cualquier otra duda. Quedo a la espera de la confirmación del funcionamiento de la instrucción.

**Comment by ClaudioRodolfoGarcete** [comment]
7/2/2019 2:34:55 PM - Proces ID :1655719178
7/2/2019 2:34:55 PM - Execution started
7/2/2019 2:34:55 PM - #PASO 37.1: Running
7/2/2019 2:34:55 PM - PASO 37.1 : Success
7/2/2019 2:34:55 PM - #: Running
7/2/2019 2:34:55 PM -  : Success
7/2/2019 2:34:55 PM - #: Running
7/2/2019 2:34:55 PM -  : Success
7/2/2019 2:34:55 PM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx": Running
7/2/2019 2:34:55 PM - MixReader : Se agrego una nueva variable : 
Var Name : obieeAgrup
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx
7/2/2019 2:34:55 PM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" : Success
7/2/2019 2:34:55 PM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx": Running
7/2/2019 2:34:55 PM - MixReader : Se agrego una nueva variable : 
Var Name : cuadraturaAvantis
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx
7/2/2019 2:34:55 PM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" : Success
7/2/2019 2:34:55 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup: Running
7/2/2019 2:34:56 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup : Success
7/2/2019 2:34:56 PM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup: Running
7/2/2019 2:34:56 PM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup : Success
7/2/2019 2:34:56 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" as miLibroCuadraturaAvantis: Running
7/2/2019 2:34:56 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" as miLibroCuadraturaAvantis : Success
7/2/2019 2:34:56 PM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant: Running
7/2/2019 2:34:56 PM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant : Success
7/2/2019 2:34:56 PM - Excel MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria[348, 600]: Running
7/2/2019 2:34:56 PM - Syntax Error in : MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria[348, 600]
7/2/2019 2:34:56 PM - Syntax Error in : MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria[348, 600]
7/2/2019 2:34:56 PM - Excel MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria[348, 600] : Error
7/2/2019 2:34:57 PM - Execution ended

**Comment by FaustinoLechuga** [comment]
Una disculpa me falto un espacio. 
`MultiFilter from Sheet2 in_column_index 2 start_at 5 with_criteria [348, 600]`

**Comment by ClaudioRodolfoGarcete** [comment]
Tampoco funciona @FaustinoLechuga 

7/2/2019 2:50:47 PM - Proces ID :1655719178
7/2/2019 2:50:47 PM - Execution started
7/2/2019 2:50:47 PM - #PASO 37.1: Running
7/2/2019 2:50:47 PM - PASO 37.1 : Success
7/2/2019 2:50:47 PM - #: Running
7/2/2019 2:50:47 PM -  : Success
7/2/2019 2:50:47 PM - #: Running
7/2/2019 2:50:47 PM -  : Success
7/2/2019 2:50:47 PM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx": Running
7/2/2019 2:50:47 PM - MixReader : Se agrego una nueva variable : 
Var Name : obieeAgrup
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx
7/2/2019 2:50:47 PM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" : Success
7/2/2019 2:50:47 PM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx": Running
7/2/2019 2:50:47 PM - MixReader : Se agrego una nueva variable : 
Var Name : cuadraturaAvantis
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx
7/2/2019 2:50:47 PM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" : Success
7/2/2019 2:50:47 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup: Running
7/2/2019 2:50:48 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup : Success
7/2/2019 2:50:48 PM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup: Running
7/2/2019 2:50:48 PM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup : Success
7/2/2019 2:50:48 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" as miLibroCuadraturaAvantis: Running
7/2/2019 2:50:48 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" as miLibroCuadraturaAvantis : Success
7/2/2019 2:50:48 PM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant: Running
7/2/2019 2:50:48 PM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant : Success
7/2/2019 2:50:48 PM - Excel MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]: Running
7/2/2019 2:50:48 PM - Error in : MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]
7/2/2019 2:50:48 PM - Exception : The given key was not present in the dictionary.
7/2/2019 2:50:48 PM - Error in : MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]
7/2/2019 2:50:48 PM - Excel MultiFilter from miLibroObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600] : Error
7/2/2019 2:50:49 PM - Execution ended

**Comment by FaustinoLechuga** [comment]
Este es el error
`Exception : The given key was not present in the dictionary.`

Se refiere a que la hoja donde estas intentando aplicar el filtro no existe. Al revisar el log me doy cuenta que "miLibroObieeAgrup" no es un worksheet si no que es un workbook. De favor pido que pongas en ese parametro el worksheet en donde se desea aplicar el filtro.

**Comment by ClaudioRodolfoGarcete** [comment]
@FaustinoLechuga 

La instruccion realiza el filtro pero de forma incorrecta, no respeta el parametro del nro de columna.

log.

7/2/2019 3:09:39 PM - #Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant: Running
7/2/2019 3:09:39 PM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant : Success
7/2/2019 3:09:39 PM - Excel MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]: Running
7/2/2019 3:09:39 PM - Excel MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600] : Success
7/2/2019 3:09:39 PM - Titanium Sleep 5000: Running
7/2/2019 3:09:44 PM - Titanium Sleep 5000 : Success

Podemos observar que el filtro siempre lo hace en la primera columna.

![AAAAAAAAAAAAAAA](https://user-images.githubusercontent.com/33100638/60535968-a9ad7980-9cdb-11e9-8be8-c53af1f8145a.png)

**Comment by FaustinoLechuga** [comment]
Me puedes pasar tu excel porfavor?

**Comment by ClaudioRodolfoGarcete** [comment]
Ver adjunto en teams.

**Comment by FaustinoLechuga** [comment]
Gracias!!

**Comment by FaustinoLechuga** [comment]
Ya te libere una versión que resuelve el problema 20190702T0857. Quedo al pendiente.

**Comment by ClaudioRodolfoGarcete** [comment]
Perfecto @FaustinoLechuga ya funciona, muchas gracias.

**Comment by ClaudioRodolfoGarcete** [comment]
Hola @FaustinoLechuga  estoy teniendo problemas con la instruccion, sera porque actualice turing?

![aaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/33100638/60596073-9ef7f080-9d7e-11e9-9432-328dc89a8df4.png)

log:

7/3/2019 10:38:36 AM - Proces ID :1655719178
7/3/2019 10:38:36 AM - Execution started
7/3/2019 10:38:36 AM - #PASO 37.1: Running
7/3/2019 10:38:36 AM - PASO 37.1 : Success
7/3/2019 10:38:36 AM - #: Running
7/3/2019 10:38:36 AM -  : Success
7/3/2019 10:38:36 AM - #: Running
7/3/2019 10:38:36 AM -  : Success
7/3/2019 10:38:36 AM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx": Running
7/3/2019 10:38:36 AM - MixReader : Se agrego una nueva variable : 
Var Name : obieeAgrup
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx
7/3/2019 10:38:36 AM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" : Success
7/3/2019 10:38:36 AM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx": Running
7/3/2019 10:38:36 AM - MixReader : Se agrego una nueva variable : 
Var Name : cuadraturaAvantis
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx
7/3/2019 10:38:36 AM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" : Success
7/3/2019 10:38:36 AM - ###################################################################: Running
7/3/2019 10:38:36 AM -  : Success
7/3/2019 10:38:36 AM - # OBIEE AGRUP.xlsx: Running
7/3/2019 10:38:36 AM - OBIEE AGRUP.xlsx : Success
7/3/2019 10:38:36 AM - #: Running
7/3/2019 10:38:36 AM -  : Success
7/3/2019 10:38:36 AM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup: Running
7/3/2019 10:38:37 AM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup : Success
7/3/2019 10:38:37 AM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup: Running
7/3/2019 10:38:37 AM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup : Success
7/3/2019 10:38:37 AM - ###################################################################: Running
7/3/2019 10:38:37 AM -  : Success
7/3/2019 10:38:37 AM - # CUADRATURA AVANTIS.xlsx: Running
7/3/2019 10:38:37 AM - CUADRATURA AVANTIS.xlsx : Success
7/3/2019 10:38:37 AM - #: Running
7/3/2019 10:38:37 AM -  : Success
7/3/2019 10:38:37 AM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" as miLibroCuadraturaAvantis: Running
7/3/2019 10:38:38 AM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" as miLibroCuadraturaAvantis : Success
7/3/2019 10:38:38 AM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant: Running
7/3/2019 10:38:38 AM - Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant : Success
7/3/2019 10:38:38 AM - ###################################################################: Running
7/3/2019 10:38:38 AM -  : Success
7/3/2019 10:38:38 AM - Excel MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]: Running
7/3/2019 10:38:38 AM - Error in : MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]
7/3/2019 10:38:38 AM - Exception : Select method of Range class failed
7/3/2019 10:38:38 AM - Error in : MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]
7/3/2019 10:38:38 AM - Excel MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600] : Error
7/3/2019 10:38:39 AM - Execution ended

Script:

#PASO 37.1
#
#
DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx"
DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx"
###################################################################
# OBIEE AGRUP.xlsx
#
Excel LoadWBook "<<<obieeAgrup>>>" as miLibroObieeAgrup
Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup
###################################################################
# CUADRATURA AVANTIS.xlsx
#
Excel LoadWBook "<<<cuadraturaAvantis>>>" as miLibroCuadraturaAvantis
Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant
###################################################################
Excel MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]
Titanium Sleep 5000

**Comment by gantonioid** [comment]
Hiciste otro issue nuevo relacionado a esto. En qué es diferente?

**Comment by ClaudioRodolfoGarcete** [comment]
En este issue se trata sobre la instruccion MultiFilter y en el otro los demas @gantonioid

**Comment by ClaudioRodolfoGarcete** [comment]
Actualizacion 7/5/2019 - 

Recien hice una call con Jonathan Camacho Guel y observamos que la instruccion MultiFilter funciona pero falla si se carga 2 o mas excel, a la espera de su solucion.

**Comment by ClaudioRodolfoGarcete** [comment]
![aaaaaaaaaaaaa](https://user-images.githubusercontent.com/33100638/60816416-1a3b1700-a170-11e9-9cd6-9752fef1b989.png)

**Comment by Johhnn117** [comment]
Se tuvo llamada con @ClaudioRodolfoGarcete la instrucción ya funciona
