### ISSUE TITLE
[Excellia fase 2] Consulta: Que posibilidades tenemos de tener un Reader que pueda manejar Word? 

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#232]
Estamos relevando procesos nuevos para la fase 2 del cliente Excellia. En un proceso nos encontramos que un usuario genera contratos de trabajo desde la combinación de dos archivos, un excel y un word (que se llena dinamicamente con datos del excel) mediante la función "correspondencia" de Word.

¿De que forma se puede realizar algo así? 

Si necesitan más información me avisan y subo.

Gracias

**Comment by gantonioid** [comment]
Yo diría que como solución más pronta tendríamos la opción de hacer un exe (CustomLocal)

**Comment by gantonioid** [comment]
Esto para dirigirse más específicamente a la funcionalidad que se desea con la correspondencia. Porque un reader nuevo, con algo tan grande como Word no es trivial. Sería similar a Excelium.

Sumado a eso, requeriría de herramientas de debugging y creación de scripts de Word, porque la estructura de los documentos no es tan obvia y directa como las hojas y celdas.

Definitivamente podemos dedicarle más análisis pero no es un compromiso a corto ni mediano plazo.

**Comment by MartinMedinaSTK** [comment]
Ok, pero lo tienen en el backlog como para desarrollarlo o lo ven muy complicado? Entiendo que tiene infinidad de opciones y eso lo hace muy complejo. Por lo que vimos de está etapa de Excellia se usa mucho la interacción con Word, quizás se podría pensar en ir armando algo con funcionalidades limitadas.

**Comment by gantonioid** [comment]
Por qué no me pasas una lista de las funciones que necesitas con el mayor detalle posible y vamos evaluándolo?

**Comment by RickProductivity** [comment]
@MartinMedinaSTK cómo ves nos ayudas con lo que haz visto para definir un primer set de Features?

**Comment by MartinMedinaSTK** [comment]
Hola @RickProductivity y @gantonioid , estoy en una call ahora termino y ya le paso los detalles que tengo por ahora.
Gracias

**Comment by pabloreitanosofttek** [comment]
https://frida.public.makerkit.co/feedback/frida-word-readed-para-funciones-basicas (En camino)

**Comment by gantonioid** [comment]
Un mes sin su input.

Trabajamos en una versión inicial que cuenta con lo absolutamente más básico de manejo de documentos. La documentación está disponible en la web de FRIDA
![image](https://user-images.githubusercontent.com/9600868/62486142-11942b80-b784-11e9-823b-98705e0d4a22.png)
[http://automationplatform.azurewebsites.net/Readers/Tools/WordReader](url)
