### ISSUE TITLE
Tratamiento de valores: cómo definir su cultura? Consulta y Propuesta

### ISSUE THREAD

**Issue by FernandoLando-Softtek** [FridaSupport/TuringSuport#234]
Al momento de leer un valor para asignarlo a una variable numérica o de fecha, generalmente es necesario definir su cultura, de modo que sea correctamente interpretado ("1.000" significa mil o uno, dependiendo del separador de listas de mi cultura. "5/4" puede ser el 4 de mayo o 5 de abril, dependiendo de mi cultura) 

Hoy los desarrolladores están trabajando artesanalmente la conversión de culturas entre el origen y el destino de la copia de datos, con varios problemas:
	• Hasta que se dan cuenta de la causa del error (mezcla de culturas) pierden tiempo
	• Parsear y convertir manualmente los valores según su origen, mediante RegEx o Powershell, implica un trabajo muy minucioso, y aumenta el esfuerzo
	• Requiere conocer que cultura utilizará Turing en su ambiente de desarrollo local y en el productivo (*Acá vi algunos comportamientos bien extraños entre Turing, Powershell y Excel). Ref: GIT #192 y #197
	• Lleva una gran repetición de sustituciones y trasposiciones de textos para conseguir el resultado deseado
	• La complejidad y la extensión de la tarea la hacen muy propensa a error

La **consulta** es: ¿existe modo de declarar la cultura del valor capturado, de modo que lo pueda cargar en una variable fecha o número y luego operarlo?

Entendiendo que hoy no hay un modo de declarar la cultura del valor leído, hoy leen un string (con Extract) y luego lo trabajan artesanalmente para darle una cultura por cada destino requerido.

La **propuesta** es considerar una mejora para esta actividad tan cotidiana, que permita **ExtraerValor**, declarando su cultura. Adicionalmente podría considerar una máscara para interpretar formatos de fecha largos. 
Luego su contraparte para **PegarValor**, usando la cultura que se indique en cada caso. (Algo como lo que hoy hace GetCurrentDate del Mixed Reader)

Mi anécdota de ejemplo. 
Para iniciarme en FRIDA el primer proceso con el que tuve contacto implicaba:
	• Capturar fechas y valores decimales de 8 webs distintas
	• Pegarlos en Excel
	• Pegarlos en SAP

Para un mismo día leemos de las web de bancos nacionales o centrales estos valores:

País | Fecha | TC Dólar
-- | -- | --
AR | 1/7/2019 | 43,2000
CL | 01.Jul.2019 | 679,15
CO | Lunes 01 de Julio   de 2019 | 3.205,67
PY | 01-07-19 | 6.198
PE | 01Jul19 | 3.288
UY | 01/07/2019 | 35,1823
VE | Lunes, 01 Julio   2019 | 6.733,29
MX | 1 de julio de 2019 | 0.0520

Nótese las potenciales confusiones con los números y la dificultad para leer la fecha en cada país, aun cuando todos los formatos cortos usan la convención día / mes. 

Gracias por su atención,

**Comment by gantonioid** [comment]
Hola Fernando
Tú mismo lo mencionas:
> Nótese las potenciales confusiones con los números y la dificultad para leer la fecha en cada país, aun cuando todos los formatos cortos usan la convención día / mes.

Esperar que FRIDA adivine el tipo de dato, la cultura y el formato va a ser complicado aparte de problemático. El mismo Excel tiene este problema con las fechas, son enmascaradas de maneras distintas dependiendo de la cultura en la que esté la máquina local.

Yo en vez de propuesta veo una solicitud, pero me hace sentido el otorgarles una instrucción simplificada para parsear strings de fechas y números a una variable reutilizable en su script. Se atenderá la solicitud como mejora de baja prioridad y **para los casos más comunes**... haciendo énfasis en que no será posible resolverlos todos. Si el string de origen viene en un formato rebuscado, tendrán que seguir usando PowerShell y sus propios Regex.

Para el análisis nos vienen bien los ejemplos que brindas, muchas gracias.

**Comment by pabloreitanosofttek** [comment]
Estoy de acuerdo con el análisis de @gantonioid  pero porfa no lo suspendas, planificalo y contanos cuando estará. 
¡gracias!

**Comment by FernandoLando-Softtek** [comment]
No me estoy explicando bien. No sugiero que FRIDA adivine la cultura del valor, sino que el desarrollador pueda indicar la cultura de cada valor extraído, de modo que FRIDA lo interprete correctamente. En mi primer ejemplo decía: "1.000" significa mil o uno, dependiendo del separador de listas de mi cultura. Entonces yo debo indicar a que cultura corresponde el valor que capturo en cada caso. 

Imagina esta parte del problema: cierta página web me presenta una fecha corta (Format specifier "d") que utiliza cultura en-US (("6/15/2019") y yo necesito tomarla para luego pegar una copia en Excel ("15-6") y otra en SAPGUI ("15.06.2019").

Usando el método de parseo debo descomponer en mes, día y año, para luego recomponer en 2 formas distintas según pego en Excel o en SAP, indicando la secuencia de las partes y el separador adecuado.

Usando el método de capturar un valor de tipo fecha podría copiar y pegar en cada destino, indicando en cada caso la cultura. (Ej: "entender valor copiado como en-US, pegar en Excel como es-AR y en SAP como es-ES). Así queda una instrucción mucho más compacta, fácil de leer y menos propensa a error, que el caso de tratar la posición y delimitador de cada parte de un valor. 

Algo como:
ExtractValue(<object/string>, <Format specifier>,<Culture>)
PasteValue (<value>,  <Format specifier>,<Culture>)

PD 1: los formatos de fecha larga y fecha completa, también están definidos para cada cultura.
PD 2: adicionalmente, podría ser necesario definir culturas custom (como otra evolución más sofisticada), para aquellos formatos rebuscados
PD 3: no identifico problema en Excel, al contrario, tiene un manejo bastante fuerte y consistente de los valores y las culturas. 

PD 4: definitivamente hay un problema en el manejo dela cultura cuando el mismo script invoca distintos readers y PowerShell. Parece ocurrir un cambio inesperado y muy inconveniente de cultura, que altera los valores capturados. Para hacer un pedido concreto necesito contar con tiempo de un desarrollador, lo haré en pedido aparte. 

Gracias nuevamente por el apoyo para hacer crecer esta plataforma.

**Comment by RickProductivity** [comment]
Gracias Fer, oye me parece muy interesante el análisis yo creo que valdría la pena hacer unos ejemplos en una reunión y definir un primer caso básico , me explico ? Oye un tema cómo se define la cultura del dato en inglés , es decir cuál sería el término en inglés?

**Comment by gantonioid** [comment]
Ya nos dio ejemplos en su post principal.
Estamos rebotando ideas internamente con baja prioridad y definiendo unas funciones para ayudar a facilitar el parseo de strings para tipo fecha y número... así podríamos dejar de requerir scripts PowerShell para la conversión y facilitarles la tarea.

Como nota adicional... si esto o cualquier otra cosa es una tarea repetitiva, podrían ayudarse entre ustedes por el canal de wiki, creando documentación para estos casos.
![image](https://user-images.githubusercontent.com/9600868/60728298-9a117900-9f05-11e9-9140-2026a0ad2ee6.png)

**Comment by FernandoLando-Softtek** [comment]
> Gracias Fer, oye me parece muy interesante el análisis yo creo que valdría la pena hacer unos ejemplos en una reunión y definir un primer caso básico , me explico ? Oye un tema cómo se define la cultura del dato en inglés , es decir cuál sería el término en inglés?

Gracias Rik. En la jerga Microsoft las palabras clave para este tema son **culture** y **locale** (que representan dos conceptos diferentes)

Cuando quieras podemos charlarlo en términos no técnicos (yo no soy desarrollador). 

Aquí hay algunas notas clave para detallar estos conceptos:
CultureInfo Class
From <https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?redirectedfrom=MSDN&view=netframework-4.8> 


NumberFormatInfo Class
From <https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=netframework-4.8> 

DateTimeFormatInfo Class
From <https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo?view=netframework-4.8> 

DateTimeFormatInfo.LongDatePatternProperty
From <https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.longdatepattern?view=netframework-4.8> 

CultureInfo.GetFormat(Type) Method
From <https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getformat?view=netframework-4.8#> 

Standard Date and Time Format Strings
From <https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings>

**Comment by FaustinoLechuga** [comment]
Acabo de terminar una función que resolvería el tema con las fechas solo necesito saber a quien librarle los cambios para que realice pruebas. La función se llama ParseExactDate abajo les dejo el link. Les recuerdo que como aun no le libero los cambios a nadie la función no se podra probar.

http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/ParseExactDate

**Comment by pabloreitanosofttek** [comment]
Excelente! Capaz @Jesusdavid Aristimuño<mailto:jaristimuno@softtek.com> podría ser... si es que no tiene nada urgente @Diana Martinez<mailto:dmartinez@softtek.com>

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: FaustinoLechuga <notifications@github.com>
Enviado: martes, julio 9, 2019 8:07 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Comment
Asunto: Re: [FridaSupport/TuringSuport] Tratamiento de valores: cómo definir su cultura? Consulta y Propuesta (#234)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Acabo de terminar una función que resolvería el tema con las fechas solo necesito saber a quien librarle los cambios para que realice pruebas. La función se llama ParseExactDate abajo les dejo el link. Les recuerdo que como aun no le libero los cambios a nadie la función no se podra probar.

http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/ParseExactDate

**Comment by pabloreitanosofttek** [comment]
Buenas noches!
Me parece perfecto!
Mañana revisamos antes que nada el avance de las tareas planificadas y luego procedemos a verificarlo.
Posiblemente escribamos algunas dudas que pudieran surgir.
Saludos.
Diana.-


De: Pablo Sebastián Reitano
Enviado el: Tuesday, July 9, 2019 8:35 PM
Para: Diana Martinez <dmartinez@softtek.com>; Jesusdavid Aristimuño <jaristimuno@softtek.com>; FridaSupport/TuringSuport <reply@reply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] Tratamiento de valores: cómo definir su cultura? Consulta y Propuesta (#234)

Excelente! Capaz @Jesusdavid Aristimuño<mailto:jaristimuno@softtek.com> podría ser... si es que no tiene nada urgente @Diana Martinez<mailto:dmartinez@softtek.com>

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: FaustinoLechuga <notifications@github.com<mailto:notifications@github.com>>
Enviado: martes, julio 9, 2019 8:07 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Comment
Asunto: Re: [FridaSupport/TuringSuport] Tratamiento de valores: cómo definir su cultura? Consulta y Propuesta (#234)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Acabo de terminar una función que resolvería el tema con las fechas solo necesito saber a quien librarle los cambios para que realice pruebas. La función se llama ParseExactDate abajo les dejo el link. Les recuerdo que como aun no le libero los cambios a nadie la función no se podra probar.

http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/ParseExactDate

-

**Comment by FaustinoLechuga** [comment]
Perfecto le liberare la version a @jesusdavid.

**Comment by FaustinoLechuga** [comment]
Le libere a @jesusdavid la version 20190710T0347 en caso que se desee se puede hacer rollback

**Comment by pabloreitanosofttek** [comment]
Capaz no tengas respuesta por unos días dado que tiene entrega comprometida al Viernes…

**Comment by FaustinoLechuga** [comment]
No hay problema

**Comment by pabloreitanosofttek** [comment]
@FernandoLando-Softtek  @DianaSTK ¿probaron? ¿Como seguimos? 

Grax!

**Comment by pabloreitanosofttek** [comment]
https://frida.public.makerkit.co/feedback/tratamiento-de-valores-como-definir-su-cultura-consulta-y-propuesta

**Comment by pabloreitanosofttek** [comment]
Lo cerraría a este ticket dado que está el ítem en el roadmap para más adelante... si queda algo x resolver, lo vemos directo en FRIDA.Public.
