### ISSUE TITLE
WriteAll

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#235]
Buen día, no estoy pudiendo ejecutar el comando WriteAll para Excel. Lo que quiero hacer es fitlrar datos de una columna y que escriba "NO EXITOSO" para los que queden visibles. También probé usando el comando _Excel Filter in hoja2 in column 35 with criteria >1_ para aplicar el filtro para ver si afectaba en algo, pero no hubo cambios.
Log:
![log write all](https://user-images.githubusercontent.com/49987311/60520357-9f7b8300-9cbb-11e9-8878-58403c4786d8.jpg)

Script (línea 13):
![script write all](https://user-images.githubusercontent.com/49987311/60520385-aaceae80-9cbb-11e9-8c98-18f49a1bfc00.jpg)

Muchas gracias!

**Comment by Johhnn117** [comment]
Buen día,
Puedes compartir el archivo de excel y el script?

**Comment by gantonioid** [comment]
ApplyFilter tiene  una sintaxis que te permite escribir al mismo tiempo que filtras. Podrías usarla. Revisa la documentación de esa instrucción.

**Comment by MartinJOlmedo** [comment]
Se me había pasado esa opción de ApplyFilter. Muchas gracias!

**Comment by MartinJOlmedo** [comment]
Buenas tardes, vuelvo a abrir el issue porque me surgió una duda. Cuando yo escribo el comando _Excel ApplyFilter to the worksheet hoja2 to the column with the LetterIndex {AI} with the criteria ">1" and write on the column {36} "NO EXITOSO"_, en Excel encuentro la siguiente fórmula: _=SI(__AI2=">1"__;"NO EXITOSO";"")_, y por el error en la lógica no escribe en la celda (mi idea es que escriba __NO EXITOSO__). Probé escribiendo el comando sin poner los __""__ (...with the criteria >1 and...) y no funcionó. Hay alguna forma de que lo pueda corregir?

**Comment by JuanISalazarM** [comment]
Se ha atendido. Se ha entregado una serie de nuevas instrucciones a probar. El usuario se encuentra realizando pruebas. Estamos al pendiente de sus comentarios.

**Comment by MartinJOlmedo** [comment]
Se solucionó el problema de WriteAll.
