### ISSUE TITLE
Problema ejecución Turing Remoto Valorem

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#236]
Pueden ayudarme a identificar por qué no se ejecuto el Turing de forma remota?

Se realizo un llamado y el TaskID que retorno es null.

![error_turing_02](https://user-images.githubusercontent.com/14879161/60521763-70f6ab80-9cad-11e9-87ca-bb6ad12bb46e.png)

![error_turing_03](https://user-images.githubusercontent.com/14879161/60521772-73590580-9cad-11e9-8037-7abf29c7ab10.png)

el Turing esta arriba en modo escucha.

![error_turing_01](https://user-images.githubusercontent.com/14879161/60521629-35f47800-9cad-11e9-8c4d-1e67ba6e4f85.png)

**Comment by pabloreitanosofttek** [comment]
@gantonioid  @andresCruzF  porfa revisar el detalle porque es un bot productivo. ¡gracias!

**Comment by gantonioid** [comment]
Un TaskID null es que no se encontraron Turings Listener disponibles

**Comment by gantonioid** [comment]
Por lo tanto, la petición no entró a cola de ejecución.

**Comment by pabloreitanosofttek** [comment]
@carlosgiraldo ¿pudiste verlo?

**Comment by carlosgiraldo** [comment]
SI @pabloreitanosofttek , en el caso indique que el turing estaba arriba incluso puse evidencia.

**Comment by pabloreitanosofttek** [comment]
Ok, como seguimos @gantonioid ?

**Comment by gantonioid** [comment]
Mi comentario es el mismo: una respuesta `null` en el API es si no hay Turing activo. 

Sugiero volver a conectarlo manualmente. Se puede comprobar si está arriba o no en el portal de FRIDA
[http://automationplatform.azurewebsites.net/Home/MyProcess](url)
![image](https://user-images.githubusercontent.com/9600868/60734607-2461d900-9f16-11e9-97bb-11616c5591df.png)


Se debe de ver así, con máquinas disponibles
![image](https://user-images.githubusercontent.com/9600868/60734574-03998380-9f16-11e9-92a0-3f1f0fe1af96.png)


Ahí compruebas que la comunicación está OK, ingresas las variables de ejecución y debe de llegar al Turing para empezar el bot.

**Comment by gantonioid** [comment]
Y de nuevo, en tu FLOW se puede agregar una alerta por mail si la respuesta del API es null, no?

**Comment by carlosgiraldo** [comment]
si claro que se puede agregar, ya la tiene creada.

**Comment by pabloreitanosofttek** [comment]
Y levantó? Que más queda para revisar para cerrar el issue? ¡gracias!

**Comment by gantonioid** [comment]
Yo vi varias ejecuciones remotas del proceso de cadenas el día de hoy

**Comment by pabloreitanosofttek** [comment]
Excelente! @carlosgiraldo lo damos x cerrado?

**Comment by carlosgiraldo** [comment]
Si, cerrar.
