### ISSUE TITLE
Consulta. Excelium GetUnique

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#237]
Necesito usar la instrucción GetUnique en el script adjunto. Tengo entendido que el comportamiento que deberia de tener es que una vez abierto el excel leera a partir de la fila 4 de la columna 2 y capturar los valores posteriores.

Me esta dando un error de que estoy intentando forzar un string a una lista "System.Collections.Generic.List`1[System.String]" 

Tambien seria bueno una instruccion de ReadRange, que lea solo los valores en el rango especificado 
[script.txt](https://github.com/FridaSupport/TuringSuport/files/3355201/script.txt)
[Libro1.xlsx](https://github.com/FridaSupport/TuringSuport/files/3355205/Libro1.xlsx)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3355206/log.txt)

Prioridad Alta

**Comment by gantonioid** [comment]
Hola, te comparto un par de observaciones...

- las variables de tipo lista son en el fondo `System.Collections.Generic.List'1[System.String]`, así que un mensaje así no es un error.
- `GetUnique`, igual que otras instrucciones lee el _UsedRange_, así que cuando le estás diciendo `col_index "2"` en este XLSX en particular, la columna 2 del _UsedRange_ está vacía. (Los índices de columna de _UsedRange_ no son los mismos que los índices de columna de la hoja: La columna B es el `col_index 2` de la hoja pero la 1 de tu _UsedRange_)
- `GetUnique `usa el `start_at` a modo de _offset_, es decir, del _UsedRange_ se va hacia abajo X número de filas dependiendo de lo que hayas puesto en `start_at`.

En resumen... prueba esta instrucción de `GetUnique `y el `foreach `para que compruebes que lo hace correctamente
```
Excel GetUnique values from "hoja" col_index "1" start_at 0 as vUnique
foreach v in vUnique {
Message <<<v>>>
Titanium Sleep 2000
}
```

**Comment by jaristimuno** [comment]
Entiendo. Ya probé y funcionó. Gracias
