### ISSUE TITLE
[TITAN] ApplyFilterStartAt - ApplyFilter - Filter - Filtrar sobre campo que contiene formula.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#238]
Instrucciones: ApplyFilterStartAt - ApplyFilter - Filter
Inconveniente: Al realizar un filtro sobre una celda que contiene una formula, no lo realiza correctamente.

Se adjunta el excel en teams.

Necesidad: Urgente.

Filtro hecho por FRIDA:

![aaaFiltro](https://user-images.githubusercontent.com/33100638/60679808-506e5300-9e5f-11e9-90bf-c9a08fe868b5.png)

Formula que contiene:

![aaaafiltro2](https://user-images.githubusercontent.com/33100638/60679830-6d0a8b00-9e5f-11e9-8b9c-e9be64a5a7b1.png)

Script:

#PASO 37.1
#
#
DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx"
DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx"
###################################################################
# OBIEE AGRUP.xlsx
#
Excel LoadWBook "<<<obieeAgrup>>>" as miLibroObieeAgrup
Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup
###################################################################
# CUADRATURA AVANTIS.xlsx
#
Excel LoadWBook "<<<cuadraturaAvantis>>>" as miLibroCuadraturaAvantis
Excel LoadWSheet miLibroCuadraturaAvantis sheet "Hoja1" as miHojaCuadraAvant
###################################################################
#Excel MultiFilter from miHojaObieeAgrup in_column_index 2 start_at 5 with_criteria [348, 600]
#Titanium Sleep 5000
#
#Save miLibroObieeAgrup
#
#FIN PASO 37.1
#
####################################################################
#PASO 37.2
#
#Ver la manera de capturar la ubicacion de las celdas
Excel CopyPaste miHojaObieeAgrup B248:H409 to miHojaCuadraAvant I2
#Excel ApplyFilterStartAt to the worksheet {miHojaCuadraAvant} start at row {1} to the column with the index {7} with the criteria "-5"
#Excel ApplyFilter to the worksheet miHojaCuadraAvant to the column with the index {1} with the criteria "600"
#Excel ApplyFilter to the worksheet miHojaCuadraAvant to the column with the index {1} with the criteria "="348""
Excel Filter in miHojaCuadraAvant in column 7 with criteria -5
Titanium Sleep 9000

Save miLibroObieeAgrup and close
Save miLibroCuadraturaAvantis and close
#
#
#FINPASO 37.2

**Comment by gantonioid** [comment]
Podrías copiar valores y luego formato de celda en texto previo a hacer el filtro... solo es una idea

**Comment by Johhnn117** [comment]
@ClaudioRodolfoGarcete puedes revisar que tengas la versión 20190704T0437?

**Comment by ClaudioRodolfoGarcete** [comment]
Tengo esa version @Johhnn117 y sigue ocurriendo el inconveniente.

**Comment by Johhnn117** [comment]
Excel ApplyFilter to the worksheet miHojaCuadraAvant to the column with the index {7} with the criteria "-5" prueba con esta instrucción

**Comment by ClaudioRodolfoGarcete** [comment]
Ya funciona correctamente en la version 20190704T0437

**Comment by gantonioid** [comment]
Fue versión o sintaxis? @Johhnn117

**Comment by Johhnn117** [comment]
Sintaxis
