### ISSUE TITLE
[Excellia] No se encuentra la instrucción DeleteFile

### ISSUE THREAD

**Issue by Josecamats** [FridaSupport/TuringSuport#239]
Buenas como estan?
Queria saber si la instrucción DeleteFile funciona correctamente porque a mi me dice el log que no se encuentra.

Log:
7/4/2019 5:54:41 PM - DeleteFile PROVIDERS_RECEIVED_PAYMENTS1562273144043.xls from "C:\Users\jose.camats\Downloads": Running
7/4/2019 5:54:41 PM - Error: DeleteFile PROVIDERS_RECEIVED_PAYMENTS1562273144043.xls from "C:\Users\jose.camats\Downloads"
7/4/2019 5:54:41 PM - Error in deletefile Instruction was't found
7/4/2019 5:54:41 PM - DeleteFile PROVIDERS_RECEIVED_PAYMENTS1562273144043.xls from "C:\Users\jose.camats\Downloads" : Error
7/4/2019 5:54:41 PM - Execution ended

Script:

DeleteFile PROVIDERS_RECEIVED_PAYMENTS1562273144043.xls from "C:\Users\jose.camats\Downloads"

**Comment by gantonioid** [comment]
@Johhnn117 contáctame y lo vemos
