### ISSUE TITLE
Turing No muestra archivos de Excel abiertos

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#240]
Buen día. Tengo un inconveniente con Turing. Cuando abro un archivo de Excel no se ve en la pantalla. Los comandos los ejecuta como si estuviera abierto y hace todo sin dar error, pero no puedo verlo en la pantalla para poder comprobar que lo que estoy haciendo da los valores que necesito. 

Versión de Turing:
![data22](https://user-images.githubusercontent.com/49987311/60731983-40b64380-9f1f-11e9-9da4-1d53442a265c.jpg)

Video:
[DATA22.pptx](https://github.com/FridaSupport/TuringSuport/files/3363271/DATA22.pptx)

Script:
[DATA22.txt](https://github.com/FridaSupport/TuringSuport/files/3363273/DATA22.txt)

Log:
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3363276/log.txt)

Muchas gracias!

**Comment by JuanISalazarM** [comment]
Enterado, le atenderemos.

**Comment by JuanISalazarM** [comment]
En la siguiente imagen se presenta una casilla con la opción Headless Process. Se encuentra marcado en rojo.
Para poder ver el proceso corriendo es necesario tener la casilla vacía, es decir, tener la casilla deseleccionada.

![image](https://user-images.githubusercontent.com/50111840/60732955-15c4f300-9f11-11e9-8afe-a4bf38a7778c.png)

Solicito de favor realizar la prueba.
Agradezco su atención. Espero su respuesta.

**Comment by MartinJOlmedo** [comment]
Se solucionó el issue
