### ISSUE TITLE
URGENTE! ERROR AL EJECUTAR TURING

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#241]
Estimados, todo el equipo de Argentina estamos teniendo el siguiente error al ejecutar Turing:

![imagen](https://user-images.githubusercontent.com/50331739/60741754-0d84ac00-9f41-11e9-9da2-02c523977611.png)

Necesidad: Urgente.

@FridaSupport

**Comment by gantonioid** [comment]
Revisar por favor, ya debe de estar funcionando

**Comment by MarianelaDuarte** [comment]
No funciona todavia.
Abre Turing, cualquier opción que se elija hace que se cierre.

**Comment by gantonioid** [comment]
Se unificaron dependencias en el server, pueden probar de nuevo?

**Comment by MarianelaDuarte** [comment]
Solucionado.
Gracias
