### ISSUE TITLE
[Excellia] Problema ingresando a SAP

### ISSUE THREAD

**Issue by Josecamats** [FridaSupport/TuringSuport#242]
Buenas como estan?
Estoy teniendo problemas al querer ingresar a SAP con turing. Manualmente no tengo problemas, solo sucede cuando corro el bot.

Log:
7/8/2019 10:59:10 AM - Message Ingresando Los Datos en SAP Transaccion ZARP209: Running
7/8/2019 10:59:10 AM - Message Ingresando Los Datos en SAP Transaccion ZARP209 : Success
7/8/2019 10:59:10 AM - SAP RunSapInstance "SAP Excellia QA" 300 PROY_TESO Seguridad1 ES graphic: Running
7/8/2019 10:59:12 AM - error: RunSapInstance "SAP Excellia QA" 300 PROY_TESO Seguridad1 ES graphic : System.Runtime.InteropServices.COMException (0x0000026B): The control could not be found by id.
   at System.RuntimeType.ForwardCallToInvokeMember(String memberName, BindingFlags flags, Object target, Int32[] aWrapperTypes, MessageData& msgData)
   at SAPFEWSELib.ISapSessionTarget.FindById(String Id, Object Raise)
   at SapScriptReader.SapScriptExecute.CLickButtonById(String ButtonId) in C:\Users\andres.cruz\source\repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 957
   at SapScriptReader.SapScriptExecute.login(String action) in C:\Users\andres.cruz\source\repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 843
7/8/2019 10:59:12 AM - SAP RunSapInstance "SAP Excellia QA" 300 PROY_TESO Seguridad1 ES graphic : Error

Script:
Message Ingresando Los Datos en SAP Transaccion ZARP209
SAP RunSapInstance "<<SAPName>>" 300 <<SAPUser>> <<SAPPas>> ES graphic

**Comment by MarianelaDuarte** [comment]
Buenos días a mi me sucede lo mismo, me funcionaba normalmente y desde un momento ya no ingresa.
Es de prioridad urgente ya que necesito probar un bot y no puedo si no accede.

**Comment by eradgg** [comment]
Hola José, Marianela.

¿Pueden revisar que no se haya deshabilitado el SapScripting? Podría ser ese el problema.

saludos.

**Comment by RickProductivity** [comment]
Saben donde consultarlo ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eradgg** [comment]
Ya lo revisé, si está activado. Lo revbiso y les aviso.

saludos.

**Comment by eradgg** [comment]
Ya hice la prueba, yo no tengo fallas. Podríamos ponernos en contacto para verlo.

saludos.

**Comment by eradgg** [comment]
Ya lo revisé con @Josecamats y no tiene problema. @MarianelaDuarte ¿podrías confirmarme si aún se te presenta el error?

**Comment by MarianelaDuarte** [comment]
A mi me sigue sin funcionar Eder.
¿Tengo que reiniciar Frida?

**Comment by MarianelaDuarte** [comment]
Te paso un ID de un proceso, igual me pasa con todos.
Process ID: 2013092002

**Comment by MarianelaDuarte** [comment]
Ya pude hacer que funcione, despues de haber matado varias veces el proceso de SAP, en el admin de tareas, ahora quedo funcionando.
Saludos

**Comment by eradgg** [comment]
Ambos confirman que si está conectándose.
