### ISSUE TITLE
[Excellia] Incluir procesos en perfil de usuario de Excellia. Necesidad: Miércoles por la mañana

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#243]
@andresCruzF @gantonioid como están?

Necesito que suban los siguientes procesos que tenemos desarrollados en nuestros perfiles de usuario al usuario de Frida de Excellia. Les comparto los IDs y nombres de los procesos:

-	Perfil de Ignacio Novios
o	PagosDuasV2Step1 --- Process ID: 985237986
o	PagosDuasV2Step2 --- Process ID: 759178396

-	Perfil de Marianela Duarte
o	CobranzasLaNacion --- Process ID: 680712849
o	CobranzasBCP --- Process ID: 1206428216

Para esto ¿deberán armar una nueva versión de Turing? tengan en cuenta que el usuario de Excellia ya tiene una versión de instalada y corriendo en producción con varios procesos que hemos modificado directamente en la maquina virtual donde esta corriendo Turing.

Me avisan si necesitan algo mas.
Gracias

**Comment by gantonioid** [comment]
@MartinMedinaSTK yo sugiero que pongan esas modificaciones en el otro Turing (online) para que no haya problema de versiones en los scripts.

De lo contrario, tendrían que cuidar que no se vayan a sobre-escribir los archivos cuando @Johhnn117 pase la nueva versión. Hoy y en el futuro.

**Comment by gantonioid** [comment]
Digo que lo pasen al Turing online para que se guarde ese script en la plataforma, ya que al momento de hacer el paquete offline, ese es el script que se toma, incluyendo archivos adicionales PowerShell, Custom e imágenes.

**Comment by Johhnn117** [comment]
@MartinMedinaSTK te compartó el paquete Offline por Teams, podemos tener una llamada para revisar lo que menciona @gantonioid ?

**Comment by gantonioid** [comment]
@MartinMedinaSTK @pabloreitanosofttek importante para cumplir la fecha de necesidad

**Comment by MartinMedinaSTK** [comment]
Hola @gantonioid @Johhnn117, mañana miércoles por la mañana podemos tener la llamada? hoy fue día no laborable en Argentina, así me explican como sería el tema de pasar los cambios al Turing online. 

Gracias, saludos

**Comment by RickProductivity** [comment]
creo que necesitamos un app para los calendarios globales jajaaj

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MartinMedinaSTK** [comment]
Sería muy bueno!

**Comment by pabloreitanosofttek** [comment]
O completar un Excel en teams! 😝

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: MartinMedinaSTK <notifications@github.com>
Enviado: miércoles, julio 10, 2019 12:44 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [Excellia] Incluir procesos en perfil de usuario de Excellia. Necesidad: Miércoles por la mañana (#243)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Sería muy bueno!

**Comment by MartinMedinaSTK** [comment]
@Johhnn117 @gantonioid buen día, la versión de Turing Offline que me pasaron me está dando en siguiente error en todos los procesos: 

![image](https://user-images.githubusercontent.com/49758327/60973565-e5a99580-a2fe-11e9-935e-6cc4009cfc05.png)

¿Se puede solucionar directamente desde este ejecutable o necesitamos una nueva versión?

**Comment by MartinMedinaSTK** [comment]
@Johhnn117 como hablamos recién, antes de generar la próxima versión de Turing te voy a pasar el ID y nombre de otro proceso que tenemos que agregar. 
Gracias.

**Comment by MartinMedinaSTK** [comment]
@Johhnn117 te paso el proceso que tenemos que agregar:

Extractos bancarios – Interbank --- Process ID: 2012751294

**Comment by Johhnn117** [comment]
Te lo comparto por Teams

**Comment by MartinMedinaSTK** [comment]
@Johhnn117 estoy revisando la versión de Turing que me enviaste y faltan 4 procesos que ya estaban en la versión productiva, los pongo a continuación: 

![image](https://user-images.githubusercontent.com/49758327/61001257-a34f7b00-a335-11e9-8036-143720a7ffc4.png)

@gantonioid ¿Podemos abrir el issue nuevamente? gracias.

**Comment by gantonioid** [comment]
@Johhnn117 Cómo va esto?

@MartinMedinaSTK Ustedes son los que nos dicen la lista de ProcessID que requieren en su nuevo Turing Offline para liberaciones al cliente.

**Comment by MartinMedinaSTK** [comment]
@gantonioid hace un rato habla con Jonathan. Le comenté, mas o menos lo mismo que a vos.  Tomar los IDs de los procesos del turing del desarrollador que hizo el proceso no es algo viable, más que nada por una cuestión que antes de pasar un código a producción se hacen pruebas y demos con el cliente y es él el que autoriza la implementación. Una vez que esto sucede, el desarrollador puede o no usar ese proceso para hacer pruebas en su perfil, entendiendo que él ya hizo entrega del código y que su trabajo ya fue terminado.  Con esto último, si tomamos los IDs de esos procesos tenemos altas chances de arrastrar errores a producción o deberíamos volver a probar todos los procesos aun cuando no hayan cambiado. 
Mi idea es poder tener acceso a la plataforma http://automationplatform.azurewebsites.net con el usuario de Excellia (con las mismas funcionalidades que tengo con el mio) y desde ahí poder mantener los procesos actualizados cada vez que un desarrollador me envíe una modificación y, a su vez, poder generar la versión de turing Offline para subir a la maquina virtual.

¿Es posible esto?

**Comment by gantonioid** [comment]
Martín abordas varios puntos... aquí mi respuesta:

Para recuperar (o no) los cambios hechos en un Turing eso existen online y offline, y es un tema de capa 8 el que un usuario edite y provoque errores en el script que ya entregó. @pabloreitanosofttek hay que controlar esto

El diseño de la plataforma incluye exactamente el punto de soporte remoto, para que el desarrollador haga ajustes y el cliente los reciba. No debe en ningún momento considerarse el trabajo como terminado y posteriormente hacer pruebas con el script productivo, porque como bien lo dices y ya todo mundo debería de conocer, el script se almacena en la plataforma y redistribuye a todos los Turings que tengan acceso a dicho proceso.

Cuando se hace un Turing online o no, se toman los scripts vigentes de cada proceso. La diferencia es que los offline nunca más se actualizarán, porque son offline.

Como respuesta a tu pregunta, sí sería posible hacer un Turing online del cliente pero no resuelve lo que comentas: que el desarrollador entre a hacer ajustes para pruebas y provoque problemas en el script productivo (por considerar el trabajo terminado)

Lo que veo a partir de aquí (y si lo comentas asumo que es porque ya sucedió) es que hay que reforzar los fundamentos de arquitectura y funcionamiento de la plataforma para no generar incidentes por desconocimiento. El desarrollador no debe de hacer cambios o pruebas en los scripts productivos.

**Comment by gantonioid** [comment]
@Johhnn117 Ya tienen el Turing de este ticket? para cerrarlo

**Comment by Johhnn117** [comment]
No, el que le mandé a Martin le faltan los 4 procesos que comentó antes. Estoy en espera de los ID de todos los procesos que debe tener el Turing para generarlo de nuevo

**Comment by MartinMedinaSTK** [comment]
@gantonioid, te dejo mis respuestas en cada punto: (perdón que se haya extendido mucho copie tu respuesta y puse las mias) Si te parece podemos hacer una call mañana lunes para hablar y hacer los ajustes necesarios. 

Para recuperar (o no) los cambios hechos en un Turing eso existen online y offline, y es un tema de capa 8 el que un usuario edite y provoque errores en el script que ya entregó. @pabloreitanosofttek hay que controlar esto. 

RTA: una vez que el script esta entregado, en producción y superada la etapa de monitoreo, el Turing el desarrollador que lo hizo no debería quedar atado al proceso en producción, por muchas razones: el desarrollado renuncia al trabajo, el desarrollador podría generar cambios en el proceso para hacer pruebas (se podría pedir que no lo hagan pero así y todo quedamos sujetos a errores humanos), el proceso es asignado a otro desarrollador para que realice una segunda versión del proceso, los equipos están separados en Proyecto y Soporte & Mantenimiento con lo cual sería muy difícil que el que lo desarrolló luego siga dando soporte, etc.

 
El diseño de la plataforma incluye exactamente el punto de soporte remoto, para que el desarrollador haga ajustes y el cliente los reciba. No debe en ningún momento considerarse el trabajo como terminado y posteriormente hacer pruebas con el script productivo, porque como bien lo dices y ya todo mundo debería de conocer, el script se almacena en la plataforma y redistribuye a todos los Turings que tengan acceso a dicho proceso.

RTA: La redistribución a todos los Turing que tengan acceso al proceso se hace solo cuando el Turing instalado en el cliente es online.  Esto que estas comentando es un punto muy crítico. Deberían considerar alguna manera de que el desarrollador pueda decidir cuándo liberar su código a producción o al resto, ya que cada vez que hace clic en “save” está enviando su script (en las condiciones en que se encuentre) a la plataforma y si el turing del cliente que tiene ese script asociado se actualiza, nuevamente podría estar llevando a producción, por ejemplo: una versión 2 inconclusa. Ojo con esto, que ya no pasa por una cuestión que el desarrollador modificó un proceso para hacer pruebas.
En lo que corresponde a nuestro caso, el turing es offline y la actualización se hace de forma manual. Contemplamos el soporte remoto, los ajustes se hacen y se sube el script manualmente a producción. En lo que no estamos de acuerdo es en que tenga que ser el mismo desarrollador el que hace el Desarrollo inicial de bot y luego el mantenimiento (pensando en que podría haber dos equipos para cada actividad).   

Cuando se hace un Turing online o no, se toman los scripts vigentes de cada proceso. La diferencia es que los offline nunca más se actualizarán, porque son offline.
Como respuesta a tu pregunta, sí sería posible hacer un Turing online del cliente pero no resuelve lo que comentas: que el desarrollador entre a hacer ajustes para pruebas y provoque problemas en el script productivo (por considerar el trabajo terminado)

RTA: Yo lo que quiero es tener un Turing online con el usuario de Excellia, que este vacío, que no tenga ningún proceso asociado a ningún desarrollador. Entonces, los pasos serían los siguientes: 
1)	El desarrollador hace su trabajo sobre un proceso completo en su perfil. 
2)	Cuando está terminado el desarrollo, envía los scripts y todos los archivos necesarios para correr el proceso al administrador de la cuenta de Excellia.
3)	El administrador de la cuenta de Excellia crea desde cero el proceso en el perfil de Excellia y sube todos los archivos que le envió el desarrollador. Ejecuta el proceso y verifica su funcionalidad.
4)	El proceso esta OK. Genera una versión de Turing offline desde la plataforma y la sube a producción. Entonces de esta forma, todos los procesos del cliente están resguardados en la cuenta del cliente y solo hay un camino para actualizarlos, sin dependencias a los turings de cada desarrollador.

Lo que veo a partir de aquí (y si lo comentas asumo que es porque ya sucedió) es que hay que reforzar los fundamentos de arquitectura y funcionamiento de la plataforma para no generar incidentes por desconocimiento. El desarrollador no debe de hacer cambios o pruebas en los scripts productivos.

RTA: por suerte no ha sucedido hasta ahora. Todo surge del pedido que hicimos para agregar 3 nuevos procesos al Turing que ya tenemos productivo. A mi particularmente me hizo ruido tener que pasar los IDs de todos los procesos que ya están en producción. 


Es por todo esto que estamos hablando que aún no se los he enviado y queremos que este proceso se haga de otra manera que nos dé más seguridad de que lo que vamos a enviar a producción sea exactamente lo que debemos enviar.
¿Podemos avanzar teniendo el usuario de Excellia para poder generar los procesos de cero y poder armar la versión productiva desde ahí?

**Comment by gantonioid** [comment]
Todo lo que dices es válido para estudiar y mejorar el procedimiento, pero no inmediatamente. Por ahora tienes que seguir el procedimiento.
Por favor pasa los Process ID para generar tu Turing y cerrar el ticket.

**Comment by gantonioid** [comment]
Sin respuesta...
