### ISSUE TITLE
[SAP] Error al buscar un texto con la instrucción FindText

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#244]
Al buscar un texto con la instrucción FindText y guardarlo en una variable, esta la retorna vacía...

@eradgg ya lo esta revisando, gracias.

**Comment by eradgg** [comment]
Solucionado, se trabajó en conjunto con Victor para solucionarlo. se crearon 2 nuevas funciones ya que no servían para este desrrollo como estaban trabjando.
