### ISSUE TITLE
URGENTE: [EXCELLIA] - Error utilizando la instrucción  SelectGridRow cuando las filas estan en una variable de tipo string.

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#246]
Estimados,
Buenas noches, al utilizar la función SelectGridRow  de la siguiente manera:
SAP SelectGridRow GridId wnd[0]/usr/cntlCONTROL01/shellcont/shell RowN "<<<todasFilas>>>"
Sucede que siempre selecciona la primer fila, probe harcodeando los valores de tipo int y string, con eso descubri que funciona ok cuando es int, cuando es string falla, es por eso que no esta funcionando con mi string concatenado.
El dia de ayer lo estaba usando con la variable y funcionaba correctamente, es por ello que cargo el ticket.
Adjunto la tabla del caso utilizado:
![imagen](https://user-images.githubusercontent.com/50331739/61017471-b4b27a80-a369-11e9-908e-6486f4ecbe78.png)
Lo que tengo que hacer es seleccionar las filas que cumplen con cierta validación.

Mi pregunta es ¿es muy complicado que pueda admitir valor de tipo string? o ¿de qué manera puedo lograr que funcione? porque supongo que con un array tampoco la tomaria.

Prioridad: ALTA @FridaSupport , es urgente ya que necesitaba que este cerrado el proceso para ayer, y en la demo falló.

**Comment by MarianelaDuarte** [comment]
Process ID: 2013092002

**Comment by raulpoltiSTK** [comment]
@RickProductivity @FridaSupport @pabloreitanosofttek 
Gente, estamos teniendo inconveniente con esta función, que hasta el día lunes funcionaba, y ayer en la puesta en producción tanto en la maquina virtual como de forma local dejo de funcionar quedando mal con el cliente en la salida a producción. Necesitamos que le den prioridad urgente. Gracias.

**Comment by RickProductivity** [comment]
@Eder Raul Alberto David Garcia Guardado<mailto:ederr.garcia@softtek.com>

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RickProductivity** [comment]
Solo para no obviar me podrían mandar un screnshot de las version que tienen locales y las que están en production   ??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarianelaDuarte** [comment]
Versión del Turing de mi máquina:

![imagen](https://user-images.githubusercontent.com/50331739/61053251-98dbc280-a3c3-11e9-8e5b-3d2716a1f0e3.png)
Capturas del Turing de la Virtual(es offline):
![TuringVirtual1](https://user-images.githubusercontent.com/50331739/61053300-b577fa80-a3c3-11e9-8ad7-c9902b2a472a.png)
![TuringVirtual2](https://user-images.githubusercontent.com/50331739/61053304-b7da5480-a3c3-11e9-88b6-040a6eb0c7d7.png)

**Comment by RickProductivity** [comment]
Perdón me refería a las versiones de SAP

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarianelaDuarte** [comment]
Ambas son SAP Logon 750.
Saludos

**Comment by eradgg** [comment]
Lo checo por Skype con Marianela.

**Comment by pabloreitanosofttek** [comment]
Gracias! Esperamos las novedades ...

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS


________________________________

**Comment by eradgg** [comment]
ES un error de sintaxis, la instrucción no acepta comillas. SelectGridRow  GridId wnd[0]/usr/cntlALV/shellcont/shell RowN 0,2,8,10.
De cualquier forma hice la prueba, aunque sea una variable string al ponerla sin las comillas debe de funcionar. 
cambia de:
#SAP SelectGridRow GridId wnd[0]/usr/cntlCONTROL01/shellcont/shell RowN "<<<todasFilas>>>"
SAP SelectGridRow GridId wnd[0]/usr/cntlCONTROL01/shellcont/shell RowN "1,2"
a
#SAP SelectGridRow GridId wnd[0]/usr/cntlCONTROL01/shellcont/shell RowN <<<todasFilas>>>
SAP SelectGridRow GridId wnd[0]/usr/cntlCONTROL01/shellcont/shell RowN 1,2
y debe de funcionar en ambos casos.

**Comment by MarianelaDuarte** [comment]
Eder sin importar que sea string? ahora hago las pruebas! buenisimo.
Muchas gracias

**Comment by pabloreitanosofttek** [comment]
Ojalá sea... pero no termino de entender xq funcionaba y ahora no... que cambio? Porque estos errores son los que más complicado veo de comentar de cara a cliente.

Gracias a ambos.

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: MarianelaDuarte <notifications@github.com>
Enviado: jueves, julio 11, 2019 11:46 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] URGENTE: [EXCELLIA] - Error utilizando la instrucción SelectGridRow cuando las filas estan en una variable de tipo string. (#246)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Eder sin importar que sea string? ahora hago las pruebas! buenisimo.
Muchas gracias

**Comment by MarianelaDuarte** [comment]
Probado, funciona ok!
Mil gracias!
saludos

**Comment by pabloreitanosofttek** [comment]
Me gustaría un RCA de este ticket... podemos tomarnos 30' y hacerlo?

Gracias Éder y Marianela.

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: MarianelaDuarte <notifications@github.com>
Enviado: jueves, julio 11, 2019 11:49 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] URGENTE: [EXCELLIA] - Error utilizando la instrucción SelectGridRow cuando las filas estan en una variable de tipo string. (#246)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Closed #246<https://github.com/FridaSupport/TuringSuport/issues/246>.
