### ISSUE TITLE
[TITAN] [Web2] Instruccion que cierre el navegador?

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#247]
Hola buenas,

Se podrá implementar una instruccion en el reader de Web 2 que cierre el navegador antes abierto?

Entiendo que Tambien lo puedo hacer a traves de PowerShell, pero cuando mato el proceso del navegador tengo problemas luego cuando quiero Volver a levantarlo.

Quedo atento, Slds.

**Comment by JuanIgnacioBurgos** [comment]
Sucede que luego de usar la instruccion `Excel TurnHeadlessTo true` las intrucciones de Web2 dejan de funcionar. En si no fallan pero quedan siempre en "Running" y nunca pasan a la siguiente instruccion segun indica el Log..

**Comment by ClaudioRodolfoGarcete** [comment]
Necesidad: Urgente.
@pablorlmx

**Comment by gantonioid** [comment]
`Excel TurnHeadlessTo true` solamente hace que Excel se vuelva invisible. No altera nada de como están funcionando los otros readers,.

**Comment by ClaudioRodolfoGarcete** [comment]
Negativo @gantonioid  favor de ver el video en teams, creemos que el error se debe a TurnHeadlessTo.

**Comment by gantonioid** [comment]
yo no veo que hayan puesto link a video ni está en tu post de teams. cómo nos lo vas a pasar?

**Comment by ClaudioRodolfoGarcete** [comment]
Verificar en teams

**Comment by ClaudioRodolfoGarcete** [comment]
alguna novedad? el inconveniente sigue ocurriendo, si desean podemos arreglar una call

**Comment by FaustinoLechuga** [comment]
Me prodras pasar el log de ese proceso? Intente replicarlo y no me da el mismo error. Quiero ver mas a detalle a que se debe esto.

**Comment by ClaudioRodolfoGarcete** [comment]
Se queda congelado en la ultima instruccion, tal como se visualiza en el video:

7/15/2019 1:36:19 PM - Proces ID :1655719178
7/15/2019 1:36:19 PM - Execution started
7/15/2019 1:36:19 PM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx": Running
7/15/2019 1:36:19 PM - MixReader : Se agrego una nueva variable : 
Var Name : obieeAgrup
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx
7/15/2019 1:36:19 PM - DefineVariable type "string" as "obieeAgrup" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" : Success
7/15/2019 1:36:19 PM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx": Running
7/15/2019 1:36:19 PM - MixReader : Se agrego una nueva variable : 
Var Name : cuadraturaAvantis
Value : C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx
7/15/2019 1:36:19 PM - DefineVariable type "string" as "cuadraturaAvantis" with the value "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\Cuadratura AVANTIS 27-03.xlsx" : Success
7/15/2019 1:36:19 PM - ###################################################################: Running
7/15/2019 1:36:19 PM -  : Success
7/15/2019 1:36:19 PM - # OBIEE AGRUP.xlsx: Running
7/15/2019 1:36:19 PM - OBIEE AGRUP.xlsx : Success
7/15/2019 1:36:19 PM - #: Running
7/15/2019 1:36:19 PM -  : Success
7/15/2019 1:36:19 PM - Web2 GoTo "https://www.google.com.ar/": Running
7/15/2019 1:36:19 PM - Runing browpet-engine
7/15/2019 1:36:28 PM - Web2 GoTo "https://www.google.com.ar/" : Success
7/15/2019 1:36:28 PM - Web2 Type "Banco Nacion precio dolar" in name="q": Running
7/15/2019 1:36:29 PM - Web2 Type "Banco Nacion precio dolar" in name="q" : Success
7/15/2019 1:36:29 PM - ################################################################: Running
7/15/2019 1:36:29 PM -  : Success
7/15/2019 1:36:29 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup: Running
7/15/2019 1:36:30 PM - Excel LoadWBook "C:\Users\claudio.garcete\Downloads\CargaLocales2Karen\OBIEE AGRUP. 27-03.xlsx" as miLibroObieeAgrup : Success
7/15/2019 1:36:30 PM - SystemNotify Type "notification" with message "breakpoint": Running
7/15/2019 1:36:33 PM - SystemNotify Type "notification" with message "breakpoint" : Success
7/15/2019 1:36:33 PM - #Titanium Sleep 2000: Running
7/15/2019 1:36:33 PM - Titanium Sleep 2000 : Success
7/15/2019 1:36:33 PM - Excel TurnHeadlessTo true: Running
7/15/2019 1:36:33 PM - Excel TurnHeadlessTo true : Success
7/15/2019 1:36:33 PM - #Titanium Sleep 2000: Running
7/15/2019 1:36:34 PM - Titanium Sleep 2000 : Success
7/15/2019 1:36:34 PM - ###################################################################: Running
7/15/2019 1:36:34 PM -  : Success
7/15/2019 1:36:34 PM - Excel TurnHeadlessTo false: Running
7/15/2019 1:36:34 PM - Excel TurnHeadlessTo false : Success
7/15/2019 1:36:34 PM - #: Running
7/15/2019 1:36:34 PM -  : Success
7/15/2019 1:36:34 PM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup: Running
7/15/2019 1:36:34 PM - Excel LoadWSheet miLibroObieeAgrup sheet "Sheet1" as miHojaObieeAgrup : Success
7/15/2019 1:36:34 PM - Excel ReadCell from the worksheet miHojaObieeAgrup from the cell {1,1} and save its value as {aaa}: Running
7/15/2019 1:36:34 PM - Se agrego una nueva variable : 
Var Name : aaa
Value : CSC-IF - Cuadratura Locales Interfase Histórica - Agrup VTA_REC_AVA
7/15/2019 1:36:34 PM - Excel ReadCell from the worksheet miHojaObieeAgrup from the cell {1,1} and save its value as {aaa} : Success
7/15/2019 1:36:34 PM - Message CSC-IF - Cuadratura Locales Interfase Histórica - Agrup VTA_REC_AVA: Running
7/15/2019 1:36:34 PM - Message CSC-IF - Cuadratura Locales Interfase Histórica - Agrup VTA_REC_AVA : Success
7/15/2019 1:36:34 PM - Titanium Sleep 2000: Running
7/15/2019 1:36:36 PM - Titanium Sleep 2000 : Success
7/15/2019 1:36:36 PM - Web2 GoTo "https://www.google.com.ar/": Running

**Comment by FaustinoLechuga** [comment]
¿Me podras apoyar con esto @JuanISalazarM?

**Comment by JuanISalazarM** [comment]
Seguro, revisaré el problema.

**Comment by gantonioid** [comment]
Pongo el video aquí porque en Teams se pierde en la historia
[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/Shared%20Documents/Soporte/TurnHeadlessTo.avi](url)

**Comment by pabloreitanosofttek** [comment]
Novedades? @gantonioid @JuanISalazarM

**Comment by gantonioid** [comment]
Ya lo revisaron? @JuanISalazarM @Johhnn117 ? esa ventana de alerta por navegación no privada que pone Chrome no creo que sea por la instrucción `TurnHeadlessTo`

Qué opinas @carlosortiz632 ?

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid la Ventana de Alerta no es el problema, ya que Podemos accede a la web, el problema es que luego de usar la instruccion TurnHeadlessTo, cualquier instruccion de web2 queda en "Running" y no continua la ejecucion del bot

**Comment by JuanISalazarM** [comment]
Seguimos viendo el código. Estamos intentando de replicar el problema.
Estamos viendo la relación que tienen ambas instrucciones. Dado que son sistemas diferentes, uno es Excel y el otro Browpet. Por tanto, no debería tener relación. 
Seguimos investigando al respecto.

**Comment by gantonioid** [comment]
Gracias @JuanISalazarM

**Comment by ClaudioRodolfoGarcete** [comment]
alguna novedad de este tema?

**Comment by FaustinoLechuga** [comment]
Estuvimos investigando y la unica manera en la que pudimos replicar el error es cuando pusimos el SystemNotify de la misma manera en la que tienes el ejemplo. ¿Podrias intentar correr el proceso sin utilizar el SystemNotify? Esa es la instrucción que creemos esta causando el problema. 

Estaremos al pendiente.

**Comment by pabloreitanosofttek** [comment]
@ClaudioRodolfoGarcete  @JuanIgnacioBurgos falta algo? probaron? que más hacemos?

**Comment by ClaudioRodolfoGarcete** [comment]
Se probo con el caso aislado y funciona correctamente (quitandole el SystemNotify), falta probarlo en el caso real (el proceso) @JuanIgnacioBurgos

**Comment by JuanIgnacioBurgos** [comment]
Buenas,

Me gustaria tener una call para poder mostrar los inconvenientes que estamos teniendo a la hora de correr el proceso.
En cuanto puedan por favor contactarme por teams.

Gracias de antemano saludos.

**Comment by JuanIgnacioBurgos** [comment]
Hola,

Alguna novedad? necesitaria ver este tema antes del Viernes de ser possible.

**Comment by FaustinoLechuga** [comment]
Podemos hacer un call ahora para ver este tema

**Comment by gantonioid** [comment]
@FaustinoLechuga Cómo les fue?

**Comment by pabloreitanosofttek** [comment]
@FaustinoLechuga  @JuanIgnacioBurgos  @gantonioid  ¿Como estamos?
