### ISSUE TITLE
Titanium, no encuentra las imagenes

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#249]
Tengo un proceso que consiste en abrir el explorador de windows para sacar capturas del contenido de algunas unidades de disco que estan compartidas en red, intente hacerlo con powershell pero como no fui capaz de acceder use Titanium.
El problema viene cuando se ejecuta el proceso en los horarios programados, las instrucciones fallan siempre al momento de reconocer las imagenes de las capturas, durante una ejecucion manual estos errores no ocurren

adjunto parte  del log:
7/11/2019 7:03:12 AM - PowerShell ps1.txt: Running
7/11/2019 7:03:21 AM - PowerShell ps1.txt : 
7/11/2019 7:03:21 AM - PowerShell ps1.txt : Success
7/11/2019 7:03:21 AM - Titanium ClickImage Equipo.PNG Timeout= 15000 NumberClicks= 1: Running
7/11/2019 7:03:39 AM - Error in ClickImage Equipo.PNG Timeout= 15000 NumberClicks= 1 : 
 Image not found in the screen.
7/11/2019 7:03:39 AM - Titanium ClickImage Equipo.PNG Timeout= 15000 NumberClicks= 1 : Error
7/11/2019 7:03:39 AM - Catch Block Running
7/11/2019 7:03:39 AM - Catch Block End
7/11/2019 7:03:39 AM - Try Block End
7/11/2019 7:03:41 AM - Execution ended

El proceso corre sobre una maquina virtual, por lo que imagino que cuando el proceso se inicia la pantalla se encuentra apagada ( no bloqueada) y por eso no encuentra las imagenes.

**Comment by gantonioid** [comment]
Cómo ocurre la ejecución con schedule? Me refiero a si la máquina en ese momento está bloqueada, el usuario fuera de sesión, etc.
Además:
- ¿el usuario está usando la computadora en el momento de que el horario de ejecución llega?, aquí podrían estorbar las otras ventanas activas, haciendo que la imagen que Titanium busca no se encuentre en pantalla.
- ¿Se tiene conexión de red e internet?

**Comment by NehuenV** [comment]
La ejecucion se hace con la sesion del usuario iniciada, desconozco si esta bloqueada o no.
Como informacion que puedo agregar, las instrucciones que no usan titanium funcionan perfecto.

Es una maquina virtual especifica para el proceso, por lo que no esta siendo utilizada durante la ejecucion.
Se tiene conexion a internet y a la red interna de la empresa.

**Comment by gantonioid** [comment]
Se requiere que la máquina tenga interfaz gráfica activa para funcionar, de otra manera para Titanium la pantalla no existe o está toda en negro...
