### ISSUE TITLE
WEB2 - IDs y CSSSelector Dinamicos

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#25]
Al ingresar a la siguiente URL se observa que el ID, el cssSelector, y el xpath relativo cambian dinamicamente.

http://apps.cnp.com.ar:8080/Mercurio/page/public/login.zul

<input id="eJ8Q00" style="" class="z-textbox" value="" type="text" maxlength="50" xpath="1">

La clase no se puede utilizar pq mas abajo se vuelve a reutilizar.

Existe alguna forma de trabajar con el xpath absoluto ? 

Se probo con lo siguiente y no hubo caso.

Instruccion:

Web2 GoTo "http://apps.cnp.com.ar:8080/Mercurio/page/public/login.zul"
Web2 Type "testearEsto" in dynamic="/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/div[3]/table[1]/tbody[2]/tr[3]/td[2]/input[1]"
Titanium Sleep 7000

Fecha de necesidad: 26/4/2019 -

**Comment by carlosortiz632** [comment]
Lo reviso enseguida

**Comment by carlosortiz632** [comment]
Subí una nueva versión de browpet. Cuando vuelvan a abrir Turing les pedirá descargarla. 
---

## Detalles 
Esta trae un correción a un error en la función `In Context`, la cual es necesaria para poder ingresar las credenciales en esta página. Esta función está en proceso de ser documentada y podrán verla pronto en la página de documentación. Sin embargo, les platico cómo es que funciona.


 ## Explicación
Esta función te ayuda a encontrar elementos dado un contexto, es decir, indicándole más o menos por dónde debe empezar a buscar para que sea más fácil encontrar el elemento objetivo. Como estamos viendo que el `id` es dinámico, lo mejor es buscar un elemento de tipo `input` cercano a la etiqueta que lo acompaña. Entonces, decimos que queremos buscar un nodo `input` dentro del contexto de la etiqueta `Número de Documento`. El programa hará una búsqueda inteligente para determinar el camino correcto al `input` que se desea encontrar. A continuación, presento las instrucciones que me funcionaron para poder ingresar datos en esta página.

## Instrucciones

```
Web2 GoTo "http://apps.cnp.com.ar:8080/Mercurio/page/public/login.zul"
Web2 In Context of dynamic="Tipo de Documento"
Web2 InsertValue "LIBRETA CIVICA" in selector="input"
Web2 EndContext
Web2 In Context of dynamic="Número de Documento"
Web2 Type "hola" in selector="input"
Web2 EndContext
Web2 In Context of dynamic="Contraseña"
Web2 Type "adios" in selector="input"
Web2 EndContext
Web2 Sleep 5000
```

**Comment by carlosortiz632** [comment]
@ClaudioRodolfoGarcete  Cierro el issue. Si tienes problemas para usar esta función, por favor vuelve a abrir otro. Cierro este porque fue una correción de un error de nuestra parte. 

Saludos.
