### ISSUE TITLE
[Excellia] No se pueden leer dentro de un for los valores escritos en Excel. Necesidad Urgente

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#250]
Al escribir un valor en una celda de excel, intento leerla, para lo cual debo hacer un save y volver a hacer un readrows, en este caso si la variable a la que apunta el readrows ya existe da error. Si intento declarar una variable dinámicamente para cada vuelta también da error porque no permite el uso de números en el nombre, y si intento hacerlo sin números no da error pero no se llena la lista.
adjunto el script que armé para probarlo.
[ScriptPrueba.txt](https://github.com/FridaSupport/TuringSuport/files/3387538/ScriptPrueba.txt)
[Registros.xlsx](https://github.com/FridaSupport/TuringSuport/files/3387539/Registros.xlsx)

**Comment by JuanISalazarM** [comment]
Enterado, lo atenderemos.

**Comment by ignacionovio** [comment]
Buenas tardes, alguna novedad de este tema? gracias

**Comment by JuanISalazarM** [comment]
Se están realizando cambios dentro del código. Se estima que para antes de las 2pm del día de mañana, se haya actualizado su versión de Turing.
Se le notificará por este medio cuando se haya realizado la actualización, para solicitar de favor que realice pruebas.

**Comment by JuanISalazarM** [comment]
Estimado @ignacionovio 
Se ha actualizado su versión de Turing, solicito de favor realizar pruebas con el Script proporcionado para llevar a cabo la solución a su problema.
Por su atención, muchas gracias.
Si tiene algún comentario, haganoslo saber porfavor, y lo atenderemos a la brevedad.

**Comment by ignacionovio** [comment]
Funcionó correctamente con la nueva versión. Gracias!
