### ISSUE TITLE
CAPTCHAS

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#251]
¿Hay forma de romper reCAPTCHAS?

![imagen](https://user-images.githubusercontent.com/32799856/61245525-120c4a00-a723-11e9-8ada-2d1eb6120f1a.png)

**Comment by pabloreitanosofttek** [comment]
Si lo hay... Preguntale a Martin @NehuenV

**Comment by gantonioid** [comment]
#210

**Comment by NehuenV** [comment]
Voy a corregir mi pregunta, la función para romper captchas es una versión de Turing específica para pocos?
En la documentación no encontré nada sobre esa función.

**Comment by pabloreitanosofttek** [comment]
@NehuenV  velo con Martín. ¡Gracias!

**Comment by MartinMedinaSTK** [comment]
@NehuenV te comento que ya existe una forma de resolver el captcha por imagenes, la instrucción es la siguiente:

Web2 Custom "EnterSunat" clave="xxxxxx" usuario="xxxxxx" ruc="xxxxxx"

Nosotros ya la tenemos implementada en un proceso en producción para el cliente Excellia, y por ahora viene funcionando bien. 
La contra, es que solo sirve para ingresar a la web de SUNAT ( https://e-menu.sunat.gob.pe/cl-ti-itmenu/MenuInternet.htm). Con lo cual, sabiendo que se puede resolver el captcha, pedí que generen una función que permita romper el captcha de la web a la que queres acceder vos, o preguntemosle a
@gantonioid : ¿se podrá generar una función que sea más genérica o para ustedes es mas fácil que le pidamos una instrucción nueva por cada vez que lo necesitemos?

**Comment by gantonioid** [comment]
Esto lo tiene que ver @carlosortiz632

**Comment by carlosortiz632** [comment]
Que se pueda solucionar una CAPTCHA depende mucho de cómo está implementada. Podrías compartirme la página a la cual quieres acceder y yo con gusto puedo revisarla. Saludos.

**Comment by NehuenV** [comment]
https://www.buenosaires.gob.ar/consulta-de-infracciones
https://www.correoargentino.com.ar/formularios/oidn

Estas son alguna de las paginas que necesito

**Comment by pabloreitanosofttek** [comment]
@carlosortiz632 @gantonioid  ¿Pudieron ver las páginas que les pasó @NehuenV ? ¡gracias!

**Comment by carlosortiz632** [comment]
## Página 1
Esta página se puede resolver con la instrucción de Titanium de SolveCpatcha
https://www.buenosaires.gob.ar/consulta-de-infracciones

## Página 2

Me podrías proporcionar un número de seguimiento válido para poder hacer la prueba?

**Comment by NehuenV** [comment]
@carlosortiz632 te lo pase por teams

**Comment by carlosortiz632** [comment]
@NehuenV ya creamos una instrucción genérica para resolver captchas de _Recaptcha_. Te paso el nuevo ejecutable y las instrucciones por Teams.

**Comment by NehuenV** [comment]
Ticket solucionado, generaron una instruccion mas generica.
