### ISSUE TITLE
[Excellia] No me es posible descargar turing (URGENTE)

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#252]
debido a un inconveniente con la maquina esta fue formateada, desde el formateo el turing que tenia descargando ya no funciona y no me es posible descargarlo desde  
http://automationplatform.azurewebsites.net/Home/ConfigurationDownload#

Necesitaría si pueden facilitarme turing en alguna nube durante el día de hoy.

**Comment by SoledadNunez** [comment]
Ninguno de los procesos que probé que antes funcionaban corren con lo que me pasaron, pero turing levanta.

**Comment by Johhnn117** [comment]
@SoledadNunez ya cuenta con Turing de nuevo
