### ISSUE TITLE
[Excellia] Error en instrucciones Web2 URGENTE

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#253]
Con el turing que me pasaron comenzaron  a fallar instrucciones en distintos procesos que ya funcionaban, para los bancos BCP (custom teclado numérico) y BCP, realizar clic sobre una de las opciones de una tabla.
```
16/07/2019 17:18:43 - Web2 Custom "CodeTC" code="242610": Running
16/7/2019 17:18:46 - {"error":"No node found for selector: #undefined > img"}
16/07/2019 17:18:46 - Web2 Custom "CodeTC" code="242610" : Error
```

```
16/07/2019 15:51:11 - Web2 Click in selector="input[value='010719_150719_160719_134917431.SMM@@null']": Running
16/7/2019 15:51:11 - {"error":"Cannot click element"}
16/07/2019 15:51:11 - Web2 Click in selector="input[value='010719_150719_160719_134917431.SMM@@null']" : Error
```

```
17/07/2019 17:44:12 - Web2 Screenshot in id="kaptchaImage" save as "ruta": Running
17/7/2019 17:44:33 - {"error":"Element not found"}
17/07/2019 17:44:33 - Web2 Screenshot in id="kaptchaImage" save as "ruta" : Error
```

**Comment by carlosortiz632** [comment]
Lo empiezo a checar.

Saludos!

**Comment by carlosortiz632** [comment]
Hola Soledad, ya lo revisé y parece que sí funciona de mi lado. Quieres que te mande mi ejecutable para que lo pruebes? Espero tu respuesta

**Comment by SoledadNunez** [comment]
Si porfa, es que dejo de funcionar con la descarga del turing anterior.

**Comment by SoledadNunez** [comment]
@carlosortiz632  Disculpa la molestia ¿tendrás la versión de turing para pasarme?

**Comment by carlosortiz632** [comment]
@SoledadNunez te contacto por Teams

**Comment by SoledadNunez** [comment]
Buenas tardes, Turing nuevamente no levanta, necesito que resolvamos este tema de manera urgente, ya que no es solo el login de un proceso puntual, en este momento no puedo probar nada de lo que estoy desarrollando.

**Comment by pabloreitanosofttek** [comment]
@carlosortiz632  @gantonioid  me cuentan el avance? ¡gracias!

**Comment by pabloreitanosofttek** [comment]
@carlosortiz632 @gantonioid ?

**Comment by SoledadNunez** [comment]
Buenos días, el dia de ayer se comunico jonathan con migo, dejamos andando turing pero no se pudo resolver el problema que se menciona en este tema.
Quedamos en comunicarnos hoy para continuarlo, todavía no lo veo conectado.

**Comment by SoledadNunez** [comment]
Buenos dias, me indica Jonathan que posiblemente sea algo en mi computador, podrán indicarme cuales son los requisitos de Frida para solicitar en IT que lo dejen acorde para el correcto funcionamiento.

**Comment by pabloreitanosofttek** [comment]
¿Como puede ser que sea la máquina? Si hasta antes de ayer estaba todo OK…… además, debería ser algo que afecte a los 20 que trabajamos con RPA-FRIDA…



A la espera de comentarios para terminar de entender.



¡gracias!

Slds

PR

**Comment by Johhnn117** [comment]
Buenos días, 
El día de ayer probe el mismo script que está corriendo Soledad en mi equipo y corrió sin problemas, Soledad me proporcionó por Teams el mismo archivo (Script, versión, archivos, etc) que ella está usando y en mi equipo de nuevo no hubo problemas. Estoy revisando cual podría ser la causa del problema ya que no es por versión de Turing

**Comment by pabloreitanosofttek** [comment]
OK, porfa cuenten los avances. ¡gracias!

**Comment by SoledadNunez** [comment]
Buenos días, hay alguna novedad?

**Comment by pabloreitanosofttek** [comment]
@Johhnn117 @gantonioid @FridaSupport ?

**Comment by gantonioid** [comment]
@pabloreitanosofttek el script funciona en 5 computadoras distintas (de innovation Mexico y compañeros de Argentina), con el usuario y versión de Turing de @SoledadNunez 

No es cuestión de Turing ni versiones. Sugerimos que revisen restricciones de red o sistema de esa computadora. Resulta curioso que haya empezado la falla cuando se hizo el formateo.

**Comment by Johhnn117** [comment]
Si quieren revisarlo todos en conjunto con los de TI cuentan con nuestro apoyo para checarlo.

**Comment by pabloreitanosofttek** [comment]
Ok, como seguimos ?

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: Jonathan Camacho Guel <notifications@github.com>
Enviado: jueves, agosto 1, 2019 8:49 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [Excellia] Error en instrucciones Web2 URGENTE (#253)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Si quieren revisarlo todos en conjunto con los de TI cuentan con nuestro apoyo para checarlo.

**Comment by SoledadNunez** [comment]
Pablo levanto un tk para que revisen la compu y los pongo en contacto con Gilbrerto

**Comment by gantonioid** [comment]
Esto queda del lado de IT y/o soporte externo al equipo de FRIDA. Sin action items de nuestro lado.
