### ISSUE TITLE
[Excellia] Captcha banco Perú

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#254]
Para el banco Nación Perú se requiere resolver el Capchat para el 18/07

https://zonasegura1.bn.com.pe/BNWeb/login.do

![image](https://user-images.githubusercontent.com/25591982/61327734-f753d700-a7ef-11e9-899f-3fc15665a316.png)

**Comment by gantonioid** [comment]
Por qué no funciona el método documentado de Titanium SolveCaptcha??
[http://automationplatform.azurewebsites.net/Readers/Tools/Titanium/SolveCAPTCHA](url)

**Comment by gantonioid** [comment]
#48

**Comment by SoledadNunez** [comment]
En este momento no me funciona ni para bcp, pensé que era solo para ese banco como con los teclados numéricos.
En cuanto se resulva para BCP lo pruebo

**Comment by gantonioid** [comment]
Si te refieres al tk 48 que puse de referencia, está solucionado desde mayo.

**Comment by SoledadNunez** [comment]
No me refiero al 48, si no a otro tk que levante antes de este por el cual el captcha y otra instrucción me están dando error desde que descargue un nuevo turing. Ese que te menciono todavía no lo vió nadie.

**Comment by gantonioid** [comment]
Cuál es el problema aquí entonces? falta información

> Por qué no funciona el método documentado de Titanium SolveCaptcha??
> [http://automationplatform.azurewebsites.net/Readers/Tools/Titanium/SolveCAPTCHA](url)

**Comment by SoledadNunez** [comment]
No funciona mi turing para el tema de captcha

**Comment by gantonioid** [comment]
Perdón pero eso no me dice nada. Necesito saber qué instrucciones usas, el log de error y detalles extra que me puedas dar.

**Comment by SoledadNunez** [comment]
https://github.com/FridaSupport/TuringSuport/issues/253

**Comment by pabloreitanosofttek** [comment]
@gantonioid  @SoledadNunez  les propongo que charlen por teams, se pongan de acuerdo y nos cuenten como seguimos... ¡Gracias! @MartinMedinaSTK

**Comment by gantonioid** [comment]
Sin información

> Por qué no funciona el método documentado de Titanium SolveCaptcha??
> [http://automationplatform.azurewebsites.net/Readers/Tools/Titanium/SolveCAPTCHA](url)
