### ISSUE TITLE
[EXCELLIA] - WEB: Teclado Virtual.

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#256]
Estimados,
Buenas noches, estoy trabajando con un teclado virtual y estoy con problemas para crear la instrucción de la selección de las teclas.
Ya tengo procesos que usan teclado virtual pero no logro armar bien el id para acceder a cada tecla.
La Página es la siguiente:
https://bancaporinternet.banbif.com.pe/DCIBS_BIFNET/pages/s/login.html
![imagen](https://user-images.githubusercontent.com/50331739/61339217-1fa0fd00-a813-11e9-8613-b6681472f9b2.png)
Priodidad: 17.07
Desde ya muchas gracias!

**Comment by carlosortiz632** [comment]
Hola! Con estas instrucciones puedes clickear los botones

```
Web2 Click in xpath="//img[@src='/DCIBS_BIFNET/images/s/d0.gif']"
Web2 Click in xpath="//img[@src='/DCIBS_BIFNET/images/s/d1.gif']"
Web2 Click in xpath="//img[@src='/DCIBS_BIFNET/images/s/d2.gif']"
```

Saludos!

**Comment by carlosortiz632** [comment]
Hay que cambiar el número desde hasta el final de acuerdo al número que se quiera clickear

**Comment by pabloreitanosofttek** [comment]
@MarianelaDuarte ¿Quedo resuelto?

**Comment by pabloreitanosofttek** [comment]
Este ticket seguramente lo evalue @MartinMedidaSTK dadas las vacaciones de @MarianelaDuarte

**Comment by gantonioid** [comment]
Se brindó solución y no hubo respuesta

> Hola! Con estas instrucciones puedes clickear los botones
> 
> ```
> Web2 Click in xpath="//img[@src='/DCIBS_BIFNET/images/s/d0.gif']"
> Web2 Click in xpath="//img[@src='/DCIBS_BIFNET/images/s/d1.gif']"
> Web2 Click in xpath="//img[@src='/DCIBS_BIFNET/images/s/d2.gif']"
> ```
> 
> Saludos!



> Hay que cambiar el número desde hasta el final de acuerdo al número que se quiera clickear
