### ISSUE TITLE
[TITAN] Error generado en uso de un  custom en FRIDA

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#257]
se esta implementando un custom para que se utilice desde FRIDA pero genera el siguiente error:
Error : System.ComponentModel.Win32Exception (0x80004005): El ejecutable especificado no es una aplicación válida para esta plataforma de sistema operativo.

el custom se desarrollo en VB 2019 C#,  se realizo prueba directamente en el archivo .exe y funciona correctamente.

agradecería alguna accesoria o sugerencia  de como se puede solucionar este error. 

se adjunta el log.
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3402220/log.txt)

gracias

**Comment by gantonioid** [comment]
Eso a veces pasa cuando se compila para 64bits y se quiere ejecutar en una máquina de 32 (o al revés)... son temas de compatibilidad con el sistema operativo.

El log me indica que se hizo el llamado al custom local y la falla es directamente en `Process.Start()`, es decir... cuando FRIDA le pide al Custom que inicie su ejecución.

**Comment by rrrios** [comment]
@gantonioid como se implementa o como es el orden con Process.Start() que se sugiere, ya que lo estuve buscando en azure y en el teams y no lo encontré

Gracias.

**Comment by gantonioid** [comment]
el Process.Start() no lo manejas tú... simplemente viene en el detalle de la Excepción. Olvida eso.
Lo que tienes que revisar tú es que el compilado de tu Custom sea correcto (32/64 bits)

**Comment by gantonioid** [comment]
```
17/07/2019 8:53:42 a. m. - Error : System.ComponentModel.Win32Exception (0x80004005): El ejecutable especificado no es una aplicación válida para esta plataforma de sistema operativo.
   en System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   en System.Diagnostics.Process.Start()
```

[https://social.msdn.microsoft.com/Forums/es-ES/036e8b43-f1a0-47d3-a9fb-f7a189ace197/mi-problema-es-este-me-ayudan-?forum=netfxcompactes](url)

**Comment by gantonioid** [comment]
@rrrios hay novedades?

**Comment by pabloreitanosofttek** [comment]
@rrrios @Pablorlmx hubo alguna novedad?

**Comment by rrrios** [comment]
a pesar de la aclaración , se siguió presentando el error sin causa clara y precisa, ya que se ejecuto desde consola y funcionaba, pero al integrarlo a Frida se presentaba el error,  el custom se realizo en .net 

se realizo cambio de proyecto desde otra maquina y con eso se logro avanzar
