### ISSUE TITLE
[Excellia] No se pueden leer dentro de un for los valores escritos en Excel. Necesidad Urgente (issue anterior #250)

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#258]
La corrección enviada por @JuanISalazarM  funciona aplicada al código enviado como ejemplo en el issue #250 pero no funciona correctamente al usarla en mi Bot, creé un nuevo script para mostrar lo que ocurre. PRIORIDAD URGENTE
[Prueba_error_ReadRows_2.txt](https://github.com/FridaSupport/TuringSuport/files/3402687/Prueba_error_ReadRows_2.txt)
[Registros.xlsx](https://github.com/FridaSupport/TuringSuport/files/3402688/Registros.xlsx)

**Comment by JuanISalazarM** [comment]
Enterado, lo atenderemos.

**Comment by JuanISalazarM** [comment]
Buenas tardes.
Quisiera preguntarle, ¿cual es el resultado que espera? y ¿cual es el resultado que está obteniendo?
En base a esto podremos solucionar el problema más rápido.
Otra pregunta. ¿Cual es la finalidad de esta línea de código?

`DefineVariable type "string" as "letra" with the value "a<<<letra>>>"`

Porque según veo este agrega la letra "a" a la variable, haciendo que se genere una cadena larguísima.
¿Cual es la finalidad de esta instrucción?

Gracias por su atención. Esperamos su respuesta.

**Comment by JuanISalazarM** [comment]
Se ha resuelto el Issue.
Se resolvió modificando únicamente la instrucción ReadRows con la opción "update", para que pueda guardar variables con valores textuales y numéricos.
Además, de haber actualizado el Turing del usuario.
