### ISSUE TITLE
[Excellia] Error al ejecutar instrucciones de Titanium en una Maquina Vitual - proceso en productivo - Necesidad Urgente

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#259]
Hola, tenemos un proceso que ejecuta la siguiente instrucción en la máquina virtual del cliente en el ambiente productivo:

Titanium ClickImage BotonExportar.PNG Timeout= 10000 NumberClicks= 1

Cuando el Bot se ejecuta estando logueado en la máquina el proceso resuelve correctamente la instrucción tomando las dos siguientes imagenes:

![image](https://user-images.githubusercontent.com/49758327/61389975-43565880-a890-11e9-9f5e-72314494f656.png)

![image](https://user-images.githubusercontent.com/49758327/61390024-5f59fa00-a890-11e9-8cdd-cb7321910811.png)

Ahora el problema, cuando el proceso corre en automático, disparado desde el Task Scheduler, la instrucción da error, las imagenes que toma son las siguientes:

![image](https://user-images.githubusercontent.com/49758327/61390430-29694580-a891-11e9-81d3-bcc0265a9add.png)

![image](https://user-images.githubusercontent.com/49758327/61390447-2f5f2680-a891-11e9-91af-e23891d65f4b.png)

Un problema similar hemos tenido hace un tiempo cuando estábamos haciendo pruebas en el ambiente de QAS sobre una maquina física (no era una virtual). 
Mis preguntas: 
¿Titanium se puede usar sin estar conectado a la MV? 
¿Tengo que hacer alguna configuración particular para que funcione?

Tengan en cuenta que es un proceso que esta en producción y que corre todos los días a las 7 am de Perú.

Gracias

**Comment by gantonioid** [comment]
Titanium requiere interfaz gráfica activa... es decir que la máquina no tenga la sesión bloqueada.

Estoy seguro que ya había un tk de esto pero no lo encuentro para ponerte referencia.

**Comment by MartinMedinaSTK** [comment]
@andresCruzF me acuerdo cuando hicimos pruebas en la maquina física de Excellia teníamos una forma de cerrar la sesión remota por powershell y dejar la sesión activa en la PC física. ¿Crees que pueda servir para la MV también? 

El punto es que tenemos varios procesos en desarrollo avanzado que utilizan Titanium, y que van a estar programados para que corran en automático, con lo cual deberíamos ir buscando una solución a este punto, mas allá de resolver este problema puntual que hoy ya tenemos en producción.
Saludos

**Comment by MartinMedinaSTK** [comment]
@pabloreitanosofttek @RickProductivity @raulpoltiSTK
Los pongo en copia porque es un tema importante.

**Comment by gantonioid** [comment]
Insisto que es un tema conocido y existe solución

**Comment by MartinMedinaSTK** [comment]
ok, ya te entendí @gantonioid, ¿podrás pasarme la solución?

**Comment by andresCruzF** [comment]
Hola @MartinMedinaSTK 

Te comparto el script de powershell para solucionar este problema , el cual como se menciona es un error conocido independiente de la plataforma, siendo una configuración que requiere para este tipo de arquitectura, es importante mencionar que por default Windows cierra la sesión al momento de terminar la conexión con la máquina virtual por lo cual hay que mantener la sesión activa y pasarla a tipo consola al momento de salir de la máquina virtual, así mismo te comento que por estar hablando de la sesión activa de Windows este tipo de acciones requieren de permisos de administrador en la máquina virtual y en la terminal en la que se ejecute el script lo que nos dificulta el poder incorporar esta funcionalidad en Turing, por ultimo cabe mencionar que si se está corriendo un robot y existe una conexión con la máquina virtual pero esta se encuentra minimizada la maquina no genera imagen por lo cual los robots no corren , es importante tener esto en cuenta para no intentar realizar pruebas con la ventana minimizada.

Script 

_$output = query session | findstr /I "Active"
# The session id starts at the 38th character and is maximum 9 characters long
$sessionId = $output.Substring(38, 9).Trim() 
#write-host $sessionID
Tscon $sessionId /dest:console
 
#write the date and the current sessions so we can see the output when it ran and that it completed successfully 
date 
query session | findstr /I "Active"
echo OK_

**Comment by gantonioid** [comment]
La referencia anterior @c6j6g7g7 hizo el issue  #67

@pabloreitanosofttek vale la pena un wiki, falta iniciativa para enriquecerla. Creé esta hoja para ubicarla siguiendo el orden del OneNote
[
![image](https://user-images.githubusercontent.com/9600868/61410220-840e9b80-a8a9-11e9-8949-b020c5ba8115.png)
](url)

**Comment by gantonioid** [comment]
Se puede cerrar esto? la pregunta fue contestada

**Comment by MartinMedinaSTK** [comment]
si se puede, gracias @andresCruzF por el soporte!
Saludos
