### ISSUE TITLE
WEB2 Y TITANIUM

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#26]
Buen dia,

Estaba viendo un proceso donde tengo que ingresar un usuario y contraseña, la pagina tiene ID y selectores dinamicos, entonces la unica forma de llegar que tenia era mediante la clase. Logre escribir el usuario pero al no poder llegar al campo "contraseña" se me ocurrio usar un titanium type {TAB}, pero el titanium no hace absolutamente nada.

Adjunto el codigo:

Web2 GoTo "http://apps.cnp.com.ar:8080/Mercurio/page/public/login.zul"
Web2 Type "<<usuario>>" in class="z-textbox"
Titanium Type {TAB}
Web2 Type "<<password>>" in class="z-textbox"

Estaria bueno saber por que no funciona el titanium, y que soluciones hay ante casos como estos donde es imposible llegar a los campos sin un selector o id

Fecha de necesidad: 29/4/2019 - o antes

**Comment by carlosortiz632** [comment]
Duplicate of #25

**Comment by carlosortiz632** [comment]
Respondo en el otro issue

**Comment by carlosortiz632** [comment]
@NehuenV Se corrigió en el issue #25
