### ISSUE TITLE
[Excellia] Error al ejecutar un proceso en automático cuando está programado para que corra 2 veces al día. Necesidad: Urgente.

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#260]
Tenemos un proceso que esta planificado en el Task Scheduler para que corra a las 12:00 y a las 16:30 todos los días, como se muestra a continuación: 

![image](https://user-images.githubusercontent.com/49758327/61392544-6f280d00-a895-11e9-983c-59c46b8e7616.png)

![image](https://user-images.githubusercontent.com/49758327/61392508-60415a80-a895-11e9-8b96-09ed188f5be1.png)

En la ejecución de las 12 hs el proceso se ejecuta correctamente, pero en la segunda ejecución del día, hasta ahora siempre se ejecutó con error. El proceso lo que hace inicialmente es ingresar a SAP, y es ahí donde da error, al querer conectarse a SAP: 

![image](https://user-images.githubusercontent.com/49758327/61392693-c75f0f00-a895-11e9-8e72-376edb913fcd.png)

Adjunto el log

[log_del_error.txt](https://github.com/FridaSupport/TuringSuport/files/3402830/log_del_error.txt)

Es el primier bot que tenemos programado para que corra dos veces al día, la primera vez de día corre bien, la segunda no, y las dos veces falla de la misma manera.

¿Tendrán alguna idea de que puede estar pasando?
Gracias

**Comment by andresCruzF** [comment]
Hola @MartinMedinaSTK 

Lo revisamos , unicamente te pediria para descartar posibles errores que realices la siguiente configuración y lo vuelvas a intentar.

1.- Desactivar el scheduling 
![image](https://user-images.githubusercontent.com/49708627/61415002-22ecc500-a8b5-11e9-9057-2a3e262fc212.png)

2.- Borrar el archivo de remember me de la carpeta C:\...\Turing\App\Scheduling que va asociado al numero de tu proceso

![image](https://user-images.githubusercontent.com/49708627/61415084-65160680-a8b5-11e9-8d05-520219a85c50.png)

![image](https://user-images.githubusercontent.com/49708627/61415182-a4445780-a8b5-11e9-9cf0-8e7e2ed320e7.png)

3.- Vuelve a realizar la configuracion y a activar el scheduling 

![image](https://user-images.githubusercontent.com/49708627/61415242-c2aa5300-a8b5-11e9-9ec3-2fbfbc02a0a0.png)

![image](https://user-images.githubusercontent.com/49708627/61415268-d5248c80-a8b5-11e9-9bae-110b1153169c.png)

**Comment by pabloreitanosofttek** [comment]
@MartinMedinaSTK ¿Como fue?

**Comment by MartinMedinaSTK** [comment]
@pabloreitanosofttek la verdad no llegué a hacer esta prueba porque a partir de la corrida del miercoles 17 por la tarde se está ejecuntando correctamente. 

De todas maneras lo estamos monitoreando. Me quedo con la respuesta de Andres y si vuelve a suceder aplicamos la solución propuesta antes de cargar un issue nuevamente.

Gracias @andresCruzF
