### ISSUE TITLE
Consulta SendEmailAttachements

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#261]
Buenas tardes, me surgió una duda con el comando SendEmailAttachements:

Yo quiero enviar un body dandole un formato html como este (escribo todo espaciado porque si no lo toma como edición para este posteo, en turing lo escribo como corresponde):
**DefineVariable type "string" as "body" with the value " < p > Buenas tardes estimados, < / p > < p style="color:#3F499E"; > < i > Les adjunto el estado de cuenta e historial de pagos actualizado para su validación y programación de pagos. < / i > < / p > "**

y despues enviarlo usando el comando:
**SendEmailAttachements body To " < < < EMAILDELCLIENTE > > >" Subject "Estado de Cuenta" Attachements "Cliente_ < < < colElemento > > > .xls,archivo.jpg" Path " < < < home > > > "**

Mi duda surge porque yo recibí lo siguiente:
**"Buenas tardes estimados,
"**

Puede ser que esté tomando que cierro **""** cuando quiero determinar el color de la letra? Quiero decir, que esta tomando como valor del string **< p > Buenas tardes estimados, < / p > < p  style=** y el resto no. Si es así, hay alguna manera de poder definir el color u otra cosa que necesite el uso de **""**?

Adjunto el log de la prueba:
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3403425/log.txt)

Muchas gracias!

**Comment by gantonioid** [comment]
A menos que la documentación o @eradgg diga lo contrario, solo se soporta texto plano.
Eso o sustituye las comillas dobles por sencillas.

Por favor comenta los resultados de tus pruebas.

**Comment by MartinJOlmedo** [comment]
Acabo de probar definiendo
DefineVariable type "string" as "body" with the value "< p >Buenas tardes estimados, < / p > < p style=**'color:#3F499E'**;> < i >Les adjunto el estado de cuenta e historial de pagos actualizado para su validación y programación de pagos. < / i > < / p >"
y recibí el texto como yo quería. 
El cambio que implementé fue usar las comillas simples (**'**) para definir el color.

Muchas gracias!!
