### ISSUE TITLE
[Excellia] Web2 Se requiere descargar un PDF embebido

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#264]
![image](https://user-images.githubusercontent.com/25591982/61483518-51c97080-a973-11e9-972f-4fe2eb820966.png)
Fecha de resolución 24/07

**Comment by pabloreitanosofttek** [comment]
¿Y que le pasa cuando tocás ahí? No entendí el ticket @SoledadNunez

**Comment by SoledadNunez** [comment]
No tengo manera de dar clic en ese botón para la descarga porque esa embebido, solo veo un tag que referencia al pdf pero nada mas.

**Comment by gantonioid** [comment]
y si navegas a esa url? o si usas Titanium para dar el click?

**Comment by SoledadNunez** [comment]
Tengo como lineamiento con excellia de no usar titanium, se podrá ver si hay alguna manera de resolverlo con web2 mientras averiguo si esto cambio.

**Comment by carlosortiz632** [comment]
Debe de haber manera de clickear ese elemento, puedes compartirme la página o el html de ella?

**Comment by gantonioid** [comment]
Posiblemente te sirva esta de la documentación de FRIDA, el componente de pdf embebido es el mismo [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter](url)

**Comment by SoledadNunez** [comment]
enviado por team

**Comment by pabloreitanosofttek** [comment]
A la espera de novedades. ¡Gracias!

**Comment by pabloreitanosofttek** [comment]
@gantonioid  @FridaSupport ?

**Comment by gantonioid** [comment]
@SoledadNunez Hice una nueva función, prueba y me dices [http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/DownloadEmbedded](url)

**Comment by SoledadNunez** [comment]
lo pruebo y te confirmo. muchas gracias

**Comment by SoledadNunez** [comment]
Buenas tardes, me genera error con los 3 atributos

```
Web2 DownloadEmbedded id="plugin"
Web2 DownloadEmbedded selector="#plugin"
Web2 DownloadEmbedded xpath//*[@id="plugin"]
```

```
Web2 DownloadEmbedded id="plugin": Running
1/8/2019 11:25:39 - {"error":"Lexical Error in line 1 in instruction: DownloadEmbedded id=\"plugin\""}
01/08/2019 11:25:39 - Web2 DownloadEmbedded id="plugin" : Error

```
```
01/08/2019 12:55:27 - Web2 DownloadEmbedded selector="#plugin": Running
1/8/2019 12:55:27 - {"error":"Lexical Error in line 1 in instruction: DownloadEmbedded selector=\"#plugin\""}
01/08/2019 12:55:27 - Web2 DownloadEmbedded selector="#plugin" : Error

```
```
01/08/2019 13:02:28 - Web2 DownloadEmbedded xpath//*[@id="plugin"]: Running
1/8/2019 13:02:28 - {"error":"Lexical Error in line 1 in instruction: DownloadEmbedded xpath//*[@id=\"plugin\"]"}
01/08/2019 13:02:28 - Web2 DownloadEmbedded xpath//*[@id="plugin"] : Error

```
![image](https://user-images.githubusercontent.com/25591982/62302065-14bfac80-b450-11e9-9257-c717f7491d33.png)

**Comment by gantonioid** [comment]
Esta función se encuentra pendiente debido a un rollback temporal que se tuvo que hacer.

@andresCruzF nos puedes avisar?

**Comment by gantonioid** [comment]
@SoledadNunez Puedes probar de nuevo por favor? Se liberó junto con la del banco de colombia

**Comment by SoledadNunez** [comment]
No descarga pero tampoco da error con las siguientes instrucciones:
```
Web2 DownloadEmbedded id="plugin"
Web2 DownloadEmbedded selector="#plugin"
```

solo con xpath genera error
```
08/08/2019 12:44:08 - Web2 DownloadEmbedded xpath="//*[@id="plugin"]": Running
8/8/2019 12:44:30 - {"error":"Element not found"}
08/08/2019 12:44:30 - Web2 DownloadEmbedded xpath="//*[@id="plugin"]" : Error
```

**Comment by gantonioid** [comment]
Intenta descargar este PDF, así nos aseguramos que tengas la función y sea una cuestión más de la página que estás tratando
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter](url)

**Comment by SoledadNunez** [comment]
Si, ese pdf pude descargarlo.

**Comment by gantonioid** [comment]
Ya que tenemos la función de Evaluate, puedes usarla? me imagino algo así: (Omito los ` porque eso es un markup de git
[https://www.w3schools.com/jsref/met_win_open.asp](url)

`Web2 Evaluate open('<url_del_documento>')`

Si tomas de ejemplo la página de frida, en mi respuesta anterior, la url del documento sería el atributo src del tag <embed>

Prueba eso en tu página y me dices

**Comment by gantonioid** [comment]
Antes de hacerlo en FRIDA, revisa si Chrome lo permite descargar con Evaluate como mencioné. Claro, en vez de google, sería la url del doc
![image](https://user-images.githubusercontent.com/9600868/62729573-d3954280-b9e3-11e9-9565-e22f97547322.png)

**Comment by gantonioid** [comment]
Se desarrolló la instrucción DownloadEmbedded y Evaluate, pero no vemos solución inmediata ya que el elemento `<embed src="url" />` trae una URL que no se refiere directamente a un documento, y por tanto, no es descargable de esa forma.

**Comment by gantonioid** [comment]
@SoledadNunez te puedo llevar con Web2 únicamente hasta esta pantalla, lo demás no veo otra opción mas que Titanium
![image](https://user-images.githubusercontent.com/9600868/62885172-c6d36000-bcfd-11e9-822c-d799485c602a.png)

1. Inicia sesión normalmente
2. ##La siguiente línea carga el iframe para que no nos estorbe
3. `Web2 GoTo https://zonasegura1.bn.com.pe/BNWeb/consulta.do`
4. ##haz el procedimiento normal para seleccionar la cuenta y el mes que se desea
5. ##...
6. `Web2 Evaluate print()`
7. ##A partir de aquí es Titanium, click en "Print", seleccionar ruta de guardado, etc.

**Comment by gantonioid** [comment]
@SoledadNunez @pabloreitanosofttek qué opinan? no podemos hacer mucho más exclusivamente con Web2.

> Se desarrolló la instrucción DownloadEmbedded y Evaluate, pero no vemos solución inmediata ya que el elemento `<embed src="url" />` trae una URL que no se refiere directamente a un documento, y por tanto, no es descargable de esa forma.

**Comment by pabloreitanosofttek** [comment]
¿y alguna idea alternativa?

**Comment by gantonioid** [comment]
ya la dije 

> @SoledadNunez te puedo llevar con Web2 únicamente hasta esta pantalla, lo demás no veo otra opción mas que Titanium
> ![image](https://user-images.githubusercontent.com/9600868/62885172-c6d36000-bcfd-11e9-822c-d799485c602a.png)
> 
> 1. Inicia sesión normalmente
> 2. ##La siguiente línea carga el iframe para que no nos estorbe
> 3. `Web2 GoTo https://zonasegura1.bn.com.pe/BNWeb/consulta.do`
> 4. ##haz el procedimiento normal para seleccionar la cuenta y el mes que se desea
> 5. ##...
> 6. `Web2 Evaluate print()`
> 7. ##A partir de aquí es Titanium, click en "Print", seleccionar ruta de guardado, etc.

**Comment by gantonioid** [comment]
También podemos probar con ideas de ustedes

**Comment by gantonioid** [comment]
Se me ocurrió hacer la descarga por aparte usando cURL, pero requiere obtener las cookies de la sesión. Ya hice experimentos y funciona... pero tendrá que ser un `Web2 Custom`

Les informo cuando quede el desarrollo.

**Comment by gantonioid** [comment]
Se compartió documentación de lo que se logró, para que @SoledadNunez o alguien más intente otras opciones. Cierro el tk pero sigo atento.
