### ISSUE TITLE
Limpiar campos en web2 

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#265]
Necesito poder limpiar un campo de texto para escribir, queda basura acumulada por cada TYPE.
Necesito hacer varias busquedas, pero de entrada me queda el cartel "BUSCAR" y cuando escribo algo en ese campo se empieza a acumular
BUSCAR3000
BUSCAR300030000
BUSCAR30003000030000

![imagen](https://user-images.githubusercontent.com/32799856/61485062-a15d6b80-a976-11e9-9090-989c963838cb.png)

**Comment by gantonioid** [comment]
Usa Insert
[http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/InsertValue](url)
![image](https://user-images.githubusercontent.com/9600868/61490278-30b45000-a972-11e9-9a04-819df58fb931.png)
