### ISSUE TITLE
[TITAN] Filtro en subcolumnas con sentencia Filter  

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#267]
se requiere realizar un filtro en unas Subcolumnas. ya que se ejecuto esta sentencia y filtra por la columna principal.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/50424090/61666864-23fb6900-ac9e-11e9-9708-9e13fc8bd5a9.png">
 

Agradezco por la atención prestada o sugerencia.

**Comment by FaustinoLechuga** [comment]
¿El campo que mencionas es en donde deseas aplicar el filtro? ¿Que instrucción estas utilizando? No entiendo bien el issue.

**Comment by rrrios** [comment]
se esta utilizando la sentencia Filter, y las SubColumnas que se van a filtrar son: 

CAJRGF,CAJFIJ,CAJRGV,CAJFIJ por el valor "#N/A"

estas columnas están debajo de la columna Discoverer.

**Comment by FaustinoLechuga** [comment]
Por el momento podrias solucionarlo utilizando la instruccion multifilter y le especificas la columna y fila donde quieres poner el filtro, solo que en lugar de poner varios campos solo pondrias el de "#N/A"
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/MultiFilter

**Comment by pabloreitanosofttek** [comment]
@rrrios  ¿Te sirve esta respuesta? ¡gracias!

**Comment by rrrios** [comment]
Buenas tardes

se utilizo la instrucción de MultiFilter y se esta generando error, se adjunta el log, 
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3448782/log.txt)

el error se puede ver en la ultima parte del log

y en la segunda respuesta, no se puede por que el archivo es del cliente y lo generar un sistema exterior.

y por tercero solicito informacion si a la sentencia MultiFilter  se le puede enviar un valor menor que o mayor que. Para aplicar el filtro ya que requiero hacer un filtro dentro de un rango. 

agradezco por la atencion prestada y si me pueden aclarar el tercer punto aca en este github o hay la nesecidad de abrir otro.

**Comment by FaustinoLechuga** [comment]
Buen dia, el error que marca es simplemente por que tu version no contaba con esa instruccion, ya te mande un update (20190723T0600)

Y no, la funcion de multifilter no tiene esa capcidad, se estara trabajando para que la funcion de applyfilter pueda comenzar en una fila en especifico para que puedas filtrar por un rango.

**Comment by gantonioid** [comment]
Se hizo el update requerido, no hay comentarios del usuario. La función se encuentra documentada en la plataforma.
