### ISSUE TITLE
SAP Export URGENTE

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#268]
Buenas tardes, no me esta funcionando el comando SAP Export. Comparto Script y Log.

SCRIPT (las variables estan espaciadas para que se vean acá):
**GetEnviormentPath
GetCurrentDate Month and save as Mes
GetCurrentDate Day and save as Dia
GetCurrentDate Year and save as Anio
Excel LoadWBook " < < < home > > >\A relevar\Compensaciones Alicorp - MasterBread\Inputs Robot sociedad 738.xlsx" as libro3
Excel LoadWSheet libro3 sheet "U-Terr" as hoja3
SAP RunSapInstance "A) SAP ECC 6.0 - PRODUCTIVO" 300 < us r > < pass > ES graphic
#Excel LoadWBook "< < < h ome > > > \A relevar\Compensaciones Alicorp - MasterBread\Inputs Robot 738-2.xls" as libro4
Excel LoadWSheet libro3 sheet "U-Bancos" as hoja33
#Excel LoadWSheet libro3 sheet "FBL3N-Bancos 738" as hoja44
Excel ReadColumn from the worksheet hoja33 with the column index {2} and save its value as {CMAYOR}
DefineVariable type "string" as "SCMAYOR" with the value "0"
foreach colElemento in CMAYOR {
SAP StartTransaction FBL3N
if (" < < < c o lElemento > > > " -eq "738")
else
SAP Write id wnd[0]/usr/ctxtSD_SAKNR-LOW " < < < c olElemento > > > "**
**SAP Write id wnd[0]/usr/ctxtSD_BUKRS-LOW "738"
SAP Write id wnd[0]/usr/ctxtPA_STIDA " < < < Dia  > > > . < < < Me s > > > . < < < A nio > > > "**
**MathOperation < < < SCMAYOR > > > + 1 and save as SCMAYOR
SystemNotify Type "Validation" with message "validation"
#Titanium Type {F8}  wnd[0]/tbar[1]/btn[8]
SAP ClickButton id wnd[0]/tbar[1]/btn[8]
SystemNotify Type "Validation" with message "validation"
Titanium Sleep 4000
SAP Export ex "738_ < < < c o l E l e m e n t o > > > .MHT" " < < < h o m e > > > "
SystemNotify Type "Validation" with message "validation"
#Titanium Type {}shift f4
#Titanium Type {}intro
end
}
SystemNotify Type "Validation" with message "validation"**

Log:
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3424059/log.txt)

Hay alguna otra forma de poder hacer el Export?

Muchas gracias!

**Comment by MartinJOlmedo** [comment]
Puede ser que no lo haga porque los archivos estan seteados para descargarse como ".mhtml"?

**Comment by RickProductivity** [comment]
Podrias probar otro formato ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pabloreitanosofttek** [comment]
@MartinMedinaSTK o @ClaudioGarcete apoyo porfa! @DianaSTK

**Comment by raulpoltiSTK** [comment]
Sigue sin funcionar, se resolvió de otra forma, sin usar la funcionalidad de SAP Export. Lo estuvo siguiendo al tema @MartinMedinaSTK Saludos.

**Comment by eradgg** [comment]
Hola, una disculpa, tenía problemas con Git. La función export es una función compuesta por los pasos estandar para exportar a excel, pero no en todas las instancias de SAP está programada de la misma manera, entonces se tendrá que hacer replicando paso por paso ya que la posibilidad de diferentes escenarios es muy grande y no llevaría mucho tiempo y riesgo de bugs estar cambiando o agregando esta funcionalidad a la función export.

**Comment by MartinJOlmedo** [comment]
Muchas gracias. Cierro el issue.
