### ISSUE TITLE
[EXCELLIA] - EXCELLIUM: ReadRows update

### ISSUE THREAD

**Issue by Josecamats** [FridaSupport/TuringSuport#269]
Buenas como estan?
Estoy teniendo un problema con el ReadRows. Tengo un foreach dentro de otro y al correr la segunda vuelta me da error el ReadRows porque ya existe una variable con ese nombre. También probé con el ReadRows update y no me funciona, no se si porque hay que actualizar mi turing o si es otra cosa. 

Subo un ejemplo del ReadRows update:

[Script.txt](https://github.com/FridaSupport/TuringSuport/files/3427639/Script.txt)

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3427640/log.txt)

**Comment by Johhnn117** [comment]
Hola José, 
pues compartir el archivo de Excel?

**Comment by FaustinoLechuga** [comment]
Como nos comentas tu version no tiene los cambios con el ReadRows te acabo de mandar un update 20190717T0853 con esto se debe de resolver lo que nos mencionas. Porfavor verificalo, en caso de no reolverse si necesitaríamos un poco mas de información como menciona @Johhnn117 .

**Comment by Josecamats** [comment]
Lo acabo de probar y con la actualización ya funciona correctamente. Muchas gracias!
