### ISSUE TITLE
Browpet Falla en primera instancia.

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#27]
Cada vez que se va a iniciar un proceso con Web2. Falla en la primera corrida

**Comment by carlosortiz632** [comment]
Parece ser que este issue ya lo había resuelto @andresCruzF. Puedes darnos la versión de Turing en la que encuentras?

**Comment by jaristimuno** [comment]
Recien se acaba de actualizar el Browpet engine y anda bien. Mi version de Turing es 20190415T1031
