### ISSUE TITLE
Multifilter y ReadCell

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#270]
Buen día, lo que necesito hacer es filtrar dos números en la misma columna. Se puede hacer con la función **MultiFilter**. 

Lo que quiero hacer es lo siguiente:
**Excel ReadCell from the worksheet hojaextra from the cell {1,9} and save its value as {VALOR}
Excel ReadCell from the worksheet hojaextra from the cell {2,3} and save its value as {VALORNEG}
Excel MultiFilter from hoja1 in_column_index 14 with_criteria [ < < < V A L O R > > >, < < < V A L O R N E G > > > ]**
VALOR tiene un valor de 342.5 y VALORNEG tiene un valor de -342.5. El error ocurre cuando los valores que necesito filtrar tienen decimales y los ingreso desde una variable (multifilter filtra por los valores 342, -342 y 5). 

Probé ingresando manualmente los valores en multifilter (342.5, -342.5) y pude hacer lo que necesitaba. Lo que vi es que Turing toma los valores con decimales separados con "," por más que tenga configurado Excel y Windows para que separe decimales con ".". 

Adjunto info.

[script multif.txt](https://github.com/FridaSupport/TuringSuport/files/3432197/script.multif.txt)

![valor con coma](https://user-images.githubusercontent.com/49987311/61886210-aae65680-aed5-11e9-98af-e858619381c2.jpg)

![valor con coma 2](https://user-images.githubusercontent.com/49987311/61886223-af127400-aed5-11e9-96d6-b585b50f3833.jpg)

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3432199/log.txt)

**Comment by pabloreitanosofttek** [comment]
¿Lo viste con Claudio o Martin?

**Comment by MartinJOlmedo** [comment]
Si, lo vi con los dos. Lo que notamos es que cuando levanto un valor con ReadCell, lo escribe separando los decimales con "," y esto me genera conflicto con el Multifilter, que separa los criterios con "," también. Estoy viendo la forma de hacerlo sin usar Multifilter.

**Comment by pabloreitanosofttek** [comment]
@gantonioid @FridaSupport ?

**Comment by JuanISalazarM** [comment]
Seguro, lo estaremos atendiendo. Por lo visto es un error de sintaxis dentro de la plataforma. Se estará revisando la problemática, la solución será entregada aproximadamente para este Viernes antes de las 4pm.
Gracias por su atención.
Tenga un excelente día.

**Comment by FaustinoLechuga** [comment]
¿Nos puedes compartir el archivo de excel donde estas filtrando y donde lees los datos?

**Comment by gantonioid** [comment]
@JuanISalazarM @FaustinoLechuga Novedades?

**Comment by JuanISalazarM** [comment]
Actualizamos la versión de Turing. Estamos esperando que se realicen las pruebas necesarias para determinar si se ha quedado resuelto o no.

**Comment by pabloreitanosofttek** [comment]
@MartinJOlmedo como fue?

**Comment by MartinJOlmedo** [comment]
Todavia no lo pude probar. Hoy a última hora lo pruebo y comento el resultado

**Comment by MartinJOlmedo** [comment]
Problema resuelto!
