### ISSUE TITLE
[RPA INTERNO] Generacion de turing off para el cliente interno

### ISSUE THREAD

**Issue by DianaSTK** [FridaSupport/TuringSuport#271]
Responsable: Diana Martinez
Nombre proceso: TIPOCAMBIO
ID: 1484870469
Necesidad: Urgente, (antes del JUEVES 01 de AGOSTO)

Aclaración: RPA interno es para procesos de Softtek SSH
Cualquier consulta a disposición. 
Saludos,
Diana Martínez.-
dmartinez@softtek.com

**Comment by pabloreitanosofttek** [comment]
@andresCruzF ? @gantonioid ?

**Comment by RickProductivity** [comment]
Oye Pablo  este para quien es? Es que está pidiendo corporativo léase la oficina del CFO tener un proceso corporativo de tipo de cambio , quisiera revisarlo antes de Liberarlo .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pabloreitanosofttek** [comment]
Tenemos bots para ssh construidos que queremos sacar a prd, entre ellos el que marca Diana... se vendrán más (de operaciones, comercial, administración, etc)

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: RickProductivity <notifications@github.com>
Enviado: martes, julio 30, 2019 9:02 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Comment
Asunto: Re: [FridaSupport/TuringSuport] [RPA INTERNO] Generacion de turing off para el cliente interno (#271)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.

Oye Pablo este para quien es? Es que está pidiendo corporativo léase la oficina del CFO tener un proceso corporativo de tipo de cambio , quisiera revisarlo antes de Liberarlo .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RickProductivity** [comment]
Este en particular quisiera revisarlo pongamos una juntita , saludos
Rick

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pabloreitanosofttek** [comment]
Podemos... @Diana Martinez<mailto:dmartinez@softtek.com>  porfa revisar si podemos ponerla hoy tipo 14hs Arg o el
Jueves x la tarde ...

Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: RickProductivity <notifications@github.com>
Enviado: martes, julio 30, 2019 9:24 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Comment
Asunto: Re: [FridaSupport/TuringSuport] [RPA INTERNO] Generacion de turing off para el cliente interno (#271)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.

Este en particular quisiera revisarlo pongamos una juntita , saludos
Rick

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DianaSTK** [comment]
Buen día @pabloreitanosofttek , @RickProductivity: 
Perdón la demora en responder.  Hoy generaron una reunión "Desarrollo de procesos de automatización RPA con FRIDA", entendí mal que se trataba de revisar este tema.
No hay problema, estoy disponible hoy 14 horas. 
Enseguida genero la cita.
Saludos,
Diana.-

**Comment by DianaSTK** [comment]
@RickProductivity, @pabloreitanosofttek  generamos una reunión para mañana 18 hs ARG.
Cualquier consulta a disposición.
Saludos,
Diana.-

**Comment by pabloreitanosofttek** [comment]
Perfecto para mí.

Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: DianaSTK <notifications@github.com>
Enviado: martes, julio 30, 2019 3:50 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [RPA INTERNO] Generacion de turing off para el cliente interno (#271)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


@RickProductivity<https://github.com/RickProductivity>, @pabloreitanosofttek<https://github.com/pabloreitanosofttek> generamos una reunión para mañana 18 hs ARG.
Cualquier consulta a disposición.
Saludos,
Diana.-

**Comment by gantonioid** [comment]
@andresCruzF se cierra esto entonces por lo que hablaron en la llamada?

**Comment by pabloreitanosofttek** [comment]
Aguanta xq en el fondo no hubo un cambio significativo... Rick es la única persona válida para decirle a Rodrigo de activar el scripting de SAP.

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: gantonioid <notifications@github.com>
Enviado: jueves, agosto 1, 2019 8:31 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [RPA INTERNO] Generacion de turing off para el cliente interno (#271)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


@andresCruzF<https://github.com/andresCruzF> se cierra esto entonces por lo que hablaron en la llamada?

**Comment by gantonioid** [comment]
Pero estás de acuerdo que eso no es  soporte Frida?

**Comment by pabloreitanosofttek** [comment]
OK cerralo. ¡gracias!
