### ISSUE TITLE
[CENTRIA] Diagrama de arquitectura

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#272]
Buen día! 
¿Como andan?

Necesito presentar a Centria un diagrama de arquitectura donde literal del cliente "_se espera ver en qué instancia, servidor, nube, etc se encuentra cada componente de la solución y cómo será el acceso a nivel de usuario y de existir interfases._ "

¿Tenemos algo ya armado y que luego en una call pueda defender sin problemas?  (La call es mañana miércoles a las 17hs Perú-19hs ARG)

¡gracias!
Slds
PR

**Comment by gantonioid** [comment]
Se trató por mail/WhatsApp
