### ISSUE TITLE
[Proyecto interno - Tipo de cambio] Ejecutar turing de otra persona.

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#273]
Estamos teniendo inconvenientes a la hora de ejecutar un proceso del turing de otro compañero (activamos turing previamente y se visulizan sus procesos).
 Este tema lo esta viendo Jonathan Camacho Guel

@Johhnn117 

Se adjunta el turing de JesusDavid en teams.

Necesidad: Urgente.

**Comment by pabloreitanosofttek** [comment]
Sería bueno tener una estimación... gracias!

**Comment by Johhnn117** [comment]
En llamada con Jhon Antony quedamos en espera de que vuelvan a descargar el Turing de Jesús David para poder probarlo de nuevo en la computadora de John.

**Comment by DianaSTK** [comment]
@Johhnn117 ahí lo verificamos y comentamos los resultados. Saludos! @ignacionovio podrás verificarlo?

**Comment by ignacionovio** [comment]
Acaban de probarlo con el Turing descargado de Jesusdavid y el resultado fue el mismo que en la call de ayer. Podrían verlo con @AntonyFagundez ? gracias!

**Comment by AntonyFagundez** [comment]
Hola muy buenas tardes, con las configuraciones comentadas con @Johhnn117
 **Borrar la carpeta RememberMe de la App** con el Turing actualizado de Jesusdavid si pudo correr efectivamente. Saludos!

**Comment by DianaSTK** [comment]
@Johhnn117 @AntonyFagundez  muchas gracias!!!
