### ISSUE TITLE
[Excellia] [PowerShell] Necesito ejecutar script con el parámetro -STA

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#274]
Tengo una imagen copiada en el portapapeles y quiero guardarla en disco. Para ello ejecuto el siguiente código en Powershell:

```
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
$img = [Windows.Forms.Clipboard]::GetImage()
$img.Save('C:\Users\cesar.lencina\Documents\PagoDeChequesDiferidos\tabla.jpeg', [Drawing.Imaging.ImageFormat]::Jpeg)
```
El problema es que para que esto funcione es necesario que el Script.txt que lee Turing se ejecute con el parámetro -sta. ¿Tengo alguna forma de indicárselo?

Necesito una solución a más tardar para el viernes 2 de agosto

Quedo atento. 

Saludos

**Comment by gantonioid** [comment]
Por ahora no manejamos STA en scripts de PowerShell dentro de FRIDA.

Generaré una función nueva para hacer lo que necesitas. Te aviso en la tarde.

**Comment by gantonioid** [comment]
@CesarEmanuelLencina tu nueva versión debe de ser **20190731T0531**, me ayudas revisando que funcione?

Aquí la documentación: [http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/SaveClipboardImage](url)

**Comment by CesarEmanuelLencina** [comment]
La nueva instrucción funcionó a la perfección.

Muchas gracias @gantonioid.

**Comment by CristianCelano** [comment]
Hola! podrian habilitarme esta version? necesito esta misma instruccion. muchas gracias
