### ISSUE TITLE
[Excellia] [Powershell] Consulta sobre el manejo de listas.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#275]
Buen día.

Quería saber si hay alguna manera de enviar una lista desde turing a un powershell y viceversa.

Saludos.

**Comment by FaustinoLechuga** [comment]
```
DefineVariable type "string" as "IDItems"
ParseVariable "IDItem" and save as "IDItem"
RunPowerShell PS.txt
StringToList IDItems and save as IDItem
```

Mi variable "IDItem" es una lista de strings, con la instruccion parse variable la convierto en un string con una estructura especifica.

Luego regreso el mismo string en powershell como un json (conservando la misma estructura que me dio el parsevariable) y en frida lo convierto a lista con el StringToList. 

Espero esto resuelva tus preguntas y si necesitas saber algo mas especifico podemos hacer un call para explicarte o te puedo mandar algunos ejemplos.

**Comment by CesarEmanuelLencina** [comment]
Todas mis consultas quedaron resueltas en la call que hicimos.

¡Mil gracias @FaustinoLechuga!
