### ISSUE TITLE
Aplicando filtros en Excel

### ISSUE THREAD

**Issue by LizMoreno** [FridaSupport/TuringSuport#276]
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3458098/log.txt)

[NOMINA PAS.XLSX](https://github.com/FridaSupport/TuringSuport/files/3458110/NOMINA.PAS.XLSX)

Este es el log de mi proceso, no me esta  funcionando aplicar el filtro siendo que estoy copiando tal cual la instruccion ApplyFilter.

`Excel ApplyFilter to the worksheet h2 to the column with the index {2} with the criteria *<<<solver>>>*`

**Comment by FaustinoLechuga** [comment]
En la criteria estas poniendo estos simbolos * ¿por que los necesitas?, Puedes intentar solo poniendo las ""

**Comment by NehuenV** [comment]
Sin los ** intenta buscar coincidencias al 100%, con los astericos implica que haya una coincidencia parcial, es decir que el filtro contenga ese criterio

**Comment by gantonioid** [comment]
En en back-end, ApplyFilter no usa filtros de Excel, sino una lógica propia de comparación.

Intenta usar los asteriscos con la función Filter (a secas), esa sí usa filtros tal cual lo harías usando Excel manualmente (aunque no hemos probado nosotros nunca con *)
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/Filter](url)

@JuanISalazarM estará pendiente para seguimiento

**Comment by JuanISalazarM** [comment]
Lo que sucede, es que al momento de traer la variable de PowerShell, trae consigo, un caracter especial 
"\ufeff", y toma esto al momento de realizar el filtrado, por eso es que no encuentra coincidencias.

![image](https://user-images.githubusercontent.com/50111840/62331979-587fd980-b483-11e9-9f72-1b5f7ab930e8.png)

Recomendaría que elimine ese caracter con PowerShell. De todas formas, investigaremos al respecto. Sin embargo, solicito que se encargue de ese caracter especial.

**Comment by FaustinoLechuga** [comment]
```
$s = "SOTO, GUSTAVO﻿"
$s = $s.Substring(0,$s.Length - 1)
```
Con estas lineas antes de mandar la variable a frida desde el powershell se debe solucionar

**Comment by gantonioid** [comment]
> ```
> $s = "SOTO, GUSTAVO﻿"
> $s = $s.Substring(0,$s.Length - 1)
> ```
> 
> Con estas lineas antes de mandar la variable a frida desde el powershell se debe solucionar

@NehuenV @LizMoreno les sirve? se da por resuelto?

**Comment by NehuenV** [comment]
Si, el problema fue resuelto con el powershell
