### ISSUE TITLE
[Excellia] - Error en Web2 goto

### ISSUE THREAD

**Issue by ignacionovio** [FridaSupport/TuringSuport#277]
Dejó de funcionar la instrucción GoTo, adjunto el log de error
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3458524/log.txt)

**Comment by FaustinoLechuga** [comment]
Lo estaremos revisando...

**Comment by FaustinoLechuga** [comment]
Puedes borrar la carpeta de browpet-engine de la carpeta de App y abre Frida para que vuelva a descargar el archivo

**Comment by pabloreitanosofttek** [comment]
Sería bueno saber que pasó en caso de que borrar una carpeta sea la solución... ¡gracias!

**Comment by ignacionovio** [comment]
se solucionó con el borrado de la carpeta. Gracias!

**Comment by FaustinoLechuga** [comment]
Fue un caso aislado con un update de browpet que solo impacto a Ignacio pero esto ya se soluciono. Al borrar la carpeta lo que hizo turing fue actualizar browpet, esto soluciona el problema de Ignacio.
