### ISSUE TITLE
[CENTRIA] Información para cliente

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#278]
Buen día, como están?
Les dejo una preguntas que me pasó el cliente y que no tengo claras las respuestas:

- Que información que se almacena en la plataforma Frida? Es decir, que info viaja desde la VM (Turing) hacia FRIDA (plataforma en Azure)

- El canal es seguro? Es decir, de que depende? Porque al ser "pública" la plataforma (si bien necesita un usuario @Softtek es de llegada pública) puede no ser segura. 

Por ahora esas 2... prioridad media, las necesito antes del jueves 08/08. 
¡gracias!
Slds
PR

**Comment by andresCruzF** [comment]
Hola @pabloreitanosofttek 

1.- La información que se envía a la plataforma como parte del flujo de ejecución se componen de los siguiente elementos.

- bitácora de ejecución (.txt)

- Usuario

- Fecha de ejecución

- Duración de la ejecución

- Número de elementos ejecutados

- Detalle (En caso de error)

2.-  La comunicación con la base de datos se realiza mediante Https con claves de autenticación dinámicas (con tiempo máximo de expiración) lo que nos permite limitar el acceso a las bases de datos proporcionando accesos ubicaciones específicas.
https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1

![image](https://user-images.githubusercontent.com/49708627/62403965-8a15a500-b556-11e9-9bf0-7895b5b67384.png)

**Comment by pabloreitanosofttek** [comment]
Una maravilla! ¡gracias!
