### ISSUE TITLE
Necesito la sentencia "SaveClipboardImage"

### ISSUE THREAD

**Issue by CristianCelano** [FridaSupport/TuringSuport#280]
Hola!
Queria pedir que se me habilite la version que tiene la sentencia "SaveClipboardImage" debido a que necesito guardar en una direccion la imagen que tengo en el Clipboard.
Muchas gracias.

**Comment by gantonioid** [comment]
#274

**Comment by gantonioid** [comment]
Se te envió la V.**20190731T0531**  que contiene lo que solicitas

**Comment by CristianCelano** [comment]
Muchas gracias!
