### ISSUE TITLE
SAP SelectGridChk

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#281]
Buen día,
No me esta funcionando la instrucción **SAP SelectGridChk GridId wnd[0]/usr/cntlCONTROL_CUSTOM_200/shellcont/shell RowN 12 Column "CHECK" Value true**. Lo que quiero hacer es que seleccione (con la casilla Sel. de SAP) el registro que estoy buscando. 
Adjunto LOG
[log SAP SELECT.txt](https://github.com/FridaSupport/TuringSuport/files/3473122/log.SAP.SELECT.txt)
En hora 12:09:06 esta el error.

![SAP SELECT](https://user-images.githubusercontent.com/49987311/62556021-669a7500-b84a-11e9-89d7-2f35a6ce11cc.jpg)

Cualquier duda, estoy a su disposición.

Gracias!

**Comment by eradgg** [comment]
Puedes agregar un show Elements y enviármelo por favor?

**Comment by MartinJOlmedo** [comment]
[Elements.txt](https://github.com/FridaSupport/TuringSuport/files/3473201/Elements.txt)
