### ISSUE TITLE
Consulta - Tiempo Ejecución de Proceso

### ISSUE THREAD

**Issue by K-MUS** [FridaSupport/TuringSuport#282]
Estimados, hay ya antecedentes de ejecutar un proceso FRIDA por mucho tiempo ? en teoría es estable ? no es que tiene un timeout o algo así?

Estamos mejorando el Bot de reparación de cadenas de SAP en BW. Las cadenas son proceso que suelen tardar mucho. Como en teoría la idea es que el bot reintente reparar una cadena X veces (por ejemplo 5). Si una cadena tarda 1 hora en correr si hay 5 intentos puede ser que tarde hasta 5 hs ejecutando el proceso.

Queremos saber esto para saber si lo hacemos de esta forma o no, porque esto implica dejar en un ciclo repetitivo muchas veces hasta que se cumplan las condiciones de reintento de cada cadena.

**Comment by gantonioid** [comment]
No hay timeout ni restricción de tiempo que le tome al RPA. Puedes hacer tu script como lo necesites, siempre que tenga sentido y no falle en la ejecución.

**Comment by K-MUS** [comment]
Gracias Toño por la respuesta, lo que si existe una instrucción do...while, while...do o como se resolvería? con un for  y un número muy alto de interaciones con un break cuando se cumpla la condición de salida?

Pregunto porque desconozco si existe alguna de esas opciones, en la academia no está y en la docu hay solo info de readers no del core del lenguaje FRIDA. y como deberemos iterar eternamente hasta que se cumpla una condición no sabemos como hacer eso.

**Comment by gantonioid** [comment]
En la PPT 5 - Ciclos y Custom se menciona que tenemos for y forEach, ahí mismo se explica cómo se usa cada uno.
Además en la wiki hay documentación y ejemplos de cada estructura lógica de FRIDA. Eso es con lo que contamos.
[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28L%C3%B3gica%20de%20scripts.one%7Cbc21b562-0c40-46c8-ad2b-e1497d9145cb%2F%29&wdorigin=717](url)

No hay un ciclo while como tal. Tendrás que hacer combinaciones de estructuras que sirvan para tu caso.
