### ISSUE TITLE
[Consulta] Encolamiento de Archivos con M.Flow y Frida

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#283]
Buenas tardes, el cliente Finning esta haciendo pruebas, resulta que envío dos mail con archivos Excel adjuntos, el proceso de Flow se ejecuto correctamente y descargo los dos archivos, pero Flow se activo solo una vez y tomo el archivo excel con la fecha mas reciente,
Existe un encolamiento en FRIDA para que se ejecutan todos los archivos excel que entran en la carpeta?

Si requieren mas detalles o no entienden algo puedo tener una call.
Gracias

**Comment by gantonioid** [comment]
Flow sirve únicamente como trigger del RPA. **Tü** tienes que manejar el caso en el que existan múltiples archivos adjuntos. Desconozco las instrucciones de Finning en este caso pero por ejemplo:
_Podrías hacer un llamado al API de runprocess por cada archivo adjunto, así FRIDA lo entiende y podría ejecutar uno tras otro._

**Comment by victorgamboa** [comment]
una consulta, de donde se saca el TaskID para hacer el llamado y ver la cola que esta actualmente?

@ignacionovio podríamos ver lo que dice @gantonioid?

**Comment by victorgamboa** [comment]
Cerré el modo Listener de Frida y lo volví a ejecutar y se activo el bots con la ejecución que estaba pendiente.

**Comment by gantonioid** [comment]
El TaskID es el resultado de la llamada al api runprocess. No se puede ver la cola de ejecución, solo revisar el estatus de un TaskID y/o borrar la cola.

> Cerré el modo Listener de Frida y lo volví a ejecutar y se activo el bots con la ejecución que estaba pendiente.

@victorgamboa ese es el funcionamiento esperado, para evitarlo tienes que borrar la cola. Los invito a revisar la documentación de estas APIs, solo tenemos tres

- RunProcess
- ExecutionStatus
- ClearExecutionQueue

[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/15/WopiFrame.aspx?sourcedoc={34a129d9-bd31-4f99-9c3d-1267675ca36f}&action=edit&wd=target%28Remoto%20y%20Scheduling.one%7C21c7d51f-bc2f-4d07-9e52-ba06e3cee982%2FAPIs%20de%20FRIDA%20ejecuci%C3%B3n%20remota%7Cbf4b6ca9-a4a1-4726-94e0-22941d7d032f%2F%29&wdorigin=703](url)

**Comment by gantonioid** [comment]
Pregunta contestada
