### ISSUE TITLE
[Excellia] Teclado Virtual - banco colombia

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#284]
Se necesita poder dar clic a las letras y al boton de Bl. May, del teclado virtual de la siguiente pagina:
https://sucursalempresas.transaccionesbancolombia.com/SVE/control/BoleTransactional.bancolombia

![image](https://user-images.githubusercontent.com/25591982/62574837-c3f4ed00-b86f-11e9-85f5-bf47025c1239.png)

Con instrucciones similares a otros teclados no se logro conseguir que funcione.
Web2 Click in xpath="//div[contains(text(),'a')]"
Fecha de necesidad de resolucion 9/8

**Comment by gantonioid** [comment]
Hola @SoledadNunez veo que los primeros dos campos funcionan con el InsertValue y/o Type tradicionales de Web2, ejemplo:
InsertValue "Hello" in id="CLIENTID"

Para el tercer campo (la contraseña) probablemente requerimos un desarrollo custom.

**Comment by SoledadNunez** [comment]
si, con los primeros no tengo inconveniente con un InserValue, el tema es la contraseña, solo logre insertar números con el xpath de otros teclados, pero no letras.

**Comment by gantonioid** [comment]
Se creó una nueva función para ti. Cada botón de ese teclado tiene un evento `onClick` asignado, por favor usa la siguiente función, enviando writeAlpha('P') para escribir una P por ejemplo... solo fíjate que tengas el foco en el campo deseado
[http://automationplatform.azurewebsites.net/Readers/Tools/Browpet/Evaluate](url)

**Comment by SoledadNunez** [comment]
Funciona sin inconvenientes, muchas gracias.

Cierro el tk.
