### ISSUE TITLE
[TITAN] agregar instruccion "SaveClipboardImage" en Turing offline del cliente

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#285]
Buenas,

Estaria necesitando que en el Turing offline que se encuentra en la vm del cliente, se incorpore la instrruccion "SaveClipboardImage" hoy en dia al querer utilizarla el log indica:

"Instruction was´t found"

Prioridad Alta.
Gracias.

**Comment by JuanIgnacioBurgos** [comment]
Similar a la resolucion de los tickets #274 y #280

**Comment by JuanIgnacioBurgos** [comment]
Hola, hay posibilidad de agregar esta funcion el dia de hoy antes del medio dia?

@FridaSupport  @pablorlmx

**Comment by RickProductivity** [comment]
A qué hora es tu medio día ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pablorlmx** [comment]
Estamos en etapa de UAT con el cliente y lo necesitamos lo antes posible. Favor de priorizar.

**Comment by pablorlmx** [comment]
Tres horas más.

**Comment by RickProductivity** [comment]
Está apretado por que es Apenas a las 1030 y nos deja con poco tiempo desde que llegan a trabajar,  @Faustino Gerardo Villarreal Lechuga<mailto:faustino.villarreal@softtek.com>  como ves ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by FaustinoLechuga** [comment]
Creo que solo es un update, me pongo en contacto con Juan Burgos para que le haga el update

**Comment by LizMoreno** [comment]
Buenas,
 Yo tambien necesito la instrución en turing "SaveClipboardImage"
Actualmente me aparece en el log:

Error in saveclipboardimage Instruction was't found

Mi version de turing:
![imagen](https://user-images.githubusercontent.com/20973539/62793318-b3c75280-baa7-11e9-8cd5-57a0ef35fe33.png)

Prioridad Alta.
Gracias.
Liz.moreno

**Comment by pablorlmx** [comment]
Estimados, alguna novedad? Sumo también a @pabloreitanosofttek e @ignacionovio

**Comment by FaustinoLechuga** [comment]
Estoy viendo el update del turing offline con Juan Ignacio y le acabo de liberar a Liz un update que ya contine el cambio (20190809T0547)

**Comment by LizMoreno** [comment]
Faustino, acabo de probar el proceso pero no me esta abriendo los excel despues de la actualización, y los necesito para utilizar la instrucción SaveClipboardImage

**Comment by pabloreitanosofttek** [comment]
@JuanIgnacioBurgos ? 

@FaustinoLechuga  no está jalando la solución... porfa apoyo! 

¡gracias!

**Comment by JuanIgnacioBurgos** [comment]
Hola, comento que Faustino ya me envio el archivo necesario.
Por el momento no tuve chance de probarlo ya que nos encontramos en UAT y el usuario se encuantra haciedo sus respectivas pruebas, en cuanto tenga oportunidad lo voy a probar y les comento como me fue.


Gracias por el apoyo.

**Comment by FaustinoLechuga** [comment]
@LizMoreno intenta desactivando el "Headless Process" antes de correr la automatizacion.

**Comment by LizMoreno** [comment]
> 
> 
> @LizMoreno intenta desactivando el "Headless Process" antes de correr la automatizacion.

Gracias!

**Comment by JuanIgnacioBurgos** [comment]
Ya pude probarlo, funciona de forma correcta, gracias Faustino por la ayuda y les pido disculpas por la demora.

Saludos
