### ISSUE TITLE
[Urgente][Cola de archivos de FRIDA] Error al ejecutar un encolamiento 

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#287]
Sigo con el problema de la ejecución en el encolamiento de los procesos en FRIDA, al enviar dos mails seguidos, el proceso se desencadena solo una vez. Pero si espero un tiempo entre 10 a 15 minutos en el envío de un mail el proceso se ejecuta correctamente.

@ignacionovio
Si tienes algo que aportar, pido tu ayuda.

**Comment by gantonioid** [comment]
No habías descrito así tu problema en el ticket anterior.
Flow tiene límites, y eso depende del plan que se tenga en la cuenta que lo está procesando.

https://us.flow.microsoft.com/en-us/pricing/

En el caso gratuito, se tienenlo siguiente
Free
2,000 runs per month
Unlimited Flow creation
5-min checks
Connect to embedded Office 365 or Dynamics services

**Comment by gantonioid** [comment]
Eso quiere decir que procesa un mail (evento de flow) cada 5 minutos. Y no sé cómo lo manejé Microsoft, pero no sería entonces cuestión de FRIDA

**Comment by ignacionovio** [comment]
@victorgamboa, si no me equivoco el cliente manifestó que el proceso de Flow se disparó correctamente en todos los casos, pero no siempre desencadenó el bot en Frida, podrías confirmarnos si fue así revisando el historial de Flow?

**Comment by victorgamboa** [comment]
@ignacionovio Correcto, se dispararon correctamente los procesos en FLOW. No así FRIDA, que se disparo solo 1 vez

**Comment by gantonioid** [comment]
Si se fijan en su misma imagen... hay tres que el correo indica como fallidas, que asumo yo corresponden a las tres que tienen "Hora de inicio" a las 15:09

Pueden ustedes probar la API de FRIDA por aparte, para verificar que funciona, las llamadas deben de retornar un número (ese es el TaskID, pueden consultar luego el estatus de cada una con la otra API de ExecutionStatus

Como información adicional pueden inspeccionar paso a paso cada registro de ejecución de FLOW y ver exactamente dónde está la falla. ¿Llegó o no al paso de enviar la llamada a FRIDA?

**Comment by ignacionovio** [comment]
@victorgamboa, podrías verificar lo que consulta @gantonioid? gracias!

**Comment by victorgamboa** [comment]
Según la prueba que adjunte en Teams (Video) acá esta el proceso que fallo, aparecen con estado Correcto.

![image](https://user-images.githubusercontent.com/49756748/62710304-0e3bb280-b9c5-11e9-886f-d68656910fcd.png)

**Comment by ignacionovio** [comment]
@victorgamboa  Si entras a los detalles de ambas y vas al paso en el que llama a frida, esta ok la llamada?

**Comment by victorgamboa** [comment]
Correcto,

![image](https://user-images.githubusercontent.com/49756748/62710870-147e5e80-b9c6-11e9-8bd9-c5116b57b015.png)

**Comment by gantonioid** [comment]
No se ve ahí la respuesta de FRIDA, pero ya probaron también con Postman o cURL ? eso para verificar el funcionamiento del API directamente (sin FLOW)

**Comment by ignacionovio** [comment]
@gantonioid, en la prueba que hizo @victorgamboa, se enviaron dos emails (que son los desencadenan el flujo de Flow) con diferencia de segundos uno del otro. Flow en su historial registró ambos flujos a las (14:43:06). En ambos casos se ejecutó la llamada a Frida con el método POST. Pero el bot de Frida solo se ejecutó una vez. No sabemos como obtener el TaskID para identificar cual de esas llamadas fue la exitosa y cual no. Como podemos verificar esto?
![thumbnail_image001](https://user-images.githubusercontent.com/49729569/62727342-ac447280-b9ef-11e9-963a-2493aa995081.png)

**Comment by gantonioid** [comment]
Tema tratado en una llamada por Teams. Se aclaró la descripción del problema, y se demostró correcto funcionamiento.

De nuevo, se mencionó que FLOW tiene limitantes
[https://us.flow.microsoft.com/en-us/pricing/](url)
