### ISSUE TITLE
[Excellia] La instrucción Web2 Custom "EnterSunat" no esta resolviendo el captcha correctamente. Necesidad: Urgente. Bot productivo.

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#289]
Esta es la instrucción en el script: 

Web2 Custom "EnterSunat" clave="<<<xlsClaveSUNAT>>>" usuario="<<<xlsUsuarioSUNAT>>>" ruc="<<<xlsRUC>>>"

El log dice lo siguiente: 

8/8/2019 1:18:17 PM - Web2 Sleep 5000 : Running
8/8/2019 1:18:23 PM - Web2 Sleep 5000  : Success
8/8/2019 1:18:23 PM - Web2 Custom "EnterSunat" clave="xxx" usuario="xxx" ruc="xxx": Running
8/8/2019 1:18:29 PM - {"error":"request to http://api.anti-captcha.com/createTask failed, reason: read ECONNRESET"}
8/8/2019 1:18:29 PM - Web2 Custom "EnterSunat" clave="xxx" usuario="xxx" ruc="xxx" : Error

El error sucede tanto desde mi maquina como desde la maquina virtual del cliente.
Cualquier cosa que necesiten me avisan.

Gracias.

**Comment by MartinMedinaSTK** [comment]
Otro error que da:

8/8/2019 11:54:50 AM - Web2 Custom "EnterSunat" clave="xxx" usuario="xxx" ruc="xxx": Running
8/8/2019 11:54:50 AM - Runing browpet-engine
8/08/2019 11:55:03 - {"error":"Error creating task"}
8/8/2019 11:55:03 AM - Web2 Custom "EnterSunat" clave="xxx" usuario="xxx" ruc="xxx" : Error

**Comment by gantonioid** [comment]
@MartinMedinaSTK sigue el problema?

**Comment by gantonioid** [comment]
Veo que las peticiones de solucion de recaptcha a la plataforma no han parado de llegar, a excepción del 4, 5 y 11 de agosto. (El pico del 8 de agosto - fecha de tu reporte -, es de 41 peticiones)
![image](https://user-images.githubusercontent.com/9600868/62898494-3efc4e80-bd1b-11e9-8050-45e5f4e75352.png)

Toma en cuenta que probablemente, la solución tome más tiempo del que tenemos de timeout (50 segundos), y entonces puede dar error. Además, es un captcha, el servicio puede solucionarlo de forma incorrecta de vez en vez.

**Comment by MartinMedinaSTK** [comment]
por el momento no se volvió a repetir este error, lo que si notamos es que antes en uno o dos intentos ya se resolvía el captcha, ahora se necesitan 5 intentos normalmente para resolverlo, y aún así a veces termina dando error luego del 5to intento.  Para que lo tengan en cuenta.

Por el momento este issue lo cierro.
