### ISSUE TITLE
[Excellia] Extraer un archivo de un archivo comprimido - CONSULTA

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#290]
Se necesita poder extraer un documento de un archivo comprimido, ¿existe alguna función que me permita hacer eso? 
Necesidad de respuesta, dentro del día de hoy.

**Comment by gantonioid** [comment]
[https://stackoverflow.com/questions/27768303/how-to-unzip-a-file-in-powershell](url)
