### ISSUE TITLE
[TITAN][Urgente] Titanium hace clicks defasados

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#291]
Buenas,

Estoy notando que un proceso que se encuentra corriendo en un vm esta fallando por hacer click defasados.
Hasta el dia Viernes el proceso reconocia de forma correcta y clickeaba bien las imagenes.

Por favor les pido apoyo con este tema.
@FridaSupport @gantonioid @pablorlmx @pabloreitanosofttek

**Comment by RickProductivity** [comment]
Ahí más que nada hay que ver qué el ambiente esté bien o no haya cambiado la resolución o cosas de esas como quiera lo revisamos pero si pidieras ver si alguien le hizo cambios a la VM (indagar con los diferentes equipos) qué cambios se le hicieron , por que es relativamente común que el equipo de infra haga cambios y no comunique o qué existan problemas de Red

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pabloreitanosofttek** [comment]
Esto es parte de la entrega de hoy? De ser así porfa celeridad a este tema
Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: JuanIgnacioBurgos <notifications@github.com>
Enviado: lunes, agosto 12, 2019 11:38 a.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: [FridaSupport/TuringSuport] [TITAN][Urgente] Titanium hace clicks defasados (#291)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Buenas,

Estoy notando que un proceso que se encuentra corriendo en un vm esta fallando por hacer click defasados.
Hasta el dia Viernes el proceso reconocia de forma correcta y clickeaba bien las imagenes.

Por favor les pido apoyo con este tema.
@FridaSupport<https://github.com/FridaSupport> @gantonioid<https://github.com/gantonioid> @pablorlmx<https://github.com/pablorlmx> @pabloreitanosofttek<https://github.com/pabloreitanosofttek>

**Comment by JuanIgnacioBurgos** [comment]
@RickProductivity Estuve revisando lo de la resolucion que mencionas, pero la misma no ha cambiado, ¿ algun otro parametro puede estar interfiriendo?

**Comment by gantonioid** [comment]
Si no mal recuerdo... se parece a uno de los primeros temas que tratamos con @MartinMedinaSTK

La compu tenía una resolución, pero para Titanium era otra diferente y salía con bordes negros... Recuerdan? @andresCruzF

**Comment by JuanIgnacioBurgos** [comment]
Por el momento algunos clicks los estoy pudiendo sortear mediante shortcuts, en otros casos no tengo mas altenativa que el reconocimiento de imagen.

**Comment by JuanIgnacioBurgos** [comment]
Alguna idea de como hacer que el reconocimiento de imagenes vuelva a funcionar?

**Comment by MartinMedinaSTK** [comment]
@JuanIgnacioBurgos hay un PowerShell para cerrar la sesión de la maquina virtual que hace que la sesión de usuario quede activa aún cuando estás desconectado de la máquina. En ese PowerShell podes configurar la resolución de pantalla que necesitas que tenga para que el bot corra bien.   Cuando estas conectado a la maquina tampoco funciona?

**Comment by pabloreitanosofttek** [comment]
@JuanIgnacioBurgos ?

**Comment by JuanIgnacioBurgos** [comment]
el proceso lo estoy ejecuntando con la sesion iniciada y la pantalla prendida

**Comment by RickProductivity** [comment]
Entocnes ya funciona?

**Comment by JuanIgnacioBurgos** [comment]
Hola

he reemplazado el maximo posible de clicks en imagenes por atajos de teclado, desafortunadamente, en ciertos pasos no me queda otra alternativa mas que el reconocimiento de imagenes.
Podre tener una call el dia de mañana con alguno de los chicos de mx para ver este tema?

**Comment by pablorlmx** [comment]
Estimados,

Por favor necesitamos su apoyo directo a Juan (acompañamiento por call) para resolver esta situación; mañana vamos a tratar de convencer al cliente de no retrasar el plan para no tener mayor impacto, no obstante mañana tenemos que poder tener resuelto esto; por favor su comprensión y ayuda.

________________________________

**Comment by pabloreitanosofttek** [comment]
Este es el ticket más importante de la lista. ¡Gracias!

**Comment by JuanIgnacioBurgos** [comment]
Adjunto la imagen @gantonioid 
<img width="1025" alt="Found" src="https://user-images.githubusercontent.com/49756974/62949953-2b052b00-bdb5-11e9-86ef-6c973b51316c.png">

**Comment by gantonioid** [comment]
Tuve sesión por Teams con JuanIgnacio; el problema es **exactamente** el mismo que tuvimos con @MartinMedinaSTK hace meses. Titanium encuentra la imagen, pero hace click en otro lado porque las dimensiones _que se ven en el monitor_, no son las dimensiones _con que se toma el screenshot_ en tiempo de ejecución de Titanium.

Esta solución se puede compartir con Juan? @andresCruzF @MartinMedinaSTK

**Comment by andresCruzF** [comment]
Hola @JuanIgnacioBurgos 

Podriamos tener una llamada a las 1pm (Hora Mexico) para revisar este error, de igual forma me podrias confirmar si la maquina a la cual nos estamos conectando es una maquina virtual o una computadora de escritorio.

**Comment by JuanIgnacioBurgos** [comment]
@andresCruzF perfecto, agendo la call, comparto tambien las especificaciones de la maquina virtual compartido por el usuario:
![Untitled11](https://user-images.githubusercontent.com/49756974/62961285-dec8e380-bdd2-11e9-99be-79865973b2a3.png)

**Comment by JuanIgnacioBurgos** [comment]
Buenas, el dia de ayer estuve viendo este tema con Andres, por el memento él se encuentra realizando los ajustes necesarios para generar una nueva version especifica para la vm del cliente.

Quedo al pendiente.
Saludos.

**Comment by JuanIgnacioBurgos** [comment]
Hola, 

Aun no tuve respuesta de Andres...


por favor les pido apoyo @FridaSupport  @pabloreitanosofttek  @RickProductivity

**Comment by pablorlmx** [comment]
Estimados, necesitamos esto con urgencia, alguna novedad?

________________________________

**Comment by RickProductivity** [comment]
Esta Andrés trabajando en eso

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pablorlmx** [comment]
Gracias Ricardo.

Dado que habían comprometido para inicio del día, cuál sería la nueva hora? Mira que transmitimos esto al cliente y ahora nos está a cada rato preguntando
________________________________

**Comment by andresCruzF** [comment]
Hola @pablorlmx 

El problema a quedado resuelto quedamos a la espera de que @JuanIgnacioBurgos  nos confirme que los robots se encuentran ejecutando sin problemas.

Saludos.

**Comment by pablorlmx** [comment]
Qué buena noticia!

Gracias por el apoyo y esperamos que todo resulte bien.

**Comment by JuanIgnacioBurgos** [comment]
Buenos dias,

Me tome todo el dia de ayer para realizar pruebas con esta nueva version que me compartio Andres. En cuanto al reconocimiento de imagenes no tuve ningun problema.
Detecte un unico error en un ReadColumun, el mismo se esta tomando aproximadamente 10 minutos en leer 100 celdas (o incluso menos), algo que con la antigua version no demandaba mas de un par de segundos.

Para asegurarme de que el problema no se produzca por otro motivo corri el proceso con ambas versiones de Turing y efectivamente con la version nueva se demora 10 minutos mientras que con la anterior 2 segundos:

### Log Turing viejo:

```
8/16/2019 9:59:18 AM - DefineVariable type "List" as "CELDA1s": Running
8/16/2019 9:59:18 AM - MixReader : Se agrego una nueva variable : 
Var Name : CELDA1s
Value : 
8/16/2019 9:59:18 AM - DefineVariable type "List" as "CELDA1s" : Success
8/16/2019 9:59:18 AM - Excel ReadColumn from the worksheet Hoja19 with the column index {1} and save its value as {CELDA1s}: Running
8/16/2019 9:59:19 AM - Se cambio la variable : 
Var Name : CELDA1s
Value : FECHA ; 43682 ; 43682 ; 43682 ; 43682 ; 43682 ; 43682 ; 43682 ; 43682
8/16/2019 9:59:19 AM - Excel ReadColumn from the worksheet Hoja19 with the column index {1} and save its value as {CELDA1s} : Success
```

### Log Turing Nuevo:
```
8/16/2019 8:53:37 AM - DefineVariable type "List" as "CELDA1s": Running
8/16/2019 8:53:37 AM - MixReader : Se agrego una nueva variable : 
Var Name : CELDA1s
Value : 
8/16/2019 8:53:37 AM - DefineVariable type "List" as "CELDA1s" : Success
8/16/2019 8:53:37 AM - Excel ReadColumn from the worksheet Hoja19 with the column index {1} and save its value as {CELDA1s}: Running
8/16/2019 9:02:46 AM - Se cambio la variable : 
Var Name : CELDA1s
Value : FECHA ; 43682 ; 43682 ; 43682 ; 43682 ; 43682 ; 43682 ; 43682 ; 43682
8/16/2019 9:02:46 AM - Excel ReadColumn from the worksheet Hoja19 with the column index {1} and save its value as {CELDA1s} : Success

```
Como pueden ver la misma instruccion y la misma cantidad de registros. Es el mismo proceso ejecutado con dos versiones de Turing.
Adjunto ambos logs para su analisis.

[log ultima version .txt](https://github.com/FridaSupport/TuringSuport/files/3509953/log.ultima.version.txt)
[log version antigua.txt](https://github.com/FridaSupport/TuringSuport/files/3509954/log.version.antigua.txt)

**Comment by andresCruzF** [comment]
Hola @JuanIgnacioBurgos 

Validare los cambios que se realizon en la funcion de ReadColumun para poder darle solucion a este problema a la brevedad.

Saludos.

**Comment by pablorlmx** [comment]
Estimados,

Por lo que revisamos con Juan queda pendiente un arreglo de algo que se "alentó" con esta nueva implementación. Tienen alguna novedad?

________________________________
From: Pablo Romero <pablorl@outlook.com>
Sent: Wednesday, August 14, 2019 19:41
To: FridaSupport/TuringSuport <reply@reply.github.com>; FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [FridaSupport/TuringSuport] [TITAN][Urgente] Titanium hace clicks defasados (#291)


Qué buena noticia!



Gracias por el apoyo y esperamos que todo resulte bien.

**Comment by pabloreitanosofttek** [comment]
Es solo lentitud?  O cambio algo del funcionamiento?

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

________________________________

**Comment by pablorlmx** [comment]
Lentitud al parecer. Se corrigió y el usuario del cliente realizó una prueba y volvió a fallar 🙁
________________________________

**Comment by andresCruzF** [comment]
Hola @pablorlmx Me podrian confirmar en que ambiente se realizo la prueba y si esta se realizo con conexion a la maquina virtual o de manera remota. Se le libero a Juan una version por lo cual desconozco si esta se instalo en algun otro ambiente diferente al que utilizo Juan para realizar pruebas.

**Comment by pablorlmx** [comment]
Estimados.

Ya Juan revisó el tema y pudo corregir el problema en la máquina donde el cliente está probando.

Gracias por la atención y seguimiento.
