### ISSUE TITLE
[Error al crear un Excel desde Frida con caracteres especiales]

### ISSUE THREAD

**Issue by FedericoRocha** [FridaSupport/TuringSuport#292]
Buenos dias, estoy teniendo un error al crear un Excel desde frida cuyo nombre deseo que tenga caracteres especials, los cuales se que Excel acepta normalmente en la creacion de archivos Ej("-"," _"). Sucede cuando tomo una variable fecha desde powershell la cual reemplazo las / por _ para que sean caracteres permitidos por Excel, pero aun asi cuando la variable es reconocida desde Frida, la unica opcion que tengo es utilizar espacios. Queria saber si hay alguna forma de poder utiliar algun caracter o alguna otra manera. Gracias.

**Comment by JuanISalazarM** [comment]
Gracias por ponerse en contacto con nosotros. Lo atenderemos a la brevedad.

**Comment by RickProductivity** [comment]
Federico Yo avanzaría así por lo pronto , saludos

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gantonioid** [comment]
@FedericoRocha Asumo que este issue es con la instrucción [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/NewWB](url)

De hecho, tampoco debería de aceptarte espacios porque en el diccionario de libros abiertos, las llaves se manejan como string de una sola palabra (sin espacios)

@JuanISalazarM Considera por favor otra función de crear libro que corrija esto: permitir especificar nombre de archivo, pero también definir una wb_key válida (sin espacios)

**Comment by JuanISalazarM** [comment]
Por supuesto, me haré cargo. Gracias por las observaciones. En cuanto corrija este detalle lo notificaré.

**Comment by JuanISalazarM** [comment]
Se ha realizado una actualización a su versión de Turing. Solicitamos de favor realice pruebas para verificar que se ha podido solucionar el problema.
Gracias por su atención. Estamos atentos a su respuesta.

**Comment by FedericoRocha** [comment]
Buenos dias, se realizo la actualización , pero ahora al querer ingresar  a Frida luego de que la actualización finalizara, me indica que no tengo activado Frida en mi equipo siendo que desde la pagina estaria todo activado  .
________________________________
De: JuanISalazarM <notifications@github.com>
Enviado: lunes, 12 de agosto de 2019 19:17
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
Cc: FedericoRocha <a7x126@hotmail.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] [Error al crear un Excel desde Frida con caracteres especiales] (#292)


Se ha realizado una actualización a su versión de Turing. Solicitamos de favor realice pruebas para verificar que se ha podido solucionar el problema.
Gracias por su atención. Estamos atentos a su respuesta.

**Comment by gantonioid** [comment]
@FedericoRocha Como admin en la plataforma veo que tienes 14 Turings registrados a tu nombre, y muchos son en la misma máquna "LSTKBA227617". De ellos, 6 no tienen tu aprobación. Haré una limpia porque tienes demasiados Turings y puede ser que haya confusión. Eso no impacta el funcionamiento, ya que puedes volver a activar las aplicaciones que realmente uses.

**Comment by FedericoRocha** [comment]
Muy bien entonces una vez realiazada la limpieza verificare de tener activada la version de Turing que estoy usando actualmente. Muchas gracias
________________________________
De: gantonioid <notifications@github.com>
Enviado: martes, 13 de agosto de 2019 09:53
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
Cc: FedericoRocha <a7x126@hotmail.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] [Error al crear un Excel desde Frida con caracteres especiales] (#292)


@FedericoRocha<https://github.com/FedericoRocha> Como admin en la plataforma veo que tienes 14 Turings registrados a tu nombre, y muchos son en la misma máquna "LSTKBA227617". De ellos, 6 no tienen tu aprobación. Haré una limpia porque tienes demasiados Turings y puede ser que haya confusión. Eso no impacta el funcionamiento, ya que puedes volver a activar las aplicaciones que realmente uses.

**Comment by gantonioid** [comment]
Listo, puedes verificar

**Comment by FedericoRocha** [comment]
Intente ingresar nuevamente al programa de FRIDA sin exito , pero en este caso no me indica ningun mensaje de error y al menos por mi parte desde la plataforma estaria viendo que esta todo activado correctamente.
________________________________
De: gantonioid <notifications@github.com>
Enviado: martes, 13 de agosto de 2019 10:01
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
Cc: FedericoRocha <a7x126@hotmail.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] [Error al crear un Excel desde Frida con caracteres especiales] (#292)


Listo, puedes verificar

**Comment by gantonioid** [comment]
Se tuvo sesión por Teams; descargamos un Turing nuevo, se recibieron los updates pendientes y se activó en la plataforma. El usuario probará el funcionamiento.

**Comment by FedericoRocha** [comment]
Se realizo prueba y todo funciona con normalidad nuevamente. Muchas gracias. Saludos.
________________________________
De: gantonioid <notifications@github.com>
Enviado: martes, 13 de agosto de 2019 10:57
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
Cc: FedericoRocha <a7x126@hotmail.com.ar>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] [Error al crear un Excel desde Frida con caracteres especiales] (#292)


Se tuvo sesión por Teams; descargamos un Turing nuevo, se recibieron los updates pendientes y se activó en la plataforma. El usuario probará el funcionamiento.

**Comment by gantonioid** [comment]
(La aprobación de Turing se resolvió)... las pruebas que se esperan son las de la solución otorgada por @JuanISalazarM

**Comment by gantonioid** [comment]
Excelente, gracias
