### ISSUE TITLE
Excel ReadRows update URGENTE

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#293]
Buenas tardes, quiero usar el comando ReadRows de Excel con la variable update (porque lo corro dentro de un for y me da error cuando lo lee por segunda vez). Actualicé hoy Turing. Puede ser que lo tengan que habilitar?

El problema es parecido al que tuvo un compañero en el issue #258 

Log:
![ReadRows update log](https://user-images.githubusercontent.com/49987311/62969898-a3371500-bde4-11e9-8df7-0a496fdfe950.jpg)

El problema esta cuando entra en el **try** del log 16:05:02, no hace nada y sale al **catch**.

Script
![ReadRows update script](https://user-images.githubusercontent.com/49987311/62969902-a6320580-bde4-11e9-931b-7286d5bf3e63.jpg)

Version de Turing: 201990730T1006

Muchas gracias!

**Comment by MartinMedinaSTK** [comment]
Hola @gantonioid , ¿nos podrás dar una mano con esto? este cambio lo necesitamos medio urgente, tenemos una demo mañana y tenemos que agregar un cambio que necesita esta instrucción.

Gracias, quedamos a la espera.

**Comment by gantonioid** [comment]
No me queda clara la petición. El 258 lo atendió @JuanISalazarM de qué se trata?

**Comment by MartinJOlmedo** [comment]
Yo estoy corriendo dentro de un for para una cantidad variable de veces, y quiero hacer un ReadRows dentro de ese for para filtrar unos datos. Cuando lo hace por primera vez, funciona correctamente, pero cuando corre por segunda vez, me da error ReadRows (dice en el log: ya se agregó un elemento con la misma clave). 
Un compañero tuvo un evento similar y a partir de eso generaron el comando **ReadRows from {wsKey} start_at {rowIndex} as {varKey} update**. 
El inconveniente que estoy teniendo yo es que cuando pongo **update** al final del comando y quiero recorrerlo con un foreach, no lo hace. En el log no figuran datos, se puede ver en la hora 16:05:02 lo siguiente: 
**try block running
catch block running
catch block end
try block end**
cuando en el script, despues del **try** tengo la lógica para filtrar mis datos, empezando con el **foreach Reg in RegistrosParcial**.
Yo creo que es porque no tengo una versión con este comando habilitado.

**Comment by MartinJOlmedo** [comment]
Cualquier duda lo podemos ver en una call.

**Comment by JuanISalazarM** [comment]
Posiblemente se trate por la versión de Turing.
Se le ha realizado una actualización. Podría porfavor realizar la prueba nuevamente.
Si eso no funciona. Solicito de favor ingrese el script, junto con el archivo de prueba porfavor.
Gracias por su atención. Estamos atentos a su respuesta.

**Comment by MartinJOlmedo** [comment]
No se solucionó.Adjunto los datos de prueba

[script.txt](https://github.com/FridaSupport/TuringSuport/files/3498802/script.txt)
[BancosFBL3N738 PRUEBA.xlsx](https://github.com/FridaSupport/TuringSuport/files/3498803/BancosFBL3N738.PRUEBA.xlsx)
[cambio.txt](https://github.com/FridaSupport/TuringSuport/files/3498804/cambio.txt)
[guionporespacio.txt](https://github.com/FridaSupport/TuringSuport/files/3498805/guionporespacio.txt)

**Comment by MartinJOlmedo** [comment]
Cambio y guionporespacio son dos powershell

**Comment by JuanISalazarM** [comment]
Ya vi el error.
Se encuentra en esta línea de código.
`Excel ReadRows from hojaextra start_at 1 as RegistrosParcial update`

Para utilizar la función "update", es necesesario utilizar llaves, para señalar las keys necesarias.
Linea corregida:
`Excel ReadRows from {hojaextra} start_at {1} as {RegistrosParcial} update`

Anexo la documentación donde se encuentra un ejemplo con la función "update"
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ReadRowsAsList

Señala error porque no encontraba la variable, porque nunca se creó.

Solicito de favor realizar la prueba con la línea corregida.

Gracias por su atención. Estamos atentos a su respuesta.

**Comment by MartinJOlmedo** [comment]
Problema resuelto, muchas gracias!!!
