### ISSUE TITLE
[RPA INTERNO] Generacion de turing off para el cliente interno

### ISSUE THREAD

**Issue by DianaSTK** [FridaSupport/TuringSuport#295]
Responsable: Diana Martinez
Nombre proceso: Envío de Recibos de Sueldo CL
ID: 1484870469
Necesidad: Urgente, (antes del 02 de SEPTIEMBRE)

Aclaración: RPA interno es para procesos de Softtek SSH
Cualquier consulta a disposición.
Saludos,
Diana Martínez.-
dmartinez@softtek.com

**Comment by RickProductivity** [comment]
Diana este proceso toca el SAP?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Johhnn117** [comment]
Buenos días @DianaSTK te comparto la carpeta por Teams
