### ISSUE TITLE
[MixedReader-ParseExactDate] Error al usar instrucción ParseExactDate

### ISSUE THREAD

**Issue by VeroPaz** [FridaSupport/TuringSuport#296]
Necesito convertir una fecha de formato: dd-MM-yyyy a: dd-MMM-yyyy, ejemplo: de 12-08-2019 a 12-ago-2019, pero con la instrucción no está resultando, indica que la instrucción no se encuentra.
[logParseDate.txt](https://github.com/FridaSupport/TuringSuport/files/3517731/logParseDate.txt)

el código: 
ParseExactDate from {<<FechaConsultada>>} input {dd-MM-yyyy} to output {dd-MMM-yyyy es} and save as {Date}

--> la variable <<FechaConsultada>> viene en el formato indicado.

**Comment by Johhnn117** [comment]
Tu variable `<<FechaConsultada>>` es de tipo Date, puedes cambiarla a tipo string como se muestra en la imagen y volver a correr el proceso?
![image](https://user-images.githubusercontent.com/50710733/63301759-fefc1500-c2a0-11e9-99e8-b78978bb7342.png)

**Comment by VeroPaz** [comment]
Si lo probé, también entregándole el dato directamente y no funciona.

**Comment by ignacionovio** [comment]
Lo acabo de probar y a mi me funciona, aunque el resultado que trae es "02-ago.-2019" en lugar de "02-ago-2019" para la instrucción "ParseExactDate from {02-08-2019} input {dd-MM-yyyy} to output {dd-MMM-yyyy es} and save as {Date}".

![image](https://user-images.githubusercontent.com/49729569/63347661-f56cbe80-c32d-11e9-8d54-b1c4d6a79693.png)

**Comment by VeroPaz** [comment]
Descargué una nueva versión, y aún figura el mismo error

**Comment by Johhnn117** [comment]
lo podemos checar en una llamada?

**Comment by Johhnn117** [comment]
El problema era la versión de Turing de @VeroPaz , se mandó un update lo cual corrigió el problema
