### ISSUE TITLE
Excel, correr macros y editar archivos .xlsm

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#32]
Buen dia, les adjunto nuevamente el excel con el que estoy trabajando, estaria necesitando cargar en el mismo una serie de datos, los cuales no estan quedando guardados, para luego una vez que toda la informacion este cargada ir a la solapa de "asiento" y darle click al voton "Ejectar_Macro" para justamente ejecutar la macro.
Necesitaria una mano para realizar esto desde FRIDA.

[Cuadratura Macro FCV ETV 2-Abr-2019; Prosegur_.zip](https://github.com/FridaSupport/TuringSuport/files/3127380/Cuadratura.Macro.FCV.ETV.2-Abr-2019.Prosegur_.zip)

Por favor atender este tema con caracter URGENTE, ya que es clave para seguir avanzando, con el desarrollo del proceso, el cual tiene fecha de entrega ya establecida.

PD: es la segunda vez que cargo el issue ya que la primera ha sido eliminado, sin ser atendido previamente.
Saludos.

**Comment by gantonioid** [comment]
Puedes compartir qué fue lo que intentaste tú antes de cargar el issue @JuanIgnacioBurgos ?
Probaste usar la función RunMacro?  [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/RunMacro](url)

**Comment by JuanIgnacioBurgos** [comment]
Hola, la documentacion de esta instrucicon esta poco clara, no entiendo a que hace referencia el parametro "macro name", que iria en ese campo, ¿el nombre del archivo?¿como puedo saber el nombre de la macro?
De todas formas no he podido cargar correctamente el archivo y editarlo desde FRIDA, es decir, todos los cambios que hago no quedan guardados, no se a que se debe esto.

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid aqui por ejemplo, abro el archive de la macro, junto con un segundo excel, y quiero hacer un copiado de ciertas columnas:

###########Carga de Excel Cuadratura Macro FCV ETV 2-Abr-2019; Prosegur ########################################################################################################################
Excel LoadWBook "C:\Users\juan.burgos\Downloads\Cruz Verde\ETV\Repositorio\Cuadratura Macro FCV ETV 2-Abr-2019; Prosegur .xlsm" as Book5
Excel LoadWSheet Book5 sheet_index 2 as Hoja8
###########Carga de Excel POS + fecha########################################################################################################################
GetCurrentDate Date{dd-MM-yyyy en} and save as ActualDate
Excel LoadWBook "C:\Users\juan.burgos\Downloads\Cruz Verde\ETV\Repositorio\Evidencia\POS <<<ActualDate>>>.xlsx" as Book6
Excel LoadWSheet Book6 sheet_index 1 as Hoja9
###########Copia de datos del POS a la Macro########################################################################################################################
Excel CopyColumn 1 from Hoja9 start_at 1 to the sheet Hoja8 in column 1 start_at 1
Excel CopyColumn 2 from Hoja9 start_at 1 to the sheet Hoja8 in column 2 start_at 1
Excel CopyColumn 3 from Hoja9 start_at 1 to the sheet Hoja8 in column 3 start_at 1
Excel CopyColumn 4 from Hoja9 start_at 1 to the sheet Hoja8 in column 4 start_at 1
Excel CopyColumn 5 from Hoja9 start_at 1 to the sheet Hoja8 in column 5 start_at 1
Excel SaveAs Book5 as MacroParcial in C:\Users\juan.burgos\Downloads\Cruz Verde\ETV\Repositorio\Evidencia
Titanium Sleep 10000

**Comment by gantonioid** [comment]
En un primer vistazo veo que tu instrucción para cargar el Book6 pretendes usar una variable pero tienes vacío el placeholder <<>>, yo te pregunto si esa variable viene de la ventana previa a comenzar la ejecución o es la variable que generas con la instrucción GetCurrentDate eso define si lleva 2 o 3 <> Esto puede ser la razón de que no veas cambios en el libro... no te sale error de file not found??

Tienes esto
Excel LoadWBook "C:\Users\juan.burgos\Downloads\Cruz Verde\ETV\Repositorio\Evidencia\POS <<>>.xlsx" as Book6

Debería ser algo así:
Excel LoadWBook "C:\Users\juan.burgos\Downloads\Cruz Verde\ETV\Repositorio\Evidencia\POS <<fecha>>.xlsx" as Book6

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid al hacer ctrC ctrV no se copio correctamente, la instruccion esta de la siguiente manera:

GetCurrentDate Date{dd-MM-yyyy en} and save as ActualDate
Excel LoadWBook "C:\Users\juan.burgos\Downloads\Cruz Verde\ETV\Repositorio\Evidencia\POS <<<ActualDate>>>.xlsx" as Book6
Excel LoadWSheet Book6 sheet_index 1 as Hoja9

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid esta correcto en el codigo por algun motivo no aparece en GitHub cuando lo escribo:
<img width="511" alt="2019-04-29 11_23_03-EditInstructionsWindow" src="https://user-images.githubusercontent.com/49756974/56902700-35532180-6a71-11e9-9d8c-dcebef46a7fd.png">

**Comment by gantonioid** [comment]
Cierto, veo que igual me modificó lo que yo escribí

**Comment by gantonioid** [comment]
Entonces... sobre la función de RunMacro
Así ves la macro que tiene asignada el botón:
![image](https://user-images.githubusercontent.com/9600868/56900111-ae934a00-6a5a-11e9-8b59-f2530af237c9.png)

Esta es la macro:
![image](https://user-images.githubusercontent.com/9600868/56900223-e9957d80-6a5a-11e9-858e-b41385180b42.png)

Ahora, fíjate en esa imagen que el libro tiene la macro como Private... por lo tanto **No la podemos ejecutar**... si la cambias a Public, ya funciona con la instrucción así
`Excel RunMacro "Hoja1.Ejecutar_Macro_Click" InBook libro`
![image](https://user-images.githubusercontent.com/9600868/56904891-d4255100-6a64-11e9-8d11-e7410d12c7eb.png)

Poniendo la macro Public, entonces te va a aparecer aquí:
![image](https://user-images.githubusercontent.com/9600868/56905057-29f9f900-6a65-11e9-92c3-b3f796cf27cf.png)

Este sería el nombre de la macro que podrías en la instrucción:
![image](https://user-images.githubusercontent.com/9600868/56905097-3bdb9c00-6a65-11e9-873e-1dea33c8939f.png)

**Comment by gantonioid** [comment]
Aclaración:

1. No podemos volver la macro "Public" desde FRIDA, ya debe de estar así en el archivo que estés utilizando.
2. Si tú no tienes control sobre el archivo para volverla "Public" (ejemplo: viene de un sistema del cliente, y no lo pueden cambiar), tendrás que encontrar otra alternativa... tal vez "traducir" lo que hace la macro a código FRIDA :(

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid okey, lo voy a estar probando, cualquier cosa me vuelvo a poner en contacto, gracias por la ayuda!

**Comment by JuanIgnacioBurgos** [comment]
@gantonioid Hola de nuevo, he podido correr las macros sin problemas.

Lo que me esta sucediendo con este archivo es que no me esta tomando los cambios realizados, es decir, si quiero hacer un "write" o "borrar columnas" o o cualquier accion que lo modifique, luego de guardar estos cambios no quedan guardados.
¿Se te ocurre porque esta pasando esto?

**Comment by gantonioid** [comment]
- Que lo tengas abierto en otra ventana de Excel y entonces la automatización lo esté abriendo como "Solo lectura"
- Tal vez estás escribiendo en otra hoja (hayas cargado el sheet_index incorrecto)
- Tal vez le das Save al libro equivocado
- Probablemente ya existe un libro con ese nombre, por lo tanto el SaveAs falla

Como ves son varias posibilidades, pero el script que te mandé **escribe en el archivo que adjuntaste en el issue** sin problemas

**Comment by JuanIgnacioBurgos** [comment]
Resuelto, al parecer el excel tenia varias pestañas ocultas, debido a esto Frida tomaba mal la carga de sheets ya que el indice era diferente, gracias nuevamente por la ayuda.
Saludos.
