### ISSUE TITLE
Instrucción If traduce de manera errónea el la variable

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#33]
El error se da en un código donde se itera varias veces, se hizo una reunión para mostrar el funcionamiento y no se encontró solución. El problema aun persiste imposibilitando la entrega de uno de los procesos.

29/04/2019 13:06:33 - #If ("PRIOX" -eq "<<<RegSociedad%0°>>>"): Running
29/04/2019 13:06:33 - If ("PRIOX" -eq "<<<RegSociedad%0°>>>") : Success
29/04/2019 13:06:33 - If Result : False
29/04/2019 13:06:33 - Else Block Running

**Comment by FaustinoLechuga** [comment]
Me podrás decir que es específicamente lo que no esta funcionando?

**Comment by gantonioid** [comment]
En el If no se reemplaza RegSociedad en el índice 0... yo lo había visto antes con ella pero se dejó el tema.

@SoledadNunez se me acaba de ocurrir que pruebes hacer una variable x = RegSociedad[0] **antes** de la línea del If, entonces la comparación la haces If ("PRIOX" -eq "<<<xxx>>>")

Me avisas los resultados

**Comment by SoledadNunez** [comment]
Debería traducirlo con el valor que contiene la variable pero lo hace de a siguiente manera <<<RegSociedad%0°>>>
Esto sucede solo en una de las ultimas instrucciones del código, se usa la misma instrucción en otras partes sin mostrar este inconveniente.

**Comment by SoledadNunez** [comment]
@gantonioid  Perdón, no entendí lo que me estas solicitando que pruebe.

**Comment by gantonioid** [comment]
Lo que sugerí fue hacer el reemplazo de <<<RegSociedad[0]>>> fuera del If, así vemos si lo que falla es el reemplazo en sí o la función If
```
##Definir variable "sociedad" with the value "<<<RegSociedad[0]>>>"
If ("PRIOX" -eq "<<<sociedad>>>")
```

**Comment by SoledadNunez** [comment]
El log se muestra de la misma manera, para mi el inconveniente esta en el foreach anterior al if
29/04/2019 17:58:19 - DefineVariable type "string" as "Nsociedad" with the value "<<<RegSociedad%0°>>>": Running
29/04/2019 17:58:19 - MixReader : Se agrego una nueva variable : 
Var Name : Nsociedad
Value : <<<RegSociedad%0°>>>
29/04/2019 17:58:19 - DefineVariable type "string" as "Nsociedad" with the value "<<<RegSociedad%0°>>>" : Success
29/04/2019 17:58:19 - #If ("ALICORP" -eq "<<<RegSociedad%0°>>>"): Running
29/04/2019 17:58:19 - If ("ALICORP" -eq "<<<RegSociedad%0°>>>") : Success

**Comment by pabloreitanosofttek** [comment]
Hola, ¿Cuál es la fecha de necesidad? ¡gracias!

**Comment by gantonioid** [comment]
Soledad, veo que ahora tu log llega a comparar con ALICORP, cuando antes era PRIOX... es posible entonces que la ejecución haya avanzado algo?

**Comment by SoledadNunez** [comment]
Buenas, el proceso realiza esa comparación en la primer vuelta con Alicorp y luego con Priox, en segundo caso corte la ejecución a la mitad. La ejecución finaliza sin problemas, solo que siempre ese if sale por false

**Comment by gantonioid** [comment]
Según recuerdo, tienes una estructura algo interesante de anidación de for, if, foreach... puedes por favor hacer eso que dije, pero más arriba en tu script?

Es decir, `DefineVariable type "string" as "sociedad" with the value "<<<RegSociedad[0]>>>"` tan pronto como empieces la iteración, o en cuanto _debiera_ de estar disponible esa variable.

Me habías dicho que si ponías ese ciclo en otro lugar más arriba de tu script, ya no tenías el problema.

**Comment by SoledadNunez** [comment]
La prueba anterior fue echa según lo indicas, el if esta inmediatamente despues del foreach:
...
foreach RegSociedad in RegSociedades {
DefineVariable type "string" as "sociedad" with the value "<<<RegSociedad[0]>>>"
If ("<<<RegCuenta[0]>>>" -eq "<<<sociedad>>>")
...

Efectivamnte, si coloco esta iteracion mas arriba en el código lo resuelve sin inconveniente.

**Comment by gantonioid** [comment]
No me quedó claro si definir la variable sociedad justo después de empezar el foreach te ayudó o no... hay error así? me pasas qué dice el log?

**Comment by SoledadNunez** [comment]
No genero ningún cambio en la ejecución, colocar esa variable así, ya que le metió por valor "<<<RegSociedad%0°>>>"

**Comment by SoledadNunez** [comment]
30/04/2019 17:52:10 - DefineVariable type "string" as "Nsociedad" with the value "<<<RegSociedad%0°>>>": Running
30/04/2019 17:52:10 - MixReader : Se agrego una nueva variable :
Var Name : Nsociedad
Value : <<<RegSociedad%0°>>>
30/04/2019 17:52:10 - DefineVariable type "string" as "Nsociedad" with the value "<<<RegSociedad%0°>>>" : Success
30/04/2019 17:52:10 - #If ("ALICORP" -eq "<<<RegSociedad%0°>>>"): Running
30/04/2019 17:52:10 - If ("ALICORP" -eq "<<<RegSociedad%0°>>>") : Success

**Comment by gantonioid** [comment]
@SoledadNunez Estoy esperando verte online para verlo en llamada

**Comment by SoledadNunez** [comment]
Buenos días, el día de ayer fue feriado en Argentina no estábamos disponibles, avisame cuando puedas y nos hablamos.

**Comment by pabloreitanosofttek** [comment]
¿Pudieron verlo? Lleva ya unos días... ¡Gracias!

**Comment by SoledadNunez** [comment]
Buenas tardes, hay alguna novedad sobre este ¿bug? el proceso ya debería estar en producción.

**Comment by pabloreitanosofttek** [comment]
Se necesita una fecha de resolución. ¡Gracias! @FaustinoLechuga @andresCruzF  @gantonioid

**Comment by SoledadNunez** [comment]
Buenas tardes, Estamos retrasados con la puesta en producción del proceso, hay alguna fecha de resolución?

**Comment by pabloreitanosofttek** [comment]
Estimados, necesitamos una respuesta concreta sobre este ticket. 
¿Cuándo la podemos tener? 

¡gracias! 
Saludos,
PR

**Comment by pabloreitanosofttek** [comment]
@SoledadNunez pudieron hacer la llamada? De no ser así, les pido que no pase del Lunes al mediodía ARG... porque sin el diagnostico jamas tendremos una respuesta.

¡gracias!
Saludos,
PR

**Comment by RickProductivity** [comment]
@SoledadNunez sugiero que mandes un MR para que agilicemos este tema. Saludos
Rick

**Comment by SoledadNunez** [comment]
@pabloreitanosofttek Nos reunimos en varias oportunidades para ver cual es el comportamiento que presenta.

**Comment by pabloreitanosofttek** [comment]
¿Como quedó esto al final? @SoledadNunez  @gantonioid  @andresCruzF  @FaustinoLechuga ?

¡Gracias!

**Comment by SoledadNunez** [comment]
@pabloreitanosofttek, no obtuve ninguna respuesta.

Habia un código basura (repetia un foreach sin código adentro sobre las misma variables mas arriba del error) que hacia que no pasara, en este lugar pero el error se vuelve a presentar en el próximo foreach.

> SendMail with subject "Extractos bancarios - BCP - <<<FechaLog>>>" to "<<<Mail%1°>>>" 

Necesitamos resolver este tema de manera urgente, dado que tenemos compromisos de entrega que no estamos cumpliendo.

**Comment by pabloreitanosofttek** [comment]
@SoledadNunez  ¿Pudiste probar y funcionó? De ser así, te pido que cierre el ticket.

¡gracias!

**Comment by SoledadNunez** [comment]
Hable con Raul, me indico que enviemos a un único mail, por lo que no seria necesario que se ajuste el envío de mail para copia oculta.
Cierro el tk.

**Comment by SoledadNunez** [comment]
Buenas tardes, Se replico el error en otro de los procesos, puedo saltear el error, pero la estructura es bastante mas sencilla que la de BCP.
Paso el código y log por si es de ayuda en la resolución del problema raíz.
[Banco BBVA Continental.txt](https://github.com/FridaSupport/TuringSuport/files/3214065/Banco.BBVA.Continental.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3214066/log.txt)
