### ISSUE TITLE
[Urgente] Turing se cierra de manera aleatoria

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#34]
Turing se esta cerrando de manera aleatoria. Sucede cuando estoy corriendo un proceso o este termina o cuando no toco el Turing. El log no muestra ningun error. Pero en el event viewer de windows, muestra error con un dll grafico. Esto significa que es un error con mi maquina, del dll, si me pudiesen ayudar. 

![image](https://user-images.githubusercontent.com/49946883/56916614-b15c6200-6a8f-11e9-9e04-56332464c9cc.png)

![image](https://user-images.githubusercontent.com/49946883/56916637-be795100-6a8f-11e9-91a7-0b8b833cb480.png)

**Comment by FaustinoLechuga** [comment]
¿Esto te pasa cuando estas utilizando SAP?

**Comment by jaristimuno** [comment]
No. Esto sucede con instancia de browpet.

**Comment by gantonioid** [comment]
@carlosortiz632  dicen que es browpet

**Comment by carlosortiz632** [comment]
Browpet se ejecuta en una instancia separada (su propio .exe), por lo que si fuera el problema de este, el error vendría sobre ese ejecutable. Lo único que hace Turing para conectarse a Browpet es abrir una conexión local, pero ambos procesos corren independientemente. 

Vamos a checar este error para ver si viene de parte de Turing o es problema de ese driver que comentas.

Saludos.

**Comment by pabloreitanosofttek** [comment]
Hola, ¿Cuál es la fecha de necesidad? ¡gracias!

**Comment by jaristimuno** [comment]
A mas tardar el 03/05/19

**Comment by carlosortiz632** [comment]
Revisando más a detalle el error, parece ser que lo que falla es el driver del chip gráfico de tu computadora. Revisando en foros, encontré que una manera de solucionarlo es instalando de nuevo el `Intel Graphics Driver` y reiniciando la computadora.

**Comment by jaristimuno** [comment]
Se reinstaló el driver. Turing sigue cerrandose
