### ISSUE TITLE
Leer el ultimo Excel dentro de una carpeta en el sistema local

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#35]
Existe alguna instrucción que lea el ultimo excel guardado en una carpeta en el PC, encontré una instrucción de Excelium "LoadWBook "C:\Users\productivity\Desktop\Book1.xlsx" as book1" pero se tiene que definir el nombre del archivo Excel, lo que yo necesito es que lea el ultimo archivo, en la carpeta y luego lea la hoja del excel...

**Comment by victorgamboa** [comment]
Este ticket me lo resolvió @FaustinoLechuga, Favor cerrar gracias.

**Comment by gantonioid** [comment]
Gracias
