### ISSUE TITLE
Ejecutar Frida desde Citrix Receiver

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#36]
Hola, tengo el siguiente caso, tengo que ejecutar SAP, pero esta dentro de una aplicación llamada CITRIX RECEIVER, el cliente lo pidió de esa forma, desconozco las razones del por que no quiere ejecutarlo directamente desde la aplicación SAP Logon...
![Citrix](https://user-images.githubusercontent.com/49756748/56926215-26836380-6a9f-11e9-8f79-2d0bc6ef96ab.jpg)

**Comment by pabloreitanosofttek** [comment]
Hola, ¿Cuál es la fecha de necesidad? ¡gracias!

**Comment by victorgamboa** [comment]
22 de Mayo

**Comment by gantonioid** [comment]
No se está describiendo un issue en este thread, cierro el tema. Intenta Titanium y nos contactas cuando exista un issue.

**Comment by pabloreitanosofttek** [comment]
Buenas, crearé uno nuevo dado que no puedo re-abrirlo... básicamente lo que esperamos es entender como hacer para correr FRIDA sobre Citrix y que dentro esté la instancia de SAP.

¡Gracias!
