### ISSUE TITLE
Error al leer user ID en MS Flow

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#38]
Buenas tardes,
Solicite mi USER ID de Frida o Turing (No se cual es) y lo agregue al código que se puede ver en el archivo adjunto, el tema es que estaba usando el USER ID de Carlos Julian Giraldo Giraldo y funcionaba correctamente el llamado de Flows.

User ID Carlos : 8621700a-0d4d-49d3-b97a-514b4b4f582c

User ID Víctor: ffa950b2-9903-470b-874b-85d21d805a09

Si necesitan algún otro dato, quedo atento,
Saludos
![msflow](https://user-images.githubusercontent.com/49756748/56990957-7d9f3c00-6b64-11e9-9b1c-277e3a5f10d8.jpg)
![msflow2](https://user-images.githubusercontent.com/49756748/56990958-7d9f3c00-6b64-11e9-9675-6e44d6fe651e.jpg)

**Comment by gantonioid** [comment]
@victorgamboa ¿tienes una computadora prendida en modo Listener para recibir la petición?
¿Probaste la misma llamada con Postman o similar?

Yo probé y mira el resultado (correcto)
![image](https://user-images.githubusercontent.com/9600868/57017326-496b6000-6be4-11e9-943c-af2261748f2c.png)

La llamada no falla (Response: 200 OK) pero me da null porque no hay máquina prendida, si hubiera ahí donde marqué de amarillo vendría un número (ID de la ejecución remota)

**Comment by victorgamboa** [comment]
Muchas gracias, ahí lo resolví, Saludos
