### ISSUE TITLE
Creación de tablas dinamicas

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#39]
Buenas Tardes, nos gustaría saber si es posible crear tablas dinámicas con FRIDA y con quien podríamos verlo, ya que para el proyecto varios de los pasos en el proceso requieren de este tipo de tablas para unas comparaciones, el tema esta relacionado con el proyecto TITAN de SAE, quedo atento, mil gracias.

**Comment by gantonioid** [comment]
Sï se puede. Las funciones se encuentran en la documentación. Si tienes un caso más específico nos dices.

- CachePivotTable
- CreatePivotTable
- CopyPivotTable
