### ISSUE TITLE
Excel no hace nada.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#40]
Cuando ejecuto el Turing para modificar archivos de excel finaliza exitosamente pero cuando reviso estos archivos resulta que no hizo nada.

Necesito esto solucionado para mañana (03/05/2019) sino no puedo continuar. Gracias.

Log:

02-May-19 15:13:30 - Execution started
02-May-19 15:13:30 - Excel LoadWBook "C:\Users\cesar.lencina\Documents\[Sofía] Documentación y archivos\Ensayo\archivo.xlsm" as Macro: Running
02-May-19 15:13:32 - Excel LoadWBook "C:\Users\cesar.lencina\Documents\[Sofía] Documentación y archivos\Ensayo\archivo.xlsm" as Macro : Success
02-May-19 15:13:32 - Excel LoadWSheet Macro sheet_index 1 as Asiento: Running
02-May-19 15:13:32 - Excel LoadWSheet Macro sheet_index 1 as Asiento : Success
02-May-19 15:13:32 - Excel ApplyFilter to the worksheet Asiento to the column with the index {2} with the criteria "111010129": Running
02-May-19 15:13:32 - Excel ApplyFilter to the worksheet Asiento to the column with the index {2} with the criteria "111010129" : Success
02-May-19 15:13:32 - Excel RemoveCols from Asiento at [5]: Running
02-May-19 15:13:32 - Excel RemoveCols from Asiento at [5] : Success
02-May-19 15:13:32 - Titanium Sleep 5000: Running
02-May-19 15:13:37 - Titanium Sleep 5000 : Success
02-May-19 15:13:38 - Execution ended

**Comment by gantonioid** [comment]
Le indicaste a FRIDA que guarde los cambios en el libro? El log que adjuntas no lo muestra

http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/SaveWB

**Comment by CesarEmanuelLencina** [comment]
Era eso, gracias. Problema solucionado.
