### ISSUE TITLE
Solicitud Version Turing Valorem

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#41]
Estoy tratando de ejecutar el Turing en la maquina de Valorem pero este se cierra, aparecen estos dos mensajes (ver abajo) y después se cierra. Pueden ayudarme con este problema o con una nueva versión para instalar en la maquina virtual que habilito Valorem para esto. 

![turing_valorem_01](https://user-images.githubusercontent.com/14879161/57141333-90418d00-6d7f-11e9-8d48-749b3c6e6a90.png)

![turing_valorem_02](https://user-images.githubusercontent.com/14879161/57141347-9a638b80-6d7f-11e9-9913-4550981f6e92.png)

Agradezco de su ayuda.

**Comment by pabloreitanosofttek** [comment]
¿Para cuando lo necesitas? ¿Es para cliente en PRD? ¡gracias!

**Comment by carlosgiraldo** [comment]
Hola Pablo, si es para ambiente productivo, lo ideal es lo mas pronto posible.

**Comment by pabloreitanosofttek** [comment]
Pongamos fecha entonces... 07/05. 
A quien corresponda, favor de dar seguimento dado que es un ambiente PRD y tiene además, los bots construidos y mostrados a cliente.
¡gracias!

**Comment by gantonioid** [comment]
@carlosgiraldo  en nuestro panel de admin tenemos asignada para VALOREM la versión 20190423T0356 (Abril 23 2019) pero la instancia 923339028 que muestras en la segunda captura tiene una versión de hace 20190213T0518 (Febrero 13 2019)

Si se cierra sin más, me hace pensar que no tiene acceso a internet, porque quiere jalar el update que te mencioné y se cierra...

**Comment by carlosgiraldo** [comment]
Gracias por la respuesta, voy a pedir que comprueben que esa maquina tenga acceso a Internet, deberían hacer la prueba con alguna URL en especial?

**Comment by gantonioid** [comment]
Sí, toma de referencia la ppt que tenemos en Teams/Academia Noviembre 2018/1 - Automationplatform.pptx en la diapositiva 25
Aquí la liga:
[https://teams.microsoft.com/l/file/1A777D4E-219F-4773-9E63-CCB5072AD832?tenantId=864ee999-c538-44a0-bddd-0449de62df6d&fileType=pptx&objectUrl=https%3A%2F%2Fonesofttek.sharepoint.com%2Fteams%2FDesarrolloFRIDA%2FShared%20Documents%2FAcademia%20Noviembre%202018%2F1%20-%20AutomationPlatform.pptx&baseUrl=https%3A%2F%2Fonesofttek.sharepoint.com%2Fteams%2FDesarrolloFRIDA&serviceName=teams&threadId=19:4a281f9de31747ecb94540a1d54643b7@thread.skype&groupId=0d5132ed-7582-417f-8a6c-63e895ec18b2](url)

**Comment by carlosgiraldo** [comment]
Buenos días @gantonioid  mientras me confirman si la maquina virtual donde se instalo Turing tiene acceso a Internet podria ayudarme a revisar la caducidad del Turing de Valorem, si ya caduco pueden ampliarme la fecha a dos años. gracias

**Comment by gantonioid** [comment]
Si Turing caducó, debe de salir una ventana indicando que ha caducado y que nos contactes, pero no incluiste un screenshot de ese mensaje por eso no lo consideré. ¿Te aparece ese mensaje?

**Comment by carlosgiraldo** [comment]
No me sale un mensaje de ese tipo, fue algo que se me ocurrió no mas, solo se presentan los mensajes que les indique. 

Ya revisamos y el equipo si tiene acceso a Internet, también a las paginas indicadas excepto una que no esta disponible:  https://innotekfilestore.file.core.windows.net/.

¿Que mas podemos revisar para que Turing funcione en la maquina Virtual?

**Comment by gantonioid** [comment]
Los accesos a esos sitios son los únicos requerimientos, pero también la fecha de expiración. Te busco en un rato y te enseño

**Comment by carlosgiraldo** [comment]
Gracias, quedo atento. Mas tarde voy a tratar de instalar la versión Turing que funciona en mi equipo en la maquina virtual del cliente y ver que pasa.

**Comment by gantonioid** [comment]
no lo recomiendo, ya que es un Turing con otros procesos que no necesariamente son del cliente
