### ISSUE TITLE
Crear nuevo Archivo Excel

### ISSUE THREAD

**Issue by dsalgadoi2012** [FridaSupport/TuringSuport#42]
Buenos dias, 
Solicito su apoyo para la creación de un nuevo archivo de Excel, en la documentacion solo encuentre la carga de un archivo existente.

**Comment by JuanISalazarM** [comment]
Buenos días.
Claro en cuanto tenga la función lista le haré saber a la brevedad. Tenga un buen día.

**Comment by JuanISalazarM** [comment]
Buenas tardes.
Se le ha liberado una nueva versión de TuringExpo. Para que de favor, haga el update (volver a abrir Turing)
En el presente enlace se encuentra la función, y cómo utilizar la nueva función: http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/NewWB

Espero confirmación acerca del correcto funcionamiento de este.

**Comment by pabloreitanosofttek** [comment]
Si la versión lanzada de Turing está OK... se debe cerrar el ticket @dsalgadoi2012  confirmar. 

gracias!
