### ISSUE TITLE
pila vacia

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#43]
Buenas tardes,
Después de realizar unos cambios en mi script, corro la automatización y me dice "Pila Vacía" sin hacer algo antes. Probé volver a dejarlo como estaba antes de hacer los cambios y sigue diciendo lo mismo. En LOG no hay mensajes.
SCRIPT 
![pila vacia](https://user-images.githubusercontent.com/49987311/57155203-3954ab80-6db1-11e9-93e7-98bb7282fe49.jpg)

MENSAJE
![pila vacia 2](https://user-images.githubusercontent.com/49987311/57155219-440f4080-6db1-11e9-8c25-ba0a7d9e36b7.jpg)

LOG
![pila vacia 3](https://user-images.githubusercontent.com/49987311/57155268-66a15980-6db1-11e9-948b-d4b94591aac5.jpg)

**Comment by FaustinoLechuga** [comment]
Hola buen dia, podras revisar que la estructuras logicas esten correctas? Ese error tiene que ver con un error en la estructura de un if, for, foreach o try.

**Comment by MartinJOlmedo** [comment]
Ok, lo reviso. Gracias!
