### ISSUE TITLE
Excelium - LoadCSV con delimitador ; Falla

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#44]
Estoy usando la instrucción LoadCSV y no importa que delimitador le indique siempre esta buscando que el archivo este separado por comas, hice varias pruebas con un archivo separado por comas y cambiando el delimitador y lo separa bien, pero necesito que tome como delimitador el punto y coma ( ; ), pueden ayudarme para incluir este delimitador, o se debe usar de una forma especial para que tome este delimitador? gracias.

Excel LoadCSV "C:\consolidado_coma.csv" separated_by ; as WBName
Excel LoadCSV "C:\consolidado_coma.csv" separated_by , as WBName
Excel LoadCSV "C:\consolidado_coma.csv" separated_by * as WBName

**Comment by pabloreitanosofttek** [comment]
Hola, en que fecha debe estar esto? Entiendo que es para SAE - SOFOCAR - CRUZ VERDE. 

¡gracias! 
Saludos,

**Comment by carlosgiraldo** [comment]
creo que la entrega completa es para el día 13 de Mayo, por lo tanto debería estar hoy o el lunes por tarde para poder usarlo ya que la herramienta del cliente es la que genera el CSV separado por ; y no con comas (,). gracias

**Comment by FaustinoLechuga** [comment]
¿Me podrás compartir el archivo que estas cargando?

**Comment by carlosgiraldo** [comment]
Hola @FaustinoLechuga , el archivo se lo envié a Juan Isaac Salazar el día viernes.

**Comment by FaustinoLechuga** [comment]
Perfecto, gracias
