### ISSUE TITLE
SendMail no puede enviar variables?

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#45]
Estuve intentando tomar valores desde una pagina para extraer datos y enviarlo por mail, al intentar enviar la variable con los datos por mail nunca se envia, y no sale codigo de error ni nada.

Web2 Extract from id="MainContent_txtOCRResultText"  save as "x"
Titanium Sleep 1000
SendMail with subject "Datos" to "nehuen.verges@softtek.com" with body "Se extrajo: <<<x>>>"

Si remuevo la X simplemente no hay problemas y el mail es enviado, pero con la variable incluida nunca se envia.

pd: si creo variables normales estas si se envian, el problema es con el extract.

**Comment by FaustinoLechuga** [comment]
Me podras compartir tu log? y la url de la pagina porfavor.

**Comment by pabloreitanosofttek** [comment]
Hola, para cuando la necesitas? 
¡gracias!
Slds,

**Comment by NehuenV** [comment]
Adjunto el log:

06-May-19 8:51:12 AM - Execution started
06-May-19 8:51:12 AM - DefineVariable type "string" as "x": Running
06-May-19 8:51:12 AM - MixReader : Se agrego una nueva variable : 
Var Name : x
Value : 
06-May-19 8:51:12 AM - DefineVariable type "string" as "x" : Success
06-May-19 8:51:12 AM - Web2 GoTo "https://www.onlineocr.net/es/": Running
06-May-19 8:51:12 AM - Runing browpet-engine
06-May-19 8:51:21 AM - Web2 GoTo "https://www.onlineocr.net/es/" : Success
06-May-19 8:51:21 AM - Web2 Select value="SPANISH" in id="MainContent_comboLanguages": Running
06-May-19 8:51:21 AM - Web2 Select value="SPANISH" in id="MainContent_comboLanguages" : Success
06-May-19 8:51:21 AM - Web2 Select value="Text Plain (txt)" in id="MainContent_comboOutput": Running
06-May-19 8:51:22 AM - Web2 Select value="Text Plain (txt)" in id="MainContent_comboOutput" : Success
06-May-19 8:51:22 AM - Web2 UploadFile "C:\Users\nehuen.verges\Documents\ticket.bmp" in id="fileupload": Running
06-May-19 8:51:22 AM - Web2 UploadFile "C:\Users\nehuen.verges\Documents\ticket.bmp" in id="fileupload" : Success
06-May-19 8:51:22 AM - Web2 Sleep 15000: Running
06-May-19 8:51:38 AM - Web2 Sleep 15000 : Success
06-May-19 8:51:38 AM - Web2 Click in id="MainContent_btnOCRConvert": Running
06-May-19 8:51:38 AM - Web2 Click in id="MainContent_btnOCRConvert" : Success
06-May-19 8:51:38 AM - Titanium Sleep 6000: Running
06-May-19 8:51:44 AM - Titanium Sleep 6000 : Success
06-May-19 8:51:44 AM - Web2 Extract from id="MainContent_txtOCRResultText" save as "x": Running
06-May-19 8:51:45 AM - Se actualizo la variable : 
Var Name : x
Value : STARBUCKS COFFEE ARGENTI 97'.1 CUIT Nro.: 30-71004052-0 IVA RESPONSABLE INSCRIPTO A CONSUMIDOR FINAL P.V. Nro.: 0086 Nro. T. 30539722 Fecha 15/11/18 Hora 19115:48 
1,0000 x 116,0000 C13025 M27075 Gonzalez TBL:0/0 -Aqui- CLS:0 Fruti Creme Frap 116,00 )1,0000 x 116,0000 Fruti Creme Frap 116,n0 TOTAL 232,00 Efectivo 5£10,M Suma de sus pagos 500,Wa Su Vuelto 26%,151 
frA7 V: 22.00 Hera 4.:»/' REGISTRO Nro.: K01002099 

06-May-19 8:51:45 AM - Web2 Extract from id="MainContent_txtOCRResultText" save as "x" : Success
06-May-19 8:51:45 AM - Message "STARBUCKS COFFEE ARGENTI 97'.1 CUIT Nro.: 30-71004052-0 IVA RESPONSABLE INSCRIPTO A CONSUMIDOR FINAL P.V. Nro.: 0086 Nro. T. 30539722 Fecha 15/11/18 Hora 19115:48 
1,0000 x 116,0000 C13025 M27075 Gonzalez TBL:0/0 -Aqui- CLS:0 Fruti Creme Frap 116,00 )1,0000 x 116,0000 Fruti Creme Frap 116,n0 TOTAL 232,00 Efectivo 5£10,M Suma de sus pagos 500,Wa Su Vuelto 26%,151 
frA7 V: 22.00 Hera 4.:»/' REGISTRO Nro.: K01002099": Running
06-May-19 8:51:45 AM - Message "STARBUCKS COFFEE ARGENTI 97'.1 CUIT Nro.: 30-71004052-0 IVA RESPONSABLE INSCRIPTO A CONSUMIDOR FINAL P.V. Nro.: 0086 Nro. T. 30539722 Fecha 15/11/18 Hora 19115:48 
1,0000 x 116,0000 C13025 M27075 Gonzalez TBL:0/0 -Aqui- CLS:0 Fruti Creme Frap 116,00 )1,0000 x 116,0000 Fruti Creme Frap 116,n0 TOTAL 232,00 Efectivo 5£10,M Suma de sus pagos 500,Wa Su Vuelto 26%,151 
frA7 V: 22.00 Hera 4.:»/' REGISTRO Nro.: K01002099" : Success
06-May-19 8:51:45 AM - Titanium Sleep 1000: Running
06-May-19 8:51:46 AM - Titanium Sleep 1000 : Success
06-May-19 8:51:46 AM - SendMail with subject "Datos" to "nehuen.verges@softtek.com" with body "Se extrajo: STARBUCKS COFFEE ARGENTI 97'.1 CUIT Nro.: 30-71004052-0 IVA RESPONSABLE INSCRIPTO A CONSUMIDOR FINAL P.V. Nro.: 0086 Nro. T. 30539722 Fecha 15/11/18 Hora 19115:48 
1,0000 x 116,0000 C13025 M27075 Gonzalez TBL:0/0 -Aqui- CLS:0 Fruti Creme Frap 116,00 )1,0000 x 116,0000 Fruti Creme Frap 116,n0 TOTAL 232,00 Efectivo 5£10,M Suma de sus pagos 500,Wa Su Vuelto 26%,151 
frA7 V: 22.00 Hera 4.:»/' REGISTRO Nro.: K01002099": Running
06-May-19 8:51:47 AM - SendMail with subject "Datos" to "nehuen.verges@softtek.com" with body "Se extrajo: STARBUCKS COFFEE ARGENTI 97'.1 CUIT Nro.: 30-71004052-0 IVA RESPONSABLE INSCRIPTO A CONSUMIDOR FINAL P.V. Nro.: 0086 Nro. T. 30539722 Fecha 15/11/18 Hora 19115:48 
1,0000 x 116,0000 C13025 M27075 Gonzalez TBL:0/0 -Aqui- CLS:0 Fruti Creme Frap 116,00 )1,0000 x 116,0000 Fruti Creme Frap 116,n0 TOTAL 232,00 Efectivo 5£10,M Suma de sus pagos 500,Wa Su Vuelto 26%,151 
frA7 V: 22.00 Hera 4.:»/' REGISTRO Nro.: K01002099" : Success
06-May-19 8:51:52 AM - Execution ended



Aprentemente lo envia, pero a mi correo nunca llega nada, al menos no cuando lo uso con la variable del extract.

Adjunto tambien el codigo que estaba usando:
DefineVariable type "string" as "x"
Web2 GoTo "https://www.onlineocr.net/es/"
Web2 Select value="SPANISH" in id="MainContent_comboLanguages"
Web2 Select value="Text Plain (txt)" in id="MainContent_comboOutput"
Web2 UploadFile "C:\Users\nehuen.verges\Documents\ticket.bmp" in id="fileupload"
Web2 Sleep 15000
Web2 Click in id="MainContent_btnOCRConvert"
Titanium Sleep 6000
Web2 Extract from id="MainContent_txtOCRResultText"  save as "x"
Message "<<<x>>>"
Titanium Sleep 1000
SendMail with subject "Datos" to "nehuen.verges@softtek.com" with body "Se extrajo: <<<x>>>"

**Comment by pabloreitanosofttek** [comment]
Siempre pongamos una fecha... porque sino, se puede atender en el 2020 ;)

**Comment by FaustinoLechuga** [comment]
Gracias, ya se esta revisando este tema

**Comment by gantonioid** [comment]
Los logs indican que se están entregando los mails, incluso que los has abierto. Como recomendación yo diría que le quites los saltos de línea a TODAS las variables, porque pueden estropear la sintaxis de la instrucción que estés usando.

![image](https://user-images.githubusercontent.com/9600868/57231304-ea408d80-6fdf-11e9-9103-cc0599683aca.png)

**Comment by NehuenV** [comment]
No veo ningun mail con fecha de hoy, estuve probando y hasta recien ejecutando ese proceso que contiene el sendmail.
Sin ir mas lejos en el mismo post aclare que estuve haciendo pruebas para ver si podia enviar variables creadas que no usen el extract

**Comment by gantonioid** [comment]
Nehuen, entiendo tu caso... vi el log que adjuntaste y por eso es que digo yo que antes de usar tu variable x en la instrucción de SendMail, quítale primero los saltos de línea... El extract funciona, el SendMail funciona, pero le estás enviando un x = string con saltos de línea y eso es problemático.

**Comment by FaustinoLechuga** [comment]
Nehuen para reemplazar los saltos de linea en la variable "x" puedes usar este script de powershell

```
$s = "<<<x>>>"
$s = $s.replace("`n", "")
$res = "x : " + $s
Write-Output $res
```
esto se hace con la siguiente instrucción en el script principal.

`RunPowerShell ps1.txt`

y la utilizas antes de mandar el mail.

**Comment by NehuenV** [comment]
Ni con el powershell se envia el mail, de todas formas no es importante, pueden cerrar
