### ISSUE TITLE
[Consulta ]Scroll Browpet 

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#46]
Hay una función que permita hacer srcoll determinado en el browpet?

**Comment by jaristimuno** [comment]
En caso de que no exista. Se puede hacer bajar o hacer scroll enviando un key "ArrowDown"

**Comment by carlosortiz632** [comment]
Actualmente no existe la función para hacer eso, pero se puede trabajar en ello. Marco la pregunta como _enhancement_.

**Comment by gantonioid** [comment]
Faltarían detalles sobre el requerimiento... Es un scroll equivalente a {ARROWDOWN} o hasta que un elemento sea visible?

**Comment by jaristimuno** [comment]
Si bien mi requerimiento lo cubre el equivalente a {ARROWDOWN}, se puede dar el caso de que se necesite mas de uno...

Esto puede ser solucionado con una cantidad de scroll, tomo de ejemplo el click de titanium, que pide la cantidad de clicks a realizar. 
Ya que de no ser asi, seria colocar n veces la instruccion de {ARROWDOWN}

**Comment by pabloreitanosofttek** [comment]
¿En que quedamos  @jaristimuno ?

**Comment by jaristimuno** [comment]
@pabloreitanosofttek Quedaria como una mejora
