### ISSUE TITLE
Error Instrucción SAP

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#47]
Hola, al ejecutar la instrucción para abrir SAP, envía un error:

Error in SAP RunSapInstance "SAP ERP (QR2)" 100 "RPASOFIA" "Rpa.finning_2019" ES

Me conecto al servidor: SAP ERP (QR2).
Al entrar directamente en SAP funciona correctamente.

Log:
5/6/2019 10:53:26 AM - Execution started
5/6/2019 10:53:26 AM - SAP RunSapInstance "SAP ERP (QR2)" 100 "RPASOFIA" "Rpa.finning_2019" ES: Running
5/6/2019 10:53:26 AM - System.NullReferenceException: Object reference not set to an instance of an object.
   at SapScriptReader.SapScriptExecute.Verify_UpdatePage() in C:\Users\productivity\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 3423
   at SapScriptReader.SapScriptExecute.SelectAction(String action) in C:\Users\productivity\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 227
   at SapScriptReader.SapScriptExecute.RunLine(String paso, Dictionary`2 variables) in C:\Users\productivity\Source\Repos\AutomationPlatform\SapScriptReader\SapScriptExecute.cs:line 156
5/6/2019 10:53:26 AM - SAP RunSapInstance "SAP ERP (QR2)" 100 "RPASOFIA" "Rpa.finning_2019" ES : Error
5/6/2019 10:53:26 AM - Execution ended

![Error Sap](https://user-images.githubusercontent.com/49756748/57233648-0991e780-6fed-11e9-84e4-e66bad38f6a0.jpg)

**Comment by eradgg** [comment]
Hola @victorgamboa, primeramente hay que revisar si SapScriptring está habilitado en ese sistema.
hay que dar chick en el siguiente botón:
![image](https://user-images.githubusercontent.com/49762120/57236760-5ffe2680-6feb-11e9-9fb0-fde7bef4bc0a.png)
y ver si está habilitada la opción siguiente:
![image](https://user-images.githubusercontent.com/49762120/57236855-88862080-6feb-11e9-96d3-1cbcf3fd21e7.png)
si no está habilitado hay que habilitarlo en la transacción RZ11. Se explica en el siguiente link:
http://winshuttle-help.s3.amazonaws.com/step-by-step/en/transaction/enable-gui-scripting.htm
si está habilitado, te pediría que me llamaras por Skype y para ver qué está sucediendo.

**Comment by victorgamboa** [comment]
Revise y me dice que falta autorización para la transacción RZ11

**Comment by eradgg** [comment]
Enteonces habrá que pedir permiso al administrador del sistema y ver si esto es posible, atendiendo a las polícas del equipo que tiene este sistema.

**Comment by eradgg** [comment]
comunícate con el dueño de ese sitema y pide permisos para ejecutar Scripts, si es con cliente creo que ese un poco más complicado ya que se tienen que seguir las políticas de cliente.

**Comment by victorgamboa** [comment]
Respuesta de Finning:

Hola Víctor,
Lamentablemente desde el lado de negocio no tengo como justificar al equipo de Compliance que les den acceso a esta transacción, considerando que el RPA realiza los mismos pasos que un “humano” y la actualidad nadie del equipo de ventas tiene acceso a esa trx.

Que podemos hacer ante esto, existe otra manera de poder solucionar el problema?

**Comment by pabloreitanosofttek** [comment]
Hola a ambos,

No me queda claro si es falta de acceso a una TX o es que no está habilitado el scripting... si es el tema del scripting, avisale a Finning que sin eso, no pueden usar FRIDA sobre SAP. 

¡gracias!

**Comment by victorgamboa** [comment]
@pabloreitanosofttek es falta de autorización del usuario de SAP para utilizar la transacció RZ11 ya lo pedí, pero me respondieron eso de mas arriba...

**Comment by eradgg** [comment]
Hola @victorgamboa, @pabloreitanosofttek el problema es el scripting, la Rz11 se usa para habilitarlo y no tiene acceso, pero el principal problema es el scripting.

**Comment by eradgg** [comment]
Voy a cerrar este Issue ya que no es problema d eSoporte de Frida, una vez que puedan tener Sapscript activado podemos darle seguimiento si existiera otro problema.

**Comment by eradgg** [comment]
Reabrimos el Issue. Hay problemas con la conexión al servidor, ya que en este caso se encuentra en sub folders.

**Comment by eradgg** [comment]
Es un problema de compatibilidad de las librerías utilizadas.

**Comment by pabloreitanosofttek** [comment]
¿Para cuando lo necesitas @victorgamboa ?

**Comment by victorgamboa** [comment]
Para el 20 de Mayo tengo que tenerlo listo y ya llevo 2 días de retraso

**Comment by pabloreitanosofttek** [comment]
Estimados, necesitamos avanzar con este ticket... porfa darnos soporte... si falta algo de nuestra parte, pedirlo a @victorgamboa .

¡gracias!
Saludos,
PR

**Comment by eradgg** [comment]
Hola Si tengo la información necesaria, es un problema con las librerías que usamos y una compatibilidad en el servidor que usan. Tenemos un correo en el que se dice que esperemos hasta que el cliente defina si vamos a usar SAP, porque la información que yo tengo es que van a usar Citrix, si sigo trabajando en SAP porque esto puede ocurrir con otro cliente, pero si se va a usar citrix sería mejor que se fueran haciendo las instrucciones de Titanium que es con lo único que se puede manejar Citrix.

**Comment by victorgamboa** [comment]
Según lo que conversamos Eder con Titanium solo podré llegar hasta cierta parte del flujo, pero cuando necesite ejecutar instrucciones de SAP me veré imposibilitado, saludos

**Comment by gantonioid** [comment]
#83 Si es Citrix, la única alternativa es Titanium como ya ha sido mencionado.

**Comment by gantonioid** [comment]
Correcto, puedes verlo así. Insisto que no es exclusivo de FRIDA. en el ticket #83 te menciono referencias de otro proveedor de RPA.

@eradgg @victorgamboa - Este ticket en particular cómo va?

**Comment by pabloreitanosofttek** [comment]
Agrego que ayer en clase (doy clases en la UTN-FRBA) hablando de RPA salto que tampoco lo resuelve el de IBM Automation Anywhere… por lo que ya son 3 de los 4 más grandes del mercado... quedaría ver si BlusPrism lo hace... Sobre todo para que siempre que tengamos que vender algo lo sepamos.

**Comment by eradgg** [comment]
Hola @pabloreitanosofttek.
Entonces, este Issue se trata de Citrix, José Pablo nos mandó un correo que dice que avancemos en lo que está Claudio. Sabes si es con Titanium podemos cerrar este ticket?

**Comment by eradgg** [comment]
se trabajará con Citrix, ya que el cliente no maneja conexiones SAP directamente.

**Comment by victorgamboa** [comment]
@pabloreitanosofttek Cuales son esas 3 herramientas?

**Comment by pabloreitanosofttek** [comment]
FRIDA (la número 1), UI Path y Automation Anywhere…  la única que no tenemos información es de Blue Prism
