### ISSUE TITLE
Error Captcha página BCP

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#48]
Falla la resolución del captcha en la página https://www.telecreditobcp.com/tlcnp/
Anteriormente el funcionamiento era el adecuado, pero ahora esta impidiendo la ejecución de más de 3 procesos.
Es de suma urgencia la resolución del problema, lo necesitamos para hoy 06/05

**Comment by gantonioid** [comment]
Las instrucciones funcionan, revisen tal vez si la captura se hace bien o está en la ruta indicada
```
Titanium SolveCAPTCHA C:\Users\gilberto.isida\Downloads\Capture.PNG and save as Solution
Message <<<Solution>>>
Titanium Sleep 5000
```

![image](https://user-images.githubusercontent.com/9600868/57237432-d2233b00-6fec-11e9-8288-79c2e6d9b698.png)

**Comment by gantonioid** [comment]
Pueden adjuntar las líneas que usan que no están funcionando y el log de error?

**Comment by FaustinoLechuga** [comment]
Realice algunas pruebas y funciono todo correctamente, utilice las siguientes instrucciones.

```
Web2 GoTo "https://www.telecreditobcp.com/tlcnp/"
Web2 Sleep 5000
Web2 Custom "CodeTC" code="242610"
Web2 Screenshot in id="kaptchaImage" save as "captcha"
Message <<<captcha>>>
Web2 Sleep 2000
Titanium SolveCAPTCHA <<<captcha>>> and save as code
Message <<<code>>>
Web2 Sleep 2000
Web2 Type "<<<code>>>" in name="kaptcha"
```

**Comment by pabloreitanosofttek** [comment]
¿@MarianelaDuarte  cual es tu comentario? 
¡gracias!

**Comment by MarianelaDuarte** [comment]
Volvimos a ejecutar y el problema se ha solucionado.

**Comment by MarianelaDuarte** [comment]
Buenas tardes:
Volvemos a tener este inconveniente en el día de la fecha, la resolución del captcha esta fallando.
Somos varios los que utilizamos esta página, por favor si pueden chequearlo.
Desde ya muchas gracias.
Necesitad: Urgente.

**Comment by pabloreitanosofttek** [comment]
¿Cual es el problema, el mismo que pasó con el origen del ticket? ¡Gracias!

**Comment by MarianelaDuarte** [comment]
La resolución del captcha no funciona. Se queda esperando hasta que tira error.
Desconocemos qué sucede por detrás.

**Comment by MarianelaDuarte** [comment]
Volvimos  a ejecutar los bots que involucran la resolución del captcha y funcionaron ok. Cierro el issue.
