### ISSUE TITLE
Variable tipo LIST

### ISSUE THREAD

**Issue by MartinJOlmedo** [FridaSupport/TuringSuport#49]
Buenas tardes, tengo un inconveniente al querer enviar por email las variables tipo "list". Lo que quiero hacer es que mande los datos de la variable por email y manda otra cosa.

SCRIPT:
![listascript1](https://user-images.githubusercontent.com/49987311/57254582-06681d00-7028-11e9-9275-6e3ce0e0da60.png)
Fragmento de la parte que no se ve de SendMail:
![listascript2](https://user-images.githubusercontent.com/49987311/57254584-0831e080-7028-11e9-930b-a0c16c71075d.jpg)

LOG:
![listalog1](https://user-images.githubusercontent.com/49987311/57254589-0b2cd100-7028-11e9-9dc9-84af9f70456b.jpg)
Fragmento que no se ve del mail:
![listalog2](https://user-images.githubusercontent.com/49987311/57254593-0cf69480-7028-11e9-810a-ae9693740c9d.png)

LO QUE RECIBO EN EL MAIL:
![listamail](https://user-images.githubusercontent.com/49987311/57254605-11bb4880-7028-11e9-852a-034f647925b7.jpg)

Muchas gracias!

**Comment by gantonioid** [comment]
Hola Martín
Las variables de tipo lista no se pueden desplegar así nada más debido a que son guardadas en FRIDA en un tipo objeto (System.Collections.Generic.List)

Lo que tienes que hacer es usar la función ParseVariable
[http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/ParseVariable](url)

**Comment by JuanISalazarM** [comment]
Se le ha liberado una nueva versión de Turing.

Espero su respuesta.

**Comment by MartinJOlmedo** [comment]
Funcionó con ParseVariable. Muchas gracias!
