### ISSUE TITLE
Foreach no itera sobre strings

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#5]
Se requiere poder recorrer una variable de tipo string por cada caracterer con el foreach

**Comment by FaustinoLechuga** [comment]
Me podras compartir la versión de turing que tieness?

**Comment by FaustinoLechuga** [comment]
Ya estoy trabajando en eso, al parecer es solo cuando busca una variable. si puedes comprateme tu script.

**Comment by FaustinoLechuga** [comment]
Listo, ya funciona el foreach por character en un string, solo espero la confirmacion de que te funciona de la manera correcta

**Comment by charlie632** [comment]
Esto ya se probó? Para poder cerrar este issue.

**Comment by FaustinoLechuga** [comment]
No me han contestado

**Comment by gantonioid** [comment]
@SoledadNunez

**Comment by gantonioid** [comment]
Post pendiente de input ya por varios días. Cierro el issue
