### ISSUE TITLE
Error con SaveAs [Exellium] y GetCurrentDate [MixerReader]

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#50]
Hola, la situación es la siguiente: quiero guardar un archivo de excel con el comando SaveAs. El archivo tiene en su nombre un determinado formato que incluye la fecha de hoy.

Los problemas:

1- El archivo no se guarda, da error.
2- El formato que devuelve GetCurrentDate no es correcto, necesito el formato 07-05-2019 y tengo 07-XX-2019, donde XX en lugar del mes es un número al azar que depende de la ejecución.

Adjunto el código que estoy utilizando y el log.

[Código.txt](https://github.com/FridaSupport/TuringSuport/files/3152433/Codigo.txt)

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3152430/log.txt)

Necesito a más tardar que esté solucionado para este viernes.

Saludos.

**Comment by CesarEmanuelLencina** [comment]
**Actualizo**: El problema del GetCurrentDate se debió a un error de sintaxis mío. El problema del guardado continúa.

[log.txt](https://github.com/FridaSupport/TuringSuport/files/3152516/log.txt)
[Código.txt](https://github.com/FridaSupport/TuringSuport/files/3152519/Codigo.txt)

**Comment by JuanISalazarM** [comment]
Seguro, revisaré el SaveAs para ver el inconveniente.

**Comment by gantonioid** [comment]
por curiosidad... probaste guardarlo como **xlsx**? o quitarle la extensión al nombre del archivo?

**Comment by CesarEmanuelLencina** [comment]
Sí, ya lo probé.

[log sin extensión.txt](https://github.com/FridaSupport/TuringSuport/files/3153784/log.sin.extension.txt)
[log con xlsx.txt](https://github.com/FridaSupport/TuringSuport/files/3153785/log.con.xlsx.txt)

**Comment by CesarEmanuelLencina** [comment]
Gracias @JuanISalazarM por solucionar mi problema. 

Por si a otro le pasa lo mismo, no se debe usar SaveAs en carpetas que tengan corchetes.

Pueden cerrar el Issue.

**Comment by pabloreitanosofttek** [comment]
Antes de cerrarlo porfa agregarlo al _reader_ así todos lo saben.
¡gracias!
