### ISSUE TITLE
Archivo csv no toma formato de fecha ni filtro aplicados

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#51]
Buenos Días, 

Estamos intentando procesar un archivo csv separado por el carácter (;) la carga ya se realiza de forma correcta, ahora el inconveniente que se presenta es que a pesar de aplicar el formato de fecha a la columna correspondiente, al intentar aplicar un filtro de fecha, el archivo no lo toma dejando vacía la información del proceso, aunque el log no genera error por esta causa, cuando se intenta guardar o cerrar el archivo al finalizar el proceso, este si genera un error.

Adjunto el archivo que se esta procesando y el Log generado, el filtro que se intenta aplicar es la fecha del día.

Se han realizado pruebas aplicando filtros de la siguiente forma: FechaHoy (Fecha del día en formato dd/MM/yyyy)
Intentos de filtro aplicados:
Excel ApplyFilter to the worksheet consolidadoWs to the column with the index {2} with the criteria "<<<FechaHoy>>>"
Excel ApplyFilter to the worksheet consolidadoWs to the column with the index {2} with the criteria "=<<<FechaHoy>>>"
Fragmento Codificado:

## Apertura archivo Consolidado *****************************************
Excel LoadCSV "<<fileConsolidado>>" separated_by ; as consolidadoWb
Excel LoadWSheet consolidadoWb sheet_index 1 as consolidadoWs
Titanium Sleep = 4000
try
## Aplica Filtro de Fecha igualando la del proceso**************************
Excel LoadWSheet cuadraturaGEOWb sheet_index 2 as cuadraturasGEOWs4
#Apply Date Format (dd/MM/yyyy)*************************************
Excel ApplyFormat from consolidadoWs in_column_index 2 format dd/MM/yyyy
Excel ApplyFilter to the worksheet consolidadoWs to the column with the index {2} with the criteria "=<<<FechaHoy>>>"
Titanium Sleep = 200
## Copia Colunas por rangos (Local,Fecha,Ventas,Recaudo,Avance,Recarga y Monto)**************************
Excel CopyRange from the worksheet consolidadoWs from the cell {1,1} up to the cell {LastRow,5} to the cell {1,1} from the worksheet cuadraturasGEOWs4
Titanium Sleep = 100
Excel CopyRange from the worksheet consolidadoWs from the cell {1,24} up to the cell {LastRow,24} to the cell {1,6} from the worksheet cuadraturasGEOWs4
Titanium Sleep = 100
Excel CopyRange from the worksheet consolidadoWs from the cell {1,30} up to the cell {LastRow,30} to the cell {1,7} from the worksheet cuadraturasGEOWs4
catch
MathOperation 1 + <<<indexLogRow>>> and save as indexLogRow
Excel Write "Error al procesar el archivo, Consolidado." in hojaLog row <<<indexLogRow>>> and column 3
Excel Write "<<fileConsolidado>>"  in hojaLog row <<<indexLogRow>>> and column 7
end

[consolidado.zip](https://github.com/FridaSupport/TuringSuport/files/3153579/consolidado.zip)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3153581/log.txt)

**Comment by JuanISalazarM** [comment]
Enterado, lo revisaré. Cualquier duda que vaya surgiendo les pregunto.

**Comment by pabloreitanosofttek** [comment]
Hola, ¿En que fecha lo necesitas? ¡Gracias!

**Comment by JulianBustos** [comment]
El filtro o la funcionalidad?, esto es para lo de cargue locales del proyecto Titan SAE.

**Comment by pabloreitanosofttek** [comment]
Cada pedido que hagas debe incluir una fecha de necesidad... porque si los chicos de soporte tienen varios temas abiertos deben saber cual es mas urgente @JulianBustos  

Por otro lado, @JuanISalazarM  necesitamos una fecha de resolución.

**Comment by JuanISalazarM** [comment]
Claro que si.
Para este caso seguramente se requerirá investigación, para ver cual es el problema realmente.
Puede ser desde la manera en que ejecuta la instrucción, o puede ser un error de código, entre otros.
Esperemos que se resuelva para antes del viernes a las 4pm. Cualquier retraso o inconveniente le haré saber.

**Comment by gantonioid** [comment]
@JulianBustos 

1. La columna 2 del CSV ya está en el formato dd/MM/yyyy
2. El CSV no contiene filas con el valor "07/05/2019" en la columna 2 (para aplicar el filtro que quieres, según dice el log)
3. El error que se muestra al final del log te está diciendo que 

> La clave proporcionada no se encontró en el diccionario.

Es decir... le estás diciendo Save a un libro que no existe. Tu instrucción es:

> Excel Close fileConsolidado

Pero nunca en el log aparece evidencia de que cargaras un libro `fileConsolidado`... probablemente te refieres a `consolidadoWb`

**Comment by JulianBustos** [comment]
Buenos Días, me gustaría conocer el estado actual de este caso, en la parte de la aplicación de filtros por el campo fecha al cargar un archivo csv.

**Comment by JuanISalazarM** [comment]
Se están realizando pruebas en la función del formato de fechas.
Dado que esta función ha sido modificada para poder funcionar con este caso.
Se estima que la problemática haya sido resuelto antes de terminar este día.
Gracias por su atención. Tenga un excelente día.

**Comment by pabloreitanosofttek** [comment]
@gantonioid  Necesitamos contar con una fecha real de resolución dado que genera atrasos en SAE-CRUZ VERDE.

¡Gracias! 
Saludos
PR

**Comment by gantonioid** [comment]
@pabloreitanosofttek Se está trabajando en la solución... se asume baja prioridad porque no hay fecha de necesidad.

**Comment by pabloreitanosofttek** [comment]
@gantonioid  ¿Cuál es la fecha de entrega? Te propongo que busques a @JulianBustos  y puedan conversar a ver si existe un workarround así podemos dejarlo como prioridad baja... en caso de no existir, si necesitaremos que levanten la prioridad a Media-Alta dado que tiene fecha de entrega (el bot que utilizará esto) en 2 semanas.

¡gracias!
Saludos,
PR

**Comment by gantonioid** [comment]
@pabloreitanosofttek no puedo más que decir que se atienden los tickets tan rápido como nos es posible. Somos solo cuatro personas acá en México atendiéndolos a ustedes, que además de soporte hacemos muchas otras cosas.

@JulianBustos te lancé una nueva versión para resolver tu problema. La función LoadCSV ahora carga el archivo con el separador ; y le pone Formato de Celdas para que los datos se mantengan en tipo Texto. Así, entonces puedes filtrar como quieres. Te facilito unas líneas de ejemplo para el caso particular.

Es importante mencionar que en la instrucción LoadCSV, ya te cargamos el libro y la hoja (ambas con el mismo nombre que le des... en este ejemplo es "consolidado"
```
Excel LoadCSV "C:\Users\gilberto.isida\Downloads\consolidado.csv" separated_by ; as consolidado
DefineVariable type "string" as "fecha" with the value "01/03/2019"
Excel ApplyFilter to the worksheet consolidado to the column with the index {2} with the criteria "=<<<fecha>>>"
Excel Save consolidado and close
```

**Comment by gantonioid** [comment]
Quedamos pendientes de su respuesta

**Comment by JulianBustos** [comment]
Buenos Días,

En efecto, esto que indicas, era como estaba inicialmente construido el script y no funcionaba, al inicio del ticket, se puede ver la definición que este tenia, Adjunto el código que inicialmente poseía el script

Excel LoadCSV "<<fileConsolidado>>" separated_by ; as consolidadoWb
Excel LoadWSheet consolidadoWb sheet_index 1 as consolidadoWs
GetCurrentDate Date{dd/MM/yyyy es} and save as fechaHoyReal
Excel ApplyFilter to the worksheet consolidadoWs to the column with the index {2} with the criteria "=<<<fechaHoyReal>>>"

La única diferencia con tu ejemplo es que la variable se captura de la fecha del sistema, para realizar el proceso, solo que no se por que al pasar a este medio el contenido de los <<<>>>, queda vacío, me imagino que es por que la pagina del Git los entiende como inyección de código o algo así.

Adjunto imagen, por si arriba no se visualiza correctamente el script.

![image](https://user-images.githubusercontent.com/50154520/57638044-833c4f00-7572-11e9-9983-6dc6e646b737.png)

**Comment by gantonioid** [comment]
Buen día
No entiendo si ya probaste y funciona o tienes error todavía. @JuanISalazarM dará seguimiento

**Comment by JulianBustos** [comment]
Solucionado correctamente, mil gracias.
