### ISSUE TITLE
Consulta VMs

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#52]
Estimados Desarrollo FRIDA. En un cliente activo nos están pidiendo recomendar cuántos bots deberían estar en un servidor, hoy tenemos 30 en backlog. lo que me comentaron es que todos se ejecutan diariamente y en cierre de mes tienen mayor carga. Tenemos alguna medición o recomendación? 

Lo necesitamos para el Viernes 10/05. ¡Gracias!

**Comment by gantonioid** [comment]
Si se va a ejecutar manualmente (una persona "solicita" la ejecución mediante Turing), la recomendación sería cuidar el nivel de acceso que se le está dando a esa persona o máquina, dado que no cualquier persona podrá ejecutar todos los 30 procesos que mencionas. Lo adecuado sería repartir esos 30 en diferentes máquinas para buscar que sea más controlado y seguro el ambiente.

**NOTA**
Lo siguiente aplica para ejecuciones bajo _schedule_: Se recomienda una instancia por cada ejecución que pueda suceder al mismo tiempo que otra. Esto más que una restricción de _poder de cómputo_ es debido a que comparten DLLs.

Si ustedes están seguros de que un proceso es (por ejemplo) 100% SAP y otro 100% web, entonces pueden trabajar sin problemas, pero si alguno utiliza Titanium... la segunda ejecución podría sacar ventanas sobre la ejecución de Titanium y provocar errores.
