### ISSUE TITLE
Seleccionar varias cuentas sin una casilla de check

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#53]
Para el banco BBVA se necesita poder seleccionar varias sodas las cuentas de una grilla para extraerlas, La dificultad se encuentra en que no existe un check. De manera manual se resuelve seleccionando la primera, ctrl + la ultima de la lista, accediendo a esta mediante el scroll.
¿Existe una manera de resolverlo?
Se requiere una respuesta para el día de hoy o de necesitarse desarrollar una solución, una fecha tentativa de implementación
`<select name="listaCuentas" size="4" multiple="" tabindex="1" class="sel" style="height: 60px;">
					
							<option value="0">00110202940100006179&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[0]=0011</script>

							<option value="1">00110218550100015442&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[1]=0011</script>

							<option value="2">00110238300100002404&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[2]=0011</script>

							<option value="3">00110249000100003818&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[3]=0011</script>

							<option value="4">00110274830100021359&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[4]=0011</script>

							<option value="5">00110281380100032529&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[5]=0011</script>

							<option value="6">00110310010100012370&nbsp;USD&nbsp;</option>
						<script language="Javascript">aBancos[6]=0011</script>

							<option value="7">00110310090100007628&nbsp;PEN&nbsp;</option>
						<script language="Javascript">aBancos[7]=0011</script>
......
							<option value="76">00110910790100133900&nbsp;USD&nbsp;</option>
						<script language="Javascript">aBancos[76]=0011</script>

				</select>`

**Comment by pabloreitanosofttek** [comment]
¿Para que fecha lo necesitas @SoledadNunez ?

**Comment by SoledadNunez** [comment]
@pabloreitanosofttek se solicita alguna respuesta para el día de hoy o fecha tentativa de una solución, no tiene fecha de entrega aun el proceso aun.

**Comment by SoledadNunez** [comment]
Hable con Raul, a mas tardar el 10 debería estar la solución a este tema.

**Comment by FaustinoLechuga** [comment]
No me queda claro de que reader es el issue o de en que instrucciones tienes el problema, ¿podrias brindarnos mas información sobre esto?

**Comment by SoledadNunez** [comment]
El reader es el Browpet, no es un a instruccion puntual, se requiere realizar una seleccion multiple de una lista proporcionada por la pagina del banco. 
![BBVA net cash - Google Chrome](https://user-images.githubusercontent.com/25591982/57333338-f9643000-70f2-11e9-97ce-b924e44b15de.jpg)

**Comment by carlosortiz632** [comment]
Se tiene que trabajar en esta funcionalidad dado que no está implementada. Se comienza a trabajr el día de hoy.

**Comment by carlosortiz632** [comment]
@SoledadNunez  Ya se trabajó en poder manejar múltiples selecciones. Te paso el nuevo ejecutable por Teams junto con la sintaxis requerida y un ejemplo. Te pido de favor que lo pruebes durante estos días para poder liberarlo como un nuevo release, así junto con otros cambios que pidió Claudio. 

Cerraré el issue y de ser necesario, que se vuelva a abrir.
Saludos.

**Comment by SoledadNunez** [comment]
Buenos días Carlos, el tema es un poco mas complejo, porque debemos seleccionar todos los valores de esa lista, y no se tienen los valores y estos pueden cambiar en el tiempo. es posible hacerlo? voy a probar la funcionalidad que me pasaste y te comento como me fue para que puedas liberarlo.

**Comment by SoledadNunez** [comment]
Buenas tardes estuve realizando pruebas pero me da error con el nuevo ejecutable:
`8/5/2019 13:23:55 - Hacer scroll a mano hacia el campo de select. : Success
8/5/2019 13:23:55 - Web2 SelectMultiple value="American;Chilean" in selector="#post-291 > div > div.render > select"`: Running
8/5/2019 13:23:55 - {"error":"line_index is not defined in instruction: SelectMultiple value=\"American;Chilean\" in selector=\"#post-291 > div > div.render > select\"`"}
8/5/2019 13:23:55 - Web2 SelectMultiple value="American;Chilean" in selector="#post-291 > div > div.render > select"` : Error
8/5/2019 13:24:00 - Execution ended
`

**Comment by carlosortiz632** [comment]
@FaustinoLechuga Tuvo un error similar pero era por unos espacios en blanco al copiar y pegar la instrucción. Nos ayudas, Tino?

**Comment by SoledadNunez** [comment]
Si queres para asegurarnos de que no sea algo de eso, quere mandarme un mail con un txt adjunto?

**Comment by FaustinoLechuga** [comment]
Si me paso algo muy parecido al copiar y pegar instrucciones en turing, lo resolvi volviendo a escribir las instrucciones que habia pegado.

**Comment by SoledadNunez** [comment]
El mensaje cambió al reescribir levanto un nuevo TK. o en todo caso abría que reabrirlo, ya que lo que realmente se necesita es seleccionar todos los elementos sin conocer los valores que tenga la lista.
Quedo al pendiente de lo que me indiquen
