### ISSUE TITLE
Correr un bot de forma remota y no asistida

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#54]
Hola!
Necesitamos saber como se puede configurar un Bot de Frida para que se ejecute todos los días a las 7am(hora de Argentina), necesitamos que sea remoto y de forma no asistida.
El id del proceso es 1981085774.

Fecha de resolucion: 07/05/2019

**Comment by gantonioid** [comment]
Esta configuración la haces tú dentro de Turing en la máquina que quieres que se encargue de la ejecución automática dentro del horario que desees.

https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/OneNote.aspx?id=%2Fteams%2FDesarrolloFRIDA%2FSiteAssets%2FDesarrollo%20FRIDA%20Notebook&wd=target%28Llamado%20Turing%20Remoto.one%7C21C7D51F-BC2F-4D07-9E52-BA06E3CEE982%2FEjecuci%C3%B3n%20por%20horario%7C46B5CD76-774C-42B7-B835-AD96880A3510%2F%29
onenote:https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/SiteAssets/Desarrollo%20FRIDA%20Notebook/Llamado%20Turing%20Remoto.one#Ejecución%20por%20horario&section-id={21C7D51F-BC2F-4D07-9E52-BA06E3CEE982}&page-id={46B5CD76-774C-42B7-B835-AD96880A3510}&end
