### ISSUE TITLE
Excel RangeDelete, (Issue #22)

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#55]
Buenas,

Estaria necesitando utilizer esta instruccion para borrar un rango dentro de una planilla excel:
Excel RangeDelete from WSlog in C2:C23

El log me arroja lo siguiente: "Error in rangedelete Instruction was't found"

Por lo que vi esto se habia solucionado liberando una nueva version de Turing.

Por favor necesitaria resolverlo a la brevedad para poder seguir avanzando.
Saludos

**Comment by FaustinoLechuga** [comment]
Lo revisare para que quede resuelto a la brevedad, la fecha tentativa seria para el dia de hoy.

**Comment by FaustinoLechuga** [comment]
Ya te libere la misma version que martin, ya deberia de funcionar, podrias revisarlo?

**Comment by JuanIgnacioBurgos** [comment]
Listo, ya quedo funcionando, muchas gracias!
