### ISSUE TITLE
Selección objeto aplicación en Oracle

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#56]
Buenos Días, Actualmente se esta intentando automatizar un proceso en el que se debe operar una aplicación de usuario en Oracle:

![image](https://user-images.githubusercontent.com/50154520/57386508-1d1e8900-717a-11e9-88a0-e5cc890869e0.png)

El proceso debe seleccionar el Dato "E" de la columna (GL) que se encuentra en la aplicación Oracle, de acuerdo a la fecha del proceso y al valor de la segunda Columna.

![image](https://user-images.githubusercontent.com/50154520/57386605-4fc88180-717a-11e9-9df8-b8fe4b612ea4.png)

Por ejemplo (27/03/2019 - 190).
![image](https://user-images.githubusercontent.com/50154520/57386636-640c7e80-717a-11e9-9193-944cce1bfbb9.png)

Al encontrar la letra "E" en rojo el RPA debe ejecutar una serie de pasos para completar el proceso y así por cada registro que contenga el valor "E" en la columna GL.

Mi pregunta es: Existe alguna forma de programar esta automatización de tal forma que el RPA extraiga los valores que requiere por cada registro que cumpla la condición descrita anteriormente y que no sea solo por la identificación de la letra "E", ya que como se ve en el ejemplo, no solo la columna GL posee este valor y el RPA procesa de forma errónea registros que no deberían ser modificados, ya que una vez realizado los ajustes correspondiente el RPA debe marcar únicamente el Check correspondiente al registro ajustado.

![image](https://user-images.githubusercontent.com/50154520/57386940-0c224780-717b-11e9-8242-ca20db419e32.png)

**Comment by pabloreitanosofttek** [comment]
¿Para cuando lo necesitas?

**Comment by JulianBustos** [comment]
Esto hace parte de los pasos relacionados al ítem (Carga Locales) del proyecto Titan SAE.

**Comment by pablorlmx** [comment]
@pabloreitanosofttek este proceso se debe entregar a UAT el viernes de la próxima semana

**Comment by FaustinoLechuga** [comment]
No tenemos nada en este momento que pueda extraer datos de Oracle. Talvez se pueda solucionar usando titanium pero al parecer el proceso es muy complejo. No hay manera de descargar esa tabla en un excel o un csv?

**Comment by JulianBustos** [comment]
Buenos Días, no señor, ya que el ajuste se debe realizar sobre la misma herramienta del cliente y depende de una serie de filtros que se deben introducir, para realizar los diversos ajustes.

**Comment by FaustinoLechuga** [comment]
Por el momento no hay nada de soporte para oracle, lo unico que se podria utilizar es titanium pero seria demasiado complejo automatizarlo de la manera que me comentaste.

**Comment by gantonioid** [comment]
Se cierra porque no es un problema de FRIDA... el proceso manual es complejo y no tenemos conectores para Oracle. Puede ser un problema de análisis al momento de considerar este proceso como automatizable. 

Titanium tiene buenas capacidades pero limitado a lo que está visible en pantalla... si el usuario no encuentra solución con clicks y teclado, por el momento no podemos resolverlo.
