### ISSUE TITLE
[Consulta] Bot no asistido sin usar Office 365 

### ISSUE THREAD

**Issue by K-MUS** [FridaSupport/TuringSuport#57]
En el hipotético caso en que un cliente no posea Office 365, es posible el hecho de crear un bot no asistido ?

El escenario es que llegue un mail (con formato predefinido) a una casilla, que se extraiga los valores y se dispare un RPA con dichos valores como parámetros.

Existe o ya han habido este tipo de casos ? como se resolvió de ser así ?

**Comment by gantonioid** [comment]
No ha existido pero en dado caso se le podría prestar un mail de Softtek? esto es porque Softron no es autónomo, entonces si lo quieren sin supervisión, Office 365 es nuestra única opción

**Comment by gantonioid** [comment]
@andresCruzF
