### ISSUE TITLE
Tabla Dinámicas

### ISSUE THREAD

**Issue by dsalgadoi2012** [FridaSupport/TuringSuport#58]
Buenos dias, 
tengo entendido que se pueden crear tablas dinámicas, solicito su apoyo con algún ejemplo especifico de ello para poder continuar, dado que en la respuesta que se le dio Julian se exponen 3 funciones pero me gustaría verlo en funcionamiento para poder replicarlo a la funcionalidad en la que estoy trabajando.

Cordialmente,
Daniel Salgado

**Comment by pabloreitanosofttek** [comment]
¿Para que lo necesitas? ¿Para cuando? 
¡gracias!

**Comment by dsalgadoi2012** [comment]
es para las carga locales Proyecto TITAN SAE
en el cual se requiere hacer una comparación mediante el uso de tablas dinámicas una ves se hallan ajustado los datos en un archivo de Excel
Gracias.

**Comment by FaustinoLechuga** [comment]
En Teams en el apartado de Wiki y la sseccion de wiki  donde esta la explicacion de la logica hay un documento de excelium donde hay una pequeña explicacion de como usar las pivot tables. 
Aun no esta terminado pero podrias basarte en ese pequeño ejemplo para crear la tabla dinamica o pivot table. 
Si tienes alguna duda puedes crear un issue y yo lo estare atendiendo.
