### ISSUE TITLE
[Exelium] Necesito obtener la posición de la última fila.

### ISSUE THREAD

**Issue by CesarEmanuelLencina** [FridaSupport/TuringSuport#59]
Hola, necesito saber la posición de la última fila con datos en una hoja de excel. Entiendo que en varias instrucciones de Excelium se utiliza el parámetro LastRow. ¿Existe alguna forma de obtener el valor de este parámetro y guardarlo en una variable?

Necesito una solución para este viernes.

**Comment by FaustinoLechuga** [comment]
No existe pero podríamos ver la manera de crear una función que cumpla con lo que necesites. Me pongo en contacto contigo para informarte si es viable crear una función para esto.

¿Me podrías compartir para que necesitas esta funcionalidad? Para ver alguna otra manera de resolverlo en lo que discutimos si es factible lo que solicitas.

**Comment by CesarEmanuelLencina** [comment]
Tengo una hoja de excel con filtros aplicados. Necesito pegar estos valores en otro excel el cual tiene un formato predeterminado. Gracias a este formato siempre me queda una diferencia entre el último valor pegado y una fila prefijada de la cual ya conozco su posición. 

Necesito el valor de la última fila del primer documento para saber con cuantos registros dispongo y así poder eliminar estas celdas vacías en el segundo documento.

Tuve que hacer un recorrido con foreach donde para cada valor filtrado itere una variable con MathOperation. El problema es que cada vez que ejecuto el proceso toma demasiado tiempo hacer esta iteración y pensaba que si se tuviera el valor de LastRow en alguna variable podía ahorrar tiempo de ejecución.

**Comment by gantonioid** [comment]
Lo pueden ver online para revisar el script? para ver si hay alguna función que se pueda usar tal cual o ajustar para el caso. Iterar y leer/escribir de uno en uno no es adecuado ni siquiera directamente en lenguaje de programación (VBA, C#)

**Comment by CesarEmanuelLencina** [comment]
Cuando quieran lo vemos.

**Comment by JuanISalazarM** [comment]
Buenas tardes. Se le ha liberado una nueva versión de Turing.
Solicito de favor pruebe la función deseada.
La documentación la puede consultar en el siguiente enlace: http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/GetSpecial

Cualquier inconveniente, porfavor háganoslo saber.
Tenga un excelente día.

**Comment by CesarEmanuelLencina** [comment]
Buenos días. Ahora que cuento con la versión 20190510T0900 probé cada una de las funciones que hicieron para resolver mi problema. Por desgracia no funciona ninguna, o quizás estoy poniendo algo mal. Adjunto el log correspondiente a cada una de las instrucciones de la función GetSpecials.

[log - lastCell.txt](https://github.com/FridaSupport/TuringSuport/files/3173290/log.-.lastCell.txt)
[log - lastRow.txt](https://github.com/FridaSupport/TuringSuport/files/3173291/log.-.lastRow.txt)
[log - visibleCellsCount.txt](https://github.com/FridaSupport/TuringSuport/files/3173292/log.-.visibleCellsCount.txt)

**Comment by JuanISalazarM** [comment]
Buenos días. Se le ha actualizado la versión de TuringExpo. Debería funcionar ahora. Espero su respuesta, tenga un excelente día.

**Comment by CesarEmanuelLencina** [comment]
Funcionan las tres instrucciones pero no sobre el filtro aplicado. Digamos que aplicando un filtro en mi hoja de excel me quedan visibles 10 filas de un total 100. Lo que hacen estas instrucciones es contar 100 en lugar de 10.

**Comment by JuanISalazarM** [comment]
Le he liberado una nueva versión de Turing.
Cualquier inconveniente, sineta la libertad de mandarme mensaje por Teams, porfavor.
Gracias por su atención. Tenga un excelente día.

**Comment by JuanISalazarM** [comment]
@CesarEmanuelLencina Favor de notificar si se ha podido resolver o no el issue, porfavor.
Gracias. Tenga un excelente día.

**Comment by CesarEmanuelLencina** [comment]
La función visibleCellsCount funciona correctamente ahora. Tenía un problema el archivo de excel que yo estaba ejecutando. Muchas gracias por resolver mi problema. 

Saludos.
