### ISSUE TITLE
Extraer cadena de caracteres, según contexto

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#6]
Se requiere tomar una cadena de carteres de un sitio web teniendo en cuenta el contexto.
Web2 in Context of dynamic="RECEPCIONADO"
Web2 Extract from selector="td.TRNliebde" and save as NombreArchivoDescarga
Web2 EndContext

**Comment by garceteclaudio** [comment]
La instruccion "Context" no esta documentada en la plataforma.

**Comment by cgarcete** [comment]
Faltaria tambien documentar la instruccion "Context" en la plataforma.

**Comment by charlie632** [comment]
@SoledadNunez parece ser que la función Extract está mal implementada. La forma correcta es:

`Web2 Extract from selector="td.TRNliebde" save as "NombreArchivoDescarga"`

**Comment by charlie632** [comment]
@cgarcete Claro, la documento en un momento y le digo a @FaustinoLechuga  para que me ayude a hacerle deploy a la página de documentación
