### ISSUE TITLE
Turing se cierra automaticamente al tratar de ejecutar un script.

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#60]
Buenas Tardes,

Se intenta ejecutar el Turing en un equipo remoto del cliente en ambiente QA, este inicia correctamente, verificando las actualizaciones disponibles.

![image](https://user-images.githubusercontent.com/50154520/57399087-35040600-7196-11e9-9c60-894718f92d22.png)

Realiza la validación de activación al ser correcta indica la fecha de la versión que se esta ejecutando.

![image](https://user-images.githubusercontent.com/50154520/57399171-59f87900-7196-11e9-8b59-688e8d428e50.png)

Carga el "IDE" mostrando los procesos de automatización disponibles

![image](https://user-images.githubusercontent.com/50154520/57399221-78f70b00-7196-11e9-8697-29a73ae5732c.png)

Permite cargar el Script del proceso que se va a ejecutar.

![image](https://user-images.githubusercontent.com/50154520/57399283-90ce8f00-7196-11e9-8dd0-2482e593f247.png)

Una vez este se verifica se procede a ejecutar el script:

![image](https://user-images.githubusercontent.com/50154520/57399333-a348c880-7196-11e9-8e56-5b0622f5fbc0.png)

Se genera automáticamente el mensaje de error en la ejecución del Turing y este se cierra.

Puedo verificar de alguna forma que los recursos que este necesita para su funcionamiento se encuentran disponibles desde la maquina del cliente?.

se verifican accesos a:

Platform:  https://innotekfilestore.file.core.windows.net:
![image](https://user-images.githubusercontent.com/50154520/57399732-7943d600-7197-11e9-8170-372da514ca7b.png)

Platform:  http://automationplatform.azurewebsites.net
![image](https://user-images.githubusercontent.com/50154520/57399797-a0020c80-7197-11e9-9d3c-a27c6fab75ac.png)

La verificación a la url (Platform:  https://automation-1713b.firebaseio.com) retorna:
![image](https://user-images.githubusercontent.com/50154520/57399858-c3c55280-7197-11e9-8674-c6a4bb541d75.png)

Con lo cual se asume que si hay conectividad dado que solicita iniciar una sesión de la misma forma que lo hace al ejecutarse localmente.

**Comment by FaustinoLechuga** [comment]
Buenas tardes, intenta borrando las carpetas de RememberMeLog y la de Local, cerrando turing y volviendolo a abrir. 

Antes de hacer esto crea un respaldo de estas dos carpetas. Me mantienes al tanto de si esto se resolvio.
![Capture](https://user-images.githubusercontent.com/49701864/57403674-d5aaf380-719f-11e9-8cb4-609025118321.PNG)

**Comment by JulianBustos** [comment]
Buenas Tardes, en efecto, eso soluciono el problema, muchísimas gracias.
