### ISSUE TITLE
Asignación Perfil en Turing

### ISSUE THREAD

**Issue by lbalboni** [FridaSupport/TuringSuport#61]
Hola por favor se podría asignar a rodrigo.dente@softtek.con un perfil inicial como copia del mio para que le aparezcan los procesos que tengo con mi usuario? gracias.

**Comment by gantonioid** [comment]
@lbalboni  Se puede agregar para ver tus scripts y ejecutarlos pero no editarlos, eso quieres?

**Comment by lbalboni** [comment]
Si eso, correcto, gracias

**Comment by gantonioid** [comment]
Ya hice eso que mencioné, debe de poder ver tus áreas... pero no editar tus scripts (eso es normal, sólo hay un creador para cada script)
