### ISSUE TITLE
#Excellia - Se puede escribir en un excel al mismo tiempo que lo estoy recorriendo con un Foreach ? 

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#62]

**Comment by MartinMedinaSTK** [comment]
Ya conseguí escribir en el excel mientras lo recorro con un foreach, durante la ejecución del proceso veo que lo hace, pero una vez que termina no veo los cambios en el archivo. Después del cierre del Foreach tengo el save y close del libro. Que me puede estar faltando?

**Comment by ClaudioRodolfoGarcete** [comment]
@MartinMedinaSTK  proba con el save dentro del foreach y el close afuera

**Comment by MartinMedinaSTK** [comment]
Es lo que estaba por problar, guardar registro por registro...

**Comment by MartinMedinaSTK** [comment]
No funcionó.

**Comment by RickProductivity** [comment]
Y ponerlo dos veces ni te funciona ?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ClaudioRodolfoGarcete** [comment]
Y poniendo 2 veces ? o sea dentro y fuera ?

Yo tengo esto y funciona:

DefineVariable type "number" as "rowExcelAcreedores" with the value "1"
Excel LoadWBook "<<<completePathForAcreedoresExcel>>>" as acreedoresBook
Excel LoadWSheet acreedoresBook sheet "Hoja1" as acreedoresHoja
Excel RemoveRows from the worksheet acreedoresHoja from the index 1 to 100
Excel Save acreedoresBook
##################################################################
##################################################################
for <<<cantidadDeFilasFBL1N>>> times {
DefineVariable type "string" as "AcreedorValue" with the value "EmptyAcreedor"
SAP ReadGridCell wnd[0]/usr/cntlGRID1/shellcont/shell/shellcont[1]/shell Column U_LIFNR Row <<<NumFilaaFBL1N>>> as AcreedorValue
Message "Indice:        <<<NumFilaaFBL1N>>> - Acreedor:      <<<AcreedorValue>>>"
Excel Write "<<<AcreedorValue>>>" in acreedoresHoja row <<<rowExcelAcreedores>>> and column 1
Excel Save acreedoresBook
MathOperation <<<rowExcelAcreedores>>> + 1 and save as rowExcelAcreedores
MathOperation <<<NumFilaaFBL1N>>> + 1 and save as NumFilaaFBL1N
}
Excel Save acreedoresBook and close
SAP CloseTrans

**Comment by MartinMedinaSTK** [comment]
poniendolo dos veces (adentro y afuera) tampoco.
aca esta el script:

#-------------------CRUCE DE ARCHIVOS - V2-------------------------
DefineVariable type "string" as "EnviormentDocumentsPath"
DefineVariable type "string" as "EnviormentDownloadsPath"
DefineVariable type "numer" as "rowPosition" with the value "1"
Powershell EnviormentDocumentsPath.txt
Excel LoadWBook "<<<EnviormentDocumentsPath>>>Excellia\Monit de Retenciones\pruebacruce\RETENCIONES 06.05.2019 SOC 107 2019561649.xlsx" as WBRetenciones
Excel LoadWSheet WBRetenciones sheet_index 1 as WSRetencionesHoja
# -- Inserto columna para los mensajes resultantes del cruce de los archivos ---
Excel InsertCol in WSRetencionesHoja at 18
# -- nombre a la columna con los mensajes del resultado del cruce ---
Excel Write "Resultado Cruce" in WSRetencionesHoja row 1 and column 18
Excel save WBRetenciones
Titanium Sleep 2000
Excel ReadRows from WSRetencionesHoja start_at 2 as Data
# -- Cargo el excel de las pendientes
Excel LoadWBook "<<<EnviormentDocumentsPath>>>Excellia\Monit de Retenciones\pruebacruce\Export107 6 2019561036.xlsx" as WBPendientes
Excel LoadWSheet WBPendientes sheet_index 1 as WSpendientesHoja
Titanium Sleep 2000
Excel ReadRows from WSpendientesHoja start_at 2 as DataP
foreach Reg in Data {
MathOperation <<<rowPosition>>> + 1 and save as rowPosition
DefineVariable type "string" as "NroFacturaRETEN" with the value "<<<Reg[16]>>>"
#-- defino variables para usar en el foreach interno --
DefineVariable type "number" as "CantCoincidenciaFactura" with the value "1"
# -- recorro el excel de la retenciones pendientes -- 
foreach RegPend in DataP {
# -- cargo la factura pendiente --
DefineVariable type "string" as "NroFacturaPEND" with the value "<<<RegPend[9]>>>"
if ("<<<NroFacturaPEND>>>" -eq "<<<NroFacturaRETEN>>>")
#- encontre la factura, incremento contador para ver si hay duplicadas --
MathOperation <<<CantCoincidenciaFactura>>> + 1 and save as CantCoincidenciaFactura
end
}
if ("<<<CantCoincidenciaFactura>>>" -eq "2")
# --- Solo se encontró una coincidencia de la factura
# --- marcar factura ok
Web Navigate to https://www.google.com/
Web Type FACT RETEN: <<<NroFacturaRETEN>>> <<<CantCoincidenciaFactura>>>: factura ok (<<<rowPosition>>>)
Titanium Sleep 3000 
Excel Write "OK" in WSRetencionesHoja row <<<rowPosition>>> and column 18
else
if ("<<<CantCoincidenciaFactura>>>" -gt "2")
# --- se encontraron mas de un registro asociado a la factura (duplicado)
# --- Marcar factura duplicada
Web Navigate to https://www.google.com/
Web Type FACT RETEN: <<<NroFacturaRETEN>>> <<<CantCoincidenciaFactura>>>: factura duplicada (<<<rowPosition>>>)
Titanium Sleep 3000 
Excel Write "Factura Duplicada" in WSRetencionesHoja row <<<rowPosition>>> and column 18
else
# --- la variable tiene el valor por defecto = 1 -- no se encontraron registros asociados a la factura
# --- Marcar factura no encotrada
Web Navigate to https://www.google.com/
Web Type FACT RETEN: <<<NroFacturaRETEN>>> <<<CantCoincidenciaFactura>>>: factura no encontrada (<<<rowPosition>>>)
Titanium Sleep 3000 
Excel Write "Factura NO encontrada" in WSRetencionesHoja row <<<rowPosition>>> and column 18
end
end
Excel save WBRetenciones
}
# -- cierro los Excels
Excel Close WBPendientes
Excel save WBRetenciones
Excel Close WBRetenciones

**Comment by FaustinoLechuga** [comment]
Intenta con esto:
Excel Save WBRetenciones

Las instrucciones de los readers son sensibles a las mayusculas y minusculas.

**Comment by MartinMedinaSTK** [comment]
@FaustinoLechuga  gracias se solucionó con la mayúscula. Cerrado.
