### ISSUE TITLE
ejemplo de uso de ReadValueThatMatch

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#63]
ejemplo de uso de ReadValueThatMatch y como se usa la variable que retorna(System.Collections.Generic.Dictionary`2[System.Int32,System.String])

**Comment by FaustinoLechuga** [comment]
nos puedes compartir tu log y el script porfavor?

**Comment by rrrios** [comment]
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3159136/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3159147/codigo.txt)

**Comment by gantonioid** [comment]
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ReadValueThatMatch](url)
Recuerda que siempre que la variable se refiera a un conjunto de valores, será de tipo lista, así que tienes que iterarla o usar 
`ParseVariable "factura" child "elIndice" and save as "nombreEmisor"`

Referencia de ParseVariable:
[http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/ParseVariable](url)

**Comment by rrrios** [comment]
si tengo el
Excel ReadValueThatMatch in the worksheet ConCopShEnTI at the column {12} maching the value "No disponible" and read the column {1} and save it value as {OBS2}
y después le doy formato con el comando sugerido
Excel ParseVariable "<<<OBS2>>>" and save as "newVarName":

el log que genera es Error in parsevariable Instruction was't found. cual seria la sintaxis correcta para ejecutar la línea
Gracias

**Comment by gantonioid** [comment]
ParesVariable no es de Excel, quítale la palabra Excel del principio.

**Comment by rrrios** [comment]
pero como se puede usar System.Collections.Generic.Dictionary en un foreach?

**Comment by gantonioid** [comment]
@FaustinoLechuga puedes verlo?

**Comment by gantonioid** [comment]
Cómo va esto?

Sugiero que usen un filtro
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter](url)

Según el código de tu script, creo que la instrucción sería:
`ApplyFilter to the worksheet ConCopShEnTI to the column with the index {12} with the criteria "=No disponible" and copy their value on "OBS2"`

OBS2 será lista de listas, y la podrás iterar así:
```
foreach item in OBS2 {
Message <<<item[3]>>>
Titanium Sleep 1500
}
```
En este caso, se está iterando por filas, usando _item_ como apuntador, y en cada pasada se está mostrando la cuarta celda de la fila en turno (es una variable de tipo lista, el {indice empieza en 0)
