### ISSUE TITLE
[Exellia] Web2, error en SelectMultiple

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#64]
SelectMultiple da error al ejecutarse.
Se requiere la solucion para a mas tarar el viernes 10.
> 8/5/2019 17:29:51 - Web2 SelectMultiple Value="American;Chilean" in Selector="#post-291 > div > div.render > select": Running
8/5/2019 17:30:14 - {"error":"Element not found"}
8/5/2019 17:30:14 - Web2 SelectMultiple Value="American;Chilean" in Selector="#post-291 > div > div.render > select" : Error
8/5/2019 17:30:19 - Execution ended

**Comment by FaustinoLechuga** [comment]
¿Podras intentar con esta instruccion? 
Web2 SelectMultiple value="American;Chilean" in selector="#post-291 > div > div.render > select"

Solo le cambie las mayusculas en "value" y en "selector"

La sintaxis es muy parecida a la instrucción de "Select"

**Comment by SoledadNunez** [comment]
ya funciono la instrucción se puede cerrar el issue. Muchas gracias
