### ISSUE TITLE
Seguridad en FRIDA, Virtualización y Gestión de claves

### ISSUE THREAD

**Issue by lbalboni** [FridaSupport/TuringSuport#65]
Preguntas técnicas para una implementación en cliente pharma:

1) Integración de FRIDA con Vault para claves? Esto es mas alla de Active Directory, sino para vault de accesos a múltiples sistemas propios.

2) Experiencias con diferentes virtualizaciones o requerimientos? VMWare, Citrix, etc? Es agnostico FRIDA a ellas o hay casos donde se haya probado que funciona bien y otros donde hay alguna restricción?

**Comment by andresCruz05** [comment]
En cuanto a experiencia con VMWare, Citrix, etc. se trabaja con Titanium que funciona mediante la identificación de los elementos activos en la pantalla del usuario, aplicando algoritmos de OCR para la extracción de información y librerías de visón para robots para encontrar campos y botones. De igual forma como contexto esta es la misma forma en la que AutomationAnywhere interactúa con estos aplicativos ya que cualquier programa corriendo dentro de estos ambientes no se encuentra expuesto e instalar un agente en estos ambientes requiere de un permiso especial que normalmente no se otorga por cuestiones de seguridad, siendo más factible usar tecnologías como Titanium (propio de Softtek) para realizar estas automatizaciones 

En cuanto a Vault revisaremos su documentación para poder contestar tu pregunta de la manera más puntual.

Saludos Lean
