### ISSUE TITLE
foreach en un System.Collections.Generic.Dictionary

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#66]
como se puede hacer un ciclo foreach a una variable System.Collections.Generic.Dictionary System.Collections.Generic.Dictionary

**Comment by gantonioid** [comment]
No se puede por el momento. foreach sólo soporta listas

**Comment by rrrios** [comment]
lo que pasa es que estoy usando la sentencia ReadValueThatMatch, para leer una columna filtrada, haciéndole seguimiento dentro del log , esta obteniendo este valor. basado en eso, entonces cual seria la forma de usar esta sentencia dentro de un ciclo, o si otra sentencia parecida a ReadValueThatMatch que realice lo mismo.

gracias

**Comment by gantonioid** [comment]
Te mandé update (versión 20190510T0144) para poder iterar diccionarios. Se está entendiendo como Diccionario un objeto de tipo (Dictionary<key, value>)
Te comparto entonces las reglas de la iteración en diccionarios:
Tienes que indicar si quieres iterar por _key_ o por _value_, por lo tanto las sintaxis soportadas son únicamente
```
##Iteración por key
foreach key in diccionario {
Message <<<key>>>
Titanium Sleep 1500
}
```
```
##Iteración por value
foreach value in diccionario {
Message <<<value>>>
Titanium Sleep 1500
}
```

Si iteras diccionarios y no nombras key o value al iterador, te marcará error

**Comment by gantonioid** [comment]
Mejora atendida
