### ISSUE TITLE
Turing en Windows Server 2016

### ISSUE THREAD

**Issue by c6j6g7g7** [FridaSupport/TuringSuport#67]
Tengo un problema con el Turing, se instalo en un servidor Windows Server 2016 y mientras se esta con la sesión abierta funciona bien, pero el administrador cierra sesión y al volver a ingresar ya no se esta ejecutando el Turing porque al cerrar sesion lo cierra, cual seria la forma correcta para que se quede ejecutando el Turing? ya que debe ser ejecutado en esa maquina en modo TURN ON EVENT LISTENER  sin tener que estar conectado en la sesión y esperando las solicitudes que le llegan por el API de FRIDA.

Les agradezco me contesten lo antes posible porque el día de mañana se va a ejecutar la primera vez el proceso en ambiente producción.

Gracias.

**Comment by gantonioid** [comment]
No cierres sesión, usa el script ReturnDesktopSessionToConsole para desconectarte del escritorio remoto pero manteniéndo la interfaz gráfica y que Titanium funcione.

**Comment by carlosgiraldo** [comment]
buenos días @gantonioid , ya ejecute el script que me indico en el caso abierto y genero el siguiente error:

query : No session exists for innovationsofttek
At C:\FRIDA\TuringValorem\App\ReturnDesktopSessionToConsole.ps1:3 char:11
+ $output = query session innovationsofttek  | findstr /I "innovationso ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (No session exists for innovationsofttek:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

El problema creo que es porque en el Script esta quemado el usuario innovationsofttek y el usuario con que hice la ejecución se llama Admit, lo que debo hacer es cambiarlo en el script en los tres sitios que sale?

Quedo atento.

`#PowerShell –file $env:userprofile\Desktop\ReturnDesktopSessionToConsole.ps1 > $env:userprofile\Desktop\output.txt

$output = query session innovationsofttek  | findstr /I "innovationsofttek"
# The session id starts at the 38th character and is maximum 9 characters long
$sessionId = $output.Substring(38, 9).Trim() 
#write-host $sessionID
Tscon $sessionId /dest:console 
& "$env:userprofile\Desktop\QRes.exe" /x 1280 /y 1024

 
#write the date and the current sessions so we can see the output when it ran and that it completed successfully 
date 
query session innovationsofttek 
echo OK `

**Comment by gantonioid** [comment]
Claro, el script se tiene que editar para que lo haga con la cuenta de la computadora en la que se quiere correr. Eso lo hace cada uno de ustedes que quiera usarlo
