### ISSUE TITLE
No envia correo con sentencia SendMail 

### ISSUE THREAD

**Issue by c6j6g7g7** [FridaSupport/TuringSuport#68]
Se debe tener algún puerto abierto para que el Turing envie un correo electrónico con la instrucción SendMail? Desde el computador qeu yo utilizo envia los correos pero cuando lo tengo ejecutando en el computador del cliente no me llegan los correos aunque el LOG dice que ejecuto satisfactoriamente el correo.

**Comment by JuanIgnacioBurgos** [comment]
Hola, me esta ocurriendo lo mismo...hasta hoy al medio dia funcionaba correctamente.

**Comment by carlosgiraldo** [comment]
Hola, es verdad lo que dice Juan, ya no envía correos ni siquiera desde mi maquina y en la mañana si lo hacia.

Disculpen que los Issues los cree con mi cuenta personal, no me di cuenta que estaba en ella.

**Comment by gantonioid** [comment]
Los logs del servicio muestran que el envío a correos softtek falla, pero prueben enviar a sus cuentas personales (a mí me llega bien al personal)... puede ser que el servidor de correos de Softtek lo esté filtrando como spam y evitando que nos llegue al inbox... eso es un problema grave pero no de FRIDA como tal...

![image](https://user-images.githubusercontent.com/9600868/57484316-5801e900-726e-11e9-9803-077c7a6a8f7f.png)
