### ISSUE TITLE
Problema con web2 para descargar un archivo se abre nueva ventana

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#69]
En un proceso debo ingresar a https://www.telecreditobcp.com/tlcnp/ y exportar un archivo (los movimientos del día). Cuando se llega al paso de la exportación el navegador abre una ventana adicional(imagen adjunta).No estoy logrando acceder a la misma, intento dar click al selector del botón que necesito pero no puedo, es como que el foco queda en la ventana principal.
En el log se loguea todo como succes:
5/9/2019 5:28:08 PM - Web2 Click in selector=".footerButtons > img:nth-child(1)": Running
5/9/2019 5:28:09 PM - Web2 Click in selector=".footerButtons > img:nth-child(1)" : Success

![2019-05-09 16_39_09-Telecrédito - BCP - Chromium](https://user-images.githubusercontent.com/50331739/57484409-568cec80-727f-11e9-8c90-3e2b81877a0d.png)

Prioridad: Alta.
Fecha de necesidad: 09/05 o 10/05

Gracias.

**Comment by gantonioid** [comment]
Ver issue resuelto #13, si los problemas continúan hacer otro ticket

**Comment by MarianelaDuarte** [comment]
Solucionado! No había visto que ya hubo un problema similar.
Igualmente recomiendo no cerrar los issues sin el ok de quien lo reporto, para evitar tener que crear un nuevo ticket en caso de que no este resuelto, asi es más fácil ver el seguimiento del issue.
Muchas gracias chicos!

**Comment by gantonioid** [comment]
Qué bien que ya está 👍 

Se cerró porque estaba duplicado, la solución era probar la otra instrucción... Si hubieras tenido error con la otra función, habría sido totalmente otro problema, y eso amerita nuevo ticket.
