### ISSUE TITLE
Problemas al ejecutar IF

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#7]
Al llevar un IF al script y ejecutarlo turing envía el siguiente error:
The type initializer for 'system.Management.Automation.PSVersionInfo' threw an exception."

Script: 
DefineVariable type "number" as "incremento" with the value "2"
Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\Cotizacion.xlsx" as WBName
Excel LoadWSheet WBName sheet "Hoja1" as WSName
for 6 times {
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,1} and save its value as {valorCelda1}
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,2} and save its value as {valorCelda2}
Message "<<<valorCelda1>>>"
Titanium Sleep 1000
Message "<<<valorCelda2>>>"
if (<<<valorCelda1>>> -eq "")
Message "Enviar_Mail"
Titanium Sleep 1000
else
Message <<<valorCelda1>>>
Titanium Sleep 1000
end
Titanium Sleep 1000
MathOperation <<<incremento>>> + 1 and save as incremento
}

Log:

18-04-2019 9:53:57 - Execution started
18-04-2019 9:53:57 - DefineVariable type "number" as "incremento" with the value "2": Running
18-04-2019 9:53:57 - MixReader : Se agrego una nueva variable : 
Var Name : incremento
Value : 2
18-04-2019 9:53:57 - DefineVariable type "number" as "incremento" with the value "2" : Success
18-04-2019 9:53:57 - Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\Cotizacion.xlsx" as WBName: Running
18-04-2019 9:53:59 - Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\Cotizacion.xlsx" as WBName : Success
18-04-2019 9:53:59 - Excel LoadWSheet WBName sheet "Hoja1" as WSName: Running
18-04-2019 9:53:59 - Excel LoadWSheet WBName sheet "Hoja1" as WSName : Success
18-04-2019 9:53:59 - Excel ReadCell from the worksheet WSName from the cell {2,1} and save its value as {valorCelda1}: Running
18-04-2019 9:53:59 - Se agrego una nueva variable : 
Var Name : valorCelda1
Value : 1327167.000
18-04-2019 9:53:59 - Excel ReadCell from the worksheet WSName from the cell {2,1} and save its value as {valorCelda1} : Success
18-04-2019 9:53:59 - Excel ReadCell from the worksheet WSName from the cell {2,2} and save its value as {valorCelda2}: Running
18-04-2019 9:53:59 - Se agrego una nueva variable : 
Var Name : valorCelda2
Value : 2
18-04-2019 9:53:59 - Excel ReadCell from the worksheet WSName from the cell {2,2} and save its value as {valorCelda2} : Success
18-04-2019 9:53:59 - Message "1327167.000": Running
18-04-2019 9:54:00 - Message "1327167.000" : Success
18-04-2019 9:54:00 - Titanium Sleep 1000: Running
18-04-2019 9:54:01 - Titanium Sleep 1000 : Success
18-04-2019 9:54:01 - Message "2": Running
18-04-2019 9:54:01 - Message "2" : Success

**Comment by FaustinoLechuga** [comment]
if ("<<>>" -eq "") intenta con esa instruccion

**Comment by victorgamboa** [comment]
Lo cambie y dice 
"The Foreach Structure is not correct"

**Comment by FaustinoLechuga** [comment]
Estas leyendo una variable nula, dejame veo de que manera la puedes comprar

**Comment by victorgamboa** [comment]
Hola, alguna solución?

**Comment by FaustinoLechuga** [comment]
Aun no, espero que hoy ya quede resulto

**Comment by FaustinoLechuga** [comment]
Me podras compratir el documento de tu script?, hubo una confusión por que no puedo ver que variables estas comparando, aprecen de la siguiente manera "<<>>" pero realmente debe aprecer el nombre de la variable en medio.

**Comment by victorgamboa** [comment]
DefineVariable type "number" as "incremento" with the value "14"
Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\SOFIA - Formulario de Solicitud de Cotización - v.1.0 - 11-04-2019.xlsx" as WBName
Excel LoadWSheet WBName sheet "Form Solicitud Cotización" as WSName
for 3 times {
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,2} and save its value as {valorCelda1}
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,3} and save its value as {valorCelda2}
Message "<<<valorCelda1>>>"
Titanium Sleep 1000
if (<<<valorCelda1>>> -eq "")
Message "Enviar_Mail"
Titanium Sleep 1000
else
Message <<<valorCelda1>>>
Titanium Sleep 1000
end
Message "<<<valorCelda2>>>"
Titanium Sleep 1000
MathOperation <<<incremento>>> + 1 and save as incremento
}

**Comment by victorgamboa** [comment]
Hola, por donde te lo puedo compartir? algún mail?

**Comment by victorgamboa** [comment]
DefineVariable type "number" as "incremento" with the value "14"
Excel LoadWBook "C:\Users\victor.gamboa\Desktop\Sofia - Finning\SOFIA - Formulario de Solicitud de Cotización - v.1.0 - 11-04-2019.xlsx" as WBName
Excel LoadWSheet WBName sheet "Form Solicitud Cotización" as WSName
for 3 times {
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,2} and save its value as {valorCelda1}
Excel ReadCell from the worksheet WSName from the cell {<<<incremento>>>,3} and save its value as {valorCelda2}
Message "<<<valorCelda1>>>"
Titanium Sleep 1000
if (<<<valorCelda1>>> -eq "")
Message "Enviar_Mail"
Titanium Sleep 1000
else
Message <<<valorCelda1>>>
Titanium Sleep 1000
end
Message "<<<valorCelda2>>>"
Titanium Sleep 1000
MathOperation <<<incremento>>> + 1 and save as incremento
}

**Comment by victorgamboa** [comment]
ese es el codigo pero veo que desaparecen algunas palabras...

**Comment by FaustinoLechuga** [comment]
A mi me funciona bien poniendo las comillas en la variable ""

**Comment by victorgamboa** [comment]
ya lo intente y me sigue apareciendo lo mismo...me podrías enviar la forma de como lo hiciste por favor, para comparar...

**Comment by RickProductivity** [comment]
Por que no hacen mejor un skype

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by victorgamboa** [comment]
Como lo puedo buscar por Skype? cual es el nombre...

**Comment by charlie632** [comment]
Siguen teniendo este problema?

**Comment by FaustinoLechuga** [comment]
Si pero es un problema de la version del windows que se esta utilizando, Andres esta viendo esto

**Comment by victorgamboa** [comment]
Hola a todos, el problema era es que tenia el Win7 y no corría el IF correctamente, migraron la maquina a Win10 y funciona bien el IF.
Gracias Faustino por la ayuda y a todos.
