### ISSUE TITLE
Reader para servicios web

### ISSUE THREAD

**Issue by pablorlmx** [FridaSupport/TuringSuport#70]
Estimados. Para el proyecto Sofia acá en Chile nos levantaron que la siguiente fase de desarrollo del BOT implica al menos interactuar con 5 servicios web. Además nos comentaron que requieren para próximos BOTS que están evaluando hacer con nosotros (al rededor de 20) gran parte de ellos requieren interactuar con servicios web y si no hay una forma directa de interactuar la herramienta no les sirve. Entiendo que dentro del roadmap de features de FRIDA está contemplado esto, tenemos claridad de para cuándo será?

**Comment by gantonioid** [comment]
Hola @pablorlmx No mencionas qué tipo de servicios web requieres consumir. Tenemos esta nueva función para servicios REST únicamente. Revisa la documentación para saber si te sirve y nos cuentas.
[http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/REST](url)

**Comment by gantonioid** [comment]
Como nota: fue incluido recientemente en los readers, así que si lo vas a usar avísanos para mandarle update a tu usuario.
