### ISSUE TITLE
[TITAN][Consulta Excel] Filtrar y ordenar Columnas por color

### ISSUE THREAD

**Issue by JuanIgnacioBurgos** [FridaSupport/TuringSuport#71]
Hola buenas, existe la forma de poder filtrar/ordenar una columna por el color del texto en cada celda? 
Es decir que el criterio sea "TextColor:Red" o "BackgroundColor:Red"

Quedo atento, Saludos.

**Comment by FaustinoLechuga** [comment]
Por el momento no existe esta funcionalidad pero voy a revisar si se puede agregar esta funcionalidad a la instrucción.

**Comment by JuanIgnacioBurgos** [comment]
Gracias, sería de mucha utilidad!

**Comment by pabloreitanosofttek** [comment]
¿Para que lo necesitsas @JuanIgnacioBurgos? 

Si no es para algún bot que estás construyendo de SAE, la prioidad es baja.
¡gracias!
Saludos,
PR

**Comment by JuanIgnacioBurgos** [comment]
Si, lo estaria necesitando para uno de los bots de SAE, en una parte del proceso el usuario filtra en una columna aquellas celdas que tienen texto en color rojo para luego copiar unicamente esos campos en otra planilla.
Saludos!

**Comment by JuanIgnacioBurgos** [comment]
@FaustinoLechuga Hola como estas?  pudiste revisarlo?

**Comment by FaustinoLechuga** [comment]
Si, ya estoy avanzando con este tema.

**Comment by FaustinoLechuga** [comment]
Por el momento quedaría  solo la función de filtrado por "cellcolor" y por "fontcolor"

Esta funcion ya casi queda lista pero la de ordenar por color quedaria pendiente.

**Comment by JuanIgnacioBurgos** [comment]
@FaustinoLechuga Perfecto, como seria la syntaxis correcta? ya se puede utilizer esta function?

**Comment by FaustinoLechuga** [comment]
Te acabo de liberar una versión con los cambios y actualice la documentación con esta nueva funcionalidad. http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter

Esta es la sintaxis correcta y solo esta disponible esta funcionalidad en algunos casos del apply filter.
En el criterio de filtrado solo es necesario ingresar el codigo RGB del color que deseas filtrar.
Aqui te mando algunos ejemplos.
ApplyFilter to the worksheet <wsKey> to the column with the index {<ColumnIndex>} by (cellcolor/fontcolor) with the criteria "<R>,<G>,<B>"
ApplyFilter to the worksheet WSExampleName to the column with the index {2} by cellcolor with the criteria "255,255,0"

ApplyFilter to the worksheet <wsKey> to the column with the index {<ColumnIndex>} by (cellcolor/fontcolor) with the criteria "<R>,<G>,<B>" and delete the rows
ApplyFilter to the worksheet WSExampleName to the column with the index {2} by fontcolor with the criteria "255,0,255" and delete the rows

**Comment by JuanIgnacioBurgos** [comment]
Genial, lo voy a estar probando, cualquier cosa vuelvo a comentar, gracias por tu colaboración @FaustinoLechuga !!

**Comment by JuanIgnacioBurgos** [comment]
Buenos dias @FaustinoLechuga el filtrado funciona de manera correcta, unicamente me esta fallando la instruccion cuando le agrego el "and delete the rows" es decir, si hago el filtro sin esta parte final de la instruccion se ejecuta de manera correcta, ahora bien cuando quiero borrar estas filas filtradas el log me tira el siguiente error:

16/5/2019 09:35:51 - Excel ApplyFilter to the worksheet WSpos to the column with the index {5} by fontcolor with the criteria "0,0,0" and delete the rows: Running
16/5/2019 09:35:51 - No se encontraron celdas.
16/5/2019 09:35:51 - Error applying filter. Ex message: No se encontraron celdas.
16/5/2019 09:35:51 - Excel ApplyFilter to the worksheet WSpos to the column with the index {5} by fontcolor with the criteria "0,0,0" and delete the rows : Error
16/5/2019 09:35:52 - Execution ended

<img width="532" alt="2019-05-16 09_35_55-Repositorio4" src="https://user-images.githubusercontent.com/49756974/57854236-2339e880-77be-11e9-9ac9-296070a51b50.png">

PD: estoy intentando filtrar las celdas con texto color negro, para luego eliminarlas.

**Comment by FaustinoLechuga** [comment]
Ok, ya vi que es. El problema es que no existe el color negro en si en el libro, y al querer filtar por eso no encuentra ninguna coincidencia. Esto por que el color negro que esta por default se guarda con el nombre de "Automatic".

Vere la manera de poder filtrar ese tipo de parametro. Les aviso cuando quede listo.

**Comment by JuanIgnacioBurgos** [comment]
En las pruebas que realice pude filtrar el color negro con el codigo "0,0,0" sin problemas, el error se da cuando a la instruccion le agrego la sentencia "and delete the rows" al final, para que las elimine.

**Comment by FaustinoLechuga** [comment]
Listo, ya te libere una nueva versión contemplando este caso.
En tu caso solo se necesitaria poner automatic en el criterio ya que es font color, para el caso que se quieran filtrar celdas sin relleno solo hay que poner nofill en el criterio. Comoquiera la documentación ya esta actualizada en caso de que surja otra duda.

Este ticket se queda abierto como mejora para agregar ver si es posible agregar el sort por color.

**Comment by FaustinoLechuga** [comment]
Aqui te mando un ejemplo que yo utilice y funciono. En caso de haber alguna anomaila infomamelo porfavor.
`Excel ApplyFilter to the worksheet Sheet1 to the column with the index {5} by fontcolor with the criteria "automatic" and delete the rows`

**Comment by JuanIgnacioBurgos** [comment]
Genial, ya con esto puedo seguir avanzando, muchas gracias!

**Comment by pabloreitanosofttek** [comment]
¿Esto fue agregado al reader? Sino, no se puede cerrar hasta que no esté ahí... @JuanIgnacioBurgos  no será el único que utilice esta función. 

¡gracias! 
Slds

**Comment by gantonioid** [comment]
Al resolver para JuanIgnacio queda integrado a la base de código de la plataforma, pero el rollout será paulatino según los usuarios soliciten los cambios. Esto porque evitamos en la medida de lo posible enviar actualizaciones generales.

Por lo tanto cierro el issue, ya que la necesidad fue atendida, aunque sigue en el roadmap la expansión para lo que mencionó @FaustinoLechuga sobre agregar el sort por color.
