### ISSUE TITLE
Datos de analíticos erróneos en FRIDA

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#72]
Por favor su ayuda con lo siguiente, como se ve en las imágenes algunas ejecuciones se fueron con unos tiempos que afectan los datos analíticos, aparte la idea es que hoy salen a producción estos procesos y seria bueno que no se vean las ejecuciones de prueba y de creación del script.

Pueden ayudarme para que se borre el log del analítico de los siguientes procesos:

cadenasbw1772122536

![valorem_monitoreo_01](https://user-images.githubusercontent.com/14879161/57539435-204b7d80-7310-11e9-89a9-b7e128ebd4de.png)

monitoreo301570862

![valorem_monitoreo_02](https://user-images.githubusercontent.com/14879161/57539447-25a8c800-7310-11e9-9588-f91cb479250a.png)

Gracias.

**Comment by FaustinoLechuga** [comment]
No es tan sencillo eliminar las ejecuciones de prueba, lo que recomendamos es que se utilice un proceso de prueba para las pruebas y cuando ya este funcionando se cree un proceso en el que va a estar ejecutándose permanentemente así las ejecuciones de prueba no afectan a los analytics del proceso.

En este caso lo mas sencillo seria crear un nuevo proceso y ese estarlo usando permanentemente para ejecuciones.

**Comment by carlosgiraldo** [comment]
El problema es que estos procesos ya están vinculados a las versión Turing del cliente y como se lanzan por medio de un flujo creado en Microsoft Flow tendría que cambiar varias cosas en el llamado del API y ustedes tendrían que vincularme los nuevos procesos a la cuenta del cliente. Si no hay otra solución por favor confirmarme para hacer los cambios ya que hoy debe quedar en producción. Para la próxima tendré en cuenta la recomendación que me hace. 

gracias

**Comment by FaustinoLechuga** [comment]
Podrias revisar si ya se eliminaron

**Comment by gantonioid** [comment]
Atendido, Analytics de esos dos procesos han sido borrados. Se cierra el ticket.
