### ISSUE TITLE
Ejecucion link menu en navegador Web

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#73]
Buenos Días,

Se esta intentando hacer click  en una de las opciones de un menú dentro de un sitio Web del cliente:

![image](https://user-images.githubusercontent.com/50154520/57538259-a9ad8080-730d-11e9-8535-38e5c8421309.png)

Para posteriormente seleccionar la siguiente opción:

![image](https://user-images.githubusercontent.com/50154520/57538475-1b85ca00-730e-11e9-8c3d-4fb5e91ef723.png)

La instrucción con la que se ha intentado abrir dicho vinculo han sido:

Paso 1:
web2 Click in id="XXCNC_-_CONCIL_MODELO_INTERFAZCarga_Locales_a_Interfaces"

Paso 2:
Aun so se logra identificar como hacer el llamado, pero la opción que se debe cargar es la que tiene como texto (Carga Locales a Interfaces)

El HTM que genera de forma dinámica el sitio del cliente en esta sección es :

[Html_Menu_EBR.txt](https://github.com/FridaSupport/TuringSuport/files/3167235/Html_Menu_EBR.txt)

Quedo atento.

**Comment by JulianBustos** [comment]
Adjunto Fragmento generado por el Log en el llamado del proceso descrito anteriormente

10/05/2019 11:17:23 - Web2 GoTo http://cor4477v.difarma.cl:8000/OA_HTML/AppsLocalLogin.jsp?langCode=ESA&_logoutRedirect=y : Success
10/05/2019 11:17:23 - Web2 Sleep 300: Running
10/05/2019 11:17:27 - Web2 Sleep 300 : Success
10/05/2019 11:17:27 - Web2 InsertValue "SOFRPA01" in name="usernameField": Running
10/05/2019 11:17:27 - Web2 InsertValue "SOFRPA01" in name="usernameField" : Success
10/05/2019 11:17:27 - Web2 InsertValue "rpa12345" in name="passwordField": Running
10/05/2019 11:17:28 - Web2 InsertValue "rpa12345" in name="passwordField" : Success
10/05/2019 11:17:28 - Web2 Key "Enter": Running
10/05/2019 11:17:28 - Web2 Key "Enter" : Success
10/05/2019 11:17:28 - Web2 Sleep 300: Running
10/05/2019 11:17:32 - Web2 Sleep 300 : Success
10/05/2019 11:17:32 - web2 Click in id="XXCNC_-_CONCIL_MODELO_INTERFAZCarga_Locales_a_Interfaces": Running
10-05-2019 11:17:53 - {"error":"Element not found"}
10/05/2019 11:17:53 - web2 Click in id="XXCNC_-_CONCIL_MODELO_INTERFAZCarga_Locales_a_Interfaces" : Error

**Comment by carlosortiz632** [comment]
Hola, podríamos probar usando el atributo dynamic. Podrías intentar esta instrucción?

Para abrir primero la "carpeta"
```
Web2 Click in dynamic="XXCNC - CONCIL MODELO INTERFAZ"
```

Para el paso 2
```
Web2 Click in dynamic="Carga Locales a Interfaces"
```

**Comment by JulianBustos** [comment]
Si sr, funciono, mil gracias.

**Comment by carlosortiz632** [comment]
@JulianBustos  Qué gusto que funcionó. Quedamos al pendiente. Saludos.
