### ISSUE TITLE
Problemas con función Turn On Event Listener

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#74]
Al utilizar la función Turn On Event Listener se cierra automáticamente y no envía ningún error.

**Comment by victorgamboa** [comment]
Hola, necesito resolver esto hoy

**Comment by pabloreitanosofttek** [comment]
@victorgamboa  subir imágenes o algo más que eso, porque los chicos de México hacen soporte, no magia. 
En caso de no ser posible, propongo que tengas una call con @gantonioid  o @FaustinoLechuga  alguno de los chicos el Lunes a media mañana de Chile (lunes temprano en MX).

¡gracias!
Saludos,
PR

**Comment by gantonioid** [comment]
Información insuficiente, se cierra el ticket
