### ISSUE TITLE
Seleccionar Navegador al ejecutar la instrucción Web2

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#75]
Buenas Tardes,

En el proceso del RPA que actualmente se construye para un cliente, es necesario ejecutar varias aplicaciones mediante el navegador web, por políticas del cliente, ciertas direcciones deben ser ejecutadas sobre el IE y otras en Chrome, me gustaría saber si existe alguna forma de realizar esta tarea utilizando el browpet con la instrucción Web2 GoTo, el navegador por defecto es el IE, sin embargo el Browpet carga siempre el Chrome.

a continuación se muestra el resultado ejecutando el mismo sitio en los navegadores (IE y Chrome)

Sitio ejecutado con IE el cual permite el acceso:

![image](https://user-images.githubusercontent.com/50154520/57548919-cc4c9300-7327-11e9-9ec7-a531fd0e8bbe.png)

Sitio ejecutado en Chrome, retorna un mensaje de instalación de plugins, que ya están en la maquina del cliente pero que por las políticas que posee el no logra cargar correctamente:

![image](https://user-images.githubusercontent.com/50154520/57548944-da9aaf00-7327-11e9-8a17-9c1ac01c0fdc.png)

Hay otro escenario en el cual se debe ingresar por Chrome para que la aplicación del cliente pueda cargar, en este caso funciona correctamente.

**Comment by carlosortiz632** [comment]
Hola, por el momento las dos herramientas de automatización web (Browpet y MagicSelenium) solo soportan Chrome. Hasta ahora, no ha habido soporte para IE y es probable que no haya en un futuro, dado que no existen librerías con mucho soporte para automatizar sobre este mismo.

Si gustas, podemos platicar y ver la manera de hacer que estas páginas carguen en Chrome.

**Comment by JulianBustos** [comment]
Buenas Tardes, mil gracias, por lo pronto se le planteo al cliente si existe la posibilidad de poder ejecutar las app requeridas en Chrome dado que actualmente no deja, una vez tengamos la respuesta de este, en caso de ser necesario, se generara un caso o no dependiendo de lo que este responda.

Mil, gracias.

**Comment by JulianBustos** [comment]
Buenas Tardes, ya el cliente nos confirma lo siguiente:
Las aplicaciones EBS y EBR no están soportados para Google Chrome.  Solo pueden operar desde IE o Mozilla FireFox.

Con esta respuesta presente existe la posibilidad, que Frida las ejecute a demanda, (Chrome/Firefox).

Quedo atento.

**Comment by gantonioid** [comment]
Si no se puede utilizar Chome o Chromium, entonces tendrás que hacer un Custom Local es decir un programa independiente para automatizar utilizando Selenium o alguna otra tecnología por tu cuenta.

Aún así puedes seguir utilizando Turing y la plataforma como orquestador y recolector de analytics.

Se cierra el issue porque la solución es hacer un programa Custom Local
