### ISSUE TITLE
[Excellia] Obtener los valores de una lista como string (MixedReader)

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#76]
Se necesita poder obtener todos los valores de una lista para usarlos en forma de string

```
Excel ReadColumn from the worksheet WSCuentas with the column index {1} and save its value as {cuentas}
Web2` SelectMultiple value="<<<cuentas>>>" in name="listaCuentas"
```

Se probo de las siguientes maneras:
```
DefineVariable type "string" as "Scuentas" with the value "<<<cuentas>>>"

Foreach cuenta in cuentas{
DefineVariable type "string" as "Scuentas" with the value <<<Scuentas>>>;<<<cuenta>>>

Foreach cuenta in cuentas{
DefineVariable type "string" as "Scuentas" with the value "<<<Scuentas>>>;<<<cuenta>>>"

Foreach cuenta in cuentas{
DefineVariable type "string" as "Scuentas" with the value <<<Scuentas>>>";"<<<cuenta>>>
```

¿Existe una manera de hacerlo?

entre las <<<>>> estan los nombre de las variables pero git las borra

**Comment by gantonioid** [comment]
Puedes usar ParseVariable, la cual te da un string, que contiene la lista representada en forma de JSON... si la requieres manipular (cambiar de formato) entonces utiliza aun script de Powershell para ajustarla a tus necesidades.
[http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/ParseVariable](url)

Ejemplo:
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\ejemplo.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
Excel ReadColumn from the worksheet hoja with the column index {1} and save its value as {cuentas}
ParseVariable "cuentas" and save as "cuentasJSON"
Message <<<cuentasJSON>>>
Titanium Sleep 3000
```
Evidencia:
![image](https://user-images.githubusercontent.com/9600868/57559848-725cc500-7349-11e9-8660-a6056ff9f13b.png)

**Comment by SoledadNunez** [comment]
Necesito que se vuelva a abrir el TK,
Cuando ejecuto la instrucción que indican me genera error:

> Excel ReadColumn from the worksheet WSCuentas with the column index {1} and save its value as {cuentas}
> ParseVariable "cuentas" and save as "Stringcuentas"
> Web2 SelectMultiple Value="<<<Stringcuentas>>>" in Selector="#post-291 > div > div.render > select"

Log

> Var Name : cuentas
> Value : American ; Chilean ; Andean flamingo ; Greater flamingo ; James
> 13/5/2019 13:58:20 - Excel ReadColumn from the worksheet WSCuentas with the column index {1} and save its value as {cuentas} : Success
> 13/5/2019 13:58:20 - ParseVariable "cuentas" and save as "Stringcuentas": Running
> 13/5/2019 13:58:20 - Se agrego una nueva variable : 
> Var Name : Stringcuentas
> Value : System.Collections.Generic.List`1[System.Object]
> 13/5/2019 13:58:20 - ParseVariable "cuentas" and save as "Stringcuentas" : Success
> 13/5/2019 13:58:20 - Web2 SelectMultiple Value="System.Collections.Generic.List`1[System.Object]" in Selector="#post-291 > div > div.render > select": Running
> 13/5/2019 13:58:44 - {"error":"Element not found"}
> 13/5/2019 13:58:44 - Web2 SelectMultiple Value="System.Collections.Generic.List`1[System.Object]" in Selector="#post-291 > div > div.render > select" : Error
> 13/5/2019 13:58:50 - Execution ended

**Comment by gantonioid** [comment]
Por las dudas te acabo de enviar una actualización de Turing debe de ser 20190513T0931. Por favor prueba de nuevo y compártenos el valor de **Stringcuentas**

**Comment by pabloreitanosofttek** [comment]
Hola, porfa re-abrir dado que entiendo que no se resolvió la situación. 

¡Gracias! 
Saludos,
PR

**Comment by gantonioid** [comment]
Está abierto Pablo. Le pedimos a Soledad que pruebe y reporte resultados. Aún sin respuesta

**Comment by SoledadNunez** [comment]
Buenos días,
Realice una prueba stringCuenta se carga de la siguiente manera:

```
 Var Name : Stringcuentas
 Value : ["American","Chilean","Andean flamingo","Greater flamingo","James"]
```

Pero falla al ser llamado desde el Selector multiple.
```
Web2 SelectMultiple Value="["American","Chilean","Andean flamingo","Greater flamingo","James"]" in Selector="#post-291 > div > div.render > select": Running
14/5/2019 10:03:13 - {"error":"Lexical Error in line 1 in instruction: SelectMultiple Value=\"[\"American\",\"Chilean\",\"Andean flamingo\",\"Greater flamingo\",\"James\"]\" in Selector=\"#post-291 > div > div.render > select\""}
14/5/2019 10:03:13 - Web2 SelectMultiple Value="["American","Chilean","Andean flamingo","Greater flamingo","James"]" in Selector="#post-291 > div > div.render > select" : Error
```

Recuerdo que esto viene del tk 53 que también fue cerrado sin llegar a aun acuerdo de la solución.

**Comment by gantonioid** [comment]
@carlosortiz632 nos ayudas?

**Comment by carlosortiz632** [comment]
La sintaxis de la función es errónea. La manera de correcta de correr la instrucción `SelectMultiple` es la siguiente:

`Web2 SelectMultiple value="American;Chilean;Andean flamingo;Greater flamingo;James" in selector="#post-291 > div > div.render > select" `


Las opciones deben ir separadas por punto y coma (;) y las palabras reservadas de `value` y `selector` deben ir en minúsculas.

Saludos.

**Comment by SoledadNunez** [comment]
Buenos días Carlos, el tema es como obtengo esa lista en el formato que estas especificando.

Probé mandando una variable de tipo lista que obtengo de un Exel y da error, probé con la función que especificaron mas arriba pero no mantiene el formatos de valor; valor.
Tengo que tomar 77 valores que pueden variar, inicialmente la idea era obtener algo que me permita seleccionar todos los valores de una.

**Comment by gantonioid** [comment]
> Puedes usar ParseVariable, la cual te da un string, que contiene la lista representada en forma de JSON... si la requieres manipular (cambiar de formato) entonces utiliza aun script de Powershell para ajustarla a tus necesidades.

Soledad, como lo dije en mi primera intervención... puedes manipular el formato del string usando Powershell. Según veo sólo tienes que hacerle un replace de los caracteres [ ] "

**Comment by SoledadNunez** [comment]
Si, debo reemplazar las [] " y los ;, pero me parece mal tener que recurrir a poweshell para modificar esa lista siendo que se creo la función para resolver un problema.
Por otro lado yo nunca logre ejecutar custom con mi usuario, veré si me deja ejecutar power

**Comment by gantonioid** [comment]
No es Custom, es RunPowerShell.
[http://automationplatform.azurewebsites.net/Readers/Tools/MixedReader/RunPowerShell](url)

 Además, no tenemos restricciones del lado de la platafroma para ejecutar Customs. Por favor apóyate con alguien de Argentina para revisar que lo estés haciendo de manera correcta.

@pabloreitanosofttek conviene que los compañeros con más experiencia apoyen a los nuevos integrantes. Así intentamos de más maneras antes de llegar al canal de Soporte.

Gracias!

**Comment by SoledadNunez** [comment]
Perdón, pero se consulto entre los compañero antes de recurrir a soporte, ya que esto viene de varios tk mas atrás pero se termino perdiendo el hilo dado que los fueron cerrando.

Me crearon una función nueva y me indicaron que pasara la lista de valores, entiendo que si es nueva podría admitir que se le envie la variable lista y no terminar haciendo una transformacional de la lista a String y ejecutando un powershell, para adecuar el texto al formato que se le definió.

**Comment by pabloreitanosofttek** [comment]
Estimados,
Necesitamos cortar con este "ida y vuelta" sin sentido... propongo usar la misma reunión y ver ambos temas... 

¡Gracias!
Saludos
PR

**Comment by carlosortiz632** [comment]
@SoledadNunez Por el momento no es posible pasarle la lista como tal a la función dado que no se tiene la funcionalidad de parseo de listas. Este desarrollo tomaría bastante tiempo en desarrollar y podría afectar a algunas otras funciones, por lo que no se consideró para esta ocasión, pero sí se tiene planeado para versiones futuras. La opción más rápida, y funcional, sería hacer el reemplazo de la forma de la lista a la que acepta la función.

Quedo al pendiente de cualquier duda o comentario.

**Comment by SoledadNunez** [comment]
Dale, @carlosortiz632, muchas gracias por la info, ya estoy avanzando con el powershell para darle el formato al texto

**Comment by gantonioid** [comment]
Se creó la wiki con un caso de ejemplo de manejo de strings con PowerShell casi idéntico al que requieres @SoledadNunez 

[https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/_layouts/OneNote.aspx?id=%2Fteams%2FDesarrolloFRIDA%2FSiteAssets%2FDesarrollo%20FRIDA%20Notebook&wd=target%28Powershell%20y%20Customs.one%7CBD8098E4-0DE8-43CB-9D8E-C59985399811%2FPowerShell%7C787ED60B-66EF-408F-9F3C-8621521B704F%2F%29
onenote:https://onesofttek.sharepoint.com/teams/DesarrolloFRIDA/SiteAssets/Desarrollo%20FRIDA%20Notebook/Powershell%20y%20Customs.one#PowerShell&section-id={BD8098E4-0DE8-43CB-9D8E-C59985399811}&page-id={787ED60B-66EF-408F-9F3C-8621521B704F}&end](url)

**Comment by SoledadNunez** [comment]
Gracias ya lo miro

**Comment by gantonioid** [comment]
Perfecto Soledad, esperamos el reporte de resultados de la prueba. No debe de requerir muchos cambios de tu parte porque el ejemplo es bastante similar a lo que requieres en cuanto al manejo de strings

**Comment by gantonioid** [comment]
@SoledadNunez @pabloreitanosofttek  Novedades? el script está en el ejemplo que te pasé, ya probaste?

**Comment by SoledadNunez** [comment]
Ya logre hacerlo funcionar se puede cerrar el tk
