### ISSUE TITLE
Instrucciones cadenas, directorios en Frida

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#77]
Buenas Tardes,

Existen actualmente en Frida instrucciones para manejo "manipulación" de datos en variables tipo cadena, es decir validación de directorios, tales como (Replace, MkDir, Direxist, Split), que no se encuentren asociadas exclusivamente a Ecellium

**Comment by gantonioid** [comment]
Tenemos GetEnvironmentPath para obtener rutas dinámicas según el usuario de la computadora, pero todo lo demás que mencionas sería con PowerShell

**Comment by gantonioid** [comment]
Cierro porque no es un problema actual
