### ISSUE TITLE
Tablas Dinamicas

### ISSUE THREAD

**Issue by dsalgadoi2012** [FridaSupport/TuringSuport#78]
Buenas Tardes,

sigo con el proceso sin embargo aun no logro poner los parámetros en los campos de la tabla dinámica requiero poner en Columnas, Filas y Valores, que se podría hacer al respecto?

Cordialmente,
Daniel Salgado.

**Comment by FaustinoLechuga** [comment]
Lo que entiendo es que necesitas usar esta instruccion.
http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/TableField

Si este no es el caso podrias especificarme mas que es lo que necesitas. En caso de existir algun error te pedire que me mandes el log y el script que estas utilizando.

Espero respuesta de esto para continuar dandole seguimiento.

**Comment by pabloreitanosofttek** [comment]
@dsalgadoi2012 ¿Te respondio lo que necesitabsa? 

¡Gracias!

Saludos,
PR

**Comment by dsalgadoi2012** [comment]
Si, Gracias por la respuesta.
