### ISSUE TITLE
Error de conversion en ReadValueThatMatch

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#79]
Buenas tardes
al ejecutar el comando de ReadValueThatMatch en una columna de en valor numérico, se generando una exception de conversion

- No se puede convertir un objeto de tipo 'System.Double' al tipo 'System.String'.

ya que se realizaron pruebas dentro del mismo excel. en columnas de tipo texto y no se presenta el error de conversion.

**Comment by gantonioid** [comment]
Probaste la sugerencia de ApplyFilter?

**Comment by gantonioid** [comment]
#63

**Comment by rrrios** [comment]
si probe el ApplyFilter y después use el read ReadColumn para traer los datos filtrados y el resultado fue que me estaba cargando todos los datos de la columna y no estaba cargando los datos filtrados. y solo se requiere que se extraiga los datos filtrados.

caso que si lo hace  ReadValueThatMatch, pero con valores de texto. con valores numéricos  se presenta la exception.

**Comment by gantonioid** [comment]
Podrías por favor regresar y decirme específicamente la instrucción que probaste en tu script de ApplyFilter?

Si te fijas en el #63 te puse la sintaxis para guardar los valores filtrados en una variable
`ApplyFilter to the worksheet <wsKey> to the column with the index {<ColumnIndex>} with the criteria "<Criteria>" and copy their value on "<SaveVariable>"`

Checa lo importante es la parte de **and copy their value on "variable"**

**Comment by gantonioid** [comment]
Pongo de nuevo la url de referencia
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter](url)

**Comment by rrrios** [comment]
esta es la sentencia y funciona
Excel ApplyFilter to the worksheet ConCopShEnTI to the column with the index {12} with the criteria "No disponible" 

pero se requiere que se le aplique el filtro a una columna,  y ya después de tener todo el excel filtrado , se copea otra columna que son los valores que se van a utilizar, como lo hace el   ReadValueThatMatch

**Comment by gantonioid** [comment]
@rrrios te está faltando `and copy their value on "<SaveVariable>`  !!! Ve la instrucción que te mandé ya en las dos threads. No me has dicho si la usaste ni me has mandado log de error.

**Comment by gantonioid** [comment]
Cierro el issue dado que la solución ya se dio (en dos tickets diferentes) con incluso ejemplos adaptados a la situación presentada.

El usuario no ha reportado errores surgidos del ejemplo brindado y el soporte no puede continuar.

Si el usuario reporta que hay errores _siguiendo el ejemplo indicado_ podemos reabrir el ticket

**Comment by rrrios** [comment]
Buenos días @gantonioid 

se realizo la implementación tal como usted la sugirió. se pudo determinar lo siguiente:

1. en la sentencia ApplyFilter se agrego copy their value on y (presento error  Referencia a objeto no establecida como instancia de un objeto).
 
2. El actual ticket se abrió para la sentencia ReadValueThatMatch  para el error de 
No se puede convertir un objeto de tipo 'System.Double' al tipo 'System.String'. se esta utilizando esta sentencia ya que cumple con lo que se requiere. y esto se basa en la información que esta en http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ReadValueThatMatch 

3. como le había comentado anteriormente la sentencia ApplyFilter  no cumple con lo requerido, ya que se necesita que se filtre por una columna y que se utilice otra columna. se implemento  que primero utilizara ApplyFilter  y después utilizara ReadColumn (esta sentencia funciona). pero tiene la novedad es que trae todos los valores de la columna y solo se necesita los que se 
había filtrado.

se adjunta el log y el código que se realizo.
  
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3173792/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3173824/codigo.txt)

Agradezco por la atención prestada y quedo atento a cualquier comentario
