### ISSUE TITLE
¿Fallo en los if?

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#8]
Estaba haciendo una pruebas muy simples de un script, para comprobar que funcione bien los IF (en algunos casos parece no funcionar)

El script es el siguiente 

DefineVariable type "string" as "num"
DefineVariable type "string" as "tope" with the value "200"
try
for 3 Times {
MathOperation <<<tope>>> - 100 and save as tope
if ("<<<tope>>>" -gt 0)
Message "Todavia hay saldo"
else
#MathOperation 1 / 0 and save as num
end
}
catch
Message " estoy fuera"
end

Al ejecutarlo recibo un cartel que dice " please check the for syntax and that the value given is a number greater than 0" 

La idea es buscar la forma de romper el for para que salga del ciclo, pero en otro script tenia algo similar y la resta podia llegar a numeros negativos aun teniendo un IF que debia comprobar que eso no pase.

pd: no hay log, no hay error, y no encontre como subir una captura.

**Comment by FaustinoLechuga** [comment]
if (<<>> -gt 0)   Podrias intentarlo de esa manera

**Comment by gantonioid** [comment]
Cierro por información insuficiente en la creación del issue y no se ha tenido update
