### ISSUE TITLE
[Excellia] Context funciona de manera erronea (MixedReader )

### ISSUE THREAD

**Issue by SoledadNunez** [FridaSupport/TuringSuport#80]
Se usa context para descargar un registro determinado de la pagina del banco.
Se conoce la extensión del archivo que se acaba de Generar.

>  Web2 in Context of dynamic=".SMM"
> #----#c2 > div.oa.mb10 > table > tbody > tr:nth-child(5) > td:nth-child(3)
> Web2 Extract from selector="td:nth-child(3)" save as "NombreArchivoDescarga"
> #----#c2 > div.oa.mb10 > table > tbody > tr:nth-child(5) > td:nth-child(1) > label > i
> Web2 Click in selector="td:nth-child(1) > label > i"
> Web2 EndContext
> Web2 Click in name="DescargarArchivo"

Context guarda como NombreArchivoDescarga "Archivo"

> > Var Name : NombreArchivoDescarga
> Value : Archivo
Y Selecciona todos los archivos, no el del contexto

En la imagen aparece subrayado el registro a bajar y remarcado sobre donde actua
![BBVA net cash - Google Chrome](https://user-images.githubusercontent.com/25591982/57555500-ccaa5580-734a-11e9-8846-3a229874b394.jpg)

**Comment by carlosortiz632** [comment]
Hola, no entiendo muy bien la pregunta. A qué elemento es al que se le debe dar click? Al checkbox?

**Comment by SoledadNunez** [comment]
Hola Tengo que extraer el nombre del archivo y hacer clic al checkbox de ese archivos.
Esta extrayendo la cabecera de la columna y haciendo clic al "Seleccionar Todos"

**Comment by carlosortiz632** [comment]
Ok. Te puedo pedir un favor? Me podrías mandar por Teams una copia del HTML de esa página? Esto para poder revisar que la función de context y extract se esté utilizando de manera adecuada, y, si no, ver qué es lo que puede estar fallando. 

Muchas gracias

**Comment by pabloreitanosofttek** [comment]
@SoledadNunez  ¿Pudiste enviar el HTML? 
¡Gracias!

Saludos,
PR

**Comment by SoledadNunez** [comment]
@pabloreitanosofttek, lo envie el mismo viernes por teams como lo solicito

**Comment by pabloreitanosofttek** [comment]
OK, @carlosortiz632  porfa confirmar si necesitas algún otro insumo o bien, porfa pasarnos una fecha de resolución.

¡Gracias!
Saludos,
Pr

**Comment by carlosortiz632** [comment]
@pabloreitanosofttek @SoledadNunez Lo revisé en cuanto llegó y dejé un comentario sobre el hilo de Teams, ya que no logré encontrar ningún elemento que se muestra en el screenshot.

**Comment by SoledadNunez** [comment]
Buenos días, ya desbloquearon el usuario, mande las credenciales por team, muchas gracias

**Comment by gantonioid** [comment]
@carlosortiz632
Cómo va este tema?

**Comment by carlosortiz632** [comment]
@gantonioid  volvieron a bloquear el usuario. Por lo que entendí, se levantó un reporte para que no volviese a pasar. De todas maneras, hice un pequeño demo simulando la página que se requiere automatizar y mandé un script de ejemplo. Con eso, en el ambiente correcto, yo creo que debería de funcionar.

**Comment by pabloreitanosofttek** [comment]
¿Debería o estamos seguros? De cara a cliente hay un abismo de diferencia... 

¡Gracias! 
Slds,

**Comment by carlosortiz632** [comment]
@pabloreitanosofttek  Funcionan correctamente en el ambiente de pruebas que cree desde cero. Es un página web donde se simula una tabla parecida a la de la página de BBVA. Cuando se tengan las credenciales desbloqueadas, Soledad, o yo, podemos probar el correcto funcionamiento de las instrucciones.

Saludos.

**Comment by pabloreitanosofttek** [comment]
OK, perfect… antes de cerrarlo aseguremos que es realmente así.

De: carlosortiz632 <notifications@github.com>
Enviado el: viernes, 17 de mayo de 2019 22:11
Para: FridaSupport/TuringSuport <TuringSuport@noreply.github.com>
CC: Pablo Sebastián Reitano <pablo.reitano@softtek.com>; Mention <mention@noreply.github.com>
Asunto: Re: [FridaSupport/TuringSuport] [Excellia] Context funciona de manera erronea (MixedReader ) (#80)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


@pabloreitanosofttek<https://github.com/pabloreitanosofttek> Funcionan correctamente en el ambiente de pruebas que cree desde cero. Es un página web donde se simula una tabla parecida a la de la página de BBVA. Cuando se tengan las credenciales desbloqueadas, Soledad, o yo, podemos probar el correcto funcionamiento de las instrucciones.

Saludos.

**Comment by carlosortiz632** [comment]
@SoledadNunez Tuviste oportunidad de probarlo? Ya pasaron 5 días desde el último update. Cierro el issue, por inactividad.

Puedes volverlo a abrir si lo requieres.

Saludos.

**Comment by SoledadNunez** [comment]
Buenos días Carlos, el usuario aun no desbloqueo las credenciales. sí cerralo y en todo caso abro otro, de ser necesario.
 Muchas gracias

**Comment by SoledadNunez** [comment]
Buenas tardes, ya desbloquearon y cambiaron la contraseña, realice las pruebas pero volvió a fallar seleccionando todas las cuentas y tomando la palabra "Archivo" por el nombre de archivo. Necesitaría que se reabra el issue.

Dados los inconvenientes que hemos tenido con la contraseña, coordinemos para realizar una prueba conjunta para poder mostrarles cual es el funcionamiento erróneo y cual el esperado.

**Comment by pabloreitanosofttek** [comment]
Buenas, este ticket tuvo varios idas y vueltas...… y me gustaría cerrarlo definitivamente... ¿Que falta? 

¡Gracias! 

@SoledadNunez  @carlosortiz632  @gantonioid  @FridaSupport

**Comment by SoledadNunez** [comment]
Buenas tardes, Quedamos con Carlos para hacer una reunión así le muestro cual es el inconveniente, me indico que cuando se desocupara lo veíamos.

**Comment by pabloreitanosofttek** [comment]
Podemos ya ponerle fecha?
Gracias!

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: SoledadNunez <notifications@github.com>
Enviado: martes, mayo 28, 2019 2:57 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Mention
Asunto: Re: [FridaSupport/TuringSuport] [Excellia] Context funciona de manera erronea (MixedReader ) (#80)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Buenas tardes, Quedamos con Carlos para hacer una reunión así le muestro cual es el inconveniente, me indico que cuando se desocupara lo veíamos.
