### ISSUE TITLE
Creacion de una nueva Hoja en Excel

### ISSUE THREAD

**Issue by dsalgadoi2012** [FridaSupport/TuringSuport#81]
Buenas tardes,

Requiero poder crear una nueva hoja en el documento Excel.

Cordialmente,
Daniel Salgado.

**Comment by gantonioid** [comment]
Les suplico que antes de preguntar vean la documentación y hagan pruebas... si hay problemas, entonces ya pregunten.
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/AddWorksheet](url)
