### ISSUE TITLE
Softron

### ISSUE THREAD

**Issue by victorgamboa** [FridaSupport/TuringSuport#82]
Hola necesito ayuda con Softron, necesito empezar a utilizarlo

**Comment by gantonioid** [comment]
Hola
Ya tienes tu script automatizado? puedes empezar con eso... la próxima semana podemos hablar sobre el caso más específico. Puede ser el miércoles a las 10am MEX (GMT-5). Esto no es una limitante dado que puedes hacer el script de automatización.

**Comment by pabloreitanosofttek** [comment]
Cuando se organicen para ver a Softtron, quiero participar porque tengo mil temas abiertos en los cuales podría aplicar.

¡Gracias!

Saludos,
PR

**Comment by gantonioid** [comment]
5 días sin respuesta, cierro el ticket

**Comment by pabloreitanosofttek** [comment]
OK, dado que era para el bot de finning que pasará al equipo de Rick
