### ISSUE TITLE
FRIDA - Ejecución sobre Citrix

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#83]
Buen día,

Relacionado con https://github.com/FridaSupport/TuringSuport/issues/36 necesito que nos comenten casos de ejemplo o bien como podemos resolver la necesidad puntual de Finning. 

Tenemos el caso donde nuestro cliente utiliza SAP desde el virtualizador CITRIX (Es básicamente un escritorio remoto presentado en un browser)... y no sabemos si FRIDA soporta este tipo de interacción... no queremos usar Titanium dado que luego de acceder necesitaremos utilizar SAP y pensábamos en usar el Reader de SAP.

La fecha de necesidad es 14/05 dado que la respuesta asociada a este ticket puede detener el proyecto entero de Finning… por esto, es de MAXIMA prioridad para entender que podemos hacer, como lo hacemos o bien, paramos el proyecto.

¡Gracias!
Saludos,
PR

PD: @RickProductivity  @FridaSupport  @gantonioid  @andresCruzF

**Comment by gantonioid** [comment]
Hola Pablo
Se ha comentado que Citrix solo es automatizable con TItanium, incluso UiPath lo hace con interfaz gráfica (ClickImage, eventos de teclado, etc). Te dejo referencias:
[https://www.uipath.com/es/soluciones/segun-tecnologia/automatizacion-citrix](url)
[https://www.uipath.com/developers/video-tutorials/citrix](url)
