### ISSUE TITLE
FRIDA - control de versiones bots (Consulta)

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#84]
Buen día,
¿Como están?

Les hago una consulta "pavota", ¿como están manejando el caso donde 2 personas trabajando sobre el mismo bot a nivel código? Es decir, ¿como aseguro que lo que construyo yo no se pisa con lo que construye Ricardo?

Quiero asegurar que nada se pierde en etapa de construcción... Si no existe algo "corpo" agrego alguna cosa acá en SSH. 

Priridad: Baja. 
Fecha de necesidad: 20/05

¡Gracias!
Saludos,
PR

**Comment by gantonioid** [comment]
Hola Pablo
La respuesta es sencilla.. no hay más de una persona con derechos de edición sobre el código (script) de automatización. A partir de ahí es cosa de sentido común... no editar el código desde dos máquinas al mismo tiempo, pues si hay dos Turings con tu usuario, ambos tendrían permiso sobre tus scripts y podría pasar lo que tú dices. Pero mientras no lo hagas entonces no hay problema.

**Comment by pabloreitanosofttek** [comment]
Hola, pero no es una respuesta que me sirva... porque si un proceso es grande y quiero achicar tiempos de construcción voy a necesitar personas en paralelo... y quiero saber como aseguran que se pueda hacer esto sin que se pisen... 

¡Gracias!

**Comment by gantonioid** [comment]
Es la única respuesta Pablo. Si quieren paralelizar entonces tienen que pensar en otra opción... ustedes dividan el proceso en dos o tres y luego ustedes integren... en la plataforma un proceso pertenece solo a un usuario, y por consiguiente esta única persona es capaz de editar su código.

**Comment by pabloreitanosofttek** [comment]
OK, gracias...

la última pregunta sobre el tema: está en pipeline que FRIDA lo haga? O nunca se hará?

**Comment by gantonioid** [comment]
Suena prácticamente a un control de versiones tipo GIT, y no está en pipeline.
