### ISSUE TITLE
Reader ERP Oracle

### ISSUE THREAD

**Issue by pablorlmx** [FridaSupport/TuringSuport#85]
Estimados,

En gran parte de los 33 bots que implica el proyecto TITAN se interactúa con el ERP de Oracle. Se podría evaluar como feature agregar un reader para dicho ERP? El cliente detrás del proyecto Titán es de gran importancia en Chile y México y más allá de los 33 bots mencionados para un proyecto de más de un año se consideran ya al menos 1 fase más igual de grande.

@RickProductivity,  @pabloreitanosofttek

**Comment by gantonioid** [comment]
Sabes si hay un conector similar al SAP Scripting para Oracle? porque hacer el reader supondrá un buen tiempo de desarrollo antes de aplicarlo en productivo.
Actualmente sería con Titanium, sugiero **MUCHO** cuidado a la hora de estimar los procesos y pensar en la lógica de solución mediante el script FRIDA antes de considerarlos automatizables

**Comment by gantonioid** [comment]
Se espera input, aunque no está en los planes del futuro cercano empezar un reader de Oracle
