### ISSUE TITLE
MixedReader > REST

### ISSUE THREAD

**Issue by ClaudioRodolfoGarcete** [FridaSupport/TuringSuport#86]
No es posible ejecutar metodos HTTP

Instruccion:
#DELETE url=https:innotek-8f84c.firebaseio.com/REST_TESTS/PUT?auth=XYZ
GET url=https:www.google.com.ar
#GET url=http://localhost:8080/subject

Tambien se probo con el siguiente endpoint:

GET http://localhost:8080/subject 

Ocurre el mismo error que se encuentra en el log.

Log:
5/13/2019 2:40:14 PM - Execution started
5/13/2019 2:40:14 PM - #DELETE url=https:innotek-8f84c.firebaseio.com/REST_TESTS/PUT?auth=XYZ: Running
5/13/2019 2:40:14 PM - DELETE url=https:innotek-8f84c.firebaseio.com/REST_TESTS/PUT?auth=XYZ : Success
5/13/2019 2:40:14 PM - GET url=https:www.google.com.ar: Running
5/13/2019 2:40:14 PM - Error: GET url=https:www.google.com.ar
5/13/2019 2:40:14 PM - Error in get Instruction was't found
5/13/2019 2:40:14 PM - GET url=https:www.google.com.ar : Error
5/13/2019 2:40:14 PM - Execution ended

**Comment by gantonioid** [comment]
Hola Claudio
Intenta por favor iniciar la instrucción con la palabra REST, y también poner las // después de http:.
Gracias, la documentación está equivicada

**Comment by ClaudioRodolfoGarcete** [comment]
Instruccion:
REST GET url=https://www.google.com.ar

Log:
5/13/2019 3:06:07 PM - Execution started
5/13/2019 3:06:07 PM - REST GET url=https://www.google.com.ar: Running
5/13/2019 3:06:07 PM - Error: REST GET url=https://www.google.com.ar
5/13/2019 3:06:07 PM - Error in rest Instruction was't found
5/13/2019 3:06:07 PM - REST GET url=https://www.google.com.ar : Error
5/13/2019 3:06:07 PM - Execution ended

**Comment by gantonioid** [comment]
te voy a poner la misma versión que tengo yo, que ya trae esta función de REST, haz la actualización y me dices si funciona

**Comment by ClaudioRodolfoGarcete** [comment]
Toño, ya funciona con la version que me pasaste.

Corregir la documentacion: La sintaxis correcta del POST es asi: 

REST POST url=http://localhost:8080/subject body { "name" : "holaaaaaaa" }

**Comment by gantonioid** [comment]
Listo, gracias
