### ISSUE TITLE
[TITAN] - Dashboard Cliente

### ISSUE THREAD

**Issue by pabloreitanosofttek** [FridaSupport/TuringSuport#87]
Hola a todos,
¿Como están?

Necesitamos consultar como muestran a sus clientes los tableros de todos los bots… hoy FRIDA a los que desarrollamos nos muestra lo siguiente:

![image](https://user-images.githubusercontent.com/50021922/57645953-dc69aa00-7595-11e9-925f-837a492fd1ee.png)

![image](https://user-images.githubusercontent.com/50021922/57645981-f4412e00-7595-11e9-883a-eb4b88070a99.png)

Y queríamos mostrarle eso a los cliente... ¿Es viable?

¡Gracias! 

Fecha de necesidad: 17/05
Prioridad: Baja

Saludos,
PR

**Comment by gantonioid** [comment]
Hola Pablo
Quieres ver esto? dime para agregarte a ese grupo... no serán tus procesos pero puedes mostrarlo con clientes

**Comment by pabloreitanosofttek** [comment]
La idea es mostrarle a los clientes de Cruz Verde... sus procesos... si con eso puedo resolverlo... Para mi es suficiente. 

@pablorlmx

**Comment by gantonioid** [comment]
Según yo, no se ha liberado ninguno para ese cliente, por lo tanto no hay grupo "Cruz Verde" que contenga analytics.

Requeriría que me pases lo siguiente:

- Cómo quieres que se llame el Grupo
- Qué procesos quieres que agregue al grupo
- Qué usuarios tendrán acceso (mails)

**Comment by pabloreitanosofttek** [comment]
Te pasa la info @pablorlmx … ¡Gracias @gantonioid! 

No sacamos ninguno, pero estamos cerca de hacerlo y tenemos en 3 semanas reunión con el CEO de la compañía y queríamos mostrarlo.

**Comment by gantonioid** [comment]
Sigue pendiente el input

**Comment by pabloreitanosofttek** [comment]
Sip... te los va a pasar @PabloRomero... hoy charlo con él y se lo recuerdo. 

¡Gracias!

**Comment by pablorlmx** [comment]
Les paso:

Cómo quieres que se llame el Grupo: SAE-TITAN
Qué procesos quieres que agregue al grupo: Process ID: 528541555 y 48636426
Qué usuarios tendrán acceso (mails): jose.romero@softtek.com; pablo.reitano@softtek.com; cecilia.real@centralsae.cl; vittorio.solari@centralsae.cl; victor.araneda@difarma.cl

**Comment by gantonioid** [comment]
Solo van a poder entrar personas de softtek, pero ya con estos datos hago el grupo de procesos y tendrán analytics mañana

> On May 14, 2019, at 14:41, Pablo Romero <notifications@github.com> wrote:
> 
> Les paso:
> 
> Cómo quieres que se llame el Grupo: SAE-TITAN
> Qué procesos quieres que agregue al grupo: Process ID: 528541555 y 48636426
> Qué usuarios tendrán acceso (mails): jose.romero@softtek.com; pablo.reitano@softtek.com; cecilia.real@centralsae.cl; vittorio.solari@centralsae.cl; victor.araneda@difarma.cl
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Aviso de confidencialidad y exención - Confidential notice and legal advice 
disclaimer -  
www.udem.edu.mx/disclaimer 
<http://www.udem.edu.mx/disclaimer>

**Comment by pablorlmx** [comment]
Gracias por la ayuda.

Me surge una duda. Una vez en productivo cómo el cliente podrá monitorear el status/resultados/información del bot?

________________________________

**Comment by gantonioid** [comment]
Tú se lo reportarías... solo pueden entrar usuarios softtek a la plataforma

**Comment by pabloreitanosofttek** [comment]
Entonces hubo un tema que no terminamos de poder resolver... ¿Como le muestran a sus clientes PRD los bots? 

La idea es con gente que no es @Softtek... ¡Gracias!

**Comment by gantonioid** [comment]
Ticket atendido, se creó el grupo de procesos para tener tablero de Analytics. de igual forma les comparto el link [http://automationplatform.azurewebsites.net/Home/ChartsMonthly/6322377](url)

¿Cómo lo mostramos a clientes? cuando nos piden verlo tomamos screenshot o iniciamos nuestra sesión.

Próximamente tendremos una manera (portal especializado) en la que podrán compartir analytics. Mientras tanto, es a través de ustedes porque solo pueden entrar usuarios softtek
