### ISSUE TITLE
Consulta con respecto a la instrucción GetAllFiles

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#88]
Buenas tardes, quiero consultar con respecto a la instrucción GetAllFiles, el objeto en donde se debe guardar el/los archivo/s ¿de qué tipo debe ser? ¿ List?, ya que en la documentación no me queda muy claro.
En mi log me figura lo siguiente:
Var Name : FileDowloaded
Value : System.Collections.Generic.List`1[System.String]
probe con tipo list y tipo file
![imagen](https://user-images.githubusercontent.com/50331739/57648704-8e0bd980-759c-11e9-8509-6e397f108e13.png)
Desde ya muchas gracias!

**Comment by gantonioid** [comment]
Hola
Como ves en el log es de tipo lista, con eso puedes iterar de la siguiente manera
```
foreach f in FileDowloaded {
## f va cambiando según la iteración vaya avanzando
Message <<<f>>>
Titanium Sleep 3000
}
```

O si quieres el tercer elemento de la lista de FileDowloaded, puedes hacerlo así (índice en base 0):
`<<<FileDowloaded[2]>>>`

**Comment by gantonioid** [comment]
@MarianelaDuarte  ya probaste? para cerrar el tema

**Comment by MarianelaDuarte** [comment]
Probado!, ya logro acceder al archivo requerido. Saludos
