### ISSUE TITLE
Error de conversion en ReadValueThatMatch referencia del 79

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#89]
Buenos días @gantonioid 

se realizo la implementación tal como usted la sugirió. se pudo determinar lo siguiente:

1. en la sentencia ApplyFilter se agrego copy their value on y (presento error  Referencia a objeto no establecida como instancia de un objeto).
 
2. El actual ticket se abrió para la sentencia ReadValueThatMatch  para el error de 
No se puede convertir un objeto de tipo 'System.Double' al tipo 'System.String'. se esta utilizando esta sentencia ya que cumple con lo que se requiere. y esto se basa en la información que esta en http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ReadValueThatMatch 

3. como le había comentado anteriormente la sentencia ApplyFilter  no cumple con lo requerido, ya que se necesita que se filtre por una columna y que se utilice otra columna. se implemento  que primero utilizara ApplyFilter  y después utilizara ReadColumn (esta sentencia funciona). pero tiene la novedad es que trae todos los valores de la columna y solo se necesita los que se 
había filtrado.

se adjunta el log y el código que se realizo.
  
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3173792/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3173824/codigo.txt)

Agradezco por la atención prestada y quedo atento a cualquier comentario

_Originally posted by @rrrios in https://github.com/FridaSupport/TuringSuport/issues/79#issuecomment-491887631_

**Comment by gantonioid** [comment]
Se envió actualización al usuario (20190513T0800). Usando el archivo Excel adjunto, se realizaron las siguientes pruebas para la necesidad reportada.
![image](https://user-images.githubusercontent.com/9600868/57650388-4da65e80-7590-11e9-9856-e69a788e8d4e.png)


### Filtrado por un valor en columna Tipo (tipo string) y lectura de columna Nombre
Aquí se usó ApplyFilter, que guarda en vars una variable de tipo `List<List<string>>`, por lo tanto al iterarla, cada elemento iterado es de tipo `List<string>`... eso significa que si se desea obtener el valor de la columna C, se debe de sacar con `<<<p[2]>>>`
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\menu.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as menu
Message Se filtran los productos que son Tipo == Pizza
Titanium Sleep 5000
Excel ApplyFilter to the worksheet menu to the column with the index {2} with the criteria "=Pizza" and copy their value on "pizzas"
foreach p in pizzas {
Message <<<p[2]>>>
TItanium Sleep 1500
}
```

### Filtrado por un valor en columna Precio (tipo numérico) y lectura de columna Nombre
Aquí se usó la instrucción ReadValueThatMatch, la cual guarda en vars una variable de tipo `Dictionary<key, value>`, por lo tanto, al iterarla se debe de indicar si queremos iterar por _key_ o por _value_
```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\menu.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as menu
Message Se filtran los productos que tienen Precio == 100
Titanium Sleep 5000
Excel ReadValueThatMatch in the worksheet menu at the column {4} maching the value "100" and read the column {3} and save it value as {seleccion}
foreach value in seleccion {
Message <<<value>>>
TItanium Sleep 1500
}
```

Ver archivo Excel para la referencia
[menu.xlsx](https://github.com/FridaSupport/TuringSuport/files/3174581/menu.xlsx)

**Comment by gantonioid** [comment]
Se revisó en vivo con el usuario y está solucionado

**Comment by carlosgiraldo** [comment]
Buenas Tardes @gantonioid , para poder aplicar el filtro de forma exitosa es necesario tener la versión 20190513T0800?

Estoy probando el código propuesto en este issue y el resultado en el log es el sigueinte:


14/05/2019 01:43:48 p. m. - Execution started
14/05/2019 01:43:48 p. m. - Excel LoadWBook "C:\prueba_frida\menu.xlsx" as libro: Running
14/05/2019 01:43:57 p. m. - Excel LoadWBook "C:\prueba_frida\menu.xlsx" as libro : Success
14/05/2019 01:43:57 p. m. - Excel LoadWSheet libro sheet_index 1 as menu: Running
14/05/2019 01:43:57 p. m. - Excel LoadWSheet libro sheet_index 1 as menu : Success
14/05/2019 01:43:57 p. m. - Message Se filtran los productos que son Tipo == Pizza: Running
14/05/2019 01:43:57 p. m. - Message Se filtran los productos que son Tipo == Pizza : Success
14/05/2019 01:43:57 p. m. - Titanium Sleep 5000: Running
14/05/2019 01:44:02 p. m. - Titanium Sleep 5000 : Success
14/05/2019 01:44:02 p. m. - Excel ApplyFilter to the worksheet menu to the column with the index {2} with the criteria "=Pizza" and copy their value on "pizzas": Running
14/05/2019 01:44:03 p. m. - Se agrego una nueva variable : 
Var Name : pizzas
Value : System.Collections.Generic.List`1[System.Array]
14/05/2019 01:44:03 p. m. - Excel ApplyFilter to the worksheet menu to the column with the index {2} with the criteria "=Pizza" and copy their value on "pizzas" : Success
14/05/2019 01:44:03 p. m. - Message <<<p%2°>>>: Running
14/05/2019 01:44:03 p. m. - Message <<<p%2°>>> : Success
14/05/2019 01:44:03 p. m. - TItanium Sleep 1500: Running
14/05/2019 01:44:04 p. m. - TItanium Sleep 1500 : Success
14/05/2019 01:44:04 p. m. - Message <<<p%2°>>>: Running
14/05/2019 01:44:04 p. m. - Message <<<p%2°>>> : Success
14/05/2019 01:44:04 p. m. - TItanium Sleep 1500: Running
14/05/2019 01:44:06 p. m. - TItanium Sleep 1500 : Success
14/05/2019 01:44:06 p. m. - Message <<<p%2°>>>: Running
14/05/2019 01:44:06 p. m. - Message <<<p%2°>>> : Success
14/05/2019 01:44:06 p. m. - TItanium Sleep 1500: Running
14/05/2019 01:44:08 p. m. - TItanium Sleep 1500 : Success
14/05/2019 01:44:08 p. m. - Message <<<p%2°>>>: Running
14/05/2019 01:44:08 p. m. - Message <<<p%2°>>> : Success
14/05/2019 01:44:08 p. m. - TItanium Sleep 1500: Running
14/05/2019 01:44:09 p. m. - TItanium Sleep 1500 : Success

**Comment by gantonioid** [comment]
> Buenas Tardes @gantonioid , para poder aplicar el filtro de forma exitosa es necesario tener la versión 20190513T0800?

Es correcto @carlosgiraldo ; esa versión o posterior.
Te mandé actualización para que puedas usarla.

Saludos
