### ISSUE TITLE
La instrucción finish del try / catch da error

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#9]
El script:

catch
SendMail with subject "Monitoreo de Detracciones - Error al descargar el archivo de SUNAT" to "<<<xlsNotificarA>>>" with body "Ocurrió un error en la descarga del archivo de detracciones de SUNAT, el proceso no se ha finalizado y deberá ser revisado manualmente. Desde la Sociedad <<<xlsRazonSocial>>> (<<<xlsSociedad>>>) inclusive y en adelante no se han procesado."
finish
end

El log: 
4/18/2019 8:41:34 AM - Web2 Type "xxxxxxxx"sdsd in id="txtContrasena": Running
4/18/2019 8:41:34 AM - {"error":"Lexical Error in line 1 in instruction: Type \"Exce1llia\"sdsd in id=\"txtContrasena\""}
4/18/2019 8:41:34 AM - Web2 Type "xxxxxxxx"sdsd in id="txtContrasena" : Error
4/18/2019 8:41:34 AM - SendMail with subject "Monitoreo de Detracciones - Error al descargar el archivo de SUNAT" to "martin.medina@softtek.com" with body "Ocurrió un error en la descarga del archivo de detracciones de SUNAT, el proceso no se ha finalizado y deberá ser revisado manualmente. Desde la Sociedad Tamarsa (301) inclusive y en adelante no se han procesado.": Running
4/18/2019 8:41:35 AM - SendMail with subject "Monitoreo de Detracciones - Error al descargar el archivo de SUNAT" to "martin.medina@softtek.com" with body "Ocurrió un error en la descarga del archivo de detracciones de SUNAT, el proceso no se ha finalizado y deberá ser revisado manualmente. Desde la Sociedad Tamarsa (301) inclusive y en adelante no se han procesado." : Success
4/18/2019 8:41:35 AM - finish: Running
4/18/2019 8:41:35 AM - finish : Error
4/18/2019 8:41:40 AM - Execution ended
![image](https://user-images.githubusercontent.com/49758327/56370133-13d07b00-61d1-11e9-8d13-f5ea12b6fb3d.png)

**Comment by FaustinoLechuga** [comment]
Puede ser que tengas algun espacio en blanco en tu script y por eso te da el error, me lo podrias compartir para confiormarte?

**Comment by MartinMedinaSTK** [comment]
[monitoreo de detracciones - 23-04-2019.txt](https://github.com/FridaSupport/TuringSuport/files/3109355/monitoreo.de.detracciones.-.23-04-2019.txt)

Te paso el script

**Comment by FaustinoLechuga** [comment]
La idea es que temine el proceso? o que solo marque el error y continue?

**Comment by MartinMedinaSTK** [comment]
La idea es que termine el proceso.

**Comment by FaustinoLechuga** [comment]
Es que la funcion del finish lo que hace es mandar un error para abortar la ejecución por que hubo un error.  Funciona de la manera correcta.

**Comment by MartinMedinaSTK** [comment]
No es lo que dice la documentación:

La lógica del try catch nos permite definir instrucciones que se realizaran únicamente si sucede un  
error en el bloque de instrucciones entre el "try" y "catch". Las instrucciones entre el "end" y el "catch"  
pueden ser ejecutadas y continuar con el script mientras que mediante la palabra "finish" se puede indicar que es un error terminal por lo que después de ejecutar estas instrucciones termine el proceso. 

Si la inclusión de la instrucción finish hace que el proceso termine con un error no tiene mucho sentido utilizarla. Si lo que hace es lanzar un error para cumplir con la función de cortar el proceso (que es lo esperado pero sin terminar con error en una intrucción), estaría bueno que tenga un texto más descriptivo, que no solo diga "Error in Finish", ya que ese mensaje lo da turing cuando realmente se produjo un error inesperado en una instrucción.  ¿Podrían cambiar el mensaje para que se entienda que termina por un error controlado, por ejemplo: "No se puede continuar con la ejecución del proceso por un error controlado", algo similar?

**Comment by gantonioid** [comment]
El finish es como dices, un error terminal... si lo pones, se aborta la ejecución marcando un error. Ese es el comportamiento esperado.

Creo que lo que buscas es un try dentro de ese catch, si anidas las estructuras de manera adecuada, me parece que podrías resolver tu necesidad.

Pequeño ejemplo (funcional)
```
try
algo - esto detona error porque no existe la instrucción "algo"
catch
try
MandarError - esto detona error porque no existe la instrucción "MandarError"
##Si se muestra "No hubo error", entonces la línea anterior no detonó error
Message No hubo error
Titanium Sleep 5000
catch
Message Aquí se atrapa el error que salió de "MandarError"
Titanium Sleep 5000
end
end
```

Con un ciclo (funcional):
```
try
DefineVariable type "int" as "i" with the value "0"
Message <<<i>>>
Titanium Sleep 2000
for 10 times {
If (<<<i>>> -gt 5)
try
MandarError
catch
Message Enviando mail de alerta
Titanium Sleep 2000
InterrumpirCiclo
end
end
Message <<<i>>>
Titanium Sleep 2000
MathOperation <<<i>>> + 1 and save as i
}
catch
Message Se interrumpió en <<<i>>>
end
Titanium Sleep 5000
```

**Comment by pabloreitanosofttek** [comment]
Hola! el issue tiene 11 días de apertura... ¿Cuándo es la fecha de fin? 
¡gracias! 
Saludos,
PR

**Comment by gantonioid** [comment]
Contesté que no es issue, ya que finish significa abortar la ejecución. Estaba esperando algún comentario de Martín por si probó mis scripts de ejemplo. Pero al no haber respuesta, cierro... gracias Pablo

**Comment by gantonioid** [comment]
Mejor sí dejo el tag porque el input no se recibió

**Comment by MartinMedinaSTK** [comment]
Ya esta cerrado este issue. Según lo que me comentaron, es correcto que la instrucción finish termine con ese error. Se está modificando el código para sacar la instrucción "finish" del script, ya que de vista al cliente que el proceso termine con un mensaje "Error in finish" no queda muy bien.
