### ISSUE TITLE
¿Problemas en el scheduled process?

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#90]
Estuve configurando la ejecucion por horario de turing y me encontre con este problema 

![error en win7](https://user-images.githubusercontent.com/32799856/57708196-4e49fe00-763f-11e9-81ae-1c7c114b2098.png)

Luego de configurarlo en el proceso, al ir al boton scheduled process la aplicacion dejaba de funcionar.
Esto pasaba en una de las computadoras de cnp seguros, el turing habia sido descargado desde la pagina ( claramente tambien fue activado), esta pc contaba con windows 7.

Es la primera vez que veo ese error, en computadoras de softtek y con windows 10 ese problema no existe.

pd: hay varios lugares donde esta mal escrito la palabra "scheduled, scheduling".

pd2: ya no tengo acceso a la computadora donde ocurrio este error, solo hago el issue para dejar el registro de lo que paso

**Comment by FaustinoLechuga** [comment]
Muchas gracias, tengo entendido que este error ya se resolvio en las versiones mas recientes de Frida, y es causado por la version del windows que tenga la maquina.

Asignare a @andresCruzF  para que confirme.

**Comment by pabloreitanosofttek** [comment]
Buscaría agregar algunos datos:

- Win7 de 32 o 64? 

- Física o virtual? 

¡Gracias!

**Comment by NehuenV** [comment]
Win7 de 32 o 64? No tengo esa info.

Física o virtual? Fisica, pero estabamos usandola por acceso remoto

**Comment by pabloreitanosofttek** [comment]
Y no la podemos averiguar? Porque es tal vez info importante.

**Comment by andresCruzF** [comment]
Hola @NehuenV el errores se presenta debido a que en background ocupamos comandos de powershell para conocer las tareas que se encuentran programadas en la computadora, dichos comando por el momento únicamente funcionan con la versión del sistema operativo Windows 8 en adelante, así mismo te comento que nos encontramos trabajando en esta mejora para garantizar la compatibilidad de la función de Scheduling con Windows 7.

Saludos.

**Comment by pabloreitanosofttek** [comment]
Decidamos si es algo que nos es útil o no, porque tal vez podemos pedirle a cnp que ponga Windows 8... @Nehuen Verges<mailto:nehuen.verges@softtek.com>  confirma porfa.
Gracias

Saludos,
Pablo Reitano
INNOVATION DELIVERY MANAGER @ SOFTTEK

Obtener Outlook<https://aka.ms/qtex0l> para iOS



________________________________
De: andresCruzF <notifications@github.com>
Enviado: jueves, mayo 16, 2019 9:00 p.m.
Para: FridaSupport/TuringSuport
CC: Pablo Sebastián Reitano; Comment
Asunto: Re: [FridaSupport/TuringSuport] ¿Problemas en el scheduled process? (#90)

EXTERNAL EMAIL: Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hola @NehuenV<https://github.com/NehuenV> el errores se presenta debido a que en background ocupamos comandos de powershell para conocer las tareas que se encuentran programadas en la computadora, dichos comando por el momento únicamente funcionan con la versión del sistema operativo Windows 8 en adelante, así mismo te comento que nos encontramos trabajando en esta mejora para garantizar la compatibilidad de la función de Scheduling con Windows 7.

Saludos.

**Comment by andresCruzF** [comment]
Yo recomiendo que sea Windows 10 el sistema operativo que se instale en esta computadora

**Comment by gantonioid** [comment]
@andresCruzF
Se cierra?

**Comment by pabloreitanosofttek** [comment]
Dejemoslo como mejora pero bajemos la criticidad... no podemos (a veces) pedirle al cliente que cambie su entorno... menos en caso de POCs donde evalua si nos contrata o no. 
A nivel incidente, lo cerraría pero déjenlo en el roadmap (sería bueno que sepa donde está, así puedo ayudar a priorizar temas) pero no como incidente. 

Slds,
