### ISSUE TITLE
No funciona WriteValueThatMatch

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#91]
funcion WriteValueThatMatch, falla, se solicita información para saber si se esta implementando mal la sentencia o si es un error. 

se utiliza WriteValueThatMatch , ya que la sentencia Write solicita la columna y fila, y para este caso solo se tiene la columna y no la fila,  basado en forum en la url : http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/WriteValueThatMatch funcionaria para lo que se requiere.

se agrega los insumos para verificar el caso.

[cuadratura caja y depósitos 27-03.xlsx](https://github.com/FridaSupport/TuringSuport/files/3178859/cuadratura.caja.y.depositos.27-03.xlsx)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3178864/log.txt)
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3178868/codigo.txt)

**Comment by JuanISalazarM** [comment]
Se ha resuelto el issue.
