### ISSUE TITLE
LoadCSV

### ISSUE THREAD

**Issue by NehuenV** [FridaSupport/TuringSuport#92]
Tengo que pasar un archivo txt a excel
Si existe una mejor instruccion para hacerlo no la encontre, pero el punto es, tome el archivo txt y usando un powershell cambie los espacios por comas, despues lo abro usando la instruccion loadCsv.

El resultado es un excel todo corrido 
![mal](https://user-images.githubusercontent.com/32799856/57728481-6d11ba00-766a-11e9-93bb-3de83b2b25a7.png)

Tambien intente imitar la limitacion que usa el excel pero no resulto, pero si lo hago a mano el archivo se pasa bien al excel.
![bien](https://user-images.githubusercontent.com/32799856/57728548-8e72a600-766a-11e9-8689-770b7b17324b.png)

Podrian ayudarme a buscar una solucion para esto?

Necesitaria una respuesta antes del 16.05.19

Archivo:
[NNNFARM00030008.txt](https://github.com/FridaSupport/TuringSuport/files/3179621/NNNFARM00030008.txt)

**Comment by gantonioid** [comment]
@JuanISalazarM Ya se comunicaron?

**Comment by JuanISalazarM** [comment]
Si, ya nos comunicamos por Teams para cualquier situación.

**Comment by JuanISalazarM** [comment]
Se ha resuelto el issue.
