### ISSUE TITLE
No se ejecuto llamados API runprocess FRIDA

### ISSUE THREAD

**Issue by carlosgiraldo** [FridaSupport/TuringSuport#93]
Pueden ayudarme para identificar que paso con 2 procesos que fueron ejecutados via API de FRIDA y que no se ejecutaron en el Turing?

El proceso se ejecuto dos veces como se ve en el historial de Microsoft Flow:

![01](https://user-images.githubusercontent.com/14879161/57738477-4442f200-7675-11e9-891d-97f21d404339.png)

En la imagen anterior se ven las dos ejecuciones de los flujos.

Ahora muestro el detalle de las tareas HTTP realizando el llamado al API runprocess de FRIDA:

cadenasbw1772122536

![04](https://user-images.githubusercontent.com/14879161/57738470-3a20f380-7675-11e9-9ccd-5c76876dc264.png)

![05](https://user-images.githubusercontent.com/14879161/57738474-3c834d80-7675-11e9-8ca0-7afaad84cd48.png)

El segundo proceso fue:

monitoreo301570862

![02](https://user-images.githubusercontent.com/14879161/57738461-33927c00-7675-11e9-886b-3d24ace59e3e.png)

![03](https://user-images.githubusercontent.com/14879161/57738458-2ecdc800-7675-11e9-8c3a-40de28366f1c.png)

Finalmente ingrese a la maquina virtual donde esta instalado Turing y no había ninguna ejecución.

![06](https://user-images.githubusercontent.com/14879161/57738372-c979d700-7674-11e9-9ced-420b25db0378.png)

Yo cerré el Turing, lo volví a ejecutar para dejarlo en modo TURN ON EVENT LISTENER y en ese momento lanzo los procesos que tuve que cancelar porque el cliente me informo que ya había corrido las cadenas manualmente y no se debían ejecutar de nuevo. 
Como información adicional la cadena fallo a las 12:10 p.m de Colombia pero solo pude tener acceso a las maquinas después de las 3:00 p.m.

Quedo atento para saber que ocurrió y ver que puedo hacer para que no suceda de nuevo.

gracias.

**Comment by gantonioid** [comment]
El día de ayer se hizo un _republish_ de la plataforma en la nube y parece que coincide con los horarios que mencionas y se desconectó tu listener... la solución inmediata sería que cuando nosotros le demos mantenimiento a la plataforma, avisaremos por el canal General de Teams para que ustedes vuelvan a conectar el Event Listener.

Como trabajo pendiente, quedaría que Turing se reconectara de manera automática, para que no lo tengan que hacer ustedes de forma manual.

**Comment by carlosgiraldo** [comment]
Gracias por la respuesta.

**Comment by carlosgiraldo** [comment]
Buenas Tardes, de nuevo se realizo llamado a Turing por medio del API de FRIDA para correr procesos pero no se ejecuto el bot, pueden ayudarme a validar si existen procesos pendientes por correr en FRIDA y podrían decirme porque no se dio la ejecución? después de la validación si existen procesos pendientes por ejecución por favor cancelarlos debido a que el cliente ya los realizo de forma manual.

Una ejecución debió darse a las 4.30 a.m de Colombia, otra a alas 9:01 a.m del día de hoy 29/05/2019.


El fin de semana me reportaron dos caídas mas de las cadenas pero de esas no tengo reportes de ejecución desde el flow, si ven algo en la herramienta agradecería me lo reportaran.  


gracias.

quedo atento a su colaboración.
