### ISSUE TITLE
Carga, ejecución y manupulación de datos de Archivo DB Access en Frida  [TITAN] 

### ISSUE THREAD

**Issue by JulianBustos** [FridaSupport/TuringSuport#94]
Buenos Días,

Para el proyecto se requiere abrir un archivo en Access, realizar una carga de datos en las tablas que este contiene, teniendo en cuenta que en caso de existir información previa en las tablas de la DB, esta debe poder eliminarse, para así insertar los valores que se importan desde un archivo de Excel previamente descargado de la plataforma del cliente, una vez hecho esto, se deben ejecutar varios Reportes contenidos en la DB y los resultados deben poder ser seleccionados y copiados para pegarlos en otros archivos de Excel y así dar continuidad al proceso. 

Archivos de Access:
![image](https://user-images.githubusercontent.com/50154520/57784242-346af280-76f5-11e9-941e-36b5706d08a3.png)

![image](https://user-images.githubusercontent.com/50154520/57786795-c07f1900-76f9-11e9-9f5b-dc298c8df5e2.png)

Archivo Insumo de Excel
![image](https://user-images.githubusercontent.com/50154520/57786926-050ab480-76fa-11e9-81bb-8680a9ac427b.png)

Archivo Final

![image](https://user-images.githubusercontent.com/50154520/57787004-32576280-76fa-11e9-8e13-af8a26f2117f.png)

Quedamos Atentos.

**Comment by RickProductivity** [comment]
oye esto es para SAE o para excelia
________________________________

**Comment by JulianBustos** [comment]
Para SAE proyecto  [TITAN] , ya actualice el titulo del asunto como lo solicitaron.

**Comment by gantonioid** [comment]
Hola Julián
No tenemos módulo de interacción directa con Access.
Una solución puede ser que ejecutes la parte de Access con CustomLocal ya que es algo particular de tu proceso: Insertar sin duplicados, ejecutar reportes, y extraer información.

**Comment by JulianBustos** [comment]
Listo, muchas gracias.
