### ISSUE TITLE
Turing se cierra de manera aleatoria desde ayer 14/05

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#95]
Buenos días, desde el día de ayer mi Turing esta inestable, cuando ejecuto procesos se cierra solo. No sigue un patrón como para detectar por qué sucede. Porque ejecute diferentes procesos y sucede lo mismo.Hace bastante no me sucedia, no sé si seré la unica.
Necesidad: Urgente porque nesecito poder ejecutar mis procesos con normalidad. 15.05
Gracias

**Comment by RickProductivity** [comment]
Oye no nos han reportado , ningún problema hiciste algún Update de tu sistema operativo?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MarianelaDuarte** [comment]
No, solo tuve migración de dominio de red. Después ninguna actualización.

**Comment by pabloreitanosofttek** [comment]
@andresCruzF  ¿lo estás viendo vos este tema? 
¡Gracias!

**Comment by pabloreitanosofttek** [comment]
Buen día, porfa darle celeridad dado que se hace imposible trabajar... ¡Gracias!

**Comment by raulpoltiSTK** [comment]
Buen dia, seguimos sin novedades de este ticket? Alguien que nos pueda ayudar con el tema?

**Comment by FaustinoLechuga** [comment]
Hola, buen dia disculpen la demora. El problema aun se sigue presentando en Turing?

**Comment by MarianelaDuarte** [comment]
Buenas tardes, si, me sucede que se cierra cuando se esta ejecutando un proceso, o al terminar, es aleatorio.

**Comment by FaustinoLechuga** [comment]
Puede que esto se deba a que la conexión a internet sea inestable. Favor de verificar esto.

Y otra cosa es que sea que la versión que tienes de turing esta muy desactualizada.

Te mandare un update para ver si de esta forma se soluciona.

**Comment by MarianelaDuarte** [comment]
Por el momento no volví a tener inconvenientes, ya corri varios procesos y el Turing funciona Ok.
Gracias
