### ISSUE TITLE
versión offline de Turing que actualiza las estadísticas de automationplatform

### ISSUE THREAD

**Issue by MartinMedinaSTK** [FridaSupport/TuringSuport#96]
Consulta: Estoy corriendo una versión offline de Turing en el ambiente de un cliente, y veo que, aun cuando la versión es offline, en las analytics de la plataforma se ven las ejecuciones.  Teníamos entendido que al ser offline se perdían las estadísticas de ejecución.  ¿Es correcto este funcionamiento?
   
![turing offline](https://user-images.githubusercontent.com/49758327/57795794-39439c80-771d-11e9-90bf-6d3e42cc042a.png)

**Comment by gantonioid** [comment]
Si realmente es un _Turing offline_, el funcionamiento es que bloqueamos las conexiones que normalmente se hacen a nuestras bases de datos, por lo tanto confirmo que no debe de haber analytics.

**Comment by MartinMedinaSTK** [comment]
![image](https://user-images.githubusercontent.com/49758327/57796556-d9e68c00-771e-11e9-9725-6d3acaebca71.png)

Ese mensaje me dice cuando ejecuto Turing.

**Comment by gantonioid** [comment]
@MartinMedinaSTK me acaban de corregir y te comparto que se actualizó Turing para que siempre intente enviar analytics. De no ser posible la conexión a internet, no afectará el funcionamiento de sus desarrollos.

Por lo tanto, es correcto que veas registros de ejecuciones en el portal de analytics aún si usas un Turing Offline

**Comment by MartinMedinaSTK** [comment]
Ok, y para saber ¿Cuál sería la diferencia entre online y offline?

**Comment by gantonioid** [comment]
La diferencia es todo lo demás que requiere conexión a internet: el usuario, los procesos, scripts, archivos CustomLocal, imágenes de TItanium, etc.  los tiene Turing en local (en vez de descargarlos para cada ejecución). Esto ya era así, solo cambiamos que _si es posible_, se registren anaytics

**Comment by gantonioid** [comment]
@MartinMedinaSTK resuelve tu pregunta?

**Comment by MartinMedinaSTK** [comment]
Si, listo. Cerramos! justo estaba hablando con Andres por otro canal. Gracias!
