### ISSUE TITLE
ReadValueThatMatch consulta con valor diferente

### ISSUE THREAD

**Issue by rrrios** [FridaSupport/TuringSuport#97]
cordial saludo

para la sentencia ReadValueThatMatch, en la parte maching the value() hay alguna forma de que traiga la lista que son diferentes a ese valor. ya que actualmente solo lo hace con el filtro cuando es igual , se probo haciendo las sintaxis que hay en Readcolumn agregando los filtros =,<=,<> y ninguno funciono.

agradezco si hay un ejemplo de como realizar este tipo de consulta.

**Comment by gantonioid** [comment]
Hola
ReadValueThatMatch específicamente es para los que sean iguales a X valor.

Para tu caso, recomiendo ApplyFilter y el criterio para obtener los valores diferentes a X sería "<>X"
`ApplyFilter to the worksheet WSExampleName to the column with the index {2} with the criteria "<>1" and copy their value on "ExcelVariable"`

Puedes ver la documentación en [http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/ApplyFilter](url)

Por favor prueba y confirma para cerrar el ticket

**Comment by rrrios** [comment]
saludos

se atendió la sugerencia escrita en el comentario, la sentencia se ejecuto sin ningún error, pero el resultado no es el esperado.

se adjunta el log y el código para hacer la respectiva verificación.
    
[codigo.txt](https://github.com/FridaSupport/TuringSuport/files/3184120/codigo.txt)
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3184122/log.txt)


agradezco por la atención prestada y quedo atento a cualquier inquietud o sugerencia

**Comment by gantonioid** [comment]
Falta información para saber por qué no es el resultado esperado... qué es lo que quieres hacer?

**Comment by rrrios** [comment]
se probo con el filtro tal y como se puso de ejemplo "<>X" y el resultado fue que no realizo la consulta con el filtro de diferente y lo que que hizo fue retornar un - y un 1 nada mas

**Comment by gantonioid** [comment]
Creo que debemos hablar... te busco en teams

**Comment by gantonioid** [comment]
En el ticket #89 incluyo un ejemplo de ApplyFilter y luego iterando con foreach

Aquí tienes otro ejemplo, utilizando el excel adjunto. El ejemplo toma el Excel, filtra por la columna B aquellos registros que contengan algo DIFERENTE a 4A, posteriormente se itera sobre cada fila resultante de ese query y se despliega en pantalla el valor que cada fila contiene en su columna A, lo cual cubre las necesidades expuestas.
[ejemplo.xlsx](https://github.com/FridaSupport/TuringSuport/files/3184468/ejemplo.xlsx)

```
Excel LoadWBook "C:\Users\gilberto.isida\Downloads\ejemplo.xlsx" as libro
Excel LoadWSheet libro sheet_index 1 as hoja
Excel ApplyFilter to the worksheet hoja to the column with the index {2} with the criteria "<>4A" and copy their value on "Personas"
foreach p in Personas {
Message <<<p[0]>>>
Titanium Sleep 3000
}
SystemNotify Type "Notification" with message "Breakpoint"
```
![image](https://user-images.githubusercontent.com/9600868/57810182-d22de400-772c-11e9-8493-e7a96dba75e1.png)
