### ISSUE TITLE
[EXCELLIA] Proceso finalizado ok, ahora falla.

### ISSUE THREAD

**Issue by MarianelaDuarte** [FridaSupport/TuringSuport#98]
Buenas tardes, tenía un proceso ya finalizado todo ok, hoy lo corro para chequear su buen funcionamiento asi pasarlo a máquina del cliente. Y varias instrucciones de SAP me fallan, estuve desde ayer viendo qué pasa y la verdad que no estoy encontrando la solución:
lo que debe hacer es filtar los registros que aparecen bloqueados (Sémaforo rojo), capturar y enviarlo por email.
![imagen](https://user-images.githubusercontent.com/50331739/57802793-2042e780-772d-11e9-85f3-8065b0de9999.png)
Yo como no podia acceder al sémaforo, hacia click en las celdas y comparaba si el valor de la columna es igual a A, esta bloqueado.
![imagen](https://user-images.githubusercontent.com/50331739/57802952-93e4f480-772d-11e9-8d41-4f26568948e3.png)

Desde antes ya se me hacia dificil trabajar con esa grilla.No sé si cambiaron cosas desde SAP porque el error es que no encuentra ese ID, pero si alguien me puede ayudar seria genial.
Adjunto el log de referencia
Muchas gracias
[log.txt](https://github.com/FridaSupport/TuringSuport/files/3184141/log.txt)
Prioridad Alta: 15.05

**Comment by pabloreitanosofttek** [comment]
@eradgg  porfa pronto soporte, es un proceso listo para subir a PRD de Excellia… me la jugaría que fue un PUMBA que no contempló todo lo que debería. 

¡gracias!

**Comment by pabloreitanosofttek** [comment]
@eradgg  @gantonioid  porfa su ayuda.

Gracias!

**Comment by eradgg** [comment]
Hola @MarianelaDuarte cual es tu proceso? para revisarlo y ver en qué está fallando.

**Comment by MarianelaDuarte** [comment]
Process ID: 1938330039

**Comment by raulpoltiSTK** [comment]
@eradgg @gantonioid Este proceso se encontraba finalizado y listo para implementar, luego de una actualizacion de la plataforma dejo de funcionar, necesitamos que vuelvan para atras los cambios realizados ya que estamos comprometidos con el cliente a entregar este proceso en produccion, del cual ya hicimos demo con la aprobacion del cliente. Necesitamos darle una respuesta al cliente sobre este tema, nos pueden ayudar?

**Comment by gantonioid** [comment]
Yo lo que veo es que marianela.duarte@softtek.com tiene la versión 20190402T1258... eso significa que no ha recibido actualización como están ustedes describiendo.

A nombre de quién está el Turing que ejecuta este proceso? para revisar su versión y si es posible darle rollback.

**Comment by eradgg** [comment]
Hola Estoy checando y no me da error. Gracias.

**Comment by eradgg** [comment]
Esperando script ya que MArianela me dice que lo cambió para que funcione. Necesito el Script original y los archivos necesarios para correrlo.

**Comment by gantonioid** [comment]
Pero ya funciona entonces?

> Esperando script ya que MArianela me dice que lo cambió para que funcione. Necesito el Script original y los archivos necesarios para correrlo.

**Comment by MarianelaDuarte** [comment]
Ahora le voy a enviar a Eder el script original y los archivos necesarios, ya que como tardaron días en revisar mi issue, estuve pensando alternativas al error. Y para probarlo necesitaba modificar el script.
Y no @gantonioid  no funciona todavía, sino hubiera cerrado el issue..

**Comment by gantonioid** [comment]
Bueno, como dije... no fue debido a un update enviado a tu usuario.

**Comment by raulpoltiSTK** [comment]
@gantonioid Pero de la noche a la mañana dejo de funcionar? como explicas eso? si no se realizo ninguna modificacion sobre un Proceso que estaba finalizado y listo para implementar?

**Comment by MarianelaDuarte** [comment]
Envíe por email la información solicitada por Eder, yo en ningun momento confirme que se debia a un Update, solo que cuando ejecute el script previo a ser pasado a la máquina del cliente ya no funcionaba cuando anteriormente dimos por cerrado el proceso funcionando correctamente, con demo incluida.
Y como necesitamos salir a productivo con ese proceso al no recibir respuestas yo hoy modifique el script intentando encontrar la solución, solo eso.

**Comment by eradgg** [comment]
ya tengo los datos. seguiré trabajando.

**Comment by gantonioid** [comment]
> @gantonioid Pero de la noche a la mañana dejo de funcionar? como explicas eso? si no se realizo ninguna modificacion sobre un Proceso que estaba finalizado y listo para implementar?

@raulpoltiSTK 
Mi comentario es únicamente que la información que tenemos es que Marianela está usando una versión del 02 de abril. Por lo tanto, no fue debido a un update reciente de nuestro lado. Ojalá ese dato sirva para el debugging.
![image](https://user-images.githubusercontent.com/9600868/57938377-b130d480-788d-11e9-86f6-3b5240a82515.png)

**Comment by pabloreitanosofttek** [comment]
Basta... ¿lo hablan x teams porfa?

¡Gracias!

**Comment by eradgg** [comment]
No puedo reproducir el script con los datos que me envió Marianela, la instrucción que falla tampoco existe en ese script. voy a cerrar el ticket, ya que Marianela también explica que tiene otra forma de hacerlo.
