### ISSUE TITLE
Turing se cuelga al editar

### ISSUE THREAD

**Issue by jaristimuno** [FridaSupport/TuringSuport#99]
Cada vez que deseo editar el script, cada cambio, por mas minimo que sea toma minutos en realizarse. 

El codigo del script lo hago aparte (en notepad) pero al momento de pegarlo en el editor de Frida, este se queda pensando ya que es muy extenso el codigo.

Se debe esto al apartado de las funciones dentro del editor?

**Comment by pabloreitanosofttek** [comment]
@gantonioid  para mi no es un QnA dado que no es pregunta, es un hecho... se le cuelga el entorno de trabajo.

**Comment by RickProductivity** [comment]
Una pregunta cuantas líneas de código tiene podrías enviarnos el script completo porfa?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pabloreitanosofttek** [comment]
@jaristimuno  porfa subir el script para que lo analicen... pero se que es archi largo (hablamos como de 4k de líneas)

**Comment by gantonioid** [comment]
@jaristimuno te mandé la versión 20190516T0436, que te permite activar/desactivar las sugerencias de autocomplete, que es la razón para que Turing se vuelva lento.

Sería una versión mínima y rápida para solucionar tu problema de momento. Si funciona (nos das tu OK) trabajaremos en volverla oficial y más en forma.

**Comment by jaristimuno** [comment]
Se actualizó. Una vez desmarcada la casilla de "suggestions", se puede editar de manera mas sencilla. En Teams les dejo un zip con el script y un video con la diferencia que hay al tener las sugerencias activadas y al estar desactivadas.

**Comment by pabloreitanosofttek** [comment]
OK, porfa atentos a resolver el tema para todos porque hoy fue a @jaristimuno  pero aplica a todos los RPA Boys. 

¡gracias!
